// Shared grounded-facts pre-pass with a jurisdiction-keyed TTL cache.
//
// Pattern (BuyWise → lease-trap-detector → bill-rescue): one small bounded
// web-search call verifies the volatile facts BEFORE the big main call, which
// stays ungrounded (a single search+long generation held the connection open
// past the API limit). The returned block is appended to the main prompt and
// OVERRIDES training knowledge; empty string on any failure so the tool's
// hedge rules take over. Best-effort by design — never throws.
//
// The cache is what makes this affordable: facts like "the CA deposit cap"
// don't change between requests, so one (topic × jurisdiction) fetch serves
// every user for the TTL window. In-memory only — empties on deploy, first
// user re-warms it. Facts are fetched in ENGLISH regardless of userLanguage
// (the block is prompt input, not user-facing output; the main call renders
// in the user's language) so one cache entry serves all 13 languages.

const fs = require('fs');
const path = require('path');
const { callClaudeWithRetry } = require('./claude');
const { MODELS } = require('./models');

const DAY_MS = 24 * 60 * 60 * 1000;
const FAILURE_TTL_MS = 5 * 60 * 1000; // brief negative-cache so a flaky search isn't hammered
const MAX_ENTRIES = 500;

const cache = new Map();    // key → { block, expires }
const inFlight = new Map(); // key → Promise<string> (dedupes concurrent cold-cache stampedes)

// ── Persistence ─────────────────────────────────────────────────────────────
// The cache being in-memory had a cost that only showed up in production: it
// empties on every deploy, it is not shared between replicas, and the search
// takes ~50s while a plan takes ~12s — so after each deploy a burst of early
// visitors ALL got the unverified fallback, not just the first. Measured on
// 2026-08-11: three consecutive production requests for the same location
// returned 0, 0 and then 3 verified venues.
//
// Two layers fix that, both optional, both fail-open, neither requiring any
// infrastructure to exist:
//
//   1. A committed seed (backend/data/grounded-seed.json), generated by
//      scripts/warm-venue-cache.js and shipped inside the image. Popular
//      locations are warm the instant a new container boots, for free.
//      Seeded entries load ALREADY EXPIRED on purpose: stale-while-revalidate
//      then serves the real venues immediately and refreshes them once in the
//      background, so a seed can never go quietly out of date.
//
//   2. A runtime file at GROUNDED_CACHE_PATH, written after each successful
//      fetch. Point that at a mounted Railway volume and locations learned in
//      production survive the next deploy too. Unset, nothing is written and
//      behaviour is exactly what it was.
const SEED_PATH = path.join(__dirname, '..', 'data', 'grounded-seed.json');
const RUNTIME_PATH = process.env.GROUNDED_CACHE_PATH || '';

function hydrate(file, { expired }) {
  let raw;
  try { raw = fs.readFileSync(file, 'utf8'); } catch { return 0; }
  let parsed;
  try { parsed = JSON.parse(raw); } catch (err) {
    console.error(`[groundedFacts] ${file} is not valid JSON, ignoring:`, err.message);
    return 0;
  }
  let n = 0;
  for (const [key, entry] of Object.entries(parsed || {})) {
    const block = entry && typeof entry.block === 'string' ? entry.block : '';
    if (!block) continue;
    // A runtime entry keeps whatever life it had left; a seed entry is served
    // once and then refreshed.
    const expires = expired ? 0 : Number(entry.expires) || 0;
    if (!expired && expires <= Date.now()) continue;
    cache.set(key, { block, data: entry.data || null, expires });
    n++;
  }
  return n;
}

// Seed first, then the runtime file on top — anything learned in production is
// fresher than anything we shipped.
const seeded = hydrate(SEED_PATH, { expired: true });
const restored = RUNTIME_PATH ? hydrate(RUNTIME_PATH, { expired: false }) : 0;
if (seeded || restored) {
  console.log(`[groundedFacts] warm at boot — ${seeded} seeded, ${restored} restored from ${RUNTIME_PATH || 'nowhere'}`);
}

// Debounced, atomic, best-effort. A cache write must never delay or fail a
// request, and a half-written file must never be readable at boot.
let flushTimer = null;
function scheduleFlush() {
  if (!RUNTIME_PATH || flushTimer) return;
  flushTimer = setTimeout(() => {
    flushTimer = null;
    const out = {};
    for (const [key, v] of cache) if (v.block) out[key] = { block: v.block, data: v.data || null, expires: v.expires };
    const tmp = `${RUNTIME_PATH}.tmp`;
    try {
      fs.mkdirSync(path.dirname(RUNTIME_PATH), { recursive: true });
      fs.writeFileSync(tmp, JSON.stringify(out));
      fs.renameSync(tmp, RUNTIME_PATH);
    } catch (err) {
      console.error('[groundedFacts] could not persist cache:', err.message);
    }
  }, 5000);
  if (typeof flushTimer.unref === 'function') flushTimer.unref(); // never hold the process open
}

// web_search responses wrap phrases in <cite> tags; strip them anywhere in the parsed JSON.
function stripCites(val) {
  if (typeof val === 'string') return val.replace(/<\/?cite[^>]*>/g, '');
  if (Array.isArray(val)) return val.map(stripCites);
  if (val && typeof val === 'object') {
    const out = {};
    for (const k of Object.keys(val)) out[k] = stripCites(val[k]);
    return out;
  }
  return val;
}

// Normalize free-text jurisdiction input ("Berlin, Deutschland ") into a stable
// cache key part.
//
// Punctuation is dropped so "Denver, CO", "Denver CO" and "Denver,CO" are one
// entry instead of three. That is a pure spelling variant and cannot be wrong.
//
// What this deliberately does NOT do is fall back to a shorter form — "Dublin,
// Ohio" will not borrow the entry for "Dublin". 36 of the 60 seeded locations
// are bare city names, and Dublin, Boston, Melbourne, Madrid and Vancouver all
// exist in more than one country. Serving Irish pubs to someone in Ohio is the
// exact failure the venue grounding was built to prevent, so an unrecognised
// location gets its own lookup.
function normalizeKeyPart(s) {
  return String(s || '').trim().toLowerCase()
    .replace(/[.,/#!$%^&*;:{}=\-_`~()'"]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 80) || 'unknown';
}

/**
 * @param {object} opts
 * @param {string} opts.cacheKey   e.g. `deposit-law:${normalizeKeyPart(location)}`
 * @param {string} opts.label      log label, e.g. 'renters-deposit-saver-facts'
 * @param {string} opts.userPrompt the verification request (ask for ONLY valid JSON)
 * @param {function} opts.render   parsed JSON → facts block string ('' if unusable)
 * @param {number} [opts.ttlMs]    default 14 days
 * @param {number} [opts.maxTokens] default 6000. Was 2500, which truncated the
 *   search summary outright at max_uses 3 or 2 — so even a pre-pass that beat
 *   the old timeout threw and cached nothing. Nothing waits on this call now,
 *   so the budget is free; 6000/max_uses 3 returns 9 verified rules in ~72s.
 * @param {string} [opts.system]   override the default verifier system prompt
 * @returns {Promise<string>} facts block, or '' on any failure
 */
// STALE-WHILE-REVALIDATE. This pre-pass used to be awaited, which put its full
// duration on every uncached request — and the cache is in-memory, emptied on
// every deploy, so the first user per jurisdiction after each deploy paid it.
// The 2026-08-07 fix bounded it at 25s; measuring the search itself then showed
// why that never helped: it takes ~50s regardless of max_uses (3 → 52s, 2 →
// 52s, 1 → 49s), so the bound fired every single time. Every cold request paid
// 25s and got an EMPTY block back — the verified-law feature had quietly
// stopped landing anywhere.
//
// So the request no longer waits. A cached block is returned immediately; a
// missing or expired one returns what we have (possibly '') and kicks the
// search off in the background, so the NEXT request for that jurisdiction is
// grounded. That is strictly better on both axes than the bounded await: 25s
// comes off the cold path AND grounding starts landing again.
//
// Cost: the first user per jurisdiction after a deploy gets the unverified
// hedge instead of verified law. Failing open is already this module's
// contract — the caller's hedge rules take over — so this is the same
// degradation, just without the 25s wait attached to it.

async function groundedFacts({ cacheKey, label, userPrompt, render, ttlMs = 14 * DAY_MS, maxTokens = 6000, system, timeoutMs = 120000, coldWaitMs = 0 }) {
  const hit = cache.get(cacheKey);
  const fresh = hit && hit.expires > Date.now();

  // Refresh whenever we have nothing fresh and nothing already running. Never
  // awaited — the caller gets today's answer now, the cache gets tomorrow's.
  if (!fresh && !inFlight.has(cacheKey)) {
    const p = (async () => {
      let timer;
      try {
        const facts = await Promise.race([
          callClaudeWithRetry({
            model: MODELS.SMART,
            max_tokens: maxTokens,
            tools: [{ type: 'web_search_20250305', name: 'web_search', max_uses: 3 }],
            system: system || 'You verify current legal and regulatory facts with web search. Prefer official sources (legislature, courts, regulators, government portals). Note effective dates and any recent changes or repeals. Return ONLY valid JSON. Never place a double-quote (") character inside any JSON string value — write quoted rule text plainly or with single quotes, or it breaks the JSON.',
            messages: [{ role: 'user', content: userPrompt }],
          }, { label }),
          // Nothing is waiting on this, so the bound only stops a hung search
          // from pinning the in-flight slot forever.
          new Promise((_, reject) => {
            timer = setTimeout(() => reject(new Error(`grounding exceeded ${timeoutMs}ms`)), timeoutMs);
          }),
        ]);
        // render may be async, and may return either a plain string (every
        // consumer before venues.js) or { block, data } when it has structure
        // worth keeping — opening hours and coordinates are not prose and
        // should not have to be re-parsed out of a prompt.
        const rendered = await render(stripCites(facts));
        const block = (typeof rendered === 'string' ? rendered : rendered && rendered.block) || '';
        const data = (rendered && typeof rendered === 'object' && rendered.data) || null;
        store(cacheKey, block, block ? ttlMs : FAILURE_TTL_MS, data);
        if (block) console.log(`[${label}] grounding refreshed in background — later requests for this jurisdiction are verified`);
        return block;
      } catch (err) {
        console.error(`[${label}] background grounding failed, staying unverified:`, err.message);
        store(cacheKey, hit ? hit.block : '', FAILURE_TTL_MS, hit ? hit.data : null);
        return '';
      } finally {
        clearTimeout(timer);
        inFlight.delete(cacheKey);
      }
    })();
    inFlight.set(cacheKey, p);
    // Best-effort by design: an unhandled rejection here must never take the
    // process down, and the caller is deliberately not awaiting it.
    p.catch(() => {});
  }

  // Stale beats nothing: an expired block is still the last verified law we saw.
  if (hit) return hit.block;

  // Nothing cached at all. Callers that would rather wait than answer
  // unverified can opt in with coldWaitMs; everyone else keeps the old
  // behaviour and gets '' immediately.
  //
  // This is only ever the FIRST request for a location. A stale entry returns
  // above without waiting, so the cost is paid once and never again — and the
  // 60-location seed means most visitors never reach this line at all.
  if (coldWaitMs > 0 && inFlight.has(cacheKey)) {
    let bail;
    try {
      const block = await Promise.race([
        inFlight.get(cacheKey),
        new Promise((resolve) => { bail = setTimeout(() => resolve(null), coldWaitMs); }),
      ]);
      if (block) {
        console.log(`[${label}] cold request waited for grounding and got it`);
        return block;
      }
      console.log(`[${label}] grounding did not land within ${coldWaitMs}ms — answering unverified`);
    } catch { /* the fetch failed; fall through unverified */ }
    finally { clearTimeout(bail); }
  }
  return '';
}

function store(key, block, ttlMs, data) {
  if (cache.size >= MAX_ENTRIES) {
    // drop the oldest-expiring entry — bounded memory beats LRU precision here
    let oldestKey, oldestExp = Infinity;
    for (const [k, v] of cache) if (v.expires < oldestExp) { oldestExp = v.expires; oldestKey = k; }
    if (oldestKey !== undefined) cache.delete(oldestKey);
  }
  cache.set(key, { block, data: data || null, expires: Date.now() + ttlMs });
  if (block) scheduleFlush();
}

/**
 * The structured half of a cached entry, when the render step produced one.
 * Null whenever there is nothing cached, or the entry predates structure —
 * callers must treat null as "no information", never as "none".
 */
function groundedData(cacheKey) {
  const hit = cache.get(cacheKey);
  return (hit && hit.data) || null;
}

module.exports = { groundedFacts, groundedData, normalizeKeyPart, stripCites };
