import React, { useState, useCallback } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { ActionBar } from '../components/ActionButtons';

const DEPTHS = [
  { value: 'quick', label: 'Quick', icon: '⚡', desc: '5 consequences, 50 years' },
  { value: 'deep', label: 'Deep Dive', icon: '🔬', desc: '10 consequences, 100+ years' },
  { value: 'absurd', label: 'Absurd', icon: '🤪', desc: 'Plausible → hilariously extreme' },
];

const QUICK_PROMPTS = [
  'The internet was invented in 1920',
  'Dinosaurs never went extinct',
  'Rome never fell',
  'Electricity was never discovered',
  'The printing press was invented 500 years earlier',
  'Humans could fly',
];

const AlternatePath = ({ tool }) => {
  const { callToolEndpoint, loading } = useClaudeAPI();
  const { isDark } = useTheme();

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-500' : 'text-gray-400',
    input:         isDark ? 'bg-zinc-700 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20'
                          : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-500/20',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white'
                          : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-100'
                          : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-green-900/20 border-green-700 text-green-200'
                          : 'bg-green-50 border-green-300 text-green-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200'
                          : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200'
                          : 'bg-red-50 border-red-200 text-red-800',
    warningBox:      isDark ? 'bg-cyan-900/20 border-cyan-700' : 'bg-cyan-50 border-cyan-200',
    pillActive:    isDark ? 'bg-cyan-600 border-cyan-600 text-white' : 'bg-cyan-600 border-cyan-600 text-white',
    pillInactive:  isDark ? 'bg-zinc-700 border-zinc-600 text-zinc-300 hover:border-zinc-500' : 'bg-white border-gray-200 text-gray-600 hover:border-gray-300',
  };

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-600 hover:text-cyan-700 underline underline-offset-2';

  const [whatIf, setWhatIf] = usePersistentState('alternatepath-whatif', '');
  const [yearOrContext, setYearOrContext] = useState('');
  const [depth, setDepth] = useState('quick');
  const [results, setResults] = usePersistentState('alternatepath-last', null);
  const [history, setHistory] = usePersistentState('alternatepath-history', []);
  const [error, setError] = useState('');

  const reset = useCallback(() => {
    setWhatIf('');
    setYearOrContext('');
    setDepth('quick');
    setResults(null);
    setError('');
  }, [setWhatIf, setResults]);

  const run = useCallback(async () => {
    if (!whatIf.trim()) return;
    setError(''); setResults(null);
    try {
      const data = await callToolEndpoint('alternate-path', { whatIf: whatIf.trim(), yearOrContext: yearOrContext.trim(), depth });
      setResults(data);
      const newEntry = {
        id: Date.now(),
        timestamp: new Date().toISOString(),
        preview: whatIf.trim().slice(0, 6),
        result: data,
      };
      setHistory(prev => [newEntry, ...(prev || [])].slice(0, 6));
    } catch (err) { setError(err.message || 'Timeline failed'); }
  }, [whatIf, yearOrContext, depth, callToolEndpoint, setResults, setHistory]);

  const buildFullText = useCallback(() => {
    if (!results) return '';
    const lines = [`🌀 ALTERNATE PATH: ${results.divergence_point || whatIf}`, ''];
    if (results.real_history) lines.push(`📜 Real history: ${results.real_history}`, '');
    results.timeline?.forEach((t, i) => lines.push(`${i + 1}. [${t.year_range}] ${t.event}`));
    lines.push('');
    if (results.today_looks_like) lines.push(`🌍 Today: ${results.today_looks_like}`);
    if (results.biggest_surprise) lines.push(`💡 Surprise: ${results.biggest_surprise}`);
    lines.push('\n— Generated by DeftBrain · deftbrain.com');
    return lines.join('\n');
  }, [results, whatIf]);

  return (
    <div className={`space-y-4 ${c.text}`}>
      <div className={`${c.card} border ${c.border} rounded-xl shadow-lg p-5`}>
        <div className={`mb-4 pb-3 border-b ${c.border}`}>
          <h2 className={`text-xl font-bold ${c.text} flex items-center gap-2`}><span>{tool.icon}</span> Alternate Path</h2>
          <p className={`text-sm ${c.textSecondaryondary}`}>What if history went differently? Watch the dominoes fall.</p>
        </div>

        <div className="mb-3">
          <label className={`text-[10px] font-bold ${c.textSecondaryondary} uppercase block mb-2`}>Try one</label>
          <div className="flex flex-wrap gap-1.5">
            {QUICK_PROMPTS.map((q, i) => (
              <button key={i} onClick={() => { setWhatIf(q); setResults(null); }}
                className={`${c.btnPrimarySecondaryondary} px-2.5 py-1.5 rounded-lg text-[11px] font-medium min-h-[28px]`}>{q}</button>
            ))}
          </div>
        </div>

        <div className="mb-3">
          <label className={`text-xs font-bold ${c.textSecondaryondary} block mb-1.5`}>What if... <span className="text-zinc-400">*</span></label>
          <input type="text" value={whatIf} onChange={e => setWhatIf(e.target.value)}
            placeholder="e.g., The internet was invented in 1920..."
            className={`w-full px-3 py-2.5 border rounded-lg text-sm ${c.input} outline-none focus:ring-2`}
            onKeyDown={e => e.key === 'Enter' && whatIf.trim() && run()} />
        </div>

        <div className="mb-4">
          <label className={`text-xs font-bold ${c.textSecondaryondary} block mb-1.5`}>Year or context <span className={`font-normal ${c.textMuteded}`}>(optional)</span></label>
          <input type="text" value={yearOrContext} onChange={e => setYearOrContext(e.target.value)}
            placeholder="e.g., 1920, during WWI, instead of..."
            className={`w-full px-3 py-2 border rounded-lg text-sm ${c.input} outline-none focus:ring-2`}
            onKeyDown={e => e.key === 'Enter' && whatIf.trim() && run()} />
        </div>

        <div className="mb-5">
          <label className={`text-xs font-bold ${c.textSecondaryondary} uppercase block mb-2`}>Depth</label>
          <div className="flex gap-2">
            {DEPTHS.map(d => (
              <button key={d.value} onClick={() => setDepth(d.value)}
                className={`flex-1 py-2.5 rounded-xl border text-center min-h-[52px] transition-colors ${depth === d.value ? c.pillActive : c.pillInactive}`}>
                <span className="text-sm block">{d.icon} {d.label}</span>
                <span className={`text-[9px] block ${depth === d.value ? 'opacity-80' : c.textMuteded}`}>{d.desc}</span>
              </button>
            ))}
          </div>
        </div>

        <p className={`text-xs text-center ${c.textMuteded} mb-3`}>
          More of a fiction person?{' '}
          <a href="/FanTheory" className={linkStyle}>Fan Theory</a>{' '}
          builds theories about stories and films.
        </p>

        <button onClick={run} disabled={!whatIf.trim() || loading}
          className={`w-full ${c.btnPrimaryPrimary} disabled:opacity-40 font-bold py-3 rounded-lg flex items-center justify-center gap-2 min-h-[48px]`}>
          {loading ? <><span className="animate-spin inline-block">{tool?.icon ?? '⚙️'}</span> Rewriting history...</> : <><span>🌀</span> Explore Timeline</>}
        </button>
      </div>

      {error && <div className={`${c.danger} border rounded-lg p-4 flex items-start gap-3`}><span>⚠️</span><p className="text-sm">{error}</p></div>}

      {results && (
        <div className="space-y-4">
          <div className="flex justify-end">
            <ActionBar content={buildFullText()} title="Alternate Path" />
          </div>

          <div className={`${c.cardAltBg} border-2 rounded-xl p-5 text-center`}>
            <span className="text-3xl block mb-2">🌀</span>
            <p className={`text-lg font-black ${c.text} mb-2`}>{results.divergence_point}</p>
            {results.real_history && <p className={`text-xs ${c.textMuteded} italic`}>📜 Reality: {results.real_history}</p>}
            {results.plausibility && <p className={`text-xs ${c.cardAlt} mt-2`}>Plausibility: {results.plausibility}/10</p>}
          </div>

          {results.timeline?.length > 0 && (
            <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
              <h3 className={`text-sm font-bold ${c.text} mb-3`}>📅 Timeline</h3>
              <div className="space-y-2">
                {results.timeline.map((t, i) => (
                  <div key={i} className={`${c.cardAlt} rounded-lg p-3 border-l-4 border-cyan-500`}>
                    <div className="flex items-start gap-2">
                      <span className={`text-xs font-black ${c.cardAlt} whitespace-nowrap`}>{t.year_range}</span>
                      <div className="flex-1">
                        <p className={`text-xs font-medium ${c.text}`}>{t.event}</p>
                        <p className={`text-[10px] ${c.textMuteded} mt-1`}>↳ {t.because}</p>
                        {t.real_world_contrast && <p className={`text-[10px] ${c.textMuteded} italic mt-1`}>Reality: {t.real_world_contrast}</p>}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {results.today_looks_like && (
            <div className={`${c.success} border rounded-xl p-4`}>
              <p className={`text-[10px] font-bold uppercase mb-1`}>🌍 Today in This Timeline</p>
              <p className="text-sm">{results.today_looks_like}</p>
            </div>
          )}

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {results.biggest_surprise && (
              <div className={`${c.warning} border rounded-xl p-4`}>
                <p className={`text-[10px] font-bold uppercase mb-1`}>💡 Biggest Surprise</p>
                <p className="text-xs">{results.biggest_surprise}</p>
              </div>
            )}
            {results.butterfly_moment && (
              <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
                <p className={`text-[10px] font-bold ${c.cardAlt} uppercase mb-1`}>🦋 Butterfly Moment</p>
                <p className={`text-xs ${c.textSecondaryondary}`}>{results.butterfly_moment}</p>
              </div>
            )}
          </div>

          <div className="flex gap-2">
            <button onClick={run} disabled={loading}
              className={`flex-1 ${c.btnPrimarySecondaryondary} font-bold py-3 rounded-lg min-h-[44px]`}>
              🌀 Different Timeline
            </button>
            <button onClick={reset}
              className={`flex-1 ${c.btnPrimarySecondaryondary} font-bold py-3 rounded-lg min-h-[44px]`}>
              ↩ Start Over
            </button>
          </div>

          <div className="space-y-1">
            <p className={`text-xs text-center ${c.textMuteded}`}>
              Want to stress-test a belief this uncovered?{' '}
              <a href="/BeliefStressTest" className={linkStyle}>Belief Stress Test</a>{' '}
              finds the weakest assumptions.
            </p>
            {results.plausibility < 4 && (
              <p className={`text-xs text-center ${c.textMuteded}`}>
                Low plausibility score?{' '}
                <a href="/BrainRoulette" className={linkStyle}>Brain Roulette</a>{' '}
                might spark a wilder but more grounded scenario.
              </p>
            )}
          </div>
        </div>
      )}

      {history?.length > 0 && (
        <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
          <h3 className={`text-sm font-bold ${c.text} mb-3`}>🕐 Recent Timelines</h3>
          <div className="space-y-1.5">
            {history.map(entry => (
              <button key={entry.id}
                onClick={() => setResults(entry.result)}
                className={`w-full text-left px-3 py-2 rounded-lg ${c.btnPrimarySecondaryondary} text-xs flex items-center gap-2`}>
                <span className={c.textMuteded}>
                  {new Date(entry.timestamp).toLocaleDateString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })}
                </span>
                <span className={c.text}>{entry.preview}{entry.preview.length >= 40 ? '…' : ''}</span>
              </button>
            ))}
          </div>
        </div>
      )}
        <div className={`mt-6 pt-4 border-t text-sm ${c.border} ${c.textMuteded}`}>
          <p className="mb-2 font-medium">You might also like:</p>
          <div className="flex flex-wrap gap-2">
            {[{slug:'what-if-machine',label:'🌀 What If Machine'},{slug:'fan-theory',label:'🎬 Fan Theory'},{slug:'future-proof',label:'🔭 Future Proof'}].map(({slug,label})=>(
              <a key={slug} href={`${slug}`} className={linkStyle}>{label}</a>
            ))}
          </div>
        </div>
    </div>
  );
};

AlternatePath.displayName = 'AlternatePath';
export default AlternatePath;
