import React, { useState, useEffect, useRef, useCallback } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';


const EXAMPLE = {
  concept: 'How vaccines work',
  audience: 'my 8-year-old',
  audienceInterests: 'loves dinosaurs, plays Minecraft, asks why constantly',
  depth: 'solid_understanding',
};

const EXAMPLE_PAIRS = [
  { concept: 'Blockchain', audience: 'My grandmother who loves gardening', emoji: '🌱' },
  { concept: 'Inflation', audience: 'A 12-year-old', emoji: '🎈' },
  { concept: 'Machine learning', audience: 'A chef', emoji: '👨‍🍳' },
  { concept: 'DNA', audience: 'Someone who builds furniture', emoji: '🪚' },
  { concept: 'Compound interest', audience: 'A teenager saving for a car', emoji: '🚗' },
  { concept: 'Quantum computing', audience: 'A musician', emoji: '🎵' },
];

const AnalogyEngine = ({ tool }) => {
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();

  const DEPTH_LEVELS = [
    { value: 'quick_grasp', label: t('ae_depth_quick'), emoji: '⚡' },
    { value: 'solid_understanding', label: t('ae_depth_solid'), emoji: '📖' },
    { value: 'deep_understanding', label: t('ae_depth_deep'), emoji: '🔬' },
  ];

  // ─── Colors ───
  const c = {
    card:          isDark ? 'bg-zinc-800'      : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50'   : 'bg-slate-50',
    input:         isDark
      ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20'
      : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50'     : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300'    : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-500'    : 'text-gray-400',
    labelText:     isDark ? 'text-zinc-200'    : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400'    : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700'  : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-200 text-red-800',
    successBox:    isDark ? 'bg-emerald-900/20 border-emerald-700' : 'bg-emerald-50 border-emerald-300',
    successTxt:    isDark ? 'text-emerald-300' : 'text-emerald-800',
    warningBox:    isDark ? 'bg-amber-900/20 border-amber-700' : 'bg-amber-50 border-amber-300',
    warningTxt:    isDark ? 'text-amber-300'   : 'text-amber-800',
    pillActive:    isDark ? 'bg-cyan-600 border-cyan-600 text-white' : 'bg-cyan-600 border-cyan-600 text-white',
    pillInactive:  isDark ? 'bg-zinc-700 border-zinc-600 text-zinc-300 hover:border-zinc-500' : 'bg-white border-gray-200 text-gray-600 hover:border-gray-300',
    required:      isDark ? 'text-amber-400'   : 'text-amber-500',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-600 hover:text-cyan-700 underline underline-offset-2';

  // ─── State ───
  const [audience, setAudience] = useState('');
  const [audienceInterests, setAudienceInterests] = useState('');
  const [depth, setDepth] = useState('solid_understanding');
  const [error, setError] = useState('');
  const [concept, setConcept] = usePersistentState('analogyengine-concept', '');

  const [results, setResults] = usePersistentState('analogyengine-last', null);
  const [sessionHistory, setSessionHistory] = usePersistentState('analogyengine-history', []);

  // ─── Refs ───
  const resultsRef = useRef(null);
  const handleSubmitRef = useRef(null);
  const canSubmitRef = useRef(false);

  // ─── Handlers ───
  const generate = async (example) => {
    const conceptText = (example?.concept || concept).trim();
    const audienceText = (example?.audience || audience).trim();
    if (!conceptText) return;

    setError('');
    setResults(null);
    if (example) {
      setConcept(example.concept);
      setAudience(example.audience);
      setAudienceInterests('');
    }

    try {
      const data = await callToolEndpoint('analogy-engine', {
        concept: conceptText,
        audience: audienceText || 'general adult',
        audienceInterests: audienceInterests.trim() || null,
        depth,
        userLocale, userCurrency, userRegion,
      });
      setResults(data);
      setSessionHistory(prev => [{
        id: Date.now(),
        timestamp: new Date().toISOString(),
        // PF-25 exception: 40-char preview-text truncation; session history is capped at 6.
        preview: conceptText.slice(0, 40),
        result: data,
      }, ...(prev || [])].slice(0, 6));
    } catch (err) {
      setError(err.message || t('ae_error'));
    }
  };

  const handleSubmit = () => generate();

  const loadExample = useCallback(() => {
    setConcept(EXAMPLE.concept);
    setAudience(EXAMPLE.audience);
    setAudienceInterests(EXAMPLE.audienceInterests);
    setDepth(EXAMPLE.depth);
    setResults(null);
  }, [setConcept, setResults]);

  const handleReset = () => {
    setConcept('');
    setAudience('');
    setAudienceInterests('');
    setDepth('solid_understanding');
    setResults(null);
    setError('');
  };

  // ─── Build copyable text ───
  const buildFullText = useCallback(() => {
    if (!results) return '';
    const r = results;
    let text = `💡 ${t('ae_copy_title')}: ${r.concept_name || concept}\n`;
    if (r.one_liner) text += `\n${t('ae_copy_one_sentence')} ${r.one_liner}\n`;
    if (r.analogies?.length) {
      r.analogies.forEach((a, i) => {
        text += `\n${i + 1}. ${a.title} [${a.type}]\n${a.analogy}`;
        if (a.why_it_works) text += `\n${t('ae_copy_why_works')} ${a.why_it_works}`;
        if (a.where_it_breaks) text += `\n⚠️ ${t('ae_copy_limit')} ${a.where_it_breaks}`;
      });
    }
    if (r.the_key_insight) text += `\n\n💡 ${t('ae_copy_key_insight')} ${r.the_key_insight}`;
    if (r.common_misconceptions?.length) {
      text += `\n\n${t('ae_copy_misconceptions')}`;
      r.common_misconceptions.forEach(m => { text += `\n• ${m}`; });
    }
    if (r.go_deeper) text += `\n\n${t('ae_copy_go_deeper')} ${r.go_deeper}`;
    if (r.teaching_tip) text += `\n\n${t('ae_copy_teaching_tip')} ${r.teaching_tip}`;
    return text + BRAND;
  }, [results, concept, t]);

  // ─── Register global actions ───
  useRegisterActions(buildFullText(), tool?.title || 'Analogy Engine');

  // ─── Ref assignments every render (for keyboard handler) ───
  handleSubmitRef.current = handleSubmit;
  canSubmitRef.current = Boolean(concept.trim()) && !loading;

  // ─── Scroll to results ───
  useEffect(() => {
    if (!results || !resultsRef.current) return;
    const timer = setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 250);
    return () => clearTimeout(timer);
  }, [results]);

  // ─── Global ⌘/Ctrl+Enter keyboard handler ───
  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && canSubmitRef.current) {
        e.preventDefault();
        handleSubmitRef.current?.();
      }
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, []);

  // ─── Render ───
  const hasAnyInput = concept.trim() || audience.trim() || audienceInterests.trim();

  return (
    <div className={`space-y-4 ${c.text}`}>

      {/* ── Input Card ── */}
      <div className={`${c.card} border ${c.border} rounded-2xl p-5 shadow-sm space-y-4`}>

        {/* Header with title + reset */}
        <div className="flex items-start justify-between gap-3 pb-4 border-b border-zinc-500">
          <div className="flex-1 min-w-0">
            <h2 className={`text-xl font-bold ${c.text} flex items-center gap-2`}>
              <span className="mr-2">{tool?.icon ?? '💡'}</span>{tool?.title ?? t('ae_title')}
            </h2>
            <p className={`text-sm ${c.textSecondary} mt-1`}>{tool?.tagline ?? t('ae_tagline')}</p>
            <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className={`mt-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium border disabled:opacity-40 ${isDark ? 'text-white border-white/40' : 'text-gray-800 border-transparent'}`}>{t('try_example')}</button>
          </div>
          {(results || hasAnyInput) ? (
            <button
              onClick={handleReset}
              className={`shrink-0 px-3 py-2 rounded-lg text-sm font-bold min-h-[40px] ${c.btnSecondary}`}
            >↺ {t('start_over')}</button>
          ) : null}
        </div>

        {/* Concept — REQUIRED */}
        <div>
          <label className={`block text-sm font-semibold ${c.labelText} mb-1.5`}>
            {t('ae_q_concept')} <span className={c.required}>*</span>
          </label>
          <input
            type="text"
            value={concept}
            onChange={e => setConcept(e.target.value)}
            placeholder={t('ae_ph_concept')}
            className={`w-full px-3 py-2.5 border rounded-lg text-sm ${c.input} outline-none focus:ring-2`}
          />
        </div>

        {/* Audience */}
        <div>
          <label className={`block text-sm font-semibold ${c.labelText} mb-1.5`}>
            {t('ae_q_audience')}
          </label>
          <input
            type="text"
            value={audience}
            onChange={e => setAudience(e.target.value)}
            placeholder={t('ae_ph_audience')}
            className={`w-full px-3 py-2.5 border rounded-lg text-sm ${c.input} outline-none focus:ring-2`}
          />
        </div>

        {/* Their interests / world */}
        <div>
          <label className={`block text-sm font-semibold ${c.labelText} mb-1.5`}>
            {t('ae_q_interests')} <span className={`font-normal ${c.textMuteded}`}>{t('ae_interests_hint')}</span>
          </label>
          <input
            type="text"
            value={audienceInterests}
            onChange={e => setAudienceInterests(e.target.value)}
            placeholder={t('ae_ph_interests')}
            className={`w-full px-3 py-2.5 border rounded-lg text-sm ${c.input} outline-none focus:ring-2`}
          />
        </div>

        {/* Depth */}
        <div>
          <label className={`block text-sm font-semibold ${c.labelText} mb-2`}>{t('ae_q_depth')}</label>
          <div className="flex gap-2">
            {DEPTH_LEVELS.map(d => (
              <button
                key={d.value}
                onClick={() => setDepth(d.value)}
                className={`flex-1 py-2.5 rounded-xl text-xs font-bold border transition-colors min-h-[44px] flex flex-col items-center gap-0.5 ${
                  depth === d.value ? c.pillActive : c.pillInactive
                }`}
              >
                <span className="text-base">{d.emoji}</span>
                {d.label}
              </button>
            ))}
          </div>
        </div>

        {/* Examples — only pre-result */}
        {!results && (
          <div>
            <p className={`text-xs font-bold ${c.textMuteded} mb-2`}>{t('ae_try_one')}</p>
            <div className="flex flex-wrap gap-1.5">
              {EXAMPLE_PAIRS.map(ex => (
                <button
                  key={ex.concept}
                  onClick={() => generate(ex)}
                  disabled={loading}
                  className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors min-h-[32px] ${c.pillInactive} disabled:opacity-40`}
                >
                  {ex.emoji} {ex.concept} → {ex.audience.split(' ').slice(0, 3).join(' ')}...
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Pre-result cross-ref */}
        <p className={`text-xs text-center ${c.textMuteded}`}>
          {t('ae_xref_pre_q')}{' '}
          <a href="/PlainTalk" className={linkStyle}>💬 {t('ae_plaintalk')}</a>{' '}
          {t('ae_xref_pre_tail')}
        </p>

        {/* Submit + Try example */}
        <button
          onClick={handleSubmit}
          disabled={loading || !concept.trim()}
          className={`w-full ${c.btnPrimary} disabled:opacity-40 font-bold py-3 rounded-lg flex items-center justify-center gap-2 min-h-[48px]`}
        >
        {loading ? (
          <>
            <span className="animate-spin inline-block">{tool?.icon ?? '💡'}</span>
            {t('ae_crafting')}
          </>
        ) : (
          <>
            <span>{tool?.icon ?? '💡'}</span> {t('ae_generate')}
          </>
        )}
        </button>
      </div>

      {/* ── Error ── */}
      {error && (
        <div className={`${c.danger} border rounded-xl p-4 text-sm flex items-start gap-2`}>
          <span className="flex-shrink-0 mt-0.5">⚠️</span>
          <p>{error}</p>
        </div>
      )}

      {/* ── Results ── */}
      {results && (
        <div ref={resultsRef} className="space-y-4">

          {/* One-liner */}
          {results?.one_liner && (
            <div className={`${c.card} border ${c.border} rounded-2xl p-5`}>
              <p className={`text-xs font-bold ${c.textMuteded} mb-1 uppercase tracking-wider`}>{t('ae_one_sentence')}</p>
              <p className={`text-base font-bold ${c.text} leading-relaxed`}>{results?.one_liner}</p>
            </div>
          )}

          {/* Analogies */}
          {results?.analogies?.length > 0 && (
            <div className="space-y-3">
              <h3 className={`text-sm font-bold ${c.text}`}>
                {results?.analogies?.length === 1
                  ? t('ae_analogies_for_one', { count: results?.analogies?.length, name: results?.concept_name || concept })
                  : t('ae_analogies_for_many', { count: results?.analogies?.length, name: results?.concept_name || concept })}
              </h3>
              {results?.analogies?.map((analogy, idx) => (
                <div key={idx} className={`${c.card} border ${c.border} rounded-2xl overflow-hidden`}>
                  <div className="p-5">
                    <div className="flex items-start justify-between gap-3 mb-3">
                      <div className="flex-1 min-w-0">
                        <h4 className={`text-sm font-bold ${c.text}`}>{analogy.title}</h4>
                        <div className="flex flex-wrap gap-1.5 mt-1.5">
                          <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full border ${c.successBox} ${c.successTxt}`}>{analogy.type}</span>
                          {analogy.accuracy === 'high' && (
                            <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full border ${c.successBox} ${c.successTxt}`}>{t('ae_high_accuracy')}</span>
                          )}
                          {analogy.memorability === 'high' && (
                            <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full border ${c.warningBox} ${c.warningTxt}`}>{t('ae_memorable')}</span>
                          )}
                        </div>
                      </div>
                    </div>
                    <div className={`${c.cardAlt} rounded-lg p-4 mb-3`}>
                      <p className={`text-sm ${c.text} leading-relaxed`}>{analogy.analogy}</p>
                    </div>
                    {analogy.why_it_works && (
                      <p className={`text-xs ${c.textSecondary} mb-2`}>
                        <span className="font-bold">{t('ae_why_works')}</span> {analogy.why_it_works}
                      </p>
                    )}
                    {analogy.where_it_breaks && (
                      <p className={`text-xs ${c.textMuteded} italic`}>⚠️ {t('ae_limit')} {analogy.where_it_breaks}</p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Key insight */}
          {results?.the_key_insight && (
            <div className={`${c.success} border rounded-2xl p-4 flex items-start gap-3`}>
              <span className="flex-shrink-0 mt-0.5 text-lg">💡</span>
              <div className="flex-1 min-w-0">
                <p className="text-xs font-bold mb-1 uppercase tracking-wider">{t('ae_key_insight')}</p>
                <p className="text-sm font-medium leading-relaxed">{results?.the_key_insight}</p>
              </div>
            </div>
          )}

          {/* Common misconceptions */}
          {results?.common_misconceptions?.length > 0 && (
            <div className={`${c.card} border ${c.border} rounded-2xl p-4`}>
              <p className={`text-xs font-bold ${c.text} mb-2 uppercase tracking-wider`}>🚫 {t('ae_misconceptions')}</p>
              <div className="space-y-1.5">
                {results?.common_misconceptions?.map((m, i) => (
                  <p key={i} className={`text-xs ${c.textSecondary} leading-relaxed`}>• {m}</p>
                ))}
              </div>
            </div>
          )}

          {/* Go deeper + teaching tip */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {results?.go_deeper && (
              <div className={`${c.cardAlt} border ${c.border} rounded-2xl p-4`}>
                <p className={`text-xs font-bold ${c.textMuteded} mb-1 uppercase tracking-wider`}>📚 {t('ae_go_deeper')}</p>
                <p className={`text-xs ${c.textSecondary} leading-relaxed`}>{results?.go_deeper}</p>
                {results?.go_deeper_concept && (
                  <button
                    onClick={() => generate({ concept: results.go_deeper_concept, audience })}
                    disabled={loading}
                    className={`mt-3 w-full ${c.btnPrimary} disabled:opacity-40 text-xs font-bold py-2 rounded-lg flex items-center justify-center gap-1.5 min-h-[36px]`}
                  >
                    <span>💡</span> {t('ae_explain_deeper')} "{results.go_deeper_concept}" <span aria-hidden="true">→</span>
                  </button>
                )}
              </div>
            )}
            {results?.teaching_tip && (
              <div className={`${c.cardAlt} border ${c.border} rounded-2xl p-4`}>
                <p className={`text-xs font-bold ${c.textMuteded} mb-1 uppercase tracking-wider`}>🎓 {t('ae_teaching_tip')}</p>
                <p className={`text-xs ${c.textSecondary} leading-relaxed`}>{results?.teaching_tip}</p>
              </div>
            )}
          </div>

          {/* Conditional cross-ref: accuracy concerns */}
          {results?.analogies?.length > 0 && results?.analogies?.[0]?.accuracy === 'medium' && (
            <p className={`text-xs text-center ${c.textMuteded}`}>
              {t('ae_xref_acc_q')}{' '}
              <a href="/BeliefStressTest" className={linkStyle}>🧪 {t('ae_beliefstress')}</a>{' '}
              {t('ae_xref_acc_tail')}
            </p>
          )}

          {/* Post-result cross-refs */}
          <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4 space-y-2`}>
            <p className={`text-xs font-semibold ${c.textMuteded} uppercase tracking-wider`}>
              {t('ae_keep_explaining')}
            </p>
            <div className="flex flex-wrap gap-x-4 gap-y-1">
              <a href="/JargonAssassin" className={`text-xs ${linkStyle}`}>🗡️ {t('ae_jargon')}</a>
              <a href="/BrainRoulette" className={`text-xs ${linkStyle}`}>🎲 {t('ae_brainroulette')}</a>
            </div>
          </div>
        </div>
      )}

      {/* ── History ── */}
      {sessionHistory?.length > 0 && (
        <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
          <h3 className={`text-sm font-bold ${c.text} mb-3`}>🕐 {t('ae_recent')}</h3>
          <div className="space-y-1.5">
            {sessionHistory.map(entry => (
              <button key={entry.id}
                onClick={() => setResults(entry.result)}
                className={`w-full text-left px-3 py-2 rounded-lg ${c.btnSecondary} text-xs flex items-center gap-2`}>
                <span className={c.textMuteded}>
                  {new Date(entry.timestamp).toLocaleDateString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })}
                </span>
                <span className={`${c.text} truncate`}>{entry.preview}{entry.preview?.length >= 40 ? '…' : ''}</span>
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

AnalogyEngine.displayName = 'AnalogyEngine';
export default AnalogyEngine;
