import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { CopyBtn, ActionBar } from '../components/ActionButtons';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

// ═══════════════════════════════════════════
// CONSTANTS
// ═══════════════════════════════════════════

const ENERGY_OPTS = [
  { v: 'morning_person', l: '🌅 Morning Person', d: 'Peak 8-11am' },
  { v: 'slow_starter', l: '☕ Slow Starter', d: 'Peak 1-4pm' },
  { v: 'afternoon_peak', l: '☀️ Afternoon Peak', d: 'Peak 1-5pm' },
  { v: 'night_owl', l: '🦉 Night Owl', d: 'Peak 7-11pm' },
  { v: 'flat', l: '➖ Roughly Even', d: 'Batch by mode' },
];
const DAY_OPTS = [
  { v: 'maker', l: '🛠️ Maker Day', d: 'Deep work first' },
  { v: 'meetings', l: '📞 Meetings Day', d: 'Batch around calls' },
  { v: 'mixed', l: '🔀 Mixed Bag', d: 'Balanced batches' },
  { v: 'errands', l: '🏃 Errand Day', d: 'Location-based' },
  { v: 'admin', l: '📋 Admin Day', d: 'Clear the backlog' },
];
const TIME_OPTS = [
  { v: '2', l: '~2 hrs' }, { v: '4', l: '~4 hrs' }, { v: '6', l: '~6 hrs' },
  { v: '8', l: 'Full day' }, { v: 'unknown', l: 'Flexible' },
];
const MODE_COLORS = {
  creative: { bg: 'bg-violet-', border: 'border-violet-', text: 'text-violet-', emoji: '🎨', label: 'Creative' },
  analytical: { bg: 'bg-blue-', border: 'border-blue-', text: 'text-blue-', emoji: '📊', label: 'Analytical' },
  social: { bg: 'bg-amber-', border: 'border-amber-', text: 'text-amber-', emoji: '💬', label: 'Social' },
  mechanical: { bg: 'bg-slate-', border: 'border-slate-', text: 'text-slate-', emoji: '⚙️', label: 'Mechanical' },
  physical: { bg: 'bg-emerald-', border: 'border-emerald-', text: 'text-emerald-', emoji: '🏃', label: 'Physical' },
  planning: { bg: 'bg-cyan-', border: 'border-cyan-', text: 'text-cyan-', emoji: '🗺️', label: 'Planning' },
  break: { bg: 'bg-gray-', border: 'border-gray-', text: 'text-gray-', emoji: '☕', label: 'Break' },
};
const RECIPIENT_OPTS = [{ v: 'partner', l: '❤️ Partner' }, { v: 'friend', l: '🤝 Friend' }, { v: 'coworker', l: '💼 Coworker' }];
const HEATMAP_INTENSITY = { high: 0.9, medium: 0.5, low: 0.2 };

// ═══════════════════════════════════════════
// COMPONENT
// ═══════════════════════════════════════════

const BatchFlow = () => {
  const { callToolEndpoint, loading } = useClaudeAPI();
  const { theme } = useTheme();
  const isDark = theme === 'dark';

  const c = {
    card: isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt: isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    text: isDark ? 'text-zinc-50' : 'text-gray-900',
    ts: isDark ? 'text-zinc-300' : 'text-gray-600',
    tm: isDark ? 'text-zinc-500' : 'text-gray-400',
    input: isDark ? 'bg-zinc-700 border-zinc-600 text-zinc-100 placeholder-zinc-400' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400',
    pri: isDark ? 'bg-emerald-600 hover:bg-emerald-500 text-white' : 'bg-emerald-600 hover:bg-emerald-700 text-white',
    sec: isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-100' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    bdr: isDark ? 'border-zinc-700' : 'border-gray-200',
    chip: (a) => a ? (isDark ? 'bg-emerald-900/40 border-emerald-500 text-emerald-200' : 'bg-emerald-100 border-emerald-400 text-emerald-800') : (isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500' : 'border-gray-200 text-gray-500 hover:border-gray-300'),
    ok: isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warn: isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    bad: isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-200 text-red-800',
    info: isDark ? 'bg-blue-900/20 border-blue-700 text-blue-200' : 'bg-blue-50 border-blue-200 text-blue-800',
    purp: isDark ? 'bg-purple-900/20 border-purple-700 text-purple-200' : 'bg-purple-50 border-purple-200 text-purple-800',
    jnl: isDark ? 'bg-amber-900/15 border-amber-700/40' : 'bg-amber-50 border-amber-300',
    jt: isDark ? 'text-amber-400' : 'text-amber-700',
    snap: isDark ? 'bg-teal-900/20 border-teal-700 text-teal-200' : 'bg-teal-50 border-teal-300 text-teal-800',
    ab: isDark ? 'bg-indigo-900/20 border-indigo-700 text-indigo-200' : 'bg-indigo-50 border-indigo-300 text-indigo-800',
  };
  const modeStyle = (mode) => { const m = MODE_COLORS[mode] || MODE_COLORS.mechanical; return isDark ? `${m.bg}900/25 ${m.border}700 ${m.text}300` : `${m.bg}50 ${m.border}300 ${m.text}800`; };
  const modeInfo = (mode) => MODE_COLORS[mode] || MODE_COLORS.mechanical;
  const modeBarColor = (mode) => {
    const map = { creative: '#8b5cf6', analytical: '#3b82f6', social: '#f59e0b', mechanical: '#64748b', physical: '#10b981', planning: '#06b6d4', break: '#9ca3af' };
    return map[mode] || '#9ca3af';
  };

  // ─── Input ───
  const [tasks, setTasks] = useState([{ text: '', duration: '', location: '' }]);
  const [showDetails, setShowDetails] = useState({});
  const [energyCurve, setEnergyCurve] = useState('');
  const [dayType, setDayType] = useState('mixed');
  const [timeAvail, setTimeAvail] = useState('');
  const [locationMode, setLocationMode] = useState(false);
  const [commitments, setCommitments] = useState([]);
  const [showCommitments, setShowCommitments] = useState(false);
  const [newCommitTime, setNewCommitTime] = useState('');
  const [newCommitLabel, setNewCommitLabel] = useState('');
  const [error, setError] = useState('');
  const [validFail, setValidFail] = useState(false);

  // ─── Quick dump ───
  const [dumpMode, setDumpMode] = useState(false);
  const [dumpText, setDumpText] = useState('');
  const [dumpLoading, setDumpLoading] = useState(false);

  // ─── Results ───
  const [results, setResults] = useState(null);
  const [expanded, setExpanded] = useState({});
  const [checked, setChecked] = useState({});
  const [completedBatches, setCompletedBatches] = useState({});

  // ─── Expand/Move/Progress ───
  const [expandedBatch, setExpandedBatch] = useState(null);
  const [expandResult, setExpandResult] = useState(null);
  const [expandLoading, setExpandLoading] = useState(false);
  const [movingTask, setMovingTask] = useState(null);
  const [progressResult, setProgressResult] = useState(null);
  const [progressLoading, setProgressLoading] = useState(false);

  // ─── Share/Templates ───
  const [showShare, setShowShare] = useState(false);
  const [shareRecipient, setShareRecipient] = useState('friend');
  const [shareResult, setShareResult] = useState(null);
  const [shareLoading, setShareLoading] = useState(false);
  const [showSaveTemplate, setShowSaveTemplate] = useState(false);
  const [templateName, setTemplateName] = useState('');
  const [saveTemplateLoading, setSaveTemplateLoading] = useState(false);

  // ─── v3: A/B Compare ───
  const [abResult, setAbResult] = useState(null);
  const [abLoading, setAbLoading] = useState(false);
  const [abChoice, setAbChoice] = useState(null); // 'sprint' | 'marathon'

  // ─── v3: Weekly Rhythm ───
  const [showWeekly, setShowWeekly] = useState(false);
  const [weeklyTasks, setWeeklyTasks] = useState([{ task: '', frequency: 'weekly', preferred_day: '', duration: '' }]);
  const [weeklyResult, setWeeklyResult] = useState(null);
  const [weeklyLoading, setWeeklyLoading] = useState(false);

  // ─── v3: Resistance ───
  const [resistResult, setResistResult] = useState(null);
  const [resistLoading, setResistLoading] = useState(false);

  // ─── v3: Time tracking ───
  const [showTimeInput, setShowTimeInput] = useState(null); // batch index
  const [actualTimes, setActualTimes] = useState({});
  const [calibResult, setCalibResult] = useState(null);
  const [calibLoading, setCalibLoading] = useState(false);

  // ─── v3: Focus preset expanded ───
  const [showFocusPreset, setShowFocusPreset] = useState({});

  // ─── Insights / Journal ───
  const [insightsResult, setInsightsResult] = useState(null);
  const [insightsLoading, setInsightsLoading] = useState(false);
  const [showJournal, setShowJournal] = useState(false);
  const [showTemplates, setShowTemplates] = useState(false);

  // ─── Persistent ───
  const [journal, setJournal] = usePersistentState('batchflow-journal', []);
  const [templates, setTemplates] = usePersistentState('batchflow-templates', []);
  const [deferredTasks, setDeferredTasks] = usePersistentState('batchflow-deferred', {});
  const [timeHistory, setTimeHistory] = usePersistentState('batchflow-times', []);

  // ─── Derived ───
  const filledTasks = tasks.filter(t => t.text.trim());
  const batchProgress = useMemo(() => {
    if (!results?.batches?.length) return { total: 0, done: 0, pct: 0 };
    let total = 0, done = 0;
    results.batches.forEach((b, bi) => { (b.tasks || []).forEach((_, ti) => { total++; if (checked[`b${bi}-${ti}`]) done++; }); });
    return { total, done, pct: total > 0 ? Math.round((done / total) * 100) : 0 };
  }, [results, checked]);

  const deferredList = useMemo(() => {
    return Object.entries(deferredTasks).filter(([_, count]) => count >= 2).map(([task, count]) => ({ task, defer_count: count, cognitive_mode: '?' })).sort((a, b) => b.defer_count - a.defer_count);
  }, [deferredTasks]);

  // ═══ HANDLERS ═══

  const addTask = () => setTasks(p => [...p, { text: '', duration: '', location: '' }]);
  const removeTask = (i) => setTasks(p => p.filter((_, idx) => idx !== i));
  const updateTask = (i, f, v) => setTasks(p => { const u = [...p]; u[i] = { ...u[i], [f]: v }; return u; });
  const toggleDetail = (i) => setShowDetails(p => ({ ...p, [i]: !p[i] }));
  const toggleExpand = (k) => setExpanded(p => ({ ...p, [k]: !p[k] }));
  const toggleCheck = (id) => setChecked(p => ({ ...p, [id]: !p[id] }));
  const addCommitment = () => { if (newCommitTime && newCommitLabel) { setCommitments(p => [...p, { time: newCommitTime, label: newCommitLabel }]); setNewCommitTime(''); setNewCommitLabel(''); } };

  const markBatchComplete = (bi) => {
    const batch = results?.batches?.[bi]; if (!batch) return;
    const updates = {}; (batch.tasks || []).forEach((_, ti) => { updates[`b${bi}-${ti}`] = true; });
    setChecked(p => ({ ...p, ...updates })); setCompletedBatches(p => ({ ...p, [bi]: true }));
  };
  const isBatchDone = (bi) => { const b = results?.batches?.[bi]; return b?.tasks?.length ? b.tasks.every((_, ti) => checked[`b${bi}-${ti}`]) : false; };

  const reset = () => {
    setTasks([{ text: '', duration: '', location: '' }]); setShowDetails({}); setEnergyCurve(''); setDayType('mixed');
    setTimeAvail(''); setLocationMode(false); setCommitments([]); setError(''); setValidFail(false);
    setResults(null); setExpanded({}); setChecked({}); setCompletedBatches({});
    setDumpMode(false); setDumpText(''); setExpandedBatch(null); setExpandResult(null);
    setMovingTask(null); setProgressResult(null); setShowShare(false); setShareResult(null);
    setAbResult(null); setAbChoice(null); setShowTimeInput(null); setActualTimes({});
    setCalibResult(null); setShowFocusPreset({}); setResistResult(null);
  };

  const saveToJournal = useCallback((res, taskCount) => {
    const topMode = (res.batches || []).reduce((acc, b) => { acc[b.cognitive_mode] = (acc[b.cognitive_mode] || 0) + (b.tasks?.length || 0); return acc; }, {});
    setJournal(p => [{ id: `bf_${Date.now()}`, date: new Date().toISOString(), totalTasks: taskCount, batchCount: (res.batches || []).length, tasksCompleted: 0, timeSaved: res.time_saved_estimate || '?', topMode: Object.entries(topMode).sort((a, b) => b[1] - a[1])[0]?.[0] || '?', dayType, energyCurve }, ...p].slice(0, 50));
  }, [setJournal, dayType, energyCurve]);

  // Track deferred tasks (unchecked when session ends)
  const trackDeferrals = useCallback(() => {
    if (!results?.batches) return;
    const unchecked = [];
    results.batches.forEach((b, bi) => { (b.tasks || []).forEach((t, ti) => { if (!checked[`b${bi}-${ti}`]) unchecked.push(t.task); }); });
    if (unchecked.length > 0) setDeferredTasks(p => { const u = { ...p }; unchecked.forEach(t => { u[t] = (u[t] || 0) + 1; }); return u; });
  }, [results, checked, setDeferredTasks]);

  // ─── Generate ───
  const handleGenerate = async () => {
    if (filledTasks.length === 0) { setError('Add at least one task.'); setValidFail(true); setTimeout(() => setValidFail(false), 2000); return; }
    setError(''); setValidFail(false); setResults(null); setChecked({}); setCompletedBatches({});
    setExpandedBatch(null); setExpandResult(null); setProgressResult(null); setAbResult(null);
    const now = new Date();
    const data = await callToolEndpoint('batch-flow', {
      action: 'generate', tasks: filledTasks.map(t => ({ task: t.text.trim(), duration: t.duration.trim() || null, location: t.location.trim() || null })),
      energy_curve: energyCurve || null, day_type: dayType, time_available: timeAvail || null,
      start_time: `${now.getHours()}:${String(now.getMinutes()).padStart(2, '0')}`,
      fixed_commitments: commitments.length ? commitments : null, location_mode: locationMode,
      pastBatches: journal.slice(0, 5),
    });
    if (data) { setResults(data); saveToJournal(data, filledTasks.length); }
  };

  // ─── Quick dump ───
  const handleDump = async () => {
    if (!dumpText.trim()) return; setDumpLoading(true);
    const data = await callToolEndpoint('batch-flow', { action: 'quick-dump', text: dumpText.trim(), energy_curve: energyCurve || null, day_type: dayType, time_available: timeAvail || null });
    if (data?.batches) { setResults(data); setDumpMode(false); setDumpText(''); saveToJournal(data, (data.extracted_tasks || []).length); }
    else if (data?.extracted_tasks) { setTasks(data.extracted_tasks.map(t => ({ text: t.task, duration: t.inferred_duration || '', location: '' }))); setDumpMode(false); setDumpText(''); }
    setDumpLoading(false);
  };

  // ─── Expand / Move / Progress ───
  const handleExpandBatch = async (batch) => { setExpandedBatch(batch.batch_id); setExpandResult(null); setExpandLoading(true); const d = await callToolEndpoint('batch-flow', { action: 'expand-batch', batch, energy_level: energyCurve || null }); if (d) setExpandResult(d); setExpandLoading(false); };
  const handleMoveTask = (task, from, to) => { if (from === to) { setMovingTask(null); return; } setResults(p => ({ ...p, batches: p.batches.map(b => { if (b.batch_id === from) return { ...b, tasks: b.tasks.filter(t => t.task !== task.task) }; if (b.batch_id === to) return { ...b, tasks: [...b.tasks, task] }; return b; }) })); setMovingTask(null); };
  const handleProgress = async () => { if (!results?.batches?.length) return; setProgressLoading(true); const comp = []; const rem = []; results.batches.forEach((b, bi) => { if (isBatchDone(bi) || completedBatches[bi]) comp.push(b); else rem.push(b); }); const d = await callToolEndpoint('batch-flow', { action: 'progress-update', completedBatches: comp, remainingBatches: rem, energy_level: energyCurve || null, time_remaining: timeAvail || null }); if (d) setProgressResult(d); setProgressLoading(false); };

  // ─── Share / Template ───
  const handleShare = async () => { if (!results?.batches?.length) return; setShareLoading(true); const d = await callToolEndpoint('batch-flow', { action: 'share-plan', batches: results.batches, time_available: timeAvail || null, recipientType: shareRecipient }); if (d) setShareResult(d); setShareLoading(false); };
  const handleSaveTemplate = async () => { if (!results?.batches?.length || !templateName.trim()) return; setSaveTemplateLoading(true); const d = await callToolEndpoint('batch-flow', { action: 'day-template', batches: results.batches, templateName: templateName.trim(), day_type: dayType, energy_curve: energyCurve }); if (d) { setTemplates(p => [{ ...d, id: `tpl_${Date.now()}`, savedAt: new Date().toISOString() }, ...p].slice(0, 20)); setTemplateName(''); setShowSaveTemplate(false); } setSaveTemplateLoading(false); };
  const handleInsights = async () => { if (journal.length < 3) return; setInsightsLoading(true); const d = await callToolEndpoint('batch-flow', { action: 'batch-insights', sessions: journal.slice(0, 15) }); if (d) setInsightsResult(d); setInsightsLoading(false); };

  // ─── v3: A/B Compare ───
  const handleABCompare = async () => {
    if (filledTasks.length === 0) return; setAbLoading(true); setAbResult(null); setAbChoice(null);
    const d = await callToolEndpoint('batch-flow', { action: 'ab-compare', tasks: filledTasks.map(t => ({ task: t.text.trim(), duration: t.duration.trim() || null, location: t.location.trim() || null })), energy_curve: energyCurve || null, time_available: timeAvail || null, fixed_commitments: commitments.length ? commitments : null });
    if (d) setAbResult(d);
    setAbLoading(false);
  };

  const applyABChoice = (choice) => {
    const plan = abResult?.[choice]; if (!plan) return;
    setResults({ ...results, batches: plan.batches, overview: plan.tagline }); setAbChoice(choice); setAbResult(null);
  };

  // ─── v3: Weekly Rhythm ───
  const handleWeeklyRhythm = async () => {
    const filled = weeklyTasks.filter(t => t.task.trim()); if (!filled.length) return; setWeeklyLoading(true);
    const d = await callToolEndpoint('batch-flow', { action: 'weekly-rhythm', recurring_tasks: filled, energy_curve: energyCurve || null, typical_commitments: commitments.length ? commitments.map(c => ({ ...c, day: 'varies' })) : null });
    if (d) setWeeklyResult(d); setWeeklyLoading(false);
  };

  // ─── v3: Resistance check ───
  const handleResistanceCheck = async () => {
    if (deferredList.length < 1) return; setResistLoading(true);
    const d = await callToolEndpoint('batch-flow', { action: 'resistance-check', deferred_tasks: deferredList.slice(0, 10), sessions: journal.length });
    if (d) setResistResult(d); setResistLoading(false);
  };

  // ─── v3: Time calibration ───
  const handleCalibrate = async () => {
    const data = Object.entries(actualTimes).map(([key, actual]) => {
      const [bi, ti] = key.split('-').map(Number);
      const batch = results?.batches?.[bi]; const task = batch?.tasks?.[ti];
      if (!task || !actual) return null;
      return { task: task.task, cognitive_mode: batch.cognitive_mode, estimated: task.time_estimate || '?', actual };
    }).filter(Boolean);
    if (!data.length) return; setCalibLoading(true);
    setTimeHistory(p => [...p, ...data].slice(-100));
    const d = await callToolEndpoint('batch-flow', { action: 'time-calibrate', time_data: data.length >= 3 ? data : timeHistory.concat(data).slice(-20) });
    if (d) setCalibResult(d); setCalibLoading(false);
  };

  // ─── Build copy text ───
  const buildText = () => {
    if (!results) return '';
    const L = ['BATCHFLOW — YOUR BATCHED SCHEDULE', ''];
    if (results.overview) { L.push(results.overview); L.push(''); }
    L.push(`Context switches: ${results.switch_cost_before} → ${results.switch_cost_after} | Saved: ${results.time_saved_estimate}`); L.push('');
    (results.batches || []).forEach(b => { const mi = modeInfo(b.cognitive_mode); L.push(`${mi.emoji} ${b.batch_name} (${b.suggested_time || '?'}) — ${b.estimated_duration || '?'}`); (b.tasks || []).forEach(t => L.push(`  [ ] ${t.task}${t.time_estimate ? ' (' + t.time_estimate + ')' : ''}`)); if (b.break_after) L.push(`  ☕ ${b.break_after}`); L.push(''); });
    L.push(BRAND); return L.join('\n');
  };

  // ─── Shared components ───
  const Pill = ({ options, value, setter }) => <div className="flex flex-wrap gap-1.5">{options.map(o => <button key={o.v} onClick={() => setter(o.v === value ? '' : o.v)} className={`px-3 py-1.5 rounded-lg border text-xs font-semibold transition-all ${c.chip(value === o.v)}`}>{o.l}{o.d && <span className={`block text-xs font-normal ${c.tm}`}>{o.d}</span>}</button>)}</div>;

  // ─── Heatmap Component ───
  const Heatmap = ({ data }) => {
    if (!data?.length) return null;
    const hours = []; for (let h = 8; h <= 20; h++) hours.push(h);
    const hourMap = {}; data.forEach(d => { hourMap[d.hour] = d; });
    return <div className={`${c.card} rounded-xl shadow-lg p-5`}>
      <h3 className={`font-bold text-sm ${c.text} mb-3`}>📊 Cognitive Load Heatmap</h3>
      <div className="flex gap-0.5 items-end h-20">{hours.map(h => {
        const d = hourMap[h]; const intensity = d ? (HEATMAP_INTENSITY[d.intensity] || 0.3) : 0.05;
        const color = d ? modeBarColor(d.mode) : (isDark ? '#3f3f46' : '#e5e7eb');
        return <div key={h} className="flex-1 flex flex-col items-center group relative">
          <div className="w-full rounded-t" style={{ height: `${Math.max(intensity * 100, 8)}%`, backgroundColor: color, opacity: d ? 1 : 0.3, minHeight: 4, transition: 'all 0.3s' }} />
          <span className={`text-xs ${c.tm} mt-1`}>{h > 12 ? h - 12 + 'p' : h + 'a'}</span>
          {d && <div className={`absolute bottom-full mb-2 px-2 py-1 rounded text-xs font-bold ${c.card} ${c.bdr} border shadow-lg hidden group-hover:block whitespace-nowrap z-10`}>{modeInfo(d.mode).emoji} {d.label} ({d.intensity})</div>}
        </div>;
      })}</div>
      <div className="flex flex-wrap gap-3 mt-3">{Object.entries(MODE_COLORS).filter(([k]) => k !== 'break').map(([k, v]) => <span key={k} className={`text-xs flex items-center gap-1 ${c.tm}`}><span className="w-3 h-3 rounded" style={{ backgroundColor: modeBarColor(k) }} />{v.label}</span>)}</div>
    </div>;
  };

  // ═══ RENDER ═══
  return (
    <div className="max-w-4xl mx-auto space-y-5">
      <div><h2 className={`text-2xl font-bold ${c.text}`}>BatchFlow ⚡</h2><p className={`text-sm ${c.tm}`}>Batch similar tasks to protect your focus and minimize mental gear-shifting</p></div>

      {/* Nav */}
      <div className="flex flex-wrap gap-2">
        {journal.length > 0 && <button onClick={() => setShowJournal(!showJournal)} className={`text-xs font-bold ${c.jt}`}>📔 History ({journal.length})</button>}
        {journal.length >= 3 && <button onClick={handleInsights} disabled={insightsLoading} className={`text-xs font-bold ${isDark ? 'text-purple-300' : 'text-purple-600'}`}>{insightsLoading ? '⏳' : '📊 Insights'}</button>}
        {templates.length > 0 && <button onClick={() => setShowTemplates(!showTemplates)} className={`text-xs font-bold ${isDark ? 'text-cyan-300' : 'text-cyan-600'}`}>📋 Templates ({templates.length})</button>}
        <button onClick={() => setShowWeekly(!showWeekly)} className={`text-xs font-bold ${isDark ? 'text-blue-300' : 'text-blue-600'}`}>📅 Weekly Rhythm</button>
        {deferredList.length >= 1 && <button onClick={handleResistanceCheck} disabled={resistLoading} className={`text-xs font-bold ${isDark ? 'text-red-300' : 'text-red-600'}`}>{resistLoading ? '⏳' : `⚠️ ${deferredList.length} stuck tasks`}</button>}
        {timeHistory.length >= 3 && <button onClick={handleCalibrate} disabled={calibLoading} className={`text-xs font-bold ${isDark ? 'text-orange-300' : 'text-orange-600'}`}>{calibLoading ? '⏳' : '⏱️ Time Calibration'}</button>}
      </div>

      {/* Insights / Resistance / Calibration panels */}
      {insightsResult && <div className={`${c.purp} border rounded-xl p-5 space-y-3`}><div className="flex justify-between"><h4 className="font-bold text-sm">📊 Batching Patterns</h4><button onClick={() => setInsightsResult(null)} className={`text-xs ${c.tm}`}>✕</button></div><p className="text-sm">{insightsResult.pattern_summary}</p><div className="grid grid-cols-2 gap-2"><p className="text-xs">⏱️ Saved: {insightsResult.total_time_saved}</p><p className="text-xs">✅ {insightsResult.completion_rate}</p><p className="text-xs">{modeInfo(insightsResult.favorite_mode).emoji} Fave: {insightsResult.favorite_mode}</p><p className="text-xs">🚫 Avoid: {insightsResult.avoided_mode}</p></div><p className="text-xs font-bold">💡 {insightsResult.best_insight}</p><p className={`text-xs italic ${c.ts}`}>{insightsResult.encouragement}</p></div>}

      {resistResult && <div className={`${c.bad} border rounded-xl p-5 space-y-3`}><div className="flex justify-between"><h4 className="font-bold text-sm">⚠️ Stuck Task Analysis</h4><button onClick={() => setResistResult(null)} className={`text-xs ${c.tm}`}>✕</button></div><p className={`text-xs ${c.ts}`}>{resistResult.overall_pattern}</p>{(resistResult.tasks || []).map((t, i) => <div key={i} className={`${c.card} border ${c.bdr} rounded-lg p-3`}><p className={`text-sm font-bold ${c.text}`}>{t.task} <span className="text-xs font-normal">(deferred {t.defer_count}x)</span></p><p className={`text-xs ${c.ts}`}>{t.diagnosis}</p><p className="text-xs font-bold mt-1">Fix: {t.fix}</p></div>)}<p className="text-xs font-bold">💡 {resistResult.meta_insight}</p><button onClick={() => setDeferredTasks({})} className={`text-xs ${c.tm}`}>🗑️ Clear deferred history</button></div>}

      {calibResult && <div className={`${c.warn} border rounded-xl p-5 space-y-3`}><div className="flex justify-between"><h4 className="font-bold text-sm">⏱️ Time Calibration</h4><button onClick={() => setCalibResult(null)} className={`text-xs ${c.tm}`}>✕</button></div><p className="text-sm">{calibResult.overall_accuracy}</p><div className="grid grid-cols-2 gap-2">{(calibResult.mode_breakdown || []).map((m, i) => <p key={i} className="text-xs">{modeInfo(m.mode).emoji} {m.mode}: {m.avg_error}</p>)}</div><p className="text-xs font-bold">💡 {calibResult.calibration_tip}</p><p className={`text-xs italic ${c.ts}`}>{calibResult.fun_stat}</p>{calibResult.adjustment_factor && <p className="text-xs">🔧 Suggested multiplier: <b>×{calibResult.adjustment_factor}</b></p>}</div>}

      {/* Weekly Rhythm */}
      {showWeekly && !results && <div className={`${c.info} border rounded-xl p-5 space-y-3`}><div className="flex justify-between"><h4 className="font-bold text-sm">📅 Weekly Rhythm</h4><button onClick={() => setShowWeekly(false)} className={`text-xs ${c.tm}`}>✕</button></div><p className={`text-xs ${c.ts}`}>Define your recurring tasks and get a weekly batching rhythm</p>
        {weeklyTasks.map((wt, i) => <div key={i} className="flex gap-2"><input value={wt.task} onChange={e => { const u = [...weeklyTasks]; u[i] = { ...u[i], task: e.target.value }; setWeeklyTasks(u); }} placeholder="Recurring task..." className={`flex-1 p-2 border rounded-lg text-sm ${c.input}`} /><input value={wt.duration} onChange={e => { const u = [...weeklyTasks]; u[i] = { ...u[i], duration: e.target.value }; setWeeklyTasks(u); }} placeholder="~30 min" className={`w-20 p-2 border rounded-lg text-xs ${c.input}`} />{weeklyTasks.length > 1 && <button onClick={() => setWeeklyTasks(p => p.filter((_,idx) => idx !== i))} className={`px-2 rounded ${c.sec}`}>✕</button>}</div>)}
        <button onClick={() => setWeeklyTasks(p => [...p, { task: '', frequency: 'weekly', preferred_day: '', duration: '' }])} className={`text-xs ${c.tm}`}>+ Add task</button>
        <button onClick={handleWeeklyRhythm} disabled={weeklyLoading} className={`w-full py-2.5 rounded-xl text-sm font-bold ${c.pri} disabled:opacity-50`}>{weeklyLoading ? '⏳' : '📅 Build Weekly Rhythm'}</button>
        {weeklyResult && <div className="space-y-3"><p className={`text-sm font-bold ${c.text}`}>{weeklyResult.rhythm_name}</p><p className={`text-xs ${c.ts}`}>{weeklyResult.overview}</p>
          {(weeklyResult.days || []).map((d, di) => <div key={di} className={`${c.card} border ${c.bdr} rounded-lg p-3`}><div className="flex justify-between mb-1"><span className={`text-sm font-bold ${c.text}`}>{d.day}</span><span className={`text-xs px-2 py-0.5 rounded-full ${c.ok} border`}>{d.theme}</span></div>
            {(d.batches || []).map((b, bi) => <div key={bi} className={`text-xs ${c.ts} ml-2`}>{modeInfo(b.cognitive_mode).emoji} {b.batch_name} ({b.suggested_time}) — {b.tasks?.join(', ')}</div>)}
            {d.day_note && <p className={`text-xs italic ${c.tm} mt-1`}>{d.day_note}</p>}
          </div>)}
          {weeklyResult.adaptation_tip && <p className={`text-xs ${c.ts}`}>💡 {weeklyResult.adaptation_tip}</p>}
        </div>}
      </div>}

      {/* Templates / Journal */}
      {showTemplates && <div className={`${c.info} border rounded-xl p-4 space-y-2`}><div className="flex justify-between"><h4 className="font-bold text-sm">📋 Templates</h4><button onClick={() => setShowTemplates(false)} className={`text-xs ${c.tm}`}>✕</button></div>{templates.map(tpl => <div key={tpl.id} className={`${c.card} border ${c.bdr} rounded-lg p-3 flex justify-between items-center`}><div><p className={`text-sm font-bold ${c.text}`}>{tpl.template_name}</p><p className={`text-xs ${c.tm}`}>{tpl.description}</p></div><div className="flex gap-2"><button onClick={() => { if (tpl.day_type) setDayType(tpl.day_type); if (tpl.energy_curve) setEnergyCurve(tpl.energy_curve); setShowTemplates(false); }} className={`text-xs font-bold px-2 py-1 rounded ${c.sec}`}>Use</button><button onClick={() => setTemplates(p => p.filter(t => t.id !== tpl.id))} className={`text-xs ${c.tm}`}>🗑️</button></div></div>)}</div>}

      {showJournal && <div className={`${c.jnl} border rounded-xl p-4 space-y-2`}><div className="flex justify-between"><h4 className={`font-bold text-sm ${c.jt}`}>📔 History</h4><button onClick={() => setShowJournal(false)} className={`text-xs ${c.tm}`}>✕</button></div>{journal.map(e => <div key={e.id} className={`${c.card} border ${c.bdr} rounded-lg p-3 flex justify-between`}><span className={`text-xs ${c.ts}`}>{(() => { try { const d = Math.floor((Date.now() - new Date(e.date)) / 86400000); return d === 0 ? 'Today' : d === 1 ? 'Yesterday' : `${d}d ago`; } catch { return ''; } })()} · {e.totalTasks} tasks · {e.batchCount} batches · saved {e.timeSaved}</span><button onClick={() => setJournal(p => p.filter(j => j.id !== e.id))} className={`text-xs ${c.tm}`}>🗑️</button></div>)}</div>}

      {/* ═══ INPUT VIEW ═══ */}
      {!results && !abResult && <div className="space-y-5">
        <div className={`${c.card} rounded-xl shadow-lg p-5`}><label className={`block font-semibold text-sm ${c.text} mb-3`}>What kind of day?</label><div className="flex flex-wrap gap-2">{DAY_OPTS.map(o => <button key={o.v} onClick={() => setDayType(o.v === dayType ? 'mixed' : o.v)} className={`px-3 py-2 rounded-lg border text-xs font-semibold ${c.chip(dayType === o.v)}`}><span className="block">{o.l}</span><span className={`block text-xs font-normal ${c.tm}`}>{o.d}</span></button>)}</div></div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div className={`${c.card} rounded-xl shadow-lg p-5`}><label className={`block font-semibold text-sm ${c.text} mb-3`}>Energy pattern</label><Pill options={ENERGY_OPTS} value={energyCurve} setter={setEnergyCurve} /></div>
          <div className={`${c.card} rounded-xl shadow-lg p-5`}><label className={`block font-semibold text-sm ${c.text} mb-3`}>Time available</label><Pill options={TIME_OPTS} value={timeAvail} setter={setTimeAvail} /></div>
        </div>

        {/* Toggles */}
        <div className="flex gap-2 flex-wrap">
          <button onClick={() => setDumpMode(!dumpMode)} className={`text-xs font-bold px-3 py-1.5 rounded-lg border ${dumpMode ? c.chip(true) : c.chip(false)}`}>{dumpMode ? '📝 Task list' : '📋 Paste list'}</button>
          <button onClick={() => setLocationMode(!locationMode)} className={`text-xs font-bold px-3 py-1.5 rounded-lg border ${locationMode ? c.chip(true) : c.chip(false)}`}>{locationMode ? '📍 Location ON' : '📍 Location mode'}</button>
          <button onClick={() => setShowCommitments(!showCommitments)} className={`text-xs font-bold px-3 py-1.5 rounded-lg border ${commitments.length ? c.chip(true) : c.chip(false)}`}>🔒 Fixed times {commitments.length ? `(${commitments.length})` : ''}</button>
        </div>

        {/* Fixed commitments */}
        {showCommitments && <div className={`${c.card} rounded-xl shadow-lg p-5 space-y-3`}>
          <p className={`text-sm font-bold ${c.text}`}>🔒 Fixed Commitments</p>
          <p className={`text-xs ${c.tm}`}>Meetings, pickups, appointments — we'll batch around these</p>
          {commitments.map((cm, i) => <div key={i} className={`flex items-center gap-2 text-sm ${c.ts}`}><span className="font-bold">{cm.time}</span> — {cm.label}<button onClick={() => setCommitments(p => p.filter((_, idx) => idx !== i))} className={`text-xs ${c.tm}`}>✕</button></div>)}
          <div className="flex gap-2"><input value={newCommitTime} onChange={e => setNewCommitTime(e.target.value)} placeholder="2:00 PM" className={`w-24 p-2 border rounded-lg text-xs ${c.input}`} /><input value={newCommitLabel} onChange={e => setNewCommitLabel(e.target.value)} placeholder="Team standup" className={`flex-1 p-2 border rounded-lg text-xs ${c.input}`} /><button onClick={addCommitment} className={`px-3 py-2 rounded-lg text-xs font-bold ${c.sec}`}>Add</button></div>
        </div>}

        {/* Quick dump */}
        {dumpMode && <div className={`${c.card} rounded-xl shadow-lg p-5 space-y-3`}><p className={`text-sm font-bold ${c.text}`}>📋 Paste your task list</p><textarea value={dumpText} onChange={e => setDumpText(e.target.value)} placeholder="- email sarah&#10;- write report&#10;- call dentist&#10;- grocery shopping" rows={6} className={`w-full px-3 py-2.5 border rounded-lg text-sm ${c.input}`} /><button onClick={handleDump} disabled={dumpLoading || !dumpText.trim()} className={`w-full py-3 rounded-xl font-bold text-sm ${c.pri} disabled:opacity-50`}>{dumpLoading ? '⏳ Extracting...' : '⚡ Extract & Batch'}</button></div>}

        {/* Tasks */}
        {!dumpMode && <>
          <div className={`${c.card} rounded-xl shadow-lg p-5 ${validFail ? 'ring-2 ring-emerald-500' : ''}`}>
            <label className={`block font-semibold text-sm ${c.text} mb-1`}>What's on your plate? <span className="text-red-500">*</span></label>
            <p className={`text-xs ${validFail ? 'text-red-500' : c.tm} mb-4`}>{validFail ? 'Add at least one task' : "List everything — we'll batch by cognitive mode"}</p>
            <div className="space-y-3 mb-4">{tasks.map((task, i) => <div key={i}><div className="flex gap-2"><input type="text" value={task.text} onChange={e => { updateTask(i, 'text', e.target.value); if (validFail) setValidFail(false); }} onKeyDown={e => { if (e.key === 'Enter' && !e.metaKey && !e.ctrlKey) { e.preventDefault(); if (i === tasks.length - 1 && task.text.trim()) addTask(); } if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && filledTasks.length > 0) { e.preventDefault(); handleGenerate(); } }} placeholder={`Task ${i + 1}...`} className={`flex-1 p-3 border rounded-lg outline-none text-sm focus:ring-2 focus:ring-emerald-300 ${c.input}`} /><button onClick={() => toggleDetail(i)} className={`px-3 rounded-lg border text-sm ${showDetails[i] ? c.chip(true) : c.chip(false)}`}>ℹ️</button>{tasks.length > 1 && <button onClick={() => removeTask(i)} className={`px-3 rounded-lg ${c.sec}`}>✕</button>}</div>{showDetails[i] && <div className="flex gap-2 mt-2"><input type="text" value={task.duration} onChange={e => updateTask(i, 'duration', e.target.value)} placeholder="Duration?" className={`flex-1 p-2 border rounded-lg text-xs ${c.input}`} /><input type="text" value={task.location} onChange={e => updateTask(i, 'location', e.target.value)} placeholder="Location?" className={`flex-1 p-2 border rounded-lg text-xs ${c.input}`} /></div>}</div>)}</div>
            <button onClick={addTask} className={`w-full py-2 rounded-lg border text-sm font-medium ${c.chip(false)}`}>+ Add Another Task</button>
          </div>

          <div className="flex gap-3">
            <button onClick={handleGenerate} disabled={loading} className={`flex-1 py-4 rounded-xl font-semibold text-lg flex items-center justify-center gap-2 shadow-lg ${loading ? (isDark ? 'bg-zinc-700 text-zinc-400' : 'bg-gray-200 text-gray-400') : c.pri}`}>{loading ? <><span className="animate-spin">⏳</span> Batching...</> : <>⚡ Batch My Tasks</>}</button>
            {filledTasks.length >= 2 && <button onClick={handleABCompare} disabled={abLoading} className={`px-6 py-4 rounded-xl font-semibold text-sm shadow-lg ${abLoading ? (isDark ? 'bg-zinc-700 text-zinc-400' : 'bg-gray-200 text-gray-400') : (isDark ? 'bg-indigo-600 hover:bg-indigo-500 text-white' : 'bg-indigo-600 hover:bg-indigo-700 text-white')}`}>{abLoading ? '⏳' : '⚖️ Compare'}</button>}
          </div>
          <p className={`text-xs text-center ${c.tm}`}>Enter adds · Ctrl+Enter batches · Compare shows Sprint vs Marathon</p>
        </>}
        {error && <div className={`p-4 rounded-xl ${c.bad} border text-sm`}>⚠️ {error}</div>}
      </div>}

      {/* ═══ A/B COMPARE VIEW ═══ */}
      {abResult && !results && <div className="space-y-5">
        <div className={`${c.card} rounded-xl shadow-lg p-5 text-center`}>
          <h3 className={`text-lg font-bold ${c.text} mb-2`}>⚖️ Pick Your Pace</h3>
          <p className={`text-sm ${c.ts}`}>{abResult.comparison?.recommendation}</p>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {['sprint', 'marathon'].map(key => { const plan = abResult[key]; if (!plan) return null; return <div key={key} className={`${c.card} rounded-xl shadow-lg p-5 border-2 ${key === 'sprint' ? (isDark ? 'border-red-600' : 'border-red-400') : (isDark ? 'border-blue-600' : 'border-blue-400')} space-y-3`}>
            <h4 className={`font-bold text-lg ${c.text}`}>{key === 'sprint' ? '🏃' : '🚶'} {plan.label}</h4>
            <p className={`text-sm ${c.ts}`}>{plan.tagline}</p>
            <p className={`text-xs font-bold ${c.text}`}>Done by: {plan.estimated_end_time}</p>
            <div className="space-y-1">{(plan.batches || []).map((b, i) => <p key={i} className={`text-xs ${c.ts}`}>{modeInfo(b.cognitive_mode).emoji} {b.batch_name} ({b.suggested_time})</p>)}</div>
            <div className="flex gap-4">{(plan.pros || []).map((p, i) => <span key={i} className="text-xs">✅ {p}</span>)}</div>
            <div className="flex gap-4">{(plan.cons || []).map((p, i) => <span key={i} className="text-xs">⚠️ {p}</span>)}</div>
            <p className={`text-xs italic ${c.tm}`}>Best for: {plan.best_for}</p>
            <button onClick={() => applyABChoice(key)} className={`w-full py-2.5 rounded-xl text-sm font-bold ${key === 'sprint' ? (isDark ? 'bg-red-600 hover:bg-red-500 text-white' : 'bg-red-600 hover:bg-red-700 text-white') : c.pri}`}>Choose {plan.label}</button>
          </div>; })}
        </div>
        <div className="text-center"><p className={`text-xs ${c.ts}`}>{abResult.comparison?.time_difference} · {abResult.comparison?.energy_difference}</p></div>
        <button onClick={() => setAbResult(null)} className={`text-xs ${c.tm}`}>← Back to input</button>
      </div>}

      {/* ═══ RESULTS VIEW ═══ */}
      {results && <div className="space-y-5">
        {/* Controls */}
        <div className={`${c.card} rounded-xl shadow-lg p-4 flex items-center justify-between flex-wrap gap-3`}>
          <div className="flex items-center gap-3"><span className={`text-sm font-semibold ${c.text}`}>{(results.batches || []).length} batches</span>{batchProgress.total > 0 && <div className="flex items-center gap-2"><div className={`w-24 h-2 rounded-full ${isDark ? 'bg-zinc-700' : 'bg-gray-200'} overflow-hidden`}><div className="h-full rounded-full bg-emerald-500 transition-all" style={{ width: `${batchProgress.pct}%` }} /></div><span className={`text-xs font-bold ${batchProgress.pct === 100 ? (isDark ? 'text-emerald-400' : 'text-emerald-600') : c.tm}`}>{batchProgress.done}/{batchProgress.total}</span></div>}</div>
          <div className="flex items-center gap-2 flex-wrap">
            <button onClick={handleProgress} disabled={progressLoading} className={`px-3 py-1.5 rounded-lg text-xs font-bold ${c.sec}`}>{progressLoading ? '⏳' : "🔄 What's next?"}</button>
            <button onClick={() => setShowShare(!showShare)} className={`px-3 py-1.5 rounded-lg text-xs font-bold ${c.sec}`}>🤝 Share</button>
            <button onClick={() => setShowSaveTemplate(!showSaveTemplate)} className={`px-3 py-1.5 rounded-lg text-xs font-bold ${c.sec}`}>💾 Template</button>
            <CopyBtn content={buildText()} label="Copy" />
            <button onClick={() => { trackDeferrals(); reset(); }} className={`px-3 py-1.5 rounded-lg text-xs font-bold ${isDark ? 'bg-red-900/30 text-red-300' : 'bg-red-50 text-red-700'}`}>🔄 New</button>
          </div>
        </div>

        {/* Share / Template / Progress panels */}
        {showShare && <div className={`${c.snap} border rounded-xl p-5 space-y-3`}><div className="flex justify-between"><h4 className="font-bold text-sm">🤝 Share Plan</h4><button onClick={() => { setShowShare(false); setShareResult(null); }} className={`text-xs ${c.tm}`}>✕</button></div><Pill options={RECIPIENT_OPTS} value={shareRecipient} setter={setShareRecipient} /><button onClick={handleShare} disabled={shareLoading} className={`w-full py-2.5 rounded-xl text-sm font-bold ${c.pri} disabled:opacity-50`}>{shareLoading ? '⏳' : '📱 Generate'}</button>{shareResult && <div className={`${c.ok} border rounded-xl p-4 space-y-2`}><p className="text-sm whitespace-pre-line">{shareResult.message}</p><CopyBtn content={`${shareResult.message}${BRAND}`} label="Copy" /></div>}</div>}
        {showSaveTemplate && <div className={`${c.info} border rounded-xl p-5 space-y-3`}><h4 className="font-bold text-sm">💾 Save Template</h4><input value={templateName} onChange={e => setTemplateName(e.target.value)} placeholder="e.g. 'My Monday Routine'" className={`w-full px-3 py-2 border rounded-lg text-sm ${c.input}`} /><button onClick={handleSaveTemplate} disabled={saveTemplateLoading || !templateName.trim()} className={`w-full py-2 rounded-xl text-sm font-bold ${c.pri} disabled:opacity-50`}>{saveTemplateLoading ? '⏳' : '💾 Save'}</button></div>}
        {progressResult && <div className={`${c.info} border rounded-xl p-5 space-y-3`}><div className="flex justify-between"><h4 className="font-bold text-sm">🔄 Progress</h4><button onClick={() => setProgressResult(null)} className={`text-xs ${c.tm}`}>✕</button></div><p className="text-sm">{progressResult.acknowledgment}</p>{progressResult.can_stop && <div className={`${c.ok} border rounded-lg p-3 text-xs font-bold`}>✅ {progressResult.stop_reasoning}</div>}{progressResult.next_batch && <p className="text-xs font-bold">→ Next: {progressResult.next_batch}</p>}<p className={`text-xs ${c.ts}`}>🔋 {progressResult.energy_note}</p></div>}

        {/* Heatmap */}
        <Heatmap data={results.heatmap} />

        {/* Efficiency */}
        <div className={`${c.card} rounded-xl shadow-lg p-5 border-l-4 ${isDark ? 'border-emerald-500' : 'border-emerald-400'}`}>
          <h3 className={`text-base font-bold mb-3 ${c.text}`}>⚡ Efficiency Gains</h3>
          <p className={`text-sm ${c.ts} leading-relaxed mb-4`}>{results.overview}</p>
          <div className="flex flex-wrap gap-6">
            <div className="text-center"><div className={`text-2xl font-bold ${isDark ? 'text-red-400' : 'text-red-600'}`}>{results.switch_cost_before}</div><div className={`text-xs ${c.tm}`}>before</div></div>
            <div className="text-center"><div className={`text-2xl font-bold ${isDark ? 'text-emerald-400' : 'text-emerald-600'}`}>{results.switch_cost_after}</div><div className={`text-xs ${c.tm}`}>after</div></div>
            <div className="text-center"><div className={`text-2xl font-bold ${isDark ? 'text-blue-400' : 'text-blue-600'}`}>{results.time_saved_estimate}</div><div className={`text-xs ${c.tm}`}>saved</div></div>
          </div>
        </div>

        {results.day_flow_note && <div className={`${c.ok} border rounded-xl p-4`}><p className="text-sm">🌊 {results.day_flow_note}</p></div>}

        {/* Fixed commitments shown */}
        {results.fixed_commitments_placed?.length > 0 && <div className={`${c.warn} border rounded-xl p-4`}><p className="text-xs font-bold mb-1">🔒 Batched around:</p>{results.fixed_commitments_placed.map((fc, i) => <p key={i} className="text-xs">{fc.time} — {fc.label}{fc.note ? ` (${fc.note})` : ''}</p>)}</div>}

        {/* Batches */}
        {(results.batches || []).map((batch, bi) => {
          const mi = modeInfo(batch.cognitive_mode); const done = isBatchDone(bi);
          return <div key={bi} className={`rounded-xl border-2 p-5 transition-all ${done ? `opacity-60 ${c.card} ${c.bdr}` : `${modeStyle(batch.cognitive_mode)} border`}`}>
            <div className="flex items-start justify-between mb-3 flex-wrap gap-2">
              <div className="flex items-center gap-3"><span className="text-2xl">{mi.emoji}</span><div><h4 className={`font-bold text-sm ${done ? 'line-through' : ''} ${c.text}`}>{batch.batch_name}</h4><p className={`text-xs ${c.ts}`}>{batch.suggested_time} · {batch.estimated_duration}</p></div></div>
              <div className="flex items-center gap-2 flex-wrap">
                <span className={`text-xs font-bold px-2 py-0.5 rounded-full border ${modeStyle(batch.cognitive_mode)}`}>{mi.label}</span>
                {batch.focus_preset && <button onClick={() => setShowFocusPreset(p => ({ ...p, [bi]: !p[bi] }))} className={`text-xs font-bold ${c.tm}`}>{showFocusPreset[bi] ? '🎯 Hide setup' : '🎯 Focus setup'}</button>}
                {!done && <button onClick={() => handleExpandBatch(batch)} disabled={expandLoading && expandedBatch === batch.batch_id} className={`text-xs font-bold ${c.tm}`}>{expandLoading && expandedBatch === batch.batch_id ? '⏳' : '🔍 Expand'}</button>}
                {!done && <button onClick={() => markBatchComplete(bi)} className={`text-xs font-bold ${isDark ? 'text-emerald-400' : 'text-emerald-600'}`}>✓ All done</button>}
                {done && <button onClick={() => setShowTimeInput(showTimeInput === bi ? null : bi)} className={`text-xs font-bold ${isDark ? 'text-orange-300' : 'text-orange-600'}`}>⏱️ Log time</button>}
              </div>
            </div>

            {/* Focus Preset */}
            {showFocusPreset[bi] && batch.focus_preset && <div className={`mb-3 p-3 rounded-lg ${c.cardAlt} border ${c.bdr} grid grid-cols-2 sm:grid-cols-3 gap-2`}>
              <div className="text-xs"><span className={`font-bold ${c.tm}`}>🔔</span> {batch.focus_preset.notifications}</div>
              <div className="text-xs"><span className={`font-bold ${c.tm}`}>🎵</span> {batch.focus_preset.music}</div>
              <div className="text-xs"><span className={`font-bold ${c.tm}`}>🖥️</span> {batch.focus_preset.workspace}</div>
              <div className="text-xs"><span className={`font-bold ${c.tm}`}>📱</span> {batch.focus_preset.phone}</div>
              <div className="text-xs"><span className={`font-bold ${c.tm}`}>🌐</span> {batch.focus_preset.browser_tabs}</div>
              <div className="text-xs col-span-2 sm:col-span-1"><span className={`font-bold ${c.tm}`}>✨</span> {batch.focus_preset.ritual}</div>
            </div>}

            {/* Time input (after batch completion) */}
            {showTimeInput === bi && <div className={`mb-3 p-3 rounded-lg ${c.warn} border space-y-2`}>
              <p className="text-xs font-bold">⏱️ How long did each task actually take?</p>
              {(batch.tasks || []).map((t, ti) => <div key={ti} className="flex items-center gap-2"><span className={`text-xs ${c.ts} flex-1`}>{t.task} (est: {t.time_estimate})</span><input value={actualTimes[`${bi}-${ti}`] || ''} onChange={e => setActualTimes(p => ({ ...p, [`${bi}-${ti}`]: e.target.value }))} placeholder="~25 min" className={`w-24 p-1.5 border rounded text-xs ${c.input}`} /></div>)}
              <button onClick={handleCalibrate} disabled={calibLoading} className={`text-xs font-bold ${c.pri} px-3 py-1.5 rounded-lg`}>{calibLoading ? '⏳' : '📊 Calibrate'}</button>
            </div>}

            {batch.why_batched && <p className={`text-xs italic ${c.ts} mb-3`}>{batch.why_batched}</p>}
            <div className="space-y-2 mb-3">{(batch.tasks || []).map((task, ti) => <div key={ti} className="flex items-center gap-3"><input type="checkbox" checked={!!checked[`b${bi}-${ti}`]} onChange={() => toggleCheck(`b${bi}-${ti}`)} className="w-4 h-4 rounded accent-emerald-500 flex-shrink-0" /><span className={`text-sm flex-1 ${checked[`b${bi}-${ti}`] ? 'line-through opacity-60' : ''} ${c.ts}`}>{task.task}{task.time_estimate && <span className={`text-xs ${c.tm}`}> ({task.time_estimate})</span>}</span><button onClick={() => setMovingTask(movingTask?.task === task.task ? null : { task, fromBatchId: batch.batch_id })} className={`text-xs ${c.tm}`}>{movingTask?.task === task.task ? '📌' : '↔️'}</button></div>)}</div>

            {movingTask && movingTask.fromBatchId !== batch.batch_id && <button onClick={() => handleMoveTask(movingTask.task, movingTask.fromBatchId, batch.batch_id)} className={`w-full py-2 rounded-lg border-2 border-dashed text-xs font-bold ${isDark ? 'border-emerald-600 text-emerald-400' : 'border-emerald-400 text-emerald-600'}`}>📥 Move here</button>}

            {batch.tools_needed?.length > 0 && <p className={`text-xs ${c.tm}`}>🔧 {batch.tools_needed.join(', ')}</p>}
            {batch.environment_tip && <p className={`text-xs ${c.tm}`}>🎯 {batch.environment_tip}</p>}
            {batch.break_after && <p className={`text-xs ${isDark ? 'text-blue-300' : 'text-blue-600'} mt-2`}>☕ {batch.break_after}</p>}

            {expandResult && expandedBatch === batch.batch_id && <div className={`mt-4 ${c.cardAlt} rounded-lg p-4 border ${c.bdr} space-y-3`}><p className={`text-xs font-bold uppercase ${c.tm}`}>Step-by-step</p>{expandResult.prep_steps?.length > 0 && <div>{expandResult.prep_steps.map((s, i) => <p key={i} className={`text-xs ${c.ts}`}>• {s}</p>)}</div>}{(expandResult.execution_plan || []).map((step, si) => <div key={si} className={`${c.card} border ${c.bdr} rounded-lg p-3`}><p className={`text-sm font-semibold ${c.text}`}>{si + 1}. {step.task}</p><p className={`text-xs ${c.ts}`}>→ {step.first_action}</p>{step.momentum_tip && <p className={`text-xs italic ${c.tm}`}>💡 {step.momentum_tip}</p>}<p className={`text-xs ${c.tm}`}>✓ {step.done_signal} · ⏱️ {step.time_estimate}</p></div>)}{expandResult.batch_complete_reward && <p className={`text-xs ${isDark ? 'text-emerald-300' : 'text-emerald-600'}`}>🎁 {expandResult.batch_complete_reward}</p>}<button onClick={() => { setExpandedBatch(null); setExpandResult(null); }} className={`text-xs font-bold ${c.tm}`}>Close</button></div>}
          </div>;
        })}

        {results.unbatchable?.length > 0 && <div className={`${c.warn} border rounded-xl p-4`}><p className="text-xs font-bold mb-1">🔀 Unbatchable:</p>{results.unbatchable.map((t, i) => <p key={i} className="text-xs">• {t}</p>)}</div>}

        <ActionBar content={buildText()} title="BatchFlow" />
        <div><p className={`text-xs ${c.tm} mb-2`}>Related:</p><div className="flex flex-wrap gap-2">{[['CrisisPrioritizer', '🚨', 'urgency triage'], ['BrainDumpStructurer', '🧠', 'organize thoughts'], ['BrainStateDeejay', '🎧', 'shift energy']].map(([id, ico, d]) => <a key={id} href={`/${id}`} target="_blank" rel="noopener noreferrer" className={`text-xs px-3 py-1.5 rounded-lg ${c.sec} border ${c.bdr} no-underline`}>{ico} {d}</a>)}</div></div>
      </div>}
    </div>
  );
};

BatchFlow.displayName = 'BatchFlow';
export default BatchFlow;
