import React, { useState, useEffect, useRef, useCallback } from 'react';
import { useTheme } from '../hooks/useTheme';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { CopyBtn } from '../components/ActionButtons';
import { useRegisterActions } from '../components/ActionBarContext';
import { usePersistentState } from '../hooks/usePersistentState';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

const EXAMPLE_BELIEFS = [
  'Hard work always pays off',
  'Money doesn\'t buy happiness',
  'You should follow your passion',
  'People don\'t change',
  'Everything in moderation',
  'Trust your gut',
  'Forgiveness is always the right choice',
  'Success requires sacrifice',
];

const SEVERITY_CONFIG = {
  fatal:       { label: 'FATAL',       colorKey: 'severityFatal' },
  significant: { label: 'SIGNIFICANT', colorKey: 'severitySignificant' },
  minor:       { label: 'MINOR',       colorKey: 'severityMinor' },
};

const VERDICT_CONFIG = {
  mostly_true:           { icon: '✅', label: 'MOSTLY TRUE',           colorKey: 'verdictTrue' },
  context_dependent:     { icon: '◇',  label: 'CONTEXT-DEPENDENT',     colorKey: 'verdictContext' },
  useful_simplification: { icon: '🔧', label: 'USEFUL SIMPLIFICATION', colorKey: 'verdictUseful' },
  mostly_false:          { icon: '❌', label: 'MOSTLY FALSE',          colorKey: 'verdictFalse' },
  it_depends:            { icon: '🔵', label: 'IT DEPENDS',            colorKey: 'verdictDepends' },
};

const BeliefStressTest = ({ tool }) => {
  const { callToolEndpoint, loading } = useClaudeAPI();
  const { isDark } = useTheme();

  const c = {
    card:          isDark ? 'bg-zinc-800'      : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50'   : 'bg-slate-50',
    cardAltHover:  isDark ? 'hover:bg-zinc-700' : 'hover:bg-gray-100',
    text:          isDark ? 'text-zinc-50'     : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300'    : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-500'    : 'text-gray-400',
    textMuteded:   isDark ? 'text-zinc-500'    : 'text-gray-400',
    input:         isDark
      ? 'bg-zinc-700 border-zinc-600 text-zinc-100 placeholder:text-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20'
      : 'bg-white border-gray-300 text-gray-900 placeholder:text-gray-400 focus:border-cyan-500 focus:ring-cyan-500/20',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-100' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700'  : 'border-gray-200',
    borderHover:   isDark ? 'hover:border-zinc-500' : 'hover:border-gray-400',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200'  : 'bg-red-50 border-red-200 text-red-800',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    required:      isDark ? 'text-amber-400'   : 'text-amber-500',
    amberText:     isDark ? 'text-amber-400'   : 'text-amber-600',
    labelText:     isDark ? 'text-zinc-200'    : 'text-gray-700',
    deleteHover:   'hover:text-red-400',
    // Severity classes (compound: bg + text + border)
    severityFatal:       isDark ? 'bg-red-900/20 text-red-200 border-red-700/50'     : 'bg-red-50 text-red-800 border-red-300',
    severitySignificant: isDark ? 'bg-amber-900/20 text-amber-200 border-amber-700/50' : 'bg-amber-50 text-amber-800 border-amber-300',
    severityMinor:       isDark ? 'bg-zinc-700/60 text-zinc-300 border-zinc-600'       : 'bg-gray-100 text-gray-600 border-gray-300',
    // Verdict classes (compound: bg + border + text)
    verdictTrue:    isDark ? 'bg-green-900/20 border-green-700/50 text-green-200'   : 'bg-green-50 border-green-300 text-green-800',
    verdictContext: isDark ? 'bg-sky-900/20 border-sky-700/50 text-sky-200'         : 'bg-sky-50 border-sky-300 text-sky-800',
    verdictUseful:  isDark ? 'bg-amber-900/20 border-amber-700/50 text-amber-200'   : 'bg-amber-50 border-amber-300 text-amber-800',
    verdictFalse:   isDark ? 'bg-red-900/20 border-red-700/50 text-red-200'         : 'bg-red-50 border-red-300 text-red-800',
    verdictDepends: isDark ? 'bg-zinc-700/60 border-zinc-600 text-zinc-300'         : 'bg-gray-100 border-gray-300 text-gray-600',
  };
  // Always include these two alias lines immediately after the closing brace (per CONVENTIONS.md):
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-600 hover:text-cyan-700 underline underline-offset-2';

  const [belief, setBelief] = usePersistentState('beliefstresstest-belief', '');
  const [history, setHistory] = usePersistentState('beliefstresstest-history', []);
  const [context, setContext] = useState('');
  const [results, setResults] = usePersistentState('beliefstresstest-last', null);
  const [error, setError] = useState('');
  const [expanded, setExpanded] = useState({ tests: true, hidden: false });

  const toggle = (k) => setExpanded(p => ({ ...p, [k]: !p[k] }));

  const handleSubmit = async () => {
    if (!belief.trim()) return;
    setError(''); setResults(null);
    try {
      const data = await callToolEndpoint('belief-stress-test', {
        belief: belief.trim(),
        context: context.trim() || undefined,
      });
      setResults(data);
      const newEntry = {
        id: Date.now(),
        timestamp: new Date().toISOString(),
        preview: belief.trim().slice(0, 40),
        result: data,
      };
      setHistory(prev => [newEntry, ...prev].slice(0, 6));
    } catch (e) { setError(e.message || 'Failed to stress-test belief.'); }
  };

  const handleReset = () => {
    setResults(null);
    setBelief('');
    setContext('');
    setError('');
  };

  const buildFullText = useCallback(() => {
    if (!results) return '';
    let t = `🧪 BELIEF STRESS TEST\n\n"${belief}"\n\n`;
    t += `WHERE IT HOLDS:\n${results.where_it_holds?.the_conditions}\n\n`;
    t += `STRESS TESTS:\n`;
    results.stress_tests?.forEach(st => { t += `• [${st.test_label}] ${st.the_test}\n  ${st.what_it_reveals}\n`; });
    t += `\nTHE UPGRADE:\n${results.the_nuanced_version?.the_upgrade}\n`;
    t += `Conditions: ${results.the_nuanced_version?.the_key_conditions}\n\n`;
    t += `VERDICT: ${results.verdict?.rating_label} — ${results.verdict?.one_line}\n`;
    return t + BRAND;
  }, [results, belief]);

  const vcfg = results ? (VERDICT_CONFIG[results.verdict?.rating] || VERDICT_CONFIG.it_depends) : null;

  // Stale-closure-safe refs for global keyboard handler
  const handleSubmitRef = useRef(null);
  const canSubmitRef = useRef(false);
  handleSubmitRef.current = handleSubmit;
  canSubmitRef.current = !!(belief?.trim()) && !loading;

  useRegisterActions(buildFullText(), tool?.title || 'Belief Stress Test');

  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && canSubmitRef.current) {
        e.preventDefault();
        handleSubmitRef.current?.();
      }
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, []);

  return (
    <div className={`space-y-4 ${c.text}`}>

      {/* Persistent header — shown on every screen (PF-16: reset button top-right) */}
      <div className="pb-3 border-b border-zinc-500">
        <div className="flex items-center justify-between">
          <div>
            <h2 className={`text-xl font-bold ${c.text}`}>
              <span className="mr-2">{tool?.icon ?? '🔬'}</span>{tool?.title ?? 'Belief Stress Test'}
            </h2>
            <p className={`text-sm ${c.textSecondary}`}>{tool?.tagline ?? 'Your guiding beliefs, pressure-tested. Where they hold. Where they break.'}</p>
          </div>
          {(results || belief.trim()) ? (
            <button onClick={handleReset} className={`${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs font-bold flex-shrink-0`}>
              ↺ Start Over
            </button>
          ) : null}
        </div>
      </div>

      {history.length > 0 && !results && (
        <div className={`${c.card} rounded-xl border ${c.border} p-4`}>
          <h3 className={`text-sm font-bold ${c.text} mb-3`}>🕐 Recent Results</h3>
          <div className="space-y-1.5">
            {history.map(entry => (
              <button key={entry.id}
                onClick={() => setResults(entry.result)}
                className={`w-full text-left px-3 py-2 rounded-lg ${c.btnSecondary} border ${c.border} text-xs`}>
                <span className={c.textMuteded}>
                  {new Date(entry.timestamp).toLocaleDateString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })}
                </span>
                <span className={`ml-2 ${c.text}`}>{entry.preview}…</span>
              </button>
            ))}
          </div>
        </div>
      )}

      {!results && (
          <div className={`${c.card} rounded-xl shadow-lg p-5 space-y-4`}>
            <div>
              <label className={`block text-sm font-semibold mb-1.5 ${c.text}`}>
                A belief that guides your life <span className={c.required}>*</span>
              </label>
              <textarea value={belief} onChange={e => setBelief(e.target.value)}
                placeholder="A principle, rule, or conviction you operate by…"
                rows={2} maxLength={300}
                onKeyDown={e => { if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && belief.trim()) { e.preventDefault(); handleSubmit(); } }}
                className={`w-full px-4 py-3 rounded-xl border text-sm resize-none ${c.input} focus:outline-none focus:ring-2`} />
              <div className="flex flex-wrap gap-2 mt-2">
                {EXAMPLE_BELIEFS.map(b => (
                  <button key={b} onClick={() => { setBelief(b); setResults(null); }}
                    className={`px-2.5 py-1 rounded-lg text-xs ${c.btnSecondary}`}>
                    {b}
                  </button>
                ))}
              </div>
            </div>

            <div>
              <label className={`block text-sm font-semibold mb-1.5 ${c.text}`}>Your context <span className={`font-normal ${c.textMuteded}`}>(optional)</span></label>
              <input type="text" value={context} onChange={e => setContext(e.target.value)}
                placeholder="How this belief shows up in your life, where you apply it most…"
                onKeyDown={e => { if (e.key === 'Enter' && belief.trim()) { e.preventDefault(); handleSubmit(); } }}
                className={`w-full px-4 py-3 rounded-xl border text-sm ${c.input} focus:outline-none focus:ring-2`} />
            </div>

            {error && <div className={`p-3 rounded-xl border text-sm ${c.danger}`}><span className="mr-1">⚠️</span>{error}</div>}

            <p className={`text-xs text-center ${c.textMuteded}`}>
              Want to challenge a specific claim first?{' '}
              <a href="/TheFinalWord" className={linkStyle}>The Final Word</a> fact-checks a statement before you stress-test the belief behind it.
            </p>

            <button onClick={handleSubmit} disabled={loading || !belief.trim()}
              className={`w-full py-3 rounded-xl font-bold disabled:opacity-40 ${c.btnPrimary}`}>
              {loading ? <><span className="animate-spin inline-block mr-2">{tool?.icon ?? '🔬'}</span>Running stress tests…</> : <><span className="mr-2">{tool?.icon ?? '🔬'}</span>Run the Stress Test</>}
            </button>
          </div>
        )}

        {results && (
          <div className="space-y-4">


            {/* Verdict */}
            {results.verdict && (
              <div className={`rounded-2xl border p-5 text-center ${c[vcfg.colorKey] || c.text}`}>
                <p className="text-3xl mb-2">{vcfg.icon}</p>
                <p className="text-xl font-black tracking-tight">{results.verdict.rating_label}</p>
                <p className="text-sm mt-1 opacity-80">{results.verdict.one_line}</p>
              </div>
            )}

            {/* Where it holds */}
            {results.where_it_holds && (
              <div className={`rounded-2xl border p-5 ${isDark ? 'bg-green-900/20 border-green-700/50' : 'bg-green-50 border-green-200'}`}>
                <p className={`text-xs font-black uppercase tracking-widest mb-3 ${isDark ? 'text-green-300' : 'text-green-700'}`}>✅ Where It Holds</p>
                <p className={`text-sm font-semibold mb-2 ${c.text}`}>{results.where_it_holds.the_conditions}</p>
                {results.where_it_holds.the_evidence_for && (
                  <p className={`text-xs mb-1 ${c.textMuteded}`}><span className="font-semibold">Evidence for it:</span> {results.where_it_holds.the_evidence_for}</p>
                )}
                {results.where_it_holds.why_people_hold_it && (
                  <p className={`text-xs ${c.textMuteded}`}><span className="font-semibold">Why it spread:</span> {results.where_it_holds.why_people_hold_it}</p>
                )}
              </div>
            )}

            {/* Stress tests */}
            {results.stress_tests?.length > 0 && (
              <div className={`rounded-2xl border overflow-hidden ${c.card} border ${c.border}`}>
                <button onClick={() => toggle('tests')} className="w-full text-left px-5 py-4 flex items-center justify-between">
                  <p className={`text-xs font-black uppercase tracking-widest ${isDark ? 'text-red-300' : 'text-red-700'}`}>
                    🔬 Stress Tests ({results.stress_tests.length})
                  </p>
                  <span className={`text-sm ${c.textMuteded}`}>{expanded.tests ? '▲' : '▼'}</span>
                </button>
                {expanded.tests && (
                  <div className={`border-t ${c.border}`}>
                    {results.stress_tests.map((st, i) => {
                      const scfg = SEVERITY_CONFIG[st.severity] || SEVERITY_CONFIG.minor;
                      return (
                        <div key={i} className={`px-5 py-4 ${i > 0 ? `border-t ${c.border}` : ''}`}>
                          <div className="flex items-center gap-2 mb-2 flex-wrap">
                            <span className={`text-xs font-bold px-2 py-0.5 rounded-full border ${c[scfg.colorKey] || c.textMuted}`}>{scfg.label}</span>
                            <span className={`text-xs font-semibold ${c.textMuteded}`}>{st.test_label}</span>
                          </div>
                          <p className={`text-sm font-semibold mb-1 ${c.text}`}>{st.the_test}</p>
                          <p className={`text-xs ${c.textMuteded}`}>{st.what_it_reveals}</p>
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>
            )}

            {/* Hidden structure */}
            {results.the_hidden_structure && (
              <div className={`rounded-2xl border overflow-hidden ${c.card} border ${c.border}`}>
                <button onClick={() => toggle('hidden')} className="w-full text-left px-5 py-4 flex items-center justify-between">
                  <p className={`text-xs font-bold uppercase tracking-wider ${c.textMuteded}`}>🔦 The Hidden Structure</p>
                  <span className={`text-sm ${c.textMuteded}`}>{expanded.hidden ? '▲' : '▼'}</span>
                </button>
                {expanded.hidden && (
                  <div className={`px-5 pb-4 space-y-3 border-t ${c.border} pt-4`}>
                    {results.the_hidden_structure.what_its_really_saying && (
                      <p className={`text-sm ${c.textSecondary}`}><span className={`font-semibold ${c.text}`}>What it's really saying:</span> {results.the_hidden_structure.what_its_really_saying}</p>
                    )}
                    {results.the_hidden_structure.the_psychological_function && (
                      <p className={`text-sm ${c.textSecondary}`}><span className={`font-semibold ${c.text}`}>Psychological function:</span> {results.the_hidden_structure.the_psychological_function}</p>
                    )}
                    {results.the_hidden_structure.when_it_becomes_harmful && (
                      <div className={`p-3 rounded-xl border ${isDark ? 'bg-red-900/15 border-red-700/40' : 'bg-red-50 border-red-200'}`}>
                        <p className={`text-xs font-bold uppercase tracking-wide mb-1 ${isDark ? 'text-red-300' : 'text-red-700'}`}>When it becomes harmful</p>
                        <p className={`text-sm ${c.textSecondary}`}>{results.the_hidden_structure.when_it_becomes_harmful}</p>
                      </div>
                    )}
                  </div>
                )}
              </div>
            )}

            {/* The nuanced version */}
            {results.the_nuanced_version && (
              <div className={`rounded-2xl border-2 p-5 ${isDark ? 'border-sky-700 bg-sky-900/20' : 'border-sky-300 bg-sky-50'}`}>
                <p className={`text-xs font-black uppercase tracking-widest mb-3 ${isDark ? 'text-sky-300' : 'text-sky-700'}`}>⬆️ The Upgrade</p>
                <p className={`text-sm font-bold mb-2 ${c.text}`}>{results.the_nuanced_version.the_upgrade}</p>
                {results.the_nuanced_version.the_key_conditions && (
                  <p className={`text-xs mb-2 ${c.textMuteded}`}><span className="font-semibold">When it's actually true:</span> {results.the_nuanced_version.the_key_conditions}</p>
                )}
                {results.the_nuanced_version.example_of_upgrade_in_action && (
                  <p className={`text-xs mb-3 italic ${c.textMuteded}`}>{results.the_nuanced_version.example_of_upgrade_in_action}</p>
                )}
                <CopyBtn content={`🧪 Upgraded belief:\n\n${results.the_nuanced_version.the_upgrade}${BRAND}`} label="Copy Upgrade" />
              </div>
            )}



            <div className="space-y-2">
              <p className={`text-xs text-center ${c.textMuteded}`}>
                Want to go deeper?{' '}
                <a href="/EgoKiller" className={linkStyle}>Ego Killer</a>{' '}
                runs a full demolition-and-rebuild on the assumptions behind your worldview.
              </p>
              {results?.verdict?.rating === 'mostly_false' && (
                <p className={`text-xs text-center ${c.textMuteded}`}>
                  This belief didn't hold up well.{' '}
                  <a href="/EgoKiller" className={linkStyle}>Ego Killer</a>{' '}
                  can help you replace it with something that does.
                </p>
              )}
              {(results?.stress_tests?.some(st => st.severity === 'fatal')) && results?.verdict?.rating !== 'mostly_false' && (
                <p className={`text-xs text-center ${c.textMuteded}`}>
                  Fatal stress tests found.{' '}
                  <a href="/TheFinalWord" className={linkStyle}>The Final Word</a>{' '}
                  can fact-check the specific claims those tests surface.
                </p>
              )}
            </div>
          </div>
        )}

        <div className={`mt-6 pt-4 border-t text-sm ${c.border} ${c.textMuted}`}>
          <p className="mb-2 font-medium">You might also like:</p>
          <div className="flex flex-wrap gap-2">
            {[{slug:'EgoKiller',label:'🪞 Ego Killer'},{slug:'DebateMe',label:'⚔️ Debate Me'},{slug:'TruthBomb',label:'💣 Truth Bomb'}].map(({slug,label})=>(
              <a key={slug} href={`/${slug}`} className={linkStyle}>{label}</a>
            ))}
          </div>
        </div>
      </div>
  );
};

BeliefStressTest.displayName = 'BeliefStressTest';
export default BeliefStressTest;
