import React, { useState, useCallback, useRef, useEffect } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';


const EXAMPLE = {
  industry: 'B2B SaaS',
  level: 'senior',
  accomplishments: [
    'Led the migration of our payment processing system from a legacy monolith to a microservices architecture, reducing checkout latency by 38% and eliminating a class of timeout-related support tickets that had been the #1 source of customer complaints.',
    'Mentored 3 mid-level engineers; two were promoted to senior within 18 months. One specifically credited our weekly 1:1s on technical scoping as the thing that unlocked the promotion.',
    "Found and fixed a memory leak in our background job processor that was causing daily 3am pages. Wrote up the postmortem; it became required reading for new infra hires.",
    "Drove the decision to standardize on TypeScript across the front-end. Wrote the migration guide, ran two lunch-and-learns. 80% of the codebase converted in 6 months.",
    'Negotiated with the security team to ship our SOC 2 Type II certification 6 weeks ahead of the original timeline by parallelizing the audit with our existing infra hardening work.',
    'Quietly maintained the on-call rotation tooling for two years — no one noticed because it just worked. Saved the team an estimated 40 hours/quarter in manual scheduling.',
    "Pushed back (politely) on a leadership request to ship a feature on a 2-week timeline that needed 6. We ended up shipping in 4 with the right scope. The PM later said it was the highest-NPS launch of the quarter.",
  ],
  currentEntry: '',
};
const BragSheetBuilder = ({ tool }) => {
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();

  // ─── Theme ───

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20'
                          : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-400' : 'text-gray-500',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white'
                          : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200'
                          : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200'
                          : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200'
                          : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200'
                          : 'bg-red-50 border-red-200 text-red-800',
    required:      isDark ? 'text-amber-400' : 'text-amber-700',
    tab:           (active) => active
                     ? (isDark ? 'border-cyan-400 text-cyan-300' : 'border-cyan-600 text-cyan-700')
                     : (isDark ? 'border-transparent text-zinc-400 hover:text-zinc-200' : 'border-transparent text-gray-500 hover:text-gray-700'),
    // ── Extended keys ──
    chip:           (active) => active
                      ? (isDark ? 'bg-cyan-900/40 border-cyan-600 text-cyan-200' : 'bg-cyan-100 border-cyan-400 text-cyan-800')
                      : (isDark ? 'bg-zinc-700 border-zinc-600 text-zinc-300 hover:border-zinc-500' : 'bg-gray-100 border-gray-200 text-gray-600 hover:border-gray-400'),
    highlightText:  isDark ? 'text-cyan-400' : 'text-cyan-600',
    highlightAlt:   isDark ? 'text-emerald-400' : 'text-emerald-600',
    highlightBg:    isDark ? 'bg-cyan-900/20 border-cyan-700' : 'bg-cyan-50 border-cyan-200',
    beforeBg:       isDark ? 'bg-zinc-700/50 border-zinc-600' : 'bg-slate-100 border-slate-200',
    afterBg:        isDark ? 'bg-emerald-900/20 border-emerald-700' : 'bg-emerald-50 border-emerald-200',
    hoverBg:        isDark ? 'hover:bg-zinc-700/50' : 'hover:bg-slate-100',
    removeBtn:      isDark ? 'text-zinc-500 hover:text-red-400 text-xs px-1.5' : 'text-gray-400 hover:text-red-500 text-xs px-1.5',
    btnLoading:     isDark ? 'bg-zinc-700 text-zinc-400' : 'bg-slate-200 text-slate-400',
    scoreBg:        isDark ? 'bg-zinc-700' : 'bg-gray-200',
    scoreHigh:      isDark ? 'bg-emerald-500' : 'bg-emerald-500',
    scoreMid:       isDark ? 'bg-amber-500' : 'bg-amber-500',
    scoreLow:       isDark ? 'bg-red-500' : 'bg-red-500',
    starBadge:      isDark ? 'bg-cyan-900/40 text-cyan-300' : 'bg-cyan-100 text-cyan-700',
    upgradeTag:     isDark ? 'bg-emerald-900/40 text-emerald-300' : 'bg-emerald-100 text-emerald-700',
    tweakTag:       isDark ? 'bg-amber-900/40 text-amber-300' : 'bg-amber-100 text-amber-700',
    preUpgradeBg:   isDark ? 'bg-zinc-700/40' : 'bg-slate-100',
    successFg:      isDark ? 'text-emerald-400' : 'text-emerald-600',
    journalBorder:  isDark ? 'border-cyan-700' : 'border-cyan-300',
    addMoreBorder:  isDark ? 'border-cyan-700' : 'border-cyan-400',
    excavatorBtn:   isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200 border border-zinc-600' : 'bg-gray-100 hover:bg-gray-200 text-gray-700 border border-gray-200',
    excavatorPanel: isDark ? 'bg-zinc-800/80 border-cyan-700' : 'bg-cyan-50 border-cyan-300',
    closingNote:    isDark ? 'bg-zinc-800' : 'bg-slate-50',
    savedBtn:       isDark ? 'bg-emerald-900/30 text-emerald-300 border-emerald-700' : 'bg-emerald-50 text-emerald-700 border-emerald-300',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';

  // ─── Constants ───
  const INDUSTRIES = [
    { value: 'tech', label: t('bsb_ind_tech') }, { value: 'finance', label: t('bsb_ind_finance') },
    { value: 'healthcare', label: t('bsb_ind_healthcare') }, { value: 'education', label: t('bsb_ind_education') },
    { value: 'marketing', label: t('bsb_ind_marketing') }, { value: 'sales', label: t('bsb_ind_sales') },
    { value: 'consulting', label: t('bsb_ind_consulting') }, { value: 'nonprofit', label: t('bsb_ind_nonprofit') },
    { value: 'engineering', label: t('bsb_ind_engineering') }, { value: 'government', label: t('bsb_ind_government') },
    { value: 'retail', label: t('bsb_ind_retail') }, { value: 'other', label: t('bsb_ind_other') },
  ];
  const LEVELS = [
    { value: 'entry', label: t('bsb_lvl_entry'), icon: '🌱' }, { value: 'mid', label: t('bsb_lvl_mid'), icon: '📈' },
    { value: 'senior', label: t('bsb_lvl_senior'), icon: '⭐' }, { value: 'manager', label: t('bsb_lvl_manager'), icon: '🎯' },
    { value: 'executive', label: t('bsb_lvl_executive'), icon: '👔' }, { value: 'student', label: t('bsb_lvl_student'), icon: '🎓' },
  ];
  const PURPOSES = [
    { value: 'resume', label: t('bsb_pur_resume'), icon: '📄' }, { value: 'linkedin', label: t('bsb_pur_linkedin'), icon: '💼' },
    { value: 'interview', label: t('bsb_pur_interview'), icon: '💬' }, { value: 'review', label: t('bsb_pur_review'), icon: '⭐' },
    { value: 'raise', label: t('bsb_pur_raise'), icon: '📈' },
  ];
  const TONES = [
    { value: 'confident', label: t('bsb_tone_confident'), icon: '🔥' },
    { value: 'balanced', label: t('bsb_tone_balanced'), icon: '⚖️' },
    { value: 'understated', label: t('bsb_tone_understated'), icon: '🎯' },
  ];

  // ─── Input State ───
  const [currentEntry, setCurrentEntry] = useState('');
  const [savedFeedback, setSavedFeedback] = useState(false);
  const [error, setError] = useState('');
  const [activeTab, setActiveTab] = useState('transform');
  const [expandedSections, setExpandedSections] = useState({});

  // ─── Refine State ───
  const [metricsAnswers, setMetricsAnswers] = useState({});
  const [refineLoading, setRefineLoading] = useState(false);
  const [refinedData, setRefinedData] = useState(null);
  const [refineRound, setRefineRound] = useState(0);
  const [preUpgradeVersions, setPreUpgradeVersions] = useState({});

  // ─── Tweak State ───
  const [tweakingIdx, setTweakingIdx] = useState(null);
  const [tweakInstruction, setTweakInstruction] = useState('');
  const [tweakLoading, setTweakLoading] = useState(false);

  // ─── Add Single State ───
  const [addingMore, setAddingMore] = useState(false);
  const [newEntry, setNewEntry] = useState('');
  const [addSingleLoading, setAddSingleLoading] = useState(false);

  // ─── STAR State ───
  const [starLoading, setStarLoading] = useState(null);
  const [starQuestion, setStarQuestion] = useState('');
  const [starSelectIdx, setStarSelectIdx] = useState(null);
  const [customStarStories, setCustomStarStories] = useState([]);

  // ─── Excavator State ───
  const [showExcavator, setShowExcavator] = useState(false);
  const [excavatorData, setExcavatorData] = useState(null);
  const [excavatorLoading, setExcavatorLoading] = useState(false);

  // ─── Journal State ───
  const [showJournal, setShowJournal] = useState(false);
  const [journalEntry, setJournalEntry] = useState('');

  // ─── Radar State ───
  const [radarData, setRadarData] = useState(null);
  const [radarLoading, setRadarLoading] = useState(false);

  // ─── JD Tailor State ───
  const [jdText, setJdText] = useState('');
  const [tailorData, setTailorData] = useState(null);
  const [tailorLoading, setTailorLoading] = useState(false);

  // ─── Interview Matrix State ───
  const [matrixData, setMatrixData] = useState(null);
  const [matrixLoading, setMatrixLoading] = useState(false);

  // ─── Voice Match State ───
  const [voiceSample, setVoiceSample] = useState('');
  const [voiceData, setVoiceData] = useState(null);
  const [voiceLoading, setVoiceLoading] = useState(false);
  const [accomplishments, setAccomplishments] = usePersistentState('brag-accomplishments', []);
  const [industry, setIndustry] = usePersistentState('brag-industry', '');
  const [level, setLevel] = usePersistentState('brag-level', '');
  const [purposes, setPurposes] = usePersistentState('brag-purposes', ['resume']);
  const [roleTitle, setRoleTitle] = usePersistentState('brag-role-title', '');
  const [yearsExp, setYearsExp] = usePersistentState('brag-years-exp', '');
  const [tone, setTone] = usePersistentState('brag-tone', 'balanced');

  // ─── Results State ───
  const [results, setResults] = usePersistentState('brag-last-result', null);

  // ─── Persistent State ───
  const [savedAccomplishments, setSavedAccomplishments] = usePersistentState('brag-saved', []);
  const [journal, setJournal] = usePersistentState('brag-journal', []);
  const [sessionHistory, setSessionHistory] = usePersistentState('brag-history', []);

  const entryRef = useRef(null);
  const resultsRef = useRef(null);
  const handleSubmitRef = useRef(null);
  const canSubmitRef = useRef(false);

  // ═══════════════════════════════════════════
  // HANDLERS
  // ═══════════════════════════════════════════
  const addAccomplishment = useCallback(() => {
    const text = currentEntry.trim();
    if (!text) return;
    setAccomplishments(prev => [...prev, text]);
    setCurrentEntry('');
    entryRef.current?.focus();
  }, [currentEntry]);

  const removeAccomplishment = useCallback((idx) => setAccomplishments(prev => prev.filter((_, i) => i !== idx)), []);
  const togglePurpose = useCallback((p) => setPurposes(prev => prev.includes(p) ? prev.filter(x => x !== p) : [...prev, p]), []);
  const toggleSection = (key) => setExpandedSections(prev => ({ ...prev, [key]: !prev[key] }));

  const handleBuild = async () => {
    const all = [...accomplishments];
    if (currentEntry.trim()) { all.push(currentEntry.trim()); setAccomplishments(all); setCurrentEntry(''); }
    if (all.length === 0) { setError(t('bsb_err_add_one')); return; }
    setError(''); setResults(null); setRefinedData(null); setMetricsAnswers({}); setRefineRound(0);
    setPreUpgradeVersions({}); setCustomStarStories([]);
    setRadarData(null); setTailorData(null); setMatrixData(null); setVoiceData(null);
    try {
      const data = await callToolEndpoint('brag-sheet-builder', {
        accomplishments: all, industry: industry || 'general', level: level || 'mid',
        purposes: purposes.length > 0 ? purposes : ['resume'],
        roleTitle: roleTitle.trim() || null, yearsExp: yearsExp ? Number(yearsExp) : null,
        tone: tone || 'balanced', userLanguage: navigator.language || 'en',
        userLocale, userCurrency, userRegion,
      });
      setResults(data);
      setActiveTab('transform');
      setSessionHistory(prev => [{
        id: Date.now().toString(),
        preview: (all[0] || '').slice(0, 40), // Exception: preview truncation, not history cap
        count: all.length,
        industry,
        date: new Date().toISOString(),
        result: data,
      }, ...prev].slice(0, 6));
    } catch (err) { setError(err.message || t('bsb_err_build')); }
  };

  const loadExample = useCallback(() => {
    setIndustry(EXAMPLE.industry);
    setLevel(EXAMPLE.level);
    setAccomplishments(EXAMPLE.accomplishments);
    setCurrentEntry(EXAMPLE.currentEntry);
  }, [setIndustry, setLevel, setAccomplishments, setCurrentEntry]);

  const handleTweak = async (idx, instruction) => {
    const tr = getDisplayTransformations()[idx];
    if (!tr) return;
    setTweakLoading(true); setTweakingIdx(idx); setError('');
    try {
      const data = await callToolEndpoint('brag-sheet-tweak', {
        original: tr.original, currentImproved: tr.improved, instruction,
        industry, level, roleTitle: roleTitle.trim() || null, tone, userLanguage: navigator.language || 'en',
        userLocale, userCurrency, userRegion,
      });
      setResults(prev => {
        const updated = { ...prev };
        updated.transformations = [...prev.transformations];
        updated.transformations[idx] = { ...updated.transformations[idx], ...data, _tweaked: true };
        return updated;
      });
      if (refinedData?.upgraded_transformations) {
        setRefinedData(prev => ({ ...prev, upgraded_transformations: prev.upgraded_transformations.filter(u => u.accomplishment_index !== idx) }));
      }
    } catch (err) { setError(err.message || t('bsb_err_tweak')); }
    setTweakLoading(false); setTweakingIdx(null); setTweakInstruction('');
  };

  const handleAddSingle = async () => {
    const text = newEntry.trim();
    if (!text) return;
    setAddSingleLoading(true); setError('');
    try {
      const data = await callToolEndpoint('brag-sheet-add-single', {
        newAccomplishment: text, existingTransformations: results?.transformations || [],
        industry, level, roleTitle: roleTitle.trim() || null, purposes, tone,
        userLanguage: navigator.language || 'en',
        userLocale, userCurrency, userRegion,
      });
      setResults(prev => {
        const updated = { ...prev };
        updated.transformations = [...prev.transformations, data.transformation];
        if (data.metrics_to_find?.length > 0) {
          const nm = data.metrics_to_find.map(m => ({ ...m, accomplishment_index: updated.transformations.length - 1 }));
          updated.metrics_to_find = [...(prev.metrics_to_find || []), ...nm];
        }
        if (data.resume_bullet) updated.resume_bullets = [...(prev.resume_bullets || []), data.resume_bullet];
        if (data.raise_statement && updated.raise_ammunition) {
          updated.raise_ammunition = { ...updated.raise_ammunition, value_statements: [...(updated.raise_ammunition.value_statements || []), data.raise_statement] };
        }
        return updated;
      });
      setAccomplishments(prev => [...prev, text]);
      setNewEntry(''); setAddingMore(false);
      setRadarData(null); // invalidate radar since data changed
    } catch (err) { setError(err.message || t('bsb_err_add')); }
    setAddSingleLoading(false);
  };

  const handleGenerateStar = async (idx) => {
    const tr = getDisplayTransformations()[idx];
    if (!tr) return;
    setStarLoading(idx); setError('');
    try {
      const data = await callToolEndpoint('brag-sheet-star', {
        accomplishment: tr.original, improved: tr.improved,
        interviewQuestion: starQuestion.trim() || null,
        industry, level, roleTitle: roleTitle.trim() || null,
        userLanguage: navigator.language || 'en',
        userLocale, userCurrency, userRegion,
      });
      setCustomStarStories(prev => [...prev, { ...data, source_index: idx }]);
      setStarSelectIdx(null); setStarQuestion('');
    } catch (err) { setError(err.message || t('bsb_err_star')); }
    setStarLoading(null);
  };

  const handleRefine = async () => {
    const answers = Object.entries(metricsAnswers).filter(([, val]) => val.trim()).map(([key, val]) => {
      const mq = getCurrentMetrics()[parseInt(key)];
      return { accomplishment_index: mq.accomplishment_index, question: mq.question, answer: val.trim() };
    });
    if (answers.length === 0) { setError(t('bsb_err_answer_one')); return; }
    setError(''); setRefineLoading(true);
    const currentTransforms = getDisplayTransformations();
    const newPre = { ...preUpgradeVersions };
    answers.forEach(a => { if (!newPre[a.accomplishment_index]) newPre[a.accomplishment_index] = currentTransforms[a.accomplishment_index]?.improved; });
    setPreUpgradeVersions(newPre);
    try {
      const data = await callToolEndpoint('brag-sheet-refine', {
        originalTransformations: currentTransforms, metricsAnswers: answers,
        industry: industry || 'general', level: level || 'mid',
        roleTitle: roleTitle.trim() || null, purposes, tone: tone || 'balanced',
        userLanguage: navigator.language || 'en',
        userLocale, userCurrency, userRegion,
      });
      setRefinedData(prev => {
        const existing = prev || { upgraded_transformations: [], updated_resume_bullets: [], updated_raise_statements: [] };
        const merged = [...(existing.upgraded_transformations || [])];
        (data.upgraded_transformations || []).forEach(upg => {
          const ei = merged.findIndex(m => m.accomplishment_index === upg.accomplishment_index);
          if (ei >= 0) merged[ei] = upg; else merged.push(upg);
        });
        return { upgraded_transformations: merged, updated_resume_bullets: data.updated_resume_bullets || existing.updated_resume_bullets || [],
          updated_raise_statements: data.updated_raise_statements || existing.updated_raise_statements || [],
          remaining_questions: data.remaining_questions || [] };
      });
      setMetricsAnswers({}); setRefineRound(r => r + 1); setRadarData(null);
    } catch (err) { setError(err.message || t('bsb_err_upgrade')); }
    setRefineLoading(false);
  };

  // ── Excavator ──
  const handleExcavate = async () => {
    setExcavatorLoading(true); setError('');
    try {
      const data = await callToolEndpoint('brag-sheet-excavate', {
        roleTitle: roleTitle.trim() || null, industry: industry || 'general',
        level: level || 'mid', yearsExp: yearsExp ? Number(yearsExp) : null,
        existingAccomplishments: accomplishments,
        userLanguage: navigator.language || 'en',
        userLocale, userCurrency, userRegion,
      });
      setExcavatorData(data); setShowExcavator(true);
    } catch (err) { setError(err.message || t('bsb_err_excavate')); }
    setExcavatorLoading(false);
  };

  // ── Journal ──
  const addJournalEntry = () => {
    const text = journalEntry.trim();
    if (!text) return;
    setJournal(prev => [{ text, date: new Date().toISOString(), id: Date.now().toString() }, ...prev]);
    setJournalEntry('');
  };
  const importJournalEntries = (entries) => {
    setAccomplishments(prev => [...prev, ...entries.map(e => e.text)]);
    setShowJournal(false);
  };

  // ── Radar ──
  const handleRadar = async () => {
    setRadarLoading(true); setError('');
    try {
      const data = await callToolEndpoint('brag-sheet-radar', {
        transformations: getDisplayTransformations(), industry: industry || 'general',
        level: level || 'mid', roleTitle: roleTitle.trim() || null,
        userLanguage: navigator.language || 'en',
        userLocale, userCurrency, userRegion,
      });
      setRadarData(data);
    } catch (err) { setError(err.message || t('bsb_err_assess')); }
    setRadarLoading(false);
  };

  // ── JD Tailor ──
  const handleTailor = async () => {
    if (!jdText.trim()) { setError(t('bsb_err_paste_jd')); return; }
    setTailorLoading(true); setError('');
    try {
      const data = await callToolEndpoint('brag-sheet-tailor', {
        jobDescription: jdText, transformations: getDisplayTransformations(),
        resumeBullets: getDisplayBullets(), industry: industry || 'general',
        level: level || 'mid', roleTitle: roleTitle.trim() || null,
        tone: tone || 'balanced', userLanguage: navigator.language || 'en',
        userLocale, userCurrency, userRegion,
      });
      setTailorData(data);
    } catch (err) { setError(err.message || t('bsb_err_tailor')); }
    setTailorLoading(false);
  };

  // ── Interview Matrix ──
  const handleMatrix = async () => {
    setMatrixLoading(true); setError('');
    try {
      const data = await callToolEndpoint('brag-sheet-interview-matrix', {
        transformations: getDisplayTransformations(), starStories: allStarStories,
        industry: industry || 'general', level: level || 'mid',
        roleTitle: roleTitle.trim() || null, userLanguage: navigator.language || 'en',
        userLocale, userCurrency, userRegion,
      });
      setMatrixData(data);
    } catch (err) { setError(err.message || t('bsb_err_matrix')); }
    setMatrixLoading(false);
  };

  // ── Voice Match ──
  const handleVoiceMatch = async () => {
    if (!voiceSample.trim()) { setError(t('bsb_err_paste_sample')); return; }
    setVoiceLoading(true); setError('');
    try {
      const data = await callToolEndpoint('brag-sheet-voice-match', {
        writingSample: voiceSample, transformations: getDisplayTransformations(),
        resumeBullets: getDisplayBullets(), linkedinAbout: results?.linkedin_about || null,
        tone: tone || 'balanced', userLanguage: navigator.language || 'en',
        userLocale, userCurrency, userRegion,
      });
      setVoiceData(data);
    } catch (err) { setError(err.message || t('bsb_err_voice')); }
    setVoiceLoading(false);
  };

  // ── Download ──
  const handleDownload = () => {
    const text = buildFullText();
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `brag-sheet${roleTitle ? '-' + roleTitle.replace(/\s+/g, '-').toLowerCase() : ''}.txt`;
    document.body.appendChild(a); a.click(); document.body.removeChild(a); URL.revokeObjectURL(url);
  };

  const reset = () => {
    setAccomplishments([]); setCurrentEntry(''); setResults(null); setError('');
    setRefinedData(null); setMetricsAnswers({}); setRefineRound(0); setPreUpgradeVersions({});
    setActiveTab('transform'); setExpandedSections({}); setCustomStarStories([]);
    setAddingMore(false); setNewEntry(''); setTweakingIdx(null); setStarSelectIdx(null);
    setRadarData(null); setTailorData(null); setMatrixData(null); setVoiceData(null);
    setJdText(''); setVoiceSample(''); setShowExcavator(false); setExcavatorData(null);
    setIndustry(''); setLevel(''); setPurposes(['resume']); setRoleTitle(''); setYearsExp(''); setTone('balanced');
  };

  // ─── Scroll + global keydown ───
  useEffect(() => {
    if (!results) return;
    const tm = setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 100);
    return () => clearTimeout(tm);
  }, [results]);

  // Assigned every render — keep handler refs fresh
  handleSubmitRef.current = handleBuild;
  canSubmitRef.current = accomplishments.length > 0 || !!currentEntry.trim();

  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && !loading && canSubmitRef.current)
        handleSubmitRef.current?.();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading]);

  // ═══════════════════════════════════════════
  // HELPERS
  // ═══════════════════════════════════════════
  const getDisplayTransformations = () => {
    if (!results?.transformations) return [];
    return results.transformations.map((tr, i) => {
      const upgrade = refinedData?.upgraded_transformations?.find(u => u.accomplishment_index === i);
      if (upgrade) return { ...tr, improved: upgrade.improved, what_changed: upgrade.what_changed, verb_upgrades: upgrade.verb_upgrades,
        why_you_deserve_this: upgrade.why_you_deserve_this, metric_highlight: upgrade.metric_highlight, _refined: true };
      return tr;
    });
  };
  const getCurrentMetrics = () => refinedData?.remaining_questions?.length > 0 ? refinedData.remaining_questions : (results?.metrics_to_find || []);
  const getDisplayBullets = () => refinedData?.updated_resume_bullets?.length > 0 ? refinedData.updated_resume_bullets : (results?.resume_bullets || []);
  const getDisplayRaise = () => {
    const base = results?.raise_ammunition || {};
    if (refinedData?.updated_raise_statements?.length > 0) return { ...base, value_statements: refinedData.updated_raise_statements };
    return base;
  };
  const allStarStories = [...(results?.star_stories || []), ...customStarStories];

  const buildFullText = useCallback(() => {
    if (!results) return '';
    const lines = [t('bsb_copy_brag_sheet'), roleTitle ? `${t('bsb_copy_role')} ${roleTitle}` : '', industry ? `${t('bsb_copy_industry')} ${industry}` : '', ''].filter(Boolean);
    const transforms = getDisplayTransformations();
    lines.push(`═══ ${t('bsb_copy_accomplishments')} ═══`, '');
    transforms.forEach((tr, i) => {
      lines.push(`${i + 1}. ${tr.improved}`, `   (${t('bsb_copy_was')} "${tr.original}")`);
      if (tr.metric_highlight) lines.push(`   📊 ${tr.metric_highlight}`);
      lines.push('');
    });
    const bullets = getDisplayBullets();
    if (bullets.length > 0) { lines.push(`═══ ${t('bsb_copy_resume_bullets')} ═══`, ...bullets.map(b => `• ${b}`), ''); }
    if (results.linkedin_about) { lines.push(`═══ ${t('bsb_copy_linkedin')} ═══`, results.linkedin_about, ''); }
    if (results.performance_review) { lines.push(`═══ ${t('bsb_copy_perf_review')} ═══`, results.performance_review, ''); }
    const raise = getDisplayRaise();
    if (raise.summary) {
      lines.push(`═══ ${t('bsb_copy_raise')} ═══`, raise.summary);
      raise.value_statements?.forEach(v => lines.push(`• ${v}`));
      if (raise.total_estimated_value) lines.push(`${t('bsb_copy_total_value')} ${raise.total_estimated_value}`);
      if (raise.script) lines.push('', `${t('bsb_copy_say_this')} "${raise.script}"`);
      lines.push('');
    }
    allStarStories.forEach((s, i) => {
      lines.push(`═══ ${t('bsb_copy_star')} ${i + 1}: ${s.title} ═══`, `S: ${s.situation}`, `T: ${s.task}`, `A: ${s.action}`, `R: ${s.result}`);
      if (s.good_for_questions?.length > 0) lines.push(`${t('bsb_copy_good_for')} ${s.good_for_questions.join(', ')}`);
      lines.push('');
    });
    lines.push(BRAND);
    return lines.join('\n');
  }, [results, roleTitle, industry, refinedData, customStarStories, t]);

  // ─── Register export content (must be after buildFullText) ───
  useRegisterActions(results ? buildFullText() : '', tool?.title);

  const r = results;
  const transforms = getDisplayTransformations();
  const metrics = getCurrentMetrics();
  const bullets = getDisplayBullets();
  const raise = getDisplayRaise();
  const hasOutputs = bullets.length > 0 || r?.linkedin_about || r?.performance_review || allStarStories.length > 0;

  const tabs = [
    { key: 'transform', label: `✨ ${t('bsb_tab_before_after')}` },
    ...(metrics.length > 0 ? [{ key: 'metrics', label: `📊 ${t('bsb_tab_upgrade')}${refineRound > 0 ? ` (${refineRound})` : ''}` }] : []),
    { key: 'radar', label: `📡 ${t('bsb_tab_radar')}` },
    { key: 'tailor', label: `🎯 ${t('bsb_tab_tailor')}` },
    { key: 'interview', label: `🎤 ${t('bsb_tab_interview')}` },
    { key: 'voice', label: `✍️ ${t('bsb_tab_voice')}` },
    ...(hasOutputs ? [{ key: 'outputs', label: `📋 ${t('bsb_tab_outputs')}` }] : []),
    ...(raise.summary ? [{ key: 'raise', label: `💰 ${t('bsb_tab_raise')}` }] : []),
  ];

  // score bar helper
  const ScoreBar = ({ score, label, size = 'md' }) => {
    const color = score >= 75 ? c.scoreHigh : score >= 50 ? c.scoreMid : c.scoreLow;
    const h = size === 'sm' ? 'h-1.5' : 'h-2.5';
    return (
      <div className="flex items-center gap-2 w-full">
        {label && <span className={`text-[10px] font-bold ${c.textMuteded} w-28 text-right flex-shrink-0`}>{label}</span>}
        <div className={`flex-1 ${c.scoreBg} rounded-full ${h} overflow-hidden`}>
          <div className={`${color} ${h} rounded-full transition-all`} style={{ width: `${Math.min(100, Math.max(0, score))}%` }} />
        </div>
        <span className={`text-[10px] font-bold ${c.text} w-8`}>{score}</span>
      </div>
    );
  };

  // ─── RENDER ───
  return (
    <div className={`space-y-4 ${c.text}`}>
      {/* Persistent header card — single reset, always in same position */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5`}>
        <div className="pb-3 border-b border-zinc-500">
          <div className="flex items-center justify-between">
            <div>
              <h2 className={`text-xl font-bold ${c.text}`}>
                <span className="mr-2">{tool?.icon ?? '🏆'}</span>{tool?.title ?? t('bsb_title')}
              </h2>
              <p className={`text-sm ${c.textSecondary} mt-1`}>{tool?.tagline ?? t('bsb_tagline')}</p>
              <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className={`mt-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium border disabled:opacity-40 ${isDark ? 'text-white border-white/40' : 'text-gray-800 border-transparent'}`}>{t('try_example')}</button>
            </div>
            {(results || accomplishments.length > 0 || currentEntry.trim()) && (
              <button onClick={reset} className={`${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs font-bold flex-shrink-0`}>
                ↺ {t('start_over')}
              </button>
            )}
          </div>
        </div>
        {/* Quick-actions + role/experience — input-phase only */}
        {!results && (
          <>
            <div className="flex items-center gap-2 flex-wrap pt-3 pb-3 border-b border-zinc-200 dark:border-zinc-700">
              {savedAccomplishments.length > 0 && (
                <button onClick={() => setAccomplishments(prev => [...prev, ...savedAccomplishments])}
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm font-medium ${c.btnSecondary}`}>
                  <span>📂</span> {t('bsb_load_saved', { count: savedAccomplishments.length })}
                </button>
              )}
              <button onClick={() => setShowJournal(!showJournal)}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm font-medium ${c.btnSecondary}`}>
                <span>🗓️</span> {t('bsb_journal')} {journal.length > 0 ? `(${journal.length})` : ''}
              </button>
            </div>
            {/* Role + Experience — first inputs, unified inside header card */}
            <div className="pt-3 grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className={`block text-sm font-semibold ${c.text} mb-1.5`}>{t('bsb_your_role')} <span className={`font-normal ${c.textMuteded}`}>{t('bsb_optional')}</span></label>
                <input type="text" value={roleTitle} onChange={e => setRoleTitle(e.target.value)}
                  onKeyDown={e => { if (e.key === 'Enter') entryRef.current?.focus(); }}
                  placeholder={t('bsb_role_ph')}
                  className={`w-full p-3 border rounded-xl outline-none text-sm focus:ring-2 focus:ring-cyan-300 ${c.input}`} />
              </div>
              <div>
                <label className={`block text-sm font-semibold ${c.text} mb-1.5`}>{t('bsb_years_exp')} <span className={`font-normal ${c.textMuteded}`}>{t('bsb_optional')}</span></label>
                <input type="number" value={yearsExp} onChange={e => setYearsExp(e.target.value)}
                  onKeyDown={e => { if (e.key === 'Enter') entryRef.current?.focus(); }}
                  placeholder={t('bsb_years_ph')}
                  className={`w-full p-3 border rounded-xl outline-none text-sm focus:ring-2 focus:ring-cyan-300 ${c.input}`} />
              </div>
            </div>
          </>
        )}
      </div>

      {/* ═══════════════ JOURNAL PANEL ═══════════════ */}
      {showJournal && !results && (
        <div className={`${c.card} rounded-xl shadow-sm p-5 mb-5 border-l-4 ${c.journalBorder}`}>
          <div className="flex items-center justify-between mb-3">
            <h3 className={`font-bold ${c.text} flex items-center gap-2`}><span>🗓️</span> {t('bsb_journal_title')}</h3>
            <button onClick={() => setShowJournal(false)} className={`text-sm ${c.textMuteded}`}>✕</button>
          </div>
          <p className={`text-xs ${c.textSecondary} mb-3`}>{t('bsb_journal_desc')}</p>
          <label className={`block text-xs font-semibold ${c.textSecondary} mb-1.5`}>{t('bsb_new_entry')} <span className={c.required}>*</span></label>
          <div className="flex gap-2 mb-3">
            <input type="text" value={journalEntry} onChange={e => setJournalEntry(e.target.value)}
              onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); addJournalEntry(); } }}
              placeholder={t('bsb_journal_ph')} className={`flex-1 p-2.5 border rounded-lg text-sm outline-none ${c.input}`} />
            <button onClick={addJournalEntry} disabled={!journalEntry.trim()}
              className={`${c.btnPrimary} disabled:opacity-40 px-3 rounded-lg font-bold text-sm`}>+</button>
          </div>
          {journal.length > 0 && (
            <>
              <div className="space-y-1.5 max-h-48 overflow-y-auto mb-3">
                {journal.map((entry, i) => (
                  <div key={entry.id} className={`flex items-start gap-2 p-2 rounded-lg ${c.cardAlt} text-xs`}>
                    <input type="checkbox" id={`j-${i}`} className="mt-0.5 accent-cyan-500" />
                    <label htmlFor={`j-${i}`} className={`flex-1 ${c.text} cursor-pointer`}>{entry.text}</label>
                    <span className={c.textMuteded}>{new Date(entry.date).toLocaleDateString()}</span>
                    <button onClick={() => setJournal(prev => prev.filter((_, idx) => idx !== i))} className={c.removeBtn}>✕</button>
                  </div>
                ))}
              </div>
              <div className="flex items-center gap-2">
                <button onClick={() => {
                  const checked = [...document.querySelectorAll('[id^="j-"]:checked')].map(el => {
                    const idx = parseInt(el.id.split('-')[1]);
                    return journal[idx];
                  }).filter(Boolean);
                  if (checked.length > 0) importJournalEntries(checked);
                }} className={`text-xs font-semibold px-3 py-1.5 rounded-lg ${c.btnPrimary}`}>{t('bsb_import_selected')}</button>
                <button onClick={() => importJournalEntries(journal)}
                  className={`text-xs font-medium px-3 py-1.5 rounded-lg ${c.btnSecondary}`}>{t('bsb_import_all', { count: journal.length })}</button>
              </div>
            </>
          )}
          {journal.length === 0 && <p className={`text-xs ${c.textMuteded} italic`}>{t('bsb_journal_empty')}</p>}
        </div>
      )}

      {/* ═══════════════ INPUT VIEW ═══════════════ */}
      {!results && (
        <div className="space-y-5">


          {/* Industry */}
          <div className={`${c.card} rounded-xl shadow-sm p-6`}>
            <label className={`block font-semibold ${c.text} mb-3`}>{t('bsb_industry')}</label>
            <div className="flex flex-wrap gap-2">
              {INDUSTRIES.map(ind => (
                <button key={ind.value} onClick={() => setIndustry(industry === ind.value ? '' : ind.value)}
                  className={`px-3 py-2 rounded-lg border text-sm font-medium transition-all ${c.chip(industry === ind.value)}`}>{ind.label}</button>
              ))}
            </div>
          </div>

          {/* Level + Tone */}
          <div className={`${c.card} rounded-xl shadow-sm p-6 space-y-5`}>
            <div>
              <label className={`block font-semibold ${c.text} mb-3`}>{t('bsb_career_level')}</label>
              <div className="flex flex-wrap gap-2">
                {LEVELS.map(lv => (
                  <button key={lv.value} onClick={() => setLevel(level === lv.value ? '' : lv.value)}
                    className={`px-3 py-2 rounded-lg border text-sm font-medium transition-all ${c.chip(level === lv.value)}`}>{lv.icon} {lv.label}</button>
                ))}
              </div>
            </div>
            <div>
              <label className={`block font-semibold ${c.text} mb-3`}>{t('bsb_tone')}</label>
              <div className="flex flex-wrap gap-2">
                {TONES.map(t => (
                  <button key={t.value} onClick={() => setTone(t.value)}
                    className={`px-3 py-2 rounded-lg border text-sm font-medium transition-all ${c.chip(tone === t.value)}`}>{t.icon} {t.label}</button>
                ))}
              </div>
            </div>
          </div>

          {/* Purposes */}
          <div className={`${c.card} rounded-xl shadow-sm p-6`}>
            <label className={`block font-semibold ${c.text} mb-3`}>{t('bsb_what_for')} <span className={`font-normal ${c.textMuteded}`}>{t('bsb_pick_all')}</span></label>
            <div className="flex flex-wrap gap-2">
              {PURPOSES.map(p => (
                <button key={p.value} onClick={() => togglePurpose(p.value)}
                  className={`px-3 py-2 rounded-lg border text-sm font-medium transition-all flex items-center gap-1.5 ${c.chip(purposes.includes(p.value))}`}><span>{p.icon}</span> {p.label}</button>
              ))}
            </div>
          </div>

          {/* Accomplishments */}
          <div className={`${c.card} rounded-xl shadow-sm p-6`}>
            <div className="flex items-center justify-between mb-2">
              <label className={`font-semibold ${c.text}`}>{t('bsb_your_accomplishments')} <span className={c.required}>*</span> <span className={`font-normal ${c.textMuteded}`}>{t('bsb_humble_hint')}</span></label>
              <button onClick={handleExcavate} disabled={excavatorLoading}
                className={`flex items-center gap-1 text-xs font-semibold px-2.5 py-1 rounded-lg ${c.excavatorBtn} disabled:opacity-40`}>
                {excavatorLoading ? <span className="inline-block animate-spin">{tool?.icon ?? '🏆'}</span> : <span>🧠</span>} {t('bsb_cant_remember')}
              </button>
            </div>

            {/* Excavator results */}
            {showExcavator && excavatorData?.categories && (
              <div className={`mb-4 p-4 rounded-xl border-2 ${c.excavatorPanel}`}>
                <div className="flex items-center justify-between mb-3">
                  <h4 className={`text-sm font-bold ${c.text}`}>🧠 {t('bsb_memory_jogger')}</h4>
                  <button onClick={() => setShowExcavator(false)} className={`text-xs ${c.textMuteded}`}>✕</button>
                </div>
                <div className="space-y-3">
                  {excavatorData.categories.map((cat, ci) => (
                    <div key={ci}>
                      <button onClick={() => toggleSection(`exc-${ci}`)} className={`flex items-center gap-1.5 w-full text-left mb-1.5`}>
                        <span>{cat.icon}</span>
                        <span className={`text-xs font-bold ${c.text}`}>{cat.name}</span>
                        <span className={`text-[10px] ${c.textMuteded} ml-auto`}>{expandedSections[`exc-${ci}`] === false ? '▼' : '▲'}</span>
                      </button>
                      {expandedSections[`exc-${ci}`] !== false && (
                        <div className="space-y-1.5 ml-5">
                          {cat.questions.map((q, qi) => (
                            <button key={qi} onClick={() => { setCurrentEntry(q.exampleAccomplishment || ''); entryRef.current?.focus(); }}
                              className={`w-full text-left p-2 rounded-lg text-xs ${c.hoverBg} transition-colors`}>
                              <p className={`font-medium ${c.text}`}>{q.text}</p>
                              {q.exampleAccomplishment && <p className={`${c.textMuteded} mt-0.5 italic`}>{t('bsb_eg_quote', { example: q.exampleAccomplishment })}</p>}
                            </button>
                          ))}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {accomplishments.length > 0 && (
              <div className="space-y-2 mb-3">
                {accomplishments.map((acc, idx) => (
                  <div key={idx} className={`flex items-start gap-2 p-3 rounded-lg ${c.cardAlt}`}>
                    <span className={`text-xs font-bold ${c.highlightText} mt-0.5`}>{idx + 1}.</span>
                    <p className={`flex-1 text-sm ${c.text}`}>{acc}</p>
                    <button onClick={() => removeAccomplishment(idx)} className={c.removeBtn}>✕</button>
                  </div>
                ))}
              </div>
            )}
            <input ref={entryRef} type="text" value={currentEntry} onChange={e => setCurrentEntry(e.target.value)}
              onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); addAccomplishment(); } }}
              placeholder={accomplishments.length === 0 ? t('bsb_acc_ph_first') : t('bsb_acc_ph_more')}
              className={`flex-1 p-3 border rounded-xl outline-none text-sm focus:ring-2 focus:ring-cyan-300 ${c.input}`} />
            <button onClick={addAccomplishment} disabled={!currentEntry.trim()} className={`${c.btnPrimary} disabled:opacity-40 px-4 rounded-xl font-bold text-lg`}>➕</button>
            <div className="flex items-center justify-between mt-2">
              <p className={`text-xs ${c.textMuteded}`}>{t('bsb_enter_to_add')}</p>
              {accomplishments.length > 0 && (
                <button
                  onClick={() => {
                    setSavedAccomplishments([...accomplishments]);
                    setSavedFeedback(true);
                    setTimeout(() => setSavedFeedback(false), 2000);
                  }}
                  disabled={savedFeedback}
                  className={`text-xs font-medium px-2.5 py-1 rounded-lg border transition-all ${savedFeedback ? c.savedBtn : `${c.highlightText} border-transparent hover:border-current`}`}>
                  {savedFeedback ? `✅ ${t('bsb_saved')}` : `💾 ${t('bsb_save_later')}`}</button>
              )}
            </div>
          </div>

          {/* Submit */}
          <button onClick={handleBuild} disabled={loading || (accomplishments.length === 0 && !currentEntry.trim())}
          className={`w-full py-4 px-6 rounded-xl font-semibold text-lg transition-all flex items-center justify-center gap-2 shadow-lg ${loading ? c.btnLoading : c.btnPrimary} disabled:opacity-40`}>
          {loading ? (<><span className="inline-block animate-spin text-lg">{tool?.icon ?? '🏆'}</span> {t('bsb_transforming')}</>) : (<><span className="text-lg">{tool?.icon ?? '🏆'}</span> {t('bsb_build')}</>)}
          </button>

          {error && <div className={`p-4 rounded-xl flex items-start gap-3 ${c.danger} border`}><span className="text-lg flex-shrink-0 mt-0.5">⚠️</span><p className="text-sm">{error}</p></div>}

          {/* History panel */}
          {sessionHistory.length > 0 && (
            <div className={`${c.card} rounded-xl border ${c.border} p-4`}>
              <h3 className={`text-sm font-bold ${c.text} mb-3`}>🕐 {t('bsb_recent')}</h3>
              <div className="space-y-1.5">
                {sessionHistory.map(entry => (
                  <button key={entry.id}
                    onClick={() => { if (entry.result) { setResults(entry.result); setActiveTab('transform'); } }}
                    className={`w-full text-left px-3 py-2 rounded-lg ${c.btnSecondary} text-xs`}>
                    <span className={c.textMuteded}>
                      {new Date(entry.date).toLocaleDateString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })}
                    </span>
                    <span className={`ml-2 ${c.text}`}>{entry.preview}{entry.preview?.length >= 40 ? '…' : ''}</span>
                    <span className={`ml-1.5 ${c.textMuteded}`}>({entry.count} {entry.count !== 1 ? t('bsb_item_many') : t('bsb_item_one')})</span>
                  </button>
                ))}
              </div>
            </div>
          )}

          <p className={`text-xs text-center ${c.textMuteded}`}>
            {t('bsb_overwhelmed_xref')} 🔧 <a href="/TaskAvalancheBreaker" className={linkStyle}>{t('bsb_task_avalanche')}</a> {t('bsb_overwhelmed_xref_end')}
          </p>
        </div>
      )}

      {/* ═══════════════ RESULTS VIEW ═══════════════ */}
      {results && (
        <div ref={resultsRef} className="space-y-5">
          {/* Controls */}
          <div className={`${c.card} rounded-xl shadow-sm p-4 flex items-center justify-between flex-wrap gap-3`}>
            <span className={`text-sm font-semibold ${c.text}`}>🏆 {transforms.length} {transforms.length !== 1 ? t('bsb_transformed_many') : t('bsb_transformed_one')}</span>
            <div className="flex items-center gap-2 flex-wrap">
              <button onClick={handleDownload} className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm font-medium ${c.btnSecondary}`}>
                <span>📥</span> {t('bsb_download')}
              </button>
              <button onClick={() => setAddingMore(true)} className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm font-medium ${c.btnSecondary}`}>
                <span>➕</span> {t('bsb_add_more')}
              </button>
            </div>
          </div>

          {/* Add One More */}
          {addingMore && (
            <div className={`${c.card} rounded-xl shadow-sm p-5 border-l-4 ${c.addMoreBorder}`}>
              <p className={`text-sm font-semibold ${c.text} mb-2`}>➕ {t('bsb_add_another')}</p>
              <input type="text" value={newEntry} onChange={e => setNewEntry(e.target.value)}
                onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); handleAddSingle(); } }}
                placeholder={t('bsb_describe_ph')} autoFocus className={`flex-1 p-3 border rounded-xl outline-none text-sm ${c.input}`} />
              <button onClick={handleAddSingle} disabled={addSingleLoading || !newEntry.trim()}
                className={`${c.btnPrimary} disabled:opacity-40 px-4 rounded-xl font-bold text-sm`}>
                <span className={addSingleLoading ? 'inline-block animate-spin' : ''}>{tool?.icon ?? '🏆'}</span></button>
              <button onClick={() => { setAddingMore(false); setNewEntry(''); }} className={`px-3 rounded-xl text-sm ${c.textMuteded}`}>✕</button>
            </div>
          )}

          {/* Tabs */}
          <div className={`flex border-b ${c.border} gap-0 overflow-x-auto`}>
            {tabs.map(tab => (
              <button key={tab.key} onClick={() => setActiveTab(tab.key)}
                className={`flex items-center gap-1.5 px-4 py-3 text-sm font-semibold border-b-2 transition-all whitespace-nowrap ${c.tab(activeTab === tab.key)}`}>{tab.label}</button>
            ))}
          </div>

          {error && <div className={`p-4 rounded-xl flex items-start gap-3 ${c.danger} border`}><span className="text-lg flex-shrink-0 mt-0.5">⚠️</span><p className="text-sm">{error}</p></div>}

          {/* ══════ TAB: TRANSFORM ══════ */}
          {activeTab === 'transform' && (
            <div className="space-y-4">
              {transforms.map((tr, idx) => (
                <div key={idx} className={`${c.card} rounded-xl shadow-sm p-5 space-y-3`}>
                  <div className={`${c.beforeBg} border rounded-lg p-3`}>
                    <p className={`text-[10px] font-bold ${c.textMuteded} uppercase mb-1`}>{t('bsb_you_said')}</p>
                    <p className={`text-sm ${c.textSecondary} italic`}>{tr.original}</p>
                  </div>
                  <div className="flex items-center gap-2 px-2">
                    <span className={c.highlightText}>→</span>
                    <span className={`text-[10px] font-bold ${c.highlightText}`}>{tr.what_changed}</span>
                    {tr._refined && <span className={`text-[9px] font-black uppercase px-1.5 py-0.5 rounded ${c.upgradeTag}`}>{t('bsb_upgraded')}</span>}
                    {tr._tweaked && <span className={`text-[9px] font-black uppercase px-1.5 py-0.5 rounded ${c.tweakTag}`}>{t('bsb_tweaked')}</span>}
                  </div>
                  {tr._refined && preUpgradeVersions[idx] && (
                    <div className={`px-3 py-2 rounded-lg ${c.preUpgradeBg}`}>
                      <p className={`text-[10px] font-bold ${c.textMuteded} mb-0.5`}>{t('bsb_before_upgrade')}</p>
                      <p className={`text-xs ${c.textMuteded} line-through`}>{preUpgradeVersions[idx]}</p>
                    </div>
                  )}
                  <div className={`flex-1 ${c.afterBg} border rounded-lg p-3`}>
                    <p className={`text-[10px] font-bold ${c.highlightText} uppercase mb-1`}>{t('bsb_power_version')}</p>
                    <p className={`text-sm font-semibold ${c.text}`}>{tr.improved}</p>
                  </div>
                  {tr.metric_highlight && <p className={`text-xs font-bold px-2 ${c.successFg}`}>📊 {tr.metric_highlight}</p>}
                  {tr.verb_upgrades?.length > 0 && (
                    <div className="flex flex-wrap gap-2 px-1">
                      {tr.verb_upgrades.map((vu, i) => (
                        <span key={i} className={`text-[10px] px-2 py-0.5 rounded-full ${c.highlightBg} border font-bold`}>
                          <span className={c.textMuteded}>{vu.from}</span> → <span className={c.highlightAlt}>{vu.to}</span>
                        </span>
                      ))}
                    </div>
                  )}
                  {tr.why_you_deserve_this && (
                    <div className={`${c.warning} border rounded-lg p-3 flex items-start gap-2`}>
                      <span className="flex-shrink-0 mt-0.5">🛡️</span><p className="text-xs">{tr.why_you_deserve_this}</p>
                    </div>
                  )}
                  {/* Action row */}
                  <div className={`flex items-center gap-2 pt-2 flex-wrap border-t ${c.border}`}>
                    {tweakingIdx !== idx && (
                      <>
                        <button onClick={() => handleTweak(idx, t('bsb_softer_instr'))} disabled={tweakLoading}
                          className={`text-[10px] px-2.5 py-1 rounded-lg ${c.btnSecondary} disabled:opacity-40`}>🌊 {t('bsb_softer')}</button>
                        <button onClick={() => handleTweak(idx, t('bsb_stronger_instr'))} disabled={tweakLoading}
                          className={`text-[10px] px-2.5 py-1 rounded-lg ${c.btnSecondary} disabled:opacity-40`}>🔥 {t('bsb_stronger')}</button>
                        <button onClick={() => setTweakingIdx(idx)} className={`text-[10px] px-2.5 py-1 rounded-lg ${c.btnSecondary}`}>✏️ {t('bsb_reword')}</button>
                        <span className={`text-[10px] ${c.textMuteded} mx-0.5`}>|</span>
                        <button onClick={() => { setStarSelectIdx(starSelectIdx === idx ? null : idx); setStarQuestion(''); }} disabled={starLoading === idx}
                          className={`text-[10px] px-2.5 py-1 rounded-lg ${c.btnSecondary} disabled:opacity-40`}>⭐ {t('bsb_star_story')}</button>
                      </>
                    )}
                    {tweakingIdx === idx && (
                      <div className="flex gap-2 w-full mt-1">
                        <input type="text" value={tweakInstruction} onChange={e => setTweakInstruction(e.target.value)}
                          onKeyDown={e => { if (e.key === 'Enter') handleTweak(idx, tweakInstruction); }}
                          placeholder={t('bsb_tweak_ph')} autoFocus className={`flex-1 p-2 border rounded-lg text-xs outline-none ${c.input}`} />
                        <button onClick={() => handleTweak(idx, tweakInstruction)} disabled={tweakLoading || !tweakInstruction.trim()}
                          className={`${c.btnPrimary} disabled:opacity-40 px-3 rounded-lg text-xs font-bold`}>{tweakLoading ? <span className="inline-block animate-spin">{tool?.icon ?? '🏆'}</span> : '✓'}</button>
                        <button onClick={() => { setTweakingIdx(null); setTweakInstruction(''); }} className={`text-xs ${c.textMuteded}`}>✕</button>
                      </div>
                    )}
                  </div>
                  {starSelectIdx === idx && (
                    <div className={`p-3 rounded-lg border ${c.border} space-y-2`}>
                      <p className={`text-xs font-semibold ${c.text}`}>⭐ {t('bsb_gen_star_from')}</p>
                      <input type="text" value={starQuestion} onChange={e => setStarQuestion(e.target.value)}
                        placeholder={t('bsb_star_q_ph')} className={`w-full p-2 border rounded-lg text-xs outline-none ${c.input}`} />
                      <button onClick={() => handleGenerateStar(idx)} disabled={starLoading === idx}
                        className={`${c.btnPrimary} disabled:opacity-40 px-3 py-1.5 rounded-lg text-xs font-bold`}>
                        {starLoading === idx ? <><span className="inline-block animate-spin">{tool?.icon ?? '🏆'}</span> {t('bsb_generating')}</> : t('bsb_generate')}</button>
                      <button onClick={() => { setStarSelectIdx(null); setStarQuestion(''); }} className={`text-xs ${c.textMuteded}`}>{t('bsb_cancel')}</button>
                    </div>
                  )}
                </div>
              ))}
              {r.confidence && (
                <div className={`${c.highlightBg} border-2 rounded-xl p-5`}>
                  <div className="flex items-start gap-3">
                    <span className="text-xl flex-shrink-0 mt-0.5">💪</span>
                    <div>
                      <h3 className={`text-sm font-bold ${c.text} mb-1`}>{t('bsb_permission_brag')}</h3>
                      {r.confidence.reframe && <p className={`text-sm ${c.textSecondary} mb-2`}>{r.confidence.reframe}</p>}
                      {r.confidence.imposter_killer && <p className={`text-xs ${c.highlightAlt} font-semibold`}>{r.confidence.imposter_killer}</p>}
                    </div>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* ══════ TAB: METRICS ══════ */}
          {activeTab === 'metrics' && (
            <div className={`${c.card} rounded-xl shadow-sm p-6 space-y-4`}>
              <h3 className={`font-bold ${c.text} flex items-center gap-2`}>
                <span className="text-lg">📊</span> {refineRound === 0 ? t('bsb_metrics_excavator') : t('bsb_round_dig', { round: refineRound + 1 })}
              </h3>
              <p className={`text-sm ${c.textSecondary}`}>{t('bsb_metrics_desc')}</p>
              <div className="space-y-4">
                {metrics.map((mq, i) => {
                  const src = transforms[mq.accomplishment_index];
                  return (
                    <div key={i} className={`p-4 rounded-lg border ${c.border}`}>
                      {src && <p className={`text-[10px] font-bold ${c.highlightText} mb-2`}>{t('bsb_re', { num: mq.accomplishment_index + 1 })} "{src.original?.substring(0, 60)}…"</p>}
                      <p className={`text-sm font-semibold ${c.text} mb-1`}>{mq.question}</p>
                      <p className={`text-xs ${c.textMuteded} mb-2`}>{t('bsb_why')} {mq.why}</p>
                      {mq.example && <p className={`text-xs ${c.highlightText} mb-3`}>{t('bsb_eg_quote', { example: mq.example })}</p>}
                      <input type="text" value={metricsAnswers[i] || ''} onChange={e => setMetricsAnswers(prev => ({ ...prev, [i]: e.target.value }))}
                        placeholder={t('bsb_your_answer_ph')} className={`w-full p-2.5 border rounded-lg outline-none text-sm ${c.input}`} />
                    </div>
                  );
                })}
              </div>
              <button onClick={handleRefine} disabled={refineLoading || Object.values(metricsAnswers).every(v => !v?.trim())}
                className={`w-full py-3 rounded-xl font-semibold text-sm flex items-center justify-center gap-2 ${c.btnPrimary} disabled:opacity-40`}>
                {refineLoading ? <><span className="inline-block animate-spin">{tool?.icon ?? '🏆'}</span> {t('bsb_upgrading')}</> : `🚀 ${t('bsb_upgrade_bullets')}`}</button>
              {refineRound > 0 && <p className={`text-xs ${c.textMuteded} text-center`}>✅ {t('bsb_round_done', { round: refineRound, count: refinedData?.upgraded_transformations?.length || 0 })}{metrics.length > 0 ? t('bsb_more_questions') : t('bsb_all_maxed')}</p>}
            </div>
          )}

          {/* ══════ TAB: RADAR ══════ */}
          {activeTab === 'radar' && (
            <div className="space-y-4">
              {!radarData && (
                <div className={`${c.card} rounded-xl shadow-sm p-6 text-center`}>
                  <span className="text-4xl block mb-3">📡</span>
                  <h3 className={`font-bold ${c.text} mb-2`}>{t('bsb_radar_title')}</h3>
                  <p className={`text-sm ${c.textSecondary} mb-4`}>{t('bsb_radar_desc')}</p>
                  <button onClick={handleRadar} disabled={radarLoading}
                    className={`${c.btnPrimary} disabled:opacity-40 px-6 py-3 rounded-xl font-semibold text-sm`}>
                    {radarLoading ? <><span className="inline-block animate-spin">{tool?.icon ?? '🏆'}</span> {t('bsb_radar_analyzing')}</> : `📡 ${t('bsb_radar_analyze')}`}</button>
                </div>
              )}
              {radarData && (
                <div className={`${c.card} rounded-xl shadow-sm p-6 space-y-5`}>
                  <div className="flex items-center justify-between">
                    <h3 className={`font-bold ${c.text} flex items-center gap-2`}><span>📡</span> {t('bsb_strength_radar')}</h3>
                    <div className={`px-3 py-1.5 rounded-lg font-bold text-sm ${radarData.overall_score >= 70 ? c.success : radarData.overall_score >= 50 ? c.warning : c.danger} border`}>
                      {radarData.overall_grade} — {radarData.overall_score}/100
                    </div>
                  </div>
                  <div className="space-y-2">
                    {radarData.dimensions?.map((dim, i) => (
                      <div key={i} className="space-y-1">
                        <div className="flex items-center gap-2">
                          <span className="text-sm">{dim.icon}</span>
                          <ScoreBar score={dim.score} label={dim.name} />
                        </div>
                        {dim.gap_suggestion && <p className={`text-[10px] ${c.highlightText} ml-10`}>💡 {dim.gap_suggestion}</p>}
                      </div>
                    ))}
                  </div>
                  {radarData.strongest && <div className={`${c.success} border rounded-lg p-3`}><p className="text-xs">💪 {radarData.strongest}</p></div>}
                  {radarData.weakest && <div className={`${c.warning} border rounded-lg p-3`}><p className="text-xs">🎯 {radarData.weakest}</p></div>}
                  {radarData.level_comparison && <p className={`text-xs ${c.textSecondary} italic`}>{radarData.level_comparison}</p>}
                  {radarData.next_actions?.length > 0 && (
                    <div className={`${c.highlightBg} border rounded-lg p-3`}>
                      <p className={`text-[10px] font-bold ${c.textMuteded} mb-1`}>{t('bsb_next_steps')}</p>
                      {radarData.next_actions.map((a, i) => <p key={i} className="text-xs">→ {a}</p>)}
                    </div>
                  )}
                  <button onClick={() => setRadarData(null)} className={`text-xs ${c.textMuteded}`}>{t('bsb_reanalyze')}</button>
                </div>
              )}
            </div>
          )}

          {/* ══════ TAB: TAILOR ══════ */}
          {activeTab === 'tailor' && (
            <div className="space-y-4">
              <div className={`${c.card} rounded-xl shadow-sm p-6 space-y-4`}>
                <h3 className={`font-bold ${c.text} flex items-center gap-2`}><span className="text-lg">🎯</span> {t('bsb_tailor_title')}</h3>
                <p className={`text-sm ${c.textSecondary}`}>{t('bsb_tailor_desc')}</p>
                <textarea value={jdText} onChange={e => setJdText(e.target.value)} rows={6} placeholder={t('bsb_jd_ph')}
                  className={`w-full p-3 border rounded-xl outline-none text-sm resize-y ${c.input}`} />
                <button onClick={handleTailor} disabled={tailorLoading || !jdText.trim()}
                  className={`w-full py-3 rounded-xl font-semibold text-sm flex items-center justify-center gap-2 ${c.btnPrimary} disabled:opacity-40`}>
                  {tailorLoading ? <><span className="inline-block animate-spin">{tool?.icon ?? '🏆'}</span> {t('bsb_tailoring')}</> : `🎯 ${t('bsb_tailor_btn')}`}</button>
              </div>
              {tailorData && (
                <div className="space-y-4">
                  {/* Match score */}
                  <div className={`${c.card} rounded-xl shadow-sm p-5`}>
                    <div className="flex items-center justify-between mb-3">
                      <h4 className={`font-bold ${c.text}`}>{t('bsb_match_score')}</h4>
                      <span className={`text-xl font-bold ${tailorData.match_score >= 70 ? (c.successFg) : c.highlightText}`}>{tailorData.match_score}%</span>
                    </div>
                    <ScoreBar score={tailorData.match_score} />
                    {tailorData.match_summary && <p className={`text-xs ${c.textSecondary} mt-2`}>{tailorData.match_summary}</p>}
                  </div>
                  {/* JD Requirements */}
                  {tailorData.jd_requirements?.length > 0 && (
                    <div className={`${c.card} rounded-xl shadow-sm p-5`}>
                      <h4 className={`font-bold ${c.text} mb-3`}>📋 {t('bsb_jd_requirements')}</h4>
                      <div className="flex flex-wrap gap-1.5">
                        {tailorData.jd_requirements.map((req, i) => (
                          <span key={i} className={`text-[10px] px-2 py-1 rounded-full border font-semibold ${req.priority === 'must_have' ? c.danger : req.priority === 'nice_to_have' ? c.warning : c.highlightBg}`}>
                            {req.requirement}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}
                  {/* Relevance ranking */}
                  {tailorData.relevance_ranking?.length > 0 && (
                    <div className={`${c.card} rounded-xl shadow-sm p-5`}>
                      <h4 className={`font-bold ${c.text} mb-3`}>🎯 {t('bsb_per_bullet')}</h4>
                      <div className="space-y-3">
                        {tailorData.relevance_ranking.map((rr, i) => (
                          <div key={i} className={`p-3 rounded-lg ${c.cardAlt} border`}>
                            <div className="flex items-center justify-between mb-1">
                              <span className={`text-[10px] font-bold ${c.textMuted}`}>{t('bsb_accomplishment_num', { num: (rr.accomplishment_index ?? i) + 1 })}</span>
                              <span className={`text-xs font-bold ${rr.relevance_score >= 70 ? c.successFg : c.highlightText}`}>{rr.relevance_score}%</span>
                            </div>
                            {rr.tailored_version && (
                              <p className={`text-sm ${c.text} mb-1`}>{rr.tailored_version}</p>
                            )}
                            {rr.keywords_used?.length > 0 && (
                              <div className="flex flex-wrap gap-1 mt-1">
                                {rr.keywords_used.map((k, ki) => <span key={ki} className={`text-[9px] px-1.5 py-0.5 rounded ${c.highlightBg} border`}>{k}</span>)}
                              </div>
                            )}
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                  {/* Tailored bullets */}
                  {tailorData.tailored_resume_bullets?.length > 0 && (
                    <div className={`${c.card} rounded-xl shadow-sm p-5`}>
                      <div className="flex items-center justify-between mb-3">
                        <h4 className={`font-bold ${c.text}`}>📄 {t('bsb_tailored_bullets')}</h4>
                      </div>
                      <div className="space-y-2">
                        {tailorData.tailored_resume_bullets.map((b, i) => (
                          <p key={i} className={`text-sm ${c.text}`}>• {b}</p>
                        ))}
                      </div>
                    </div>
                  )}
                  {/* Cover letter opening */}
                  {tailorData.cover_letter_opening && (
                    <div className={`${c.card} rounded-xl shadow-sm p-5`}>
                      <div className="flex items-center justify-between mb-3">
                        <h4 className={`font-bold ${c.text}`}>✉️ {t('bsb_cover_opening')}</h4>
                        
                      </div>
                      <p className={`text-sm ${c.text} leading-relaxed`}>{tailorData.cover_letter_opening}</p>
                    </div>
                  )}
                  {/* Gaps */}
                  {tailorData.gaps?.length > 0 && (
                    <div className={`${c.card} rounded-xl shadow-sm p-5`}>
                      <h4 className={`font-bold ${c.text} mb-3`}>⚠️ {t('bsb_gaps_address')}</h4>
                      <div className="space-y-2">
                        {tailorData.gaps.map((gap, i) => (
                          <div key={i} className={`p-3 rounded-lg border ${gap.severity === 'critical' ? c.danger : gap.severity === 'moderate' ? c.warning : c.highlightBg}`}>
                            <div className="flex items-center gap-2 mb-1">
                              <span className="text-[10px] font-black uppercase">{gap.severity}</span>
                              <span className={`text-xs font-bold ${c.text}`}>{gap.requirement}</span>
                            </div>
                            <p className="text-xs">{gap.suggestion}</p>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}

          {/* ══════ TAB: INTERVIEW ══════ */}
          {activeTab === 'interview' && (
            <div className="space-y-4">
              {!matrixData && (
                <div className={`${c.card} rounded-xl shadow-sm p-6 text-center`}>
                  <span className="text-4xl block mb-3">🎤</span>
                  <h3 className={`font-bold ${c.text} mb-2`}>{t('bsb_interview_title')}</h3>
                  <p className={`text-sm ${c.textSecondary} mb-4`}>{t('bsb_interview_desc')}</p>
                  <button onClick={handleMatrix} disabled={matrixLoading}
                    className={`${c.btnPrimary} disabled:opacity-40 px-6 py-3 rounded-xl font-semibold text-sm`}>
                    {matrixLoading ? <><span className="inline-block animate-spin">{tool?.icon ?? '🏆'}</span> {t('bsb_building_matrix')}</> : `🎤 ${t('bsb_build_interview')}`}</button>
                </div>
              )}
              {matrixData && (
                <div className="space-y-4">
                  {/* Coverage summary */}
                  <div className={`${c.card} rounded-xl shadow-sm p-5`}>
                    <div className="flex items-center justify-between mb-3">
                      <h4 className={`font-bold ${c.text}`}>🎤 {t('bsb_interview_coverage')}</h4>
                      <span className={`text-sm font-bold ${matrixData.coverage_score >= 70 ? (c.successFg) : c.highlightText}`}>
                        {matrixData.covered_count}/{matrixData.questions?.length} {t('bsb_covered')} ({matrixData.coverage_score}%){matrixData.gap_count ? ` · ${matrixData.gap_count} ${t('bsb_gaps_suffix')}` : ''}
                      </span>
                    </div>
                    <ScoreBar score={matrixData.coverage_score} />
                    {matrixData.prep_summary && <p className={`text-xs ${c.textSecondary} mt-2`}>{matrixData.prep_summary}</p>}
                  </div>
                  {/* Covered questions */}
                  <div className={`${c.card} rounded-xl shadow-sm p-5`}>
                    <h4 className={`font-bold ${c.text} mb-3`}>✅ {t('bsb_ready_for')}</h4>
                    <div className="space-y-2">
                      {matrixData.questions?.filter(q => q.best_match?.type !== 'none').map((q, i) => (
                        <div key={i} className={`p-3 rounded-lg ${c.cardAlt}`}>
                          <div className="flex-1">
                            <p className={`text-sm font-semibold ${c.text}`}>"{q.question}"</p>
                            <div className="flex items-center gap-2 mt-1">
                              <span className={`text-[9px] px-1.5 py-0.5 rounded ${c.highlightBg} border font-bold`}>{q.category}</span>
                              <span className={`text-[9px] ${c.textMuteded}`}>{q.likelihood === 'very_likely' ? `🔴 ${t('bsb_very_likely')}` : q.likelihood === 'likely' ? `🟡 ${t('bsb_likely')}` : `⚪ ${t('bsb_possible')}`}</span>
                            </div>
                          </div>
                          {q.best_match?.angle && <p className={`text-xs ${c.highlightText} mt-2`}>💡 {q.best_match.angle}</p>}
                          {q.best_match?.opening_line && <p className={`text-xs ${c.text} mt-1 italic`}>{t('bsb_start_with')} "{q.best_match.opening_line}"</p>}
                        </div>
                      ))}
                    </div>
                  </div>
                  {/* Gaps */}
                  {matrixData.gaps?.length > 0 && (
                    <div className={`${c.card} rounded-xl shadow-sm p-5`}>
                      <h4 className={`font-bold ${c.text} mb-3`}>⚠️ {t('bsb_gaps_no_answer')}</h4>
                      <div className="space-y-2">
                        {matrixData.gaps.map((gap, i) => (
                          <div key={i} className={`p-3 rounded-lg ${c.warning} border`}>
                            <p className={`text-sm font-semibold`}>"{gap.question}"</p>
                            <p className={`text-xs mt-1`}>💡 {gap.suggestion}</p>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                  <button onClick={() => setMatrixData(null)} className={`text-xs ${c.textMuteded}`}>{t('bsb_rebuild_matrix')}</button>
                </div>
              )}
            </div>
          )}

          {/* ══════ TAB: VOICE ══════ */}
          {activeTab === 'voice' && (
            <div className="space-y-4">
              <div className={`${c.card} rounded-xl shadow-sm p-6 space-y-4`}>
                <h3 className={`font-bold ${c.text} flex items-center gap-2`}><span className="text-lg">✍️</span> {t('bsb_voice_title')}</h3>
                <p className={`text-sm ${c.textSecondary}`}>{t('bsb_voice_desc')}</p>
                <textarea value={voiceSample} onChange={e => setVoiceSample(e.target.value)} rows={5} placeholder={t('bsb_voice_ph')}
                  className={`w-full p-3 border rounded-xl outline-none text-sm resize-y ${c.input}`} />
                <button onClick={handleVoiceMatch} disabled={voiceLoading || !voiceSample.trim()}
                  className={`w-full py-3 rounded-xl font-semibold text-sm flex items-center justify-center gap-2 ${c.btnPrimary} disabled:opacity-40`}>
                  {voiceLoading ? <><span className="inline-block animate-spin">{tool?.icon ?? '🏆'}</span> {t('bsb_matching_voice')}</> : `✍️ ${t('bsb_rewrite_voice')}`}</button>
              </div>
              {voiceData && (
                <div className="space-y-4">
                  {/* Voice profile */}
                  {voiceData.voice_profile && (
                    <div className={`${c.card} rounded-xl shadow-sm p-5`}>
                      <h4 className={`font-bold ${c.text} mb-3`}>🔊 {t('bsb_voice_profile')}</h4>
                      <p className={`text-sm ${c.textSecondary} mb-3`}>{voiceData.voice_summary}</p>
                      <div className="flex flex-wrap gap-2">
                        <span className={`text-[10px] px-2.5 py-1 rounded-full ${c.highlightBg} border font-bold`}>{t('bsb_sentences')} {voiceData.voice_profile.sentence_length}</span>
                        <span className={`text-[10px] px-2.5 py-1 rounded-full ${c.highlightBg} border font-bold`}>{t('bsb_formality')} {voiceData.voice_profile.formality}</span>
                        <span className={`text-[10px] px-2.5 py-1 rounded-full ${c.highlightBg} border font-bold`}>{t('bsb_perspective')} {voiceData.voice_profile.perspective}</span>
                      </div>
                      {voiceData.voice_profile.style_notes && <p className={`text-xs ${c.textMuteded} mt-2 italic`}>{voiceData.voice_profile.style_notes}</p>}
                      {voiceData.voice_profile.prefers?.length > 0 && <p className={`text-xs ${c.textSecondary} mt-1`}>✓ {t('bsb_gravitate')} {voiceData.voice_profile.prefers.join(', ')}</p>}
                      {voiceData.voice_profile.avoids?.length > 0 && <p className={`text-xs ${c.textMuteded} mt-0.5`}>✗ {t('bsb_avoid')} {voiceData.voice_profile.avoids.join(', ')}</p>}
                    </div>
                  )}
                  {/* Rewritten transformations */}
                  {voiceData.rewritten_transformations?.length > 0 && (
                    <div className={`${c.card} rounded-xl shadow-sm p-5`}>
                      <h4 className={`font-bold ${c.text} mb-3`}>{t('bsb_acc_in_voice')}</h4>
                      <div className="space-y-3">
                        {voiceData.rewritten_transformations.map((rt, i) => (
                          <div key={i} className="space-y-1.5">
                            <div className={`${c.beforeBg} border rounded-lg p-2.5`}>
                              <p className={`text-[10px] font-bold ${c.textMuteded} mb-0.5`}>{t('bsb_ai_version')}</p>
                              <p className={`text-xs ${c.textMuteded}`}>{rt.original_ai_version}</p>
                            </div>
                            <div className={`${c.afterBg} border rounded-lg p-2.5`}>
                              <p className={`text-[10px] font-bold ${c.highlightText} mb-0.5`}>{t('bsb_your_voice')}</p>
                              <p className={`text-sm font-semibold ${c.text}`}>{rt.voice_matched_version}</p>
                            </div>
                            {rt.what_changed && <p className={`text-[10px] ${c.textMuted} px-1`}>✏️ {rt.what_changed}</p>}
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                  {/* Rewritten resume bullets */}
                  {voiceData.rewritten_resume_bullets?.length > 0 && (
                    <div className={`${c.card} rounded-xl shadow-sm p-5`}>
                      <div className="flex items-center justify-between mb-3">
                        <h4 className={`font-bold ${c.text}`}>📄 {t('bsb_bullets_voice')}</h4>
                      </div>
                      <div className="space-y-1.5">
                        {voiceData.rewritten_resume_bullets.map((b, i) => (
                          <p key={i} className={`text-sm ${c.text}`}>• {b}</p>
                        ))}
                      </div>
                    </div>
                  )}
                  {/* Rewritten LinkedIn */}
                  {voiceData.rewritten_linkedin && (
                    <div className={`${c.card} rounded-xl shadow-sm p-5`}>
                      <div className="flex items-center justify-between mb-3">
                        <h4 className={`font-bold ${c.text}`}>💼 {t('bsb_linkedin_voice')}</h4>
                        
                      </div>
                      <p className={`text-sm ${c.text} whitespace-pre-wrap leading-relaxed`}>{voiceData.rewritten_linkedin}</p>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}

          {/* ══════ TAB: OUTPUTS ══════ */}
          {activeTab === 'outputs' && (
            <div className="space-y-4">
              {bullets.length > 0 && (
                <div className={`${c.card} rounded-xl shadow-sm p-6`}>
                  <div className="flex items-center justify-between mb-3">
                    <h3 className={`font-bold ${c.text} flex items-center gap-2`}><span className="text-lg">📄</span> {t('bsb_resume_bullets')}</h3>
                  </div>
                  <div className="space-y-2">
                    {bullets.map((bullet, i) => (
                      <p key={i} className={`text-sm ${c.text}`}>• {bullet}</p>
                    ))}
                  </div>
                </div>
              )}
              {allStarStories.length > 0 && (
                <div className={`${c.card} rounded-xl shadow-sm p-6`}>
                  <button onClick={() => toggleSection('star')} className={`w-full flex items-center justify-between ${c.text}`}>
                    <h3 className="font-bold flex items-center gap-2"><span className="text-lg">⭐</span> {t('bsb_star_stories')} ({allStarStories.length})</h3>
                    <span className="text-sm">{expandedSections.star === false ? '▼' : '▲'}</span>
                  </button>
                  {expandedSections.star !== false && (
                    <div className="space-y-4 mt-4">
                      {allStarStories.map((story, idx) => (
                        <div key={idx} className="space-y-2">
                          {idx > 0 && <div className={`border-t ${c.border} my-3`} />}
                          <div className="flex items-center justify-between">
                            <p className={`text-xs font-bold ${c.highlightText}`}>
                              {story.source_index !== undefined ? `${t('bsb_from_num', { num: story.source_index + 1 })} ` : ''}{story.title}
                            </p>
                            
                          </div>
                          <div className="grid grid-cols-1 gap-2">
                            {[{ k: 'S', l: t('bsb_star_situation'), v: story.situation }, { k: 'T', l: t('bsb_star_task'), v: story.task },
                              { k: 'A', l: t('bsb_star_action'), v: story.action }, { k: 'R', l: t('bsb_star_result'), v: story.result }]
                              .map(s => s.v ? (
                                <div key={s.k} className={`flex items-start gap-2 ${c.cardAlt} rounded-lg p-2.5`}>
                                  <span className={`text-[10px] font-black w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0 ${c.starBadge}`}>{s.k}</span>
                                  <div><p className={`text-[10px] font-bold ${c.textMuteded}`}>{s.l}</p><p className={`text-xs ${c.text}`}>{s.v}</p></div>
                                </div>
                              ) : null)}
                          </div>
                          {story.good_for_questions?.length > 0 && (
                            <div className="flex flex-wrap gap-1.5 px-1">
                              <span className={`text-[10px] font-bold ${c.textMuteded}`}>{t('bsb_good_for')}</span>
                              {story.good_for_questions.map((q, qi) => <span key={qi} className={`text-[10px] px-2 py-0.5 rounded-full ${c.highlightBg} border`}>{q}</span>)}
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}
              {r.linkedin_about && (
                <div className={`${c.card} rounded-xl shadow-sm p-6`}>
                  <div className="flex items-center justify-between mb-3">
                    <h3 className={`font-bold ${c.text} flex items-center gap-2`}><span className="text-lg">💼</span> {t('bsb_linkedin_about')}</h3>
                    
                  </div>
                  <div className={`${c.cardAlt} rounded-lg p-4`}><p className={`text-sm ${c.text} whitespace-pre-wrap leading-relaxed`}>{r.linkedin_about}</p></div>
                </div>
              )}
              {r.performance_review && (
                <div className={`${c.card} rounded-xl shadow-sm p-6`}>
                  <div className="flex items-center justify-between mb-3">
                    <h3 className={`font-bold ${c.text} flex items-center gap-2`}><span className="text-lg">📝</span> {t('bsb_perf_review')}</h3>
                    
                  </div>
                  <div className={`${c.cardAlt} rounded-lg p-4`}><p className={`text-sm ${c.text} whitespace-pre-wrap leading-relaxed`}>{r.performance_review}</p></div>
                </div>
              )}
            </div>
          )}

          {/* ══════ TAB: RAISE ══════ */}
          {activeTab === 'raise' && raise.summary && (
            <div className="space-y-4">
              <div className={`${c.card} rounded-xl shadow-sm p-6`}>
                <div className="flex items-center justify-between mb-3">
                  <h3 className={`font-bold ${c.text} flex items-center gap-2`}><span className="text-lg">💰</span> {t('bsb_raise_ammo')}</h3>
                </div>
                <p className={`text-sm ${c.textSecondary} mb-4`}>{raise.summary}</p>
                {raise.total_estimated_value && (
                  <div className={`p-4 rounded-xl ${c.success} border text-center mb-4`}>
                    <p className="text-xs font-bold mb-1">{t('bsb_est_value')}</p>
                    <p className="text-xl font-bold">{raise.total_estimated_value}</p>
                  </div>
                )}
                {raise.value_statements?.length > 0 && (
                  <div className="space-y-2 mb-4">
                    {raise.value_statements.map((vs, i) => (
                      <div key={i} className={`${c.success} border rounded-lg p-3`}>
                        <p className="text-xs font-bold">{vs}</p>
                      </div>
                    ))}
                  </div>
                )}
                {raise.script && (
                  <div className={`p-4 rounded-xl ${c.highlightBg} border`}>
                    <p className={`text-[10px] font-bold ${c.textMuteded} uppercase mb-2`}>{t('bsb_say_this')}</p>
                    <p className={`text-sm ${c.text} leading-relaxed`}>"{raise.script}"</p>
                    <div className="mt-2"></div>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Cross-references */}
          <div className="text-center space-y-2">
            <p className={`text-xs ${c.textMuteded}`}>
              {t('bsb_leverage_xref')} 💪 <a href="/LeverageLogic" className={linkStyle}>{t('bsb_leverage_logic')}</a> {t('bsb_leverage_xref_end')}
            </p>
          </div>

          <div className={`p-4 rounded-xl text-center ${c.closingNote}`}>
            <p className={`text-xs ${c.textMuteded}`}>✨ {t('bsb_closing_note')}</p>
          </div>
          <p className={`text-xs text-center ${c.textMuteded}`}>{t('bsb_ai_disclaimer')}</p>
        </div>
      )}
    </div>
  );
};

BragSheetBuilder.displayName = 'BragSheetBuilder';
export default BragSheetBuilder;
