import React, { useState, useCallback, useRef, useEffect } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { useRegisterActions } from '../components/ActionBarContext';
import { CopyBtn } from '../components/ActionButtons';
import { usePersistentState } from '../hooks/usePersistentState';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

const EXAMPLE_ROUTINES = [
  {
    routine: 'Wake up, make coffee, check phone for 20 mins, work from home 9-5, eat lunch at desk, gym 3x/week after work, cook or order dinner, watch TV or scroll until 11pm, repeat.',
    context: 'Remote software engineer, been in this city 2 years, same friend group, same bars',
    stuck: 'Everything feels fine but nothing feels exciting. The weeks blur together.',
  },
  {
    routine: 'Up at 6:30, get kids ready, commute 45 mins, back-to-back meetings all day, commute home, dinner with family, help with homework, collapse on couch, bed by 10.',
    context: 'Manager at a mid-size company, two kids under 10, been in the same role 4 years',
    stuck: 'No time for anything that feels like mine. Running on fumes.',
  },
  {
    routine: 'Sleep until 9, freelance work from home (highly variable hours), social media between tasks, lunch whenever, occasional gym, evenings very unstructured.',
    context: 'Freelance designer, work is good but inconsistent, mostly works alone',
    stuck: 'Productive some days, completely derailed others. No real rhythm.',
  },
];

// ════════════════════════════════════════════════════════════
// MAIN COMPONENT
// ════════════════════════════════════════════════════════════
const ChaosPilot = ({ tool }) => {
  const { callToolEndpoint, loading } = useClaudeAPI();
  const { isDark } = useTheme();

  const c = {
    card:            isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:         isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:           isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:            isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary:   isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:       isDark ? 'text-zinc-500' : 'text-gray-400',
    labelText:       isDark ? 'text-zinc-200' : 'text-gray-700',
    required:        isDark ? 'text-amber-400' : 'text-amber-500',
    badgeNeutral:    isDark ? 'bg-zinc-700 text-zinc-300' : 'bg-gray-100 text-gray-600',
    accentTxt:       isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:      isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:    isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:          isDark ? 'border-zinc-700' : 'border-gray-200',
    success:         isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:         isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:          isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-200 text-red-800',
    textDanger:      isDark ? 'text-red-300' : 'text-red-700',
    infoBox:         isDark ? 'bg-sky-900/20 border-sky-700 text-sky-200' : 'bg-sky-50 border-sky-200 text-sky-800',
    pillActive:      isDark ? 'border-cyan-500 bg-cyan-900/30 text-cyan-200' : 'border-cyan-600 bg-cyan-100 text-cyan-900',
    pillInactive:    isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500' : 'border-gray-300 text-gray-500 hover:border-gray-400',
    disruptionHero:  isDark ? 'border-cyan-700 bg-zinc-800' : 'border-cyan-400 bg-cyan-50',
    disruptionHead:  isDark ? 'bg-cyan-900/30' : 'bg-cyan-100',
    disruptionAccent: isDark ? 'text-cyan-400' : 'text-cyan-700',
    disruptionSub:   isDark ? 'bg-zinc-700/50 border-zinc-600' : 'bg-slate-100 border-slate-200',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-600 hover:text-cyan-700 underline underline-offset-2';

  // ── State ──
  const [error,   setError]   = useState('');
  const [results, setResults] = useState(null);

  // ── Refs ──
  const resultsRef      = useRef(null);
  const handleSubmitRef = useRef(null);
  const canSubmitRef    = useRef(false);

  // ── Persistent state ──
  const [routine,          setRoutine]          = usePersistentState('chaos-pilot-routine', '');
  const [context,          setContext]          = usePersistentState('chaos-pilot-context', '');
  const [goals,            setGoals]            = usePersistentState('chaos-pilot-goals', '');
  const [whatsFeelingStuck, setWhatsFeelingStuck] = usePersistentState('chaos-pilot-stuck', '');
  const [history,          setHistory]          = usePersistentState('chaos-pilot-history', []);

  // ── Handlers ──
  const handleSubmit = async () => {
    if (!routine.trim()) return;
    setError('');
    setResults(null);
    try {
      const data = await callToolEndpoint('chaos-pilot', {
        routine: routine.trim(),
        context: context.trim() || undefined,
        goals: goals.trim() || undefined,
        whatsFeelingStuck: whatsFeelingStuck.trim() || undefined,
      });
      setResults(data);
      const entry = {
        id: Date.now(),
        timestamp: new Date().toISOString(),
        preview: routine.trim().slice(0, 40),
        result: data,
      };
      setHistory(prev => [entry, ...prev].slice(0, 6));
    } catch (e) {
      setError(e.message || 'Failed to design your disruption.');
    }
  };

  const handleReset = () => {
    setResults(null);
    setRoutine('');
    setContext('');
    setGoals('');
    setWhatsFeelingStuck('');
    setError('');
  };

  const handleExample = () => {
    const ex = EXAMPLE_ROUTINES[Math.floor(Math.random() * EXAMPLE_ROUTINES.length)];
    setRoutine(ex.routine);
    setContext(ex.context || '');
    setWhatsFeelingStuck(ex.stuck || '');
    setResults(null);
    setError('');
  };

  // ── Assign refs every render ──
  handleSubmitRef.current = handleSubmit;
  canSubmitRef.current = !loading && !!routine.trim();

  // ── Build copy text ──
  const buildFullText = useCallback(() => {
    if (!results) return '';
    const d = results.the_disruption;
    const p = results.pattern_diagnosis;
    let t = `🎰 CHAOS PILOT\n\n`;
    t += `THE INVISIBLE RUT:\n${p?.the_invisible_rut}\n`;
    if (p?.why_its_invisible) t += `${p.why_its_invisible}\n`;
    if (p?.what_its_costing) t += `What it's costing you: ${p.what_its_costing}\n`;
    t += `\nTHE DISRUPTION:\n${d?.what}\n`;
    if (d?.when) t += `When: ${d.when}\n`;
    if (d?.the_full_instruction) t += `\n${d.the_full_instruction}\n`;
    if (d?.the_slight_discomfort) t += `\nThe friction you'll feel: ${d.the_slight_discomfort}\n`;
    if (d?.why_this_one) t += `Why this one: ${d.why_this_one}\n`;
    if (results.the_downstream_effect) {
      t += `\nTHE RIPPLE EFFECT:\n`;
      if (results.the_downstream_effect.immediate) t += `First 30 min: ${results.the_downstream_effect.immediate}\n`;
      if (results.the_downstream_effect.within_a_week) t += `Within a week: ${results.the_downstream_effect.within_a_week}\n`;
      if (results.the_downstream_effect.compound_effect) t += `The door that opens: ${results.the_downstream_effect.compound_effect}\n`;
    }
    if (results.if_they_resist) t += `\nWhen you want to skip it: ${results.if_they_resist}\n`;
    return t + BRAND;
  }, [results]);

  // ── Register global actions ──
  useRegisterActions(buildFullText(), tool?.title || 'Chaos Pilot');

  // ── Scroll to results ──
  useEffect(() => {
    if (!results) return;
    const t = setTimeout(() => {
      resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }, 100);
    return () => clearTimeout(t);
  }, [results]);

  // ── Keyboard shortcut (Ctrl/Cmd+Enter) ──
  useEffect(() => {
    const handler = (e) => {
      if (e.target.tagName === 'SELECT') return;
      if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') {
        e.preventDefault();
        if (canSubmitRef.current) handleSubmitRef.current();
      }
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, []);

  // ════════════════════════════════════════════════════════════
  // RENDER
  // ════════════════════════════════════════════════════════════
  return (
    <div className={`space-y-4 ${c.text}`}>

      {/* ── Input Card ── */}
      <div className={`${c.card} rounded-xl shadow-lg p-5 border ${c.border}`}>

        {/* Standard header — with reset top-right */}
        <div className="mb-4 pb-3 border-b border-zinc-500">
          <div className="flex items-center justify-between">
            <div>
              <h2 className={`text-xl font-bold ${c.text} flex items-center gap-2`}>
                <span className="mr-2">{tool?.icon ?? '🎰'}</span>{tool?.title ?? 'Chaos Pilot'}
              </h2>
              <p className={`text-sm ${c.textSecondary}`}>{tool?.tagline ?? 'One calculated disruption. Not random — strategically chaotic.'}</p>
            </div>
            {(!!results || !!routine.trim()) && (
              <button
                onClick={handleReset}
                className={`${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs`}
              >
                ↺ Start Over
              </button>
            )}
          </div>
        </div>

        <div className="space-y-4">
          {/* Required field */}
          <div>
            <label className={`block text-sm font-semibold mb-1.5 ${c.text}`}>
              Your typical week, hour by hour <span className={c.required}>*</span>
            </label>
            <textarea
              value={routine}
              onChange={e => setRoutine(e.target.value)}
              placeholder="Walk me through a normal week — wake up time, work routine, evenings, weekends. The more specific, the better the disruption."
              rows={5}
              maxLength={800}
              className={`w-full px-4 py-3 rounded-xl border text-sm resize-none focus:outline-none transition-colors ${c.input}`}
            />
            <p className={`text-xs ${c.textMuted} mt-1`}>Ctrl+Enter to submit</p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <label className={`block text-sm font-semibold mb-1.5 ${c.text}`}>
                Context about you <span className={`font-normal ${c.textMuted}`}>(optional)</span>
              </label>
              <textarea
                value={context}
                onChange={e => setContext(e.target.value)}
                placeholder="Job, city, living situation, life stage…"
                rows={2}
                maxLength={300}
                className={`w-full px-4 py-3 rounded-xl border text-sm resize-none focus:outline-none transition-colors ${c.input}`}
              />
            </div>
            <div>
              <label className={`block text-sm font-semibold mb-1.5 ${c.text}`}>
                What's feeling stale? <span className={`font-normal ${c.textMuted}`}>(optional)</span>
              </label>
              <textarea
                value={whatsFeelingStuck}
                onChange={e => setWhatsFeelingStuck(e.target.value)}
                placeholder="What's the vague dissatisfaction you can't quite name…"
                rows={2}
                maxLength={300}
                className={`w-full px-4 py-3 rounded-xl border text-sm resize-none focus:outline-none transition-colors ${c.input}`}
              />
            </div>
          </div>

          {error && (
            <div className={`p-3 rounded-xl border text-sm ${c.danger}`}>
              <span className="mr-1">⚠️</span>{error}
            </div>
          )}

          <div className="flex gap-2">
            <button
              onClick={handleSubmit}
              disabled={loading || !routine.trim()}
              className={`flex-1 w-full py-3 min-h-[48px] rounded-xl font-bold disabled:opacity-40 transition-colors flex items-center justify-center gap-2 ${c.btnPrimary}`}
            >
              {loading
                ? <><span className="animate-spin inline-block">{tool?.icon ?? '🎰'}</span> Designing your disruption…</>
                : <><span>{tool?.icon ?? '🎰'}</span> Give Me My Disruption</>}
            </button>
            <button
              onClick={handleExample}
              disabled={loading}
              className={`px-4 py-3 rounded-xl text-sm font-medium transition-colors ${c.btnSecondary}`}
            >
              Example
            </button>
          </div>

          {/* Pre-result cross-ref — below submit button */}
          <p className={`text-xs text-center ${c.textMuted}`}>
            Want to find the single highest-leverage habit change?{' '}
            <a href="/OnePercenter" className={linkStyle}>🎯 One Percenter</a> does the math.
          </p>
        </div>
      </div>

      {/* ── History panel ── */}
      {history.length > 0 && !results && (
        <div className={`${c.card} rounded-xl border ${c.border} p-4`}>
          <h3 className={`text-sm font-bold ${c.text} mb-3`}>🕐 Recent Disruptions</h3>
          <div className="space-y-1.5">
            {history.map(entry => (
              <button
                key={entry.id}
                onClick={() => setResults(entry.result)}
                className={`w-full text-left px-3 py-2 rounded-lg ${c.btnSecondary} text-xs`}
              >
                <span className={c.textMuted}>
                  {new Date(entry.timestamp).toLocaleDateString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })}
                </span>
                <span className={`ml-2 ${c.text}`}>{entry.preview}…</span>
              </button>
            ))}
          </div>
        </div>
      )}

      {/* ── Results ── */}
      {results && (
        <div ref={resultsRef} className="space-y-4">

          {/* Regenerate */}
          <div className="flex items-center justify-start">
            <button
              onClick={handleSubmit}
              disabled={loading || !routine.trim()}
              className={`px-4 py-2 rounded-lg text-sm font-bold disabled:opacity-40 transition-colors ${c.btnPrimary}`}
            >
              {loading ? <span className="animate-spin inline-block">{tool?.icon ?? '🎰'}</span> : <><span>🎲</span> Different Disruption</>}
            </button>
          </div>

          {/* Pattern diagnosis */}
          <div className={`${c.card} rounded-xl border ${c.border} p-5`}>
            <p className={`text-xs font-black uppercase tracking-widest mb-3 ${c.textMuted}`}>🔍 The Invisible Rut</p>
            <p className={`text-base font-bold mb-2 ${c.text}`}>{results.pattern_diagnosis?.the_invisible_rut}</p>
            {results.pattern_diagnosis?.why_its_invisible && (
              <p className={`text-sm mb-2 ${c.textSecondary}`}>{results.pattern_diagnosis.why_its_invisible}</p>
            )}
            {results.pattern_diagnosis?.what_its_costing && (
              <div className={`mt-3 p-3 rounded-xl border ${c.danger}`}>
                <p className={`text-xs font-bold uppercase tracking-wide mb-1 ${c.textDanger}`}>What it's costing you</p>
                <p className={`text-sm ${c.textDanger}`}>{results.pattern_diagnosis.what_its_costing}</p>
              </div>
            )}
          </div>

          {/* THE DISRUPTION — hero card */}
          {results.the_disruption && (
            <div className={`rounded-xl border-2 overflow-hidden ${c.disruptionHero}`}>
              <div className={`px-6 py-4 ${c.disruptionHead}`}>
                <p className={`text-xs font-black uppercase tracking-widest mb-1 ${c.disruptionAccent}`}>🎰 Your Disruption</p>
                <p className={`text-lg font-bold ${c.text}`}>{results.the_disruption.what}</p>
                {results.the_disruption.when && (
                  <p className={`text-sm mt-1 font-medium ${c.disruptionAccent}`}>📅 {results.the_disruption.when}</p>
                )}
              </div>
              <div className="px-6 py-5 space-y-4">
                {results.the_disruption.the_full_instruction && (
                  <p className={`text-sm leading-relaxed italic ${c.textSecondary}`}>
                    "{results.the_disruption.the_full_instruction}"
                  </p>
                )}
                {results.the_disruption.the_slight_discomfort && (
                  <div className={`p-3 rounded-xl border ${c.disruptionSub}`}>
                    <p className={`text-xs font-bold uppercase tracking-wide mb-1 ${c.textMuted}`}>😬 The friction you'll feel</p>
                    <p className={`text-sm ${c.textSecondary}`}>{results.the_disruption.the_slight_discomfort}</p>
                  </div>
                )}
                {results.the_disruption.why_this_one && (
                  <div>
                    <p className={`text-xs font-bold uppercase tracking-wide mb-1 ${c.textMuted}`}>Why this one specifically</p>
                    <p className={`text-sm ${c.textSecondary}`}>{results.the_disruption.why_this_one}</p>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Downstream effects */}
          {results.the_downstream_effect && (
            <div className={`${c.card} rounded-xl border ${c.border} p-5 space-y-3`}>
              <p className={`text-xs font-black uppercase tracking-widest ${c.textMuted}`}>⚡ The Ripple Effect</p>
              {[
                { key: 'immediate',       label: 'First 30 minutes',    icon: '⚡' },
                { key: 'within_a_week',   label: 'Within a week',       icon: '🌊' },
                { key: 'compound_effect', label: 'The door that opens',  icon: '🚪' },
              ].map(row => results.the_downstream_effect[row.key] && (
                <div key={row.key} className="flex gap-3">
                  <span className="flex-shrink-0 text-lg">{row.icon}</span>
                  <div>
                    <p className={`text-xs font-bold uppercase tracking-wide mb-0.5 ${c.textMuted}`}>{row.label}</p>
                    <p className={`text-sm ${c.textSecondary}`}>{results.the_downstream_effect[row.key]}</p>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Resistance */}
          {results.if_they_resist && (
            <div className={`rounded-xl border p-4 ${c.warning}`}>
              <p className="text-xs font-bold uppercase tracking-wider mb-2">🧠 When You Want to Skip It</p>
              <p className="text-sm">{results.if_they_resist}</p>
            </div>
          )}

          {/* Cross-refs — post-result */}
          <div className={`${c.cardAlt} rounded-xl border ${c.border} p-4 space-y-2`}>
            <p className={`text-xs ${c.textMuted} text-center`}>
              Want to engineer a lasting change?{' '}
              <a href="/AlternatePath" className={linkStyle}>🛤️ Alternate Path</a>{' '}
              maps the concrete steps between where you are and where you want to be.
            </p>
            <p className={`text-xs ${c.textMuted} text-center`}>
              Want more opportunities to cross your path?{' '}
              <a href="/LuckSurface" className={linkStyle}>🍀 Luck Surface</a>{' '}
              expands where opportunity can find you.
            </p>
          </div>

          {/* AI disclaimer */}
          <p className={`text-xs text-center ${c.textMuted}`}>
            AI-generated — treat as a creative prompt, not a prescription.
          </p>

        </div>
      )}
    </div>
  );
};

ChaosPilot.displayName = 'ChaosPilot';
export default ChaosPilot;
