import React, { useState, useCallback, useRef, useEffect } from 'react';
import { useRegisterActions } from '../components/ActionBarContext';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useTranslation } from '../i18n/useTranslation';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

// ════════════════════════════════════════════════════════════
// MAIN COMPONENT
// ════════════════════════════════════════════════════════════
const ColdOpenCraft = ({ tool }) => {
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();

  // Channel / tone option configs (labels localized via t()).
  const CHANNELS = [
    { value: 'email',        label: t('coc_ch_email'),     emoji: '📧' },
    { value: 'linkedin',     label: t('coc_ch_linkedin'),  emoji: '💼' },
    { value: 'twitter_dm',   label: t('coc_ch_twitter'),   emoji: '🐦' },
    { value: 'instagram_dm', label: t('coc_ch_instagram'), emoji: '📸' },
    { value: 'text',         label: t('coc_ch_text'),      emoji: '💬' },
    { value: 'in_person',    label: t('coc_ch_inperson'),  emoji: '🤝' },
  ];

  const TONES = [
    { value: 'safe',   label: t('coc_tone_safe'),   emoji: '🛡️', desc: t('coc_tone_safe_desc') },
    { value: 'medium', label: t('coc_tone_medium'), emoji: '⚖️', desc: t('coc_tone_medium_desc') },
    { value: 'bold',   label: t('coc_tone_bold'),   emoji: '🔥', desc: t('coc_tone_bold_desc') },
  ];


  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-400' : 'text-gray-500',
    required:      isDark ? 'text-amber-400' : 'text-amber-700',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-200 text-red-800',
    pillActive:    isDark ? 'border-cyan-500 bg-cyan-900/30 text-cyan-200' : 'border-cyan-600 bg-cyan-100 text-cyan-900',
    pillInactive:  isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500' : 'border-gray-300 text-gray-500 hover:border-gray-400',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';

  // ── Persisted state ──

  const [error, setError] = useState('');
  const [who,             setWho]             = usePersistentState('cold-open-craft-who', '');
  const [why,             setWhy]             = usePersistentState('cold-open-craft-why', '');
  const [channel,         setChannel]         = usePersistentState('cold-open-craft-channel', 'email');
  const [whatYouKnow,     setWhatYouKnow]     = usePersistentState('cold-open-craft-know', '');
  const [yourBackground,  setYourBackground]  = usePersistentState('cold-open-craft-bg', '');
  const [tone,            setTone]            = usePersistentState('cold-open-craft-tone', 'medium');
  const [results,         setResults]         = usePersistentState('cold-open-craft-results', null);
  const [sessionHistory,         setSessionHistory]         = usePersistentState('cold-open-craft-history', []);
  const resultsRef = useRef(null);

  // ── Document-level Ctrl+Enter submit ──
  useEffect(() => {
    const handler = (e) => {
      if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') {
        e.preventDefault();
        if (!loading && who.trim() && why.trim()) generate();
      }
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }); // eslint-disable-line react-hooks/exhaustive-deps

  // ── Actions ──
  const generate = useCallback(async () => {
    if (!who.trim() || !why.trim()) return;
    setError('');
    setResults(null);
    try {
      const data = await callToolEndpoint('cold-open-craft', {
        who: who.trim(),
        why: why.trim(),
        channel,
        whatYouKnow: whatYouKnow.trim() || null,
        yourBackground: yourBackground.trim() || null,
        tone,
        userLocale, userCurrency, userRegion,
      });
      setResults(data);
      const entry = {
        id: Date.now(),
        timestamp: new Date().toISOString(),
        preview: who.trim().slice(0, 40),
        result: data,
      };
      setSessionHistory(prev => [entry, ...prev].slice(0, 6));
    } catch (err) {
      setError(err.message || t('coc_error'));
    }
  }, [who, why, channel, whatYouKnow, yourBackground, tone, callToolEndpoint, userLocale, userCurrency, userRegion, t]); // eslint-disable-line react-hooks/exhaustive-deps

  const loadExample = useCallback(() => {
    setWho(t('coc_ex_who'));
    setWhy(t('coc_ex_why'));
    setChannel('email');
    setWhatYouKnow(t('coc_ex_know'));
    setYourBackground(t('coc_ex_bg'));
    setTone('medium');
    setResults(null);
  }, [setWho, setWhy, setChannel, setWhatYouKnow, setYourBackground, setTone, setResults, t]);

  const handleReset = useCallback(() => {
    setWho(''); setWhy(''); setChannel('email'); setWhatYouKnow('');
    setYourBackground(''); setTone('medium'); setResults(null); setError('');
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // ── Build copy text ──
  const buildFullText = useCallback(() => {
    if (!results) return '';
    const r = results;
    let text = `📬 ${t('coc_copy_header')}\n${t('coc_copy_reaching')} ${who}\n`;
    if (r.situation_read) text += `\n${r.situation_read}\n`;
    if (r.subject_line) text += `\n${t('coc_copy_subject')} ${r.subject_line}\n`;
    if (r.openers?.length) {
      r.openers.forEach(o => {
        text += `\n--- ${o.label} [${o.boldness}] ---\n${o.message}\n`;
        if (o.why_it_works) text += `${t('coc_copy_why')} ${o.why_it_works}\n`;
      });
    }
    if (r.what_not_to_say?.length) {
      text += `\n${t('coc_copy_donotsay')}\n${r.what_not_to_say.map(x => `• ${x}`).join('\n')}\n`;
    }
    if (r.follow_up_plan) {
      text += `\n${t('coc_copy_followup')}\n${t('coc_copy_wait')} ${r.follow_up_plan.when}\n${r.follow_up_plan.message}\n${t('coc_copy_stopwhen')} ${r.follow_up_plan.when_to_stop}`;
    }
    if (r.power_move) text += `\n\n${t('coc_copy_powermove')}\n${r.power_move}`;
    return text + BRAND;
  }, [results, who, t]);

  useRegisterActions(buildFullText(), tool?.title || 'Cold Open Craft');

  const boldnessEmoji  = (b) => b === 'safe' ? '🛡️' : b === 'bold' ? '🔥' : '⚖️';
  const boldnessColor  = (b) => b === 'safe' ? c.success : b === 'bold' ? c.warning : c.warning;
  const responseColor  = (rv) => rv === 'high' ? c.success : rv === 'low' ? c.danger : c.warning;

  const r = results;

  // ════════════════════════════════════════════════════════════
  // RENDER
  // ════════════════════════════════════════════════════════════
  return (
    <div className={`space-y-4 ${c.text}`}>

      {/* ── INPUT CARD ── */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5`}>
        {/* Standard header */}
        <div className="mb-4 pb-3 border-b border-zinc-500">
          <div className="flex items-center justify-between">
            <div>
              <h2 className={`text-xl font-bold ${c.text} flex items-center gap-2`}>
                <span className="mr-2">{tool?.icon ?? '📬'}</span>{tool?.title ?? t('coc_title')}
              </h2>
              <p className={`text-sm ${c.textSecondary}`}>{tool?.tagline ?? t('coc_tagline')}</p>
              <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className={`mt-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium border disabled:opacity-40 ${isDark ? 'text-white border-white/40' : 'text-gray-800 border-transparent'}`}>{t('try_example')}</button>
            </div>
            {(results || who.trim() || why.trim()) && (
              <button onClick={handleReset} className={`${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs`}>
                ↺ {t('start_over')}
              </button>
            )}
          </div>
        </div>

        {/* Pre-result cross-ref */}
        <p className={`text-xs text-center ${c.textMuteded} mb-4`}>
          {t('coc_xref_pre')}{' '}
          <a href="/TheAlibi" className={linkStyle}>{t('coc_thealibi')}</a> {t('coc_xref_post')}
        </p>

        <div className="space-y-4">
          {/* Who */}
          <div>
            <label className={`text-sm font-bold ${c.text} block mb-1.5`}>
              {t('coc_who_label')} <span className={c.required}>*</span>
            </label>
            <input
              type="text"
              value={who}
              onChange={e => setWho(e.target.value)}
              placeholder={t('coc_who_ph')}
              className={`w-full px-4 py-3 border rounded-xl text-sm focus:outline-none transition-colors ${c.input}`}
            />
          </div>

          {/* Why */}
          <div>
            <label className={`text-sm font-bold ${c.text} block mb-1.5`}>
              {t('coc_why_label')} <span className={c.required}>*</span>
            </label>
            <textarea
              value={why}
              onChange={e => setWhy(e.target.value)}
              placeholder={t('coc_why_ph')}
              rows={2}
              className={`w-full px-4 py-3 border rounded-xl text-sm focus:outline-none transition-colors resize-none ${c.input}`}
            />
            <p className={`text-xs ${c.textMuteded} mt-1`}>{t('coc_ctrl_enter')}</p>
          </div>

          {/* Channel */}
          <div>
            <label className={`text-sm font-bold ${c.text} block mb-2`}>{t('coc_channel_label')}</label>
            <div className="flex flex-wrap gap-1.5">
              {CHANNELS.map(ch => (
                <button
                  key={ch.value}
                  onClick={() => setChannel(ch.value)}
                  className={`px-3 py-1.5 rounded-lg text-xs font-bold border transition-colors min-h-[32px] ${
                    channel === ch.value ? c.pillActive : c.pillInactive
                  }`}
                >
                  {ch.emoji} {ch.label}
                </button>
              ))}
            </div>
          </div>

          {/* What you know */}
          <div>
            <label className={`text-sm font-bold ${c.text} block mb-1.5`}>
              {t('coc_know_label')}{' '}
              <span className={`font-normal ${c.textMuteded}`}>{t('coc_know_note')}</span>
            </label>
            <input
              type="text"
              value={whatYouKnow}
              onChange={e => setWhatYouKnow(e.target.value)}
              placeholder={t('coc_know_ph')}
              className={`w-full px-4 py-3 border rounded-xl text-sm focus:outline-none transition-colors ${c.input}`}
            />
          </div>

          {/* Your background */}
          <div>
            <label className={`text-sm font-bold ${c.text} block mb-1.5`}>
              {t('coc_bg_label')} <span className={`font-normal ${c.textMuteded}`}>{t('coc_bg_note')}</span>
            </label>
            <input
              type="text"
              value={yourBackground}
              onChange={e => setYourBackground(e.target.value)}
              placeholder={t('coc_bg_ph')}
              className={`w-full px-4 py-3 border rounded-xl text-sm focus:outline-none transition-colors ${c.input}`}
            />
          </div>

          {/* Tone */}
          <div>
            <label className={`text-sm font-bold ${c.text} block mb-2`}>{t('coc_boldness_label')}</label>
            <div className="flex gap-2">
              {TONES.map(toneOpt => (
                <button
                  key={toneOpt.value}
                  onClick={() => setTone(toneOpt.value)}
                  className={`flex-1 py-2.5 rounded-xl text-[11px] font-bold border transition-colors min-h-[44px] flex flex-col items-center gap-0.5 ${
                    tone === toneOpt.value ? c.pillActive : c.pillInactive
                  }`}
                >
                  <span className="text-base">{toneOpt.emoji}</span>
                  <span>{toneOpt.label}</span>
                  <span className={`font-normal text-[9px] ${tone === toneOpt.value ? 'opacity-80' : c.textMuteded}`}>{toneOpt.desc}</span>
                </button>
              ))}
            </div>
          </div>

          {error && (
            <div className={`${c.danger} border rounded-xl p-4 flex items-start gap-3`}>
              <span className="flex-shrink-0">⚠️</span>
              <p className="text-sm">{error}</p>
            </div>
          )}

          {/* Submit */}
          <button
          onClick={generate}
          disabled={loading || !who.trim() || !why.trim()}
          className={`w-full ${c.btnPrimary} disabled:opacity-40 disabled:cursor-not-allowed font-bold py-3 px-6 rounded-xl flex items-center justify-center gap-2 min-h-[48px] transition-colors`}
          >
          {loading
            ? <><span className="animate-spin inline-block">{tool?.icon ?? '📬'}</span> {t('coc_crafting')}</>
            : <><span>{tool?.icon ?? '📬'}</span> {t('coc_craft')}</>}
          </button>
        </div>
      </div>

      {/* ── HISTORY ── */}
      {sessionHistory.length > 0 && !results && (
        <div className={`${c.card} rounded-xl border ${c.border} p-4`}>
          <h3 className={`text-sm font-bold ${c.text} mb-3`}>🕐 {t('coc_recent')}</h3>
          <div className="space-y-1.5">
            {sessionHistory.map(entry => (
              <button
                key={entry.id}
                onClick={() => setResults(entry.result)}
                className={`w-full text-left px-3 py-2 rounded-lg ${c.btnSecondary} text-xs`}
              >
                <span className={c.textMuteded}>
                  {new Date(entry.timestamp).toLocaleDateString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })}
                </span>
                <span className={`ml-2 ${c.text}`}>{entry.preview}…</span>
              </button>
            ))}
          </div>
        </div>
      )}

      {/* ════════════════════════════════════════════════════════
          RESULTS
          ════════════════════════════════════════════════════════ */}
      {results && (
        <div ref={resultsRef} className="space-y-4">

          {/* Situation read */}
          {r.situation_read && (
            <div className={`${c.card} border ${c.border} rounded-xl p-5`}>
              <p className={`text-xs font-bold uppercase tracking-wide ${c.textMuteded} mb-2`}>🎯 {t('coc_situation_read')}</p>
              <p className={`text-sm ${c.textSecondary} leading-relaxed`}>{r.situation_read}</p>
            </div>
          )}

          {/* Subject line */}
          {r.subject_line && (
            <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
              <p className={`text-[10px] font-bold ${c.textMuteded} mb-0.5`}>{t('coc_subject_line')}</p>
              <p className={`text-sm font-bold ${c.text}`}>{r.subject_line}</p>
            </div>
          )}

          {/* Openers */}
          {r.openers?.length > 0 && (
            <div className="space-y-3">
              {r.openers.map((opener, idx) => (
                <div key={idx} className={`${c.card} border ${c.border} rounded-xl overflow-hidden`}>
                  <div className="p-5">
                    <div className="flex items-start justify-between mb-3">
                      <div>
                        <h4 className={`text-sm font-bold ${c.text}`}>{boldnessEmoji(opener.boldness)} {opener.label}</h4>
                        <div className="flex gap-1.5 mt-1">
                          <span className={`text-[9px] font-bold px-2 py-0.5 rounded-full border ${boldnessColor(opener.boldness)}`}>
                            {opener.boldness}
                          </span>
                          {opener.response_rate && (
                            <span className={`text-[9px] font-bold px-2 py-0.5 rounded-full border ${responseColor(opener.response_rate)}`}>
                              {opener.response_rate} {t('coc_response_rate')}
                            </span>
                          )}
                        </div>
                      </div>
                    </div>

                    {/* The message */}
                    <div className={`${c.cardAlt} rounded-lg p-4 mb-3`}>
                      <p className={`text-sm ${c.text} leading-relaxed whitespace-pre-line`}>{opener.message}</p>
                    </div>

                    {opener.why_it_works && (
                      <p className={`text-xs ${c.textSecondary} mb-1`}>
                        <span className="font-bold">{t('coc_why_works')}</span> {opener.why_it_works}
                      </p>
                    )}
                    {opener.best_if && (
                      <p className={`text-xs ${c.textMuteded} italic`}>{t('coc_best_if')} {opener.best_if}</p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* What not to say */}
          {r.what_not_to_say?.length > 0 && (
            <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
              <p className={`text-xs font-bold ${c.text} mb-2`}>🚫 {t('coc_not_to_say')}</p>
              <div className="space-y-1.5">
                {r.what_not_to_say.map((item, i) => (
                  <p key={i} className={`text-xs ${c.textSecondary} leading-relaxed`}>• {item}</p>
                ))}
              </div>
            </div>
          )}

          {/* Follow-up plan */}
          {r.follow_up_plan && (
            <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
              <p className={`text-xs font-bold ${c.text} mb-3`}>📅 {t('coc_followup_plan')}</p>
              <div className="space-y-3">
                <div>
                  <p className={`text-[10px] font-bold ${c.textMuteded} mb-0.5`}>{t('coc_when_followup')}</p>
                  <p className={`text-xs ${c.textSecondary}`}>{r.follow_up_plan.when}</p>
                </div>
                {r.follow_up_plan.message && (
                  <div className={`${c.cardAlt} rounded-lg p-3`}>
                    <p className={`text-[10px] font-bold ${c.textMuteded} mb-0.5`}>{t('coc_followup_msg')}</p>
                    <p className={`text-xs ${c.text}`}>{r.follow_up_plan.message}</p>
                  </div>
                )}
                <div>
                  <p className={`text-[10px] font-bold ${c.textMuteded} mb-0.5`}>{t('coc_when_stop')}</p>
                  <p className={`text-xs ${c.textSecondary}`}>{r.follow_up_plan.when_to_stop}</p>
                </div>
              </div>
            </div>
          )}

          {/* Power move */}
          {r.power_move && (
            <div className={`${c.warning} border rounded-xl p-4 flex items-start gap-3`}>
              <span className="flex-shrink-0 mt-0.5">⚡</span>
              <div>
                <p className="text-xs font-bold mb-1">{t('coc_power_move')}</p>
                <p className="text-sm leading-relaxed">{r.power_move}</p>
              </div>
            </div>
          )}

          {/* Cross-refs — post-result */}
          <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4 space-y-2`}>
            <p className={`text-xs ${c.textMuteded} text-center`}>
              {t('coc_xref2_pre')}{' '}
              <a href="/VelvetHammer" className={linkStyle}>{t('coc_velvethammer')}</a>{' '}
              {t('coc_xref2_post')}
            </p>
            {(r.openers?.some(o => o.boldness === 'bold') || yourBackground) && (
              <p className={`text-xs ${c.textMuteded} text-center`}>
                {t('coc_xref3_pre')}{' '}
                <a href="/BragSheetBuilder" className={linkStyle}>{t('coc_bragsheet')}</a>{' '}
                {t('coc_xref3_post')}
              </p>
            )}
          </div>

          {/* AI disclaimer */}
          <p className={`text-xs text-center ${c.textMuteded}`}>
            {t('coc_disclaimer')}
          </p>

        </div>
      )}
    </div>
  );
};

ColdOpenCraft.displayName = 'ColdOpenCraft';
export default ColdOpenCraft;
