import React, { useState, useRef, useEffect, useCallback } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';
import { currencySymbol } from '../utils/formatLocale';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';


const EXAMPLE = {
  company: 'United Airlines',
  industry: 'travel',
  issue: "Flight UA-2453 from SFO to EWR was canceled 90 minutes before boarding due to crew scheduling. Was rebooked 19 hours later, missed a wedding I was traveling for. UA offered $200 in flight credit; declined. No hotel offered initially despite the overnight delay. Filed online complaint two weeks ago — got a generic auto-reply, no follow-up.",
  previousAttempts: 'One online complaint via the form on united.com (2 weeks ago, no real response). One Twitter @ to @united (no response). Spoke to a gate agent at the time who was helpful but couldn\'t do anything.',
};
const ComplaintEscalationWriter = ({ tool }) => {
  const { isDark } = useTheme();
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { t } = useTranslation();
  const sym = currencySymbol(userLocale, userCurrency);

  // ─── Standard c object ───

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-500' : 'text-gray-400',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-200 text-red-800',
    required:      'text-red-500',
    // ─── Tool-specific semantic colors ───
    highlight:        isDark ? 'bg-cyan-900/20 border-cyan-700' : 'bg-cyan-50 border-cyan-300',
    hintStyle:        isDark ? 'bg-zinc-700/50 text-zinc-300' : 'bg-slate-100 text-slate-600',
    letterBox:        isDark ? 'bg-zinc-900/50 border-zinc-600' : 'bg-gray-50 border-gray-200',
    industryActive:   isDark ? 'border-cyan-500 bg-cyan-900/30 text-cyan-200' : 'border-cyan-600 bg-cyan-100 text-cyan-900',
    industryInactive: isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500' : 'border-gray-300 text-gray-500 hover:border-gray-400',
    toneActive:       isDark ? 'border-cyan-500 bg-cyan-900/30' : 'border-cyan-600 bg-cyan-50',
    toneInactive:     isDark ? 'border-zinc-600 hover:border-zinc-500' : 'border-gray-200 hover:border-gray-300',
    issueTip:         isDark ? 'text-amber-400' : 'text-amber-600',
    resolvedBtn:      isDark ? 'border-emerald-600 bg-emerald-900/30 text-emerald-300 hover:bg-emerald-900/50' : 'border-emerald-400 bg-emerald-50 text-emerald-700 hover:bg-emerald-100',
    resolvedText:     isDark ? 'text-emerald-300' : 'text-emerald-700',
    escalateBtn:      isDark ? 'border-red-700 bg-red-900/30 text-red-300 hover:bg-red-900/50' : 'border-red-300 bg-red-50 text-red-700 hover:bg-red-100',
    analyzeBtn:       isDark ? 'border-cyan-700 bg-cyan-900/30 text-cyan-300 hover:bg-cyan-900/50' : 'border-cyan-300 bg-cyan-50 text-cyan-700 hover:bg-cyan-100',
    failedText:       isDark ? 'text-red-400' : 'text-red-600',
    editDoneBtn:      isDark ? 'bg-emerald-900/30 text-emerald-300 hover:bg-emerald-900/50' : 'bg-emerald-50 text-emerald-700 hover:bg-emerald-100',
    loadingSubmit:    isDark ? 'bg-zinc-700 text-zinc-300' : 'bg-gray-100 text-gray-500',
    firstVisitLink:   isDark ? 'text-cyan-400 hover:text-cyan-300' : 'text-cyan-600 hover:text-cyan-700',
    progressTrack:    isDark ? 'bg-zinc-700' : 'bg-gray-200',
    contextBadge:     isDark ? 'bg-cyan-900/40 text-cyan-300' : 'bg-cyan-100 text-cyan-700',
    tacticsTag:       isDark ? 'bg-zinc-700 text-zinc-300' : 'bg-gray-100 text-gray-600',
    counterBox:       isDark ? 'border-cyan-700 bg-cyan-900/20' : 'border-cyan-300 bg-cyan-50',
    counterBoxHd:     isDark ? 'text-cyan-400' : 'text-cyan-700',
    // ─── Severity semantic colors (for severityConfig lookup) ───
    sevLowColor:    isDark ? 'text-green-400' : 'text-green-600',
    sevLowBg:       isDark ? 'bg-green-900/20' : 'bg-green-50',
    sevLowBorder:   isDark ? 'border-green-700' : 'border-green-200',
    sevMedColor:    isDark ? 'text-amber-400' : 'text-amber-600',
    sevMedBg:       isDark ? 'bg-amber-900/20' : 'bg-amber-50',
    sevMedBorder:   isDark ? 'border-amber-700' : 'border-amber-200',
    sevCritColor:   isDark ? 'text-red-400' : 'text-red-600',
    sevCritBg:      isDark ? 'bg-red-900/20' : 'bg-red-50',
    sevCritBorder:  isDark ? 'border-red-700' : 'border-red-200',
    redFlagsBox:      isDark ? 'bg-red-900/20 text-red-300' : 'bg-red-50 text-red-700',
    checkboxAccent:   isDark ? 'accent-cyan-500' : 'accent-cyan-600',
    evidenceChecked:  isDark ? 'bg-emerald-900/20' : 'bg-emerald-50',
    stageTabInactive: isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500 bg-transparent' : 'border-gray-300 text-gray-500 hover:border-gray-400 bg-transparent',
    timelineLine:     isDark ? 'bg-zinc-600' : 'bg-gray-300',
    timelineDotRest:  isDark ? 'bg-zinc-600' : 'bg-gray-300',
    disclaimerBox:    isDark ? 'bg-zinc-700/50' : 'bg-gray-50',
    callOpenBox:      isDark ? 'bg-sky-900/20' : 'bg-sky-50',
    callOpenText:     isDark ? 'text-sky-400' : 'text-sky-700',
    callPhrasesBox:   isDark ? 'bg-emerald-900/20' : 'bg-emerald-50',
    callPhrasesText:  isDark ? 'text-emerald-400' : 'text-emerald-700',
    callAvoidBox:     isDark ? 'bg-red-900/20' : 'bg-red-50',
    callAvoidText:    isDark ? 'text-red-400' : 'text-red-600',
    callPressureBox:  isDark ? 'border-amber-700 bg-amber-900/20' : 'border-amber-300 bg-amber-50',
    callPressureText: isDark ? 'text-amber-400' : 'text-amber-700',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-600 hover:text-cyan-700 underline underline-offset-2';

  // ─── Helper color maps (dynamic + isDark) ───
  const legalStrengthBadge = {
    strong:   isDark ? 'bg-green-900/40 text-green-300' : 'bg-green-100 text-green-700',
    moderate: isDark ? 'bg-amber-900/40 text-amber-300' : 'bg-amber-100 text-amber-700',
  };
  const legalStrengthDefault = isDark ? 'bg-zinc-700 text-zinc-400' : 'bg-gray-100 text-gray-500';

  const recoBg = {
    accept:  isDark ? 'border-green-700 bg-green-900/15' : 'border-green-200 bg-green-50',
    escalate: isDark ? 'border-red-700 bg-red-900/15' : 'border-red-200 bg-red-50',
  };
  const recoDefault = isDark ? 'border-amber-700 bg-amber-900/15' : 'border-amber-200 bg-amber-50';

  const recoBadge = {
    accept:  isDark ? 'bg-green-900/40 text-green-300' : 'bg-green-100 text-green-700',
    escalate: isDark ? 'bg-red-900/40 text-red-300' : 'bg-red-100 text-red-700',
  };
  const recoBadgeDefault = isDark ? 'bg-amber-900/40 text-amber-300' : 'bg-amber-100 text-amber-700';

  const timeLimitBg = (days) => {
    if (!days) return isDark ? 'bg-zinc-700/50' : 'bg-gray-50';
    if (days <= 30) return isDark ? 'bg-red-900/15 border border-red-800/40' : 'bg-red-50 border border-red-100';
    if (days <= 90) return isDark ? 'bg-amber-900/15 border border-amber-800/40' : 'bg-amber-50 border border-amber-100';
    return isDark ? 'bg-zinc-700/50' : 'bg-gray-50';
  };
  const timeLimitTxt = (days) => {
    if (!days) return c.textMuteded;
    if (days <= 30) return isDark ? 'text-red-400' : 'text-red-600';
    if (days <= 90) return isDark ? 'text-amber-400' : 'text-amber-600';
    return c.textMuteded;
  };

  const evidencePriority = {
    critical:  isDark ? 'bg-red-900/40 text-red-300' : 'bg-red-100 text-red-600',
    important: isDark ? 'bg-amber-900/40 text-amber-300' : 'bg-amber-100 text-amber-600',
  };
  const evidencePriorityDefault = isDark ? 'bg-zinc-700 text-zinc-400' : 'bg-gray-100 text-gray-500';

  const outcomeBadge = {
    resolved: isDark ? 'bg-green-900/40 text-green-300' : 'bg-green-100 text-green-700',
    failed:   isDark ? 'bg-red-900/40 text-red-300' : 'bg-red-100 text-red-700',
  };

  const deadlineBorderBg = (info) => {
    if (info.isOverdue) return isDark ? 'border-red-700 bg-red-900/15' : 'border-red-200 bg-red-50';
    if (info.daysRemaining <= 3) return isDark ? 'border-amber-700 bg-amber-900/15' : 'border-amber-200 bg-amber-50';
    return isDark ? 'border-zinc-600 bg-zinc-700/30' : 'border-gray-200 bg-gray-50';
  };
  const deadlineTxt = (info) => {
    if (info.isOverdue) return isDark ? 'text-red-400' : 'text-red-600';
    if (info.daysRemaining <= 3) return isDark ? 'text-amber-400' : 'text-amber-600';
    return c.textMuteded;
  };

  // ─── Stage color map (tool-specific: 5 distinct stage colors) ───
  const stageColors = (color, type) => {
    const map = {
      blue:   { badge: isDark ? 'bg-sky-900/40 text-sky-300 border-sky-700' : 'bg-sky-100 text-sky-700 border-sky-200', bg: isDark ? 'bg-sky-900/15' : 'bg-sky-50', border: isDark ? 'border-sky-700' : 'border-sky-300', accent: isDark ? 'text-sky-400' : 'text-sky-600' },
      purple: { badge: isDark ? 'bg-cyan-900/40 text-cyan-300 border-cyan-700' : 'bg-cyan-100 text-cyan-700 border-cyan-200', bg: isDark ? 'bg-cyan-900/15' : 'bg-cyan-50', border: isDark ? 'border-cyan-700' : 'border-cyan-300', accent: isDark ? 'text-cyan-400' : 'text-cyan-600' },
      orange: { badge: isDark ? 'bg-amber-900/40 text-amber-300 border-amber-700' : 'bg-amber-100 text-amber-700 border-amber-200', bg: isDark ? 'bg-amber-900/15' : 'bg-amber-50', border: isDark ? 'border-amber-700' : 'border-amber-300', accent: isDark ? 'text-amber-400' : 'text-amber-600' },
      pink:   { badge: isDark ? 'bg-red-900/40 text-red-300 border-red-700' : 'bg-red-100 text-red-700 border-red-200', bg: isDark ? 'bg-red-900/15' : 'bg-red-50', border: isDark ? 'border-red-700' : 'border-red-300', accent: isDark ? 'text-red-400' : 'text-red-600' },
      red:    { badge: isDark ? 'bg-red-900/40 text-red-300 border-red-700' : 'bg-red-100 text-red-700 border-red-200', bg: isDark ? 'bg-red-900/15' : 'bg-red-50', border: isDark ? 'border-red-700' : 'border-red-300', accent: isDark ? 'text-red-400' : 'text-red-600' },
    };
    return map[color]?.[type] || '';
  };

  const severityConfig = {
    low:      { label: t('cew_sev_low'),      colorKey: 'sevLowColor',  bgKey: 'sevLowBg',  borderKey: 'sevLowBorder' },
    medium:   { label: t('cew_sev_medium'),   colorKey: 'sevMedColor',  bgKey: 'sevMedBg',  borderKey: 'sevMedBorder' },
    high:     { label: t('cew_sev_high'),     colorKey: 'sevMedColor',  bgKey: 'sevMedBg',  borderKey: 'sevMedBorder' },
    critical: { label: t('cew_sev_critical'), colorKey: 'sevCritColor', bgKey: 'sevCritBg', borderKey: 'sevCritBorder' },
  };

  const stageConfig = [
    { num: 1, key: 'stage_1_direct',          label: t('cew_stage1_label'), icon: '📨', color: 'blue' },
    { num: 2, key: 'stage_2_regulatory',       label: t('cew_stage2_label'), icon: '🛡️', color: 'purple' },
    { num: 3, key: 'stage_3_executive',        label: t('cew_stage3_label'), icon: '🎯', color: 'orange' },
    { num: 4, key: 'stage_4_public',           label: t('cew_stage4_label'), icon: '📢', color: 'pink' },
    { num: 5, key: 'stage_5_financial_legal',  label: t('cew_stage5_label'), icon: '⚖️', color: 'red' },
  ];

  const industries = [
    { id: 'auto',        label: t('cew_ind_auto') },        { id: 'airline',      label: t('cew_ind_airline') },
    { id: 'telecom',     label: t('cew_ind_telecom') },     { id: 'banking',      label: t('cew_ind_banking') },
    { id: 'insurance',   label: t('cew_ind_insurance') },   { id: 'retail',       label: t('cew_ind_retail') },
    { id: 'utility',     label: t('cew_ind_utility') },     { id: 'healthcare',   label: t('cew_ind_healthcare') },
    { id: 'auto_dealer', label: t('cew_ind_auto_dealer') }, { id: 'subscription', label: t('cew_ind_subscription') },
    { id: 'contractor',  label: t('cew_ind_contractor') },  { id: 'other',        label: t('cew_ind_other') },
  ];

  const tones = [
    { id: 'firm',       label: t('cew_tone_firm_label'),       desc: t('cew_tone_firm_desc') },
    { id: 'aggressive', label: t('cew_tone_aggressive_label'), desc: t('cew_tone_aggressive_desc') },
    { id: 'empathetic', label: t('cew_tone_empathetic_label'), desc: t('cew_tone_empathetic_desc') },
  ];

  // ─── Persisted inputs ───
  const [resultsMap,        setResultsMap]        = useState({});

  // ─── Session state ───
  const [error,              setError]              = useState('');
  const [activeStage,        setActiveStage]        = useState(1);
  const [expandedSections,   setExpandedSections]   = useState({});
  const [responseText,       setResponseText]       = useState('');
  const [responseAnalysis,   setResponseAnalysis]   = useState(null);
  const [responseLoading,    setResponseLoading]    = useState(false);
  const [showResponseInput,  setShowResponseInput]  = useState(null);
  const [editingLetter,      setEditingLetter]      = useState(null);
  const [editedLetters,      setEditedLetters]      = useState({});
  const [regeneratedStages,  setRegeneratedStages]  = useState({});
  const [regenerating,       setRegenerating]       = useState(null);
  const [showCallScript,     setShowCallScript]     = useState(false);
  const [showHistory,        setShowHistory]        = useState(false);
  const [activeComplaintId,  setActiveComplaintId]  = useState(null);
  const [company,          setCompany]          = usePersistentState('cew-company', '');
  const [industry,         setIndustry]         = usePersistentState('cew-industry', 'auto');
  const [issue,            setIssue]            = usePersistentState('cew-issue', '');
  const [previousAttempts, setPreviousAttempts] = usePersistentState('cew-prev-attempts', '');
  const [, setAnalysisLog] = usePersistentState('complaintescalationwriter-history', []);
  const [desiredOutcome,   setDesiredOutcome]   = usePersistentState('cew-outcome', '');
  const [amountAtStake,    setAmountAtStake]    = usePersistentState('cew-amount', '');
  const [hasDocumentation, setHasDocumentation] = usePersistentState('cew-docs', '');
  const [tone,             setTone]             = usePersistentState('cew-tone', 'firm');
  const [results,          setResults]          = usePersistentState('cew-results', null);

  // ─── Campaign tracking (persisted) ───
  const [campaignHistory,   setCampaignHistory]   = usePersistentState('cew-campaign', {});
  const [complaintHistory,  setComplaintHistory]  = usePersistentState('cew-history', []);
  const [stageProgress,     setStageProgress]     = usePersistentState('cew-progress', {});
  const [checkedEvidence,   setCheckedEvidence]   = usePersistentState('cew-evidence', {});
  const [hasVisited,        setHasVisited]        = usePersistentState('cew-visited', false);
  const [dismissedHints,    setDismissedHints]    = usePersistentState('cew-hints', {});

  // ─── Helpers ───
  const toggleSection = (key) => setExpandedSections(prev => ({ ...prev, [key]: !prev[key] }));

  const resultsRef = useRef(null);

  const submitRef    = useRef(null);
  const canSubmitRef = useRef(false);

  // ── Document-level Ctrl+Enter submit ──
  useEffect(() => {
    const handler = (e) => {
      const tag = e.target?.tagName;
      if (tag === 'SELECT') return;
      if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') {
        if (canSubmitRef.current) { e.preventDefault(); submitRef.current?.(); }
      }
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, []);

  // ─── Hint render function (not a component — avoids new-type-every-render issue) ───
  const renderHint = (id, children) => {
    if (dismissedHints[id]) return null;
    return (
      <div className={`flex items-start gap-2 px-3 py-2 mt-2 rounded-lg text-xs ${c.hintStyle}`}>
        <span className="flex-shrink-0 mt-0.5">💡</span>
        <span className="flex-1">{children}</span>
        <button onClick={() => setDismissedHints(prev => ({ ...prev, [id]: true }))} className="flex-shrink-0 opacity-50 hover:opacity-100 ml-1">✕</button>
      </div>
    );
  };

  // ─── Stage progress ───
  const getStageStatus = (stageNum) => {
    if (!activeComplaintId) return null;
    return stageProgress[activeComplaintId]?.[stageNum] || null;
  };

  const markStageSent = (stageNum) => {
    if (!activeComplaintId) return;
    setStageProgress(prev => ({ ...prev, [activeComplaintId]: { ...(prev[activeComplaintId] || {}), [stageNum]: { sent: new Date().toISOString(), outcome: 'pending' } } }));
    addCampaignEntry(stageNum, { sentDate: new Date().toISOString() });
  };

  const markStageOutcome = (stageNum, outcome) => {
    if (!activeComplaintId) return;
    setStageProgress(prev => ({ ...prev, [activeComplaintId]: { ...(prev[activeComplaintId] || {}), [stageNum]: { ...(prev[activeComplaintId]?.[stageNum] || {}), outcome } } }));
    updateCampaignEntry(stageNum, { outcome });
  };

  // ─── Campaign sessionHistory ───
  const addCampaignEntry = (stageNum, data) => {
    if (!activeComplaintId) return;
    setCampaignHistory(prev => {
      const existing = prev[activeComplaintId] || [];
      const idx = existing.findIndex(e => e.stage === stageNum);
      if (idx >= 0) { const u = [...existing]; u[idx] = { ...u[idx], ...data }; return { ...prev, [activeComplaintId]: u }; }
      return { ...prev, [activeComplaintId]: [...existing, { stage: stageNum, ...data }] };
    });
  };

  const updateCampaignEntry = (stageNum, data) => {
    if (!activeComplaintId) return;
    setCampaignHistory(prev => {
      const existing = prev[activeComplaintId] || [];
      const idx = existing.findIndex(e => e.stage === stageNum);
      if (idx >= 0) { const u = [...existing]; u[idx] = { ...u[idx], ...data }; return { ...prev, [activeComplaintId]: u }; }
      return { ...prev, [activeComplaintId]: [...existing, { stage: stageNum, ...data }] };
    });
  };

  const getCampaignEntries = () => {
    if (!activeComplaintId) return [];
    return campaignHistory[activeComplaintId] || [];
  };

  const toggleEvidence = (idx) => {
    const key = activeComplaintId || 'temp';
    setCheckedEvidence(prev => ({ ...prev, [key]: { ...(prev[key] || {}), [idx]: !prev[key]?.[idx] } }));
  };

  const isEvidenceChecked = (idx) => {
    const key = activeComplaintId || 'temp';
    return !!checkedEvidence[key]?.[idx];
  };

  // ─── Deadline info ───
  const getDeadlineInfo = (stageNum) => {
    if (!activeComplaintId) return null;
    const status = stageProgress[activeComplaintId]?.[stageNum];
    if (!status?.sent) return null;
    const sentDate = new Date(status.sent);
    const deadlineDays = stageNum === 1 ? 14 : stageNum === 2 ? 21 : stageNum === 3 ? 10 : 7;
    const deadline = new Date(sentDate);
    deadline.setDate(deadline.getDate() + deadlineDays);
    const now = new Date();
    const daysRemaining = Math.ceil((deadline - now) / (1000 * 60 * 60 * 24));
    return {
      sentDate: sentDate.toLocaleDateString(userLocale || undefined, { month: 'short', day: 'numeric', year: 'numeric' }),
      deadlineDate: deadline.toLocaleDateString(userLocale || undefined, { month: 'short', day: 'numeric', year: 'numeric' }),
      daysRemaining, isOverdue: daysRemaining < 0, deadlineDays,
    };
  };

  const progressBarFill = (n) => {
    const st = getStageStatus(n);
    if (st?.outcome === 'resolved') return 'bg-green-500';
    if (st?.outcome === 'failed')   return 'bg-red-500';
    if (st)                          return 'bg-amber-500';
    return isDark ? 'bg-zinc-600' : 'bg-gray-200';
  };

  // ─── StageActionBar render function (not a component — avoids new-type-every-render issue) ───
  const renderStageActionBar = (stageNum, sentLabel, nextStage) => {
    const status = getStageStatus(stageNum);
    const deadlineInfo = getDeadlineInfo(stageNum);

    if (!status) {
      return (
        <div className={`p-4 rounded-xl border ${c.border} ${c.cardAlt}`}>
          <div className="flex items-center justify-between">
            <div>
              <p className={`text-sm font-bold ${c.text}`}>{t('cew_ready_to_send')}</p>
              <p className={`text-xs ${c.textMuteded}`}>{t('cew_ready_desc')}</p>
            </div>
            <button onClick={() => markStageSent(stageNum)} className={`px-4 py-2 rounded-lg text-sm font-bold ${c.btnPrimary}`}>
              ✅ {sentLabel || t('cew_mark_sent')}
            </button>
          </div>
        </div>
      );
    }

    if (status.outcome === 'pending') {
      return (
        <div className="space-y-3">
          {deadlineInfo && (
            <div className={`p-3 rounded-xl border ${deadlineBorderBg(deadlineInfo)}`}>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span>{deadlineInfo.isOverdue ? '🚨' : deadlineInfo.daysRemaining <= 3 ? '⏰' : '📅'}</span>
                  <div>
                    <p className={`text-xs font-bold ${c.text}`}>{t('cew_sent_deadline', { sent: deadlineInfo.sentDate, deadline: deadlineInfo.deadlineDate })}</p>
                    <p className={`text-xs ${deadlineTxt(deadlineInfo)}`}>
                      {deadlineInfo.isOverdue
                        ? t('cew_overdue', { n: Math.abs(deadlineInfo.daysRemaining) })
                        : (deadlineInfo.daysRemaining === 1 ? t('cew_day_remaining', { n: deadlineInfo.daysRemaining }) : t('cew_days_remaining', { n: deadlineInfo.daysRemaining }))}
                    </p>
                  </div>
                </div>
                <div className={`w-24 h-1.5 rounded-full ${c.progressTrack}`}>
                  <div
                    className={`h-full rounded-full transition-all ${deadlineInfo.isOverdue ? 'bg-red-500' : deadlineInfo.daysRemaining <= 3 ? 'bg-amber-500' : 'bg-green-500'}`}
                    style={{ width: `${Math.min(100, Math.max(0, ((deadlineInfo.deadlineDays - deadlineInfo.daysRemaining) / deadlineInfo.deadlineDays) * 100))}%` }}
                  />
                </div>
              </div>
            </div>
          )}

          <div className={`p-4 rounded-xl border ${c.border} ${c.cardAlt}`}>
            <p className={`text-xs ${c.textMuteded} mb-3`}>{t('cew_did_respond')}</p>
            <div className="flex flex-wrap gap-2">
              <button onClick={() => markStageOutcome(stageNum, 'resolved')} className={`px-3 py-1.5 rounded-lg text-xs font-bold border ${c.resolvedBtn}`}>✅ {t('cew_btn_resolved')}</button>
              <button onClick={() => setShowResponseInput(stageNum)} className={`px-3 py-1.5 rounded-lg text-xs font-bold border ${c.analyzeBtn}`}>📨 {t('cew_btn_analyze_resp')}</button>
              {nextStage && (
                <button onClick={() => handleContextEscalate(stageNum, nextStage)} className={`px-3 py-1.5 rounded-lg text-xs font-bold border ${c.escalateBtn}`}>❌ {t('cew_btn_no_response', { n: nextStage })}</button>
              )}
              {!nextStage && (
                <button onClick={() => markStageOutcome(stageNum, 'failed')} className={`px-3 py-1.5 rounded-lg text-xs font-bold border ${c.escalateBtn}`}>❌ {t('cew_btn_not_resolved')}</button>
              )}
            </div>
          </div>

          {showResponseInput === stageNum && (
            <div className={`p-4 rounded-xl border ${c.highlight}`}>
              <p className={`text-sm font-bold ${c.text} mb-2`}>📨 {t('cew_paste_response')}</p>
              <textarea
                value={responseText}
                onChange={e => setResponseText(e.target.value)}
                placeholder={t('cew_ph_paste')}
                rows={5}
                className={`w-full p-3 border rounded-xl text-sm resize-y outline-none focus:ring-2 ${c.input}`}
              />
              <div className="flex items-center gap-2 mt-2">
                <button
                  onClick={() => handleAnalyzeResponse(stageNum)}
                  disabled={responseLoading || !responseText.trim()}
                  className={`px-4 py-2 rounded-lg text-sm font-bold disabled:opacity-40 ${c.btnPrimary}`}
                >
                  {responseLoading ? <><span className="animate-spin inline-block">{tool?.icon ?? '📧'}</span> {t('cew_analyzing')}</> : <><span>🔍</span> {t('cew_analyze_response')}</>}
                </button>
                <button onClick={() => { setShowResponseInput(null); setResponseText(''); setResponseAnalysis(null); }} className={`text-xs font-bold ${c.textMuteded}`}>{t('cew_cancel')}</button>
              </div>

              {responseAnalysis && (
                <div className="space-y-3 mt-4">
                  <div className={`p-3 rounded-xl border ${recoBg[responseAnalysis.recommendation] || recoDefault}`}>
                    <div className="flex items-center gap-2 mb-2">
                      <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${recoBadge[responseAnalysis.recommendation] || recoBadgeDefault}`}>
                        {responseAnalysis.recommendation === 'accept' ? <>✅ {t('cew_reco_accept')}</> : responseAnalysis.recommendation === 'counter' ? <>🤝 {t('cew_reco_counter')}</> : responseAnalysis.recommendation === 'escalate' ? <>⬆️ {t('cew_reco_escalate')}</> : <><span className="inline-block animate-spin">{tool?.icon ?? '📧'}</span> {t('cew_reco_wait')}</>}
                      </span>
                      <span className={`text-xs ${c.textMuteded}`}>{responseAnalysis.response_type_label}</span>
                    </div>
                    <p className={`text-sm leading-relaxed ${c.text}`}>{responseAnalysis.assessment}</p>
                  {responseAnalysis.is_genuine !== undefined && (
                    <p className={`text-xs font-semibold mt-1 ${responseAnalysis.is_genuine ? (isDark ? 'text-emerald-400' : 'text-emerald-600') : (isDark ? 'text-red-400' : 'text-red-600')}`}>
                      {responseAnalysis.is_genuine ? `✓ ${t('cew_appears_genuine')}` : `⚠️ ${t('cew_likely_deflection')}`}
                    </p>
                  )}
                  {responseAnalysis.genuineness_explanation && (
                    <p className={`text-xs ${c.textMuteded} mt-0.5`}>{responseAnalysis.genuineness_explanation}</p>
                  )}
                  </div>

                  <p className={`text-sm leading-relaxed ${c.textSecondary}`}>{responseAnalysis.recommendation_explanation}</p>

                  {responseAnalysis.tactics_used?.length > 0 && (
                    <div>
                      <p className={`text-xs font-bold ${c.textMuteded} mb-1.5`}>🎭 {t('cew_tactics_identified')}</p>
                      <div className="flex flex-wrap gap-1.5">
                        {responseAnalysis.tactics_used.map((tactic, i) => (
                          <span key={i} className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${c.tacticsTag}`}>{tactic}</span>
                        ))}
                      </div>
                    </div>
                  )}

                  {responseAnalysis.offer_analysis?.what_they_offered && (
                    <div className={`p-3 rounded-lg ${c.cardAlt}`}>
                      <p className={`text-xs font-bold ${c.textMuteded} mb-2`}>💰 {t('cew_offer_analysis')}</p>
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
                        <div><span className={c.textMuteded}>{t('cew_offered')} </span><span className={`font-bold ${c.text}`}>{responseAnalysis.offer_analysis.what_they_offered}</span></div>
                        <div><span className={c.textMuteded}>{t('cew_you_asked')} </span><span className={`font-bold ${c.text}`}>{responseAnalysis.offer_analysis.what_you_asked_for}</span></div>
                        {responseAnalysis.offer_analysis.gap && <div className="col-span-2"><span className={c.textMuteded}>{t('cew_gap')} </span><span className={`font-bold ${c.issueTip}`}>{responseAnalysis.offer_analysis.gap}</span></div>}
                        {responseAnalysis.offer_analysis.fair_market_value && <div className="col-span-2"><span className={c.textMuteded}>{t('cew_fair_value')} </span><span className={c.textSecondary}>{responseAnalysis.offer_analysis.fair_market_value}</span></div>}
                      </div>
                    </div>
                  )}

                  {responseAnalysis.if_counter?.counter_offer_text && responseAnalysis.recommendation === 'counter' && (
                    <div className={`p-3 rounded-xl border ${c.counterBox}`}>
                      <div className="flex items-center justify-between mb-2">
                        <p className={`text-xs font-bold ${c.counterBoxHd}`}>🤝 {t('cew_suggested_counter')}</p>
                      </div>
                      <div className={`whitespace-pre-wrap text-xs ${c.textSecondary} leading-relaxed`}>{responseAnalysis.if_counter.counter_offer_text}</div>
                      {responseAnalysis.if_counter.target_amount_or_resolution && (
                        <p className={`text-xs ${c.textMuteded} mt-2`}>{t('cew_target')} {responseAnalysis.if_counter.target_amount_or_resolution}</p>
                      )}
                      {responseAnalysis.if_counter.leverage_to_mention && (
                        <p className={`text-xs ${c.textMuteded} mt-0.5`}>{t('cew_leverage')} {responseAnalysis.if_counter.leverage_to_mention}</p>
                      )}
                    </div>
                  )}

                  {responseAnalysis.if_accept && responseAnalysis.recommendation === 'accept' && (
                    <div className={`p-3 rounded-lg ${c.cardAlt} border ${c.border}`}>
                      <p className={`text-xs font-bold ${c.textMuteded} mb-1`}>✅ {t('cew_before_accepting')}</p>
                      <p className={`text-xs ${c.textSecondary}`}>{responseAnalysis.if_accept}</p>
                    </div>
                  )}

                  {responseAnalysis.if_escalate?.what_to_reference && responseAnalysis.recommendation === 'escalate' && (
                    <div className={`p-3 rounded-lg ${c.redFlagsBox}`}>
                      <p className="text-xs font-bold mb-1">⬆️ {t('cew_use_next_escalation')}</p>
                      <p className={`text-xs ${c.textSecondary}`}>{responseAnalysis.if_escalate.what_to_reference}</p>
                    </div>
                  )}

                  {responseAnalysis.red_flags?.length > 0 && (
                    <div className={`p-3 rounded-lg ${c.redFlagsBox}`}>
                      <p className="text-xs font-bold mb-1">🚩 {t('cew_red_flags')}</p>
                      {responseAnalysis.red_flags.map((f, i) => <p key={i} className={`text-xs ${c.textSecondary}`}>• {f}</p>)}
                    </div>
                  )}

                  {responseAnalysis.things_to_get_in_writing?.length > 0 && (
                    <div className={`p-3 rounded-lg ${c.cardAlt}`}>
                      <p className={`text-xs font-bold ${c.textMuteded} mb-1`}>📝 {t('cew_get_in_writing')}</p>
                      {responseAnalysis.things_to_get_in_writing.map((item, i) => <p key={i} className={`text-xs ${c.textSecondary}`}>• {item}</p>)}
                    </div>
                  )}

                  <div className="flex flex-wrap gap-2 pt-2">
                    {responseAnalysis.recommendation === 'accept' && (
                      <button onClick={() => markStageOutcome(stageNum, 'resolved')} className={`px-3 py-1.5 rounded-lg text-xs font-bold border ${c.resolvedBtn}`}>✅ {t('cew_accept_resolved')}</button>
                    )}
                    {responseAnalysis.recommendation === 'escalate' && nextStage && (
                      <button onClick={() => handleContextEscalate(stageNum, nextStage)} className={`px-3 py-1.5 rounded-lg text-xs font-bold border ${c.escalateBtn}`}>⬆️ {t('cew_escalate_to', { n: nextStage })}</button>
                    )}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      );
    }

    return (
      <div className={`p-4 rounded-xl border ${c.border} ${c.cardAlt}`}>
        <p className={`text-sm font-bold ${status.outcome === 'resolved' ? c.resolvedText : c.failedText}`}>
          {status.outcome === 'resolved' ? `✅ ${t('cew_resolved_complete')}` : `❌ ${nextStage ? t('cew_not_resolved_see', { n: nextStage }) : t('cew_not_resolved')}`}
        </p>
      </div>
    );
  };

  // ─── Main handlers ───
  const handleSubmit = async () => {
    if (!company.trim() || !issue.trim()) { setError(t('cew_err_company_issue')); return; }
    setError('');
    setResults(null);
    try {
      const data = await callToolEndpoint('complaint-escalation-writer', {
        company: company.trim(), industry: industry === 'auto' ? null : industry, issue: issue.trim(),
        previousAttempts: previousAttempts.trim() || null, desiredOutcome: desiredOutcome.trim() || null,
        amountAtStake: amountAtStake.trim() || null, hasDocumentation: hasDocumentation.trim() || null, tone,
        userLocale, userCurrency, userRegion,
      });
      setResults(data);
      setAnalysisLog(prev => [{ id: Date.now(), date: new Date().toISOString(), preview: '' }, ...prev].slice(0, 6));
      setActiveStage(1);
      const id = Date.now().toString();
      setActiveComplaintId(id);
      const newEntry = {
        id, company: company.trim(), industry, tone,
        issue: issue.trim(),
        previousAttempts: previousAttempts.trim().slice(0, 300) || null,
        desiredOutcome: desiredOutcome.trim().slice(0, 300) || null,
        amountAtStake: amountAtStake.trim() || null,
        hasDocumentation: hasDocumentation.trim().slice(0, 300) || null,
        severity: data.situation_assessment?.severity || 'medium',
        date: new Date().toISOString(),
      };
      setComplaintHistory(prev => {
        const updated = [newEntry, ...prev].slice(0, 6);
        // Clean up resultsMap for IDs no longer in sessionHistory
        const keepIds = new Set(updated.map(e => e.id));
        setResultsMap(prev => Object.fromEntries(Object.entries(prev).filter(([k]) => keepIds.has(k))));
        return updated;
      });
      setResultsMap(prev => ({ ...prev, [id]: data }));
    } catch (err) {
      setError(err.message || t('cew_err_build'));
    }
  };

  const reset = () => {
    setResults(null); setError(''); setActiveStage(1); setExpandedSections({});
    setActiveComplaintId(null); setResponseText(''); setResponseAnalysis(null);
    setShowResponseInput(null); setEditingLetter(null); setEditedLetters({});
    setRegeneratedStages({}); setRegenerating(null); setShowCallScript(false);
  };

  const loadExample = useCallback(() => {
    setCompany(EXAMPLE.company);
    setIndustry(EXAMPLE.industry);
    setIssue(EXAMPLE.issue);
    setPreviousAttempts(EXAMPLE.previousAttempts);
    setResultsMap({});
  }, [setCompany, setIndustry, setIssue, setPreviousAttempts, setResultsMap]);

  const handleAnalyzeResponse = async (stageNum) => {
    if (!responseText.trim()) { setError(t('cew_err_paste_first')); return; }
    setResponseLoading(true); setError(''); setResponseAnalysis(null);
    try {
      const data = await callToolEndpoint('complaint-escalation-writer/analyze-response', {
        company: company.trim(), originalIssue: issue.trim(), stage: stageNum,
        companyResponse: responseText.trim(), desiredOutcome: desiredOutcome.trim() || null,
        userLocale, userCurrency, userRegion,
      });
      setResponseAnalysis(data);
      updateCampaignEntry(stageNum, { companyResponse: responseText.trim(), analysisResult: data });
    } catch (err) {
      setError(err.message || t('cew_err_analyze'));
    } finally {
      setResponseLoading(false);
    }
  };

  const handleContextEscalate = async (fromStage, toStage) => {
    markStageOutcome(fromStage, 'failed');
    setShowResponseInput(null);
    setActiveStage(toStage);
    const entries = getCampaignEntries();
    const hasContext = entries.some(e => e.companyResponse || e.analysisResult);
    if (hasContext && toStage >= 2 && toStage <= 5) {
      setRegenerating(toStage);
      try {
        const stageKey = `stage_${toStage}_${toStage === 2 ? 'regulatory' : toStage === 3 ? 'executive' : toStage === 4 ? 'public' : 'financial_legal'}`;
        const data = await callToolEndpoint('complaint-escalation-writer/regenerate-stage', {
          company: company.trim(), issue: issue.trim(), industry: industry === 'auto' ? null : industry,
          desiredOutcome: desiredOutcome.trim() || null, amountAtStake: amountAtStake.trim() || null,
          tone, targetStage: toStage, campaignHistory: entries,
          userLocale, userCurrency, userRegion,
        });
        setRegeneratedStages(prev => ({ ...prev, [stageKey]: data }));
        setEditedLetters(prev => { const next = { ...prev }; delete next[stageKey]; return next; });
      } catch (err) {
        console.error('Stage regeneration failed, using original:', err);
      } finally {
        setRegenerating(null);
      }
    }
    setResponseAnalysis(null);
    setResponseText('');
  };

  const getStageData = (stageKey, original) => regeneratedStages[stageKey] || original;
  const getLetterText = (stageKey, originalText) => editedLetters[stageKey] ?? originalText;

  const startEditingLetter = (stageKey, originalText) => {
    if (!editedLetters[stageKey]) setEditedLetters(prev => ({ ...prev, [stageKey]: originalText }));
    setEditingLetter(stageKey);
  };
  const cancelEditingLetter = (stageKey, originalText) => {
    setEditedLetters(prev => ({ ...prev, [stageKey]: originalText }));
    setEditingLetter(null);
  };

  // ─── Restore a past complaint ───
  const restoreComplaint = (h) => {
    setCompany(h.company || '');
    setIssue(h.issue || '');
    if (h.industry) setIndustry(h.industry);
    if (h.tone) setTone(h.tone);
    if (h.previousAttempts != null) setPreviousAttempts(h.previousAttempts);
    if (h.desiredOutcome != null) setDesiredOutcome(h.desiredOutcome);
    if (h.amountAtStake != null) setAmountAtStake(h.amountAtStake);
    if (h.hasDocumentation != null) setHasDocumentation(h.hasDocumentation);
    setActiveComplaintId(h.id);
    const savedResults = resultsMap[h.id] || null;
    setResults(savedResults);
    setError('');
    setActiveStage(1);
    setExpandedSections({});
    setEditedLetters({});
    setRegeneratedStages({});
    setResponseText('');
    setResponseAnalysis(null);
    setShowResponseInput(null);
    setShowHistory(false);
  };

  // ─── Build full copy text ───
  const buildFullText = useCallback(() => {
    if (!results) return '';
    const toneLabel = { firm: t('cew_tone_firm_short'), aggressive: t('cew_tone_aggressive_short'), empathetic: t('cew_tone_empathetic_short') }[tone] || tone;
    const lines = [t('cew_copy_title'), `${t('cew_copy_company')} ${company}`, `${t('cew_copy_tone')} ${toneLabel}`, ''];
    const sa = results?.situation_assessment;
    if (sa) lines.push(`${t('cew_copy_severity')} ${sa.severity}`, `${t('cew_copy_legal_strength')} ${sa.legal_strength}`, sa.key_insight, '');
    const s1 = results?.escalation_stages?.stage_1_direct;
    if (s1) lines.push(`═══ ${t('cew_copy_s1')} ═══`, `${t('cew_copy_subject')} ${s1.subject_line}`, '', getLetterText('stage_1_direct', s1.letter_body), '');
    const s2 = results?.escalation_stages?.stage_2_regulatory;
    if (s2) lines.push(`═══ ${t('cew_copy_s2')} ═══`, `${t('cew_copy_agency')} ${s2.agency}`, `${t('cew_copy_url')} ${s2.agency_url}`, '', getLetterText('stage_2_regulatory', s2.complaint_text), '');
    const s3 = results?.escalation_stages?.stage_3_executive;
    if (s3) lines.push(`═══ ${t('cew_copy_s3')} ═══`, `${t('cew_copy_subject')} ${s3.subject_line}`, '', getLetterText('stage_3_executive', s3.letter_body), '');
    const s4 = results?.escalation_stages?.stage_4_public;
    if (s4) lines.push(`═══ ${t('cew_copy_s4')} ═══`, s4.social_media_post, '', s4.social_media_long, '');
    if (results?.evidence_checklist?.length > 0) {
      lines.push(`═══ ${t('cew_copy_evidence')} ═══`);
      results?.evidence_checklist?.forEach((item, i) => lines.push(`${isEvidenceChecked(i) ? '✅' : '☐'} [${item.priority}] ${item.item} — ${item.how}`));
      lines.push('');
    }
    if (results?.timeline) {
      lines.push(`═══ ${t('cew_copy_timeline')} ═══`);
      Object.entries(results?.timeline).forEach(([key, value]) => lines.push(`${key.replace(/_/g, ' ')}: ${value}`));
      lines.push('');
    }
    lines.push('───', t('cew_copy_disclaimer'));
    return lines.join('\n') + BRAND;
  }, [results, editedLetters, company, tone, t]); // eslint-disable-line react-hooks/exhaustive-deps

  // ─── Keyboard refs (assigned on every render, after all handlers are declared) ───
  submitRef.current    = handleSubmit;
  canSubmitRef.current = !loading && !!company.trim() && !!issue.trim();

  useRegisterActions(buildFullText, tool?.title ?? t('cew_title'));

  // ─── Scroll to results ───
  useEffect(() => {
    if (!results) return;
    const t = setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 100);
    return () => clearTimeout(t);
  }, [results]);

  const hasResults = !!results;
  return (
    <div className={`space-y-4 ${c.text}`}>

      {/* ── INPUT CARD ── */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5`}>
        {/* Standard header */}
        <div className="mb-4 pb-3 border-b border-zinc-500">
          <div className="flex items-center justify-between">
            <div>
              <h2 className={`text-xl font-bold ${c.text} flex items-center gap-2`}>
                <span className="mr-2">{tool?.icon ?? '📧'}</span>{tool?.title ?? t('cew_title')}
              </h2>
              <p className={`text-sm ${c.textSecondary}`}>{tool?.tagline ?? t('cew_tagline')}</p>
              <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className={`mt-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium border disabled:opacity-40 ${isDark ? 'text-white border-white/40' : 'text-gray-800 border-transparent'}`}>{t('cew_try_example')}</button>
            </div>
            <div className="flex items-center gap-2">
              {hasResults && (
                <button onClick={reset} className={`${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs`}>↺ {t('start_over')}</button>
              )}
              {complaintHistory.length > 0 && (
                <button onClick={() => setShowHistory(!showHistory)} className={`${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs flex items-center gap-1`}>
                  <span>📁</span> {t('cew_history', { count: complaintHistory.length })}
                </button>
              )}
            </div>
          </div>
        </div>

        {/* ── HISTORY PANEL — inside card so it's visible regardless of scroll position ── */}
        {showHistory && complaintHistory.length > 0 && (
          <div className={`mb-4 rounded-xl border ${c.border} overflow-hidden`}>
            <div className={`px-4 py-2.5 border-b ${c.border} ${c.cardAlt} flex items-center justify-between`}>
              <span className={`text-xs font-bold ${c.text} uppercase tracking-wider`}>🕐 {t('cew_past_complaints')}</span>
              <button onClick={() => setShowHistory(false)} className={`text-xs ${c.textMuted} hover:${c.text}`}>✕ {t('cew_close')}</button>
            </div>
            <div className="divide-y divide-zinc-700/30 max-h-96 overflow-y-auto">
              {complaintHistory.map(h => {
                const sev = severityConfig[h.severity] || severityConfig.medium;
                const progress = stageProgress[h.id] || {};
                const stageNums = [1, 2, 3, 4, 5];
                const stageIcons = { pending: tool?.icon ?? '📧', resolved: '✅', failed: '❌' };
                const toneLabels = { firm: t('cew_tone_firm_short'), aggressive: t('cew_tone_aggressive_short'), empathetic: t('cew_tone_empathetic_short') };
                const isActive = h.id === activeComplaintId;
                return (
                  <div key={h.id} className={`p-4 ${isActive ? (isDark ? 'bg-cyan-900/10' : 'bg-cyan-50/60') : ''}`}>
                    {/* Row 1: company + date + severity */}
                    <div className="flex items-start justify-between gap-2 mb-1">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className={`text-sm font-bold ${c.text}`}>{h.company}</span>
                        {isActive && <span className={`text-[10px] font-bold px-1.5 py-0.5 rounded ${isDark ? 'bg-cyan-900/40 text-cyan-300' : 'bg-cyan-100 text-cyan-700'}`}>{t('cew_active')}</span>}
                      </div>
                      <span className={`flex-shrink-0 px-2 py-0.5 rounded-full text-[10px] font-bold ${c[sev.bgKey]} ${c[sev.colorKey]} border ${c[sev.borderKey]}`}>{sev.label}</span>
                    </div>
                    {/* Row 2: meta */}
                    <div className={`flex items-center gap-2 text-xs ${c.textMuted} mb-2 flex-wrap`}>
                      <span>{new Date(h.date).toLocaleDateString(userLocale || undefined, { month: 'short', day: 'numeric', year: 'numeric' })}</span>
                      {h.industry && h.industry !== 'auto' && <><span>·</span><span>{h.industry}</span></>}
                      {h.tone && <><span>·</span><span>{toneLabels[h.tone] || h.tone}</span></>}
                    </div>
                    {/* Issue — full text, no truncate */}
                    <p className={`text-xs ${c.textSecondary} mb-3 leading-relaxed`}>{isActive ? issue : h.issue}</p>
                    {/* Stage progress */}
                    {Object.keys(progress).length > 0 && (
                      <div className="flex items-center gap-1 mb-3">
                        {stageNums.map(n => {
                          const st = progress[n];
                          return (
                            <div key={n} title={t('cew_stage_label', { n, label: st ? st.outcome : t('cew_unknown') })}
                              className={`flex items-center justify-center w-7 h-7 rounded-full text-[11px] border ${
                                st?.outcome === 'resolved' ? (isDark ? 'bg-emerald-900/40 border-emerald-600 text-emerald-300' : 'bg-emerald-100 border-emerald-400 text-emerald-700') :
                                st?.outcome === 'failed'   ? (isDark ? 'bg-red-900/40 border-red-600 text-red-300' : 'bg-red-100 border-red-400 text-red-700') :
                                st?.outcome === 'pending'  ? (isDark ? 'bg-amber-900/40 border-amber-600 text-amber-300' : 'bg-amber-100 border-amber-400 text-amber-700') :
                                (isDark ? 'bg-zinc-700 border-zinc-600 text-zinc-500' : 'bg-gray-100 border-gray-300 text-gray-400')
                              }`}>
                              {st ? (stageIcons[st.outcome] || n) : n}
                            </div>
                          );
                        })}
                        <span className={`text-xs ${c.textMuted} ml-1`}>
                          {Object.values(progress).filter(s => s.outcome === 'resolved').length > 0 ? `✅ ${t('cew_resolved_short')}` :
                           Object.values(progress).filter(s => s.outcome === 'pending').length > 0 ? t('cew_in_progress') :
                           t('cew_stages_count', { done: Object.keys(progress).length })}
                        </span>
                      </div>
                    )}
                    {/* Restore button */}
                    <div className="flex items-center gap-3">
                      {!isActive && (
                        <button
                          onClick={() => restoreComplaint(h)}
                          className={`text-xs font-semibold px-3 py-1.5 rounded-lg ${c.btnPrimary}`}
                        >
                          ↩ {t('cew_resume_campaign')}
                        </button>
                      )}
                      {isActive && (
                        <span className={`text-xs font-semibold ${isDark ? 'text-cyan-400' : 'text-cyan-600'}`}>
                          ✓ {t('cew_currently_active')}
                        </span>
                      )}
                      {!resultsMap[h.id] && !isActive && (
                        <span className={`text-xs ${c.textMuted}`}>{t('cew_inputs_only')}</span>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Pre-result cross-ref */}
        <p className={`text-xs text-center ${c.textMuted} mb-4`}>
          {t('cew_xref_pre_q')} <a href="/PlainTalk" className={linkStyle}>🗣️ {t('cew_xref_plaintalk')}</a> {t('cew_xref_pre_tail')}
        </p>

        {/* First-visit welcome */}
        {!hasVisited && (
          <div className={`${c.cardAlt} rounded-xl p-5 mb-4`}>
            <h3 className={`text-base font-bold ${c.text} mb-2`}>{t('cew_welcome_title')}</h3>
            <p className={`text-sm ${c.textSecondary} mb-4`}>{t('cew_welcome_desc')}</p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 mb-4">
              {[
                { emoji: '📨', title: t('cew_feat1_title'), desc: t('cew_feat1_desc') },
                { emoji: '⚖️', title: t('cew_feat2_title'), desc: t('cew_feat2_desc') },
                { emoji: '📋', title: t('cew_feat3_title'), desc: t('cew_feat3_desc') },
                { emoji: '📊', title: t('cew_feat4_title'), desc: t('cew_feat4_desc') },
              ].map((f, i) => (
                <div key={i} className={`flex items-start gap-2 p-2.5 rounded-xl ${c.card}`}>
                  <span className="text-lg">{f.emoji}</span>
                  <div><p className={`text-sm font-bold ${c.text}`}>{f.title}</p><p className={`text-xs ${c.textMuteded}`}>{f.desc}</p></div>
                </div>
              ))}
            </div>
            <button onClick={() => setHasVisited(true)} className={`text-xs font-bold ${c.firstVisitLink}`}>{t('cew_welcome_cta')}</button>
          </div>
        )}

        <div className={`space-y-4 ${c.text}`}>
          {/* Company */}
          <div>
            <label className={`block font-semibold ${c.text} mb-2`}>{t('cew_label_company')} <span className={c.required}>*</span></label>
              <input type="text" value={company} onChange={e => setCompany(e.target.value)}
              placeholder={t('cew_ph_company')}
              className={`w-full p-3 border rounded-xl outline-none focus:ring-2 ${c.input}`} />
          </div>

          {/* Industry */}
          <div>
            <label className={`block font-semibold ${c.text} mb-2`}>{t('cew_label_industry')} <span className={`text-xs font-normal ${c.textMuteded}`}>{t('cew_industry_hint')}</span></label>
            <div className="flex flex-wrap gap-2">
              {industries.map(ind => (
                <button key={ind.id} onClick={() => setIndustry(ind.id)}
                  className={`px-3 py-1.5 rounded-lg border text-sm font-medium transition-all ${industry === ind.id ? c.industryActive : c.industryInactive}`}>
                  {ind.label}
                </button>
              ))}
            </div>
          </div>

          {/* Issue */}
          <div>
            <label className={`block font-semibold ${c.text} mb-2`}>{t('cew_label_issue')} <span className={c.required}>*</span></label>
              <textarea value={issue} onChange={e => setIssue(e.target.value)}
              placeholder={t('cew_ph_issue')}
              rows={6} className={`w-full p-4 border rounded-xl outline-none text-sm resize-y focus:ring-2 ${c.input}`} />
            {issue.length > 0 && issue.length < 100 && (
              <p className={`text-xs ${c.issueTip} mt-2`}>{t('cew_issue_tip')}</p>
            )}
            <p className={`text-xs ${c.textMuteded} mt-1`}>{t('cew_ctrl_enter')}</p>
          </div>

          {/* Tone */}
          <div>
            <label className={`block font-semibold ${c.text} mb-3`}>{t('cew_label_tone')}</label>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
              {tones.map(toneOpt => (
                <button key={toneOpt.id} onClick={() => setTone(toneOpt.id)}
                  className={`p-3 rounded-xl border text-left transition-all ${tone === toneOpt.id ? c.toneActive : c.toneInactive}`}>
                  <p className={`text-sm font-bold ${c.text}`}>{toneOpt.label}</p>
                  <p className={`text-xs ${c.textMuteded} mt-0.5`}>{toneOpt.desc}</p>
                </button>
              ))}
            </div>
            {renderHint('tone', t('cew_tone_hint'))}
          </div>

          {/* Details grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {[
              { label: t('cew_label_prev'), value: previousAttempts, setter: setPreviousAttempts, placeholder: t('cew_ph_prev') },
              { label: t('cew_label_outcome'),   value: desiredOutcome,   setter: setDesiredOutcome,   placeholder: t('cew_ph_outcome', { sym }) },
              { label: t('cew_label_amount'),   value: amountAtStake,    setter: setAmountAtStake,    placeholder: t('cew_ph_amount', { sym }) },
              { label: t('cew_label_docs'), value: hasDocumentation, setter: setHasDocumentation, placeholder: t('cew_ph_docs') },
            ].map(({ label, value, setter, placeholder }) => (
              <div key={label}>
                <label className={`block text-sm font-semibold ${c.text} mb-2`}>{label}</label>
                  <textarea value={value} onChange={e => setter(e.target.value)} rows={2}
                  placeholder={placeholder} className={`w-full p-3 border rounded-xl outline-none text-sm focus:ring-2 ${c.input}`} />
              </div>
            ))}
          </div>

          {error && (
            <div className={`p-4 rounded-xl flex items-start gap-3 border ${c.danger}`}>
              <span className="flex-shrink-0 mt-0.5">⚠️</span>
              <p className="text-sm">{error}</p>
            </div>
          )}

          <button onClick={handleSubmit} disabled={loading || !company.trim() || !issue.trim()}
          className={`w-full py-4 px-6 rounded-xl font-semibold text-lg flex items-center justify-center gap-2 min-h-[48px] shadow-lg disabled:opacity-40 disabled:cursor-not-allowed transition-all ${loading ? c.loadingSubmit : c.btnPrimary}`}>
          {loading
            ? <><span className="animate-spin inline-block">{tool?.icon ?? '📧'}</span> {t('cew_building')}</>
            : <><span>{tool?.icon ?? '📧'}</span> {t('cew_build_btn')}</>}
          </button>
        </div>
      </div>

      {/* ═══════════════════════════════════════════════════════════════
          RESULTS
          ═══════════════════════════════════════════════════════════════ */}
      {results && (
        <div ref={resultsRef} className="space-y-4">

          {/* Situation Assessment */}
          {results?.situation_assessment && (() => {
            const sev = severityConfig[results?.situation_assessment?.severity] || severityConfig.medium;
            return (
              <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-6 border-l-4 ${c[sev.borderKey]}`}>
                <div className="flex items-start justify-between flex-wrap gap-3 mb-3">
                  <span className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold ${c[sev.bgKey]} ${c[sev.colorKey]} border ${c[sev.borderKey]}`}>{sev.label}</span>
                  <div className="flex gap-3 text-sm">
                    {results?.situation_assessment?.legal_strength && <span className={c.textSecondary}>{t('cew_legal_position')} <strong className={c.text}>{results?.situation_assessment?.legal_strength}</strong></span>}
                    {results?.situation_assessment?.estimated_resolution_likelihood && <span className={c.textSecondary}>{t('cew_success_est')} <strong className={c.text}>{results?.situation_assessment?.estimated_resolution_likelihood}</strong></span>}
                  </div>
                </div>
                <p className={`font-semibold ${c.text} mb-2`}>{results?.situation_assessment?.key_insight}</p>
                {results?.situation_assessment?.company_reputation && <p className={`text-sm ${c.textSecondary}`}>{results?.situation_assessment?.company_reputation}</p>}
              </div>
            );
          })()}

          {/* Legal Leverage */}
          {results?.legal_leverage?.length > 0 && (
            <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-6`}>
              <button onClick={() => toggleSection('legal')} className={`w-full flex items-center justify-between ${c.text}`}>
                <h3 className="font-bold flex items-center gap-2"><span>⚖️</span> {t('cew_legal_leverage', { count: results?.legal_leverage?.length })}</h3>
                {expandedSections.legal ? <span>▲</span> : <span>▼</span>}
              </button>
              {expandedSections.legal && (
                <div className="space-y-3 mt-4">
                  {results?.legal_leverage?.map((law, idx) => (
                    <div key={idx} className={`p-4 rounded-lg border ${c.border}`}>
                      <div className="flex items-start justify-between gap-2 mb-1">
                        <p className={`font-bold ${c.text} text-sm`}>{law.law_or_regulation}</p>
                        <span className={`px-2 py-0.5 rounded-full text-xs font-bold ${legalStrengthBadge[law.strength] || legalStrengthDefault}`}>{law.strength}</span>
                      </div>
                      {law.what_it_protects && <p className={`text-xs font-semibold ${c.textSecondary} mb-1`}>{law.what_it_protects}</p>}
                      <p className={`text-sm ${c.textSecondary} mb-1`}>{law.how_it_applies}</p>
                      <p className={`text-xs ${c.textMuteded}`}>{t('cew_company_risk')} {law.consequence_for_company}</p>
                      {law.time_limit_days && (
                        <div className={`mt-2 flex items-center gap-2 px-2.5 py-1.5 rounded-lg ${timeLimitBg(law.time_limit_days)}`}>
                          <span className="text-xs">{law.time_limit_days <= 30 ? '🚨' : law.time_limit_days <= 90 ? '⏰' : '📅'}</span>
                          <span className={`text-xs font-bold ${timeLimitTxt(law.time_limit_days)}`}>
                            {t('cew_filing_window')} {law.time_limit_note || t('cew_days_approx', { days: law.time_limit_days })}
                          </span>
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* Evidence Checklist */}
          {results?.evidence_checklist?.length > 0 && (
            <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-6`}>
              <button onClick={() => toggleSection('evidence')} className={`w-full flex items-center justify-between ${c.text}`}>
                <h3 className="font-bold flex items-center gap-2">
                  <span>📋</span> {t('cew_evidence_checklist', { done: results?.evidence_checklist?.filter((_, i) => isEvidenceChecked(i)).length, total: results?.evidence_checklist?.length })}
                </h3>
                {expandedSections.evidence ? <span>▲</span> : <span>▼</span>}
              </button>
              {expandedSections.evidence && (
                <div className="space-y-2 mt-4">
                  {renderHint('evidence', t('cew_evidence_hint'))}
                  {results?.evidence_checklist?.map((item, idx) => (
                    <div key={idx} onClick={() => toggleEvidence(idx)}
                      className={`flex items-start gap-3 p-3 rounded-lg cursor-pointer transition-colors ${isEvidenceChecked(idx) ? c.evidenceChecked : c.cardAlt}`}>
                      <input type="checkbox" checked={isEvidenceChecked(idx)} readOnly className={`mt-1 w-4 h-4 rounded ${c.checkboxAccent}`} />
                      <div className="flex-1">
                        <div className="flex items-center gap-2">
                          <p className={`text-sm font-semibold ${isEvidenceChecked(idx) ? `${c.textMuteded} line-through` : c.text}`}>{item.item}</p>
                          <span className={`px-1.5 py-0.5 rounded text-[10px] font-bold uppercase ${evidencePriority[item.priority] || evidencePriorityDefault}`}>{item.priority}</span>
                        </div>
                        <p className={`text-xs ${c.textSecondary} mt-0.5`}>{item.how}</p>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* ── ESCALATION LADDER ── */}
          <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-6`}>
            <h3 className={`font-bold ${c.text} mb-4 flex items-center gap-2`}><span>⚡</span> {t('cew_escalation_ladder')}</h3>
            <p className={`text-sm ${c.textSecondary} mb-5`}>{t('cew_ladder_intro')}</p>

            {/* Stage Tabs */}
            <div className="flex gap-1 mb-6 overflow-x-auto pb-1">
              {stageConfig.map(stage => {
                const isActive = activeStage === stage.num;
                const sc = stageColors(stage.color, 'badge');
                const status = getStageStatus(stage.num);
                return (
                  <button key={stage.num} onClick={() => setActiveStage(stage.num)}
                    className={`flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm font-semibold whitespace-nowrap border transition-all relative ${isActive ? sc : c.stageTabInactive}`}>
                    <span>{stage.icon}</span>
                    <span className="hidden sm:inline">{stage.num}.</span> {stage.label}
                    {status && <span className={`w-2 h-2 rounded-full absolute -top-0.5 -right-0.5 ${status.outcome === 'resolved' ? 'bg-green-500' : status.outcome === 'failed' ? 'bg-red-500' : 'bg-amber-500'}`} />}
                  </button>
                );
              })}
            </div>

            {/* Campaign Progress */}
            {activeComplaintId && Object.keys(stageProgress[activeComplaintId] || {}).length > 0 && (
              <div className={`mb-5 p-3 rounded-lg ${c.cardAlt}`}>
                <span className={`text-xs font-bold ${c.textMuteded}`}>{t('cew_campaign_progress')}</span>
                <div className="flex gap-1 mt-2">
                  {[1, 2, 3, 4, 5].map(n => (
                    <div key={n} className={`flex-1 h-2 rounded-full ${progressBarFill(n)}`} />
                  ))}
                </div>
              </div>
            )}

            {/* Stage 1 */}
            {activeStage === 1 && results?.escalation_stages?.stage_1_direct && (() => {
              const s = results?.escalation_stages?.stage_1_direct;
              const stageKey = 'stage_1_direct';
              const letterText = getLetterText(stageKey, s.letter_body);
              const isEditing = editingLetter === stageKey;
              return (
                <div className={`space-y-4 ${c.text}`}>
                  <div className="flex items-center justify-between">
                    <h4 className={`font-bold ${c.text}`}>{t('cew_s1_heading')}</h4>
                    <div className="flex items-center gap-2">
                      {!isEditing && <button onClick={() => startEditingLetter(stageKey, s.letter_body)} className={`px-2.5 py-1 rounded-lg text-xs font-bold ${c.btnSecondary}`}>✏️ {t('cew_edit')}</button>}
                    </div>
                  </div>
                  <div className={`rounded-xl p-5 border ${c.letterBox}`}>
                    <p className={`text-xs font-bold ${c.textMuteded} mb-1`}>{t('cew_subject')}</p>
                    <p className={`font-semibold ${c.text} mb-4`}>{s.subject_line}</p>
                    {isEditing ? (
                      <div>
                        <textarea value={editedLetters[stageKey] || s.letter_body} onChange={e => setEditedLetters(prev => ({ ...prev, [stageKey]: e.target.value }))} rows={16} className={`w-full p-3 border rounded-xl text-sm resize-y outline-none focus:ring-2 leading-relaxed ${c.input}`} />
                        <div className="flex items-center gap-2 mt-2">
                          <button onClick={() => setEditingLetter(null)} className={`px-3 py-1.5 rounded-lg text-xs font-bold ${c.editDoneBtn}`}>✅ {t('cew_done_editing')}</button>
                          <button onClick={() => cancelEditingLetter(stageKey, s.letter_body)} className={`text-xs font-bold ${c.textMuteded}`}>{t('cew_reset_original')}</button>
                          {editedLetters[stageKey] !== s.letter_body && <span className={`text-[10px] ${c.issueTip}`}>✏️ {t('cew_modified')}</span>}
                        </div>
                      </div>
                    ) : (
                      <div className={`whitespace-pre-wrap text-sm ${c.textSecondary} leading-relaxed`}>{letterText}
                        {editedLetters[stageKey] && editedLetters[stageKey] !== s.letter_body && <p className={`text-[10px] mt-2 ${c.issueTip}`}>✏️ {t('cew_edited_letter')}</p>}
                      </div>
                    )}
                  </div>
                  {s.send_to?.length > 0 && (
                    <div className={`p-4 rounded-lg ${stageColors('blue', 'bg')}`}>
                      <p className={`text-xs font-bold ${stageColors('blue', 'accent')} mb-2`}>{t('cew_send_to')}</p>
                      {s.send_to.map((r, i) => (
                        <div key={i} className={`text-sm ${c.textSecondary} mb-2`}>
                          <span className={`font-semibold ${c.text}`}>{r.role}</span> — {r.how_to_find}
                          {r.email_pattern && <span className={`ml-1 ${c.textMuteded}`}>({r.email_pattern})</span>}
                        </div>
                      ))}
                    </div>
                  )}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    {s.send_via && <div className={`p-3 rounded-lg ${c.cardAlt}`}><p className={`text-xs font-bold ${c.textMuteded} mb-1`}>{t('cew_send_via')}</p><p className={`text-sm ${c.textSecondary}`}>{s.send_via}</p></div>}
                    {s.deadline_to_set && <div className={`p-3 rounded-lg ${c.cardAlt}`}><p className={`text-xs font-bold ${c.textMuteded} mb-1`}>{t('cew_response_deadline')}</p><p className={`text-sm ${c.textSecondary}`}>{s.deadline_to_set}</p></div>}
                  </div>
                  {s.leverage_points_used?.length > 0 && (
                    <div className="flex flex-wrap gap-2">
                      {s.leverage_points_used.map((lp, i) => <span key={i} className={`px-2.5 py-1 rounded-full text-xs font-medium ${stageColors('blue', 'badge')}`}>{lp}</span>)}
                    </div>
                  )}
                  {renderStageActionBar(1, t('cew_mark_sent'), 2)}
                </div>
              );
            })()}

            {/* Stage 2 */}
            {activeStage === 2 && results?.escalation_stages?.stage_2_regulatory && (() => {
              const s = getStageData('stage_2_regulatory', results?.escalation_stages?.stage_2_regulatory);
              const stageKey = 'stage_2_regulatory';
              const isRegenerated = !!regeneratedStages[stageKey];
              const complaintText = getLetterText(stageKey, s.complaint_text);
              const isEditing = editingLetter === stageKey;
              if (regenerating === 2) return (
                <div className={`p-8 text-center ${c.cardAlt} rounded-xl`}>
                  <p className="text-lg mb-2"><span className="animate-spin inline-block">{tool?.icon ?? '📧'}</span></p>
                  <p className={`text-sm font-bold ${c.text}`}>{t('cew_regen_s2')}</p>
                  <p className={`text-xs ${c.textMuteded} mt-1`}>{t('cew_regen_s2_desc')}</p>
                </div>
              );
              return (
                <div className={`space-y-4 ${c.text}`}>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <h4 className={`font-bold ${c.text}`}>{t('cew_s2_heading')}</h4>
                      {isRegenerated && <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${c.contextBadge}`}>🔄 {t('cew_context_aware')}</span>}
                    </div>
                    <div className="flex items-center gap-2">
                      {!isEditing && <button onClick={() => startEditingLetter(stageKey, s.complaint_text)} className={`px-2.5 py-1 rounded-lg text-xs font-bold ${c.btnSecondary}`}>✏️ {t('cew_edit')}</button>}
                    </div>
                  </div>
                  <div className={`p-4 rounded-xl ${stageColors('purple', 'bg')} border ${stageColors('purple', 'border')}`}>
                    <p className={`text-xs font-bold ${stageColors('purple', 'accent')} mb-1`}>{t('cew_file_with')}</p>
                    <p className={`font-bold ${c.text} text-lg`}>{s.agency}</p>
                    {s.agency_url && <p className={`text-sm ${stageColors('purple', 'accent')} mt-1`}>{s.agency_url}</p>}
                    <p className={`text-sm ${c.textSecondary} mt-2`}>{s.why_this_agency}</p>
                  </div>
                  <div className={`rounded-xl p-5 border ${c.letterBox}`}>
                    <p className={`text-xs font-bold ${c.textMuteded} mb-2`}>{t('cew_prewritten')}</p>
                    {isEditing ? (
                      <div>
                        <textarea value={editedLetters[stageKey] || s.complaint_text} onChange={e => setEditedLetters(prev => ({ ...prev, [stageKey]: e.target.value }))} rows={12} className={`w-full p-3 border rounded-xl text-sm resize-y outline-none focus:ring-2 leading-relaxed ${c.input}`} />
                        <div className="flex items-center gap-2 mt-2">
                          <button onClick={() => setEditingLetter(null)} className={`px-3 py-1.5 rounded-lg text-xs font-bold ${c.editDoneBtn}`}>✅ {t('cew_done')}</button>
                          <button onClick={() => cancelEditingLetter(stageKey, s.complaint_text)} className={`text-xs font-bold ${c.textMuteded}`}>{t('cew_reset')}</button>
                        </div>
                      </div>
                    ) : (
                      <div className={`whitespace-pre-wrap text-sm ${c.textSecondary} leading-relaxed`}>{complaintText}
                        {editedLetters[stageKey] && editedLetters[stageKey] !== s.complaint_text && <p className={`text-[10px] mt-2 ${c.issueTip}`}>✏️ {t('cew_edited_text')}</p>}
                      </div>
                    )}
                  </div>
                  {s.what_happens_after && <div className={`p-4 rounded-lg ${c.cardAlt}`}><p className={`text-xs font-bold ${c.textMuteded} mb-1`}>{t('cew_what_after')}</p><p className={`text-sm ${c.textSecondary}`}>{s.what_happens_after}</p></div>}
                  {s.company_impact && <div className={`p-4 rounded-lg ${c.cardAlt}`}><p className={`text-xs font-bold ${c.textMuteded} mb-1`}>{t('cew_why_serious')}</p><p className={`text-sm ${c.textSecondary}`}>{s.company_impact}</p></div>}
                  {renderStageActionBar(2, t('cew_mark_filed'), 3)}
                </div>
              );
            })()}

            {/* Stage 3 */}
            {activeStage === 3 && results?.escalation_stages?.stage_3_executive && (() => {
              const s = getStageData('stage_3_executive', results?.escalation_stages?.stage_3_executive);
              const stageKey = 'stage_3_executive';
              const isRegenerated = !!regeneratedStages[stageKey];
              const letterText = getLetterText(stageKey, s.letter_body);
              const isEditing = editingLetter === stageKey;
              if (regenerating === 3) return (
                <div className={`p-8 text-center ${c.cardAlt} rounded-xl`}>
                  <p className="text-lg mb-2"><span className="animate-spin inline-block">{tool?.icon ?? '📧'}</span></p>
                  <p className={`text-sm font-bold ${c.text}`}>{t('cew_regen_s3')}</p>
                  <p className={`text-xs ${c.textMuteded} mt-1`}>{t('cew_regen_s3_desc')}</p>
                </div>
              );
              return (
                <div className={`space-y-4 ${c.text}`}>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <h4 className={`font-bold ${c.text}`}>{t('cew_s3_heading')}</h4>
                      {isRegenerated && <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${c.contextBadge}`}>🔄 {t('cew_context_aware')}</span>}
                    </div>
                    <div className="flex items-center gap-2">
                      {!isEditing && <button onClick={() => startEditingLetter(stageKey, s.letter_body)} className={`px-2.5 py-1 rounded-lg text-xs font-bold ${c.btnSecondary}`}>✏️ {t('cew_edit')}</button>}
                    </div>
                  </div>
                  <div className={`rounded-xl p-5 border ${c.letterBox}`}>
                    <p className={`text-xs font-bold ${c.textMuteded} mb-1`}>{t('cew_subject')}</p>
                    <p className={`font-semibold ${c.text} mb-4`}>{s.subject_line}</p>
                    {isEditing ? (
                      <div>
                        <textarea value={editedLetters[stageKey] || s.letter_body} onChange={e => setEditedLetters(prev => ({ ...prev, [stageKey]: e.target.value }))} rows={12} className={`w-full p-3 border rounded-xl text-sm resize-y outline-none focus:ring-2 leading-relaxed ${c.input}`} />
                        <div className="flex items-center gap-2 mt-2">
                          <button onClick={() => setEditingLetter(null)} className={`px-3 py-1.5 rounded-lg text-xs font-bold ${c.editDoneBtn}`}>✅ {t('cew_done')}</button>
                          <button onClick={() => cancelEditingLetter(stageKey, s.letter_body)} className={`text-xs font-bold ${c.textMuteded}`}>{t('cew_reset')}</button>
                        </div>
                      </div>
                    ) : (
                      <div className={`whitespace-pre-wrap text-sm ${c.textSecondary} leading-relaxed`}>{letterText}
                        {editedLetters[stageKey] && editedLetters[stageKey] !== s.letter_body && <p className={`text-[10px] mt-2 ${c.issueTip}`}>✏️ {t('cew_edited_letter')}</p>}
                      </div>
                    )}
                  </div>
                  {s.target_contacts?.length > 0 && (
                    <div className={`p-4 rounded-lg ${stageColors('orange', 'bg')} border ${stageColors('orange', 'border')}`}>
                      <p className={`text-xs font-bold ${stageColors('orange', 'accent')} mb-2`}>{t('cew_target_contacts')}</p>
                      {s.target_contacts.map((tc, i) => (
                        <div key={i} className={`text-sm ${c.textSecondary} mb-2`}>
                          <span className={`font-semibold ${c.text}`}>{tc.title}</span>
                          {tc.email_pattern && <span className={`ml-2 font-mono text-xs ${c.textMuteded}`}>{tc.email_pattern}</span>}
                          {tc.why && <p className={`text-xs ${c.textMuteded} mt-0.5`}>{tc.why}</p>}
                        </div>
                      ))}
                    </div>
                  )}
                  {s.timing && <div className={`p-3 rounded-lg ${c.cardAlt}`}><p className={`text-xs font-bold ${c.textMuteded} mb-1`}>{t('cew_timing')}</p><p className={`text-sm ${c.textSecondary}`}>{s.timing}</p></div>}
                  {renderStageActionBar(3, t('cew_mark_sent'), 4)}
                </div>
              );
            })()}

            {/* Stage 4 */}
            {activeStage === 4 && results?.escalation_stages?.stage_4_public && (() => {
              const s = getStageData('stage_4_public', results?.escalation_stages?.stage_4_public);
              const isRegenerated = !!regeneratedStages['stage_4_public'];
              if (regenerating === 4) return (
                <div className={`p-8 text-center ${c.cardAlt} rounded-xl`}>
                  <p className="text-lg mb-2"><span className="animate-spin inline-block">{tool?.icon ?? '📧'}</span></p>
                  <p className={`text-sm font-bold ${c.text}`}>{t('cew_regen_s4')}</p>
                  <p className={`text-xs ${c.textMuteded} mt-1`}>{t('cew_regen_s4_desc')}</p>
                </div>
              );
              return (
                <div className={`space-y-4 ${c.text}`}>
                  <div className="flex items-center gap-2">
                    <h4 className={`font-bold ${c.text}`}>{t('cew_s4_heading')}</h4>
                    {isRegenerated && <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${c.contextBadge}`}>🔄 {t('cew_context_aware')}</span>}
                  </div>
                  {s.social_media_post && (
                    <div className={`rounded-xl p-5 border ${c.letterBox}`}>
                      <div className="flex items-center justify-between mb-2">
                        <p className={`text-xs font-bold ${c.textMuteded}`}>{t('cew_twitter_post')}</p>
                      </div>
                      <p className={`text-sm ${c.text} leading-relaxed`}>{s.social_media_post}</p>
                      <p className={`text-xs ${c.textMuteded} mt-2`}>{t('cew_chars', { n: s.social_media_post.length })}</p>
                    </div>
                  )}
                  {s.social_media_long && (
                    <div className={`rounded-xl p-5 border ${c.letterBox}`}>
                      <div className="flex items-center justify-between mb-2">
                        <p className={`text-xs font-bold ${c.textMuteded}`}>{t('cew_detailed_post')}</p>
                      </div>
                      <div className={`whitespace-pre-wrap text-sm ${c.textSecondary} leading-relaxed`}>{s.social_media_long}</div>
                    </div>
                  )}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    {s.platforms_to_target?.length > 0 && (
                      <div className={`p-4 rounded-lg ${stageColors('pink', 'bg')} border ${stageColors('pink', 'border')}`}>
                        <p className={`text-xs font-bold ${stageColors('pink', 'accent')} mb-2`}>{t('cew_post_on')}</p>
                        {s.platforms_to_target.map((p, i) => <p key={i} className={`text-sm ${c.textSecondary}`}>• {p}</p>)}
                      </div>
                    )}
                    {s.review_sites?.length > 0 && (
                      <div className={`p-4 rounded-lg ${stageColors('pink', 'bg')} border ${stageColors('pink', 'border')}`}>
                        <p className={`text-xs font-bold ${stageColors('pink', 'accent')} mb-2`}>{t('cew_leave_reviews')}</p>
                        {s.review_sites.map((r, i) => <p key={i} className={`text-sm ${c.textSecondary}`}>• {r}</p>)}
                      </div>
                    )}
                  </div>
                  {s.hashtags?.length > 0 && <div className="flex flex-wrap gap-2">{s.hashtags.map((h, i) => <span key={i} className={`px-2 py-1 rounded-full text-xs font-medium ${stageColors('pink', 'badge')}`}>{h}</span>)}</div>}
                  {s.media_tip && <div className={`p-3 rounded-lg ${c.cardAlt}`}><p className={`text-xs font-bold ${c.textMuteded} mb-1`}>📺 {t('cew_media_tip')}</p><p className={`text-sm ${c.textSecondary}`}>{s.media_tip}</p></div>}
                  {renderStageActionBar(4, t('cew_mark_posted'), 5)}
                </div>
              );
            })()}

            {/* Stage 5 */}
            {activeStage === 5 && results?.escalation_stages?.stage_5_financial_legal && (() => {
              const s = getStageData('stage_5_financial_legal', results?.escalation_stages?.stage_5_financial_legal);
              const isRegenerated = !!regeneratedStages['stage_5_financial_legal'];
              if (regenerating === 5) return (
                <div className={`p-8 text-center ${c.cardAlt} rounded-xl`}>
                  <p className="text-lg mb-2"><span className="animate-spin inline-block">{tool?.icon ?? '📧'}</span></p>
                  <p className={`text-sm font-bold ${c.text}`}>{t('cew_regen_s5')}</p>
                  <p className={`text-xs ${c.textMuteded} mt-1`}>{t('cew_regen_s5_desc')}</p>
                </div>
              );
              return (
                <div className={`space-y-4 ${c.text}`}>
                  <div className="flex items-center gap-2">
                    <h4 className={`font-bold ${c.text}`}>{t('cew_s5_heading')}</h4>
                    {isRegenerated && <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${c.contextBadge}`}>🔄 {t('cew_context_aware')}</span>}
                  </div>
                  {s.chargeback?.applicable && (
                    <div className={`p-5 rounded-xl border ${stageColors('red', 'border')} ${stageColors('red', 'bg')}`}>
                      <p className={`text-xs font-bold ${stageColors('red', 'accent')} mb-2`}>💳 {t('cew_chargeback')}</p>
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-3">
                        {s.chargeback.reason_code && <div><p className={`text-xs ${c.textMuteded}`}>{t('cew_reason_code')}</p><p className={`text-sm font-semibold ${c.text}`}>{s.chargeback.reason_code}</p></div>}
                        {s.chargeback.time_window && <div><p className={`text-xs ${c.textMuteded}`}>{t('cew_time_window')}</p><p className={`text-sm font-semibold ${c.text}`}>{s.chargeback.time_window}</p></div>}
                      </div>
                      {s.chargeback.how_to_file && <p className={`text-sm ${c.textSecondary} mb-2`}><strong>{t('cew_how_to_file')}</strong> {s.chargeback.how_to_file}</p>}
                      {s.chargeback.documentation_needed && <p className={`text-sm ${c.textSecondary} mb-2`}><strong>{t('cew_documentation')}</strong> {s.chargeback.documentation_needed}</p>}
                      {s.chargeback.success_likelihood && <p className={`text-sm ${c.textSecondary}`}><strong>{t('cew_likelihood')}</strong> {s.chargeback.success_likelihood}</p>}
                    </div>
                  )}
                  {s.small_claims?.applicable && (
                    <div className={`p-5 rounded-xl border ${c.border} ${c.cardAlt}`}>
                      <p className={`text-xs font-bold ${stageColors('red', 'accent')} mb-2`}>⚖️ {t('cew_small_claims')}</p>
                      <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 mb-3">
                        {s.small_claims.filing_fee_range && <div><p className={`text-xs ${c.textMuteded}`}>{t('cew_filing_fee')}</p><p className={`text-sm font-semibold ${c.text}`}>{s.small_claims.filing_fee_range}</p></div>}
                        {s.small_claims.max_claim_amount && <div><p className={`text-xs ${c.textMuteded}`}>{t('cew_max_claim')}</p><p className={`text-sm font-semibold ${c.text}`}>{s.small_claims.max_claim_amount}</p></div>}
                        {s.small_claims.jurisdiction && <div><p className={`text-xs ${c.textMuteded}`}>{t('cew_jurisdiction')}</p><p className={`text-sm font-semibold ${c.text}`}>{s.small_claims.jurisdiction}</p></div>}
                      </div>
                      {s.small_claims.typical_outcome && <p className={`text-sm ${c.textSecondary} mb-1`}><strong>{t('cew_typical_outcome')}</strong> {s.small_claims.typical_outcome}</p>}
                      {s.small_claims.company_response && <p className={`text-sm ${c.textSecondary}`}><strong>{t('cew_company_usually')}</strong> {s.small_claims.company_response}</p>}
                    </div>
                  )}
                  {s.attorney_general?.applicable && (
                    <div className={`p-5 rounded-xl border ${c.border} ${c.cardAlt}`}>
                      <p className={`text-xs font-bold ${stageColors('red', 'accent')} mb-2`}>🏛️ {t('cew_attorney_general')}</p>
                      {s.attorney_general.how_to_file && <p className={`text-sm ${c.textSecondary} mb-1`}><strong>{t('cew_how_to_file')}</strong> {s.attorney_general.how_to_file}</p>}
                      {s.attorney_general.what_it_triggers && <p className={`text-sm ${c.textSecondary}`}><strong>{t('cew_what_triggers')}</strong> {s.attorney_general.what_it_triggers}</p>}
                    </div>
                  )}
                  {renderStageActionBar(5, t('cew_mark_filed'), null)}
                </div>
              );
            })()}

            {/* Preview next stage nudge */}
            {activeStage < 5 && !getStageStatus(activeStage) && (
              <div className="flex justify-end mt-4">
                <button onClick={() => setActiveStage(activeStage + 1)} className={`flex items-center gap-1.5 text-sm font-medium ${c.textSecondary} transition-colors`}>
                  {t('cew_preview_stage', { n: activeStage + 1 })} <span>→</span>
                </button>
              </div>
            )}
          </div>

          {/* Timeline */}
          {results?.timeline && (
            <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-6`}>
              <h3 className={`font-bold ${c.text} mb-4 flex items-center gap-2`}><span>⏰</span> {t('cew_campaign_timeline')}</h3>
              <div className="relative pl-6">
                <div className={`absolute left-2 top-0 bottom-0 w-0.5 ${c.timelineLine}`} />
                {Object.entries(results?.timeline).map(([key, value], idx) => (
                  <div key={key} className="relative mb-4 last:mb-0">
                    <div className={`absolute -left-4 top-1 w-3 h-3 rounded-full border-2 ${idx === 0 ? 'bg-green-500 border-green-300' : c.timelineDotRest}`} />
                    <p className={`text-xs font-bold uppercase tracking-wide ${idx === 0 ? c.resolvedText : c.textMuteded} mb-0.5`}>{key.replace(/_/g, ' ')}</p>
                    <p className={`text-sm ${c.textSecondary}`}>{value}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Quick Tips */}
          {results?.quick_tips?.length > 0 && (
            <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-6`}>
              <h3 className={`font-bold ${c.text} mb-3 flex items-center gap-2`}><span>⚡</span> {t('cew_tactical_tips')}</h3>
              {results?.quick_tips?.map((tip, idx) => <p key={idx} className={`text-sm ${c.textSecondary} mb-2`}>• {tip}</p>)}
            </div>
          )}

          {/* Call Script */}
          {results?.call_script && (
            <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-6`}>
              <button onClick={() => setShowCallScript(!showCallScript)} className={`w-full flex items-center justify-between ${c.text}`}>
                <h3 className="font-bold flex items-center gap-2"><span>📞</span> {t('cew_call_script')}</h3>
                {showCallScript ? <span>▲</span> : <span>▼</span>}
              </button>
              {showCallScript && (
                <div className="space-y-4 mt-4">
                  <div className={`p-4 rounded-xl border ${c.callOpenBox}`}>
                    <p className={`text-xs font-bold ${c.callOpenText} mb-1`}>📋 {t('cew_open_with')}</p>
                    <p className={`text-sm ${c.text} leading-relaxed`}>{results?.call_script?.opening}</p>
                  </div>
                  {results?.call_script?.key_phrases?.length > 0 && (
                    <div>
                      <p className={`text-xs font-bold ${c.callPhrasesText} mb-2`}>✅ {t('cew_key_phrases')}</p>
                      {results?.call_script?.key_phrases.map((phrase, i) => (
                        <div key={i} className={`flex items-start gap-2 mb-2 p-2 rounded-lg ${c.callPhrasesBox}`}>
                          <span className="text-xs mt-0.5">💬</span>
                          <p className={`text-sm italic ${c.text}`}>"{phrase}"</p>
                        </div>
                      ))}
                    </div>
                  )}
                  {results?.call_script?.things_to_avoid_saying?.length > 0 && (
                    <div>
                      <p className={`text-xs font-bold ${c.callAvoidText} mb-2`}>🚫 {t('cew_never_say')}</p>
                      {results?.call_script?.things_to_avoid_saying.map((phrase, i) => (
                        <div key={i} className={`flex items-start gap-2 mb-2 p-2 rounded-lg ${c.callAvoidBox}`}>
                          <span className="text-xs mt-0.5">✕</span>
                          <p className={`text-sm ${c.textSecondary}`}>"{phrase}"</p>
                        </div>
                      ))}
                    </div>
                  )}
                  {results?.call_script?.redirect_to_writing && (
                    <div className={`p-4 rounded-xl border ${c.border} ${c.cardAlt}`}>
                      <p className={`text-xs font-bold ${c.textMuteded} mb-1`}>📝 {t('cew_redirect_writing')}</p>
                      <p className={`text-sm italic ${c.text}`}>"{results?.call_script?.redirect_to_writing}"</p>
                      <p className={`text-xs ${c.textMuteded} mt-1`}>{t('cew_redirect_note')}</p>
                    </div>
                  )}
                  {results?.call_script?.if_they_pressure && (
                    <div className={`p-4 rounded-xl border ${c.callPressureBox}`}>
                      <p className={`text-xs font-bold ${c.callPressureText} mb-1`}>⚡ {t('cew_if_pressure')}</p>
                      <p className={`text-sm italic ${c.text}`}>"{results?.call_script?.if_they_pressure}"</p>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}

          {/* Campaign Log */}
          {getCampaignEntries().length > 0 && (
            <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-6`}>
              <button onClick={() => toggleSection('campaign')} className={`w-full flex items-center justify-between ${c.text}`}>
                <h3 className="font-bold flex items-center gap-2">
                  <span>📜</span> {getCampaignEntries().length === 1 ? t('cew_campaign_log_one', { count: getCampaignEntries().length }) : t('cew_campaign_log', { count: getCampaignEntries().length })}
                </h3>
                {expandedSections.campaign ? <span>▲</span> : <span>▼</span>}
              </button>
              {expandedSections.campaign && (
                <div className="space-y-3 mt-4">
                  {getCampaignEntries().sort((a, b) => a.stage - b.stage).map(entry => {
                    const stg = stageConfig[entry.stage - 1];
                    return (
                      <div key={entry.stage} className={`p-3 rounded-xl border ${c.border}`}>
                        <div className="flex items-center gap-2 mb-1">
                          <span>{stg?.icon || '📨'}</span>
                          <p className={`text-sm font-bold ${c.text}`}>{t('cew_stage_label', { n: entry.stage, label: stg?.label || t('cew_unknown') })}</p>
                          {entry.sentDate && <span className={`text-xs ${c.textMuteded}`}>{t('cew_sent_on', { date: new Date(entry.sentDate).toLocaleDateString(userLocale || undefined) })}</span>}
                          {entry.outcome && <span className={`px-1.5 py-0.5 rounded text-[10px] font-bold ${outcomeBadge[entry.outcome] || ''}`}>{entry.outcome}</span>}
                        </div>
                        {entry.companyResponse && <p className={`text-xs ${c.textSecondary} mt-1`}>📨 {t('cew_log_response', { text: `${entry.companyResponse.slice(0, 120)}…` })}</p>}
                        {entry.analysisResult?.recommendation && <p className={`text-xs ${c.textMuteded} mt-0.5`}>{t('cew_ai_said', { reco: entry.analysisResult.recommendation, assessment: `${entry.analysisResult.assessment?.slice(0, 100)}…` })}</p>}
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          )}

          {/* Cross-references (post-result) */}
          <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
            <p className={`text-xs font-semibold ${c.textMuted} uppercase tracking-wider mb-2`}>{t('cew_while_at_it')}</p>
            <p className={`text-sm ${c.textSecondary}`}>
              {t('cew_xref_post_q')} <a href="/LeverageLogic" className={linkStyle}>⚖️ {t('cew_xref_leverage')}</a> {t('cew_xref_post_tail')}
              {amountAtStake && <>{' '}{t('cew_xref_billing_q')} <a href="/BillRescue" className={linkStyle}>💰 {t('cew_xref_billrescue')}</a> {t('cew_xref_billing_tail')}</>}
            </p>
          </div>

          {/* Disclaimer */}
          <div className={`p-4 rounded-xl text-center ${c.disclaimerBox}`}>
            <p className={`text-xs ${c.textMuteded}`}>⚖️ {t('cew_disclaimer')}</p>
          </div>
        </div>
      )}
    </div>
  );
};

ComplaintEscalationWriter.displayName = 'ComplaintEscalationWriter';
export default ComplaintEscalationWriter;
