import React, { useState, useEffect, useRef, useCallback } from 'react';
import Caret from '../components/Caret';
import { useRegisterActions } from '../components/ActionBarContext';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useTranslation } from '../i18n/useTranslation';
import { pickExample } from '../utils/exampleRotation';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

const ConflictCoach = ({ tool }) => {
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();

  const EXAMPLES = [
    {
      receivedMessage: t('cc_ex1_msg'),
      relationship: 'Roommate',
      emotional: { angry: false, hurt: true, defensive: false, frustrated: true, calm: false, confused: false },
    },
    {
      receivedMessage: t('cc_ex2_msg'),
      relationship: 'Partner',
      emotional: { angry: false, hurt: true, defensive: false, frustrated: false, calm: false, confused: true },
    },
  ];

  // ─── Standard c object ───
  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-400' : 'text-gray-500',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-200 text-red-800',
    required:      'text-red-500',
    // ─── Tool-specific semantic colors ───
    toast:             isDark ? 'bg-zinc-700 text-zinc-100 border border-zinc-600' : 'bg-white text-gray-900 border border-gray-200',
    draftFlag:         isDark ? 'bg-amber-900/20' : 'bg-amber-50',
    strategySelected:  isDark ? 'border-cyan-500 bg-cyan-900/20' : 'border-cyan-500 bg-cyan-50',
    strategyHover:     isDark ? 'border-zinc-600 hover:border-zinc-500' : 'border-gray-200 hover:border-gray-300',
    toneBadge:         isDark ? 'bg-zinc-700 text-zinc-300' : 'bg-gray-100 text-gray-600',
    lockIcon:          isDark ? 'text-red-400' : 'text-red-600',
    unlockIcon:        isDark ? 'text-emerald-400' : 'text-emerald-600',
    strategyText:      isDark ? 'bg-zinc-700/50' : 'bg-gray-50',
    toneSlider:        isDark ? 'bg-zinc-700/50' : 'bg-gray-50',
    toneAdjusted:      isDark ? 'bg-zinc-700/30' : 'bg-gray-50',
    followupMe:        isDark ? 'bg-zinc-700/50' : 'bg-gray-100',
    confirmModal:      isDark ? 'bg-zinc-700/50' : 'bg-gray-100',
    goalActive:        isDark ? 'border-cyan-500 bg-cyan-900/30 text-cyan-200' : 'border-cyan-600 bg-cyan-100 text-cyan-900',
    goalInactive:      isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500' : 'border-gray-300 text-gray-500 hover:border-gray-400',
    threadContainer:   isDark ? 'bg-zinc-800/50 border-zinc-700' : 'bg-gray-50 border-gray-200',
    threadMsgMe:       isDark ? 'bg-cyan-900/30 border-cyan-700' : 'bg-cyan-50 border-cyan-200',
    threadMsgThem:     isDark ? 'bg-zinc-700/50 border-zinc-600' : 'bg-white border-gray-200',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';

  // Temperature color map
  const [emotionalState, setEmotionalState] = useState({ angry: false, hurt: false, defensive: false, frustrated: false, calm: false, confused: false });
  const [goal,           setGoal]           = useState('');
  const [userDraft,      setUserDraft]      = useState('');
  const [error,          setError]          = useState('');
  const [toast,          setToast]          = useState(null);
  const [delayEndTime,          setDelayEndTime]          = useState(null);
  const [now,                   setNow]                   = useState(Date.now);
  const [selectedResponse,      setSelectedResponse]      = useState(null);
  const [showConfirmSend,       setShowConfirmSend]       = useState(false);
  const [threadMessages,        setThreadMessages]        = useState([]);
  const [threadInput,           setThreadInput]           = useState('');
  const [threadSender,          setThreadSender]          = useState('them');
  const [useThread,             setUseThread]             = useState(false);
  const [followupQuestion,      setFollowupQuestion]      = useState('');
  const [followupHistory,       setFollowupHistory]       = useState([]);
  const [followupLoading,       setFollowupLoading]       = useState(false);
  const [selectedStrategyIdx,   setSelectedStrategyIdx]   = useState(null);
  const [toneLevel,             setToneLevel]             = useState(50);
  const [adjustedResponse,      setAdjustedResponse]      = useState(null);
  const [toneLoading,           setToneLoading]           = useState(false);

  // ─── Refs ───
  const toastTimerRef  = useRef(null);
  const mountedRef     = useRef(true);
  const followupRef    = useRef(null);
  const resultsRef     = useRef(null);
  const loadExample = () => {
    const ex = pickExample('ConflictCoach', EXAMPLES);
    setReceivedMessage(ex.receivedMessage);
    setRelationship(ex.relationship);
    setEmotionalState(ex.emotional);
  };

  const submitRef      = useRef(null);
  const canSubmitRef   = useRef(false);

  // ─── Persisted state ───
  const [receivedMessage, setReceivedMessage] = usePersistentState('cc-message', '');
  const [relationship,    setRelationship]    = usePersistentState('cc-relationship', 'Friend');
  const [personLabel,     setPersonLabel]     = usePersistentState('cc-person', '');
  const [actualGoal,      setActualGoal]      = usePersistentState('cc-goal', '');
  const [results,         setResults]         = usePersistentState('cc-results', null);

  // ─── Helpers ───
  const showToast = (msg, dur = 4000) => {
    if (!mountedRef.current) return;
    if (toastTimerRef.current) clearTimeout(toastTimerRef.current);
    setToast(msg);
    toastTimerRef.current = setTimeout(() => { if (mountedRef.current) setToast(null); }, dur);
  };

  const delayActive  = delayEndTime !== null && now < delayEndTime;
  const delaySeconds = delayEndTime !== null ? Math.max(0, Math.round((delayEndTime - now) / 1000)) : 0;

  const relationshipOptions = [
    { value: 'Partner',  label: t('cc_rel_partner') },
    { value: 'Family',   label: t('cc_rel_family') },
    { value: 'Friend',   label: t('cc_rel_friend') },
    { value: 'Coworker', label: t('cc_rel_coworker') },
    { value: 'Ex',       label: t('cc_rel_ex') },
    { value: 'Customer', label: t('cc_rel_customer') },
    { value: 'Other',    label: t('cc_rel_other') },
  ];

  useEffect(() => {
    if (!delayEndTime) return;
    const tick = () => {
      if (!mountedRef.current) return;
      const remaining = delayEndTime - Date.now();
      if (remaining <= 0) {
        setDelayEndTime(null);
        setNow(Date.now());
        showToast(t('cc_toast_cooling_done'), 6000);
      } else {
        setNow(Date.now());
      }
    };
    const iv = setInterval(tick, 1000);
    return () => clearInterval(iv);
  }, [delayEndTime]); // eslint-disable-line react-hooks/exhaustive-deps

  // ─── Cleanup all timers on unmount ───
  useEffect(() => {
    mountedRef.current = true;
    return () => {
      mountedRef.current = false;
      if (toastTimerRef.current) clearTimeout(toastTimerRef.current);
    };
  }, []);

  const formatTime = (s) => `${Math.floor(s / 60)}:${(s % 60).toString().padStart(2, '0')}`;

  // ─── Core actions ───
  const handleAnalyze = async () => {
    const msg = useThread
      ? threadMessages.map(m => `[${m.sender}]: ${m.text}`).join('\n')
      : receivedMessage.trim();
    if (!msg || msg.length < 10) { setError(t('cc_err_paste')); return; }

    setError(''); setResults(null); setFollowupHistory([]); setSelectedStrategyIdx(null); setAdjustedResponse(null);
    try {
      const data = await callToolEndpoint('conflict-coach', {
        receivedMessage: msg, relationship,
        emotionalState: Object.keys(emotionalState).filter(k => emotionalState[k]),
        goals: goal ? [goal] : [],
        userDraft: userDraft.trim(), actualGoal: actualGoal.trim(),
        isThread: useThread, personLabel: personLabel.trim() || null,
        userLocale, userCurrency, userRegion,
      });
      setResults(data);
      if (emotionalState.angry || emotionalState.defensive) {
        if (!delayActive) { setDelayEndTime(Date.now() + 600 * 1000); }
      }
    } catch (err) { setError(err.message || t('cc_err_analysis')); }
  };


  const handleConfirmCopy = async () => {
    if (!selectedResponse) return;
    try {
      await navigator.clipboard.writeText(`${selectedResponse}${BRAND}`);
      setShowConfirmSend(false); showToast(t('cc_toast_copied')); setSelectedResponse(null);
    } catch { showToast(t('cc_toast_copy_failed')); }
  };

  const handleReset = () => {
    setReceivedMessage(''); setRelationship('Friend');
    setEmotionalState({ angry: false, hurt: false, defensive: false, frustrated: false, calm: false, confused: false });
    setGoal('');
    setUserDraft(''); setResults(null); setError('');
    setSelectedResponse(null); setActualGoal('');
    setShowConfirmSend(false);
    setThreadMessages([]); setFollowupHistory([]); setSelectedStrategyIdx(null); setAdjustedResponse(null);
  };

  // ─── Thread builder ───
  const handleAddThreadMessage = () => {
    if (!threadInput.trim()) return;
    setThreadMessages(p => [...p, { sender: threadSender, text: threadInput.trim(), id: Date.now() }]);
    setThreadInput(''); setThreadSender(threadSender === 'them' ? 'me' : 'them');
  };
  const handleRemoveThreadMessage = (id) => setThreadMessages(p => p.filter(m => m.id !== id));

  // ─── Follow-up coaching ───
  const handleFollowup = async () => {
    if (!followupQuestion.trim() || !results) return;
    setFollowupLoading(true); const q = followupQuestion.trim(); setFollowupQuestion('');
    try {
      const data = await callToolEndpoint('conflict-coach/followup', {
        question: q, originalAnalysis: results, relationship,
        receivedMessage: receivedMessage.trim(), actualGoal: actualGoal.trim(),
        personLabel: personLabel.trim() || null,
        userLocale, userCurrency, userRegion,
      });
      setFollowupHistory(p => [...p, { question: q, answer: data.answer }]);
      setTimeout(() => followupRef.current?.scrollIntoView({ behavior: 'smooth' }), 100);
    } catch { showToast(t('cc_toast_followup_failed')); }
    setFollowupLoading(false);
  };

  // ─── Tone adjustment ───
  const handleAdjustTone = async () => {
    if (selectedStrategyIdx === null || !results?.response_strategies?.[selectedStrategyIdx]) return;
    setToneLoading(true);
    const strategy = results.response_strategies[selectedStrategyIdx];
    try {
      const data = await callToolEndpoint('conflict-coach/adjust-tone', {
        originalResponse: strategy.response_text, originalStrategy: strategy.strategy,
        toneLevel, relationship, receivedMessage: receivedMessage.trim(), actualGoal: actualGoal.trim(),
        userLocale, userCurrency, userRegion,
      });
      setAdjustedResponse(data);
    } catch { showToast(t('cc_toast_tone_failed')); }
    setToneLoading(false);
  };

  const buildFullText = useCallback(() => {
    if (!results) return '';
    const l = [`💬 ${t('cc_copy_header')}`, '═'.repeat(40)];
    if (results.message_analysis) {
      if (results.message_analysis.whats_being_asked) l.push('', results.message_analysis.whats_being_asked);
      if (results.message_analysis.triggers_identified?.length) l.push(`${t('cc_copy_triggers')}: ${results.message_analysis.triggers_identified.join('; ')}`);
    }
    if (results.goal_reality_check) { l.push('', `🎯 ${t('cc_copy_goalcheck')}`, results.goal_reality_check.assessment); if (results.goal_reality_check.alternative_approach) l.push(`${t('cc_copy_alternative')}: ${results.goal_reality_check.alternative_approach}`); }
    if (results.draft_analysis) { l.push('', `🚨 ${t('cc_copy_draft')}`, results.draft_analysis.overall_assessment); }
    if (results.response_strategies?.length) { l.push('', `💡 ${t('cc_copy_strategies')}`); results.response_strategies.forEach((s, i) => { l.push(`\n  ${i + 1}. ${s.strategy} (${s.tone})`, `  "${s.response_text}"`, ''); }); }
    if (followupHistory.length) { l.push('', `${t('cc_copy_followup')}:`); followupHistory.forEach(f => l.push(`  ${t('cc_copy_q')}: ${f.question}`, `  ${t('cc_copy_a')}: ${f.answer}`, '')); }
    return l.join('\n') + BRAND;
  }, [results, followupHistory]); // eslint-disable-line react-hooks/exhaustive-deps

  useRegisterActions(buildFullText(), tool?.title ?? 'Conflict Coach');

  // ─── Scroll to results ───
  useEffect(() => {
    if (!results) return;
    const tm = setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 100);
    return () => clearTimeout(tm);
  }, [results]);

  // ─── Keyboard refs (assigned on every render so handler sees fresh state) ───
  submitRef.current    = handleAnalyze;
  canSubmitRef.current = !loading &&
    (useThread ? threadMessages.length > 0 : receivedMessage.trim().length >= 10);

  // ─── Document-level Ctrl+Enter submit ───
  useEffect(() => {
    const handler = (e) => {
      const tag = e.target?.tagName;
      if (tag === 'SELECT') return;
      if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') {
        if (!loading && canSubmitRef.current) {
          e.preventDefault();
          submitRef.current?.();
        }
      }
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, [loading]);

  // The history is gone, but anyone who used this tool before today still has
  // it on their device: who upset them, what was said, and the tactics the
  // model scored those people with. Removing the feature does not remove the
  // file, so clear it once on mount. Cheap, silent, and the only chance we get
  // — after this release nothing else references the key.
  useEffect(() => {
    try { window.localStorage.removeItem('cc-history'); } catch { /* private mode */ }
  }, []);

  const exampleMessage = t('cc_example_message');
  const hasContent = !!(results || receivedMessage.trim());


  // ═══════════════════════════════════════════════════════════════
  // RENDER
  // ═══════════════════════════════════════════════════════════════
  return (
    <div className={`space-y-4 ${c.text}`}>

      {/* Toast */}
      {toast && (
        <div className={`fixed top-4 start-1/2 -translate-x-1/2 z-50 px-6 py-3 rounded-lg shadow-lg text-sm font-medium max-w-md text-center ${c.toast}`}>
          {toast}
        </div>
      )}

      {/* ═══ INPUT CARD ═══ */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm px-5 pt-2.5 pb-5`}>
        {/* Standard header */}
        <div className="mb-4 pb-3 border-b border-zinc-500">
          <div className="flex items-center justify-between">
            <div>
              {/* PF-30 — the wrapper already prints the name as the page <h1>. */}
              <p className={`text-base ${c.textSecondary}`}>
                <span className="me-2 text-lg">{tool?.icon ?? '📱'}</span>{tool?.tagline ?? t('cc_tagline')}
              </p>
              <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className="mt-2 px-4 py-2 rounded-full text-sm font-semibold border border-black/25 text-zinc-900 shadow-sm hover:brightness-105 hover:shadow transition disabled:opacity-40 whitespace-nowrap">✨ {t('try_example')}</button>
            </div>
            <div className="flex items-center gap-2">
              {hasContent && (
                <button onClick={handleReset} className={`${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs`}>
                  ↺ {t('start_over')}
                </button>
              )}
            </div>
          </div>
        </div>

        <div className="space-y-5">

        {/* Mandatory delay — below header so tool name always renders first */}
          {delayActive && (
            <div className={`${c.danger} border-4 rounded-xl p-6 text-center`}>
              <span className="text-6xl block mb-4">🔒</span>
              <h3 className={`text-2xl font-bold mb-2 ${c.text}`}>{t('cc_cooling_title')}</h3>
              <div className={`text-5xl font-mono font-bold mb-3 ${c.text}`}>{formatTime(delaySeconds)}</div>
              <p className={`text-sm ${c.text}`}>{t('cc_cooling_body')}</p>
              {results?.cooling_recommendation?.delay_time && (
                <p className={`text-xs ${c.textSecondary} mt-2`}>{t('cc_cooling_suggested')}: {results.cooling_recommendation.delay_time}</p>
              )}
              {results?.cooling_recommendation?.why_delay && (
                <p className={`text-xs ${c.textMuteded} mt-1`}>{results.cooling_recommendation.why_delay}</p>
              )}
            </div>
          )}

          {/* Relationship */}
          <div>
            <label className={`block text-sm font-medium ${c.text} mb-1`}>{t('cc_relationship_label')}</label>
            <select value={relationship} onChange={e => setRelationship(e.target.value)}
              className={`w-full p-3 border rounded-lg ${c.input}`}>
              {relationshipOptions.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
            </select>
          </div>

          {/* Thread toggle */}
          <label className={`flex items-center gap-2 cursor-pointer text-sm ${c.text}`}>
            <input type="checkbox" checked={useThread} onChange={e => setUseThread(e.target.checked)} className="w-4 h-4" />
            {t('cc_thread_toggle')}
          </label>

          {/* Thread builder OR single message */}
          {useThread ? (
            <div>
              <label className={`block text-sm font-medium ${c.text} mb-2`}>{t('cc_thread_build')}</label>
              {threadMessages.length > 0 && (
                <div className={`mb-3 p-3 rounded-lg border ${c.threadContainer} max-h-48 overflow-y-auto space-y-2`}>
                  {threadMessages.map(m => (
                    <div key={m.id} className={`flex ${m.sender === 'me' ? 'justify-end' : 'justify-start'}`}>
                      <div className={`max-w-[75%] p-2 rounded-lg text-sm border ${m.sender === 'me' ? c.threadMsgMe : c.threadMsgThem}`}>
                        <p className={`text-xs font-bold mb-0.5 ${c.textMuteded}`}>{m.sender === 'me' ? t('cc_sender_you') : t('cc_sender_them')}</p>
                        <p className={c.text}>{m.text}</p>
                        <button onClick={() => handleRemoveThreadMessage(m.id)} className={`text-xs ${c.textMuteded} mt-1 hover:underline`}>✕ {t('cc_remove')}</button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
              <div className="flex gap-2">
                <select value={threadSender} onChange={e => setThreadSender(e.target.value)} className={`p-2 border rounded text-sm ${c.input} w-24`}>
                  <option value="them">{t('cc_sender_them')}</option><option value="me">{t('cc_sender_me')}</option>
                </select>
                <input type="text" value={threadInput} onChange={e => setThreadInput(e.target.value)}
                  placeholder={t('cc_thread_input_ph')}
                  className={`flex-1 p-2 border rounded text-sm ${c.input}`}
                  onKeyDown={e => { if (e.key === 'Enter') handleAddThreadMessage(); }} />
                <button onClick={handleAddThreadMessage} className={`${c.btnPrimary} px-3 py-2 rounded text-sm`}>{t('cc_add')}</button>
              </div>
              <p className={`text-xs ${c.textMuteded} mt-1`}>{t('cc_thread_hint')}</p>
            </div>
          ) : (
            <div>
              <div className="flex justify-between mb-1">
                <label className={`text-sm font-medium ${c.text}`}>{t('cc_received_label')} <span className={c.required}>*</span></label>
                <button onClick={() => setReceivedMessage(exampleMessage)} className={`text-xs ${linkStyle}`}>{t('example')}</button>
              </div>
              <textarea value={receivedMessage} onChange={e => setReceivedMessage(e.target.value)}
                placeholder={t('cc_received_ph')}
                className={`w-full p-4 border rounded-lg ${c.input}`} rows={4} />
            </div>
          )}

          {/* What they want to say. An ordinary optional field: the red box and
              the stop sign made typing an honest answer feel like a confession. */}
          <div>
            <label className={`block text-sm font-medium ${c.text} mb-1`}>{t('cc_draft_label')}</label>
            <textarea value={userDraft} onChange={e => setUserDraft(e.target.value)}
              placeholder={t('cc_draft_ph')}
              className={`w-full p-4 border rounded-lg ${c.input}`} rows={3} />
            <p className={`text-xs ${c.textMuteded} mt-1`}>{t('cc_draft_hint')}</p>
          </div>

          {/* Goals */}
          <div>
            <label className={`block text-sm font-medium ${c.text} mb-2`}>{t('cc_goal_label')}</label>
            {/* PF-37: one choice, as cards. Five checkboxes invited picking
                three goals at once, which is how a conversation gets away from
                someone — the tool should ask what they actually want most. */}
            <div className="grid grid-cols-2 md:grid-cols-3 gap-2">
              {[
                ['resolve',       t('cc_goal_resolve')],
                ['boundary',      t('cc_goal_boundary')],
                ['disengage',     t('cc_goal_disengage')],
                ['validate',      t('cc_goal_validate')],
                ['schedule_talk', t('cc_goal_schedule')],
              ].map(([key, label]) => (
                <button key={key} type="button" onClick={() => setGoal(goal === key ? '' : key)}
                  className={`w-full min-h-[44px] px-3 py-2.5 rounded-xl text-sm border-2 text-start transition-colors ${goal === key ? c.goalActive : c.goalInactive}`}>
                  {label}
                </button>
              ))}
            </div>
          </div>

          <div className="flex gap-3">
            <button title={t('cmd_enter')} onClick={handleAnalyze} disabled={loading}
              className={`relative flex-1 ${c.btnPrimary} font-medium py-3 rounded-lg flex items-center justify-center gap-2 min-h-[48px]`}>
              {loading
                ? <><span className="animate-spin inline-block">{tool?.icon ?? '📱'}</span> {t('cc_analyzing')}</>
                : <><span>{tool?.icon ?? '📱'}</span> {t('cc_analyze')}</>}
            {!loading && (
              <kbd aria-hidden="true"
                className="hidden sm:flex items-center absolute end-3 top-1/2 -translate-y-1/2 px-1.5 py-0.5 rounded border border-white/30 bg-white/15 text-[10px] font-bold tracking-wide">
                ⌘↵
              </kbd>
            )}
            </button>
          </div>

          {!receivedMessage.trim() && !loading && (
            <div className="flex justify-center">
              <button
                onClick={() => {
                  setReceivedMessage("Fine. Whatever. I guess I'll just handle it myself like I always do. Don't worry about it.");
                  setRelationship('Partner');
                  setPersonLabel('Alex');
                  setActualGoal('Reconnect without escalating');
                  setEmotionalState({ angry: false, hurt: true, defensive: true, frustrated: false, calm: false, confused: false });
                  setGoal('');
                }}
                className={`text-xs font-medium ${c.accentTxt} underline underline-offset-2 min-h-[32px]`}
              >
              </button>
            </div>
          )}

          {error && (
            <div className={`p-4 ${c.danger} border rounded-lg flex items-start gap-3`}>
              <span>⚠️</span><p className="text-sm">{error}</p>
            </div>
          )}
        </div>
      </div>

      {/* ═══════════════════════════════════════════════════════
          RESULTS
          ═══════════════════════════════════════════════════════ */}
      {results && (
        <div data-copy-results ref={resultsRef} className="space-y-4">

          {/* Triggers */}
          {results.message_analysis?.triggers_identified?.length > 0 && (
            <div className={`${c.card} border ${c.border} rounded-xl p-5`}>
              <h3 className={`font-bold mb-3 ${c.text}`}>{t('cc_triggers_title')}</h3>
              <ul className={`text-sm space-y-1 ${c.text}`}>{results.message_analysis.triggers_identified.map((trig, i) => <li key={i}>• "{trig}"</li>)}</ul>
              {results.message_analysis.whats_being_asked && (
                <p className={`text-sm mt-3 ${c.textSecondary}`}>{results.message_analysis.whats_being_asked}</p>
              )}
            </div>
          )}

          {/* Draft Analysis */}
          {results.draft_analysis && userDraft && (
            <div className={`${c.card} border ${c.border} rounded-xl p-6`}>
              <h3 className={`text-lg font-bold mb-3 ${c.text}`}>🚨 {t('cc_draftanalysis_title')}</h3>
              <p className={`text-sm mb-3 ${c.textSecondary}`}>{results.draft_analysis.overall_assessment}</p>
              {results.draft_analysis.tone_flags?.length > 0 && (
                <div className="mb-3">
                  <p className={`text-sm font-bold mb-2 ${c.text}`}>{t('cc_draftanalysis_toneflags')}:</p>
                  {results.draft_analysis.tone_flags.map((f, i) => (
                    <div key={i} className={`p-2 rounded mb-1 ${c.draftFlag}`}><p className="text-sm"><strong>{f.flag}</strong>: {f.why_problematic}</p></div>
                  ))}
                </div>
              )}
              {results.draft_analysis.problematic_phrases?.length > 0 && (
                <div className="mb-3">
                  <p className={`text-sm font-bold mb-2 ${c.text}`}>🔍 {t('cc_draftanalysis_problematic')}:</p>
                  {results.draft_analysis.problematic_phrases.map((p, i) => (
                    <div key={i} className={`p-2 rounded mb-1 ${c.draftFlag}`}>
                      <p className="text-sm font-semibold">"{p.phrase}"</p>
                      <p className={`text-xs ${c.textSecondary}`}>{p.issue}</p>
                      {p.better_version && <p className={`text-xs ${c.success} mt-0.5`}>→ "{p.better_version}"</p>}
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* Response Strategies + Tone Slider */}
          {results.response_strategies?.length > 0 && (
            <div className={`${c.card} border ${c.border} rounded-xl p-6`}>
              <h3 className={`text-lg font-bold ${c.text} mb-4 flex items-center gap-2`}>
                {delayActive ? <span className={c.lockIcon}>🔒</span> : <span className={c.unlockIcon}>🔓</span>} {t('cc_strategies_title')}
                {delayActive && <span className={`text-sm font-normal ${c.textMuteded}`}>({t('cc_locked')})</span>}
              </h3>
              <div className={`space-y-4 ${c.text}`}>
                {results.response_strategies.map((s, idx) => (
                  <div key={idx} className={`border-2 rounded-lg p-5 transition-colors ${delayActive ? 'opacity-50' : selectedStrategyIdx === idx ? c.strategySelected : c.strategyHover}`}>
                    <div className="mb-2">
                      <h4 className={`font-bold ${c.text}`}>{s.strategy}</h4>
                      {s.tone && <span className={`text-xs px-2 py-0.5 rounded ${c.toneBadge}`}>{t('cc_tone')}: {s.tone}</span>}
                    </div>
                    <div className={`p-3 rounded ${c.strategyText} mb-2`}>
                      <p className={`${c.text} font-medium`}>"{s.response_text}"</p>
                    </div>

                    {!delayActive && (
                      <div className="mt-3">
                        <button
                          onClick={() => { setSelectedStrategyIdx(selectedStrategyIdx === idx ? null : idx); setAdjustedResponse(null); setToneLevel(50); }}
                          className={`text-xs ${linkStyle}`}>
                          {selectedStrategyIdx === idx ? <><Caret open /> {t('cc_hide_tone')}</> : `🎚️ ${t('cc_adjust_tone')}`}
                        </button>
                        {selectedStrategyIdx === idx && (
                          <div className={`mt-2 p-3 rounded ${c.toneSlider}`}>
                            <div className="flex items-center gap-3 mb-2">
                              <span className="text-xs">🕊️ {t('cc_gentle')}</span>
                              <input type="range" min="0" max="100" value={toneLevel}
                                onChange={e => setToneLevel(parseInt(e.target.value))} className="flex-1" />
                              <span className="text-xs">💪 {t('cc_firm')}</span>
                            </div>
                            <button onClick={handleAdjustTone} disabled={toneLoading}
                              className={`${c.btnPrimary} px-4 py-2 rounded text-sm w-full disabled:opacity-40`}>
                              {toneLoading ? <span className="animate-spin inline-block">{tool?.icon ?? '📱'}</span> : t('cc_regenerate', { level: toneLevel })}
                            </button>
                            {adjustedResponse && (
                              <div className="mt-2">
                                <div className={`p-3 rounded border ${c.border} ${c.toneAdjusted}`}>
                                  <p className={`text-sm ${c.text}`}>"{adjustedResponse.adjusted_text}"</p>
                                </div>
                                {adjustedResponse.tone_note && <p className={`text-xs mt-1 ${c.textMuteded}`}>{adjustedResponse.tone_note}</p>}
                              </div>
                            )}
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Follow-up Q&A */}
          <div className={`${c.card} border ${c.border} rounded-xl p-5`}>
            <h3 className={`font-bold mb-3 ${c.text}`}>💬 {t('cc_followup_title')}</h3>
            <p className={`text-xs mb-3 ${c.textMuteded}`}>{t('cc_followup_intro')}</p>
            {followupHistory.length > 0 && (
              <div className="space-y-3 mb-4">
                {followupHistory.map((f, i) => (
                  <div key={i} className="space-y-1">
                    <div className={`p-3 rounded ${c.followupMe}`}>
                      <p className={`text-xs font-semibold ${c.textMuteded}`}>{t('cc_you')}:</p>
                      <p className={`text-sm ${c.text}`}>{f.question}</p>
                    </div>
                    <div className={`p-3 rounded ${c.cardAlt}`}>
                      <p className={`text-sm ${c.textSecondary}`}>{f.answer}</p>
                    </div>
                  </div>
                ))}
              </div>
            )}
            <div className="flex gap-2" ref={followupRef}>
              <label htmlFor="cc-followup-q" className="sr-only">{t('cc_followup_aria')}</label>
              <input id="cc-followup-q" type="text" value={followupQuestion} onChange={e => setFollowupQuestion(e.target.value)}
                placeholder={t('cc_followup_ph')}
                className={`flex-1 p-3 border rounded-lg ${c.input}`}
                onKeyDown={e => { if (e.key === 'Enter') handleFollowup(); }} />
              <button onClick={handleFollowup} disabled={followupLoading || !followupQuestion.trim()}
                className={`${c.btnPrimary} px-4 py-2 rounded-lg disabled:opacity-40`}>
                {followupLoading ? <span className="animate-spin inline-block">{tool?.icon ?? '📱'}</span> : '➤'}
              </button>
            </div>
          </div>

          {/* Cross-refs (post-result) */}
          <div className="text-center space-y-1">
            <p className={`text-xs ${c.textMuted}`}>{t('cc_xref_firm_q')} <a href="/VelvetHammer" className={linkStyle}>🔨 {t('cc_xref_velvethammer')}</a></p>
            {results.message_analysis?.emotional_temperature === 'high' && (
              <p className={`text-xs ${c.textMuted}`}>{t('cc_xref_spiral_q')} → <a href="/SpiralStopper" className={linkStyle}>🌀 {t('cc_xref_spiralstopper')}</a></p>
            )}
          </div>

          {/* AI disclaimer */}
          <div className={`p-4 rounded-xl text-center ${c.cardAlt}`}>
            <p className={`text-xs ${c.textMuteded}`}>💬 {t('cc_disclaimer')}</p>
          </div>
        </div>
      )}

      {/* Confirm Send Modal */}
      {showConfirmSend && selectedResponse && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center p-4 z-50" onClick={() => setShowConfirmSend(false)}>
          <div className={`${c.card} border-2 border-cyan-500 rounded-xl p-6 max-w-md w-full`} onClick={e => e.stopPropagation()}>
            <h3 className={`text-lg font-bold mb-4 ${c.text}`}>⚠️ {t('cc_confirm_title')}</h3>
            <ul className={`text-sm space-y-1 mb-4 ${c.text}`}>
              <li>• {t('cc_confirm_q1')}</li>
              <li>• {t('cc_confirm_q2')}</li>
              <li>• {t('cc_confirm_q3')}</li>
              <li>• {t('cc_confirm_q4')}</li>
            </ul>
            <div className={`p-3 rounded ${c.confirmModal} mb-4`}>
              <p className={`text-sm ${c.text}`}>"{selectedResponse}"</p>
            </div>
            <div className="flex gap-3">
              <button onClick={handleConfirmCopy} className={`flex-1 ${c.btnPrimary} py-3 rounded-lg font-semibold`}>{t('cc_confirm_yes')}</button>
              <button onClick={() => { setShowConfirmSend(false); setSelectedResponse(null); }} className={`flex-1 ${c.btnSecondary} py-3 rounded-lg`}>{t('cc_confirm_wait')}</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

ConflictCoach.displayName = 'ConflictCoach';
export default ConflictCoach;
