import React, { useMemo, useState, useRef, useEffect, useCallback } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';
import { pickExample } from '../utils/exampleRotation';
import { tools } from '../data/tools';
import Caret from '../components/Caret';

// Local date, not toISOString(): that converts to UTC first, so west of
// Greenwich an evening check-in lands on tomorrow. This log is a record of
// the visitor's day, which is the local one.
const today = () => {
  const d = new Date();
  const pad = n => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
};

// Chip key → locale key. Derived labels ("brainFog" → "Brain Fog") read
// fine in English and are English everywhere else; nothing flags them,
// because there is no literal to flag.
const CHIP_LABELS = {
  work: 'cpr_act_work', social: 'cpr_act_social', exercise: 'cpr_act_exercise',
  rest: 'cpr_act_rest', obligations: 'cpr_act_obligations',
  headache: 'cpr_sym_headache', fatigue: 'cpr_sym_fatigue', tension: 'cpr_sym_tension',
  appetiteChanges: 'cpr_sym_appetite', sleepIssues: 'cpr_sym_sleep_issues',
  irritability: 'cpr_warn_irritability', brainFog: 'cpr_warn_brain_fog',
  difficultyDeciding: 'cpr_warn_cant_decide', cryingEasily: 'cpr_warn_crying',
  withdrawing: 'cpr_warn_withdrawing',
};

const EMPTY_ENTRY = {
  date: today(),
  energy: 5,
  sleep: 5,
  stress: 5,
  mood: 5,
  activities: { work: false, social: false, exercise: false, rest: false, obligations: false },
  physicalSymptoms: { headache: false, fatigue: false, tension: false, appetiteChanges: false, sleepIssues: false },
  warningSigns: { irritability: false, brainFog: false, difficultyDeciding: false, cryingEasily: false, withdrawing: false },
  customSymptoms: [],
  caffeine: 0,
  alcohol: 0,
  medications: '',
  menstrualPhase: 'na',
  notes: '',
  biometrics: { hrv: '', restingHR: '', sleepHours: '', steps: '' },
  weather: { condition: '', barometricPressure: '' },
  crashDay: false,
};

const clamp = n => Math.max(1, Math.min(10, Number(n) || 1));

function Metric({ label, value, onChange, low, high }) {
  return (
    <label className="block">
      <div className="flex justify-between gap-3 text-sm font-medium mb-1">
        <span>{label}</span><span>{value}/10</span>
      </div>
      <input
        type="range" min="1" max="10" value={value}
        onChange={e => onChange(clamp(e.target.value))}
        className="w-full min-h-[44px]"
      />
      {/* Scale markers. The number pair above tells you where you are; without
          these there is nothing telling you how far 7 is from 4 (owner,
          2026-08-26). Rendered with the inherited colour at two opacities so
          the row needs no palette and works in both themes. */}
      <div className="flex justify-between px-0.5 text-[10px] tabular-nums leading-none" aria-hidden="true">
        {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map(n => (
          <span key={n} className={n === value ? 'font-bold opacity-100' : 'opacity-40'}>{n}</span>
        ))}
      </div>
      <div className="mt-1 flex justify-between text-xs opacity-60"><span>{low}</span><span>{high}</span></div>
    </label>
  );
}

function ToggleChip({ active, onClick, children }) {
  return (
    <button
      type="button" onClick={onClick}
      className={`min-h-[44px] rounded-full border px-4 py-2 text-sm ${active ? 'font-semibold ring-2 ring-offset-1' : ''}`}
    >
      {children}
    </button>
  );
}

function Section({ title, children }) {
  return (
    <section className="rounded-xl border p-4 md:p-5">
      <h3 className="font-bold mb-3">{title}</h3>
      {children}
    </section>
  );
}

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

export default function CrashPredictor() {
  const { callToolEndpoint, loading } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();

  // PF-14 / PF-11: the palette before any state, useState before
  // usePersistentState. The keys are the house set — a tool with its own
  // vocabulary (muted, soft) cannot be restyled with the rest of the catalog.
  const c = {
    text:          isDark ? 'text-zinc-100' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-700',
    textMuted:     isDark ? 'text-zinc-400' : 'text-gray-500',
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/40' : 'bg-slate-50',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100' : 'bg-white border-gray-300 text-gray-900',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    deleteHover:   isDark ? 'hover:text-red-400' : 'hover:text-red-600',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-300 text-red-800',
    required:      isDark ? 'text-amber-400' : 'text-amber-700',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';

  const tool = tools.find(x => x.id === 'CrashPredictor');

  const [entry, setEntry] = useState({ ...EMPTY_ENTRY });
  const [view, setView] = useState('dashboard');
  const [analysis, setAnalysis] = useState(null);
  const [patterns, setPatterns] = useState(null);
  const [showMore, setShowMore] = useState(false);
  // Checked rows in History, keyed by date — save() dedupes on date, so
  // a date identifies exactly one entry.
  const [checked, setChecked] = useState([]);
  const submitRef = useRef(null);
  const canSubmitRef = useRef(false);

  const [logs, setLogs] = usePersistentState('crashpredictor-v2-logs', []);

  const results = analysis || patterns;
  const latest = logs[0];
  const markedCrashCount = useMemo(() => logs.filter(l => l.crashDay).length, [logs]);

  // True once the visitor has put something into today's draft. `date` is
  // pre-filled, so it is excluded — otherwise the draft is dirty on arrival.
  const entryDirty = useMemo(() => {
    const blank = { ...EMPTY_ENTRY };
    return Object.keys(blank).some(k =>
      k !== 'date' && JSON.stringify(entry[k]) !== JSON.stringify(blank[k]));
  }, [entry]);

  // Start over clears the working state, never the log — that is what the
  // reset control means everywhere else in the catalog. Deleting saved
  // history is a separate, confirmed action in the History view.
  const canReset = Boolean(analysis || patterns || entryDirty || view !== 'dashboard');

  const reset = () => {
    setEntry({ ...EMPTY_ENTRY, date: today() });
    setAnalysis(null);
    setPatterns(null);
    setChecked([]);
    setView('dashboard');
  };

  const toggleChecked = (date) => setChecked(prev =>
    prev.includes(date) ? prev.filter(d => d !== date) : [...prev, date]);

  const clearChecked = () => {
    if (!checked.length) return;
    const ask = checked.length === 1
      ? t('cpv2_clear_checked_confirm_1')
      : t('cpv2_clear_checked_confirm', { n: checked.length });
    if (!window.confirm(ask)) return;
    setLogs(prev => prev.filter(l => !checked.includes(l.date)));
    setChecked([]);
    // Both readings describe a history that no longer exists.
    setAnalysis(null);
    setPatterns(null);
  };

  const update = (key, value) => setEntry(prev => ({ ...prev, [key]: value }));
  const toggleNested = (group, key) => setEntry(prev => ({
    ...prev,
    [group]: { ...prev[group], [key]: !prev[group]?.[key] }
  }));

  const save = () => {
    const summary = [`E${entry.energy}`, `S${entry.sleep}`, `St${entry.stress}`, `M${entry.mood}`].join(' · ');
    const stamp = entry.date || today();
    const next = [{ ...entry, date: stamp, preview: entry.notes?.slice(0, 40) || summary }, ...logs.filter(l => l.date !== stamp)]
      .sort((a, b) => String(b.date).localeCompare(String(a.date)));
    setLogs(next);
    setEntry({ ...EMPTY_ENTRY, date: today() });
    setView('dashboard');
    setAnalysis(null);
    setPatterns(null);
  };

  // House scaffolding the rewrite did not carry over: a demo path, a copy
  // payload with the branding line, the Cmd+Enter shortcut, and the disclaimer.
  const loadExample = () => {
    const ex = pickExample('CrashPredictor', [
      { energy: 4, sleep: 5, stress: 7, mood: 4, notes: 'Third late night this week. Ran out of steam mid-afternoon.' },
      { energy: 7, sleep: 8, stress: 3, mood: 7, notes: 'Slept properly, walked at lunch, felt like myself.' },
    ]);
    setEntry({ ...EMPTY_ENTRY, date: today(), ...ex });
    setView('checkin');
  };

  const buildFullText = useCallback(() => {
    if (!logs.length) return '';
    const lines = [`⚡ ${t('cpv2_today')}`, ''];
    logs.slice(0, 20).forEach(l => {
      lines.push(`${l.date} — ${t('cpv2_energy')} ${l.energy} ${t('cpv2_sleep')} ${l.sleep} ${t('cpv2_stress')} ${l.stress} ${t('cpv2_mood')} ${l.mood}${l.crashDay ? ` · ${t('cpv2_marked_short')}` : ''}`);
      if (l.notes) lines.push(`   ${l.notes}`);
    });
    if (analysis?.headline) lines.push('', `${t('cpv2_recent_pattern')}: ${analysis.headline}`);
    if (patterns?.headline) lines.push('', `${t('cpv2_longterm')}: ${patterns.headline}`);
    return lines.join('\n') + BRAND;
  }, [logs, analysis, patterns, t]);

  useRegisterActions(buildFullText(), tool?.title || 'Crash Predictor');

  useEffect(() => {
    const handler = (e) => {
      if (e.target.tagName === 'SELECT') return;
      if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') {
        e.preventDefault();
        if (canSubmitRef.current) submitRef.current?.();
      }
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, []);

  submitRef.current = save;
  canSubmitRef.current = view === 'checkin' && !loading;

  const analyze = async () => {
    if (logs.length < 2) return;
    const data = await callToolEndpoint('crash-predictor-analyze', { logs: logs.slice(0, 60) });
    setAnalysis(data);
  };

  const analyzePatterns = async () => {
    if (logs.length < 7) return;
    const data = await callToolEndpoint('crash-predictor-patterns', { logs: logs.slice(0, 120) });
    setPatterns(data);
  };

  const metricRows = [
    [t('cpv2_energy'), latest?.energy],
    [t('cpv2_sleep_label'), latest?.sleep],
    [t('cpv2_stress_label'), latest?.stress],
    [t('cpv2_mood_label'), latest?.mood],
  ];

  return (
    <div className={`space-y-4 ${c.text}`}>
      {/* ── Unified header card: icon + tagline + Try an example + reset + tabs ── */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm px-5 pt-2.5 pb-5`}>
        <div className="flex items-start justify-between gap-3 pb-3 border-b border-zinc-500">
          <div className="flex-1 min-w-0">
            {/* PF-30 — the wrapper already prints the name as the page <h1>. */}
            <p className={`text-base ${c.textSecondary}`}>
              <span className="me-2 text-lg">{tool?.icon ?? '⚡'}</span>{t('cpv2_hero')}
            </p>
            {/* PF-17c */}
            <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }}
              className="mt-2 px-4 py-2 rounded-full text-sm font-semibold border border-black/25 text-zinc-900 shadow-sm hover:brightness-105 hover:shadow transition disabled:opacity-40 whitespace-nowrap">
              ✨ {t('try_example')}
            </button>
          </div>
          {canReset ? (
            <button
              onClick={reset}
              className={`shrink-0 px-3 py-2 rounded-lg text-sm font-bold min-h-[40px] ${c.btnSecondary}`}
            >↺ {t('start_over')}</button>
          ) : null}
        </div>

        <div className="flex gap-2 pt-3">
          {[
            ['dashboard', t('cpv2_tab_dashboard')],
            ['checkin', t('cpv2_tab_checkin')],
            ['history', t('cpv2_tab_history')],
          ].map(([key, label]) => (
            <button
              key={key} type="button" onClick={() => setView(key)}
              className={`w-full py-2.5 rounded-lg text-sm font-bold transition-all ${view === key ? c.btnPrimary : c.btnSecondary}`}
            >{label}</button>
          ))}
        </div>
      </div>

      <details className={`group ${c.cardAlt} border ${c.border} rounded-xl p-3`}>
        <summary className="cursor-pointer list-none [&::-webkit-details-marker]:hidden">
          <div className={`flex items-center gap-2 text-xs font-bold ${c.text}`}>
            {t('cpv2_how_title')}
            <Caret groupOpen className="ms-auto" />
          </div>
        </summary>
        <p className={`text-sm mt-2 ${c.textMuted}`}>{t('cpv2_how_body')}</p>
      </details>

      {view === 'dashboard' && (
        <div className="space-y-4">
          {logs.length === 0 ? (
            <Section title={t('cpv2_no_pattern')}>
              <p className={c.textMuted}>{t('cpv2_no_pattern_sub')}</p>
              <button type="button" onClick={() => setView('checkin')} className="mt-4 w-full min-h-[48px] rounded-lg border font-semibold">
                {t('cpv2_start_first')}
              </button>
            </Section>
          ) : (
            <>
              <Section title={t('cpv2_latest')}>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
                  {metricRows.map(([label, value]) => (
                    <div key={label} className={`${c.cardAlt} rounded-lg p-3 text-center`}>
                      <div className="text-xl font-bold">{value ?? '—'}</div>
                      <div className={`text-xs ${c.textMuted}`}>{label}</div>
                    </div>
                  ))}
                </div>
                {latest?.crashDay && <p className="mt-3 text-sm font-medium">{t('cpv2_marked_crash_note')}</p>}
              </Section>

              <Section title={t('cpv2_recent_pattern')}>
                {analysis ? (
                  <div className="space-y-4">
                    <p className="font-semibold">{analysis.headline}</p>

                    {!!analysis.recent_changes?.length && (
                      <div>
                        <h4 className="text-sm font-bold mb-2">{t('cpv2_what_changed')}</h4>
                        <div className="space-y-2">
                          {analysis.recent_changes.map((x, i) => (
                            <div key={i} className={`${c.cardAlt} rounded-lg p-3`}>
                              <p className="font-medium">{x.signal}</p>
                              <p className="text-sm">{x.observation}</p>
                              <p className={`text-xs mt-1 ${c.textMuted}`}>{x.evidence}</p>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {!!analysis.patterns_worth_noticing?.length && (
                      <div>
                        <h4 className="text-sm font-bold mb-2">{t('cpv2_travel_together')}</h4>
                        <div className="space-y-2">
                          {analysis.patterns_worth_noticing.map((x, i) => (
                            <div key={i} className={`${c.cardAlt} rounded-lg p-3`}>
                              <p className="font-medium">{x.pattern}</p>
                              <p className="text-sm">{x.observation}</p>
                              <p className={`text-xs mt-1 ${c.textMuted}`}>{x.evidence} · {x.confidence_note}</p>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {!!analysis.not_enough_evidence_yet?.length && (
                      <div>
                        <h4 className="text-sm font-bold mb-2">{t('cpv2_worth_watching')}</h4>
                        <ul className="list-disc ps-5 text-sm space-y-1">
                          {analysis.not_enough_evidence_yet.map((x, i) => <li key={i}>{x}</li>)}
                        </ul>
                      </div>
                    )}

                    {analysis.small_experiment?.try && (
                      <div className="rounded-lg border p-3">
                        <p className="text-xs font-bold uppercase tracking-wide">{t('cpv2_try_change')}</p>
                        <p className="font-medium mt-1">{analysis.small_experiment.try}</p>
                        <p className="text-sm mt-2"><strong>{t('cpv2_watch')}</strong> {analysis.small_experiment.watch}</p>
                        <p className={`text-xs mt-1 ${c.textMuted}`}>{analysis.small_experiment.why_this_one}</p>
                      </div>
                    )}
                  </div>
                ) : (
                  <>
                    <p className={c.textMuted}>
                      {logs.length < 2
                        ? t('cpv2_keep_going')
                        : t('cpv2_compare_sub')}
                    </p>
                    <button
                      type="button" onClick={analyze} disabled={loading || logs.length < 2}
                      className="mt-4 w-full min-h-[48px] rounded-lg border font-semibold disabled:opacity-40"
                    >
                      {loading ? t('cpv2_comparing') : t('cpv2_compare_cta')}
                    </button>
                  </>
                )}
              </Section>

              {logs.length >= 7 && (
                <Section title={t('cpv2_longterm')}>
                  {patterns ? (
                    <div className="space-y-3">
                      <p className="font-semibold">{patterns.headline}</p>
                      {(patterns.recurring_patterns || []).map((x, i) => (
                        <div key={i} className={`${c.cardAlt} rounded-lg p-3`}>
                          <p className="font-medium">{x.pattern}</p>
                          <p className="text-sm">{x.evidence}</p>
                          <p className={`text-xs mt-1 ${c.textMuted}`}>{x.limits}</p>
                        </div>
                      ))}
                      {!!patterns.before_marked_crash_days?.length && (
                        <div>
                          <h4 className="text-sm font-bold mb-2">{t('cpv2_before_crash')}</h4>
                          {patterns.before_marked_crash_days.map((x, i) => (
                            <div key={i} className={`${c.cardAlt} rounded-lg p-3 mb-2`}>
                              <p className="text-sm">{x.observation}</p>
                              <p className={`text-xs mt-1 ${c.textMuted}`}>{x.evidence}</p>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  ) : (
                    <>
                      <p className={c.textMuted}>
                        {t('cpv2_longterm_sub')}{markedCrashCount ? ' ' + (markedCrashCount === 1 ? t('cpv2_crash_days_1') : t('cpv2_crash_days_n', { n: markedCrashCount })) : ''}
                      </p>
                      <button type="button" onClick={analyzePatterns} disabled={loading} className="mt-4 w-full min-h-[48px] rounded-lg border font-semibold disabled:opacity-40">
                        {t('cpv2_longterm_cta')}
                      </button>
                    </>
                  )}
                </Section>
              )}
            </>
          )}
        </div>
      )}

      {view === 'checkin' && (
        <div className="space-y-4">
          <Section title={t('cpv2_today')}>
            <p className={`text-xs -mt-1 mb-4 ${c.textMuted}`}>{t('cpv2_replace_note')}</p>
            <div className="space-y-4">
              <Metric label={t('cpv2_energy')} value={entry.energy} onChange={v => update('energy', v)} low={t('cpv2_energy_low')} high={t('cpv2_energy_high')} />
              <Metric label={t('cpv2_sleep_label')} value={entry.sleep} onChange={v => update('sleep', v)} low={t('cpv2_sleep_low')} high={t('cpv2_sleep_high')} />
              <Metric label={t('cpv2_stress_label')} value={entry.stress} onChange={v => update('stress', v)} low={t('cpv2_stress_low')} high={t('cpv2_stress_high')} />
              <Metric label={t('cpv2_mood_label')} value={entry.mood} onChange={v => update('mood', v)} low={t('cpv2_mood_low')} high={t('cpv2_mood_high')} />

              <div>
                <p className="text-sm font-medium mb-2">{t('cpv2_part_of_today')}</p>
                <div className="flex flex-wrap gap-2">
                  {Object.keys(entry.activities).map(k => (
                    <ToggleChip key={k} active={entry.activities[k]} onClick={() => toggleNested('activities', k)}>
                      {t(CHIP_LABELS[k])}
                    </ToggleChip>
                  ))}
                </div>
              </div>

              <div>
                <p className="text-sm font-medium mb-2">{t('cpv2_noticed')}</p>
                <div className="flex flex-wrap gap-2">
                  {[...Object.keys(entry.physicalSymptoms), ...Object.keys(entry.warningSigns)].map(k => {
                    const group = Object.prototype.hasOwnProperty.call(entry.physicalSymptoms, k) ? 'physicalSymptoms' : 'warningSigns';
                    return <ToggleChip key={k} active={entry[group][k]} onClick={() => toggleNested(group, k)}>{t(CHIP_LABELS[k])}</ToggleChip>;
                  })}
                </div>
              </div>

              <label className="block">
                <span className="text-sm font-medium">{t('cpv2_notes')} <span className={c.textMuted}>{t('cpv2_optional')}</span></span>
                <textarea
                  value={entry.notes} onChange={e => update('notes', e.target.value)}
                  placeholder={t('cpv2_notes_ph')}
                  rows={3} className={`mt-1 w-full rounded-lg border p-3 text-base ${c.input}`}
                />
              </label>

              <label className="flex items-start gap-3 rounded-lg border p-3">
                <input type="checkbox" checked={entry.crashDay} onChange={e => update('crashDay', e.target.checked)} className="mt-1 h-5 w-5" />
                <span>
                  <span className="font-medium block">{t('cpv2_crashed')}</span>
                  <span className={`text-xs ${c.textMuted}`}>{t('cpv2_crashed_hint')}</span>
                </span>
              </label>

              <button type="button" onClick={() => setShowMore(!showMore)} className="text-sm underline underline-offset-2">
                {showMore ? 'Hide optional details' : 'Add optional details'}
              </button>

              {showMore && (
                <div className="space-y-4 rounded-lg border p-4">
                  <div className="grid grid-cols-2 gap-3">
                    <label className="text-sm">{t('cpv2_caffeine')}<input type="number" min="0" value={entry.caffeine} onChange={e => update('caffeine', Number(e.target.value))} className={`mt-1 w-full rounded-lg border p-2 ${c.input}`} /></label>
                    <label className="text-sm">{t('cpv2_alcohol')}<input type="number" min="0" value={entry.alcohol} onChange={e => update('alcohol', Number(e.target.value))} className={`mt-1 w-full rounded-lg border p-2 ${c.input}`} /></label>
                  </div>
                  <label className="block text-sm">{t('cpv2_medication')}<input value={entry.medications} onChange={e => update('medications', e.target.value)} className={`mt-1 w-full rounded-lg border p-2 ${c.input}`} /></label>
                  <div className="grid grid-cols-2 gap-3">
                    {[
                      ['hrv', 'HRV'],
                      ['restingHR', 'Resting heart rate'],
                      ['sleepHours', 'Sleep hours'],
                      ['steps', 'Steps'],
                    ].map(([key, label]) => (
                      <label key={key} className="text-sm">{label}
                        <input type="number" value={entry.biometrics[key]} onChange={e => setEntry(p => ({ ...p, biometrics: { ...p.biometrics, [key]: e.target.value } }))} className={`mt-1 w-full rounded-lg border p-2 ${c.input}`} />
                      </label>
                    ))}
                  </div>
                  <p className={`text-xs ${c.textMuted}`}>{t('cpv2_optional_note')}</p>
                </div>
              )}

              <button type="button" onClick={save} disabled={loading}
                className={`w-full min-h-[48px] rounded-lg font-semibold flex items-center justify-center gap-2 ${c.btnPrimary}`}>
                {loading
                  ? <><span className="animate-spin inline-block">{tool?.icon ?? '⚡'}</span> {t('cpv2_save')}</>
                  : t('cpv2_save')}
              </button>
            </div>
          </Section>
        </div>
      )}

      {view === 'history' && (
        <Section title={logs.length === 1 ? t('cpv2_history_1') : t('cpv2_history_n', { n: logs.length })}>
          {logs.length === 0 ? (
            <p className={c.textMuted}>{t('cpv2_no_checkins')}</p>
          ) : (
            <div className="space-y-2">
              {logs.map((log, i) => (
                <label key={`${log.date}-${i}`} className={`${c.cardAlt} rounded-lg p-3 flex items-start gap-3 cursor-pointer`}>
                  <input
                    type="checkbox"
                    className="mt-1 h-5 w-5 shrink-0"
                    checked={checked.includes(log.date)}
                    onChange={() => toggleChecked(log.date)}
                    aria-label={t('cpv2_select_row', { date: log.date })}
                  />
                  <span className="flex-1 min-w-0">
                    <span className="flex items-center justify-between gap-3">
                      <strong>{log.date}</strong>
                      {log.crashDay && <span className="text-xs font-semibold">{t('cpv2_marked_short')}</span>}
                    </span>
                    <span className={`block text-sm mt-1 ${c.textMuted}`}>
                      {t('cpv2_energy')} {log.energy} {t('cpv2_sleep')} {log.sleep} {t('cpv2_stress')} {log.stress} {t('cpv2_mood')} {log.mood}
                    </span>
                    {log.notes && <span className="block text-sm mt-2">{log.notes}</span>}
                  </span>
                </label>
              ))}
              {checked.length > 0 && (
                <button
                  type="button"
                  onClick={clearChecked}
                  className={`w-full mt-1 text-center text-xs font-semibold ${c.btnSecondary} ${c.deleteHover} py-1.5 rounded-lg`}
                >{t('cpv2_clear_checked')}</button>
              )}
            </div>
          )}
        </Section>
      )}

      {!results && (
        <p className={`text-xs text-center px-4 ${c.textMuted}`}>
          {t('cpv2_xref_pre')} <a href="/PEP" className={linkStyle}>✨ {t('cpr_xref_pep')}</a>
        </p>
      )}

      {results && (
        <div className={`${c.cardAlt} border ${c.border} rounded-xl p-3 text-center`}>
          <p className={`text-xs ${c.textMuted}`}>
            {t('cpv2_xref_post')}{' '}
            <a href="/SpiralStopper" className={linkStyle}>🌀 {t('cpr_xref_spiral')}</a>{' · '}
            <a href="/PEP" className={linkStyle}>✨ {t('cpr_xref_pep')}</a>
          </p>
        </div>
      )}

      <p className={`text-xs text-center px-4 ${c.textMuted}`}>
        {t('cpv2_disclaimer')}
      </p>
    </div>
  );
}

CrashPredictor.displayName = 'CrashPredictor';
