import React, { useState, useEffect, useRef, useCallback } from 'react';
import { useTheme } from '../hooks/useTheme';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

// Maps archetype emoji → c object key (approved color families only)
// Five distinct voice colors are a core function of this tool — documented exception
const ARCHETYPE_KEY = {
  '🔧': 'archetypePragmatist',
  '🎲': 'archetypeRisk',
  '🪞': 'archetypeRegret',
  '🕰️': 'archetypeWait',
  '🔄': 'archetypeContrarian',
};

const CrowdWisdom = ({ tool }) => {
  const { isDark } = useTheme();
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { t } = useTranslation();

  // Example questions — localized seed text.
  const EXAMPLE_QUESTIONS = [
    { q: t('cw_ex1_q'), ctx: t('cw_ex1_ctx') },
    { q: t('cw_ex2_q'), ctx: t('cw_ex2_ctx') },
    { q: t('cw_ex3_q'), ctx: t('cw_ex3_ctx') },
    { q: t('cw_ex4_q'), ctx: t('cw_ex4_ctx') },
    { q: t('cw_ex5_q'), ctx: t('cw_ex5_ctx') },
  ];


  const c = {
    card:                isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:             isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:               isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20'
                                : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:                isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary:       isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:           isDark ? 'text-zinc-400' : 'text-gray-500',
    labelText:           isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:           isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:          isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white'
                                : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:        isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200'
                                : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:              isDark ? 'border-zinc-700' : 'border-gray-200',
    success:             isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200'
                                : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:             isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200'
                                : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:              isDark ? 'bg-red-900/20 border-red-700 text-red-200'
                                : 'bg-red-50 border-red-200 text-red-800',
    infoBox:             isDark ? 'bg-sky-900/20 border-sky-700 text-sky-200'
                                : 'bg-sky-50 border-sky-200 text-sky-800',
    successBox:          isDark ? 'bg-emerald-900/20 border-emerald-700' : 'bg-emerald-50 border-emerald-300',
    successTxt:          isDark ? 'text-emerald-300' : 'text-emerald-800',
    warningBox:          isDark ? 'bg-amber-900/20 border-amber-700' : 'bg-amber-50 border-amber-300',
    warningTxt:          isDark ? 'text-amber-300' : 'text-amber-800',
    pillActive:          isDark ? 'border-cyan-500 bg-cyan-900/30 text-cyan-200'
                                : 'border-cyan-600 bg-cyan-100 text-cyan-900',
    pillInactive:        isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500'
                                : 'border-gray-300 text-gray-500 hover:border-gray-400',
    required:            isDark ? 'text-amber-400' : 'text-amber-700',
    // Bespoke — five distinct archetype voice colors (documented exception to color family limit)
    archetypePragmatist: isDark ? 'bg-zinc-800 border-zinc-600' : 'bg-slate-50 border-slate-300',
    archetypeRisk:       isDark ? 'bg-amber-900/20 border-amber-700' : 'bg-amber-50 border-amber-300',
    archetypeRegret:     isDark ? 'bg-red-900/20 border-red-700' : 'bg-red-50 border-red-200',
    archetypeWait:       isDark ? 'bg-sky-900/20 border-sky-700' : 'bg-sky-50 border-sky-200',
    archetypeContrarian: isDark ? 'bg-emerald-900/20 border-emerald-700' : 'bg-emerald-50 border-emerald-200',
    quoteInner:          isDark ? 'bg-zinc-700/60' : 'bg-slate-100',
    tensionBg:           isDark ? 'bg-amber-900/20 border-amber-700' : 'bg-amber-50 border-amber-300',
    tensionLabel:        isDark ? 'text-amber-400' : 'text-amber-700',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';


  // ─── State ───
  const [error, setError] = useState('');
  const [expanded, setExpanded] = useState({});

  const [question, setQuestion] = usePersistentState('crowd-wisdom-question', '');
  const [context, setContext] = usePersistentState('crowd-wisdom-context', '');
  const [results, setResults] = usePersistentState('crowd-wisdom-results', null);
  const [sessionHistory, setSessionHistory] = usePersistentState('crowd-wisdom-history', []);

  // ─── Refs ───
  const resultsRef = useRef(null);
  const handleRef = useRef(null);
  const canSubmitRef = useRef(false);

  // Scroll to results when they load
  useEffect(() => {
    if (results && resultsRef.current) {
      resultsRef.current.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }, [results]);

  // Keyboard: Cmd/Ctrl+Enter to submit
  useEffect(() => {
    const handler = (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'Enter' && canSubmitRef.current)
        handleRef.current?.();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, []);

  const toggle = (key) => setExpanded(p => ({ ...p, [key]: !p[key] }));

  const handleSubmit = async () => {
    if (!question.trim()) return;
    setError(''); setResults(null);
    try {
      const data = await callToolEndpoint('crowd-wisdom', {
        question: question.trim(),
        context: context.trim() || undefined,
        userLocale, userCurrency, userRegion,
      });
      setResults(data);
      setSessionHistory(p => [{
        // PF-25 exception: 40-char preview-text truncation; session history is capped at 6.
        preview: question.trim().slice(0, 40),
        question: question.trim(),
        context: context.trim(),
        result: data,
        date: new Date().toISOString(),
      }, ...p].slice(0, 6));
    } catch (e) {
      setError(e.message || t('cw_error'));
    }
  };

  const loadExample = () => {
    const ex = EXAMPLE_QUESTIONS[Math.floor(Math.random() * EXAMPLE_QUESTIONS.length)];
    setQuestion(ex.q); setContext(ex.ctx); setResults(null); setError('');
  };

  const handleReset = () => {
    setResults(null); setQuestion(''); setContext(''); setExpanded({}); setError('');
  };

  const buildFullText = useCallback(() => {
    if (!results) return '';
    let out = `👥 ${t('cw_copy_header')}\n\n"${question}"\n\n`;
    if (results.question_reframed) out += `${t('cw_copy_deeper')} ${results.question_reframed}\n\n`;
    results.voices?.forEach(v => {
      out += `${v.emoji} ${v.archetype}\n${v.what_they_say}\n\n${t('cw_copy_uniquely')} ${v.the_truth_only_they_see}\n\n`;
    });
    if (results.the_tension) out += `━━ ${t('cw_copy_tension')} ━━\n${results.the_tension}\n\n`;
    if (results.the_question_nobody_asked) out += `${t('cw_copy_nobody')} ${results.the_question_nobody_asked}\n`;
    return out + BRAND;
  }, [results, question, t]);

  useRegisterActions(buildFullText(), tool?.title || 'Crowd Wisdom');

  handleRef.current = handleSubmit;
  canSubmitRef.current = !loading && !!question.trim();

  return (
    <div className={`space-y-4 ${c.text}`}>

      {/* Header card */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm`}>
        <div className="px-5 pt-5">
          <div className="pb-3 border-b border-zinc-500">
            <div className="flex items-start justify-between gap-3">
              <div>
                <h2 className={`text-xl font-bold ${c.text}`}>
                  <span className="mr-2">{tool?.icon ?? '👥'}</span>{tool?.title ?? 'Crowd Wisdom'}
                </h2>
                <p className={`text-sm ${c.textSecondary}`}>{tool?.tagline ?? t('cw_tagline')}</p>
                <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className={`mt-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium border disabled:opacity-40 ${isDark ? 'text-white border-white/40' : 'text-gray-800 border-transparent'}`}>{t('try_example')}</button>
              </div>
              {(results || question.trim()) && (
                <button onClick={handleReset} className={`${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs font-bold flex-shrink-0`}>
                  ↺ {t('start_over')}
                </button>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Pre-result cross-ref */}
      {!results && (
        <p className={`text-xs ${c.textMuted}`}>
          {t('cw_pre_xref_q')}{' '}
          <a href="/BeliefStressTest" className={linkStyle}>🧪 {t('cw_belief')}</a>
        </p>
      )}

      {/* Input card */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5 space-y-4`}>
        <div className="pb-3 border-b border-zinc-500">
          <h3 className={`font-semibold text-sm ${c.text}`}>{tool?.icon ?? '👥'} {t('cw_your_question')}</h3>
          <p className={`text-xs ${c.textSecondary}`}>{t('cw_subtitle')}</p>
        </div>

        <div>
          <label className={`block text-sm font-semibold mb-1.5 ${c.labelText}`}>
            {t('cw_question_label')} <span className={c.required}>*</span>
          </label>
          <textarea
            value={question}
            onChange={e => setQuestion(e.target.value)}
            placeholder={t('cw_question_ph')}
            rows={3}
            maxLength={500}
            className={`w-full px-4 py-3 rounded-xl border text-sm resize-none ${c.input}`}
          />
        </div>

        <div>
          <label className={`block text-sm font-semibold mb-1.5 ${c.labelText}`}>
            {t('cw_context_label')} <span className={`font-normal ${c.textMuted}`}>{t('cw_context_hint')}</span>
          </label>
          <textarea
            value={context}
            onChange={e => setContext(e.target.value)}
            placeholder={t('cw_context_ph')}
            rows={2}
            maxLength={300}
            className={`w-full px-4 py-3 rounded-xl border text-sm resize-none ${c.input}`}
          />
        </div>

        {error && (
          <div className={`p-3 rounded-xl border text-sm ${c.danger}`}>
            <span className="mr-1">⚠️</span>{error}
          </div>
        )}

        <div>
          <button
            onClick={handleSubmit}
            disabled={loading || !question.trim()}
            className={`w-full py-3 rounded-xl font-bold disabled:opacity-40 ${c.btnPrimary}`}
          >
            {loading
              ? <><span className="animate-spin inline-block mr-2">{tool?.icon ?? '👥'}</span>{t('cw_gathering')}</>
              : <><span className="mr-1">{tool?.icon ?? '👥'}</span>{t('cw_ask')}</>}
          </button>
        </div>
        <p className={`text-xs text-center ${c.textMuted}`}>{t('cw_submit_hint')}</p>
      </div>

      {/* History panel */}
      {sessionHistory.length > 0 && !results && (
        <div className={`rounded-xl border p-4 space-y-2 ${c.card} ${c.border}`}>
          <p className={`text-xs font-bold uppercase tracking-wide ${c.textMuted}`}>{t('cw_recent')}</p>
          {sessionHistory.map((h, i) => (
            <button
              key={i}
              onClick={() => { setQuestion(h.question); setContext(h.context); setResults(h.result); setExpanded({}); setError(''); }}
              className={`w-full text-left px-3 py-2 rounded-lg text-xs ${c.cardAlt} ${c.textSecondary} hover:opacity-80`}
            >
              {h.preview}{h.preview?.length >= 40 ? '…' : ''}
            </button>
          ))}
        </div>
      )}

      {/* Results */}
      {results && (
        <div ref={resultsRef} className="space-y-4">

          {/* Question header */}
          <div className={`rounded-xl border p-5 ${c.card} ${c.border}`}>
            <p className={`text-xs font-bold uppercase tracking-wider mb-1 ${c.textMuted}`}>{t('cw_the_question')}</p>
            <p className={`text-base font-semibold ${c.text}`}>"{question}"</p>
            {results.question_reframed && (
              <p className={`text-sm mt-2 italic ${c.textSecondary}`}>
                {t('cw_deeper')} {results.question_reframed}
              </p>
            )}
          </div>

          {/* Five voices */}
          {results.voices?.map((voice, i) => {
            const isOpen = expanded[i];
            const cardKey = ARCHETYPE_KEY[voice.emoji] || 'archetypeContrarian';
            return (
              <div key={i} className={`rounded-xl overflow-hidden border ${c[cardKey]}`}>
                <button onClick={() => toggle(i)} className="w-full text-left p-5">
                  <div className="flex items-start justify-between gap-3">
                    <div className="flex items-center gap-3">
                      <span className="text-2xl">{voice.emoji}</span>
                      <div>
                        <p className={`font-bold ${c.text}`}>{voice.archetype}</p>
                        <p className={`text-xs mt-0.5 ${c.textMuted}`}>{voice.profile}</p>
                      </div>
                    </div>
                    <span className={`flex-shrink-0 text-sm mt-1 ${c.textMuted}`}>{isOpen ? '▲' : '▼'}</span>
                  </div>
                  {!isOpen && (
                    <p className={`text-sm mt-3 leading-relaxed line-clamp-2 ${c.textSecondary}`}>
                      {voice.what_they_say}
                    </p>
                  )}
                </button>
                {isOpen && (
                  <div className={`px-5 pb-5 space-y-3 border-t ${c.border}`}>
                    <div className="pt-3">
                      <p className={`text-xs font-bold uppercase tracking-wider mb-1 ${c.textMuted}`}>{t('cw_what_they_say')}</p>
                      <p className={`text-sm leading-relaxed ${c.text}`}>{voice.what_they_say}</p>
                    </div>
                    {voice.core_belief && (
                      <p className={`text-xs ${c.textMuted} italic`}><span className="font-semibold not-italic">{t('cw_core_belief')}</span> {voice.core_belief}</p>
                    )}
                    <div className={`p-3 rounded-xl ${c.quoteInner}`}>
                      <p className={`text-xs font-bold uppercase tracking-wider mb-1 ${c.textMuted}`}>🔦 {t('cw_only_see')}</p>
                      <p className={`text-sm ${c.textSecondary}`}>{voice.the_truth_only_they_see}</p>
                    </div>
                    <div className={`text-xs ${c.textMuted} italic`}>
                      <span className="font-semibold not-italic">{t('cw_blind_spot')}</span> {voice.the_thing_they_might_miss}
                    </div>
                  </div>
                )}
              </div>
            );
          })}

          {/* Tension + closing question */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {results.the_tension && (
              <div className={`rounded-xl border p-4 ${c.tensionBg}`}>
                <p className={`text-xs font-bold uppercase tracking-wider mb-2 ${c.tensionLabel}`}>⚡ {t('cw_tension')}</p>
                <p className={`text-sm ${c.textSecondary}`}>{results.the_tension}</p>
              </div>
            )}
            {results.the_question_nobody_asked && (
              <div className={`rounded-xl border p-4 ${c.card} ${c.border}`}>
                <p className={`text-xs font-bold uppercase tracking-wider mb-2 ${c.textMuted}`}>❓ {t('cw_nobody_asked')}</p>
                <p className={`text-sm italic ${c.textSecondary}`}>{results.the_question_nobody_asked}</p>
              </div>
            )}
          </div>

          {/* AI disclaimer */}
          <p className={`text-xs text-center italic ${c.textMuted}`}>
            {t('cw_disclaimer')}
          </p>

          {/* Post-result cross-refs */}
          <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
            <p className={`text-[10px] font-bold ${c.textMuted} uppercase mb-2`}>🔗 {t('cw_related')}</p>
            <div className="flex flex-wrap gap-3">
              <a href="/DecisionCoach" className={`text-xs ${linkStyle}`}>🎯 {t('cw_decision_coach')}</a>
              <a href="/BeliefStressTest" className={`text-xs ${linkStyle}`}>🧪 {t('cw_belief')}</a>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

CrowdWisdom.displayName = 'CrowdWisdom';
export default CrowdWisdom;
