import React, { useState, useEffect, useRef, useCallback } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

const TRIP_PURPOSES = [
  { id: 'tourism',  labelKey: 'cb_purpose_tourism',  icon: '🏖️' },
  { id: 'business', labelKey: 'cb_purpose_business', icon: '💼' },
  { id: 'family',   labelKey: 'cb_purpose_family',   icon: '👨‍👩‍👧' },
  { id: 'living',   labelKey: 'cb_purpose_living',   icon: '🏠' },
  { id: 'study',    labelKey: 'cb_purpose_study',    icon: '📚' },
  { id: 'remote',   labelKey: 'cb_purpose_remote',   icon: '💻' },
];


const EXAMPLE = {
  destination: 'Japan',
  tripPurpose: 'business',
  duration: '1 week',
  homeCountry: 'United States',
  region: 'Osaka',
  context: 'Vegetarian and don\u2019t drink alcohol; meeting a client\u2019s executive team',
};

function CultureBriefing({ tool }) {
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20'
                          : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-500' : 'text-gray-400',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white'
                          : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200'
                          : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    pillActive:    isDark ? 'border-cyan-500 bg-cyan-900/30 text-cyan-200'
                          : 'border-cyan-600 bg-cyan-100 text-cyan-900',
    pillInactive:  isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500'
                          : 'border-gray-300 text-gray-500 hover:border-gray-400',
    required:      isDark ? 'text-amber-400' : 'text-amber-500',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200'
                          : 'bg-red-50 border-red-200 text-red-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200'
                          : 'bg-amber-50 border-amber-300 text-amber-800',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200'
                          : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    infoBox:       isDark ? 'bg-sky-900/20 border-sky-700 text-sky-200'
                          : 'bg-sky-50 border-sky-200 text-sky-800',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-600 hover:text-cyan-700 underline underline-offset-2';

  const [destination, setDestination]   = useState('');
  const [tripPurpose, setTripPurpose]   = useState('tourism');
  const [duration, setDuration]         = useState('');
  const [homeCountry, setHomeCountry]   = useState('');
  const [region, setRegion]             = useState('');
  const [context, setContext]           = useState('');
  const [results, setResults]           = usePersistentState('culturebriefing-results', null);
  const [sessionHistory, setSessionHistory]           = usePersistentState('culturebriefing-history', []);
  const [error, setError]               = useState('');
  const [activeSection, setActiveSection] = useState(null);

  const resultsRef    = useRef(null);
  const handleBriefRef = useRef(null);
  const canSubmitRef  = useRef(false);

  const canSubmit = destination.trim().length >= 2;

  const handleReset = useCallback(() => {
    setResults(null);
    setError('');
    setDestination('');
    setDuration('');
    setHomeCountry('');
    setTripPurpose('tourism');
    setActiveSection(null);
  }, [setResults]);

  const loadExample = useCallback(() => {
    setDestination(EXAMPLE.destination);
    setTripPurpose(EXAMPLE.tripPurpose);
    setDuration(EXAMPLE.duration);
    setHomeCountry(EXAMPLE.homeCountry);
    setRegion(EXAMPLE.region);
    setContext(EXAMPLE.context);
    setResults(null);
    setError('');
  }, [setResults]);

  const handleBrief = useCallback(async () => {
    if (!canSubmit || loading) return;
    setError('');
    setResults(null);
    setActiveSection(null);

    try {
      const parsed = await callToolEndpoint('culture-briefing', {
        destination: destination.trim(),
        tripPurpose,
        duration: duration.trim() || null,
        homeCountry: homeCountry.trim() || null,
        region: region.trim() || null,
        context: context.trim() || null,
        userLocale,
        userCurrency,
        userRegion,
      });
      setResults({ ...parsed, destination: destination.trim(), tripPurpose });
      // PF-25 exception: keeps the last 8 destination lookups for the history panel.
      setSessionHistory(prev => [{
        destination: destination.trim(),
        tripPurpose,
        preview: destination.trim().slice(0, 40),
        ts: Date.now(),
      }, ...prev].slice(0, 8));
      setActiveSection(parsed?.sections?.[0]?.id ?? null);
    } catch (err) {
      setError(err.message || t('cb_error_generic'));
    }
  }, [canSubmit, loading, destination, tripPurpose, duration, homeCountry, region, context, callToolEndpoint, setResults, setSessionHistory, userLocale, userCurrency, userRegion, t]);

  handleBriefRef.current = handleBrief;
  canSubmitRef.current   = canSubmit;

  const buildFullText = useCallback(() => {
    if (!results) return '';
    const lines = [`${t('cb_copy_header')} — ${results.destination?.toUpperCase()}`, ''];
    if (results.overview) lines.push(results.overview, '');
    results.sections?.forEach(sec => {
      lines.push(`\n${sec.icon ?? '•'} ${sec.title?.toUpperCase()}`);
      sec.dos?.forEach(d => lines.push(`  ✅ ${d}`));
      sec.donts?.forEach(d => lines.push(`  🚫 ${d}`));
      sec.notes?.forEach(n => lines.push(`  ℹ️ ${n}`));
    });
    if (results.insider_tips?.length) {
      lines.push(`\n💡 ${t('cb_copy_insider_tips')}`);
      results.insider_tips.forEach(tip => lines.push(`  • ${tip}`));
    }
    if (results.forgiveness?.forgiven?.length || results.forgiveness?.serious?.length) {
      lines.push(`\n⚖️ ${t('cb_forgiveness_title')}`);
      results.forgiveness?.forgiven?.forEach(x => lines.push(`  🙆 ${x}`));
      results.forgiveness?.serious?.forEach(x => lines.push(`  🚫 ${x}`));
    }
    lines.push(BRAND);
    return lines.join('\n');
  }, [results, t]);

  useRegisterActions(buildFullText(), tool?.title || 'CultureBriefing');

  useEffect(() => {
    if (!results || !resultsRef.current) return;
    const t = setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 200);
    return () => clearTimeout(t);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [results]);

  useEffect(() => {
    const handler = (e) => {
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && !loading && canSubmitRef.current)
        handleBriefRef.current?.();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading]);

  const activeData = results?.sections?.find(s => s.id === activeSection);

  const renderInput = () => (
    <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5 space-y-4`}>
      {/* Destination */}
      <div>
        <label className={`block text-sm font-medium ${c.labelText} mb-1`}>
          {t('cb_destination')} <span className={c.required}>*</span>
        </label>
        <input
          type="text"
          value={destination}
          onChange={e => setDestination(e.target.value)}
          placeholder={t('cb_destination_ph')}
          className={`w-full px-3 py-2.5 border rounded-xl text-sm focus:outline-none focus:ring-2 ${c.input}`}
        />
      </div>

      {/* Region / city */}
      <div>
        <label className={`block text-sm font-medium ${c.labelText} mb-1`}>
          {t('cb_region')} <span className={`text-xs font-normal ${c.textMuted}`}>({t('optional')})</span>
        </label>
        <input
          type="text"
          value={region}
          onChange={e => setRegion(e.target.value)}
          placeholder={t('cb_region_ph')}
          className={`w-full px-3 py-2 border rounded-xl text-sm focus:outline-none focus:ring-2 ${c.input}`}
        />
      </div>

      {/* Trip purpose */}
      <div>
        <label className={`block text-sm font-medium ${c.labelText} mb-2`}>{t('cb_trip_purpose')}</label>
        <div className="flex flex-wrap gap-2">
          {TRIP_PURPOSES.map(tp => (
            <button key={tp.id} onClick={() => setTripPurpose(tp.id)}
              className={`px-3 py-1.5 rounded-lg border text-xs font-medium transition-colors ${tripPurpose === tp.id ? c.pillActive : c.pillInactive}`}>
              <span className="mr-1">{tp.icon}</span>{t(tp.labelKey)}
            </button>
          ))}
        </div>
      </div>

      {/* Duration + Home country */}
      <div className="grid grid-cols-2 gap-3">
        <div>
          <label className={`block text-sm font-medium ${c.labelText} mb-1`}>
            {t('cb_duration')} <span className={`text-xs font-normal ${c.textMuted}`}>({t('optional')})</span>
          </label>
          <input
            type="text"
            value={duration}
            onChange={e => setDuration(e.target.value)}
            placeholder={t('cb_duration_ph')}
            className={`w-full px-3 py-2 border rounded-xl text-sm focus:outline-none focus:ring-2 ${c.input}`}
          />
        </div>
        <div>
          <label className={`block text-sm font-medium ${c.labelText} mb-1`}>
            {t('cb_home_country')} <span className={`text-xs font-normal ${c.textMuted}`}>({t('optional')})</span>
          </label>
          <input
            type="text"
            value={homeCountry}
            onChange={e => setHomeCountry(e.target.value)}
            placeholder={t('cb_home_country_ph')}
            className={`w-full px-3 py-2 border rounded-xl text-sm focus:outline-none focus:ring-2 ${c.input}`}
          />
        </div>
      </div>

      {/* Context / constraints */}
      <div>
        <label className={`block text-sm font-medium ${c.labelText} mb-1`}>
          {t('cb_context')} <span className={`text-xs font-normal ${c.textMuted}`}>({t('optional')})</span>
        </label>
        <textarea
          value={context}
          onChange={e => setContext(e.target.value)}
          placeholder={t('cb_context_ph')}
          rows={2}
          className={`w-full px-3 py-2 border rounded-xl text-sm focus:outline-none focus:ring-2 ${c.input}`}
        />
      </div>

      {error && <p className={`text-sm ${c.danger} border rounded-lg px-3 py-2`}>{error}</p>}

      <p className={`text-xs ${c.textMuted}`}>
        {t('cb_xref_layover_intro')} <a href="/LayoverMaximizer" className={linkStyle}>✈️ {t('cb_layover')}</a> {t('cb_xref_layover_outro')}
      </p>

      <button onClick={handleBrief} disabled={!canSubmit || loading}
        className={`w-full ${c.btnPrimary} disabled:opacity-40 font-bold py-3 rounded-lg flex items-center justify-center gap-2 min-h-[48px]`}>
        {loading
          ? <><span className="inline-block animate-spin">{tool?.icon ?? '🌍'}</span> {t('cb_building')}</>
          : <><span className="mr-1">{tool?.icon ?? '🌍'}</span> {t('cb_get_briefing')}</>}
      </button>

      {sessionHistory.length > 0 && (
        <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
          <div className="flex items-center justify-between mb-3">
            <p className={`text-xs font-bold ${c.textMuted} uppercase tracking-wide`}>🕓 {t('cb_recent_briefings')}</p>
            <button onClick={() => setSessionHistory([])} className={`text-xs ${c.textMuted}`}>{t('cb_clear')}</button>
          </div>
          <ul className="space-y-1.5">
            {sessionHistory.map((h, i) => {
              const purposeMeta = TRIP_PURPOSES.find(tp => tp.id === h.tripPurpose);
              return (
                <li key={i} className={`text-xs ${c.textSecondary} flex items-center gap-2`}>
                  <span>{purposeMeta?.icon ?? '🌍'}</span>
                  <span className="font-medium">{h.destination}</span>
                  <span className={c.textMuted}>· {purposeMeta ? t(purposeMeta.labelKey) : ''}</span>
                </li>
              );
            })}
          </ul>
        </div>
      )}
    </div>
  );

  const renderResults = () => {
    if (!results) return null;
    const purposeMeta = TRIP_PURPOSES.find(tp => tp.id === results.tripPurpose);

    return (
      <div className="space-y-4" ref={resultsRef}>

        {/* Header + overview */}
        <div className={`${c.card} border ${c.border} rounded-xl p-5`}>
          <div className="flex items-start justify-between gap-4 mb-3">
            <div>
              <p className={`text-2xl font-black ${c.text}`}>{results.destination}</p>
              <p className={`text-sm ${c.textMuted}`}>
                {purposeMeta?.icon} {purposeMeta ? t(purposeMeta.labelKey) : ''} {t('cb_briefing_suffix')}
                {results.risk_level && (
                  <span className={`ml-2 text-xs font-bold px-2 py-0.5 rounded-full border ${
                    results.risk_level === 'high' ? c.danger :
                    results.risk_level === 'medium' ? c.warning : c.success
                  }`}>{results.risk_level === 'high' ? t('cb_risk_high') : results.risk_level === 'medium' ? t('cb_risk_medium') : t('cb_risk_low')}</span>
                )}
              </p>
            </div>
          </div>
          {results.overview && <p className={`text-sm ${c.textSecondary}`}>{results.overview}</p>}
        </div>

        {results.confidence === 'low' && (
          <div className={`text-xs ${c.warning} border rounded-lg px-3 py-2`}>ℹ️ {t('cb_confidence_low')}</div>
        )}

        {/* Section nav */}
        {results.sections?.length > 0 && (
          <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
            <p className={`text-xs font-bold ${c.textMuted} uppercase tracking-wide mb-3`}>{t('cb_browse_topics')}</p>
            <div className="flex flex-wrap gap-2">
              {results.sections.map(sec => (
                <button key={sec.id} onClick={() => setActiveSection(activeSection === sec.id ? null : sec.id)}
                  className={`px-3 py-1.5 rounded-lg border text-xs font-medium transition-colors ${activeSection === sec.id ? c.pillActive : c.pillInactive}`}>
                  <span className="mr-1">{sec.icon}</span>{sec.title}
                </button>
              ))}
            </div>

            {/* Active section detail */}
            {activeData && (
              <div className={`mt-4 pt-4 border-t ${isDark ? 'border-zinc-700' : 'border-slate-200'} space-y-3`}>
                <p className={`text-sm font-bold ${c.text}`}>{activeData.icon} {activeData.title}</p>
                {activeData.dos?.length > 0 && (
                  <div className="space-y-1.5">
                    {activeData.dos.map((d, i) => (
                      <div key={i} className={`text-sm ${c.success} border rounded-lg px-3 py-2 flex gap-2`}>
                        <span className="flex-shrink-0">✅</span><span>{d}</span>
                      </div>
                    ))}
                  </div>
                )}
                {activeData.donts?.length > 0 && (
                  <div className="space-y-1.5">
                    {activeData.donts.map((d, i) => (
                      <div key={i} className={`text-sm ${c.danger} border rounded-lg px-3 py-2 flex gap-2`}>
                        <span className="flex-shrink-0">🚫</span><span>{d}</span>
                      </div>
                    ))}
                  </div>
                )}
                {activeData.notes?.length > 0 && (
                  <div className="space-y-1.5">
                    {activeData.notes.map((n, i) => (
                      <div key={i} className={`text-sm ${c.infoBox} border rounded-lg px-3 py-2 flex gap-2`}>
                        <span className="flex-shrink-0">ℹ️</span><span>{n}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
        )}

        {/* Insider tips */}
        {results.insider_tips?.length > 0 && (
          <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
            <p className={`text-xs font-bold ${c.textMuted} uppercase tracking-wide mb-3`}>💡 {t('cb_insider_tips')}</p>
            <ul className="space-y-2">
              {results.insider_tips.map((tip, i) => (
                <li key={i} className={`text-sm ${c.textSecondary} flex gap-2`}>
                  <span className={`flex-shrink-0 font-bold ${c.accentTxt}`}>{i + 1}.</span><span>{tip}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {(results.forgiveness?.forgiven?.length > 0 || results.forgiveness?.serious?.length > 0) && (
          <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
            <p className={`text-xs font-bold ${c.textMuted} uppercase tracking-wide mb-3`}>⚖️ {t('cb_forgiveness_title')}</p>
            {results.forgiveness?.forgiven?.length > 0 && (
              <div className="mb-3">
                <p className={`text-xs font-semibold ${c.textMuted} mb-1.5`}>{t('cb_forgiven_label')}</p>
                <div className="space-y-1.5">
                  {results.forgiveness.forgiven.map((x, i) => (
                    <div key={i} className={`text-sm ${c.success} border rounded-lg px-3 py-2 flex gap-2`}><span className="flex-shrink-0">🙆</span><span>{x}</span></div>
                  ))}
                </div>
              </div>
            )}
            {results.forgiveness?.serious?.length > 0 && (
              <div>
                <p className={`text-xs font-semibold ${c.textMuted} mb-1.5`}>{t('cb_serious_label')}</p>
                <div className="space-y-1.5">
                  {results.forgiveness.serious.map((x, i) => (
                    <div key={i} className={`text-sm ${c.danger} border rounded-lg px-3 py-2 flex gap-2`}><span className="flex-shrink-0">🚫</span><span>{x}</span></div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        {/* Must-know phrases */}
        {results.key_phrases?.length > 0 && (
          <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
            <p className={`text-xs font-bold ${c.textMuted} uppercase tracking-wide mb-3`}>💬 {t('cb_must_know_phrases')}</p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {results.key_phrases.map((p, i) => (
                <div key={i} className={`${c.cardAlt} border ${c.border} rounded-lg px-3 py-2`}>
                  <p className={`text-sm font-bold ${c.text}`}>{p.phrase}</p>
                  <p className={`text-xs ${c.textMuted}`}>{p.meaning}</p>
                  {p.pronunciation && <p className={`text-xs italic ${c.textMuted}`}>{p.pronunciation}</p>}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Post-result cross-refs */}
        <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
          <p className={`text-[10px] font-bold ${c.textMuted} uppercase mb-2`}>🔗 {t('cb_related_tools')}</p>
          <div className="flex flex-wrap gap-3">
            <a href="/LayoverMaximizer" className={`text-xs ${linkStyle}`}>✈️ {t('cb_layover')}</a>
            <a href="/MoneyDiplomat" className={`text-xs ${linkStyle}`}>💰 {t('cb_money_diplomat')}</a>
            <a href="/ApologyCalibrator" className={`text-xs ${linkStyle}`}>🙏 {t('cb_apology_calibrator')}</a>
          </div>
        </div>
      </div>
    );
  };

  return (
    <div className={`space-y-4 ${c.text}`}>
      {/* Persistent header */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5`}>
        <div className="flex items-start justify-between">
          <div>
            <h2 className={`text-xl font-bold ${c.text}`}>
              <span className="mr-2">{tool?.icon ?? '🌍'}</span>{tool?.title ?? t('cb_title')}
            </h2>
            <p className={`text-sm ${c.textSecondary}`}>{tool?.tagline ?? t('cb_tagline')}</p>
            <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className={`mt-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium border disabled:opacity-40 ${isDark ? 'text-white border-white/40' : 'text-gray-800 border-transparent'}`}>{t('try_example')}</button>
          </div>
          <button
            onClick={handleReset}
            style={{ visibility: (results || destination.trim()) ? 'visible' : 'hidden' }}
            className={`${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs font-bold`}
          >
            ↺ {t('cb_new_briefing')}
          </button>
        </div>
      </div>
      {!results && <p className={`text-xs ${c.textMuted} px-1`}>{t('cb_xref_layover_intro2')} <a href="/LayoverMaximizer" className={linkStyle}>✈️ {t('cb_layover')}</a> {t('cb_xref_layover_outro')}</p>}
      {!results && renderInput()}
      {results && renderResults()}
    </div>
  );
}

CultureBriefing.displayName = 'CultureBriefing';
export default CultureBriefing;
