import React, { useState, useCallback, useEffect, useRef } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { CopyBtn } from '../components/ActionButtons';
import { useRegisterActions } from '../components/ActionBarContext';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

// ═══════════════════════════════════════════
// CONSTANTS
// ═══════════════════════════════════════════

const DATE_TYPES = [
  { id: 'casual', l: '😊 Casual', d: 'Low-key and comfortable' },
  { id: 'romantic', l: '🌹 Romantic', d: 'Intimate and special' },
  { id: 'adventurous', l: '🎢 Adventurous', d: 'Try something new' },
  { id: 'first_date', l: '✨ First Date', d: 'Impressive but not try-hard' },
  { id: 'anniversary', l: '💍 Anniversary', d: 'Celebrate your story' },
  { id: 'stay_in', l: '🏠 Stay-In', d: 'Cozy night at home' },
];
const DURATION_OPTIONS = [{ v: 'quick', l: '⚡ Quick' }, { v: 'standard', l: '🌙 Standard' }, { v: 'long', l: '✨ Long' }];
const WEATHER_OPTIONS = [{ v: '', l: '🤷 ?' }, { v: 'clear', l: '🌙 Clear' }, { v: 'rainy', l: '🌧️ Rain' }, { v: 'cold', l: '🥶 Cold' }, { v: 'hot', l: '🔥 Hot' }, { v: 'perfect', l: '✨ Perfect' }];
const DIETARY_OPTIONS = [
  { v: 'vegetarian', l: '🥬 Vegetarian' }, { v: 'vegan', l: '🌱 Vegan' },
  { v: 'gluten-free', l: '🌾 GF' }, { v: 'halal', l: '☪️ Halal' },
  { v: 'kosher', l: '✡️ Kosher' }, { v: 'no-alcohol', l: '🚫🍷 No alcohol' },
  { v: 'dairy-free', l: '🥛 No dairy' }, { v: 'nut-allergy', l: '🥜 Nut allergy' },
];
const STOP_RATINGS = [{ v: 'loved', l: '❤️ Loved' }, { v: 'fine', l: '👍 Fine' }, { v: 'skip', l: '👎 Skip' }];
const NOISE_OPTIONS = [{ v: 'quiet', l: '🤫 Quiet' }, { v: 'moderate', l: '🔊 Moderate' }, { v: 'lively', l: '🎉 Lively' }];
const ENERGY_OPTIONS = [{ v: 'low', l: '🧘 Low-key' }, { v: 'medium', l: '☯️ Balanced' }, { v: 'high', l: '⚡ High energy' }];

const STOP_EMOJIS = { drinks: '🍷', dinner: '🍽️', dessert: '🍰', walk: '🚶', entertainment: '🎭', activity: '⭐', coffee: '☕', tea: '🍵', bar: '🍸', cocktail: '🍹' };
function stopEmoji(type) { if (!type) return '📍'; const l = type.toLowerCase(); for (const [k, e] of Object.entries(STOP_EMOJIS)) { if (l.includes(k)) return e; } return '📍'; }

const BUDGET_PRESETS = {
  '$': [25, 50, 75, 100, 150, 200], '€': [20, 40, 60, 80, 120, 180], '£': [20, 40, 60, 80, 120, 160],
  '¥': [3000, 5000, 8000, 10000, 15000, 20000], '₹': [500, 1000, 2000, 3000, 5000, 8000],
  'R$': [50, 100, 150, 250, 400, 600], '₩': [20000, 40000, 60000, 80000, 120000, 150000],
  'A$': [30, 50, 80, 120, 170, 250], 'C$': [30, 50, 80, 120, 170, 250],
  'CHF': [25, 50, 75, 100, 150, 200], 'kr': [200, 400, 600, 800, 1200, 1800],
  'zł': [80, 150, 250, 400, 600, 800], '₱': [500, 1000, 2000, 3000, 5000, 8000],
  '฿': [500, 1000, 1500, 2500, 4000, 6000], 'RM': [50, 100, 150, 250, 400, 600],
};
const CURRENCIES = [
  { s: '$', l: 'USD', f: '🇺🇸' }, { s: '€', l: 'EUR', f: '🇪🇺' }, { s: '£', l: 'GBP', f: '🇬🇧' },
  { s: '¥', l: 'JPY', f: '🇯🇵' }, { s: '₹', l: 'INR', f: '🇮🇳' }, { s: 'R$', l: 'BRL', f: '🇧🇷' },
  { s: '₩', l: 'KRW', f: '🇰🇷' }, { s: 'A$', l: 'AUD', f: '🇦🇺' }, { s: 'C$', l: 'CAD', f: '🇨🇦' },
  { s: 'CHF', l: 'CHF', f: '🇨🇭' }, { s: 'kr', l: 'SEK', f: '🇸🇪' }, { s: 'zł', l: 'PLN', f: '🇵🇱' },
  { s: '₱', l: 'PHP', f: '🇵🇭' }, { s: '฿', l: 'THB', f: '🇹🇭' }, { s: 'RM', l: 'MYR', f: '🇲🇾' },
];
const LOC_CUR = { 'en-us': '$', 'en-gb': '£', 'en-au': 'A$', 'en-ca': 'C$', 'en-in': '₹', 'ja': '¥', 'ko': '₩', 'pt-br': 'R$', 'de': '€', 'fr': '€', 'it': '€', 'sv': 'kr', 'pl': 'zł', 'th': '฿', 'ms': 'RM', 'fil': '₱' };
function detectCur() { try { const l = (navigator.language || 'en-US').toLowerCase(); return LOC_CUR[l] || LOC_CUR[l.split('-')[0]] || '$'; } catch { return '$'; } }
function detectLoc() { try { const p = (Intl.DateTimeFormat().resolvedOptions().timeZone || '').split('/'); return p.length >= 2 ? p[p.length - 1].replace(/_/g, ' ') : ''; } catch { return ''; } }
function budgetRange(s) { const p = BUDGET_PRESETS[s] || BUDGET_PRESETS['$']; return { min: Math.round(p[0] * 0.5), max: Math.round(p[p.length - 1] * 1.5), step: p[0] <= 100 ? 5 : p[0] <= 1000 ? 50 : 500 }; }
function fmtMoney(a, s) { return ['kr', 'zł'].includes(s) ? `${a} ${s}` : `${s}${a}`; }
const START_TIMES = ['5:00 PM', '5:30 PM', '6:00 PM', '6:30 PM', '7:00 PM', '7:30 PM', '8:00 PM', '8:30 PM', '9:00 PM', '9:30 PM', '10:00 PM'];

// ═══════════════════════════════════════════
// COMPONENT
// ═══════════════════════════════════════════

const DateNight = ({ tool }) => {
  const { callToolEndpoint, loading } = useClaudeAPI();
  const { isDark } = useTheme();

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20'
                          : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-500' : 'text-gray-400',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white'
                          : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200'
                          : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200'
                          : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200'
                          : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200'
                          : 'bg-red-50 border-red-200 text-red-800',
    required:      isDark ? 'text-amber-400' : 'text-amber-500',
    // Bespoke keys
    roseText:      isDark ? 'text-rose-400' : 'text-rose-600',
    roseBorder:    isDark ? 'border-rose-700' : 'border-rose-300',
    chipOn:        isDark ? 'bg-rose-800 border-rose-600 text-rose-100' : 'bg-rose-600 border-rose-600 text-white',
    chipOff:       isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500' : 'border-gray-300 text-gray-500 hover:border-gray-400',
    headerCard:    isDark ? 'bg-rose-900/20 border-rose-700' : 'bg-rose-50 border-rose-200',
    btnAction:     isDark ? 'bg-rose-600 hover:bg-rose-500 text-white' : 'bg-rose-600 hover:bg-rose-700 text-white',
    btnLive:       isDark ? 'bg-emerald-700 hover:bg-emerald-600 text-white' : 'bg-emerald-600 hover:bg-emerald-700 text-white',
    accentCard:    isDark ? 'bg-rose-900/20 border-rose-700' : 'bg-rose-50 border-rose-200',
    altCard:       isDark ? 'bg-zinc-700/50 border-zinc-600' : 'bg-slate-50 border-slate-200',
    infoCard:      isDark ? 'bg-sky-900/20 border-sky-700' : 'bg-sky-50 border-sky-200',
    budgetBar:     isDark ? 'bg-zinc-700' : 'bg-gray-200',
    budgetFill:    isDark ? 'bg-rose-600' : 'bg-rose-500',
    bufferText:    isDark ? 'text-emerald-400' : 'text-emerald-600',
    journalText:   isDark ? 'text-amber-400' : 'text-amber-600',
    journalCard:   isDark ? 'bg-amber-900/20 border-amber-700' : 'bg-amber-50 border-amber-200',
    jarBtnText:    isDark ? 'text-orange-400' : 'text-orange-600',
    jarCard:       isDark ? 'bg-orange-900/20 border-orange-700' : 'bg-orange-50 border-orange-200',
    rutText:       isDark ? 'text-cyan-400' : 'text-cyan-600',
    liveCard:      isDark ? 'bg-emerald-900/20 border-emerald-700' : 'bg-emerald-50 border-emerald-200',
    proTipText:    isDark ? 'text-amber-300' : 'text-amber-700',
    quoteCard:     isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    stopCard:      isDark ? 'bg-zinc-800 border-zinc-700' : 'bg-white border-gray-200',
    timelineDot:   isDark ? 'bg-rose-600' : 'bg-rose-500',
    timelineLine:  isDark ? 'bg-zinc-700' : 'bg-gray-200',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-600 hover:text-cyan-700 underline underline-offset-2';


  // ─── Input ───
  const [currency, setCurrency] = useState(detectCur);
  const [budget, setBudget] = useState(() => (BUDGET_PRESETS[detectCur()] || BUDGET_PRESETS['$'])[2]);
  const [dateType, setDateType] = useState('');
  const [location, setLocation] = useState(detectLoc() || '');
  const [restrictions, setRestrictions] = useState('');
  const [lastTime, setLastTime] = useState('');
  const [startTime, setStartTime] = useState('7:00 PM');
  const [duration, setDuration] = useState('standard');
  const [weather, setWeather] = useState('');
  const [plannedDate, setPlannedDate] = useState(''); // '' = tonight
  const [dietary, setDietary] = useState([]);
  const [showDietary, setShowDietary] = useState(false);
  const [yearsTogether, setYearsTogether] = useState(1);
  const [showInputs, setShowInputs] = useState(true);
  const [error, setError] = useState('');

  // ─── Results ───
  const [results, setResults] = useState(null);
  const [swapping, setSwapping] = useState(null);
  const [expandedConvo, setExpandedConvo] = useState(false);
  const [expandedPlanB, setExpandedPlanB] = useState(false);

  // ─── Live mode ───
  const [liveMode, setLiveMode] = useState(false);
  const [liveStep, setLiveStep] = useState(0);
  const [timeOffset, setTimeOffset] = useState(0);

  // ─── Rating ───
  const [showRate, setShowRate] = useState(false);
  const [overallRating, setOverallRating] = useState(0);
  const [stopRatings, setStopRatings] = useState({});
  const [rateNotes, setRateNotes] = useState('');
  const [rateResult, setRateResult] = useState(null);
  const [actualSpend, setActualSpend] = useState('');

  // ─── Share / Surprise ───
  const [shareData, setShareData] = useState(null);
  const [shareLoading, setShareLoading] = useState(false);
  const [surpriseMode, setSurpriseMode] = useState(false);

  // ─── Similar ───
  const [similarResults, setSimilarResults] = useState(null);
  const [similarLoading, setSimilarLoading] = useState(false);

  // ─── Checklist ───
  const [checklist, setChecklist] = useState(null);
  const [checklistLoading, setChecklistLoading] = useState(false);
  const [checklistChecked, setChecklistChecked] = useState({});

  // ─── Date Jar ───
  const [showJar, setShowJar] = useState(false);
  const [jarLoading, setJarLoading] = useState(false);

  // ─── Rut ───
  const [rutResult, setRutResult] = useState(null);
  const [rutLoading, setRutLoading] = useState(false);

  // ─── Partner prefs ───
  const [showPartner, setShowPartner] = useState(false);

  // ─── Persistent ───
  // Journal capped at 50 (not 5-6): pattern analysis requires enough history to detect ruts
  const [resultsPersist, setResultsPersist] = usePersistentState('date-night-results', null);
  const [dateTypePersist, setDateTypePersist] = usePersistentState('date-night-type', '');
  const [locationPersist, setLocationPersist] = usePersistentState('date-night-location', detectLoc() || '');
  const [journal, setJournal] = usePersistentState('date-night-journal', []);
  const [prefs, setPrefs] = usePersistentState('date-night-prefs', { liked: [], disliked: [] });
  const [favorites, setFavorites] = usePersistentState('date-night-favorites', []);
  const [partnerPrefs, setPartnerPrefs] = usePersistentState('date-night-partner', { partnerLikes: '', partnerDislikes: '', noiseLevel: '', energyLevel: '' });
  const [dateJar, setDateJar] = usePersistentState('date-night-jar', []);
  const [history, setHistory] = usePersistentState('date-night-history', []);
  const [showJournal, setShowJournal] = useState(false);

  // Sync persistent dateType/location/results into local state on first render
  const _dtRef = useRef(false);
  useEffect(() => { if (!_dtRef.current) { _dtRef.current = true; if (dateTypePersist) setDateType(dateTypePersist); if (locationPersist) setLocation(locationPersist); if (resultsPersist) setResults(resultsPersist); } }, []); // eslint-disable-line

  // Keep persistent values in sync
  useEffect(() => { setDateTypePersist(dateType); }, [dateType]); // eslint-disable-line
  useEffect(() => { setLocationPersist(location); }, [location]); // eslint-disable-line
  useEffect(() => { setResultsPersist(results); }, [results]); // eslint-disable-line

  const resultsRef = useRef(null);
  const handleRef = useRef(null);
  const canSubmitRef = useRef(false);

  // Scroll to results when they load
  useEffect(() => {
    if (results && !showInputs && resultsRef.current) {
      resultsRef.current.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }, [results, showInputs]);

  // Keyboard: Cmd/Ctrl+Enter to submit
  useEffect(() => {
    const handler = (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'Enter' && canSubmitRef.current)
        handleRef.current?.();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, []);

  // ─── Derived ───
  const presets = BUDGET_PRESETS[currency] || BUDGET_PRESETS['$'];
  const br = budgetRange(currency);
  const fm = useCallback((a) => fmtMoney(a, currency), [currency]);
  const totalSpent = results?.total_estimated || 0;
  const bufferAmt = results?.buffer || (budget - totalSpent);
  const spentPct = budget > 0 ? Math.min(100, (totalSpent / budget) * 100) : 0;
  const isAnni = dateType === 'anniversary';
  const isFuture = !!plannedDate && plannedDate > new Date().toISOString().slice(0, 10);
  const daysUntil = isFuture ? Math.round((new Date(plannedDate) - new Date()) / 86400000) : 0;
  const fmtDate = (iso) => { try { const d = Math.floor((Date.now() - new Date(iso)) / 86400000); return d === 0 ? 'Today' : d === 1 ? 'Yesterday' : d < 7 ? `${d}d ago` : new Date(iso).toLocaleDateString('en', { month: 'short', day: 'numeric' }); } catch { return ''; } };
  const plannedDateLabel = isFuture ? new Date(plannedDate + 'T12:00:00').toLocaleDateString('en', { weekday: 'short', month: 'short', day: 'numeric' }) : 'Tonight';

  // ═══ HELPERS ═══

  const handleCurrencyChange = useCallback((s) => { setCurrency(s); setBudget((BUDGET_PRESETS[s] || BUDGET_PRESETS['$'])[2]); }, []);
  const toggleDietary = useCallback((v) => setDietary(p => p.includes(v) ? p.filter(d => d !== v) : [...p, v]), []);

  const getPayload = useCallback(() => ({
    budget, currency, dateType, location: location.trim(), restrictions: restrictions.trim(),
    lastTime: lastTime.trim(), startTime, duration, weather, dietary, partnerPrefs,
    plannedDate: plannedDate || null,
    isFuturePlan: isFuture,
    favorites: favorites.slice(0, 8),
    pastDates: journal.filter(j => (j.location || '').toLowerCase().includes((location || '').toLowerCase()))
      .map(j => ({ title: j.vibeTitle || '?', stops: (j.stops || []).map(s => s.venue_name), dateType: j.dateType, rating: j.rating })),
    preferences: prefs,
  }), [budget, currency, dateType, location, restrictions, lastTime, startTime, duration, weather, dietary, partnerPrefs, plannedDate, isFuture, favorites, journal, prefs]);

  const saveToJournal = useCallback((res) => {
    setJournal(p => [{ id: `dn_${Date.now()}`, date: new Date().toISOString(), location: location.trim(),
      dateType, vibeTitle: res.vibe_title, stops: res.itinerary || [], budget, currency, rating: null }, ...p].slice(0, 6));
  }, [setJournal, location, dateType, budget, currency]);

  const resetResults = () => {
    setShowRate(false); setRateResult(null); setShareData(null); setSimilarResults(null);
    setExpandedConvo(false); setExpandedPlanB(false); setStopRatings({}); setOverallRating(0);
    setRateNotes(''); setActualSpend(''); setChecklist(null); setChecklistChecked({});
    setLiveMode(false); setLiveStep(0); setTimeOffset(0); setRutResult(null);
  };

  const buildText = () => {
    if (!results?.itinerary) return '';
    const stops = results.itinerary.map(s => `${s.time} — ${s.venue_name}: ${s.description} (~${fm(s.estimated_cost)})`).join('\n');
    let t = `💘 ${results.vibe_title || 'Date Night'}\n${results.vibe_description || ''}\nBudget: ${fm(budget)}\n\n${stops}\n\nTotal: ~${fm(results.total_estimated)}`;
    if (results.overall_dress_code) t += `\n👗 ${results.overall_dress_code}`;
    return t + BRAND;
  };

  const buildFullText = useCallback(() => {
    if (!results) return '';
    return buildText();
  }, [results, budget, currency]);

  useRegisterActions(buildFullText(), tool?.title || 'Date Night');

  const toggleFavorite = (stop) => {
    const exists = favorites.find(f => f.venue_name === stop.venue_name);
    if (exists) setFavorites(p => p.filter(f => f.venue_name !== stop.venue_name));
    else setFavorites(p => [{ venue_name: stop.venue_name, stop_type: stop.stop_type, estimated_cost: stop.estimated_cost, added: new Date().toISOString() }, ...p].slice(0, 6));
  };

  const isFav = (stop) => favorites.some(f => f.venue_name === stop.venue_name);

  // ═══ API CALLS ═══

  const generate = async () => {
    if (!location.trim()) { setError('Enter a city or neighborhood.'); return; }
    if (!dateType) { setError('Select a date type.'); return; }
    setError(''); setResults(null); resetResults();
    if (isAnni && yearsTogether > 0) {
      const data = await callToolEndpoint('date-night', { action: 'anniversary-deep', ...getPayload(), yearsTogether });
      if (data) {
        setResults(data); setShowInputs(false); saveToJournal(data);
        setHistory(p => [{ preview: (data.vibe_title || location.trim()).slice(0, 40), result: data, date: new Date().toISOString() }, ...p].slice(0, 6));
      }
      return;
    }
    const data = await callToolEndpoint('date-night', { action: 'generate', ...getPayload() });
    if (data) {
      setResults(data); setShowInputs(false); saveToJournal(data);
      setHistory(p => [{ preview: (data.vibe_title || location.trim()).slice(0, 40), result: data, date: new Date().toISOString() }, ...p].slice(0, 6));
    }
  };

  const regenerate = async () => {
    if (!results) return; resetResults();
    const data = await callToolEndpoint('date-night', { action: 'regenerate', ...getPayload(), previousTitle: results.vibe_title });
    if (data) { setResults(data); saveToJournal(data); }
  };

  const swapStop = async (num) => {
    setSwapping(num);
    const data = await callToolEndpoint('date-night', { action: 'swap', ...getPayload(), currentItinerary: results, swapStopNumber: num });
    if (data?.stop) { setResults(p => { const it = [...(p.itinerary || [])]; const idx = it.findIndex(s => s.stop_number === num); if (idx !== -1) it[idx] = data.stop; return { ...p, itinerary: it }; }); }
    setSwapping(null);
  };

  const handleRate = async () => {
    if (!overallRating) { setError('Tap a star.'); return; }
    const sr = (results?.itinerary || []).map(s => ({ venue_name: s.venue_name, stop_type: s.stop_type, rating: stopRatings[s.stop_number] || 'fine', note: '' }));
    const data = await callToolEndpoint('date-night', { action: 'rate', vibeTitle: results?.vibe_title, location, dateType, overallRating, stopRatings: sr, notes: rateNotes, actualSpend: actualSpend || null });
    if (data) {
      setRateResult(data);
      setPrefs(p => ({ liked: [...new Set([...(p.liked || []), ...(data.liked_types || []), ...(data.liked_qualities || [])])].slice(0, 15), disliked: [...new Set([...(p.disliked || []), ...(data.disliked_types || [])])].slice(0, 10) }));
      setJournal(p => p.map(j => j.vibeTitle === results?.vibe_title && j.location === location.trim() ? { ...j, rating: overallRating } : j));
    }
  };

  const handleShare = async () => {
    setShareLoading(true); setShareData(null);
    const data = await callToolEndpoint('date-night', { action: 'share', vibeTitle: results?.vibe_title, dateType, location, itinerary: results?.itinerary, startTime, budget, currency, surprise: surpriseMode });
    if (data) setShareData(data);
    setShareLoading(false);
  };

  const handleSimilar = async (stop) => {
    setSimilarLoading(true); setSimilarResults(null);
    const data = await callToolEndpoint('date-night', { action: 'similar', venueName: stop.venue_name, stopType: stop.stop_type, location, dateType, budget, currency });
    if (data) setSimilarResults(data);
    setSimilarLoading(false);
  };

  const handleChecklist = async () => {
    setChecklistLoading(true); setChecklist(null); setChecklistChecked({});
    const data = await callToolEndpoint('date-night', { action: 'checklist', dateType, startTime, weather, dietary, hasReservation: false });
    if (data) setChecklist(data);
    setChecklistLoading(false);
  };

  const handleDateJar = async () => {
    setJarLoading(true);
    const data = await callToolEndpoint('date-night', { action: 'date-jar', location: location.trim(), budget, currency, dietary, preferences: prefs, partnerPrefs, pastDates: journal.map(j => ({ title: j.vibeTitle, stops: (j.stops || []).map(s => s.venue_name), dateType: j.dateType, rating: j.rating })) });
    if (data?.concepts) { setDateJar(data.concepts); }
    setJarLoading(false);
  };

  const handleRutDetect = async () => {
    setRutLoading(true); setRutResult(null);
    const data = await callToolEndpoint('date-night', { action: 'rut-detect', pastDates: journal.map(j => ({ title: j.vibeTitle, stops: (j.stops || []).map(s => s.venue_name), dateType: j.dateType, rating: j.rating })), location, preferences: prefs });
    if (data) setRutResult(data);
    setRutLoading(false);
  };

  const loadJournal = (entry) => {
    setResults({ vibe_title: entry.vibeTitle, itinerary: entry.stops });
    setLocation(entry.location || ''); setDateType(entry.dateType || '');
    setCurrency(entry.currency || '$'); setBudget(entry.budget || 100);
    setShowInputs(false); resetResults(); setShowJournal(false);
  };

  // ═══ SHARED ═══
  const Pill = ({ options, value, setter, multi }) => (
    <div className="flex flex-wrap gap-1.5">
      {options.map(o => {
        const active = multi ? (value || []).includes(o.v) : value === (o.v || o.id);
        return (
          <button key={o.v || o.id} onClick={() => multi ? setter(o.v) : setter(o.v || o.id)}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold border ${active ? c.chipOn : c.chipOff}`}>
            {active && '✓ '}{o.l}
          </button>
        );
      })}
    </div>
  );

  // ═══════════════════════════════════════════
  // RENDER
  // ═══════════════════════════════════════════
  handleRef.current = generate;
  canSubmitRef.current = !loading && !!location.trim() && !!dateType;


  // ═══ RENDER: Results ═══
  const renderResults = () => {
    if (!results || showInputs || liveMode) return null;
    const stops = results.itinerary || [];
    return (
    <div ref={resultsRef} className="space-y-4">
      <button onClick={() => setShowInputs(true)} className={`text-xs font-bold ${c.roseText}`}>✏️ Edit · {location} · {fm(budget)}{isFuture ? ` · ${plannedDateLabel}` : ''}</button>

      {/* Header */}
      <div className={`${c.headerCard} border-2 rounded-2xl p-5`}>
        <h3 className={`text-xl font-bold ${c.text}`}>{tool?.icon ?? '💘'} {results.vibe_title || 'Your Evening'}</h3>
        {results.vibe_description && <p className={`text-sm ${c.textSecondary} mt-1`}>{results.vibe_description}</p>}
        {results.narrative_arc && <p className={`text-xs italic ${c.textSecondary} mt-2`}>{results.narrative_arc}</p>}
      </div>

      {/* Actions */}
      <div className="flex flex-wrap gap-2">
        {isFuture ? (
          <div className={`w-full ${c.infoCard} border rounded-xl p-4 space-y-2`}>
            <p className={`text-sm font-bold ${c.text}`}>📅 Planning ahead for {plannedDateLabel}</p>
            {daysUntil > 7 && <p className={`text-xs ${c.textSecondary}`}>⏰ {daysUntil} days away — book reservations now to secure the best spots.</p>}
            {daysUntil <= 7 && daysUntil > 1 && <p className={`text-xs ${c.textSecondary}`}>⏰ {daysUntil} days away — call ahead today to confirm availability.</p>}
            {daysUntil === 1 && <p className={`text-xs ${c.textSecondary}`}>⏰ Tomorrow's date — confirm bookings today.</p>}
            {results?.advance_booking?.length > 0 && (
              <div className="pt-1 space-y-1">
                {results.advance_booking.map((b, i) => <p key={i} className={`text-xs ${c.textSecondary}`}>• {b}</p>)}
              </div>
            )}
          </div>
        ) : (
          <button onClick={() => { setLiveMode(true); setLiveStep(0); setTimeOffset(0); }} className={`px-4 py-2 rounded-xl text-xs font-bold ${c.btnLive}`}>▶️ Start Date</button>
        )}
        <button onClick={handleChecklist} disabled={checklistLoading} className={`px-3 py-2 rounded-xl text-xs font-bold ${c.btnSecondary} border ${c.border}`}>
          {checklistLoading ? <><span className="animate-spin inline-block">{tool?.icon ?? '💘'}</span> Loading…</> : '📋 Pre-date checklist'}
        </button>
        <button onClick={regenerate} disabled={loading} className={`px-3 py-2 rounded-xl text-xs font-bold ${c.btnSecondary} border ${c.border}`}>
          {loading ? <><span className="animate-spin inline-block">{tool?.icon ?? '💘'}</span> …</> : '🔄 Different'}
        </button>
        <button onClick={() => { setSurpriseMode(false); handleShare(); }} disabled={shareLoading} className={`px-3 py-2 rounded-xl text-xs font-bold ${c.btnSecondary} border ${c.border}`}>
          {shareLoading ? <><span className="animate-spin inline-block">{tool?.icon ?? '💘'}</span> …</> : '📨 Send plan'}
        </button>
        <button onClick={() => { setSurpriseMode(true); handleShare(); }} disabled={shareLoading} className={`px-3 py-2 rounded-xl text-xs font-bold ${c.btnSecondary} border ${c.border}`}>
          {shareLoading ? <><span className="animate-spin inline-block">{tool?.icon ?? '💘'}</span> …</> : '🎁 Surprise invite'}
        </button>
      </div>

      {/* Checklist */}
      {checklist && (
        <div className={`${c.success} border rounded-xl p-4 space-y-2`}>
          <div className="flex justify-between"><h4 className="font-bold text-sm">📋 Pre-Date Checklist</h4><button onClick={() => setChecklist(null)} className={`text-xs ${c.textMuteded}`}>✕</button></div>
          {(checklist.checklist || []).map((item, i) => (
            <button key={i} onClick={() => setChecklistChecked(p => ({ ...p, [i]: !p[i] }))}
              className={`flex items-center gap-2 w-full text-left text-xs ${checklistChecked[i] ? 'line-through opacity-50' : ''}`}>
              <span className={`w-5 h-5 rounded flex-shrink-0 flex items-center justify-center border-2 text-[10px] ${checklistChecked[i] ? 'bg-emerald-500 border-emerald-500 text-white' : c.border}`}>{checklistChecked[i] ? '✓' : ''}</span>
              <span className="flex-1">{item.item}</span>
              <span className={c.textMuteded}>{item.timing}</span>
              {item.priority === 'must' && <span className={`text-[10px] ${c.roseText}`}>●</span>}
            </button>
          ))}
          {checklist.last_minute_reminder && <div className={`${c.warning} border rounded-lg p-2 text-xs mt-2`}>🚪 {checklist.last_minute_reminder}</div>}
        </div>
      )}

      {/* Share */}
      {shareData && (
        <div className={`${c.infoCard} border rounded-xl p-4 space-y-2`}>
          <div className="flex justify-between"><h4 className="text-sm font-bold">{shareData.isSurprise ? '🎁 Mystery Invite' : '📨 Invite'}</h4><button onClick={() => setShareData(null)} className={`text-xs ${c.textMuteded}`}>✕</button></div>
          <p className={`text-sm whitespace-pre-line`}>{shareData.message}</p>
          {shareData.what_to_tell_them && <div className={`${c.warning} border rounded-lg p-2 text-xs`}>📌 All they need to know: {shareData.what_to_tell_them}</div>}
          <CopyBtn content={shareData.message + BRAND} label="Copy" />
        </div>
      )}

      {/* Dress code */}
      {results.overall_dress_code && (
        <div className={`${c.altCard} border rounded-xl p-3 text-center`}>
          <p className={`text-xs font-bold ${c.text}`}>👗 {results.overall_dress_code}</p>
        </div>
      )}

      {/* Budget bar */}
      <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
        <div className="flex justify-between mb-2">
          <p className={`text-xs font-bold ${c.text}`}>💰 Budget</p>
          <p className={`text-sm font-bold ${c.text}`}>~{fm(totalSpent)} / {fm(budget)}</p>
        </div>
        <div className={`w-full h-3 rounded-full ${c.budgetBar} overflow-hidden`}>
          <div className={`h-full rounded-full ${c.budgetFill}`} style={{ width: `${spentPct}%` }} />
        </div>
        {bufferAmt > 0 && <p className={`text-[10px] font-bold ${c.bufferText} mt-1 text-right`}>~{fm(bufferAmt)} buffer</p>}
      </div>

      {/* Milestone gesture */}
      {results.milestone_gesture && (
        <div className={`${c.accentCard} border ${c.border} rounded-xl p-4`}>
          <p className={`text-xs font-bold ${c.roseText} mb-1`}>🎁 Anniversary gesture</p>
          <p className={`text-sm ${c.text}`}>{results.milestone_gesture}</p>
        </div>
      )}

      {/* Timeline */}
      <div className="relative">
        <div className={`absolute left-[19px] top-6 bottom-6 w-px ${c.timelineLine}`} />
        {stops.map((stop, idx) => {
          const isSwap = swapping === (stop.stop_number || idx + 1);
          return (
            <div key={idx} className="flex gap-4 relative mb-4">
              <div className={`flex-shrink-0 w-10 h-10 rounded-full flex items-center justify-center z-10 border-2 ${c.timelineDot}`}>
                <span className="text-base">{stopEmoji(stop.stop_type || stop.venue_name)}</span>
              </div>
              <div className={`flex-1 ${c.stopCard} border rounded-xl p-4 ${isSwap ? 'opacity-50' : ''}`}>
                <div className="flex justify-between mb-1">
                  <div>
                    <span className={`text-[10px] font-bold ${c.roseText} uppercase`}>{stop.time}</span>
                    <h4 className={`text-sm font-bold ${c.text}`}>{stop.venue_name}</h4>
                  </div>
                  <span className={`text-sm font-black ${c.roseText}`}>~{fm(stop.estimated_cost)}</span>
                </div>
                <p className={`text-xs ${c.textSecondary} leading-relaxed mb-2`}>{stop.description}</p>
                {stop.dress_vibe && <p className={`text-[10px] ${c.textMuteded} mb-1`}>👗 {stop.dress_vibe}</p>}
                {stop.pro_tip && <p className={`text-[10px] ${c.proTipText} mb-1`}>💡 {stop.pro_tip}</p>}
                {stop.anniversary_touch && <p className={`text-[10px] ${c.roseText} mb-1`}>💍 {stop.anniversary_touch}</p>}
                {stop.plan_b && <p className={`text-[10px] ${c.textMuteded} mb-1`}>🔄 Backup: {stop.plan_b}</p>}
                <div className="flex flex-wrap gap-1.5 mt-2">
                  <button onClick={() => swapStop(stop.stop_number || idx + 1)} disabled={isSwap || loading} className={`text-xs font-bold ${c.textMuteded}`}>
                    {isSwap ? <><span className="animate-spin inline-block">{tool?.icon ?? '💘'}</span></> : '🔄 Swap'}
                  </button>
                  <button onClick={() => handleSimilar(stop)} disabled={similarLoading} className={`text-xs font-bold ${c.roseText}`}>💜 More like this</button>
                  <button onClick={() => toggleFavorite(stop)} className={`text-xs font-bold ${isFav(stop) ? c.roseText : c.textMuteded}`}>{isFav(stop) ? '❤️ Saved' : '🤍 Save'}</button>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Similar */}
      {similarResults && (
        <div className={`${c.altCard} border rounded-xl p-5 space-y-3`}>
          <div className="flex justify-between">
            <h3 className={`font-bold text-sm ${c.text}`}>💜 More like "{similarResults.original}"</h3>
            <button onClick={() => setSimilarResults(null)} className={`text-xs ${c.textMuteded}`}>✕</button>
          </div>
          {(similarResults.similar || []).map((s, i) => (
            <div key={i} className={`${c.card} border ${c.border} rounded-lg p-3`}>
              <div className="flex justify-between">
                <p className={`text-sm font-bold ${c.text}`}>{stopEmoji(s.stop_type)} {s.venue_name}</p>
                <span className={`text-xs font-bold ${c.roseText}`}>~{fm(s.estimated_cost)}</span>
              </div>
              <p className={`text-xs ${c.textSecondary} mt-1`}>{s.why_similar}</p>
            </div>
          ))}
        </div>
      )}

      {/* Conversation starters / nostalgia */}
      {(results.conversation_starters || results.nostalgia_prompts) && (
        <div className={`${c.card} border ${c.border} rounded-xl overflow-hidden`}>
          <button onClick={() => setExpandedConvo(!expandedConvo)} className="w-full p-4 flex justify-between text-left">
            <span className={`text-sm font-bold ${c.text}`}>{results.nostalgia_prompts ? '💭 Reflection Prompts' : '💬 Conversation Starters'}</span>
            <span className={`text-xs ${c.textMuteded}`}>{expandedConvo ? '▲' : '▼'}</span>
          </button>
          {expandedConvo && (
            <div className={`px-4 pb-4 space-y-2 border-t ${c.border} pt-3`}>
              {(results.nostalgia_prompts || results.conversation_starters || []).map((q, i) => (
                <div key={i} className={`${c.quoteCard} rounded-lg p-3`}>
                  <p className={`text-xs ${c.textSecondary}`}>{results.nostalgia_prompts ? '💭' : '💬'} {q}</p>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Plan B + Tips */}
      {results.plan_b && (
        <div className={`${c.card} border ${c.border} rounded-xl overflow-hidden`}>
          <button onClick={() => setExpandedPlanB(!expandedPlanB)} className="w-full p-4 flex justify-between text-left">
            <span className={`text-sm font-bold ${c.text}`}>🔄 Plan B</span>
            <span className={`text-xs ${c.textMuteded}`}>{expandedPlanB ? '▲' : '▼'}</span>
          </button>
          {expandedPlanB && <div className={`px-4 pb-4 border-t ${c.border} pt-3`}><p className={`text-sm ${c.textSecondary}`}>{results.plan_b}</p></div>}
        </div>
      )}
      {results.tips?.length > 0 && (
        <div className={`${c.warning} border rounded-xl p-4`}>
          <p className="text-xs font-bold mb-2">✨ Make It Better</p>
          {results.tips.map((t, i) => <p key={i} className="text-xs mb-1">• {t}</p>)}
        </div>
      )}

      {/* Rate */}
      <button onClick={() => setShowRate(!showRate)} className={`text-xs font-bold ${c.roseText}`}>{showRate ? '▲' : '⭐'} Rate this date</button>
      {showRate && (
        <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-4`}>
          <div>
            <p className={`text-sm font-bold ${c.text} mb-2`}>Overall</p>
            <div className="flex gap-1">
              {[1, 2, 3, 4, 5].map(s => (
                <button key={s} onClick={() => setOverallRating(s)} className={`text-2xl ${s <= overallRating ? '' : 'opacity-30'}`}>⭐</button>
              ))}
            </div>
          </div>
          <div>
            <p className={`text-sm font-bold ${c.text} mb-2`}>Each stop</p>
            {stops.map((s, i) => (
              <div key={i} className={`${c.stopCard} border rounded-lg p-3 mb-2`}>
                <p className={`text-xs font-bold ${c.text} mb-1`}>{stopEmoji(s.stop_type)} {s.venue_name}</p>
                <div className="flex gap-1">
                  {STOP_RATINGS.map(r => (
                    <button key={r.v} onClick={() => setStopRatings(p => ({ ...p, [s.stop_number || i + 1]: r.v }))}
                      className={`px-2 py-1 rounded-lg text-xs border ${stopRatings[s.stop_number || i + 1] === r.v ? c.chipOn : c.chipOff}`}>{r.l}
                    </button>
                  ))}
                </div>
              </div>
            ))}
          </div>
          <div>
            <p className={`text-xs font-bold ${c.text} mb-1`}>💰 Actual spend? <span className={c.textMuteded}>(optional)</span></p>
            <input value={actualSpend} onChange={e => setActualSpend(e.target.value)} placeholder={`e.g., ${fm(budget)}`} className={`w-40 px-3 py-2 border rounded-lg text-sm ${c.input}`} />
          </div>
          <textarea value={rateNotes} onChange={e => setRateNotes(e.target.value)} placeholder="Highlight? What to change?" rows={2} className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} />
          <button onClick={handleRate} disabled={loading || !overallRating} className={`w-full py-2.5 rounded-xl font-bold text-sm ${c.btnAction} disabled:opacity-40`}>
            {loading ? <><span className="animate-spin inline-block mr-2">{tool?.icon ?? '💘'}</span>Saving…</> : '⭐ Submit'}
          </button>
          {rateResult && (
            <div className={`${c.success} border rounded-xl p-4 space-y-2`}>
              <p className={`text-sm`}>{rateResult.encouragement}</p>
              <p className={`text-xs ${c.textSecondary}`}>{rateResult.summary}</p>
              {rateResult.next_suggestion && <p className={`text-xs ${c.roseText}`}>💡 Next: {rateResult.next_suggestion}</p>}
              {rateResult.budget_accuracy && <p className={`text-xs ${c.textMuteded}`}>💰 {rateResult.budget_accuracy}</p>}
            </div>
          )}
        </div>
      )}

      {/* AI disclaimer */}
      <p className={`text-xs italic text-center ${c.textMuted}`}>
        AI-generated suggestions. Venue types are ideas — confirm availability and local pricing before going.
      </p>

      {/* Post-result cross-refs */}
      <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
        <p className={`text-[10px] font-bold ${c.textMuted} uppercase mb-2`}>🔗 Related tools</p>
        <div className="flex flex-wrap gap-3">
          <a href="/CaptionMagic" className={`text-xs ${linkStyle}`}>📸 Caption Magic</a>
          <a href="/DecisionCoach" className={`text-xs ${linkStyle}`}>🎯 Decision Coach</a>
        </div>
      </div>

      {/* Reset */}
      <button onClick={() => { setResults(null); setShowInputs(true); resetResults(); }} className={`px-4 py-2 rounded-lg text-sm font-medium ${c.btnSecondary}`}>
        🔄 New Date Night
      </button>
    </div>
    );
  };

  return (
    <div className={`space-y-4 ${c.text}`}>

      {/* Header card */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm`}>
        <div className="px-5 pt-5">
          <div className="pb-3 border-b border-zinc-500 flex items-start justify-between">
            <div>
              <h2 className={`text-xl font-bold ${c.text}`}>
                <span className="mr-2">{tool?.icon ?? '💘'}</span>{tool?.title ?? 'Date Night'}
              </h2>
              <p className={`text-sm ${c.textSecondary}`}>{tool?.tagline ?? 'Budget-smart evening plans that feel intentional, not improvised'}</p>
            </div>
            {results && !showInputs && (
              <button onClick={() => { setResults(null); setShowInputs(true); resetResults(); }}
                className={`ml-4 mt-0.5 px-3 py-1.5 rounded-lg text-xs font-medium flex-shrink-0 ${c.btnSecondary}`}>
                ↩ Start Over
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Pre-result cross-ref */}
      {!results && (
        <p className={`text-xs ${c.textMuted}`}>
          Need inspiration first?{' '}<a href="/DecisionCoach" className={linkStyle}>🎯 Decision Coach</a>{' '}
          can help you figure out what kind of evening fits the moment.
        </p>
      )}

      {/* Nav */}
      <div className="flex flex-wrap gap-2">
        {journal.length > 0 && <button onClick={() => setShowJournal(!showJournal)} className={`text-xs font-bold ${c.journalText}`}>📔 History ({journal.length})</button>}
        {journal.length >= 3 && <button onClick={handleRutDetect} disabled={rutLoading} className={`text-xs font-bold ${c.rutText}`}>{rutLoading ? <><span className="animate-spin inline-block">{tool?.icon ?? '💘'}</span></> : '🔍 Rut check'}</button>}
        <button onClick={() => { setShowJar(!showJar); if (!dateJar.length && location.trim()) handleDateJar(); }} className={`text-xs font-bold ${c.jarBtnText}`}>🫙 Date Jar</button>
        {prefs.liked?.length > 0 && <span className={`text-xs ${c.textMuteded}`}>🧠 {prefs.liked.length} prefs</span>}
      </div>

      {/* Rut result */}
      {rutResult && (
        <div className={`${c.altCard} border rounded-xl p-4 space-y-2`}>
          <div className="flex justify-between"><h4 className={`font-bold text-sm ${c.text}`}>🔍 Date Pattern Analysis</h4><button onClick={() => setRutResult(null)} className={`text-xs ${c.textMuteded}`}>✕</button></div>
          <p className={`text-sm ${c.textSecondary}`}>{rutResult.pattern_summary}</p>
          {rutResult.rut_detected && <div className={`${c.warning} border rounded-lg p-3 text-xs`}>⚠️ {rutResult.rut_description}</div>}
          {rutResult.missing_categories?.length > 0 && <p className={`text-xs ${c.textSecondary}`}>Missing: {rutResult.missing_categories.join(', ')}</p>}
          {(rutResult.suggestions || []).map((s, i) => <div key={i} className={`text-xs ${c.textSecondary}`}>💡 {s.idea} — {s.why}</div>)}
          {rutResult.encouragement && <p className={`text-xs italic ${c.textSecondary}`}>{rutResult.encouragement}</p>}
        </div>
      )}

      {/* Date Jar */}
      {showJar && (
        <div className={`${c.jarCard} border rounded-xl p-4 space-y-3`}>
          <div className="flex justify-between items-center">
            <h4 className={`font-bold text-sm ${c.text}`}>🫙 Date Jar — {dateJar.length} ideas</h4>
            <div className="flex gap-2">
              <button onClick={handleDateJar} disabled={jarLoading || !location.trim()} className={`text-xs font-bold ${c.roseText}`}>{jarLoading ? <><span className="animate-spin inline-block">{tool?.icon ?? '💘'}</span> Filling…</> : '🔄 Refill'}</button>
              <button onClick={() => setShowJar(false)} className={`text-xs ${c.textMuteded}`}>✕</button>
            </div>
          </div>
          {dateJar.length === 0 && !jarLoading && <p className={`text-xs ${c.textMuteded}`}>Enter a location above, then tap Refill to generate ideas.</p>}
          {dateJar.map((concept, i) => (
            <div key={i} className={`${c.card} border ${c.border} rounded-lg p-3 cursor-pointer hover:opacity-80`}
              onClick={() => { setDateType(concept.type || 'casual'); setShowJar(false); setShowInputs(true); }}>
              <div className="flex justify-between items-start">
                <p className={`text-sm font-bold ${c.text}`}>{concept.name}</p>
                <span className={`text-xs ${c.roseText}`}>{concept.estimated_budget}</span>
              </div>
              <p className={`text-xs ${c.textSecondary} mt-0.5`}>{concept.description}</p>
              <div className="flex gap-2 mt-1">
                {concept.vibe && <span className={`text-[10px] ${c.textMuteded}`}>✨ {concept.vibe}</span>}
                {concept.best_for && <span className={`text-[10px] ${c.textMuteded}`}>📅 {concept.best_for}</span>}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Journal */}
      {showJournal && (
        <div className={`${c.journalCard} border rounded-xl p-4 space-y-2`}>
          {journal.map(e => (
            <div key={e.id} className={`${c.card} border ${c.border} rounded-lg p-3`}>
              <div className="flex justify-between">
                <div className="flex-1 cursor-pointer" onClick={() => loadJournal(e)}>
                  <p className={`text-sm font-bold ${c.text}`}>{e.vibeTitle || 'Date'}</p>
                  <span className={`text-xs ${c.textMuteded}`}>{fmtDate(e.date)} · {e.location} · {fm(e.budget)}{e.rating ? ` · ${'⭐'.repeat(e.rating)}` : ''}</span>
                </div>
                <button onClick={() => setJournal(p => p.filter(j => j.id !== e.id))} className={`text-xs ${c.textMuteded}`}>🗑️</button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Recent plans (history) */}
      {history.length > 0 && !results && !liveMode && !showJournal && (
        <div className={`${c.card} border ${c.border} rounded-xl p-4 space-y-2`}>
          <p className={`text-xs font-bold uppercase tracking-wide ${c.textMuteded}`}>Recent plans</p>
          {history.map((h, i) => (
            <button
              key={i}
              onClick={() => { setResults(h.result); setShowInputs(false); resetResults(); }}
              className={`w-full text-left px-3 py-2 rounded-lg text-xs ${c.cardAlt} ${c.textSecondary} hover:opacity-80`}
            >
              {h.preview}{(h.preview?.length ?? 0) >= 40 ? '…' : ''}
            </button>
          ))}
        </div>
      )}

      {/* ═══ INPUT FORM ═══ */}
      {(!results || showInputs) && !liveMode && (
        <div className="space-y-4">
          {/* Date type */}
          <div className={`${c.card} border ${c.border} rounded-xl p-5`}>
            <div className={`border-b ${c.border} pb-3 mb-3`}>
              <p className={`text-xs font-bold ${c.textSecondary} uppercase`}>{tool?.icon ?? '💘'} What kind of date? <span className={c.required}>*</span></p>
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
              {DATE_TYPES.map(dt => (
                <button key={dt.id} onClick={() => setDateType(dateType === dt.id ? '' : dt.id)}
                  className={`p-3 rounded-lg border text-left ${dateType === dt.id ? c.chipOn : c.chipOff}`}>
                  <span className="text-xs font-bold">{dt.l}</span>
                  <p className={`text-[10px] mt-0.5 ${dateType === dt.id ? 'text-white/70' : c.textMuteded}`}>{dt.d}</p>
                </button>
              ))}
            </div>
            {isAnni && (
              <div className="mt-3 flex items-center gap-2">
                <input type="number" min={1} max={75} value={yearsTogether} onChange={e => setYearsTogether(Math.max(1, parseInt(e.target.value) || 1))} className={`w-20 px-3 py-2 rounded-lg border text-sm text-center ${c.input}`} />
                <span className={`text-xs ${c.textMuteded}`}>year{yearsTogether > 1 ? 's' : ''}</span>
              </div>
            )}
          </div>

          {/* Budget */}
          <div className={`${c.card} border ${c.border} rounded-xl p-5`}>
            <div className="flex justify-between mb-2">
              <p className={`text-xs font-bold ${c.textSecondary} uppercase`}>💰 Budget: <span className={c.roseText}>{fm(budget)}</span></p>
              <select value={currency} onChange={e => handleCurrencyChange(e.target.value)} className={`py-1 px-2 border rounded-lg text-xs ${c.input}`}>
                {CURRENCIES.map(cur => <option key={cur.s} value={cur.s}>{cur.f} {cur.l}</option>)}
              </select>
            </div>
            <div className="relative w-full h-6 flex items-center">
              <div className={`absolute left-0 right-0 h-2 rounded-full ${c.budgetBar}`}>
                <div className={`h-full rounded-full ${c.budgetFill}`} style={{ width: `${((budget - br.min) / (br.max - br.min)) * 100}%` }} />
              </div>
              <input type="range" min={br.min} max={br.max} step={br.step} value={budget} onChange={e => setBudget(Number(e.target.value))}
                className="absolute left-0 w-full h-2 cursor-pointer opacity-0" style={{ zIndex: 2 }} />
              <div className="absolute h-5 w-5 rounded-full bg-red-500 border-2 border-white shadow-md pointer-events-none" style={{ left: `calc(${((budget - br.min) / (br.max - br.min)) * 100}% - 10px)`, zIndex: 1 }} />
            </div>
            <div className="flex flex-wrap gap-1.5 mt-2">
              {presets.map(p => (
                <button key={p} onClick={() => setBudget(p)} className={`px-3 py-1.5 rounded-lg text-xs font-bold border ${budget === p ? c.chipOn : c.chipOff}`}>{fm(p)}</button>
              ))}
            </div>
          </div>

          {/* Location + Time + Duration + Weather */}
          <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-3`}>
            <div>
              <label className={`block text-xs font-bold ${c.textSecondary} uppercase mb-1`}>📍 Location <span className={c.required}>*</span></label>
              <input value={location} onChange={e => setLocation(e.target.value)} placeholder="City, neighborhood..." className={`w-full px-3 py-2.5 border rounded-lg text-sm ${c.input}`} />
            </div>
            <div>
              <p className={`text-xs font-bold ${c.textSecondary} uppercase mb-1`}>📅 When</p>
              <div className="flex gap-2 items-center flex-wrap">
                <button onClick={() => setPlannedDate('')}
                  className={`px-3 py-1.5 rounded-lg text-xs font-semibold border ${!plannedDate ? c.chipOn : c.chipOff}`}>
                  Tonight
                </button>
                <input
                  type="date"
                  value={plannedDate}
                  min={new Date(Date.now() + 86400000).toISOString().slice(0, 10)}
                  onChange={e => setPlannedDate(e.target.value)}
                  className={`px-3 py-1.5 border rounded-lg text-xs ${c.input}`}
                />
                {isFuture && <span className={`text-xs font-semibold ${c.roseText}`}>{daysUntil === 1 ? 'Tomorrow' : `${daysUntil} days away`}</span>}
              </div>
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div>
                <p className={`text-xs font-bold ${c.textSecondary} uppercase mb-1`}>🕐 Start</p>
                <select value={startTime} onChange={e => setStartTime(e.target.value)} className={`w-full py-2.5 px-3 border rounded-lg text-sm ${c.input}`}>
                  {START_TIMES.map(t => <option key={t} value={t}>{t}</option>)}
                </select>
              </div>
              <div>
                <p className={`text-xs font-bold ${c.textSecondary} uppercase mb-1`}>⏱️ Length</p>
                <Pill options={DURATION_OPTIONS} value={duration} setter={setDuration} />
              </div>
            </div>
            <div>
              <p className={`text-xs font-bold ${c.textSecondary} uppercase mb-1`}>🌙 Weather</p>
              <Pill options={WEATHER_OPTIONS} value={weather} setter={setWeather} />
            </div>
          </div>

          {/* Dietary + Restrictions */}
          <div className={`${c.card} border ${c.border} rounded-xl p-5`}>
            <button onClick={() => setShowDietary(!showDietary)} className={`text-xs font-bold ${c.textSecondary} uppercase`}>
              🍽️ Dietary {dietary.length > 0 ? `(${dietary.length})` : ''} {showDietary ? '▲' : '▼'}
            </button>
            {showDietary && (
              <div className="mt-2 space-y-2">
                <Pill options={DIETARY_OPTIONS} value={dietary} setter={toggleDietary} multi />
                <input value={restrictions} onChange={e => setRestrictions(e.target.value)} placeholder="Other restrictions..." className={`w-full px-3 py-2 border rounded-lg text-sm ${c.input}`} />
              </div>
            )}
          </div>

          {/* Partner prefs */}
          <div className={`${c.card} border ${c.border} rounded-xl p-5`}>
            <button onClick={() => setShowPartner(!showPartner)} className={`text-xs font-bold ${c.textSecondary} uppercase`}>
              👫 Partner Preferences {showPartner ? '▲' : '▼'}
            </button>
            {showPartner && (
              <div className="mt-3 space-y-3">
                <div>
                  <p className={`text-xs ${c.textMuteded} mb-1`}>What does your partner enjoy?</p>
                  <input value={partnerPrefs.partnerLikes} onChange={e => setPartnerPrefs(p => ({ ...p, partnerLikes: e.target.value }))} placeholder="Live music, cozy spots, Italian food..." className={`w-full px-3 py-2 border rounded-lg text-sm ${c.input}`} />
                </div>
                <div>
                  <p className={`text-xs ${c.textMuteded} mb-1`}>What do they dislike?</p>
                  <input value={partnerPrefs.partnerDislikes} onChange={e => setPartnerPrefs(p => ({ ...p, partnerDislikes: e.target.value }))} placeholder="Loud clubs, crowded places, spicy food..." className={`w-full px-3 py-2 border rounded-lg text-sm ${c.input}`} />
                </div>
                <div>
                  <p className={`text-xs ${c.textMuteded} mb-1`}>Noise level</p>
                  <Pill options={NOISE_OPTIONS} value={partnerPrefs.noiseLevel} setter={v => setPartnerPrefs(p => ({ ...p, noiseLevel: v }))} />
                </div>
                <div>
                  <p className={`text-xs ${c.textMuteded} mb-1`}>Energy level</p>
                  <Pill options={ENERGY_OPTIONS} value={partnerPrefs.energyLevel} setter={v => setPartnerPrefs(p => ({ ...p, energyLevel: v }))} />
                </div>
              </div>
            )}
          </div>

          {/* Last time */}
          <div className={`${c.card} border ${c.border} rounded-xl p-5`}>
            <p className={`text-xs font-bold ${c.textSecondary} uppercase mb-1`}>🔁 Last time? <span className={c.textMuteded}>(optional)</span></p>
            <input value={lastTime} onChange={e => setLastTime(e.target.value)} placeholder="Sushi and a movie..." className={`w-full px-3 py-2.5 border rounded-lg text-sm ${c.input}`} />
          </div>

          {prefs.liked?.length > 0 && (
            <div className={`${c.accentCard} border ${c.border} rounded-lg p-3`}>
              <p className={`text-xs ${c.roseText}`}>🧠 You enjoy: {prefs.liked.slice(0, 4).join(', ')}</p>
            </div>
          )}

          {error && <div className={`${c.danger} border rounded-xl p-4 text-sm`}>⚠️ {error}</div>}

          <button onClick={generate} disabled={loading || !location.trim() || !dateType}
            className={`w-full py-3.5 rounded-xl font-bold text-sm ${c.btnAction} disabled:opacity-40`}>
            {loading
              ? <><span className="animate-spin inline-block mr-2">{tool?.icon ?? '💘'}</span>Planning…</>
              : isAnni
                ? <><span className="mr-1">{tool?.icon ?? '💘'}</span>Plan {yearsTogether}-Year Anniversary{isFuture ? ` · ${plannedDateLabel}` : ''}</>
                : isFuture
                  ? <><span className="mr-1">{tool?.icon ?? '💘'}</span>Plan Date for {plannedDateLabel}</>
                  : <><span className="mr-1">{tool?.icon ?? '💘'}</span>Plan My Date Night</>}
          </button>
          <p className={`text-xs text-center ${c.textMuteded}`}>Cmd+Enter to plan</p>
        </div>
      )}

      {renderResults()}


      {/* ═══ LIVE DATE MODE ═══ */}
      {liveMode && (results != null) && (() => {
        const stops = results.itinerary || [];
        const cur = stops[liveStep];
        if (!cur) return null;
        const progress = stops.length > 0 ? ((liveStep + 1) / stops.length) * 100 : 0;

        const liveEl = (
          <div className="space-y-4">
            <div className={`${c.liveCard} border-2 rounded-2xl p-5`}>
              <div className="flex justify-between items-center mb-3">
                <h3 className={`font-bold text-sm ${c.text}`}>▶️ Date Night Live</h3>
                <button onClick={() => setLiveMode(false)} className={`text-xs font-bold ${c.textMuteded}`}>✕ Exit</button>
              </div>
              <div className={`w-full h-2 rounded-full ${c.budgetBar} mb-2`}>
                <div className="h-full rounded-full bg-red-500 transition-all" style={{ width: `${progress}%` }} />
              </div>
              <div className="flex justify-between">
                <p className={`text-xs ${c.textMuteded}`}>Stop {liveStep + 1} of {stops.length}</p>
                {timeOffset !== 0 && <p className={`text-xs ${c.roseText}`}>{timeOffset > 0 ? `+${timeOffset}` : timeOffset}min</p>}
              </div>
            </div>

            {/* Time adjuster */}
            <div className="flex items-center gap-2">
              <span className={`text-xs ${c.textSecondary}`}>Running late?</span>
              {[15, 30, -15].map(m => (
                <button key={m} onClick={() => setTimeOffset(p => p + m)} className={`px-2 py-1 rounded text-xs ${c.btnSecondary} border ${c.border}`}>{m > 0 ? '+' : ''}{m}m</button>
              ))}
              {timeOffset !== 0 && <button onClick={() => setTimeOffset(0)} className={`text-xs ${c.textMuteded}`}>Reset</button>}
            </div>

            {/* Current stop */}
            <div className={`${c.card} border-2 ${c.roseBorder} rounded-2xl p-5 space-y-3`}>
              <div className="flex justify-between">
                <div>
                  <p className={`text-xs font-bold ${c.roseText} mb-1`}>NOW</p>
                  <h3 className={`text-lg font-bold ${c.text}`}>{stopEmoji(cur.stop_type)} {cur.venue_name}</h3>
                </div>
                <span className={`text-sm font-bold ${c.roseText}`}>~{fm(cur.estimated_cost)}</span>
              </div>
              <p className={`text-sm ${c.text}`}>{cur.description}</p>
              {cur.dress_vibe && <p className={`text-sm font-bold ${c.textSecondary}`}>👗 {cur.dress_vibe}</p>}
              {cur.pro_tip && <div className={`text-sm p-3 rounded-lg border ${c.warning}`}>💡 {cur.pro_tip}</div>}
              {cur.anniversary_touch && <div className={`text-sm p-3 rounded-lg border ${c.accentCard} ${c.border}`}>💍 {cur.anniversary_touch}</div>}
            </div>

            {/* Plan B for this stop */}
            {cur.plan_b && (
              <div className={`${c.infoCard} border rounded-xl p-3`}>
                <p className={`text-xs font-bold mb-0.5`}>🔄 If this doesn't work:</p>
                <p className={`text-xs`}>{cur.plan_b}</p>
              </div>
            )}

            {/* Swap mid-date */}
            <button onClick={() => swapStop(cur.stop_number || liveStep + 1)} disabled={swapping === (cur.stop_number || liveStep + 1) || loading}
              className={`w-full py-2 rounded-xl text-xs font-bold ${c.btnSecondary} border ${c.border}`}>
              {swapping ? <><span className="animate-spin inline-block mr-1">{tool?.icon ?? '💘'}</span>Finding replacement…</> : '🔄 This stop isn\'t working — swap it'}
            </button>

            {/* Next stop preview */}
            {liveStep < stops.length - 1 && (
              <div className={`${c.altCard} border ${c.border} rounded-xl p-3`}>
                <p className={`text-xs font-bold ${c.text} mb-1`}>Up next: {stopEmoji(stops[liveStep + 1].stop_type)} {stops[liveStep + 1].venue_name}</p>
                <p className={`text-xs ${c.textMuteded}`}>{stops[liveStep + 1].time}{timeOffset ? ` (adj: ~${timeOffset > 0 ? '+' : ''}${timeOffset}m)` : ''}</p>
                {results?.transportation != null && <p className={`text-xs ${c.textSecondary} mt-1`}>🚶 {results.transportation}</p>}
              </div>
            )}

            {/* Nav */}
            <div className="flex gap-2">
              {liveStep > 0 && <button onClick={() => setLiveStep(p => p - 1)} className={`flex-1 py-3 rounded-xl text-sm font-bold ${c.btnSecondary} border ${c.border}`}>← Back</button>}
              {liveStep < stops.length - 1
                ? <button onClick={() => setLiveStep(p => p + 1)} className={`flex-1 py-3 rounded-xl text-sm font-bold ${c.btnAction}`}>Next stop →</button>
                : <button onClick={() => { setLiveMode(false); setShowRate(true); }} className={`flex-1 py-3 rounded-xl text-sm font-bold ${c.btnAction}`}>🎉 Finish & Rate</button>}
            </div>
          </div>
        );
        return liveEl;
      })()}

      {/* Favorites list */}
      {favorites.length > 0 && !results && !liveMode && (
        <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
          <p className={`text-xs font-bold ${c.roseText} mb-2`}>❤️ Saved Venues ({favorites.length})</p>
          <div className="space-y-1">
            {favorites.slice(0, 6).map((f, i) => (
              <div key={i} className="flex justify-between text-xs">
                <span className={c.text}>{stopEmoji(f.stop_type)} {f.venue_name}</span>
                <button onClick={() => setFavorites(p => p.filter(x => x.venue_name !== f.venue_name))} className={c.textMuteded}>✕</button>
              </div>
            ))}
          </div>
          {favorites.length > 6 && <p className={`text-xs ${c.textMuteded} mt-1`}>+{favorites.length - 6} more</p>}
          <p className={`text-xs ${c.textMuteded} mt-2`}>These are factored into future plans.</p>
        </div>
      )}

      {/* Error */}
      {error && <div className={`${c.danger} border rounded-xl p-4 text-sm`}>⚠️ {error}</div>}
    </div>
  );
};

DateNight.displayName = 'DateNight';
export default DateNight;
