import React, { useState, useCallback } from 'react';
import Caret from '../components/Caret';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useRegisterActions } from '../components/ActionBarContext';
import { usePersistentState } from '../hooks/usePersistentState';
import { useTheme } from '../hooks/useTheme';
import { useTranslation } from '../i18n/useTranslation';
import { formatDate } from '../utils/formatLocale';
import { pickExample } from '../utils/exampleRotation';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

const EXAMPLES = [
  {
  mode: 'single',
  description: "I was running late to a flight but the airport kept rearranging itself. Every time I found my gate it had moved. My old college roommate was there, but she didn't recognize me. Eventually I realized I'd forgotten my passport — and also forgotten where I was supposed to be flying to.",
},
  {
  mode: 'single',
  description: "I was in my grandmother's house, except it had a whole wing I'd never seen. Room after room, all furnished, dust on everything, like they'd been waiting. I kept thinking I should be surprised and instead I felt calm, almost relieved. In the last room there was a piano nobody in my family ever played.",
},
];;

const DreamPatternSpotter = ({ tool }) => {
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();

  const c = {
    required:      isDark ? 'text-amber-400' : 'text-amber-700',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-300 text-red-800',
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-400' : 'text-gray-500',
    input:         isDark ? 'bg-zinc-900 border-zinc-700 text-zinc-50 placeholder:text-zinc-500 focus:border-cyan-500 focus:ring-cyan-500/20' : 'bg-white border-gray-300 text-gray-900 placeholder:text-gray-400 focus:border-cyan-500',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-100' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    // Bespoke dream-themed keys
    deleteHover: isDark ? 'hover:text-red-400' : 'hover:text-red-600',
    labelText:   isDark ? 'text-zinc-200' : 'text-gray-700',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';

  // Mode selection
  const [mode, setMode] = useState('single'); // 'single' or 'pattern'

  // Single dream state
  const [singleDream, setSingleDream] = useState({
    description: '',
    date: new Date().toISOString().split('T')[0],
    emotions: {
      anxious: false,
      happy: false,
      scared: false,
      confused: false,
      excited: false,
      sad: false,
      neutral: false,
    },
    lifeContext: '',
  });

  // Multi-dream state — persisted so the dream journal survives refresh
  const [dreams, setDreams] = usePersistentState('dps-dreams', [
    {
      id: 1,
      description: '',
      date: new Date().toISOString().split('T')[0],
      emotions: [],
      lifeContext: '',
    }
  ]);

  // Results state
  const [results, setResults] = usePersistentState('dps-results', null);
  const [sessionHistory, setSessionHistory] = usePersistentState('dps-history', []);
  const [error, setError] = useState('');
  const resultsRef = React.useRef(null);


  const emotionOptions = [
    { key: 'anxious',  label: t('dps_emotion_anxious') },
    { key: 'happy',    label: t('dps_emotion_happy') },
    { key: 'scared',   label: t('dps_emotion_scared') },
    { key: 'confused', label: t('dps_emotion_confused') },
    { key: 'excited',  label: t('dps_emotion_excited') },
    { key: 'sad',      label: t('dps_emotion_sad') },
    { key: 'neutral',  label: t('dps_emotion_neutral') },
  ];

  const handleSingleDreamAnalyze = async () => {
    if (!singleDream.description.trim()) {
      setError(t('dps_err_describe'));
      return;
    }

    const selectedEmotions = Object.keys(singleDream.emotions).filter(key => singleDream.emotions[key]);

    setError('');
    setResults(null);

    try {
      const data = await callToolEndpoint('dream-pattern-spotter-single', {
        description: singleDream.description.trim(),
        date: singleDream.date,
        emotions: selectedEmotions,
        lifeContext: singleDream.lifeContext.trim() || null,
        userLocale, userCurrency, userRegion,
      });
      
      const entry = {
        id: Date.now().toString(),
        date: new Date().toISOString(),
        mode: 'single',
        preview: singleDream.description.trim().slice(0, 60),
        input: { singleDream: { ...singleDream }, dreams: [] },
        results: data,
      };
      // Exception (PF-25): journal history — users revisit past analyses; 6 would lose the journal.
      setSessionHistory(prev => [entry, ...prev].slice(0, 50));
      setResults(data);
    } catch (err) {
      setError(err.message || t('dps_err_single_fail'));
    }
  };

  const handlePatternAnalyze = async () => {
    const validDreams = dreams.filter(d => d.description.trim());
    
    if (validDreams.length < 2) {
      setError(t('dps_err_two_dreams'));
      return;
    }

    setError('');
    setResults(null);

    try {
      const data = await callToolEndpoint('dream-pattern-spotter-pattern', {
        dreams: validDreams.map(d => ({
          description: d.description.trim(),
          date: d.date,
          emotions: d.emotions,
          lifeContext: d.lifeContext.trim() || null,
        })),
        userLocale, userCurrency, userRegion,
      });
      
      const entry = {
        id: Date.now().toString(),
        date: new Date().toISOString(),
        mode: 'pattern',
        preview: validDreams[0].description.trim().slice(0, 60),
        dreamCount: validDreams.length,
        input: { singleDream: null, dreams: [...dreams] },
        results: data,
      };
      setSessionHistory(prev => [entry, ...prev].slice(0, 10)); // PF-25 exception: pattern analysis requires 2+ dreams; 10 entries needed to surface meaningful patterns
      setResults(data); setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth' }), 100);
    } catch (err) {
      setError(err.message || t('dps_err_pattern_fail'));
    }
  };

  const addDream = () => {
    setDreams([...dreams, {
      id: Date.now(),
      description: '',
      date: new Date().toISOString().split('T')[0],
      emotions: [],
      lifeContext: '',
    }]);
  };

  const removeDream = (id) => {
    setDreams(dreams.filter(d => d.id !== id));
  };

  const updateDream = (id, field, value) => {
    setDreams(dreams.map(d => d.id === id ? { ...d, [field]: value } : d));
  };

  const loadExample = useCallback(() => {
    const ex = pickExample('DreamPatternSpotter', EXAMPLES);
    setMode(ex.mode);
    // Preserve every field of the state's initial shape (emotions object, lifeContext) —
    // replacing the whole object crashes the emotion checkboxes.
    setSingleDream(prev => ({
      ...prev,
      description: ex.description,
      date: new Date().toISOString().slice(0, 10),
    }));
    setResults(null);
  }, [setSingleDream, setResults]);

  const handleReset = () => {
    setSingleDream({
      description: '',
      date: new Date().toISOString().split('T')[0],
      emotions: {
        anxious: false,
        happy: false,
        scared: false,
        confused: false,
        excited: false,
        sad: false,
        neutral: false,
      },
      lifeContext: '',
    });
    setDreams([{
      id: 1,
      description: '',
      date: new Date().toISOString().split('T')[0],
      emotions: [],
      lifeContext: '',
    }]);
    setResults(null);
    setError('');
  };

  const buildExportText = React.useCallback(() => {
    if (!results) return '';
    const lines = [t('dps_copy_header'), ''];
    // Single dream fields
    if (results?.dream_classification) {
      lines.push(`${t('dps_copy_type')}: ${results.dream_classification.type || ''} · ${t('dps_copy_intensity')}: ${results.dream_classification.intensity || ''}`);
    }
    if (results?.insights?.overall_assessment) lines.push('', t('dps_copy_overall'), results.insights.overall_assessment);
    if (results?.insights?.therapeutic_value) lines.push('', t('dps_copy_therapeutic'), results.insights.therapeutic_value);
    if (results?.insights?.growth_areas) lines.push('', t('dps_copy_growth'), results.insights.growth_areas);
    // Themes
    const themes = results?.pattern_analysis?.recurring_themes || results?.themes;
    if (themes?.length) {
      lines.push('', t('dps_copy_themes'));
      themes.forEach((th, i) => lines.push(`${i + 1}. ${th.theme}`, th.possible_meaning || ''));
    }
    // Symbols
    const symbols = results?.pattern_analysis?.recurring_symbols || results?.symbols;
    if (symbols?.length) {
      lines.push('', t('dps_copy_symbols'));
      symbols.forEach(s => lines.push(`• ${s.symbol}`, s.context_in_dream || ''));
    }
    if (results?.emotional_significance?.emotional_processing) {
      lines.push('', t('dps_copy_emotional_processing'), results.emotional_significance.emotional_processing);
    }
    if (results?.nightmare_analysis?.is_nightmare) {
      lines.push('', t('dps_copy_nightmare'));
      lines.push(`${t('dps_copy_severity')}: ${results.nightmare_analysis.severity || ''}`);
      lines.push(`${t('dps_copy_type')}: ${results.nightmare_analysis.nightmare_type || ''}`);
    }
    if (results?.reflection_questions?.length) {
      lines.push('', t('dps_copy_reflection'));
      results.reflection_questions.forEach(q => lines.push(`• ${q}`));
    }
    if (results?.therapist_export_summary) {
      const tx = results.therapist_export_summary;
      lines.push('', t('dps_copy_therapist_header'));
      if (tx.classification) lines.push(`${t('dps_copy_classification')}: ${tx.classification}`);
      if (tx.emotional_content) lines.push(`${t('dps_copy_emotional_content')}: ${tx.emotional_content}`);
      if (tx.trauma_indicators) lines.push(`${t('dps_copy_trauma')}: ${tx.trauma_indicators}`);
      if (tx.clinical_relevance) lines.push(`${t('dps_copy_clinical')}: ${tx.clinical_relevance}`);
      if (tx.recommended_exploration) lines.push(`${t('dps_copy_rec_exploration')}: ${tx.recommended_exploration}`);
      if (tx.clinical_priority_areas?.length) lines.push(`${t('dps_copy_priority')}: ${tx.clinical_priority_areas.join(', ')}`);
      if (tx.recommended_interventions?.length) lines.push(`${t('dps_copy_interventions')}: ${tx.recommended_interventions.join(', ')}`);
    }
    return lines.join('\n') + BRAND;
  }, [results, t]);

  useRegisterActions(buildExportText(), tool?.title || 'Dream Pattern Spotter');

  // ── Keyboard handler (after handlers to avoid TDZ) ──
  const handleSingleRef = React.useRef(null);
  const handlePatternRef = React.useRef(null);
  const canSubmitRef = React.useRef(false);
  handleSingleRef.current = handleSingleDreamAnalyze;
  handlePatternRef.current = handlePatternAnalyze;
  canSubmitRef.current = !loading;

  React.useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && canSubmitRef.current) {
        if (mode === 'pattern') handlePatternRef.current?.();
        else handleSingleRef.current?.();
      }
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mode]);

  return (
    <div className={`space-y-4 ${c.text}`}>
      <div className="max-w-4xl mx-auto space-y-4">

        {/* Header */}
        <div className={`${c.card} border ${c.border} rounded-xl shadow-sm px-5 pt-2.5 pb-5`}>
          <div className="pb-3 border-b border-zinc-500">
            <div className="flex items-start justify-between gap-3">
              <div>
                {/* PF-30 — the wrapper already prints the name as the page <h1>. */}
                <p className={`text-base ${c.textSecondary}`}>
                  <span className="me-2 text-lg">{tool?.icon ?? '🌙'}</span>{t('dps_tagline')}
                </p>
                <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className="mt-2 px-4 py-2 rounded-full text-sm font-semibold border border-black/25 text-zinc-900 shadow-sm hover:brightness-105 hover:shadow transition disabled:opacity-40 whitespace-nowrap">✨ {t('try_example')}</button>
              </div>
              {(results || singleDream.description.trim() || dreams.some(d => d.description.trim())) && (
                <button onClick={handleReset} className={`${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs font-bold flex-shrink-0`}>
                  ↺ {t('start_over')}
                </button>
              )}
            </div>
          </div>
        </div>

        {/* Mode Selection */}
        <div className={`${c.card} border rounded-xl shadow-sm p-6`}>
          <h3 className={`text-lg font-bold ${c.text} mb-4`}>{t('dps_mode_title')}</h3>
          <div className="grid grid-cols-2 gap-4">
            <button
              onClick={() => setMode('single')}
              className={`p-4 border-2 rounded-lg transition-colors ${
                mode === 'single'
                  ? isDark
                    ? 'border-cyan-500 bg-cyan-900/20'
                    : 'border-cyan-500 bg-cyan-50'
                  : isDark
                    ? 'border-zinc-700 hover:border-zinc-600'
                    : 'border-gray-200 hover:border-gray-300'
              }`}
            >
              <span className="text-2xl block mb-1">🌙</span>
              <h4 className={`font-semibold ${c.text} mb-1`}>{t('dps_mode_single')}</h4>
              <p className={`text-xs ${c.textMuteded}`}>{t('dps_mode_single_desc')}</p>
            </button>
            
            <button
              onClick={() => setMode('pattern')}
              className={`p-4 border-2 rounded-lg transition-colors ${
                mode === 'pattern'
                  ? isDark
                    ? 'border-cyan-500 bg-cyan-900/20'
                    : 'border-cyan-500 bg-cyan-50'
                  : isDark
                    ? 'border-zinc-700 hover:border-zinc-600'
                    : 'border-gray-200 hover:border-gray-300'
              }`}
            >
              <span className="text-2xl block mb-1">📊</span>
              <h4 className={`font-semibold ${c.text} mb-1`}>{t('dps_mode_pattern')}</h4>
              <p className={`text-xs ${c.textMuteded}`}>{t('dps_mode_pattern_desc')}</p>
            </button>
          </div>
        </div>

        {/* Single Dream Mode */}
        {mode === 'single' && (
          <div className={`${c.card} border rounded-xl shadow-sm p-6`}>
            <h3 className={`text-lg font-bold ${c.text} mb-4`}>{t('dps_describe_title')}</h3>

            <div className="space-y-6">
              {/* Dream Description */}
              <div>
                <p className={`text-xs ${c.textMuted} mb-3`}>
                  {t('dps_xref_feeling_pre')} <a href="/NameThatFeeling" className={linkStyle}>🎭 {t('dps_xref_namethatfeeling')}</a> {t('dps_xref_feeling_post')}
                </p>
                <label htmlFor="dream" className={`block text-sm font-medium ${c.textSecondary} mb-2`}>
                  {t('dps_dream_label')} *
                </label>
                <textarea
                  id="dream"
                  value={singleDream.description}
                  onChange={(e) => setSingleDream(prev => ({ ...prev, description: e.target.value }))}
                  placeholder={t('dps_dream_ph')}
                  className={`w-full h-48 p-4 border-2 rounded-lg ${c.input} outline-none focus:ring-2 resize-none`}
                />
              </div>

              {/* Date */}
              <div>
                <label htmlFor="date" className={`block text-sm font-medium ${c.textSecondary} mb-2`}>
                  {t('dps_date_label')}
                </label>
                <input
                  type="date"
                  id="date"
                  value={singleDream.date}
                  onChange={(e) => setSingleDream(prev => ({ ...prev, date: e.target.value }))}
                  className={`p-3 border rounded-lg ${c.input} outline-none focus:ring-2`}
                />
              </div>

              {/* Emotional Tone */}
              <div>
                <label className={`block text-sm font-medium ${c.textSecondary} mb-3`}>
                  {t('dps_tone_label')}
                </label>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                  {emotionOptions.map(emotion => (
                    <label
                      key={emotion.key}
                      className={`flex items-center gap-2 p-3 border-2 rounded-lg cursor-pointer transition-colors ${
                        singleDream.emotions[emotion.key]
                          ? isDark
                            ? 'border-cyan-500 bg-cyan-900/20'
                            : 'border-cyan-500 bg-cyan-50'
                          : isDark
                            ? 'border-zinc-700 hover:border-zinc-600'
                            : 'border-gray-200 hover:border-gray-300'
                      }`}
                    >
                      <input
                        type="checkbox"
                        checked={singleDream.emotions[emotion.key]}
                        onChange={() => setSingleDream(prev => ({
                          ...prev,
                          emotions: {
                            ...prev.emotions,
                            [emotion.key]: !prev.emotions[emotion.key]
                          }
                        }))}
                        className="w-4 h-4 rounded accent-cyan-500"
                      />
                      <span className="text-sm">{emotion.label}</span>
                    </label>
                  ))}
                </div>
              </div>

              {/* Life Context */}
              <div>
                <label htmlFor="context" className={`block text-sm font-medium ${c.textSecondary} mb-2`}>
                  {t('dps_context_label')}
                </label>
                <textarea
                  id="context"
                  value={singleDream.lifeContext}
                  onChange={(e) => setSingleDream(prev => ({ ...prev, lifeContext: e.target.value }))}
                  placeholder={t('dps_context_ph')}
                  className={`w-full h-24 p-4 border-2 rounded-lg ${c.input} outline-none focus:ring-2 resize-none`}
                />
              </div>

              {/* Action Button */}
          <button
              onClick={handleSingleDreamAnalyze}
              disabled={loading}
              className={`w-full ${c.btnPrimary} disabled:opacity-40 py-3 px-6 rounded-lg font-semibold transition-colors flex items-center justify-center gap-2`}
              >
              {loading ? (
                <>
                  <span className="animate-spin inline-block">{tool?.icon ?? '🌙'}</span>
                  {t('dps_analyzing_dream')}
                </>
              ) : (
                <>
                  <span>🌙</span>
                  {t('dps_analyze_dream')}
                </>
              )}
              </button>
            </div>
          </div>
        )}

        {/* Pattern Analysis Mode */}
        {mode === 'pattern' && (
          <div className={`${c.card} border rounded-xl shadow-sm p-6`}>
            <div className="flex items-center justify-between mb-4">
              <h3 className={`text-lg font-bold ${c.text}`}>{t('dps_add_dreams_title')}</h3>
              <button
                onClick={addDream}
                className={`${c.btnSecondary} py-2 px-4 rounded-lg text-sm flex items-center gap-2`}
              >
                <span>+</span>
                {t('dps_add_dream')}
              </button>
            </div>

            <div className="space-y-6">
              {dreams.map((dream, index) => (
                <div key={dream.id} className={`${c.cardAlt} border rounded-lg p-4`}>
                  <div className="flex items-center justify-between mb-3">
                    <h4 className={`font-semibold ${c.text}`}>{t('dps_dream_n', { n: index + 1 })}</h4>
                    {dreams.length > 1 && (
                      <button
                        onClick={() => removeDream(dream.id)}
                        className={`text-red-500 ${c.deleteHover}`}
                      >
                        <span>🗑️</span>
                      </button>
                    )}
                  </div>

                  <div className="space-y-3">
                    <textarea
                      value={dream.description}
                      onChange={(e) => updateDream(dream.id, 'description', e.target.value)}
                      placeholder={t('dps_dream_short_ph')}
                      className={`w-full h-32 p-3 border rounded-lg ${c.input} outline-none focus:ring-2 resize-none text-sm`}
                    />

                    <input
                      type="date"
                      value={dream.date}
                      onChange={(e) => updateDream(dream.id, 'date', e.target.value)}
                      className={`p-2 border rounded-lg ${c.input} outline-none focus:ring-2 text-sm`}
                    />
                  </div>
                </div>
              ))}
            </div>

            {/* Action Button */}
            <div className="flex gap-2">
          <button title={t('cmd_enter')}
              onClick={handlePatternAnalyze}
              disabled={loading}
              className={`relative w-full ${c.btnPrimary} py-3 px-6 rounded-lg font-semibold transition-colors flex items-center justify-center gap-2 mt-6`}
            >
              {loading ? (
                <>
                  <span className="animate-spin inline-block">{tool?.icon ?? '🌙'}</span>
                  {t('dps_analyzing_patterns')}
                </>
              ) : (
                <>
                  <span>📊</span>
                  {t('dps_analyze_patterns')}
                </>
              )}
            {!loading && (
            <kbd aria-hidden="true"
              className="hidden sm:flex items-center absolute end-3 top-1/2 -translate-y-1/2 px-1.5 py-0.5 rounded border border-white/30 bg-white/15 text-[10px] font-bold tracking-wide">
              ⌘↵
            </kbd>
          )}
          </button>
          <button
            onClick={loadExample}
            className={`px-4 py-3 rounded-lg text-xs font-bold ${c.btnSecondary}`}
          >
          </button>
        </div>
          </div>
        )}

        {/* Error */}
        {error && (
          <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-700 rounded-lg p-4">
            <p className="text-sm text-red-700 dark:text-red-300">{error}</p>
          </div>
        )}

        {/* Results */}
        {results && (
          <div data-copy-results ref={resultsRef} className="space-y-6">

            {/* ── Single dream: seven sections, in the order a reader wants
                   them — what happened, what is notable, what it might be
                   about, other traditions, the life they actually told us
                   about, questions, and what to watch for next time. ── */}
            {results.at_a_glance && (
              <div className={`${c.card} border rounded-xl shadow-sm p-6`}>
                <h3 className={`text-sm font-bold uppercase tracking-wide ${c.textMuteded} mb-2`}>{t('dps_at_a_glance')}</h3>
                <p className={`text-base ${c.text}`}>{results.at_a_glance}</p>
              </div>
            )}

            {!!results.what_stands_out?.length && (
              <div className={`${c.card} border rounded-xl shadow-sm p-6`}>
                <h3 className={`text-sm font-bold uppercase tracking-wide ${c.textMuteded} mb-3`}>{t('dps_stands_out')}</h3>
                <div className="space-y-3">
                  {results.what_stands_out.map((x, i) => (
                    <div key={i} className={`${c.cardAlt} border rounded-lg p-3`}>
                      <p className={`text-sm font-semibold ${c.text}`}>{x.element}</p>
                      {x.why_it_stands_out && <p className={`text-sm ${c.textSecondary} mt-1`}>{x.why_it_stands_out}</p>}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {!!results.possible_associations?.length && (
              <div className={`${c.card} border rounded-xl shadow-sm p-6`}>
                <h3 className={`text-sm font-bold uppercase tracking-wide ${c.textMuteded} mb-3`}>{t('dps_associations')}</h3>
                <div className="space-y-3">
                  {results.possible_associations.map((x, i) => (
                    <div key={i} className={`${c.cardAlt} border rounded-lg p-3`}>
                      <p className={`text-sm font-semibold ${c.text} mb-1`}>{x.element}</p>
                      <ul className={`text-sm ${c.textSecondary} space-y-1 list-disc ps-5`}>
                        {(x.possibilities || []).map((pp, j) => <li key={j}>{pp}</li>)}
                      </ul>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {results.different_lenses && (
              <details className={`group ${c.card} border rounded-xl shadow-sm p-4`}>
                <summary className="cursor-pointer list-none [&::-webkit-details-marker]:hidden">
                  <div className={`flex items-center gap-2 text-sm font-bold uppercase tracking-wide ${c.textMuteded}`}>
                    {t('dps_lenses')}
                    <Caret groupOpen className="ms-auto" />
                  </div>
                </summary>
                <div className="mt-3 space-y-3">
                  {[['dps_lens_jung', results.different_lenses.jungian],
                    ['dps_lens_freud', results.different_lenses.freudian],
                    ['dps_lens_science', results.different_lenses.dream_science]].map(([k, v]) => v ? (
                    <div key={k} className={`${c.cardAlt} border rounded-lg p-3`}>
                      <p className={`text-xs font-bold ${c.textMuteded} mb-1`}>{t(k)}</p>
                      <p className={`text-sm ${c.textSecondary}`}>{v}</p>
                    </div>
                  ) : null)}
                </div>
              </details>
            )}

            {!!results.connections_to_your_life?.length && (
              <div className={`${c.card} border rounded-xl shadow-sm p-6`}>
                <h3 className={`text-sm font-bold uppercase tracking-wide ${c.textMuteded} mb-3`}>{t('dps_life_conn')}</h3>
                <ul className={`text-sm ${c.textSecondary} space-y-2 list-disc ps-5`}>
                  {results.connections_to_your_life.map((x, i) => <li key={i}>{x}</li>)}
                </ul>
              </div>
            )}

            {!!results.questions_worth_sitting_with?.length && (
              <div className={`${c.card} border rounded-xl shadow-sm p-6`}>
                <h3 className={`text-sm font-bold uppercase tracking-wide ${c.textMuteded} mb-3`}>{t('dps_questions_title')}</h3>
                <ul className={`text-sm ${c.text} space-y-2 list-disc ps-5`}>
                  {results.questions_worth_sitting_with.map((x, i) => <li key={i}>{x}</li>)}
                </ul>
              </div>
            )}

            {!!results.patterns_to_watch?.length && (
              <div className={`${c.card} border rounded-xl shadow-sm p-6`}>
                <h3 className={`text-sm font-bold uppercase tracking-wide ${c.textMuteded} mb-3`}>{t('dps_watch')}</h3>
                <ul className={`text-sm ${c.textSecondary} space-y-2 list-disc ps-5`}>
                  {results.patterns_to_watch.map((x, i) => <li key={i}>{x}</li>)}
                </ul>
              </div>
            )}

            {/* ── Pattern mode: counting, with the count shown. ── */}
            {[['dps_rec_elements', results.recurring_elements, 'element'],
              ['dps_rec_emotions', results.recurring_emotions, 'emotion'],
              ['dps_rec_narrative', results.recurring_narrative_patterns, 'pattern']].map(([label, list, key]) => (
              Array.isArray(list) && list.length > 0 ? (
                <div key={label} className={`${c.card} border rounded-xl shadow-sm p-6`}>
                  <h3 className={`text-sm font-bold uppercase tracking-wide ${c.textMuteded} mb-3`}>{t(label)}</h3>
                  <div className="space-y-2">
                    {list.map((x, i) => (
                      <div key={i} className={`${c.cardAlt} border rounded-lg p-3 flex items-baseline justify-between gap-3`}>
                        <span className={`text-sm font-semibold ${c.text}`}>{x[key]}</span>
                        <span className={`text-xs ${c.textMuteded} whitespace-nowrap`}>{t('dps_in_n_of', { n: x.count, of: x.of })}</span>
                      </div>
                    ))}
                  </div>
                </div>
              ) : null
            ))}

            {!!results.possible_connections?.length && (
              <div className={`${c.card} border rounded-xl shadow-sm p-6`}>
                <h3 className={`text-sm font-bold uppercase tracking-wide ${c.textMuteded} mb-3`}>{t('dps_possible_conn')}</h3>
                <ul className={`text-sm ${c.textSecondary} space-y-2 list-disc ps-5`}>
                  {results.possible_connections.map((x, i) => <li key={i}>{x}</li>)}
                </ul>
              </div>
            )}

            {results.limits && (
              <div className={`${c.cardAlt} border rounded-xl p-4`}>
                <p className={`text-xs font-bold uppercase tracking-wide ${c.textMuteded} mb-1`}>{t('dps_limits')}</p>
                <p className={`text-sm ${c.textSecondary}`}>{results.limits}</p>
              </div>
            )}

            {/* Cross-references */}
            <p className={`text-xs ${c.textMuteded} text-center`}>
              {t('dps_xref_ego_pre')}{' '}<a href="/BeliefStressTest" className={linkStyle}>{t('dps_xref_egokiller')}</a>{' '}
              {t('dps_xref_ego_post')}
            </p>
          </div>
        )}
      </div>
        {sessionHistory.length > 0 && (
          <div className={`mt-6 border-t pt-4 ${c.border}`}>
            <div className="flex items-center justify-between mb-3">
              <h3 className={`text-sm font-semibold ${c.textSecondary}`}>📖 {t('dps_previous_analyses')}</h3>
              <button onClick={() => setSessionHistory([])} className={`text-xs ${c.textMuted} ${c.deleteHover}`}>{t('dps_clear_all')}</button>
            </div>
            <div className="space-y-1.5">
              {sessionHistory.map((h, i) => (
                <button
                  key={h.id || i}
                  onClick={() => {
                    if (h.results) {
                      setResults(h.results);
                      if (h.input?.singleDream) setSingleDream(h.input.singleDream);
                      if (h.input?.dreams?.length) setDreams(h.input.dreams);
                      if (h.mode) setMode(h.mode);
                      setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth' }), 100);
                    }
                  }}
                  disabled={!h.results}
                  className={`w-full flex items-center justify-between p-2.5 rounded-lg text-start transition-colors ${h.results ? `${c.cardAlt} hover:opacity-80 cursor-pointer` : `${c.cardAlt} opacity-50 cursor-default`}`}
                >
                  <div className="flex items-center gap-2 flex-1 min-w-0">
                    <span className="text-xs">{h.mode === 'pattern' ? '🔁' : '🌙'}</span>
                    <span className={`text-xs ${c.text} truncate`}>{h.preview}{h.dreamCount ? ` ${t('dps_more_suffix', { n: h.dreamCount - 1 })}` : ''}</span>
                  </div>
                  <span className={`text-xs ${c.textMuted} ms-2 flex-shrink-0`}>{formatDate(h.date, userLocale)}</span>
                </button>
              ))}
            </div>
          </div>
        )}
    </div>
  );
};

DreamPatternSpotter.displayName = 'DreamPatternSpotter';
export default DreamPatternSpotter;
