import React, { useState, useCallback, useEffect, useRef } from 'react';
import { useTheme} from '../hooks/useTheme';
import { useClaudeAPI} from '../hooks/useClaudeAPI';
import { usePersistentState} from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

const EXAMPLE = {
  belief: 'You should always finish what you start',
  context: 'Drilled into me as a kid — quitting felt like failing. I apply it to projects, books, even relationships. Curious how much of my life is running on inertia disguised as integrity.',
  howStrongly: 8,
};

const VERDICT_CONFIG = {
  demolished:  { icon: '💥', light: 'bg-red-50 border-red-300 text-red-800',             dark: 'bg-red-900/20 border-red-700/50 text-red-300' },
  refined:     { icon: '🔧', light: 'bg-amber-50 border-amber-300 text-amber-800',       dark: 'bg-amber-900/20 border-amber-700/40 text-amber-300' },
  vindicated:  { icon: '✅', light: 'bg-emerald-50 border-emerald-300 text-emerald-800', dark: 'bg-emerald-900/20 border-emerald-700/40 text-emerald-300' },
  complicated: { icon: '🔵', light: 'bg-cyan-50 border-cyan-300 text-cyan-800',          dark: 'bg-cyan-900/20 border-cyan-700/40 text-cyan-300' },
};

const EgoKiller = ({ tool }) => {
  const { isDark } = useTheme();
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { t } = useTranslation();

  const EXAMPLE_BELIEFS = [
    t('ek_eb1'), t('ek_eb2'), t('ek_eb3'), t('ek_eb4'),
    t('ek_eb5'), t('ek_eb6'), t('ek_eb7'), t('ek_eb8'),
  ];

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-500' : 'text-gray-400',
    input:         isDark ? 'bg-zinc-900 border-zinc-700 text-zinc-50 placeholder:text-zinc-500 focus:outline-none focus:ring-2 focus:ring-cyan-500/20 focus:border-cyan-500' : 'bg-slate-50 border-gray-300 text-gray-900 placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-cyan-500/20 focus:border-cyan-500',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-100 border border-zinc-600' : 'bg-gray-100 hover:bg-gray-200 text-gray-700 border border-gray-200',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-300' : 'bg-red-50 border-red-300 text-red-800',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-300' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    required:      isDark ? 'text-amber-400' : 'text-amber-500',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-600 hover:text-cyan-700 underline underline-offset-2';



  const [context, setContext] = useState('');
  const [howStrongly, setHowStrongly] = useState(7);
  const [results, setResults] = usePersistentState('egokiller-results', null);
  const [belief, setBelief] = usePersistentState('egokiller-belief', '');
  const [sessionHistory, setSessionHistory] = usePersistentState('egokiller-history', []);
  const [error, setError] = useState('');

  // ── Refs (after all useState per PF-10) ──
  const resultsRef = useRef(null);
  const handleSubmitRef = useRef(null);
  const canSubmitRef = useRef(false);

  const handleSubmit = async () => {
    if (!belief.trim()) return;
    setError(''); setResults(null);
    try {
      const data = await callToolEndpoint('ego-killer', {
        belief: belief.trim(),
        context: context.trim() || undefined,
        howStrongly,
        userLocale, userCurrency, userRegion,});
      setResults(data);
      setSessionHistory(prev => [{
        id: Date.now(),
        timestamp: new Date().toISOString(),
        // PF-25 exception: 40-char preview-text truncation; session history is capped at 6.
        preview: belief.trim().slice(0, 40),
        result: data,
      }, ...(prev || [])].slice(0, 6));
    } catch (e) { setError(e.message || t('ek_error'));}};

  const loadExample = useCallback(() => {
    setBelief(EXAMPLE.belief);
    setContext(EXAMPLE.context);
    setHowStrongly(EXAMPLE.howStrongly);
    setResults(null);
  }, [setBelief, setResults]);

  const buildText = useCallback(() => {
    if (!results) return '';
    let out = `🪦 ${t('ek_copy_header')}\n\n"${belief}"\n\n`;
    out += `${t('ek_copy_steelmanned')}\n${results?.belief_steelmanned}\n\n`;
    out += `${t('ek_copy_demolition')}\n${results?.the_demolition?.the_core_attack}\n\n`;
    out += `${t('ek_copy_survives')}\n${results?.what_survives?.the_kernel}\n\n`;
    out += `${t('ek_copy_rebuild')}\n${results?.the_rebuild?.the_stronger_version}\n\n`;
    out += `${t('ek_copy_verdict')} ${results?.the_verdict?.outcome_label} — ${results?.the_verdict?.one_line}\n`;
    return out + BRAND;
  }, [results, belief, t]);

  // ── PF-6: Keyboard handler ──
  handleSubmitRef.current = handleSubmit;
  canSubmitRef.current = !!belief.trim() && !loading;

  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && canSubmitRef.current)
        handleSubmitRef.current?.();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useRegisterActions(buildText(), tool?.title || 'Ego Killer');

  const vcfg = results ? (VERDICT_CONFIG[results?.the_verdict?.outcome] || VERDICT_CONFIG.complicated) : null;

  return (
    <div className={`space-y-4 ${c.text}`}>

      {/* Persistent header card */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5`}>
        <div className="pb-3 border-b border-zinc-500">
          <h2 className={`text-xl font-bold ${c.text} flex items-center gap-2`}>
            <span>{tool?.icon ?? '🪦'}</span>{tool?.title ?? t('ek_title')}
          </h2>
          <p className={`text-sm ${c.textSecondary}`}>{tool?.tagline ?? t('ek_tagline')}</p>
          <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className={`mt-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium border disabled:opacity-40 ${isDark ? 'text-white border-white/40' : 'text-gray-800 border-transparent'}`}>{t('try_example')}</button>
        </div>
      </div>

        {!results && (
          <div className={`rounded-2xl border p-6 shadow-sm space-y-4 ${c.card} ${c.border}`}>
            <p className={`text-xs ${c.textMuted}`}>
              {t('ek_pre_xref')} <a href="/BeliefStressTest" className={linkStyle}>🧪 {t('ek_belief_stress_test')}</a> {t('ek_pre_xref_link_suffix')}
            </p>
            <div>
              <label className={`block text-sm font-semibold mb-1.5 ${c.text}`}>
                {t('ek_belief_label')} <span className={c.required}>*</span>
              </label>
              <textarea value={belief} onChange={e => setBelief(e.target.value)}
                placeholder={t('ek_belief_ph')}
                rows={2} maxLength={300}
                className={`w-full px-4 py-3 rounded-xl border text-sm resize-none ${c.input}`} />
              <div className="flex flex-wrap gap-2 mt-2">
                {EXAMPLE_BELIEFS.map(b => (
                  <button key={b} onClick={() => { setBelief(b); setResults(null);}}
                    className={`px-2.5 py-1 rounded-lg text-xs ${c.btnSecondary}`}>
                    {b}
                  </button>
                ))}
              </div>
            </div>

            <div>
              <label className={`block text-sm font-semibold mb-1.5 ${c.text}`}>{t('ek_context_label')} <span className={`font-normal ${c.textMuted}`}>({t('optional')})</span></label>
              <textarea value={context} onChange={e => setContext(e.target.value)}
                placeholder={t('ek_context_ph')}
                rows={2} maxLength={300}
                className={`w-full px-4 py-3 rounded-xl border text-sm resize-none ${c.input}`} />
            </div>

            <div>
              <label className={`block text-sm font-semibold mb-2 ${c.text}`}>
                {t('ek_strength_label')} <span className={`font-normal ${c.textMuted}`}>{howStrongly}/10</span>
              </label>
              <input type="range" min={1} max={10} value={howStrongly} onChange={e => setHowStrongly(Number(e.target.value))}
                className="w-full accent-cyan-500" />
              <div className={`flex justify-between text-xs mt-1 ${c.textMuted}`}>
                <span>{t('ek_strength_low')}</span><span>{t('ek_strength_high')}</span>
              </div>
            </div>

            {error && <div className={`p-3 rounded-xl border text-sm ${c.danger}`}><span className="mr-1">⚠️</span>{error}</div>}

            <button onClick={handleSubmit} disabled={loading || !belief.trim()}
              className={`w-full py-3 rounded-xl font-bold disabled:opacity-40 ${c.btnPrimary}`}>
              {loading ? <><span className="animate-spin inline-block mr-2">{tool?.icon ?? '🪦'}</span>{t('ek_demolishing')}</> : <><span className="mr-1">{tool?.icon ?? '🪦'}</span>{t('ek_destroy')}</>}
            </button>
          </div>
        )}

        {results && (
          <div ref={resultsRef} className="space-y-4">

            {/* Verdict badge */}
            {results?.the_verdict && (
              <div className={`rounded-2xl border p-5 text-center ${isDark ? vcfg.dark : vcfg.light}`}>
                <p className="text-3xl mb-2">{vcfg.icon}</p>
                <p className="text-xl font-black tracking-tight">{results?.the_verdict?.outcome_label}</p>
                <p className="text-sm mt-1 opacity-80">{results?.the_verdict?.one_line}</p>
              </div>
            )}

            {/* Steelmanned */}
            <div className={`rounded-2xl border p-5 ${c.card} ${c.border}`}>
              <p className={`text-xs font-bold uppercase tracking-wider mb-2 ${c.textMuted}`}>🛡️ {t('ek_steelmanned')}</p>
              <p className={`text-sm leading-relaxed italic ${c.textSecondary}`}>"{results?.belief_steelmanned}"</p>
            </div>

            {/* Demolition */}
            {results?.the_demolition && (
              <div className={`rounded-2xl border-2 overflow-hidden ${isDark ? 'border-red-700/50 bg-zinc-800' : 'border-red-300 bg-white'}`}>
                <div className={`px-5 py-4 ${isDark ? 'bg-red-900/10' : 'bg-red-50'}`}>
                  <p className={`text-xs font-black uppercase tracking-widest ${isDark ? 'text-red-300' : 'text-red-800'}`}>💥 {t('ek_demolition')}</p>
                </div>
                <div className="px-5 py-4 space-y-4">
                  <div>
                    <p className={`text-xs font-bold uppercase tracking-wide mb-1 ${c.textMuted}`}>{t('ek_core_attack')}</p>
                    <p className={`text-sm leading-relaxed font-semibold ${c.text}`}>{results?.the_demolition?.the_core_attack}</p>
                  </div>
                  {results?.the_demolition?.why_its_devastating && (
                    <p className={`text-sm ${c.textSecondary}`}>{results?.the_demolition?.why_its_devastating}</p>
                  )}
                  {results?.the_demolition?.the_evidence && (
                    <div className={`p-3 rounded-xl border ${c.cardAlt} ${c.border}`}>
                      <p className={`text-xs font-bold uppercase tracking-wide mb-1 ${c.textMuted}`}>{t('ek_evidence')}</p>
                      <p className={`text-sm ${c.textSecondary}`}>{results?.the_demolition?.the_evidence}</p>
                    </div>
                  )}
                  {results?.the_demolition?.historical_counterexamples?.length > 0 && (
                    <div className="space-y-2">
                      <p className={`text-xs font-bold uppercase tracking-wide ${c.textMuted}`}>{t('ek_counterexamples')}</p>
                      {results?.the_demolition?.historical_counterexamples.map((ex, i) => (
                        <div key={i} className={`p-3 rounded-xl border ${c.cardAlt} ${c.border}`}>
                          <p className={`text-sm font-semibold ${c.text}`}>{ex.example}</p>
                          <p className={`text-xs mt-0.5 ${c.textMuted}`}>{ex.what_it_shows}</p>
                        </div>
                      ))}
                    </div>
                  )}
                  {results?.the_demolition?.the_hidden_assumption && (
                    <div className={`p-3 rounded-xl border ${isDark ? 'bg-red-900/10 border-red-800/30' : 'bg-red-50 border-red-300'}`}>
                      <p className={`text-xs font-bold uppercase tracking-wide mb-1 ${isDark ? 'text-red-300' : 'text-red-800'}`}>💣 {t('ek_hidden_assumption')}</p>
                      <p className={`text-sm ${c.textSecondary}`}>{results?.the_demolition?.the_hidden_assumption}</p>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* What survives */}
            {results?.what_survives && (
              <div className={`rounded-2xl border p-5 ${isDark ? 'bg-emerald-900/10 border-emerald-700/40' : 'bg-emerald-50 border-emerald-300'}`}>
                <p className={`text-xs font-black uppercase tracking-widest mb-3 ${isDark ? 'text-emerald-300' : 'text-emerald-800'}`}>✅ {t('ek_what_survives')}</p>
                <p className={`text-sm font-semibold mb-2 ${c.text}`}>{results?.what_survives?.the_kernel}</p>
                {results?.what_survives?.what_it_explains_well && (
                  <p className={`text-xs ${c.textMuted} mb-1`}><span className="font-semibold">{t('ek_explains_well')}</span> {results?.what_survives?.what_it_explains_well}</p>
                )}
                {results?.what_survives?.under_what_conditions && (
                  <p className={`text-xs ${c.textMuted}`}><span className="font-semibold">{t('ek_when_true')}</span> {results?.what_survives?.under_what_conditions}</p>
                )}
              </div>
            )}

            {/* The Rebuild */}
            {results?.the_rebuild && (
              <div className={`rounded-2xl border-2 p-5 ${isDark ? 'border-cyan-700 bg-cyan-900/10' : 'border-cyan-400 bg-cyan-50'}`}>
                <p className={`text-xs font-black uppercase tracking-widest mb-3 ${isDark ? 'text-cyan-300' : 'text-cyan-700'}`}>🔧 {t('ek_rebuild')}</p>
                <p className={`text-sm font-bold mb-2 ${c.text}`}>{results?.the_rebuild?.the_stronger_version}</p>
                {results?.the_rebuild?.the_key_qualification && (
                  <p className={`text-xs mb-2 ${c.textMuted}`}><span className="font-semibold">{t('ek_key_qualifier')}</span> {results?.the_rebuild?.the_key_qualification}</p>
                )}
                {results?.the_rebuild?.now_unshakeable_because && (
                  <p className={`text-xs italic ${c.textMuted}`}>{results?.the_rebuild?.now_unshakeable_because}</p>
                )}
              </div>
            )}

            <div className="flex items-center gap-3 flex-wrap">
              <button onClick={() => { setResults(null); setBelief(''); setContext('');}}
                className={`px-4 py-2 rounded-lg text-sm font-medium ${c.btnSecondary}`}>
                🔄 {t('ek_new_belief')}
              </button>
            </div>

            <div className={`rounded-xl border p-4 ${c.cardAlt} ${c.border}`}>
              <p className={`text-xs font-semibold uppercase tracking-wide mb-3 ${c.textMuted}`}>{t('ek_related')}</p>
              <div className="flex flex-wrap gap-2">
                {[
                  { id: 'BeliefStressTest', icon: '🧪', label: t('ek_xref_stress')},
                  { id: 'TheFinalWord', icon: '⚖️', label: t('ek_xref_finalword')},
                  { id: 'CrowdWisdom', icon: '👥', label: t('ek_xref_crowd')},
                ].map(r => (
                  <a key={r.id} href={`/${r.id}`}
                    className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${c.btnSecondary}`}>
                    {r.icon} {r.label}
                  </a>
                ))}
              </div>
              <p className={`text-xs ${c.textMuted} mt-3`}>
                {t('ek_post_xref')} <a href="/BeliefStressTest" className={linkStyle}>🧪 {t('ek_belief_stress_test')}</a> {t('ek_post_xref_suffix')}
              </p>
            </div>
          </div>
        )}

      {/* ── History ── */}
      {sessionHistory?.length > 0 && (
        <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
          <h3 className={`text-sm font-bold ${c.text} mb-3`}>🕐 {t('ek_recent')}</h3>
          <div className="space-y-1.5">
            {sessionHistory.map(entry => (
              <button key={entry.id}
                onClick={() => setResults(entry.result)}
                className={`w-full text-left px-3 py-2 rounded-lg ${c.btnSecondary} text-xs flex items-center gap-2`}>
                <span className={c.textMuted}>
                  {new Date(entry.timestamp).toLocaleDateString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })}
                </span>
                <span className={`${c.text} truncate`}>{entry.preview}{entry.preview?.length >= 40 ? '…' : ''}</span>
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );}

EgoKiller.displayName = 'EgoKiller';
export default EgoKiller;
