import React, { useState, useCallback, useMemo, useEffect, useRef } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

// ════════════════════════════════════════════════════════════
// CONSTANTS
// ════════════════════════════════════════════════════════════
// Tier config: domain-specific styling kept static; localized label/sub
// resolved at render time via the lk/sk translation keys.
const TIER_CFG = {
  now: { icon: '🔴', lk: 'eut_tier_now', sk: 'eut_tier_now_sub', ck: 'tierNow', bc: 'border-red-400' },
  this_week: { icon: '⏰', lk: 'eut_tier_week', sk: 'eut_tier_week_sub', ck: 'tierWeek', bc: 'border-amber-400' },
  optional: { icon: '☕', lk: 'eut_tier_optional', sk: 'eut_tier_optional_sub', ck: 'tierOptional', bc: 'border-emerald-400' },
};
const CAT_MAP = {
  'fyi': { icon: 'ℹ️', bg: 'bg-cyan-500' }, 'action required': { icon: '🎯', bg: 'bg-red-500' },
  'response expected': { icon: '💬', bg: 'bg-amber-500' }, 'automated': { icon: '🔔', bg: 'bg-gray-500' },
  'newsletter': { icon: '✉️', bg: 'bg-zinc-500' },
};
const TONES = [
  { id: 'professional', lk: 'eut_tone_professional' }, { id: 'casual', lk: 'eut_tone_casual' },
  { id: 'firm', lk: 'eut_tone_firm' }, { id: 'apologetic', lk: 'eut_tone_apologetic' },
  { id: 'grateful', lk: 'eut_tone_grateful' }, { id: 'urgent', lk: 'eut_tone_urgent' },
];
const LENGTHS = [
  { id: 'quick', lk: 'eut_len_quick' },
  { id: 'standard', lk: 'eut_len_standard' },
  { id: 'detailed', lk: 'eut_len_detailed' },
];
const RULE_TYPES = [
  { id: 'sender', lk: 'eut_rule_sender' },
  { id: 'subject', lk: 'eut_rule_subject' },
  { id: 'cc_only', lk: 'eut_rule_cc_only' },
];

// ════════════════════════════════════════════════════════════
// MAIN COMPONENT
// ════════════════════════════════════════════════════════════
const EmailUrgencyTriager = ({ tool }) => {
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();
  // This tool surfaces no currency/number/date values in its UI, so no
  // formatLocale/sym wiring is needed; userLocale/userCurrency/userRegion are
  // still forwarded to the backend for output-language + locale reasoning.
  const DEFAULT_PROFILES = useMemo(() => [{ id: 'work', name: t('eut_profile_work'), icon: '💼', role: t('eut_role_employee') }], [t]);

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-500' : 'text-gray-400',
    input:         isDark ? 'bg-zinc-900 border-zinc-700 text-zinc-50 placeholder:text-zinc-500 focus:border-emerald-500 focus:ring-emerald-500/20' : 'bg-white border-gray-300 text-gray-900 placeholder:text-gray-400 focus:border-emerald-500',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-100' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    danger:        isDark ? 'bg-red-900/30 hover:bg-red-900/50 text-red-300' : 'bg-red-50 hover:bg-red-100 text-red-700',
    // Status tier colors (domain-specific)
    tierNow:      isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-300 text-red-800',
    tierWeek:     isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    tierOptional: isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    highlight:     isDark ? 'bg-cyan-900/20 border-cyan-700 text-cyan-200' : 'bg-cyan-50 border-cyan-200 text-cyan-800',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-200 text-emerald-800',
    warning:       isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-200 text-red-800',
    // Pill variants
    pillCyan:  isDark ? 'bg-cyan-900/40 text-cyan-300 border-cyan-700/40' : 'bg-cyan-100 text-cyan-700 border-cyan-200',
    pillGreen: isDark ? 'bg-emerald-900/40 text-emerald-300 border-emerald-700/40' : 'bg-emerald-100 text-emerald-700 border-emerald-200',
    pillAmber: isDark ? 'bg-amber-900/40 text-amber-300 border-amber-700/40' : 'bg-amber-100 text-amber-700 border-amber-200',
    pillRed:   isDark ? 'bg-red-900/40 text-red-300 border-red-700/40' : 'bg-red-100 text-red-700 border-red-200',
    pillGray:  isDark ? 'bg-zinc-700 text-zinc-400 border-zinc-600' : 'bg-zinc-100 text-zinc-500 border-zinc-200',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    required:      isDark ? 'text-amber-400' : 'text-amber-500',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-emerald-400 hover:text-emerald-300 underline underline-offset-2'
    : 'text-emerald-600 hover:text-emerald-700 underline underline-offset-2';

  // MODE
  const [mode, setMode] = useState('input');

  // FORM
  const [emailContent, setEmailContent] = usePersistentState('email-content', '');
  const [userRole, setUserRole] = useState('Employee');
  const [userTimezone] = useState(Intl.DateTimeFormat().resolvedOptions().timeZone);

  // RESULTS + UI
  const [results, setResults] = usePersistentState('email-results', null);
  const [error, setError] = useState('');
  const [expandedEmail, setExpandedEmail] = useState(null);
  const [expandAll, setExpandAll] = useState(false);
  const [handled, setHandled] = useState({});
  const [overrides, setOverrides] = useState({});

  // COMPOSE (F1)
  const [composeTarget, setComposeTarget] = useState(null);
  const [composeDraft, setComposeDraft] = useState('');
  const [composeTone, setComposeTone] = useState('professional');
  const [composeLength, setComposeLength] = useState('standard');
  const [composeInstructions, setComposeInstructions] = useState('');
  const [composeResult, setComposeResult] = useState(null);

  // RULE FORM (F3)
  const [ruleForm, setRuleForm] = useState({ type: 'sender', pattern: '', tier: 'optional' });

  // PERSISTENT STORES
  const [senderHistory, setSenderHistory] = usePersistentState('email-sender-history', {});
  const [triageHistory, setTriageHistory] = usePersistentState('email-triage-history', []);
  const [rules, setRules] = usePersistentState('email-triage-rules', []);
  const [responseTimes, setResponseTimes] = usePersistentState('email-response-times', []);
  const [profiles, setProfiles] = usePersistentState('email-profiles', DEFAULT_PROFILES);
  const [activeProfileId, setActiveProfileId] = usePersistentState('email-active-profile', 'work');

  // ── Refs (after all useState per PF-10) ──
  const resultsRef = useRef(null);
  const runAnalyzeRef = useRef(null);
  const canSubmitRef = useRef(false);


  // ─── PROFILE HELPERS ───
  const activeProfile = useMemo(() => profiles.find(p => p.id === activeProfileId) || profiles[0], [profiles, activeProfileId]);
  const pfx = activeProfileId + ':';
  const profileSenders = useMemo(() => {
    const out = {};
    Object.entries(senderHistory).forEach(([k, v]) => { if (k.startsWith(pfx)) out[k.slice(pfx.length)] = v; });
    return out;
  }, [senderHistory, pfx]);
  const profileTriages = useMemo(() => triageHistory.filter(h => h.profileId === activeProfileId), [triageHistory, activeProfileId]);
  const profileRules = useMemo(() => rules.filter(r => r.profileId === activeProfileId && r.enabled), [rules, activeProfileId]);
  const profileResponses = useMemo(() => responseTimes.filter(r => r.profileId === activeProfileId), [responseTimes, activeProfileId]);

  // ─── HELPERS ───
  const getCat = (cat) => CAT_MAP[cat?.toLowerCase()] || { icon: '✉️', bg: 'bg-gray-400' };
  const getRep = (sender) => {
    const h = profileSenders[sender];
    if (!h || h.total < 3) return null;
    if (h.cryWolfScore > 0.5) return { label: t('eut_rep_cry_wolf'), icon: '🐺', pill: 'pillRed' };
    if (h.actuallyUrgent / h.total > 0.7) return { label: t('eut_rep_vip'), icon: '⭐', pill: 'pillAmber' };
    return null;
  };

  // F3: Apply rules to determine effective tier
  const applyRules = useCallback((email) => {
    for (const rule of profileRules) {
      if (rule.type === 'sender' && email.from?.toLowerCase().includes(rule.pattern.toLowerCase())) return rule.tier;
      if (rule.type === 'subject' && email.email_subject?.toLowerCase().includes(rule.pattern.toLowerCase())) return rule.tier;
      if (rule.type === 'cc_only' && email.thread_analysis?.on_cc) return rule.tier;
    }
    return null;
  }, [profileRules]);

  const getEmailsByTier = useCallback((tier) => {
    if (!results?.urgency_analysis) return [];
    return results.urgency_analysis.map((email, idx) => ({ ...email, _idx: idx })).filter(email => {
      const raw = email.urgency_tier?.toLowerCase().replace(' ', '_').replace('urgent', 'now');
      const origTier = raw === 'this week' ? 'this_week' : raw;
      const ruleOverride = applyRules(email);
      const overKey = `${origTier}-${email._idx}`;
      const manualOverride = overrides[overKey];
      const effectiveTier = manualOverride || ruleOverride || origTier;
      return effectiveTier === tier;
    });
  }, [results, overrides, applyRules]);

  // ─── SENDER LEARNING ───
  const updateSenderHistory = useCallback((analysisResults) => {
    if (!analysisResults?.length) return;
    const updated = { ...senderHistory };
    analysisResults.forEach(email => {
      if (!email.from) return;
      const key = pfx + email.from;
      if (!updated[key]) updated[key] = { total: 0, markedUrgent: 0, actuallyUrgent: 0, cryWolfScore: 0, firstSeen: new Date().toISOString().split('T')[0], categories: {} };
      updated[key].total++;
      if (email.sender_marked_urgent) updated[key].markedUrgent++;
      if (email.urgency_tier === 'now') updated[key].actuallyUrgent++;
      const cat = email.email_category || 'Unknown';
      updated[key].categories[cat] = (updated[key].categories[cat] || 0) + 1;
      updated[key].lastSeen = new Date().toISOString().split('T')[0];
      if (updated[key].markedUrgent > 0) updated[key].cryWolfScore = (updated[key].markedUrgent - updated[key].actuallyUrgent) / updated[key].markedUrgent;
    });
    setSenderHistory(updated);
  }, [senderHistory, setSenderHistory, pfx]);

  // ─── ANALYZE ───
  const handleAnalyze = async () => {
    if (!emailContent.trim()) { setError(t('eut_err_paste')); return; }
    setError(''); setResults(null); setHandled({}); setOverrides({});
    try {
      const data = await callToolEndpoint('email-urgency-triager', {
        emailContent: emailContent.trim(), userRole: activeProfile.role || userRole, userTimezone,
        senderHistory: profileSenders, triageHistory: profileTriages.slice(0, 6),
        userLocale, userCurrency, userRegion,
      });
      setResults(data); setMode('results');
      updateSenderHistory(data.urgency_analysis);
    } catch (err) { setError(err.message || t('eut_err_analyze')); }
  };

  const loadExample = useCallback(() => {
    setEmailContent(t('eut_example_emails'));
    setMode('triage');
  }, [setEmailContent, t]);

  // F1: COMPOSE
  const handleCompose = async () => {
    if (!composeTarget) return;
    setError(''); setComposeResult(null);
    try {
      const data = await callToolEndpoint('email-urgency-triager', {
        action: 'compose', emailSubject: composeTarget.email_subject, emailFrom: composeTarget.from,
        emailBody: composeTarget.reasoning, currentDraft: composeDraft.trim() || composeTarget.draft_reply || null,
        tone: composeTone, length: composeLength,
        instructions: composeInstructions.trim() || null, userRole: activeProfile.role || userRole,
        userLocale, userCurrency, userRegion,
      });
      setComposeResult(data);
    } catch (err) { setError(err.message || t('eut_err_compose')); }
  };

  const openComposer = (email) => {
    setComposeTarget(email); setComposeDraft(email.draft_reply || '');
    setComposeTone('professional'); setComposeLength('standard');
    setComposeInstructions(''); setComposeResult(null); setMode('compose');
  };

  // SAVE + F4 RESPONSE TRACKING
  const saveToHistory = useCallback(() => {
    if (!results) return;
    const entry = {
      id: Date.now(), date: new Date().toISOString().split('T')[0],
      time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      profileId: activeProfileId, summary: results.summary,
      emailCount: results.urgency_analysis?.length || 0,
      subjects: results.urgency_analysis?.map(e => e.email_subject).slice(0, 6) || [],
      preview: `${results.urgency_analysis?.length || 0} emails triaged`.slice(0, 40),
      handled: { ...handled }, results,
    };
    setTriageHistory(prev => [entry, ...prev].slice(0, 6));
  }, [results, handled, activeProfileId, setTriageHistory]);

  // F4: Mark done with timestamp tracking
  const markHandled = useCallback((key, emailData) => {
    setHandled(p => ({ ...p, [key]: p[key] === 'done' ? undefined : 'done' }));
    if (emailData && !handled[key]) {
      setResponseTimes(prev => [...prev, {
        id: Date.now(), profileId: activeProfileId,
        subject: emailData.email_subject, from: emailData.from,
        tier: key.split('-')[0], triageTime: new Date().toISOString(),
        doneTime: new Date().toISOString(),
      }].slice(0, 6));
    }
  }, [handled, activeProfileId, setResponseTimes]);

  const overrideUrgency = (origTier, idx, newTier) => {
    const key = `${origTier}-${idx}`;
    setOverrides(prev => newTier === origTier ? (({ [key]: _, ...rest }) => rest)(prev) : { ...prev, [key]: newTier });
  };

  // ─── EXPORTS ───
  const buildFullExport = useCallback(() => {
    if (!results) return '';
    const lines = ['EMAIL TRIAGE REPORT', '═'.repeat(50), `Date: ${new Date().toISOString().split('T')[0]}`, `Profile: ${activeProfile.name}`, ''];
    const s = results.summary;
    if (s) lines.push(`Total: ${s.total_emails} | 🔴 ${s.urgent_count} | ⏰ ${s.this_week_count} | ☕ ${s.optional_count}`, s.total_estimated_minutes ? `⏱️ ~${s.total_estimated_minutes} min total` : '', '');

    const bi = results.batch_insights;
    if (bi?.time_block_suggestion) lines.push(`⚡ TIME BLOCK: ${bi.time_block_suggestion}`, '');

    const ar = results.anxiety_relief;
    if (ar) {
      lines.push('✅ PERMISSION TO BREATHE');
      if (ar.permission_to_wait) lines.push(ar.permission_to_wait);
      if (ar.what_to_ignore) lines.push(`Ignore: ${ar.what_to_ignore}`);
      if (ar.batch_processing_tip) lines.push(`💡 ${ar.batch_processing_tip}`);
      lines.push('');
    }

    ['now', 'this_week', 'optional'].forEach(tier => {
      const emails = getEmailsByTier(tier);
      if (!emails.length) return;
      lines.push(`${TIER_CFG[tier].icon} ${t(TIER_CFG[tier].lk).toUpperCase()} (${emails.length})`, '─'.repeat(40));
      emails.forEach((e, i) => {
        const st = handled[`${tier}-${e._idx}`];
        lines.push(`${i + 1}. ${st === 'done' ? '✅' : '⬜'} [${e.email_category || ''}] ${e.email_subject}`, `   ${t('eut_from', { sender: e.from })}`, `   ${e.reasoning}`, e.draft_reply ? `   ${t('eut_draft_reply')}: ${e.draft_reply}` : '', '');
      });
    });

    if (bi?.delegation_opportunities) lines.push(`📤 ${bi.delegation_opportunities}`, '');
    if (bi?.similar_emails?.length) lines.push('📦', ...bi.similar_emails.map(b => `  • ${b}`), '');

    lines.push(BRAND.trim());
    return lines.filter(l => l !== undefined).join('\n');
  }, [results, activeProfile, getEmailsByTier, handled, t]);

  // ── PF-8: buildFullText ──
  const buildFullText = useCallback(() => {
    if (results) return buildFullExport();
    return '';
  }, [results, buildFullExport]);

  // ─── STATS ───
  const handledStats = useMemo(() => {
    const d = Object.values(handled).filter(v => v === 'done').length;
    const tot = results?.urgency_analysis?.length || 0;
    return { done: d, remaining: tot - d, total: tot };
  }, [handled, results]);

  const senderStats = useMemo(() => {
    const entries = Object.entries(profileSenders);
    return { total: entries.length, vips: entries.filter(([_, h]) => h.total >= 3 && h.actuallyUrgent / h.total > 0.7).length, wolves: entries.filter(([_, h]) => h.total >= 3 && h.cryWolfScore > 0.5).length };
  }, [profileSenders]);

  // F5: INBOX HEALTH SCORE
  const inboxHealth = useMemo(() => {
    const recent = profileTriages.slice(0, 6);
    if (recent.length < 2) return null;
    const totalEmails = recent.reduce((s, r) => s + (r.summary?.total_emails || 0), 0);
    const urgentEmails = recent.reduce((s, r) => s + (r.summary?.urgent_count || 0), 0);
    const optionalEmails = recent.reduce((s, r) => s + (r.summary?.optional_count || 0), 0);
    if (!totalEmails) return null;
    const urgentRatio = 1 - (urgentEmails / totalEmails); // fewer urgent = better
    const optionalRatio = optionalEmails / totalEmails; // more optional = healthier (less noise reaching you)
    const wolfCount = Object.values(profileSenders).filter(h => h.cryWolfScore > 0.5).length;
    const wolfPenalty = Math.min(wolfCount * 5, 20);
    const handledRate = recent.filter(r => Object.values(r.handled || {}).some(v => v === 'done')).length / recent.length;
    const score = Math.round(Math.min(100, Math.max(0, urgentRatio * 30 + optionalRatio * 20 + handledRate * 30 + 20 - wolfPenalty)));
    const label = score >= 80 ? t('eut_health_excellent') : score >= 60 ? t('eut_health_good') : score >= 40 ? t('eut_health_needs_work') : t('eut_health_stressed');
    const color = score >= 80 ? 'bg-emerald-500' : score >= 60 ? 'bg-amber-500' : 'bg-red-500';
    return { score, label, color, sessions: recent.length, urgentRatio: Math.round(urgentEmails / totalEmails * 100), totalEmails };
  }, [profileTriages, profileSenders, t]);

  // F2: BRIEFING DATA
  const briefingData = useMemo(() => {
    if (!profileTriages.length) return null;
    const latest = profileTriages[0];
    const previous = profileTriages[1];
    // Overdue: urgent items from previous triages not marked done
    const overdue = profileTriages.slice(0, 6).flatMap(entry =>
      (entry.results?.urgency_analysis || []).filter(e => e.urgency_tier === 'now')
        .filter(e => !entry.handled?.[`now-${(entry.results?.urgency_analysis || []).indexOf(e)}`])
        .map(e => ({ ...e, triageDate: entry.date }))
    ).slice(0, 6);
    // Volume comparison
    const latestCount = latest.summary?.total_emails || 0;
    const prevCount = previous?.summary?.total_emails || 0;
    const volumeChange = previous ? Math.round(((latestCount - prevCount) / Math.max(prevCount, 1)) * 100) : null;
    // Avg urgent
    const avgUrgent = profileTriages.length >= 3 ? Math.round(profileTriages.slice(0, 6).reduce((s, r) => s + (r.summary?.urgent_count || 0), 0) / Math.min(profileTriages.length, 5) * 10) / 10 : null;
    return { latest, previous, overdue, volumeChange, latestCount, prevCount, avgUrgent };
  }, [profileTriages]);

  // F4: SLA METRICS
  const slaMetrics = useMemo(() => {
    if (profileResponses.length < 3) return null;
    const byTier = {};
    profileResponses.forEach(r => {
      if (!byTier[r.tier]) byTier[r.tier] = [];
      byTier[r.tier].push(r);
    });
    return { total: profileResponses.length, byTier, recentWeek: profileResponses.filter(r => { const d = new Date(r.doneTime); const w = new Date(); w.setDate(w.getDate() - 7); return d >= w; }).length };
  }, [profileResponses]);

  const handleReset = () => { setEmailContent(''); setResults(null); setError(''); setExpandedEmail(null); setHandled({}); setOverrides({}); setExpandAll(false); setMode('input'); };

  // ════════════════════════════════════════════════════════════
  // EMAIL CARD RENDERER
  // ════════════════════════════════════════════════════════════
  const renderCard = (email, tier, _idx) => {
    const rep = getRep(email.from);
    const catInfo = getCat(email.email_category);
    const key = `${tier}-${email._idx}`;
    const isExp = expandAll || expandedEmail === key;
    const status = handled[key];
    return (
      <div key={key} className={`${c.card} border-2 ${TIER_CFG[tier].bc} rounded-lg p-4 transition-all ${status === 'done' ? 'opacity-50' : ''}`}>
        <div className="flex items-start justify-between mb-2">
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-1.5 flex-wrap mb-1">
              {email.email_category && <span className={`px-1.5 py-0.5 rounded text-[10px] font-bold text-white ${catInfo.bg}`}>{catInfo.icon} {email.email_category}</span>}
              {rep && <span className={`${c[rep.pill]} border text-[9px] font-bold px-1.5 py-0.5 rounded`}>{rep.icon} {rep.label}</span>}
              {email.thread_analysis?.is_escalating && <span className={`${c.pillRed} border text-[9px] font-bold px-1.5 py-0.5 rounded`}>{t('eut_escalating')}</span>}
              {email.thread_analysis?.on_cc && <span className={`${c.pillGray} border text-[9px] px-1.5 py-0.5 rounded`}>{t('eut_cc')}</span>}
              {email.thread_analysis?.follow_up_count > 0 && <span className={`${c.pillGray} border text-[9px] px-1.5 py-0.5 rounded`}>{t('eut_follow_ups', { count: email.thread_analysis.follow_up_count })}</span>}
            </div>
            <p className={`text-sm font-semibold ${c.text} truncate`}>{email.email_subject}</p>
            <p className={`text-xs ${c.textMuted} mt-0.5`}>{t('eut_from', { sender: email.from })}</p>
            {email.deadline_detected && <p className={`text-xs mt-1 font-medium ${c.textSecondary}`}>📅 {email.deadline_detected}</p>}
            {(email.recipient_timezone || email.estimated_minutes) && (
              <p className={`text-[10px] ${c.textMuted} mt-0.5`}>
                {[email.recipient_timezone && `🌐 ${email.recipient_timezone}`, email.estimated_minutes && t('eut_min_suffix', { min: email.estimated_minutes })].filter(Boolean).join(' · ')}
              </p>
            )}
          </div>
          <div className="flex items-center gap-1 ml-2 flex-shrink-0">
            {tier !== 'optional' && <button onClick={() => markHandled(key, email)} className={`text-sm p-1 rounded ${status === 'done' ? 'opacity-100' : 'opacity-40 hover:opacity-100'}`} title={t('eut_done_title')}>✅</button>}
            {tier !== 'optional' && <button onClick={() => openComposer(email)} className={`text-sm p-1 rounded opacity-40 hover:opacity-100`} title={t('eut_compose_title')}>✍️</button>}
            <button onClick={() => setExpandedEmail(isExp && !expandAll ? null : key)} className={`p-1 rounded ${c.btnSecondary} text-xs`}>{isExp ? '▲' : '▼'}</button>
          </div>
        </div>
        {isExp && (
          <div className={`mt-3 pt-3 ${c.border} border-t space-y-3`}>
            <div><p className={`text-[10px] font-bold ${c.textMuted}`}>{t('eut_why')}</p><p className={`text-xs ${c.textSecondary}`}>{email.reasoning}</p></div>
            {email.consequence_of_delay && <div><p className={`text-[10px] font-bold ${c.textMuted}`}>{t('eut_if_you_wait')}</p><p className={`text-xs ${c.textSecondary}`}>{email.consequence_of_delay}</p></div>}
            {email.response_optimization && (
              <div className={`${c.cardAlt} border rounded-lg p-3 space-y-1`}>
                <p className="text-xs"><strong>{t('eut_best_time')}</strong> {email.response_optimization.best_time}</p>
                {email.response_optimization.estimated_time && <p className="text-xs"><strong>{t('eut_time')}</strong> {email.response_optimization.estimated_time}</p>}
                {email.response_optimization.can_delegate && <p className={`text-xs ${c.textSecondary}`}>{t('eut_delegate_to', { who: email.response_optimization.delegate_to })}</p>}
              </div>
            )}
            {email.draft_reply && (
              <div>
                <div className="flex items-center justify-between mb-1"><p className={`text-[10px] font-bold ${c.textMuted}`}>{t('eut_draft_reply')}</p></div>
                <div className={`${c.highlight} border rounded-lg p-3`}><p className={`text-xs ${c.textSecondary} whitespace-pre-wrap`}>{email.draft_reply}</p></div>
              </div>
            )}
            <div><p className={`text-[10px] font-bold ${c.textMuted} mb-1`}>{t('eut_move_to')}</p><div className="flex gap-1.5">
              {Object.entries(TIER_CFG).filter(([k]) => k !== tier).map(([k, cfg]) => (<button key={k} onClick={() => overrideUrgency(tier, email._idx, k)} className={`text-[10px] px-2 py-1 rounded border ${c.pillGray} border hover:opacity-80`}>{cfg.icon} {t(cfg.lk)}</button>))}
            </div></div>
          </div>
        )}
      </div>
    );
  };

  // ── PF-8: useRegisterActions — after all useMemo/useCallback per convention ──
  useRegisterActions(buildFullText(), tool?.title || 'Email Urgency Triager');

  // ── PF-6: Keyboard handler ──
  runAnalyzeRef.current = handleAnalyze;
  canSubmitRef.current = !loading && !!emailContent.trim();

  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && canSubmitRef.current)
        runAnalyzeRef.current?.();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // ════════════════════════════════════════════════════════════
  // RENDER
  // ════════════════════════════════════════════════════════════
  return (
    <div className={`space-y-4 ${c.text}`}>
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5`}>
        <div className="pb-3 border-b border-zinc-500">
          <h2 className={`text-xl font-bold ${c.text} flex items-center gap-2`}>
            <span className="mr-2">{tool?.icon ?? '📬'}</span>{tool?.title ?? 'Email Urgency Triager'}
          </h2>
          <p className={`text-sm ${c.textSecondary}`}>{tool?.tagline ?? t('eut_tagline')}</p>
          <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className={`mt-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium border disabled:opacity-40 ${isDark ? 'text-white border-white/40' : 'text-gray-800 border-transparent'}`}>{t('try_example')}</button>
        </div>
      </div>

      {/* F6: PROFILE SWITCHER */}
      <div className={`${c.card} border rounded-xl p-3 flex items-center gap-2 flex-wrap`}>
        <span className={`text-xs font-bold ${c.textMuted}`}>{t('eut_profile_label')}</span>
        {profiles.map(p => (
          <button key={p.id} onClick={() => { setActiveProfileId(p.id); setUserRole(p.role); }}
            className={`text-xs px-2.5 py-1 rounded-lg border-2 transition-colors ${activeProfileId === p.id ? (isDark ? 'border-emerald-500 bg-emerald-900/20' : 'border-emerald-500 bg-emerald-50') : `${c.pillGray} border`}`}>
            {p.icon} {p.name}
          </button>
        ))}
        <button onClick={() => {
          const name = window.prompt(t('eut_prompt_profile_name'));
          if (!name?.trim()) return;
          const icon = window.prompt(t('eut_prompt_icon'), '📧') || '📧';
          const role = window.prompt(t('eut_prompt_role'), t('eut_role_employee')) || t('eut_role_employee');
          setProfiles(prev => [...prev, { id: Date.now().toString(), name: name.trim(), icon, role }]);
        }} className={`text-xs px-2 py-1 rounded-lg border ${c.pillGray} border hover:opacity-80`}>➕</button>
        {profiles.length > 1 && activeProfileId !== 'work' && (
          <button onClick={() => { if (window.confirm(t('eut_confirm_delete_profile', { name: activeProfile.name }))) { setProfiles(p => p.filter(pr => pr.id !== activeProfileId)); setActiveProfileId('work'); } }}
            className={`text-[10px] ${c.textMuted} hover:opacity-80 ml-auto`}>{t('eut_delete')}</button>
        )}
      </div>

      {/* MODE TABS */}
      <div className={`${c.card} border rounded-xl p-4`}>
        <div className="grid grid-cols-6 gap-1.5">
          {[
            { id: 'input', icon: '✉️', label: t('eut_tab_triage') },
            { id: 'results', icon: '📋', label: t('eut_tab_results'), disabled: !results },
            { id: 'compose', icon: '✍️', label: t('eut_tab_compose'), disabled: !composeTarget && !results },
            { id: 'briefing', icon: '📰', label: t('eut_tab_briefing') },
            { id: 'history', icon: '📚', label: t('eut_tab_history') },
            { id: 'settings', icon: '⚙️', label: t('eut_tab_settings') },
          ].map(m => (
            <button key={m.id} onClick={() => !m.disabled && setMode(m.id)} disabled={m.disabled}
              className={`p-2 border-2 rounded-lg text-center transition-colors ${m.disabled ? 'opacity-30 cursor-not-allowed' : ''} ${mode === m.id ? (isDark ? 'border-emerald-500 bg-emerald-900/20' : 'border-emerald-500 bg-emerald-50') : (isDark ? 'border-zinc-700 hover:border-zinc-600' : 'border-emerald-200 hover:border-emerald-300')}`}>
              <span className="text-lg block">{m.icon}</span>
              <p className={`text-[10px] font-semibold ${c.text}`}>{m.label}</p>
            </button>
          ))}
        </div>
      </div>

      {/* ══════════ INPUT MODE ══════════ */}
      {mode === 'input' && (
        <div className="space-y-4">
          {senderStats.total > 0 && (
            <div className={`${c.highlight} border-l-4 rounded-r-lg p-3 flex items-center gap-2`}>
              <span>📈</span><span className="text-xs font-semibold">{t('eut_senders_tracked', { count: senderStats.total })}{senderStats.vips > 0 ? ` · ${senderStats.vips} ⭐` : ''}{senderStats.wolves > 0 ? ` · ${senderStats.wolves} 🐺` : ''}</span>
              {profileRules.length > 0 && <span className={`${c.pillCyan} border text-[9px] px-1.5 py-0.5 rounded ml-auto`}>{t('eut_rules_active', { count: profileRules.length })}</span>}
            </div>
          )}
          <div className={`${c.card} border rounded-xl p-6 space-y-5`}>
            <div><label className={`text-sm font-semibold ${c.textSecondary} block mb-1.5`}>{t('eut_paste_emails')} <span className={c.required}>*</span></label>
              <p className={`text-[10px] ${c.textMuted} mb-1`}>{t('eut_paste_hint')}</p>
              <textarea value={emailContent} onChange={e => setEmailContent(e.target.value)}
                placeholder={t('eut_paste_placeholder')}
                onKeyDown={e => { if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && emailContent.trim()) handleAnalyze(); }}
                className={`w-full h-44 p-4 border-2 rounded-lg ${c.input} outline-none focus:ring-2 resize-none text-sm font-mono`} />
            </div>
            <button onClick={handleAnalyze} disabled={loading || !emailContent.trim()}
            className={`w-full ${c.btnPrimary} disabled:opacity-40 font-bold py-3 rounded-lg flex items-center justify-center gap-2`}>
            {loading ? <><span className="animate-spin inline-block">{tool?.icon ?? '📬'}</span> {t('eut_analyzing')}</> : <><span className="mr-1">{tool?.icon ?? '📬'}</span>{t('eut_analyze_urgency')}</>}
            </button>
            {error && <div className={`${c.warning} border rounded-lg p-4 flex items-start gap-2`}><span>⚠️</span><p className="text-sm">{error}</p></div>}

            {/* Pre-result cross-ref */}
            <div className={`p-4 rounded-2xl border ${c.border} ${c.cardAlt}`}>
              <p className={`text-xs ${c.textMuted}`}>
                💡 {t('eut_xref_input')}{' '}<a href="/VelvetHammer" className={linkStyle}>{t('eut_velvet_hammer')}</a>{' '}
                {t('eut_xref_input_2')}
              </p>
            </div>
          </div>
        </div>
      )}

      {/* ══════════ RESULTS MODE ══════════ */}
      {mode === 'results' && results && (
        <div ref={resultsRef} className="space-y-4">
          <div className="flex items-center justify-between flex-wrap gap-2">
            <div className="flex flex-wrap gap-2">
              <button onClick={saveToHistory} className={`${c.btnPrimary} py-2 px-4 rounded-lg text-sm font-semibold`}>{t('eut_save')}</button>
              <button onClick={() => setExpandAll(p => !p)} className={`${c.btnSecondary} py-2 px-3 rounded-lg text-sm`}>{expandAll ? t('eut_collapse') : t('eut_expand')}</button>
            </div>
            <button onClick={handleReset} className={`${c.btnSecondary} py-2 px-3 rounded-lg text-sm`}>{t('eut_new')}</button>
          </div>

          <div className="grid grid-cols-4 gap-3">
            <div className={`${c.card} border rounded-xl p-3 text-center`}><p className="text-2xl font-bold">{results.summary?.total_emails || 0}</p><p className={`text-[10px] ${c.textMuted}`}>{t('eut_total')}</p></div>
            <div className={`${c.tierNow} border rounded-xl p-3 text-center`}><p className="text-2xl font-bold">{getEmailsByTier('now').length}</p><p className="text-[10px] opacity-75">{t('eut_now_short')}</p></div>
            <div className={`${c.tierWeek} border rounded-xl p-3 text-center`}><p className="text-2xl font-bold">{getEmailsByTier('this_week').length}</p><p className="text-[10px] opacity-75">{t('eut_week_short')}</p></div>
            <div className={`${c.tierOptional} border rounded-xl p-3 text-center`}><p className="text-2xl font-bold">{getEmailsByTier('optional').length}</p><p className="text-[10px] opacity-75">{t('eut_skip_short')}</p></div>
          </div>

          {handledStats.done > 0 && (
            <div className={`${c.card} border rounded-xl p-4`}>
              <div className="flex items-center justify-between mb-2"><p className={`text-sm font-semibold ${c.text}`}>{t('eut_progress')}</p><p className={`text-xs ${c.textMuted}`}>{t('eut_progress_stats', { done: handledStats.done, remaining: handledStats.remaining })}</p></div>
              <div className={`h-3 rounded-full overflow-hidden ${isDark ? 'bg-zinc-700' : 'bg-emerald-100'}`}><div className="h-full bg-emerald-500 rounded-full transition-all" style={{ width: `${(handledStats.done / handledStats.total) * 100}%` }} /></div>
            </div>
          )}

          {results.batch_insights?.time_block_suggestion && (
            <div className={`${c.highlight} border-l-4 rounded-r-lg p-4 flex items-start gap-2`}><span>⚡</span><div><p className="text-sm font-bold">{t('eut_time_block')}</p><p className="text-xs">{results.batch_insights.time_block_suggestion}</p>{results.summary?.total_estimated_minutes > 0 && <p className="text-xs mt-1 font-semibold">{t('eut_min_total', { min: results.summary.total_estimated_minutes })}</p>}</div></div>
          )}

          {results.anxiety_relief && (
            <div className={`${c.success} border-l-4 rounded-r-lg p-4`}><h4 className="font-bold text-sm mb-1">{t('eut_permission_breathe')}</h4>
              {results.anxiety_relief.permission_to_wait && <p className="text-xs mb-1">{results.anxiety_relief.permission_to_wait}</p>}
              {results.anxiety_relief.what_to_ignore && <p className="text-xs mb-1"><strong>{t('eut_ignore')}</strong> {results.anxiety_relief.what_to_ignore}</p>}
              {results.anxiety_relief.batch_processing_tip && <p className="text-xs">💡 {results.anxiety_relief.batch_processing_tip}</p>}
            </div>
          )}

          {results.recurring_patterns?.unsubscribe_candidates?.length > 0 && (
            <div className={`${c.highlight} border-l-4 rounded-r-lg p-4`}><h4 className="font-bold text-sm mb-1">{t('eut_patterns')}</h4>{results.recurring_patterns.unsubscribe_candidates.map((u, i) => <p key={i} className="text-xs mb-0.5">📬 {u}</p>)}{results.recurring_patterns.volume_observation && <p className="text-xs mt-1">{results.recurring_patterns.volume_observation}</p>}</div>
          )}
          {(results.recurring_patterns?.always_urgent_senders?.length > 0 || results.recurring_patterns?.always_optional_senders?.length > 0) && (
            <div className={`${c.cardAlt} border rounded-lg p-4 space-y-2`}>
              <h4 className="font-bold text-sm">{t('eut_sender_patterns')}</h4>
              {results.recurring_patterns.always_urgent_senders?.length > 0 && (
                <div><p className={`text-[10px] font-bold ${c.textMuted} mb-1`}>{t('eut_always_urgent')}</p>{results.recurring_patterns.always_urgent_senders.map((s, i) => <p key={i} className="text-xs">• {s}</p>)}</div>
              )}
              {results.recurring_patterns.always_optional_senders?.length > 0 && (
                <div><p className={`text-[10px] font-bold ${c.textMuted} mb-1`}>{t('eut_always_optional')}</p>{results.recurring_patterns.always_optional_senders.map((s, i) => <p key={i} className="text-xs">• {s}</p>)}</div>
              )}
              {results.summary?.delegation_count > 0 && <p className={`text-xs ${c.textSecondary}`}>📤 {t('eut_delegation_count', { count: results.summary.delegation_count })}</p>}
            </div>
          )}

          {Object.keys(overrides).length > 0 && (
            <div className={`${c.tierWeek} border rounded-lg p-3 flex items-center justify-between`}><p className="text-xs font-semibold">{t('eut_manually_moved', { count: Object.keys(overrides).length })}</p><button onClick={() => setOverrides({})} className="text-xs underline">{t('eut_reset')}</button></div>
          )}

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
            {['now', 'this_week', 'optional'].map(tier => {
              const cfg = TIER_CFG[tier]; const emails = getEmailsByTier(tier);
              return (<div key={tier}>
                <div className={`${c[cfg.ck]} border-2 rounded-t-xl p-4`}><div className="flex items-center gap-2"><span>{cfg.icon}</span><h3 className="font-bold text-lg">{t(cfg.lk)}</h3><span className="text-sm font-bold opacity-75">({emails.length})</span></div><p className="text-sm opacity-75 mt-0.5">{t(cfg.sk)}</p></div>
                <div className="space-y-3 mt-3">{emails.length === 0 ? <div className={`${c.cardAlt} border rounded-lg p-4 text-center`}><span className="text-2xl block mb-1">{tier === 'now' ? '✅' : cfg.icon}</span><p className={`text-sm ${c.textMuted}`}>{tier === 'now' ? t('eut_nothing_urgent') : t('eut_nothing_here')}</p></div> : emails.map((e, i) => renderCard(e, tier, i))}</div>
              </div>);
            })}
          </div>

          {results.response_templates?.length > 0 && (
            <div className={`${c.card} border rounded-xl p-5`}><h3 className={`text-sm font-bold ${c.text} mb-3`}>{t('eut_templates')}</h3><div className="space-y-2">{results.response_templates.map((tpl, i) => (
              <div key={i} className={`${c.cardAlt} border rounded-lg p-3`}><div className="flex items-center justify-between mb-1"><span className={`${tpl.for_urgency === 'now' ? c.pillRed : c.pillAmber} border text-[9px] font-bold px-1.5 py-0.5 rounded`}>{tpl.for_urgency}</span></div><p className={`text-xs ${c.textSecondary}`}>{tpl.template}</p></div>
            ))}</div></div>
          )}

          <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
            <p className={`text-[10px] font-bold ${c.textMuted} mb-2`}>{t('eut_related_tools')}</p>
            <div className="flex flex-wrap gap-3">
              <a href="/GentlePushGenerator" className={`text-xs ${linkStyle}`}>📨 {t('eut_gentle_push')}</a>
              <a href="/DifficultTalkCoach" className={`text-xs ${linkStyle}`}>🗣️ {t('eut_difficult_talk')}</a>
            </div>
          </div>
        </div>
      )}

      {/* ══════════ F1: COMPOSE MODE ══════════ */}
      {mode === 'compose' && (
        <div className="space-y-4">
          {!composeTarget ? (
            <div className={`${c.card} border rounded-xl p-6 text-center`}><span className="text-4xl block mb-3">✍️</span><p className={`text-sm ${c.textSecondary}`}>{t('eut_compose_empty')}</p><button onClick={() => setMode('results')} className={`${c.btnPrimary} px-4 py-2 rounded-lg text-sm mt-3`}>{t('eut_back_to_results')}</button></div>
          ) : (<>
            <div className={`${c.card} border rounded-xl p-5`}>
              <h3 className={`text-sm font-bold ${c.text} mb-3 flex items-center gap-2`}><span>✍️</span> {t('eut_reply_composer')}</h3>
              <div className={`${c.cardAlt} border rounded-lg p-3 mb-4`}>
                <p className={`text-xs ${c.textMuted}`}>{t('eut_replying_to')}</p>
                <p className={`text-sm font-semibold ${c.text}`}>{composeTarget.email_subject}</p>
                <p className={`text-xs ${c.textMuted}`}>{t('eut_from', { sender: composeTarget.from })}</p>
              </div>

              <div className="space-y-4">
                <div>
                  <label className={`text-xs font-semibold ${c.textSecondary} block mb-1`}>{t('eut_current_draft')}</label>
                  <textarea value={composeDraft} onChange={e => setComposeDraft(e.target.value)}
                    placeholder={t('eut_compose_draft_ph')}
                    className={`w-full h-24 p-3 border-2 rounded-lg ${c.input} outline-none resize-none text-sm`} />
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <div><label className={`text-xs font-semibold ${c.textSecondary} block mb-1`}>{t('eut_tone')}</label>
                    <div className="flex flex-wrap gap-1">{TONES.map(tn => (<button key={tn.id} onClick={() => setComposeTone(tn.id)} className={`text-[10px] px-2 py-1 rounded border transition-colors ${composeTone === tn.id ? (isDark ? 'border-emerald-500 bg-emerald-900/20' : 'border-emerald-500 bg-emerald-50') : `${c.pillGray} border`}`}>{t(tn.lk)}</button>))}</div>
                  </div>
                  <div><label className={`text-xs font-semibold ${c.textSecondary} block mb-1`}>{t('eut_length')}</label>
                    <div className="flex flex-wrap gap-1">{LENGTHS.map(l => (<button key={l.id} onClick={() => setComposeLength(l.id)} className={`text-[10px] px-2 py-1 rounded border transition-colors ${composeLength === l.id ? (isDark ? 'border-emerald-500 bg-emerald-900/20' : 'border-emerald-500 bg-emerald-50') : `${c.pillGray} border`}`}>{t(l.lk)}</button>))}</div>
                  </div>
                </div>
                <div><label className={`text-xs font-semibold ${c.textSecondary} block mb-1`}>{t('eut_instructions')} <span className={`text-[10px] ${c.textMuted}`}>({t('optional')})</span></label>
                  <input value={composeInstructions} onChange={e => setComposeInstructions(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') handleCompose(); }} placeholder={t('eut_compose_instr_ph')}
                    className={`w-full p-2.5 border rounded-lg ${c.input} outline-none text-sm`} />
                </div>
                <button onClick={handleCompose} disabled={loading} className={`w-full ${c.btnPrimary} disabled:opacity-40 font-bold py-3 rounded-lg flex items-center justify-center gap-2`}>
                  {loading ? <><span className="animate-spin inline-block">{tool?.icon ?? '📬'}</span> {t('eut_composing')}</> : <><span className="mr-1">{tool?.icon ?? '📬'}</span>{composeDraft.trim() ? t('eut_refine_reply') : t('eut_compose_reply')}</>}
                </button>
              </div>
            </div>

            {composeResult && (
              <div className={`${c.card} border rounded-xl p-5 space-y-4`}>
                <div className="flex items-center justify-between"><h3 className={`text-sm font-bold ${c.text}`}>{t('eut_composed_reply')}</h3></div>
                <div className={`${c.cardAlt} border rounded-lg p-3`}><p className={`text-[10px] font-bold ${c.textMuted} mb-1`}>{t('eut_subject')}</p><p className={`text-sm ${c.text}`}>{composeResult.subject_line}</p></div>
                <div className={`${c.highlight} border rounded-lg p-4`}><p className={`text-sm ${c.textSecondary} whitespace-pre-wrap`}>{composeResult.composed_reply}</p></div>
                <div className="flex flex-wrap gap-2">
                  {composeResult.key_points_addressed?.map((p, i) => <span key={i} className={`${c.pillGreen} border text-[9px] px-1.5 py-0.5 rounded`}>✓ {p}</span>)}
                  <span className={`${c.pillGray} border text-[9px] px-1.5 py-0.5 rounded`}>{t('eut_words_tone', { count: composeResult.word_count, tone: composeResult.tone_used })}</span>
                </div>
                {composeResult.alternative_closings?.length > 0 && (
                  <div><p className={`text-[10px] font-bold ${c.textMuted} mb-1`}>{t('eut_alt_closings')}</p><div className="flex flex-wrap gap-1">{composeResult.alternative_closings.map((cl, i) => <span key={i} className={`${c.pillGray} border text-[10px] px-2 py-0.5 rounded`}>{cl}</span>)}</div></div>
                )}
                <button onClick={() => { setComposeDraft(composeResult.composed_reply); setComposeResult(null); }} className={`${c.btnSecondary} text-xs px-3 py-2 rounded-lg`}>{t('eut_refine_further')}</button>
              </div>
            )}
          </>)}

          {/* Cross-references */}
          <p className={`text-xs ${c.textMuted} text-center`}>
            {t('eut_xref_compose')}{' '}
            {t('eut_xref_compose_2')}{' '}
            <a href="/GentlePushGenerator" className={`text-xs ${linkStyle}`}>📨 {t('eut_gentle_push')}</a>{' '}
            {t('eut_xref_compose_3')}
          </p>
        </div>
      )}

      {/* ══════════ F2+F5: BRIEFING MODE ══════════ */}
      {mode === 'briefing' && (
        <div className="space-y-4">
          {/* F5: Inbox Health */}
          {inboxHealth ? (
            <div className={`${c.card} border rounded-xl p-5`}>
              <h3 className={`text-sm font-bold ${c.text} mb-3`}>{t('eut_inbox_health')}</h3>
              <div className="flex items-center gap-4">
                <div className="relative w-20 h-20 flex-shrink-0">
                  <svg viewBox="0 0 36 36" className="w-full h-full -rotate-90">
                    <path d="M18 2.0845a 15.9155 15.9155 0 0 1 0 31.831a 15.9155 15.9155 0 0 1 0 -31.831" fill="none" stroke={isDark ? '#374151' : '#d1fae5'} strokeWidth="3" />
                    <path d="M18 2.0845a 15.9155 15.9155 0 0 1 0 31.831a 15.9155 15.9155 0 0 1 0 -31.831" fill="none"
                      stroke={inboxHealth.score >= 80 ? '#10b981' : inboxHealth.score >= 60 ? '#f59e0b' : '#ef4444'}
                      strokeWidth="3" strokeDasharray={`${inboxHealth.score}, 100`} strokeLinecap="round" />
                  </svg>
                  <div className="absolute inset-0 flex items-center justify-center"><span className={`text-lg font-bold ${c.text}`}>{inboxHealth.score}</span></div>
                </div>
                <div>
                  <p className={`text-sm font-bold ${c.text}`}>{inboxHealth.label}</p>
                  <p className={`text-xs ${c.textMuted}`}>{t('eut_sessions_emails', { sessions: inboxHealth.sessions, emails: inboxHealth.totalEmails })}</p>
                  <p className={`text-xs ${c.textMuted}`}>{t('eut_urgent_rate', { pct: inboxHealth.urgentRatio })}</p>
                </div>
              </div>
            </div>
          ) : (
            <div className={`${c.card} border rounded-xl p-5 text-center`}><span className="text-3xl block mb-2">🏥</span><p className={`text-sm ${c.textSecondary}`}>{t('eut_health_empty')}</p></div>
          )}

          {/* F2: Briefing */}
          {briefingData ? (
            <div className="space-y-4">
              {/* Overdue from previous */}
              {briefingData.overdue.length > 0 && (
                <div className={`${c.tierNow} border-2 rounded-xl p-4`}>
                  <h4 className="font-bold text-sm mb-2">{t('eut_unreplied_urgent', { count: briefingData.overdue.length })}</h4>
                  {briefingData.overdue.map((e, i) => <div key={i} className="flex items-center gap-2 mb-1"><span className={`text-[10px] ${c.textMuted}`}>{e.triageDate}</span><p className={`text-xs ${c.text} truncate`}>{e.email_subject} — {e.from}</p></div>)}
                </div>
              )}

              {/* Latest session summary */}
              <div className={`${c.card} border rounded-xl p-5`}>
                <h3 className={`text-sm font-bold ${c.text} mb-3`}>{t('eut_latest_triage', { date: briefingData.latest.date })}</h3>
                <div className="grid grid-cols-3 gap-3 mb-3">
                  <div className="text-center"><p className="text-xl font-bold">{briefingData.latest.summary?.urgent_count || 0}</p><p className={`text-[10px] ${c.textMuted}`}>{t('eut_urgent_label')}</p></div>
                  <div className="text-center"><p className="text-xl font-bold">{briefingData.latest.summary?.this_week_count || 0}</p><p className={`text-[10px] ${c.textMuted}`}>{t('eut_this_week_label')}</p></div>
                  <div className="text-center"><p className="text-xl font-bold">{briefingData.latest.summary?.optional_count || 0}</p><p className={`text-[10px] ${c.textMuted}`}>{t('eut_optional_label')}</p></div>
                </div>
                {briefingData.volumeChange !== null && (
                  <div className={`${briefingData.volumeChange > 20 ? c.tierNow : briefingData.volumeChange < -20 ? c.success : c.highlight} border rounded-lg p-3`}>
                    <p className="text-xs">{briefingData.volumeChange > 0 ? t('eut_vol_more', { pct: briefingData.volumeChange }) : briefingData.volumeChange < 0 ? t('eut_vol_fewer', { pct: Math.abs(briefingData.volumeChange) }) : t('eut_vol_same')} {t('eut_emails_vs_prev', { prev: briefingData.prevCount, latest: briefingData.latestCount })}</p>
                  </div>
                )}
                {briefingData.avgUrgent !== null && <p className={`text-xs ${c.textMuted} mt-2`}>{t('eut_avg_urgent', { n: briefingData.avgUrgent })}</p>}
              </div>

              {/* Volume trend */}
              {profileTriages.length >= 3 && (
                <div className={`${c.card} border rounded-xl p-5`}>
                  <h3 className={`text-sm font-bold ${c.text} mb-3`}>{t('eut_volume_trend')}</h3>
                  <div className="space-y-1.5">{profileTriages.slice(0, 6).map(entry => {
                    const total = entry.summary?.total_emails || 0;
                    const urgent = entry.summary?.urgent_count || 0;
                    const max = Math.max(...profileTriages.slice(0, 6).map(e => e.summary?.total_emails || 1));
                    return (<div key={entry.id} className="flex items-center gap-2"><span className={`w-16 text-[10px] ${c.textMuted}`}>{entry.date}</span><div className={`flex-1 h-4 rounded-full overflow-hidden ${isDark ? 'bg-zinc-700' : 'bg-emerald-100'} flex`}><div className="h-full bg-red-500 rounded-l-full" style={{ width: `${(urgent / max) * 100}%` }} /><div className="h-full bg-emerald-500" style={{ width: `${((total - urgent) / max) * 100}%` }} /></div><span className={`w-8 text-right text-[10px] font-bold ${c.textMuted}`}>{total}</span></div>);
                  })}</div>
                  <div className="flex items-center gap-3 mt-2"><div className="flex items-center gap-1"><div className="w-2 h-2 rounded bg-red-500" /><span className={`text-[9px] ${c.textMuted}`}>{t('eut_legend_urgent')}</span></div><div className="flex items-center gap-1"><div className="w-2 h-2 rounded bg-emerald-500" /><span className={`text-[9px] ${c.textMuted}`}>{t('eut_legend_other')}</span></div></div>
                </div>
              )}
            </div>
          ) : (
            <div className={`${c.card} border rounded-xl p-6 text-center`}><span className="text-3xl block mb-2">📰</span><p className={`text-sm ${c.textSecondary}`}>{t('eut_briefing_empty')}</p></div>
          )}
        </div>
      )}

      {/* ══════════ HISTORY + F4 SLA ══════════ */}
      {mode === 'history' && (
        <div className="space-y-4">
          {/* F4: SLA metrics */}
          {slaMetrics && (
            <div className={`${c.card} border rounded-xl p-5`}>
              <h3 className={`text-sm font-bold ${c.text} mb-3`}>{t('eut_response_tracking')}</h3>
              <div className="grid grid-cols-3 gap-3">
                <div className="text-center"><p className="text-xl font-bold">{slaMetrics.total}</p><p className={`text-[10px] ${c.textMuted}`}>{t('eut_completed')}</p></div>
                <div className="text-center"><p className="text-xl font-bold">{slaMetrics.recentWeek}</p><p className={`text-[10px] ${c.textMuted}`}>{t('eut_this_week_stat')}</p></div>
                <div className="text-center"><p className="text-xl font-bold">{Object.keys(slaMetrics.byTier).length}</p><p className={`text-[10px] ${c.textMuted}`}>{t('eut_tiers_used')}</p></div>
              </div>
              {Object.entries(slaMetrics.byTier).map(([tier, items]) => (
                <div key={tier} className="flex items-center gap-2 mt-2"><span className={`w-20 text-[10px] font-bold ${c.textMuted}`}>{TIER_CFG[tier]?.icon || '📧'} {TIER_CFG[tier]?.lk ? t(TIER_CFG[tier].lk) : tier}</span>
                  <div className={`flex-1 h-3 rounded-full overflow-hidden ${isDark ? 'bg-zinc-700' : 'bg-emerald-100'}`}><div className="h-full bg-emerald-500 rounded-full" style={{ width: `${(items.length / slaMetrics.total) * 100}%` }} /></div>
                  <span className={`w-6 text-right text-[10px] font-bold ${c.textMuted}`}>{items.length}</span></div>
              ))}
            </div>
          )}

          <div className={`${c.card} border rounded-xl p-5`}>
            <div className="flex items-center justify-between mb-3">
              <h3 className={`text-sm font-bold ${c.text}`}>{t('eut_history_title', { count: profileTriages.length })}</h3>
              {profileTriages.length > 0 && <button onClick={() => { if (window.confirm(t('eut_confirm_clear_history'))) setTriageHistory(p => p.filter(h => h.profileId !== activeProfileId)); }} className={`text-xs ${c.textMuted} hover:opacity-80`}>{t('eut_clear')}</button>}
            </div>
            {profileTriages.length === 0 ? <p className={`text-sm ${c.textSecondary} text-center py-6`}>{t('eut_history_empty')}</p>
            : <div className="space-y-2 max-h-[500px] overflow-y-auto">{profileTriages.map(entry => (
              <div key={entry.id} className={`${c.cardAlt} border rounded-lg p-4`}>
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2"><span className={`text-xs font-bold ${c.text}`}>{entry.date}</span><span className={`text-[10px] ${c.textMuted}`}>{entry.time}</span></div>
                  <div className="flex items-center gap-1.5">
                    <span className={`${c.pillRed} border text-[9px] font-bold px-1.5 py-0.5 rounded`}>{entry.summary?.urgent_count || 0}</span>
                    <span className={`${c.pillAmber} border text-[9px] font-bold px-1.5 py-0.5 rounded`}>{entry.summary?.this_week_count || 0}</span>
                    <span className={`${c.pillGreen} border text-[9px] font-bold px-1.5 py-0.5 rounded`}>{entry.summary?.optional_count || 0}</span>
                  </div>
                </div>
                <p className={`text-xs ${c.textSecondary}`}>{t('eut_emails_count', { count: entry.emailCount })}</p>
                {entry.subjects?.slice(0, 6).map((s, i) => <p key={i} className={`text-[10px] ${c.textMuted} truncate`}>• {s}</p>)}
                {Object.values(entry.handled || {}).filter(v => v === 'done').length > 0 && <p className={`text-[10px] ${c.textSecondary} mt-1`}>{t('eut_handled_count', { count: Object.values(entry.handled).filter(v => v === 'done').length })}</p>}
                <div className="flex gap-2 mt-2">
                  <button onClick={() => { setResults(entry.results); setHandled(entry.handled || {}); setOverrides({}); setMode('results'); }} className={`${c.btnSecondary} text-xs px-3 py-1 rounded-lg`}>{t('eut_view')}</button>
                  <button onClick={() => setTriageHistory(p => p.filter(e => e.id !== entry.id))} className={`text-xs ${c.textMuted} hover:opacity-80 px-1`}>🗑️</button>
                </div>
              </div>
            ))}</div>}
          </div>
        </div>
      )}

      {/* ══════════ SETTINGS: F3 RULES + F6 PROFILES + SENDERS ══════════ */}
      {mode === 'settings' && (
        <div className="space-y-4">
          {/* F3: Smart Rules */}
          <div className={`${c.card} border rounded-xl p-5`}>
            <h3 className={`text-sm font-bold ${c.text} mb-3`}>{t('eut_auto_rules', { count: profileRules.length })}</h3>
            <p className={`text-xs ${c.textMuted} mb-3`}>{t('eut_rules_hint')}</p>
            <div className={`${c.cardAlt} border rounded-lg p-3 mb-3 space-y-2`}>
              <div className="grid grid-cols-3 gap-2">
                <select value={ruleForm.type} onChange={e => setRuleForm(p => ({ ...p, type: e.target.value }))} className={`p-2 border rounded-lg ${c.input} text-xs`}>{RULE_TYPES.map(r => <option key={r.id} value={r.id}>{t(r.lk)}</option>)}</select>
                {ruleForm.type !== 'cc_only' && <><label htmlFor="eut-rule-pattern" className="sr-only">{t('eut_pattern_label')}</label><input id="eut-rule-pattern" value={ruleForm.pattern} onChange={e => setRuleForm(p => ({ ...p, pattern: e.target.value }))} placeholder={t('eut_pattern_ph')} className={`p-2 border rounded-lg ${c.input} text-xs`} /></>}
                <select value={ruleForm.tier} onChange={e => setRuleForm(p => ({ ...p, tier: e.target.value }))} className={`p-2 border rounded-lg ${c.input} text-xs`}>{Object.entries(TIER_CFG).map(([k, v]) => <option key={k} value={k}>{v.icon} {t(v.lk)}</option>)}</select>
              </div>
              <button onClick={() => {
                if (ruleForm.type !== 'cc_only' && !ruleForm.pattern.trim()) return;
                setRules(prev => [...prev, { id: Date.now(), profileId: activeProfileId, type: ruleForm.type, pattern: ruleForm.pattern.trim(), tier: ruleForm.tier, enabled: true }]);
                setRuleForm({ type: 'sender', pattern: '', tier: 'optional' });
              }} disabled={ruleForm.type !== 'cc_only' && !ruleForm.pattern.trim()} className={`${c.btnPrimary} disabled:opacity-40 text-xs px-3 py-1.5 rounded-lg`}>{t('eut_add_rule')}</button>
            </div>
            {rules.filter(r => r.profileId === activeProfileId).length === 0 ? <p className={`text-xs ${c.textMuted} text-center py-2`}>{t('eut_no_rules')}</p>
            : <div className="space-y-1.5">{rules.filter(r => r.profileId === activeProfileId).map(rule => (
              <div key={rule.id} className="flex items-center gap-2">
                <button onClick={() => setRules(p => p.map(r => r.id === rule.id ? { ...r, enabled: !r.enabled } : r))} className={`text-xs ${rule.enabled ? 'opacity-100' : 'opacity-40'}`}>{rule.enabled ? '✅' : '⬜'}</button>
                <span className={`text-[10px] font-bold ${c.textMuted} w-20`}>{(() => { const rt = RULE_TYPES.find(x => x.id === rule.type); return rt ? t(rt.lk) : rule.type; })()}</span>
                {rule.pattern && <span className={`text-xs ${c.text}`}>"{rule.pattern}"</span>}
                <span className="text-xs">→</span>
                <span className={`${c.pillGray} border text-[9px] px-1.5 py-0.5 rounded`}>{TIER_CFG[rule.tier]?.icon} {TIER_CFG[rule.tier]?.lk ? t(TIER_CFG[rule.tier].lk) : rule.tier}</span>
                <button onClick={() => setRules(p => p.filter(r => r.id !== rule.id))} className={`text-[10px] ${c.textMuted} hover:opacity-80 ml-auto`}>✕</button>
              </div>
            ))}</div>}
          </div>

          {/* Sender Intelligence */}
          <div className={`${c.card} border rounded-xl p-5`}>
            <div className="flex items-center justify-between mb-3">
              <h3 className={`text-sm font-bold ${c.text}`}>{t('eut_senders_title', { count: senderStats.total })}</h3>
              {senderStats.total > 0 && <button onClick={() => { if (window.confirm(t('eut_confirm_clear_senders'))) { const updated = { ...senderHistory }; Object.keys(updated).forEach(k => { if (k.startsWith(pfx)) delete updated[k]; }); setSenderHistory(updated); } }} className={`text-xs ${c.textMuted} hover:opacity-80`}>{t('eut_clear')}</button>}
            </div>
            {senderStats.total === 0 ? <p className={`text-xs ${c.textMuted} text-center py-3`}>{t('eut_senders_empty')}</p>
            : <div className="space-y-2 max-h-80 overflow-y-auto">{Object.entries(profileSenders).sort((a, b) => b[1].total - a[1].total).map(([sender, data]) => {
              const rep = getRep(sender);
              const topCat = data.categories ? Object.entries(data.categories).sort((a, b) => b[1] - a[1])[0] : null;
              return (
                <div key={sender} className={`${c.cardAlt} border rounded-lg p-3`}>
                  <div className="flex items-center justify-between mb-1">
                    <div className="flex items-center gap-2"><span className={`text-xs font-semibold ${c.text}`}>{sender}</span>{rep && <span className={`${c[rep.pill]} border text-[9px] font-bold px-1.5 py-0.5 rounded`}>{rep.icon} {rep.label}</span>}</div>
                    <button onClick={() => { const updated = { ...senderHistory }; delete updated[pfx + sender]; setSenderHistory(updated); }} className={`text-[10px] ${c.textMuted} hover:opacity-80`}>✕</button>
                  </div>
                  <div className="flex flex-wrap gap-1.5 items-center">
                    <span className={`${c.pillGray} border text-[9px] px-1.5 py-0.5 rounded`}>{t('eut_emails_pill', { count: data.total })}</span>
                    <span className={`${c.pillRed} border text-[9px] px-1.5 py-0.5 rounded`}>{t('eut_urgent_pill', { count: data.actuallyUrgent || 0 })}</span>
                    {data.cryWolfScore > 0.3 && <span className={`${c.pillAmber} border text-[9px] px-1.5 py-0.5 rounded`}>🐺 {Math.round(data.cryWolfScore * 100)}%</span>}
                    {topCat && <span className={`${c.pillCyan} border text-[9px] px-1.5 py-0.5 rounded`}>{topCat[0]}</span>}
                  </div>
                  <div className="flex gap-1.5 mt-2">
                    <button onClick={() => setSenderHistory(prev => ({ ...prev, [pfx + sender]: { ...prev[pfx + sender], actuallyUrgent: prev[pfx + sender].total, cryWolfScore: 0 } }))} className={`text-[9px] px-2 py-0.5 rounded border ${c.pillAmber} border`}>{t('eut_vip_btn')}</button>
                    <button onClick={() => setSenderHistory(prev => ({ ...prev, [pfx + sender]: { ...prev[pfx + sender], actuallyUrgent: 0, cryWolfScore: 1 } }))} className={`text-[9px] px-2 py-0.5 rounded border ${c.pillGray} border`}>{t('eut_noise_btn')}</button>
                    <button onClick={() => { setRules(prev => [...prev, { id: Date.now(), profileId: activeProfileId, type: 'sender', pattern: sender, tier: 'optional', enabled: true }]); }} className={`text-[9px] px-2 py-0.5 rounded border ${c.pillGray} border`}>{t('eut_rule_btn')}</button>
                  </div>
                </div>
              );
            })}</div>}
          </div>

          {/* Category breakdown */}
          {(() => {
            const allCats = {};
            Object.values(profileSenders).forEach(h => { if (h.categories) Object.entries(h.categories).forEach(([cat, count]) => { allCats[cat] = (allCats[cat] || 0) + count; }); });
            const total = Object.values(allCats).reduce((s, v) => s + v, 0);
            if (!total) return null;
            return (
              <div className={`${c.card} border rounded-xl p-5`}><h3 className={`text-sm font-bold ${c.text} mb-3`}>{t('eut_categories')}</h3>
                <div className="space-y-1.5">{Object.entries(allCats).sort((a, b) => b[1] - a[1]).map(([cat, count]) => {
                  const info = getCat(cat);
                  return (<div key={cat} className="flex items-center gap-2"><span className={`text-xs font-semibold ${c.text} w-32`}>{info.icon} {cat}</span><div className={`flex-1 h-3 rounded-full overflow-hidden ${isDark ? 'bg-zinc-700' : 'bg-emerald-100'}`}><div className={`h-full rounded-full ${info.bg}`} style={{ width: `${(count / total) * 100}%` }} /></div><span className={`w-8 text-right text-[10px] font-bold ${c.textMuted}`}>{count}</span></div>);
                })}</div>
              </div>
            );
          })()}

          {/* Response time clear */}
          {profileResponses.length > 0 && <button onClick={() => { if (window.confirm(t('eut_confirm_clear_responses'))) setResponseTimes(p => p.filter(r => r.profileId !== activeProfileId)); }} className={`text-xs ${c.textMuted} hover:opacity-80`}>{t('eut_clear_responses', { count: profileResponses.length })}</button>}
        </div>
      )}
    </div>
  );
};

EmailUrgencyTriager.displayName = 'EmailUrgencyTriager';
export default EmailUrgencyTriager;
