import React, { useState } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { getToolById } from '../data/tools';
import { CopyBtn, ActionBar } from '../components/ActionButtons';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

const CONSTRAINTS = [
  { id: 'dairy-free', icon: '🥛', label: 'Dairy-Free' }, { id: 'gluten-free', icon: '🌾', label: 'Gluten-Free' },
  { id: 'vegan', icon: '🌱', label: 'Vegan' }, { id: 'vegetarian', icon: '🥬', label: 'Vegetarian' },
  { id: 'keto', icon: '🥓', label: 'Keto / Low-Carb' }, { id: 'nut-free', icon: '🥜', label: 'Nut-Free' },
  { id: 'egg-free', icon: '🥚', label: 'Egg-Free' }, { id: 'soy-free', icon: '🫘', label: 'Soy-Free' },
  { id: 'sugar-free', icon: '🍬', label: 'Sugar-Free / Low Sugar' }, { id: 'low-sodium', icon: '🧂', label: 'Low Sodium' },
  { id: 'fodmap', icon: '🫃', label: 'Low FODMAP' }, { id: 'halal', icon: '☪️', label: 'Halal' },
  { id: 'kosher', icon: '✡️', label: 'Kosher' }, { id: 'pescatarian', icon: '🐟', label: 'Pescatarian' },
];
const CUISINES = [
  { id: 'italian', icon: '🇮🇹', label: 'Italian' }, { id: 'chinese', icon: '🇨🇳', label: 'Chinese' },
  { id: 'japanese', icon: '🇯🇵', label: 'Japanese' }, { id: 'mexican', icon: '🇲🇽', label: 'Mexican' },
  { id: 'thai', icon: '🇹🇭', label: 'Thai' }, { id: 'indian', icon: '🇮🇳', label: 'Indian' },
  { id: 'korean', icon: '🇰🇷', label: 'Korean' }, { id: 'french', icon: '🇫🇷', label: 'French' },
  { id: 'american', icon: '🇺🇸', label: 'American / Diner' }, { id: 'mediterranean', icon: '🫒', label: 'Mediterranean' },
  { id: 'ethiopian', icon: '🇪🇹', label: 'Ethiopian' }, { id: 'middle-eastern', icon: '🧆', label: 'Middle Eastern' },
  { id: 'other', icon: '🍽️', label: 'Other' },
];
const CURRENT_MONTH = new Date().toLocaleString('default', { month: 'long', year: 'numeric' });

const FoodSwap = () => {
  const { callToolEndpoint, loading } = useClaudeAPI();
  const { theme } = useTheme();
  const isDark = theme === 'dark';
  const toolData = getToolById('FoodSwap');

  const c = {
    card: isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt: isDark ? 'bg-zinc-700/50' : 'bg-orange-50/50',
    text: isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted: isDark ? 'text-zinc-500' : 'text-gray-400',
    label: isDark ? 'text-zinc-200' : 'text-gray-800',
    input: isDark ? 'bg-zinc-700 border-zinc-600 text-zinc-100 placeholder-zinc-400' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400',
    btnPrimary: isDark ? 'bg-orange-600 hover:bg-orange-500 text-white' : 'bg-orange-600 hover:bg-orange-700 text-white',
    btnSecondary: isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-100' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    btnActive: isDark ? 'bg-orange-600 text-white' : 'bg-orange-600 text-white',
    btnInactive: isDark ? 'bg-zinc-700 text-zinc-300 hover:bg-zinc-600' : 'bg-gray-100 text-gray-600 hover:bg-gray-200',
    border: isDark ? 'border-zinc-700' : 'border-gray-200',
    success: isDark ? 'bg-green-900/20 border-green-700 text-green-200' : 'bg-green-50 border-green-300 text-green-800',
    warning: isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    danger: isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-200 text-red-800',
    info: isDark ? 'bg-blue-900/20 border-blue-700 text-blue-200' : 'bg-blue-50 border-blue-200 text-blue-800',
    accentBg: isDark ? 'bg-orange-900/20 border-orange-700' : 'bg-orange-50 border-orange-200',
    accentText: isDark ? 'text-orange-300' : 'text-orange-700',
    purpleBg: isDark ? 'bg-purple-900/20 border-purple-700 text-purple-200' : 'bg-purple-50 border-purple-200 text-purple-800',
    scoreBg: (s) => s >= 85 ? (isDark ? 'bg-green-900/30 text-green-300' : 'bg-green-100 text-green-700') : s >= 70 ? (isDark ? 'bg-amber-900/30 text-amber-300' : 'bg-amber-100 text-amber-700') : (isDark ? 'bg-red-900/30 text-red-300' : 'bg-red-100 text-red-700'),
  };

  // ─── State: Mode + error ───
  const [mode, setMode] = useState('swap');
  const [error, setError] = useState('');

  // ─── State: Multi-constraint (persistent) ───
  const [selectedConstraints, setSelectedConstraints] = usePersistentState('food-swap-constraints', []);
  const [customConstraint, setCustomConstraint] = useState('');

  // ─── State: Swap ───
  const [food, setFood] = useState('');
  const [results, setResults] = useState(null);

  // ─── State: Restaurant ───
  const [selectedCuisine, setSelectedCuisine] = useState('');
  const [customCuisine, setCustomCuisine] = useState('');
  const [specificRestaurant, setSpecificRestaurant] = useState('');
  const [cravingType, setCravingType] = useState('');
  const [restaurantResults, setRestaurantResults] = useState(null);

  // ─── State: Pantry ───
  const [stapleMeals, setStapleMeals] = useState('');
  const [pantryResults, setPantryResults] = useState(null);

  // ─── State: Craving ───
  const [cravingText, setCravingText] = useState('');
  const [mood, setMood] = useState('');
  const [timeOfDay, setTimeOfDay] = useState('');
  const [cravingResults, setCravingResults] = useState(null);

  // ─── State: Batch ───
  const [batchMeals, setBatchMeals] = useState(['']);
  const [batchResults, setBatchResults] = useState(null);

  // ─── State: Label ───
  const [productName, setProductName] = useState('');
  const [ingredientList, setIngredientList] = useState('');
  const [labelResults, setLabelResults] = useState(null);

  // ─── State: Social + Host ───
  const [socialSituation, setSocialSituation] = useState('');
  const [socialRelationship, setSocialRelationship] = useState('');
  const [socialResults, setSocialResults] = useState(null);
  const [socialSubMode, setSocialSubMode] = useState('event');
  const [hostContext, setHostContext] = useState('');
  const [plannedMenu, setPlannedMenu] = useState('');
  const [hostResults, setHostResults] = useState(null);

  // ─── State: Meal Plan ───
  const [mealPlanDays, setMealPlanDays] = useState(7);
  const [mealPlanPrefs, setMealPlanPrefs] = useState('');
  const [mealPlanResults, setMealPlanResults] = useState(null);

  // ─── State: Travel (v3) ───
  const [travelDest, setTravelDest] = useState('');
  const [tripLength, setTripLength] = useState('');
  const [travelResults, setTravelResults] = useState(null);

  // ─── State: Party Planner (v3) ───
  const [partyGuests, setPartyGuests] = useState([{ name: '', constraints: '' }]);
  const [partyOccasion, setPartyOccasion] = useState('');
  const [partyCuisine, setPartyCuisine] = useState('');
  const [partyResults, setPartyResults] = useState(null);

  // ─── State: Journal entry form (v3) ───
  const [journalSwapName, setJournalSwapName] = useState('');
  const [journalOriginal, setJournalOriginal] = useState('');
  const [journalRating, setJournalRating] = useState(7);
  const [journalNotes, setJournalNotes] = useState('');
  const [styleResults, setStyleResults] = useState(null);
  const [styleLoading, setStyleLoading] = useState(false);

  // ─── State: Fridge Check (v3) ───
  const [fridgeItems, setFridgeItems] = useState('');
  const [fridgePlanned, setFridgePlanned] = useState('');
  const [fridgeResults, setFridgeResults] = useState(null);

  // ─── State: Expiration (v3) ───
  const [expiryProducts, setExpiryProducts] = useState('');
  const [expiryResults, setExpiryResults] = useState(null);

  // ─── State: Confidence check-in form (v3) ───
  const [confidenceLevel, setConfidenceLevel] = useState(5);
  const [confidenceNote, setConfidenceNote] = useState('');

  // ─── Deep Dive + Recipe + Reswap ───
  const [deepData, setDeepData] = useState({});
  const [deepLoading, setDeepLoading] = useState(null);
  const [recipeData, setRecipeData] = useState({});
  const [recipeLoading, setRecipeLoading] = useState(null);
  const [reswapLoading, setReswapLoading] = useState(null);

  // ─── Persistent state ───
  const [userProfile, setUserProfile] = usePersistentState('food-swap-profile', { budget: '', cookingSkill: '', location: '', groceryAccess: '' });
  const [showProfile, setShowProfile] = useState(false);
  const [history, setHistory] = usePersistentState('food-swap-history', []);
  const [ratings, setRatings] = usePersistentState('food-swap-ratings', {});
  const [favorites, setFavorites] = usePersistentState('food-swap-favorites', []);
  const [showFavorites, setShowFavorites] = useState(false);
  const [journal, setJournal] = usePersistentState('food-swap-journal', []);
  const [dictionary, setDictionary] = usePersistentState('food-swap-dictionary', []);
  const [showDictionary, setShowDictionary] = useState(false);
  const [dictSearch, setDictSearch] = useState('');
  const [confidenceLog, setConfidenceLog] = usePersistentState('food-swap-confidence', []);
  const [showConfidence, setShowConfidence] = useState(false);

  // ─── UI ───
  const [expandedSections, setExpandedSections] = useState({});
  const toggleSection = (k) => setExpandedSections(p => ({ ...p, [k]: !p[k] }));

  // ═══ HELPERS ═══
  const toggleConstraint = (id) => setSelectedConstraints(prev => prev.includes(id) ? prev.filter(c => c !== id) : [...prev, id]);
  const getConstraintLabels = () => { const l = selectedConstraints.map(id => CONSTRAINTS.find(c => c.id === id)?.label).filter(Boolean); if (customConstraint.trim()) l.push(customConstraint.trim()); return l; };
  const getConstraintPayload = () => { const l = getConstraintLabels(); return l.length === 1 ? l[0] : l; };
  const hasConstraint = () => getConstraintLabels().length > 0;
  const getCuisineText = () => selectedCuisine === 'other' ? customCuisine.trim() : CUISINES.find(c => c.id === selectedCuisine)?.label || customCuisine.trim() || '';
  const addToHistory = (type, input) => setHistory(prev => [{ type, input, timestamp: new Date().toISOString() }, ...prev].slice(0, 50));
  const rateSwap = (name, r) => setRatings(prev => ({ ...prev, [name]: r }));
  const toggleFavorite = (swap) => setFavorites(prev => prev.find(f => f.name === swap.name) ? prev.filter(f => f.name !== swap.name) : [...prev, { name: swap.name, food, constraint: getConstraintLabels().join(' + '), score: swap.closeness_score, timestamp: new Date().toISOString() }]);
  const isFavorite = (name) => favorites.some(f => f.name === name);
  const getDislikedSwaps = () => Object.entries(ratings).filter(([, v]) => v === 'down').map(([k]) => k);

  // Dictionary helpers
  const addToDictionary = (ingredient, meaning, constraint) => {
    setDictionary(prev => {
      if (prev.find(d => d.ingredient.toLowerCase() === ingredient.toLowerCase())) return prev;
      return [{ ingredient, meaning, constraint, timestamp: new Date().toISOString() }, ...prev];
    });
  };
  const filteredDict = dictSearch.trim() ? dictionary.filter(d => d.ingredient.toLowerCase().includes(dictSearch.toLowerCase()) || d.meaning.toLowerCase().includes(dictSearch.toLowerCase())) : dictionary;

  // Journal helpers
  const addJournalEntry = () => {
    if (!journalSwapName.trim()) return;
    setJournal(prev => [{ swapName: journalSwapName.trim(), originalFood: journalOriginal.trim(), rating: journalRating, notes: journalNotes.trim(), timestamp: new Date().toISOString() }, ...prev].slice(0, 100));
    setJournalSwapName(''); setJournalOriginal(''); setJournalRating(7); setJournalNotes('');
  };

  // Confidence helpers
  const addConfidenceCheckin = () => {
    setConfidenceLog(prev => [{ level: confidenceLevel, note: confidenceNote.trim(), timestamp: new Date().toISOString() }, ...prev].slice(0, 100));
    setConfidenceNote('');
  };
  const getTransitionDays = () => { const first = confidenceLog[confidenceLog.length - 1]; return first ? Math.floor((Date.now() - new Date(first.timestamp).getTime()) / 86400000) : 0; };

  // ═══ API HANDLERS (existing v2 — all preserved) ═══
  const handleSwap = async () => {
    if (!food.trim() || !hasConstraint()) { setError('Tell us what you love and pick at least one constraint.'); return; }
    setError('');
    const data = await callToolEndpoint('food-swap', { food: food.trim(), constraint: getConstraintPayload(), profileCtx: userProfile, dislikedSwaps: getDislikedSwaps(), favorites });
    if (data) { setResults(data); addToHistory('swap', `${food} → ${getConstraintLabels().join(' + ')}`); }
  };

  const handleReswap = async (index, rejectedName) => {
    setReswapLoading(index);
    const data = await callToolEndpoint('food-swap-reswap', { food: food.trim(), constraint: getConstraintPayload(), rejectedSwap: rejectedName, allRejected: [...getDislikedSwaps(), rejectedName], profileCtx: userProfile, favorites });
    if (data?.swap && results) { const s = [...results.swaps]; s[index] = data.swap; setResults({ ...results, swaps: s }); rateSwap(rejectedName, 'down'); }
    setReswapLoading(null);
  };

  const handleRestaurant = async () => {
    if (!getCuisineText() || !hasConstraint()) { setError('Pick a cuisine and constraint.'); return; }
    setError('');
    const data = await callToolEndpoint('food-swap-restaurant', { cuisine: getCuisineText(), constraint: getConstraintPayload(), specificRestaurant, cravingType, profileCtx: userProfile });
    if (data) { setRestaurantResults(data); addToHistory('restaurant', `${getCuisineText()}`); }
  };

  const handlePantry = async () => {
    if (!stapleMeals.trim() || !hasConstraint()) { setError('List staples and pick a constraint.'); return; }
    setError('');
    const data = await callToolEndpoint('food-swap-pantry', { stapleMeals: `${stapleMeals.trim()}\n[SEASONAL CONTEXT: ${CURRENT_MONTH}]`, constraint: getConstraintPayload(), profileCtx: userProfile });
    if (data) { setPantryResults(data); addToHistory('pantry', 'Pantry transition'); }
  };

  const handleCraving = async () => {
    if (!cravingText.trim() || !hasConstraint()) { setError('Describe craving and pick a constraint.'); return; }
    setError('');
    const data = await callToolEndpoint('food-swap-craving', { craving: cravingText.trim(), constraint: getConstraintPayload(), mood, timeOfDay, profileCtx: userProfile });
    if (data) { setCravingResults(data); addToHistory('craving', cravingText.substring(0, 40)); }
  };

  const handleBatch = async () => {
    const meals = batchMeals.filter(m => m.trim());
    if (!meals.length || !hasConstraint()) { setError('Add meals and pick a constraint.'); return; }
    setError('');
    const data = await callToolEndpoint('food-swap-batch', { meals, constraint: getConstraintPayload(), profileCtx: userProfile });
    if (data) { setBatchResults(data); addToHistory('batch', `${meals.length} meals`); }
  };

  const handleLabel = async () => {
    if ((!productName.trim() && !ingredientList.trim()) || !hasConstraint()) { setError('Enter a product and pick a constraint.'); return; }
    setError('');
    const data = await callToolEndpoint('food-swap-label', { productName: productName.trim(), ingredients: ingredientList.trim(), constraint: getConstraintPayload() });
    if (data) {
      setLabelResults(data);
      addToHistory('label', productName || 'product');
      // Auto-save flagged ingredients to dictionary
      data.flagged_ingredients?.forEach(f => addToDictionary(f.ingredient, f.why_flagged, f.which_constraint || getConstraintLabels().join(', ')));
      data.hidden_names?.forEach(n => addToDictionary(n, `Hidden name for flagged ingredient in ${productName || 'product'}`, getConstraintLabels().join(', ')));
    }
  };

  const handleSocial = async () => {
    if (!socialSituation.trim() || !hasConstraint()) { setError('Describe situation and pick a constraint.'); return; }
    setError('');
    const data = await callToolEndpoint('food-swap-social', { situation: socialSituation.trim(), constraint: getConstraintPayload(), relationship: socialRelationship });
    if (data) { setSocialResults(data); addToHistory('social', socialSituation.substring(0, 40)); }
  };

  const handleHost = async () => {
    if (!hostContext.trim() || !hasConstraint()) { setError('Describe dinner and pick a constraint.'); return; }
    setError('');
    const data = await callToolEndpoint('food-swap-host', { hostContext: hostContext.trim(), constraint: getConstraintPayload(), relationship: socialRelationship, plannedMenu });
    if (data) { setHostResults(data); addToHistory('host', hostContext.substring(0, 40)); }
  };

  const handleMealPlan = async () => {
    if (!hasConstraint()) { setError('Pick a constraint.'); return; }
    setError('');
    const data = await callToolEndpoint('food-swap-mealplan', { constraint: getConstraintPayload(), days: mealPlanDays, preferences: `${mealPlanPrefs}\n[SEASONAL: ${CURRENT_MONTH} — prefer in-season produce]`, profileCtx: userProfile, favorites });
    if (data) { setMealPlanResults(data); addToHistory('mealplan', `${mealPlanDays}-day plan`); }
  };

  // ═══ API HANDLERS (v3 new) ═══
  const handleTravel = async () => {
    if (!travelDest.trim() || !hasConstraint()) { setError('Enter destination and pick a constraint.'); return; }
    setError('');
    const data = await callToolEndpoint('food-swap-travel', { destination: travelDest.trim(), constraint: getConstraintPayload(), tripLength, profileCtx: userProfile });
    if (data) { setTravelResults(data); addToHistory('travel', travelDest); }
  };

  const handleParty = async () => {
    const guests = partyGuests.filter(g => g.constraints.trim());
    if (!guests.length) { setError('Add at least one guest with dietary needs.'); return; }
    setError('');
    const data = await callToolEndpoint('food-swap-party', { guestCount: guests.length, guestConstraints: guests.map(g => ({ name: g.name, constraints: g.constraints })), occasion: partyOccasion, cuisinePreference: partyCuisine, profileCtx: userProfile });
    if (data) { setPartyResults(data); addToHistory('party', `${guests.length} guests`); }
  };

  const handleSwapStyle = async () => {
    if (journal.length < 5) { setError('Log at least 5 journal entries first.'); return; }
    setError(''); setStyleLoading(true);
    const data = await callToolEndpoint('food-swap-style', { journalEntries: journal, constraint: getConstraintPayload(), favorites });
    if (data) setStyleResults(data);
    setStyleLoading(false);
  };

  const handleFridgeCheck = async () => {
    if (!fridgeItems.trim()) { setError('List what you have on hand.'); return; }
    setError('');
    const data = await callToolEndpoint('food-swap-fridge', { onHand: fridgeItems.trim(), constraint: getConstraintPayload(), mealsPlanned: fridgePlanned, profileCtx: userProfile });
    if (data) { setFridgeResults(data); addToHistory('fridge', 'Fridge check'); }
  };

  const handleExpiry = async () => {
    if (!expiryProducts.trim()) { setError('List the swap products.'); return; }
    setError('');
    const data = await callToolEndpoint('food-swap-expiry', { products: expiryProducts.split(',').map(p => p.trim()).filter(Boolean), constraint: getConstraintPayload() });
    if (data) { setExpiryResults(data); addToHistory('expiry', 'Expiration guide'); }
  };

  const handleDeepDive = async (swapName, origFood) => {
    const k = `${swapName}-${origFood}`; if (deepData[k]) return; setDeepLoading(k);
    const data = await callToolEndpoint('food-swap-deep', { swapName, originalFood: origFood, constraint: getConstraintPayload() });
    if (data) setDeepData(p => ({ ...p, [k]: data })); setDeepLoading(null);
  };

  const handleRecipe = async (recipeName, origFood) => {
    const k = `${recipeName}-${origFood}`; if (recipeData[k]) return; setRecipeLoading(k);
    const data = await callToolEndpoint('food-swap-recipe', { recipeName, originalFood: origFood, constraint: getConstraintPayload(), profileCtx: userProfile });
    if (data) setRecipeData(p => ({ ...p, [k]: data })); setRecipeLoading(null);
  };

  // ═══ TEXT BUILDERS ═══
  const buildSwapText = () => { if (!results) return ''; let t = `🔄 FoodSwap: ${food} → ${getConstraintLabels().join(' + ')}\n\n`; results.swaps?.forEach((s, i) => { t += `${i + 1}. ${s.name} (${s.closeness_score}%)\n   ${s.description}\n   Tip: ${s.pro_tip}\n\n`; }); return t + BRAND; };

  // ═══ SUB-COMPONENTS ═══
  const MODES = [
    { id: 'swap', icon: '🔄', label: 'Swap' }, { id: 'restaurant', icon: '🍽️', label: 'Eat Out' },
    { id: 'pantry', icon: '🛒', label: 'Pantry' }, { id: 'craving', icon: '🧠', label: 'Cravings' },
    { id: 'batch', icon: '📋', label: 'Batch' }, { id: 'mealplan', icon: '📅', label: 'Meal Plan' },
    { id: 'label', icon: '🏷️', label: 'Labels' }, { id: 'social', icon: '🗣️', label: 'Social' },
    { id: 'travel', icon: '✈️', label: 'Travel' }, { id: 'party', icon: '🎉', label: 'Party' },
    { id: 'journal', icon: '📓', label: 'Journal' },
  ];

  const ScoreBar = ({ score, label }) => (
    <div className="flex items-center gap-2">
      {label && <span className={`text-xs ${c.textMuted}`}>{label}</span>}
      <div className={`flex-1 h-2 rounded-full ${isDark ? 'bg-zinc-600' : 'bg-gray-200'}`}>
        <div className={`h-2 rounded-full transition-all ${score >= 85 ? 'bg-green-500' : score >= 70 ? 'bg-amber-500' : 'bg-red-400'}`} style={{ width: `${Math.min(score, 100)}%` }} />
      </div>
      <span className={`text-sm font-bold ${c.scoreBg(score)} px-2 py-0.5 rounded-full`}>{score}%</span>
    </div>
  );

  const SwapCard = ({ swap, index, originalFood }) => {
    const dKey = `${swap.name}-${originalFood}`;
    const deep = deepData[dKey]; const recipe = recipeData[dKey]; const rating = ratings[swap.name]; const fav = isFavorite(swap.name);
    return (
      <div className={`${c.card} border ${c.border} rounded-xl p-4 space-y-3`}>
        <div className="flex items-start justify-between gap-2">
          <div className="flex-1">
            <div className="flex items-center gap-2 flex-wrap">
              <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${isDark ? 'bg-zinc-600 text-zinc-300' : 'bg-gray-200 text-gray-600'}`}>#{index + 1}</span>
              <span className={`text-xs px-2 py-0.5 rounded-full ${isDark ? 'bg-orange-900/30 text-orange-300' : 'bg-orange-100 text-orange-700'}`}>{swap.type}</span>
              {rating && <span className={`text-xs px-2 py-0.5 rounded-full ${rating === 'up' ? (isDark ? 'bg-green-900/30 text-green-300' : 'bg-green-100 text-green-700') : (isDark ? 'bg-red-900/30 text-red-300' : 'bg-red-100 text-red-700')}`}>{rating === 'up' ? '👍' : '👎'}</span>}
            </div>
            <h4 className={`text-lg font-bold ${c.text} mt-1`}>{swap.name}</h4>
          </div>
          <button onClick={() => toggleFavorite(swap)} className="text-lg">{fav ? '⭐' : '☆'}</button>
        </div>
        <ScoreBar score={swap.closeness_score} label="Match" />
        <p className={`text-sm ${c.textSecondary}`}>{swap.description}</p>
        <div className="grid grid-cols-2 gap-2 text-xs">
          {[['Brand', swap.brand_or_recipe], ['Where', swap.where_to_find], ['Cost', swap.cost_comparison], ['Prep', swap.prep_difficulty]].map(([l, v]) => <div key={l} className={`${c.cardAlt} rounded-lg p-2`}><span className={c.textMuted}>{l}</span><p className={`${c.text} font-medium mt-0.5`}>{v}</p></div>)}
        </div>
        {swap.pro_tip && <div className={`${isDark ? 'bg-amber-900/20 border-amber-700' : 'bg-amber-50 border-amber-200'} border rounded-lg p-3 text-sm`}>💡 <strong>Pro tip:</strong> {swap.pro_tip}</div>}
        {swap.honest_gap && <p className={`text-xs ${c.textMuted} italic`}>⚡ Gap: {swap.honest_gap}</p>}
        <div className="flex items-center gap-1.5 flex-wrap">
          <button onClick={() => rateSwap(swap.name, 'up')} className={`text-xs px-2 py-1 rounded-lg ${rating === 'up' ? (isDark ? 'bg-green-900/30 text-green-300' : 'bg-green-100 text-green-700') : c.btnSecondary}`}>👍</button>
          <button onClick={() => rateSwap(swap.name, 'down')} className={`text-xs px-2 py-1 rounded-lg ${rating === 'down' ? (isDark ? 'bg-red-900/30 text-red-300' : 'bg-red-100 text-red-700') : c.btnSecondary}`}>👎</button>
          <button onClick={() => handleDeepDive(swap.name, originalFood)} disabled={deepLoading === dKey || !!deep} className={`text-xs px-2 py-1 rounded-lg ${deep ? (isDark ? 'bg-green-900/30 text-green-300' : 'bg-green-100 text-green-700') : c.btnSecondary}`}>{deepLoading === dKey ? '⏳' : deep ? '✅ Deep' : '🔍 Deep'}</button>
          <button onClick={() => handleRecipe(swap.brand_or_recipe || swap.name, originalFood)} disabled={recipeLoading === dKey || !!recipe} className={`text-xs px-2 py-1 rounded-lg ${recipe ? (isDark ? 'bg-green-900/30 text-green-300' : 'bg-green-100 text-green-700') : c.btnSecondary}`}>{recipeLoading === dKey ? '⏳' : recipe ? '✅ Recipe' : '📖 Recipe'}</button>
          <button onClick={() => handleReswap(index, swap.name)} disabled={reswapLoading === index} className={`text-xs px-2 py-1 rounded-lg ${c.btnSecondary}`}>{reswapLoading === index ? '⏳' : '🔀 Try Another'}</button>
          <button onClick={() => { setJournalSwapName(swap.name); setJournalOriginal(food); setMode('journal'); }} className={`text-xs px-2 py-1 rounded-lg ${c.btnSecondary}`}>📓 Log</button>
          <CopyBtn content={`${swap.name} (${swap.closeness_score}%)\n${swap.description}\nTip: ${swap.pro_tip}${BRAND}`} label="Copy" />
        </div>
        {/* Deep + Recipe expansions (preserved from v2) */}
        {deep && <div className={`${c.cardAlt} rounded-lg p-4 space-y-2 border ${c.border}`}><h5 className={`font-bold ${c.accentText} text-sm`}>🔍 {deep.swap_name}</h5>{deep.detailed_comparison && <div className="grid grid-cols-2 gap-2 text-xs">{Object.entries(deep.detailed_comparison).map(([k, v]) => <div key={k} className={`${c.card} rounded-lg p-2 border ${c.border}`}><span className={`font-bold ${c.textMuted} uppercase`}>{k}</span><p className={`${c.textSecondary} mt-0.5`}>{v}</p></div>)}</div>}{deep.best_brands?.map((b, i) => <p key={i} className={`text-xs ${c.textSecondary}`}><strong>{b.brand}</strong> {b.product} — {b.verdict}</p>)}{deep.honest_verdict && <p className={`text-xs ${c.textSecondary} mt-1`}>📋 {deep.honest_verdict}</p>}</div>}
        {recipe && <div className={`${isDark ? 'bg-emerald-900/20 border-emerald-700' : 'bg-emerald-50 border-emerald-200'} border rounded-lg p-4 space-y-2`}><h5 className={`font-bold ${isDark ? 'text-emerald-300' : 'text-emerald-700'} text-sm`}>📖 {recipe.recipe_name}</h5><div className="flex flex-wrap gap-2 text-xs"><span className={`px-2 py-1 rounded-full ${c.cardAlt}`}>⏱️ {recipe.total_time}</span><span className={`px-2 py-1 rounded-full ${c.cardAlt}`}>📊 {recipe.difficulty}</span></div>{recipe.ingredients?.map((i, idx) => <p key={idx} className={`text-xs ${c.textSecondary}`}>• {i.amount} {i.item}</p>)}{recipe.steps?.map(s => <p key={s.step} className={`text-xs ${c.text}`}><strong>{s.step}.</strong> {s.instruction}</p>)}<CopyBtn content={`${recipe.recipe_name}\n\n${recipe.ingredients?.map(i => `• ${i.amount} ${i.item}`).join('\n')}\n\n${recipe.steps?.map(s => `${s.step}. ${s.instruction}`).join('\n')}${BRAND}`} label="Copy Recipe" /></div>}
      </div>
    );
  };

  // ═══════════════════════════════════════════════════
  // RENDER
  // ═══════════════════════════════════════════════════
  return (
    <div className="max-w-4xl mx-auto space-y-6">

      {/* Mode Tabs */}
      <div className="flex flex-wrap gap-1.5">
        {MODES.map(m => <button key={m.id} onClick={() => { setMode(m.id); setError(''); }} className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${mode === m.id ? c.btnActive : c.btnInactive}`}><span className="mr-1">{m.icon}</span> {m.label}</button>)}
        {[
          ['showProfile', setShowProfile, showProfile, '⚙️', 'Profile'],
          ['showFavorites', setShowFavorites, showFavorites, '⭐', `Favs${favorites.length > 0 ? ` (${favorites.length})` : ''}`],
          ['showDictionary', setShowDictionary, showDictionary, '📖', `Dict${dictionary.length > 0 ? ` (${dictionary.length})` : ''}`],
          ['showConfidence', setShowConfidence, showConfidence, '📊', 'Confidence'],
        ].map(([key, setter, val, ico, lbl]) => <button key={key} onClick={() => setter(!val)} className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${val ? c.btnActive : c.btnInactive}`}><span className="mr-1">{ico}</span> {lbl}</button>)}
      </div>

      {/* ─── Profile Panel ─── */}
      {showProfile && (
        <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-3`}>
          <h3 className={`font-bold ${c.text}`}>⚙️ Your Food Profile</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {[['Budget', 'budget', [['', 'Not set'], ['tight', 'Tight'], ['moderate', 'Moderate'], ['flexible', 'Flexible']]], ['Cooking Skill', 'cookingSkill', [['', 'Not set'], ['beginner', 'Beginner'], ['intermediate', 'Intermediate'], ['advanced', 'Advanced']]], ['Grocery Access', 'groceryAccess', [['', 'Not set'], ['limited', 'Limited'], ['good', 'Good'], ['excellent', 'Excellent']]]].map(([lbl, key, opts]) => <div key={key}><label className={`text-xs font-medium ${c.label}`}>{lbl}</label><select value={userProfile[key]} onChange={e => setUserProfile(p => ({ ...p, [key]: e.target.value }))} className={`w-full mt-1 px-3 py-2 rounded-lg border text-sm ${c.input}`}>{opts.map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></div>)}
            <div><label className={`text-xs font-medium ${c.label}`}>Location</label><input value={userProfile.location} onChange={e => setUserProfile(p => ({ ...p, location: e.target.value }))} placeholder="City/region" className={`w-full mt-1 px-3 py-2 rounded-lg border text-sm ${c.input}`} /></div>
          </div>
        </div>
      )}

      {/* ─── Favorites Panel ─── */}
      {showFavorites && (
        <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-2`}>
          <h3 className={`font-bold ${c.text}`}>⭐ Favorites</h3>
          {favorites.length === 0 ? <p className={`text-sm ${c.textMuted}`}>Star swaps to build your reference.</p> : favorites.map((f, i) => <div key={i} className={`${c.cardAlt} rounded-lg p-2 flex items-center justify-between`}><div><span className={`text-sm font-bold ${c.text}`}>{f.name}</span><p className={`text-xs ${c.textMuted}`}>{f.constraint} · {f.score}%</p></div><button onClick={() => toggleFavorite(f)} className="text-xs text-red-400">🗑️</button></div>)}
        </div>
      )}

      {/* ─── Dictionary Panel ─── */}
      {showDictionary && (
        <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-3`}>
          <h3 className={`font-bold ${c.text}`}>📖 Ingredient Dictionary ({dictionary.length})</h3>
          <p className={`text-xs ${c.textMuted}`}>Auto-grows from Label Reader. Your personal cheat sheet for reading labels.</p>
          <input value={dictSearch} onChange={e => setDictSearch(e.target.value)} placeholder="Search ingredients..." className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} />
          {filteredDict.length === 0 ? <p className={`text-sm ${c.textMuted}`}>{dictionary.length === 0 ? 'Use the Label Reader to start building your dictionary.' : 'No matches.'}</p> : filteredDict.slice(0, 30).map((d, i) => (
            <div key={i} className={`${c.cardAlt} rounded-lg p-3 flex items-start justify-between`}>
              <div><span className={`text-sm font-bold ${c.text}`}>{d.ingredient}</span><p className={`text-xs ${c.textSecondary}`}>{d.meaning}</p>{d.constraint && <span className={`text-xs ${c.textMuted}`}>Constraint: {d.constraint}</span>}</div>
              <button onClick={() => setDictionary(p => p.filter((_, idx) => idx !== dictionary.indexOf(d)))} className={`text-xs ${c.textMuted}`}>✕</button>
            </div>
          ))}
        </div>
      )}

      {/* ─── Confidence Tracker Panel ─── */}
      {showConfidence && (
        <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-3`}>
          <h3 className={`font-bold ${c.text}`}>📊 Transition Confidence</h3>
          {confidenceLog.length > 0 && <p className={`text-xs ${c.accentText}`}>🗓️ Day {getTransitionDays()} of your transition · {confidenceLog.length} check-ins</p>}
          <div className="flex items-center gap-3">
            <span className={`text-xs ${c.label}`}>How's it going?</span>
            <input type="range" min="1" max="10" value={confidenceLevel} onChange={e => setConfidenceLevel(Number(e.target.value))} className="flex-1" />
            <span className={`text-lg font-bold ${confidenceLevel >= 7 ? (isDark ? 'text-green-300' : 'text-green-600') : confidenceLevel >= 4 ? (isDark ? 'text-amber-300' : 'text-amber-600') : (isDark ? 'text-red-300' : 'text-red-600')}`}>{confidenceLevel}/10</span>
          </div>
          <input value={confidenceNote} onChange={e => setConfidenceNote(e.target.value)} placeholder="Quick note (optional — 'Found a great cheese substitute!' or 'Struggling at restaurants')" className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} onKeyDown={e => e.key === 'Enter' && addConfidenceCheckin()} />
          <button onClick={addConfidenceCheckin} className={`px-4 py-2 rounded-lg text-xs font-bold ${c.btnPrimary}`}>📊 Log Check-in</button>
          {confidenceLog.length > 0 && (
            <div className="space-y-1 mt-2">
              <div className={`flex items-end gap-0.5 h-16`}>
                {confidenceLog.slice(0, 30).reverse().map((cl, i) => (
                  <div key={i} className={`flex-1 rounded-t ${cl.level >= 7 ? 'bg-green-500' : cl.level >= 4 ? 'bg-amber-500' : 'bg-red-400'}`} style={{ height: `${cl.level * 10}%` }} title={`${cl.level}/10 — ${cl.note || 'no note'}`} />
                ))}
              </div>
              <p className={`text-xs ${c.textMuted} text-center`}>← oldest · newest →</p>
              {confidenceLog.slice(0, 5).map((cl, i) => <p key={i} className={`text-xs ${c.textSecondary}`}>{new Date(cl.timestamp).toLocaleDateString()} — {cl.level}/10{cl.note ? `: ${cl.note}` : ''}</p>)}
            </div>
          )}
        </div>
      )}

      {/* ─── Constraint Picker ─── */}
      <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-3`}>
        <div className="flex items-center justify-between">
          <h3 className={`font-bold ${c.text}`}>🎯 Constraints</h3>
          {selectedConstraints.length > 0 && <span className={`text-xs ${c.accentText} font-medium`}>{selectedConstraints.length} selected</span>}
        </div>
        <div className="flex flex-wrap gap-2">
          {CONSTRAINTS.map(ct => <button key={ct.id} onClick={() => toggleConstraint(ct.id)} className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors border ${selectedConstraints.includes(ct.id) ? (isDark ? 'bg-orange-600 text-white border-orange-500' : 'bg-orange-600 text-white border-orange-600') : `${c.btnInactive} ${c.border}`}`}><span className="mr-1">{ct.icon}</span> {ct.label}</button>)}
        </div>
        <input value={customConstraint} onChange={e => setCustomConstraint(e.target.value)} placeholder="Additional (e.g., 'no nightshades')" className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} />
      </div>

      {/* ═══ INPUT FORMS ═══ */}

      {mode === 'swap' && <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-4`}><h3 className={`font-bold ${c.text}`}>🔄 What food do you love?</h3><textarea value={food} onChange={e => setFood(e.target.value)} placeholder="e.g., 'Mac and cheese — baked with crunchy breadcrumb top'" rows={3} className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} /><button onClick={handleSwap} disabled={loading} className={`w-full py-3 rounded-xl font-bold text-sm ${c.btnPrimary} disabled:opacity-50`}>{loading ? '⏳' : '🔄 Find My Swap'}</button></div>}

      {mode === 'restaurant' && <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-4`}><h3 className={`font-bold ${c.text}`}>🍽️ Eating Out Guide</h3><div className="flex flex-wrap gap-2">{CUISINES.map(cu => <button key={cu.id} onClick={() => setSelectedCuisine(cu.id)} className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors border ${selectedCuisine === cu.id ? (isDark ? 'bg-orange-600 text-white border-orange-500' : 'bg-orange-600 text-white border-orange-600') : `${c.btnInactive} ${c.border}`}`}><span className="mr-1">{cu.icon}</span> {cu.label}</button>)}</div>{selectedCuisine === 'other' && <input value={customCuisine} onChange={e => setCustomCuisine(e.target.value)} placeholder="Type cuisine" className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} />}<input value={specificRestaurant} onChange={e => setSpecificRestaurant(e.target.value)} placeholder="Specific restaurant? (optional)" className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} /><button onClick={handleRestaurant} disabled={loading} className={`w-full py-3 rounded-xl font-bold text-sm ${c.btnPrimary} disabled:opacity-50`}>{loading ? '⏳' : '🍽️ Get Guide'}</button></div>}

      {mode === 'pantry' && <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-4`}><h3 className={`font-bold ${c.text}`}>🛒 Pantry Transition</h3><textarea value={stapleMeals} onChange={e => setStapleMeals(e.target.value)} placeholder="Your staple meals and ingredients..." rows={4} className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} /><div className="flex gap-2"><button onClick={handlePantry} disabled={loading} className={`flex-1 py-3 rounded-xl font-bold text-sm ${c.btnPrimary} disabled:opacity-50`}>{loading ? '⏳' : '🛒 Build Plan'}</button><button onClick={() => toggleSection('fridge')} className={`px-4 py-3 rounded-xl text-sm font-bold ${c.btnSecondary}`}>🧊 Fridge Check</button><button onClick={() => toggleSection('expiry')} className={`px-4 py-3 rounded-xl text-sm font-bold ${c.btnSecondary}`}>⏰ Expiry Guide</button></div>{expandedSections.fridge && <div className={`${c.cardAlt} border ${c.border} rounded-lg p-4 space-y-3`}><h4 className={`font-bold text-sm ${c.text}`}>🧊 Quick Fridge Check</h4><textarea value={fridgeItems} onChange={e => setFridgeItems(e.target.value)} placeholder="What's in your fridge/pantry right now?" rows={2} className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} /><input value={fridgePlanned} onChange={e => setFridgePlanned(e.target.value)} placeholder="Planned meals (optional)" className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} /><button onClick={handleFridgeCheck} disabled={loading} className={`w-full py-2 rounded-lg text-sm font-bold ${c.btnPrimary} disabled:opacity-50`}>{loading ? '⏳' : '🧊 Check'}</button>{fridgeResults && <div className={`${fridgeResults.status?.includes('set') ? c.success : fridgeResults.status?.includes('Almost') ? c.warning : c.info} border rounded-lg p-3 space-y-1`}><div className="flex items-center gap-2"><span className="text-lg">{fridgeResults.status_emoji}</span><strong>{fridgeResults.status}</strong></div>{fridgeResults.can_make_now?.map((m, i) => <p key={i} className="text-sm">✅ {m.meal}</p>)}{fridgeResults.gaps?.map((g, i) => <p key={i} className="text-sm">🛒 Need: {g.item}{g.substitute ? ` (or sub: ${g.substitute})` : ''}</p>)}{fridgeResults.bonus_meal && <p className="text-sm">🎁 Bonus: {fridgeResults.bonus_meal}</p>}</div>}</div>}{expandedSections.expiry && <div className={`${c.cardAlt} border ${c.border} rounded-lg p-4 space-y-3`}><h4 className={`font-bold text-sm ${c.text}`}>⏰ Expiration Guide</h4><input value={expiryProducts} onChange={e => setExpiryProducts(e.target.value)} placeholder="Comma-separated: oat milk, GF bread, vegan cheese" className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} /><button onClick={handleExpiry} disabled={loading} className={`w-full py-2 rounded-lg text-sm font-bold ${c.btnPrimary} disabled:opacity-50`}>{loading ? '⏳' : '⏰ Get Guide'}</button>{expiryResults?.products?.map((p, i) => <div key={i} className={`${c.card} border ${c.border} rounded-lg p-3 space-y-1`}><h5 className={`font-bold text-sm ${c.text}`}>{p.name}</h5><p className={`text-xs ${c.textSecondary}`}>📦 Opened: {p.opened_shelf_life} · Sealed: {p.unopened_shelf_life}</p><p className={`text-xs ${c.textSecondary}`}>📍 {p.storage} · Freeze: {p.freezer_friendly}</p>{p.quirks?.map((q, j) => <p key={j} className={`text-xs ${c.textMuted}`}>⚡ {q}</p>)}{p.pro_tip && <p className={`text-xs ${c.accentText}`}>💡 {p.pro_tip}</p>}</div>)}</div>}</div>}

      {mode === 'craving' && <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-4`}><h3 className={`font-bold ${c.text}`}>🧠 Craving Decoder</h3><textarea value={cravingText} onChange={e => setCravingText(e.target.value)} placeholder="e.g., 'Something creamy, warm, cheesy...'" rows={3} className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} /><div className="grid grid-cols-2 gap-3"><div><label className={`text-xs ${c.label}`}>Mood</label><select value={mood} onChange={e => setMood(e.target.value)} className={`w-full mt-1 px-3 py-2 rounded-lg border text-sm ${c.input}`}>{['', 'stressed', 'tired', 'celebrating', 'bored', 'nostalgic', 'hangry', 'comfort'].map(v => <option key={v} value={v}>{v || 'Skip'}</option>)}</select></div><div><label className={`text-xs ${c.label}`}>Time</label><select value={timeOfDay} onChange={e => setTimeOfDay(e.target.value)} className={`w-full mt-1 px-3 py-2 rounded-lg border text-sm ${c.input}`}>{['', 'morning', 'afternoon', 'evening', 'late-night'].map(v => <option key={v} value={v}>{v || 'Skip'}</option>)}</select></div></div><button onClick={handleCraving} disabled={loading} className={`w-full py-3 rounded-xl font-bold text-sm ${c.btnPrimary} disabled:opacity-50`}>{loading ? '⏳' : '🧠 Decode'}</button></div>}

      {mode === 'batch' && <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-4`}><h3 className={`font-bold ${c.text}`}>📋 Batch Swap</h3>{batchMeals.map((meal, i) => <div key={i} className="flex items-center gap-2"><span className={`text-xs ${c.textMuted} w-6 text-center`}>{i + 1}.</span><input value={meal} onChange={e => { const u = [...batchMeals]; u[i] = e.target.value; setBatchMeals(u); }} placeholder={`Meal ${i + 1}`} className={`flex-1 px-3 py-2 rounded-lg border text-sm ${c.input}`} onKeyDown={e => { if (e.key === 'Enter' && i === batchMeals.length - 1 && meal.trim()) setBatchMeals(p => [...p, '']); }} />{batchMeals.length > 1 && <button onClick={() => setBatchMeals(p => p.filter((_, idx) => idx !== i))} className="text-xs">🗑️</button>}</div>)}<button onClick={() => setBatchMeals(p => [...p, ''])} className={`text-xs ${c.accentText}`}>➕ Add meal</button><button onClick={handleBatch} disabled={loading} className={`w-full py-3 rounded-xl font-bold text-sm ${c.btnPrimary} disabled:opacity-50`}>{loading ? '⏳' : `📋 Swap ${batchMeals.filter(m => m.trim()).length}`}</button></div>}

      {mode === 'mealplan' && <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-4`}><h3 className={`font-bold ${c.text}`}>📅 Meal Plan ({CURRENT_MONTH})</h3><div className="grid grid-cols-2 gap-3"><div><label className={`text-xs ${c.label}`}>Days</label><select value={mealPlanDays} onChange={e => setMealPlanDays(Number(e.target.value))} className={`w-full mt-1 px-3 py-2 rounded-lg border text-sm ${c.input}`}>{[3, 5, 7].map(d => <option key={d} value={d}>{d} days</option>)}</select></div><div><label className={`text-xs ${c.label}`}>Preferences</label><input value={mealPlanPrefs} onChange={e => setMealPlanPrefs(e.target.value)} placeholder="e.g., 'love Mexican, hate tofu'" className={`w-full mt-1 px-3 py-2 rounded-lg border text-sm ${c.input}`} /></div></div><button onClick={handleMealPlan} disabled={loading} className={`w-full py-3 rounded-xl font-bold text-sm ${c.btnPrimary} disabled:opacity-50`}>{loading ? '⏳' : `📅 Generate ${mealPlanDays}-Day Plan`}</button></div>}

      {mode === 'label' && <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-4`}><h3 className={`font-bold ${c.text}`}>🏷️ Label Reader</h3><p className={`text-xs ${c.textMuted}`}>Flagged ingredients auto-save to your Dictionary 📖</p><input value={productName} onChange={e => setProductName(e.target.value)} placeholder="Product name" className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} /><textarea value={ingredientList} onChange={e => setIngredientList(e.target.value)} placeholder="Paste ingredient list (optional)" rows={3} className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} /><button onClick={handleLabel} disabled={loading} className={`w-full py-3 rounded-xl font-bold text-sm ${c.btnPrimary} disabled:opacity-50`}>{loading ? '⏳' : '🏷️ Check Product'}</button></div>}

      {mode === 'social' && <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-4`}><h3 className={`font-bold ${c.text}`}>🗣️ Social Situations</h3><div className="flex gap-2"><button onClick={() => setSocialSubMode('event')} className={`px-3 py-1.5 rounded-lg text-xs font-medium ${socialSubMode === 'event' ? c.btnActive : c.btnInactive}`}>🎉 Event</button><button onClick={() => setSocialSubMode('host')} className={`px-3 py-1.5 rounded-lg text-xs font-medium ${socialSubMode === 'host' ? c.btnActive : c.btnInactive}`}>🏡 Someone's Cooking</button></div>{socialSubMode === 'event' ? <><textarea value={socialSituation} onChange={e => setSocialSituation(e.target.value)} placeholder="Describe the social eating situation..." rows={3} className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} /><input value={socialRelationship} onChange={e => setSocialRelationship(e.target.value)} placeholder="Relationship context (optional)" className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} /><button onClick={handleSocial} disabled={loading} className={`w-full py-3 rounded-xl font-bold text-sm ${c.btnPrimary} disabled:opacity-50`}>{loading ? '⏳' : '🗣️ Get Script'}</button></> : <><textarea value={hostContext} onChange={e => setHostContext(e.target.value)} placeholder="e.g., 'Friend invited me for dinner, she loves cooking Italian'" rows={3} className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} /><input value={socialRelationship} onChange={e => setSocialRelationship(e.target.value)} placeholder="Relationship" className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} /><input value={plannedMenu} onChange={e => setPlannedMenu(e.target.value)} placeholder="Know what they're planning? (optional)" className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} /><button onClick={handleHost} disabled={loading} className={`w-full py-3 rounded-xl font-bold text-sm ${c.btnPrimary} disabled:opacity-50`}>{loading ? '⏳' : '🏡 Get Dinner Guide'}</button></>}</div>}

      {/* ═══ v3: TRAVEL ═══ */}
      {mode === 'travel' && <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-4`}><h3 className={`font-bold ${c.text}`}>✈️ Travel Eating Guide</h3><p className={`text-sm ${c.textMuted}`}>Language cards, safe brands, labeling laws, and survival strategies for eating abroad.</p><input value={travelDest} onChange={e => setTravelDest(e.target.value)} placeholder="Destination (e.g., 'Tokyo, Japan' or 'Italy')" className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} /><input value={tripLength} onChange={e => setTripLength(e.target.value)} placeholder="Trip length (optional — e.g., '10 days')" className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} onKeyDown={e => e.key === 'Enter' && handleTravel()} /><button onClick={handleTravel} disabled={loading} className={`w-full py-3 rounded-xl font-bold text-sm ${c.btnPrimary} disabled:opacity-50`}>{loading ? '⏳' : '✈️ Generate Travel Guide'}</button></div>}

      {/* ═══ v3: PARTY PLANNER ═══ */}
      {mode === 'party' && <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-4`}><h3 className={`font-bold ${c.text}`}>🎉 Party Planner</h3><p className={`text-sm ${c.textMuted}`}>Hosting guests with different dietary needs? Build a menu that works for everyone.</p>{partyGuests.map((g, i) => <div key={i} className="flex items-center gap-2"><input value={g.name} onChange={e => { const u = [...partyGuests]; u[i] = { ...u[i], name: e.target.value }; setPartyGuests(u); }} placeholder={`Guest ${i + 1} name`} className={`w-1/3 px-3 py-2 rounded-lg border text-sm ${c.input}`} /><input value={g.constraints} onChange={e => { const u = [...partyGuests]; u[i] = { ...u[i], constraints: e.target.value }; setPartyGuests(u); }} placeholder="Their constraints (e.g., 'vegan, nut-free')" className={`flex-1 px-3 py-2 rounded-lg border text-sm ${c.input}`} />{partyGuests.length > 1 && <button onClick={() => setPartyGuests(p => p.filter((_, idx) => idx !== i))} className="text-xs">🗑️</button>}</div>)}<button onClick={() => setPartyGuests(p => [...p, { name: '', constraints: '' }])} className={`text-xs ${c.accentText}`}>➕ Add guest</button><input value={partyOccasion} onChange={e => setPartyOccasion(e.target.value)} placeholder="Occasion (optional — birthday, Thanksgiving, dinner party)" className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} /><input value={partyCuisine} onChange={e => setPartyCuisine(e.target.value)} placeholder="Cuisine preference (optional)" className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} /><button onClick={handleParty} disabled={loading} className={`w-full py-3 rounded-xl font-bold text-sm ${c.btnPrimary} disabled:opacity-50`}>{loading ? '⏳' : `🎉 Plan Menu for ${partyGuests.filter(g => g.constraints.trim()).length} Guests`}</button></div>}

      {/* ═══ v3: JOURNAL ═══ */}
      {mode === 'journal' && <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-4`}><h3 className={`font-bold ${c.text}`}>📓 Swap Journal</h3><p className={`text-sm ${c.textMuted}`}>Log what you tried, rate 1-10, add notes. After 5+ entries, unlock your Swap Style Profile.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><input value={journalSwapName} onChange={e => setJournalSwapName(e.target.value)} placeholder="What swap did you try?" className={`px-3 py-2 rounded-lg border text-sm ${c.input}`} /><input value={journalOriginal} onChange={e => setJournalOriginal(e.target.value)} placeholder="Original food it replaced?" className={`px-3 py-2 rounded-lg border text-sm ${c.input}`} /></div><div className="flex items-center gap-3"><span className={`text-xs ${c.label}`}>Rating:</span><input type="range" min="1" max="10" value={journalRating} onChange={e => setJournalRating(Number(e.target.value))} className="flex-1" /><span className={`text-lg font-bold ${journalRating >= 7 ? (isDark ? 'text-green-300' : 'text-green-600') : journalRating >= 4 ? (isDark ? 'text-amber-300' : 'text-amber-600') : (isDark ? 'text-red-300' : 'text-red-600')}`}>{journalRating}/10</span></div><textarea value={journalNotes} onChange={e => setJournalNotes(e.target.value)} placeholder="Notes (e.g., 'Needed more salt, texture was great, would try the Miyoko brand next time')" rows={2} className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} /><div className="flex gap-2"><button onClick={addJournalEntry} disabled={!journalSwapName.trim()} className={`flex-1 py-3 rounded-xl font-bold text-sm ${c.btnPrimary} disabled:opacity-50`}>📓 Log Entry</button>{journal.length >= 5 && <button onClick={handleSwapStyle} disabled={styleLoading} className={`px-4 py-3 rounded-xl text-sm font-bold ${c.purpleBg} border`}>{styleLoading ? '⏳' : '🎨 My Swap Style'}</button>}</div>
        {/* Style Results */}
        {styleResults && <div className={`${c.purpleBg} border rounded-xl p-5 space-y-3`}><div className="flex items-center gap-2"><span className="text-2xl">{styleResults.swap_style?.emoji}</span><div><h4 className="font-bold text-lg">{styleResults.swap_style?.title}</h4><p className="text-sm">{styleResults.swap_style?.description}</p></div></div>{styleResults.insights?.map((ins, i) => <p key={i} className="text-sm">💡 {ins}</p>)}{styleResults.lean_into?.length > 0 && <div><span className="text-xs font-bold">✅ Lean into:</span> {styleResults.lean_into.join(', ')}</div>}{styleResults.avoid_for_you?.length > 0 && <div><span className="text-xs font-bold">❌ Avoid:</span> {styleResults.avoid_for_you.join(', ')}</div>}{styleResults.next_to_try?.map((n, i) => <div key={i} className={`${c.card} border ${c.border} rounded-lg p-3`}><p className="text-sm font-bold">{n.suggestion}</p><p className="text-xs">{n.why}</p></div>)}{styleResults.milestone && <div className={`${c.success} border rounded-lg p-3`}><p className="text-sm">{styleResults.milestone.message}</p><p className="text-xs">Best swap: {styleResults.milestone.best_swap} · Avg: {styleResults.milestone.average_rating}/10</p></div>}</div>}
        {/* Journal Entries */}
        {journal.length > 0 && <div className="space-y-2"><h4 className={`font-bold text-sm ${c.text}`}>Recent Entries ({journal.length})</h4>{journal.slice(0, 15).map((e, i) => <div key={i} className={`${c.cardAlt} rounded-lg p-3 flex items-center justify-between`}><div><span className={`text-sm font-bold ${c.text}`}>{e.swapName}</span>{e.originalFood && <span className={`text-xs ${c.textMuted}`}> for {e.originalFood}</span>}{e.notes && <p className={`text-xs ${c.textSecondary}`}>{e.notes}</p>}</div><div className="text-right"><span className={`text-sm font-bold ${e.rating >= 7 ? (isDark ? 'text-green-300' : 'text-green-600') : e.rating >= 4 ? (isDark ? 'text-amber-300' : 'text-amber-600') : (isDark ? 'text-red-300' : 'text-red-600')}`}>{e.rating}/10</span><p className={`text-xs ${c.textMuted}`}>{new Date(e.timestamp).toLocaleDateString()}</p></div></div>)}</div>}
      </div>}

      {/* ─── Error ─── */}
      {error && <div className={`${c.danger} border rounded-xl p-4 text-sm`}>⚠️ {error}</div>}

      {/* ═══════════════════════════════════════════════════ */}
      {/* RESULTS (all modes — preserved from v2)            */}
      {/* ═══════════════════════════════════════════════════ */}

      {/* Swap Results */}
      {mode === 'swap' && results && <div className="space-y-4">{results.craving_analysis && <div className={`${c.accentBg} border rounded-xl p-5 space-y-2`}><h3 className={`font-bold ${c.accentText}`}>🧠 What You Actually Crave</h3><p className={`text-sm ${c.text}`}>{results.craving_analysis.what_you_actually_crave}</p>{results.craving_analysis.key_elements?.length > 0 && <div className="flex flex-wrap gap-1.5">{results.craving_analysis.key_elements.map((el, i) => <span key={i} className={`text-xs px-2 py-1 rounded-full ${isDark ? 'bg-orange-900/40 text-orange-200' : 'bg-orange-100 text-orange-700'}`}>{el}</span>)}</div>}{results.craving_analysis.constraint_challenge && <p className={`text-xs ${c.textMuted}`}>🎯 {results.craving_analysis.constraint_challenge}</p>}</div>}{results.swaps?.map((s, i) => <SwapCard key={`${s.name}-${i}`} swap={s} index={i} originalFood={food} />)}{results.avoid_these?.length > 0 && <div className={`${c.danger} border rounded-xl p-5 space-y-2`}><h3 className="font-bold">🚫 Skip These</h3>{results.avoid_these.map((a, i) => <div key={i} className="text-sm"><strong>{a.swap}</strong> — {a.why_it_fails}</div>)}</div>}{results.surprise_option && <div className={`${c.info} border rounded-xl p-5 space-y-2`}><h3 className="font-bold">✨ Surprise</h3><p className="text-sm font-medium">{results.surprise_option.name}</p><p className="text-sm">{results.surprise_option.why_it_works}</p><ScoreBar score={results.surprise_option.closeness_score} label="Match" /></div>}{results.stacking_tip && <div className={`${c.success} border rounded-xl p-4 text-sm`}>🧩 <strong>Stack:</strong> {results.stacking_tip}</div>}<ActionBar content={buildSwapText()} title={`FoodSwap: ${food}`} /></div>}

      {/* Restaurant Results */}
      {mode === 'restaurant' && restaurantResults && <div className="space-y-4">{restaurantResults.cuisine_overview && <div className={`${c.accentBg} border rounded-xl p-5 space-y-2`}><h3 className={`font-bold ${c.accentText}`}>🍽️ {getCuisineText()}</h3><div className={`inline-block text-sm font-bold px-3 py-1 rounded-full ${restaurantResults.cuisine_overview.how_friendly?.includes('Very') ? c.success : restaurantResults.cuisine_overview.how_friendly?.includes('Minefield') ? c.danger : c.warning}`}>{restaurantResults.cuisine_overview.how_friendly}</div><p className={`text-sm ${c.text}`}>✅ {restaurantResults.cuisine_overview.good_news}</p></div>}{restaurantResults.safe_bets?.map((s, i) => <div key={i} className={`${c.card} border ${c.border} rounded-xl p-4`}><h4 className={`font-bold text-sm ${c.text}`}>{s.dish}</h4><p className={`text-xs ${c.textSecondary}`}>{s.why_safe}</p><p className={`text-xs ${c.accentText}`}>📝 {s.how_to_order}</p></div>)}{restaurantResults.server_script && <div className={`${c.card} border ${c.border} rounded-xl p-5`}><h3 className={`font-bold ${c.text}`}>🗣️ Server Script</h3><p className={`text-sm ${c.textSecondary} italic`}>"{restaurantResults.server_script}"</p><CopyBtn content={restaurantResults.server_script + BRAND} label="Copy" /></div>}</div>}

      {/* Pantry Results */}
      {mode === 'pantry' && pantryResults && <div className="space-y-4"><div className={`${c.accentBg} border rounded-xl p-5`}><h3 className={`font-bold ${c.accentText}`}>🛒 Pantry Transition</h3><div className={`inline-block text-sm font-bold px-3 py-1 rounded-full ${pantryResults.transition_difficulty?.includes('Easy') ? c.success : pantryResults.transition_difficulty?.includes('Major') ? c.danger : c.warning}`}>{pantryResults.transition_difficulty}</div><p className={`text-sm ${c.text} mt-1`}>✅ {pantryResults.good_news_first}</p></div>{pantryResults.pantry_swaps?.map((s, i) => <div key={i} className={`${c.cardAlt} rounded-lg p-3 flex items-center gap-3`}><div className="flex-1"><span className={`text-sm ${c.textMuted} line-through`}>{s.current}</span> → <span className={`text-sm font-bold ${c.text}`}>{s.replacement}</span></div><span className={`text-xs px-2 py-0.5 rounded-full ${s.taste_match === 'Identical' || s.taste_match === 'Very close' ? c.success : c.warning}`}>{s.taste_match}</span></div>)}{pantryResults.shopping_list && <div className={`${c.card} border ${c.border} rounded-xl p-5`}><h3 className={`font-bold ${c.text}`}>📝 Shopping List</h3>{pantryResults.shopping_list.essentials?.map((item, i) => <p key={i} className={`text-sm ${c.textSecondary}`}>☐ {item}</p>)}<CopyBtn content={`Shopping List\n\n${pantryResults.shopping_list.essentials?.map(i => `☐ ${i}`).join('\n')}${BRAND}`} label="Copy List" /></div>}<ActionBar content={buildSwapText()} title="FoodSwap Pantry" /></div>}

      {/* Craving Results */}
      {mode === 'craving' && cravingResults && <div className="space-y-4">{cravingResults.decoded_craving && <div className={`${c.accentBg} border rounded-xl p-5 space-y-2`}><h3 className={`font-bold ${c.accentText}`}>🧠 Decoded</h3>{cravingResults.decoded_craving.sensory_profile && <div className="flex flex-wrap gap-2">{Object.entries(cravingResults.decoded_craving.sensory_profile).map(([k, v]) => <span key={k} className={`text-xs px-2 py-1 rounded-full ${isDark ? 'bg-orange-900/40 text-orange-200' : 'bg-orange-100 text-orange-700'}`}>{k}: {v}</span>)}</div>}{cravingResults.decoded_craving.emotional_layer && <p className={`text-sm ${c.textSecondary}`}>💭 {cravingResults.decoded_craving.emotional_layer}</p>}</div>}{cravingResults.sideways_solutions?.map((sol, i) => <div key={i} className={`${c.card} border ${c.border} rounded-xl p-4`}><h4 className={`font-bold text-sm ${c.text}`}>{sol.suggestion}</h4><p className={`text-sm ${c.textSecondary}`}>{sol.why_it_works}</p><p className={`text-xs ${c.textMuted}`}>⏱️ {sol.effort}</p></div>)}{cravingResults.quick_fix && <div className={`${c.success} border rounded-xl p-4 text-sm`}>⚡ <strong>Quick fix:</strong> {cravingResults.quick_fix.item} ({cravingResults.quick_fix.honest_rating}/10)</div>}</div>}

      {/* Batch Results */}
      {mode === 'batch' && batchResults && <div className="space-y-4">{batchResults.swaps?.map((s, i) => <div key={i} className={`${c.card} border ${c.border} rounded-xl p-4 space-y-2`}><span className={`text-sm ${c.textMuted} line-through`}>{s.original}</span> → <span className={`text-sm font-bold ${c.text}`}>{s.best_swap}</span><ScoreBar score={s.closeness} label="Match" />{s.brand_tip && <p className={`text-xs ${c.accentText}`}>🏪 {s.brand_tip}</p>}</div>)}{batchResults.overall_assessment && <div className={`${c.success} border rounded-xl p-4 text-sm`}>{batchResults.overall_assessment.weekly_prep_tip && <p>💡 {batchResults.overall_assessment.weekly_prep_tip}</p>}</div>}</div>}

      {/* Meal Plan Results */}
      {mode === 'mealplan' && mealPlanResults && <div className="space-y-4">{mealPlanResults.plan_overview && <div className={`${c.accentBg} border rounded-xl p-5`}><h3 className={`font-bold ${c.accentText}`}>📅 {mealPlanResults.days?.length}-Day Plan</h3><p className={`text-sm ${c.textSecondary}`}>💰 {mealPlanResults.plan_overview.estimated_weekly_grocery_cost} · 🧑‍🍳 {mealPlanResults.plan_overview.prep_strategy}</p></div>}{mealPlanResults.days?.map(day => <div key={day.day} className={`${c.card} border ${c.border} rounded-xl p-4`}><button onClick={() => toggleSection(`day-${day.day}`)} className="flex items-center justify-between w-full"><h4 className={`font-bold ${c.text}`}>Day {day.day}</h4><span>{expandedSections[`day-${day.day}`] ? '▲' : '▼'}</span></button>{(expandedSections[`day-${day.day}`] || day.day <= 2) && <div className="space-y-2 mt-2">{['breakfast', 'lunch', 'dinner', 'snack'].map(slot => day[slot] && <div key={slot} className={`${c.cardAlt} rounded-lg p-3`}><span className={`text-xs font-bold uppercase ${c.textMuted}`}>{slot}</span><p className={`text-sm font-medium ${c.text}`}>{day[slot].meal}</p></div>)}</div>}</div>)}{mealPlanResults.grocery_list?.length > 0 && <div className={`${c.card} border ${c.border} rounded-xl p-5`}><h3 className={`font-bold ${c.text}`}>📝 Grocery List</h3>{mealPlanResults.grocery_list.map((i, idx) => <p key={idx} className={`text-sm ${c.textSecondary}`}>☐ {i}</p>)}<CopyBtn content={`Grocery List\n\n${mealPlanResults.grocery_list.map(i => `☐ ${i}`).join('\n')}${BRAND}`} label="Copy List" /></div>}</div>}

      {/* Label Results */}
      {mode === 'label' && labelResults && <div className="space-y-4"><div className={`${labelResults.verdict === 'Safe' ? c.success : labelResults.verdict === 'Avoid' ? c.danger : c.warning} border rounded-xl p-5`}><div className="flex items-center gap-2"><span className="text-2xl">{labelResults.verdict_emoji}</span><h3 className="font-bold text-lg">{labelResults.verdict}</h3></div><p className="text-sm">{labelResults.explanation}</p></div>{labelResults.flagged_ingredients?.map((f, i) => <div key={i} className={`${c.cardAlt} rounded-lg p-3`}><strong className={`text-sm ${c.text}`}>{f.ingredient}</strong> — <span className={`text-xs ${c.textSecondary}`}>{f.why_flagged}</span>{f.which_constraint && <span className={`text-xs ${c.textMuted}`}> (violates: {f.which_constraint})</span>}</div>)}{labelResults.safe_alternative && <div className={`${c.success} border rounded-xl p-4 text-sm`}>✅ Try: {labelResults.safe_alternative.brand} — {labelResults.safe_alternative.product}</div>}{labelResults.hidden_names?.length > 0 && <div className={`${c.info} border rounded-xl p-4 text-sm`}>🕵️ Hidden names: {labelResults.hidden_names.join(', ')}</div>}{dictionary.length > 0 && <p className={`text-xs ${c.accentText}`}>📖 {labelResults.flagged_ingredients?.length || 0} ingredients saved to your Dictionary</p>}</div>}

      {/* Social Results */}
      {mode === 'social' && socialSubMode === 'event' && socialResults && <div className="space-y-4">{socialResults.before_scripts?.map((s, i) => <div key={i} className={`${c.card} border ${c.border} rounded-xl p-4`}><p className={`text-xs ${c.textMuted}`}>{s.timing} · {s.tone}</p><p className={`text-sm ${c.textSecondary} italic`}>"{s.script}"</p><CopyBtn content={s.script + BRAND} label="Copy" /></div>)}{socialResults.if_they_push_back && <div className={`${c.warning} border rounded-xl p-4`}><strong className="text-sm">🛡️ If they push back:</strong><p className="text-sm mt-1">"{socialResults.if_they_push_back.response}"</p></div>}</div>}

      {/* Host Results */}
      {mode === 'social' && socialSubMode === 'host' && hostResults && <div className="space-y-4">{hostResults.message_to_host && <div className={`${c.card} border ${c.border} rounded-xl p-5`}><h3 className={`font-bold ${c.text}`}>💬 Message to Host</h3><p className={`text-sm ${c.textSecondary} italic`}>"{hostResults.message_to_host.script}"</p><CopyBtn content={hostResults.message_to_host.script + BRAND} label="Copy Message" /></div>}{hostResults.dishes_to_suggest?.map((d, i) => <div key={i} className={`${c.cardAlt} rounded-lg p-3`}><p className={`text-sm font-bold ${c.text}`}>{d.dish}</p><p className={`text-xs ${c.textSecondary}`}>{d.why_suggest}</p></div>)}{hostResults.bring_this && <div className={`${c.success} border rounded-xl p-4`}><strong className="text-sm">🍱 Bring:</strong> {hostResults.bring_this.dish}<p className="text-xs italic mt-1">Say: "{hostResults.bring_this.how_to_frame_it}"</p></div>}</div>}

      {/* Travel Results */}
      {mode === 'travel' && travelResults && <div className="space-y-4">{travelResults.destination_overview && <div className={`${c.accentBg} border rounded-xl p-5 space-y-2`}><h3 className={`font-bold ${c.accentText}`}>✈️ {travelDest}</h3><div className={`inline-block text-sm font-bold px-3 py-1 rounded-full ${travelResults.destination_overview.difficulty?.includes('Easy') ? c.success : travelResults.destination_overview.difficulty?.includes('Survival') ? c.danger : c.warning}`}>{travelResults.destination_overview.difficulty}</div><p className={`text-sm ${c.text}`}>🌍 {travelResults.destination_overview.cultural_attitude}</p><p className={`text-sm ${c.textSecondary}`}>✅ {travelResults.destination_overview.good_news}</p></div>}{travelResults.language_card && <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-2`}><h3 className={`font-bold ${c.text}`}>🗣️ Language Card</h3><div className={`${isDark ? 'bg-blue-900/20 border-blue-700' : 'bg-blue-50 border-blue-200'} border rounded-lg p-4`}><p className={`text-sm font-medium ${c.text}`}>{travelResults.language_card.allergy_statement}</p></div><p className={`text-xs ${c.textSecondary}`}>Say: {travelResults.language_card.phrase}</p><CopyBtn content={`${travelResults.language_card.allergy_statement}\n\n${travelResults.language_card.phrase}${BRAND}`} label="Copy Card" />{travelResults.language_card.key_words?.map((w, i) => <p key={i} className={`text-xs ${c.textSecondary}`}>{w.local} ({w.pronunciation}) = {w.english}</p>)}</div>}{travelResults.safe_shopping && <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-2`}><h3 className={`font-bold ${c.text}`}>🛒 Safe Shopping</h3><h4 className={`text-xs font-bold ${c.label}`}>Convenience stores:</h4>{travelResults.safe_shopping.convenience_stores?.map((s, i) => <p key={i} className={`text-sm ${c.textSecondary}`}>• {s}</p>)}<h4 className={`text-xs font-bold ${c.label} mt-2`}>Grocery staples:</h4>{travelResults.safe_shopping.grocery_staples?.map((s, i) => <p key={i} className={`text-sm ${c.textSecondary}`}>• {s}</p>)}</div>}{travelResults.pack_these?.length > 0 && <div className={`${c.warning} border rounded-xl p-4`}><strong className="text-sm">🎒 Pack from home:</strong>{travelResults.pack_these.map((p, i) => <p key={i} className="text-sm">• {p}</p>)}</div>}{travelResults.emergency_plan && <div className={`${c.danger} border rounded-xl p-4 text-sm`}>🚨 <strong>Emergency:</strong> {travelResults.emergency_plan}</div>}<ActionBar content={`✈️ FoodSwap Travel: ${travelDest} + ${getConstraintLabels().join(' + ')}\n\nLanguage Card: ${travelResults.language_card?.allergy_statement || ''}\n\nSafe Shopping:\n${travelResults.safe_shopping?.convenience_stores?.map(s => `• ${s}`).join('\n') || ''}${BRAND}`} title={`Travel Guide: ${travelDest}`} /></div>}

      {/* Party Results */}
      {mode === 'party' && partyResults && <div className="space-y-4">{partyResults.strategy && <div className={`${c.accentBg} border rounded-xl p-5`}><h3 className={`font-bold ${c.accentText}`}>🎉 Party Strategy</h3><p className={`text-sm ${c.text}`}>{partyResults.strategy}</p></div>}{partyResults.universal_dishes?.length > 0 && <div className={`${c.success} border rounded-xl p-5 space-y-2`}><h3 className="font-bold">✅ Works for Everyone</h3>{partyResults.universal_dishes.map((d, i) => <div key={i}><p className="text-sm font-bold">{d.dish}</p><p className="text-xs">{d.crowd_appeal}</p></div>)}</div>}{partyResults.menu && <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-3`}><h3 className={`font-bold ${c.text}`}>📋 Full Menu</h3>{['appetizers', 'mains', 'sides', 'dessert'].map(cat => partyResults.menu[cat]?.length > 0 && <div key={cat}><h4 className={`text-xs font-bold uppercase ${c.accentText}`}>{cat}</h4>{partyResults.menu[cat].map((d, i) => <p key={i} className={`text-sm ${c.textSecondary}`}>• {d}</p>)}</div>)}</div>}{partyResults.shopping_list?.length > 0 && <div className={`${c.card} border ${c.border} rounded-xl p-5`}><h3 className={`font-bold ${c.text}`}>🛒 Shopping List</h3>{partyResults.shopping_list.map((i, idx) => <p key={idx} className={`text-sm ${c.textSecondary}`}>☐ {i}</p>)}<CopyBtn content={`Party Shopping List\n\n${partyResults.shopping_list.map(i => `☐ ${i}`).join('\n')}${BRAND}`} label="Copy List" /></div>}{partyResults.hosting_tips?.length > 0 && <div className={`${c.info} border rounded-xl p-4`}><strong className="text-sm">💡 Hosting Tips</strong>{partyResults.hosting_tips.map((t, i) => <p key={i} className="text-sm mt-1">• {t}</p>)}</div>}</div>}

      {/* Cross-References */}
      {(results || restaurantResults || pantryResults || mealPlanResults || travelResults || partyResults) && <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}><p className={`text-xs ${c.textMuted} mb-2`}>Related tools:</p><div className="flex flex-wrap gap-2">{[['FridgeAlchemy', '🧪', 'cook with what you have'], ['RecipeChaosSolver', '📖', 'fix confusing recipes'], ['BuyWise', '🛒', 'smart grocery decisions'], ['MoneyDiplomat', '💵', 'budget dining out']].map(([id, ico, desc]) => <a key={id} href={`/${id}`} target="_blank" rel="noopener noreferrer" className={`text-xs px-3 py-1.5 rounded-lg ${c.btnSecondary} no-underline`}>{ico} {desc}</a>)}</div></div>}

      {/* History */}
      {history.length > 0 && <div className={`${c.card} border ${c.border} rounded-xl p-5`}><button onClick={() => toggleSection('history')} className="flex items-center justify-between w-full"><h3 className={`font-bold ${c.text}`}>📜 Recent ({history.length})</h3><span>{expandedSections.history ? '▲' : '▼'}</span></button>{expandedSections.history && <div className="mt-3 space-y-1">{history.slice(0, 20).map((h, i) => <div key={i} className={`${c.cardAlt} rounded-lg p-2 flex items-center justify-between`}><span className={`text-sm ${c.textSecondary}`}>{MODES.find(m => m.id === h.type)?.icon || '🔄'} {h.input}</span><span className={`text-xs ${c.textMuted}`}>{new Date(h.timestamp).toLocaleDateString()}</span></div>)}<button onClick={() => setHistory([])} className={`text-xs ${c.textMuted}`}>🗑️ Clear</button></div>}</div>}
    </div>
  );
};

FoodSwap.displayName = 'FoodSwap';
export default FoodSwap;
