import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useScrollToSection } from '../hooks/useScrollToSection';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';
import { pickExample } from '../utils/exampleRotation';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

// Stable internal value first, translated label key second. The value is what
// the backend sees; the label is what the visitor reads. Never send the label.
const RELATIONSHIPS = [
  ['close_friend', 'ffa_rel_close_friend'],
  ['friend', 'ffa_rel_friend'],
  ['family', 'ffa_rel_family'],
  ['former_coworker', 'ffa_rel_former_coworker'],
  ['mentor', 'ffa_rel_mentor'],
  ['other', 'ffa_rel_other'],
];

const RHYTHMS = [
  ['weekly', 'ffa_rhythm_weekly', 7],
  ['biweekly', 'ffa_rhythm_biweekly', 18],
  ['monthly', 'ffa_rhythm_monthly', 30],
  ['quarterly', 'ffa_rhythm_quarterly', 90],
  ['semiannually', 'ffa_rhythm_semiannual', 180],
];

const LAST_CONTACT_CHOICES = [
  ['today', 'ffa_last_today', 0],
  ['this_week', 'ffa_last_week', 4],
  ['few_weeks', 'ffa_last_few_weeks', 18],
  ['month_plus', 'ffa_last_month_plus', 45],
  ['not_sure', 'ffa_last_not_sure', 30],
];

const SNOOZE_CHOICES = [[7, 'ffa_1_week'], [14, 'ffa_2_weeks'], [30, 'ffa_1_month'], [60, 'ffa_2_months']];

// What happened, and whether it counts as actually catching up. An email
// arriving is worth remembering and worth talking about; it is not the two of
// them having spoken, so it must not reset the rhythm. `meaningful` is the only
// thing that moves lastContact.
// Three different social problems, not three tones of the same message.
const APPROACHES = [
  ['pickUpThread', 'ffa_pick_up_thread'],
  ['simpleHello', 'ffa_just_say_hello'],
  ['makeAPlan', 'ffa_make_a_plan'],
];

const CONNECTION_KINDS = [
  ['caught_up', 'ffa_kind_caught_up', true],
  ['messages', 'ffa_kind_messages', true],
  ['they_reached_out', 'ffa_kind_they_reached', false],
  ['other', 'ffa_kind_other', false],
];

const isoDaysAgo = (days) => {
  const d = new Date();
  d.setHours(12, 0, 0, 0);
  d.setDate(d.getDate() - days);
  return d.toISOString().split('T')[0];
};

const daysSince = (dateStr) => {
  if (!dateStr) return 0;
  const a = new Date(`${dateStr}T12:00:00`);
  const b = new Date();
  b.setHours(12, 0, 0, 0);
  return Math.max(0, Math.round((b - a) / 86400000));
};

const rhythmDays = (value) => RHYTHMS.find(([v]) => v === value)?.[2] || 30;
const rhythmKey = (value) => RHYTHMS.find(([v]) => v === value)?.[1] || 'ffa_rhythm_comfortable';
const relationKey = (value) => RELATIONSHIPS.find(([v]) => v === value)?.[1] || 'ffa_rel_friend';

const blankPerson = () => ({
  id: null,
  name: '',
  relationshipType: 'friend',
  rhythm: 'monthly',
  lastContact: isoDaysAgo(0),
  contextNotes: '',
  snoozedUntil: null,
  contactLog: [],
});

// The previous version stored `frequency` and carried two fields this design
// has no screen for. Reshaping on read rather than writing a new key means
// nobody who already added people opens the tool to an empty list.
const migratePerson = (p) => ({
  ...blankPerson(),
  ...p,
  id: p.id ?? `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
  rhythm: p.rhythm || p.frequency || 'monthly',
  relationshipType: p.relationshipType === 'colleague' ? 'former_coworker' : (p.relationshipType || 'friend'),
  // Entries logged before the kinds existed were all made by pressing a button
  // that meant "we connected", so they are read as catching up. Guessing the
  // other way would tell people they are overdue for connections they made.
  contactLog: (p.contactLog || []).map(l => ({
    type: 'caught_up',
    meaningfulConnection: true,
    ...l,
  })),
});

// `lastContact` only ever advances on a meaningful connection, so it is the
// anchor for the rhythm. Contact of any kind lives in the log.
const lastMeaningful = (p) => p.lastContact;

const FriendshipFadeAlerter = ({ tool }) => {
  const { callToolEndpoint, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t, i18n } = useTranslation();
  const locale = userLocale || (typeof navigator !== 'undefined' ? navigator.language : 'en');
  const apiLocale = { locale: typeof navigator !== 'undefined' ? navigator.language : 'en', userLocale, userCurrency, userRegion };

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20'
                          : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-400' : 'text-gray-500',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white'
                          : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200'
                          : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200'
                          : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200'
                          : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200'
                          : 'bg-red-50 border-red-200 text-red-800',
    pillActive:    isDark ? 'border-cyan-500 bg-cyan-900/30 text-cyan-200'
                          : 'border-cyan-600 bg-cyan-100 text-cyan-900',
    pillInactive:  isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500'
                          : 'border-gray-300 text-gray-500 hover:border-gray-400',
    required:      isDark ? 'text-amber-400' : 'text-amber-700',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';

  const [view, setView] = useState('');
  const [form, setForm] = useState(blankPerson());
  const [lastContactChoice, setLastContactChoice] = useState('today');
  const [customLastContact, setCustomLastContact] = useState('');
  const [rhythmHelpLoading, setRhythmHelpLoading] = useState(false);
  const [rhythmSuggestion, setRhythmSuggestion] = useState(null);
  const [selectedId, setSelectedId] = useState(null);
  const [reachout, setReachout] = useState(null);
  const [reachoutLoading, setReachoutLoading] = useState(false);
  const [logNote, setLogNote] = useState('');
  const [loggingKind, setLoggingKind] = useState(false);
  const [snoozeDays, setSnoozeDays] = useState(14);
  const [error, setError] = useState('');

  const [storedPeople, setStoredPeople] = usePersistentState('ffa-relationships', []);
  const people = useMemo(() => (storedPeople || []).map(migratePerson), [storedPeople]);
  const setPeople = setStoredPeople;



  // `view` starts empty so the state order stays PF-14 legal; which screen a
  // returning visitor lands on is a function of their data, not of init order.
  const screen = view || (people.length ? 'dashboard' : 'welcome');
  // This tool's outcome is the reach-out. Naming it `results` as well is what
  // places its cross-refs on the right side of the result.
  const results = reachout;
  const selected = people.find(p => p.id === selectedId) || null;

  const stageRef = useRef(null);
  useScrollToSection(stageRef, screen);

  // ⌘↵ / Ctrl+↵ commits the screen you are on. Refs rather than deps so the
  // listener is attached once and never sees a stale closure.
  const submitRef = useRef(null);
  const canSubmitRef = useRef(false);
  useEffect(() => {
    const handler = (e) => {
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && canSubmitRef.current) submitRef.current?.();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, []);

  const personStatus = useCallback((p) => {
    if (p.snoozedUntil && new Date(p.snoozedUntil) > new Date()) {
      return {
        key: 'paused',
        label: t('ffa_status_paused'),
        detail: t('ffa_until_date', { date: new Intl.DateTimeFormat(locale).format(new Date(p.snoozedUntil)) }),
      };
    }
    const elapsed = daysSince(lastMeaningful(p));
    const ratio = elapsed / rhythmDays(p.rhythm);
    const detail = t(elapsed === 1 ? 'ffa_days_since_one' : 'ffa_days_since', { days: elapsed });
    if (ratio < 0.7) return { key: 'recent', label: t('ffa_status_recent'), detail };
    if (ratio <= 1.25) return { key: 'hello', label: t('ffa_status_hello'), detail };
    return { key: 'while', label: t('ffa_status_while'), detail };
  }, [t, locale]);

  const sortedPeople = useMemo(() => {
    const rank = { while: 0, hello: 1, recent: 2, paused: 3 };
    return [...people].sort((a, b) => rank[personStatus(a).key] - rank[personStatus(b).key]);
  }, [people, personStatus]);

  const savePerson = () => {
    setError('');
    if (!form.name.trim()) { setError(t('ffa_err_name')); return; }
    const chosen = lastContactChoice === 'custom'
      ? customLastContact
      : isoDaysAgo(LAST_CONTACT_CHOICES.find(([v]) => v === lastContactChoice)?.[2] ?? 0);
    if (!chosen) { setError(t('ffa_err_last_contact')); return; }
    const person = {
      ...form,
      id: form.id || `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      name: form.name.trim(),
      lastContact: chosen,
      contextNotes: form.contextNotes.trim(),
      contactLog: form.contactLog || [],
    };
    setPeople(prev => form.id ? prev.map(p => p.id === form.id ? person : p) : [...prev, person]);
    setForm(blankPerson());
    setLastContactChoice('today');
    setCustomLastContact('');
    setRhythmSuggestion(null);
    setView('dashboard');
  };

  const askForRhythm = async () => {
    if (!form.name.trim()) { setError(t('ffa_err_add_first')); return; }
    setError('');
    setRhythmHelpLoading(true);
    try {
      const result = await callToolEndpoint('friendship-fade-alerter/recommend-rhythm', {
        name: form.name,
        relationshipType: form.relationshipType,
        contextNotes: form.contextNotes,
        ...apiLocale,
      });
      setRhythmSuggestion(result);
      if (result?.suggested_frequency) setForm(prev => ({ ...prev, rhythm: result.suggested_frequency }));
    } catch {
      setError(t('ffa_err_rhythm'));
    } finally {
      setRhythmHelpLoading(false);
    }
  };

  const openPerson = (id) => {
    setSelectedId(id);
    setReachout(null);
    setLogNote('');
    setView('person');
  };

  const generateReachout = async (p) => {
    setReachoutLoading(true);
    setReachout(null);
    setError('');
    try {
      const data = await callToolEndpoint('friendship-fade-alerter', {
        name: p.name,
        relationship: p.relationshipType,
        rhythm: p.rhythm,
        lastMeaningfulConnection: lastMeaningful(p),
        daysSinceMeaningfulConnection: daysSince(lastMeaningful(p)),
        notes: p.contextNotes,
        recentConnections: (p.contactLog || []).slice(0, 6),
        ...apiLocale,
      });
      setReachout(data);
    } catch {
      setError(t('ffa_err_message'));
    } finally {
      setReachoutLoading(false);
    }
  };

  const logContact = (p, kind) => {
    const [type, labelKey, meaningful] = kind;
    const note = logNote.trim();
    const now = new Date().toISOString().split('T')[0];
    setPeople(prev => prev.map(x => x.id === p.id ? {
      ...x,
      // Only catching up moves the clock. Logging that an email arrived should
      // not make the tool announce they connected today.
      lastContact: meaningful ? now : x.lastContact,
      snoozedUntil: meaningful ? null : x.snoozedUntil,
      contactLog: [{ date: now, type, meaningfulConnection: meaningful, note: note || t(labelKey) }, ...(x.contactLog || [])].slice(0, 20),
    } : x));
    setLogNote('');
    setLoggingKind(false);
    setReachout(null);
    setView('dashboard');
  };

  const snooze = (p) => {
    const until = new Date();
    until.setDate(until.getDate() + Number(snoozeDays || 14));
    setPeople(prev => prev.map(x => x.id === p.id ? { ...x, snoozedUntil: until.toISOString() } : x));
    setView('dashboard');
  };

  const editPerson = (p) => {
    setForm({ ...p });
    setLastContactChoice('custom');
    setCustomLastContact(p.lastContact);
    setView('add');
  };

  const removePerson = (p) => {
    if (!window.confirm(t('ffa_confirm_remove', { name: p.name }))) return;
    setPeople(prev => prev.filter(x => x.id !== p.id));
    setView(people.length <= 1 ? 'welcome' : 'dashboard');
  };

  const startAdding = () => {
    setForm(blankPerson());
    setLastContactChoice('today');
    setCustomLastContact('');
    setRhythmSuggestion(null);
    setError('');
    setView('add');
  };

  const loadExample = () => {
    // A friend drifting because life got busy, and one who has been quiet for
    // years — the message that suits those two is not remotely the same.
    const ex = pickExample('FriendshipFadeAlerter', [
      { nameKey: 'ffa_example_name', notesKey: 'ffa_example_notes', relationshipType: 'close_friend', rhythm: 'biweekly', daysAgo: 21 },
      { nameKey: 'ffa_example2_name', notesKey: 'ffa_example2_notes', relationshipType: 'friend', rhythm: 'semiannually', daysAgo: 400 },
    ]);
    setForm({
      ...blankPerson(),
      name: t(ex.nameKey),
      relationshipType: ex.relationshipType,
      rhythm: ex.rhythm,
      contextNotes: t(ex.notesKey),
    });
    setLastContactChoice('custom');
    setCustomLastContact(isoDaysAgo(ex.daysAgo));
    setRhythmSuggestion(null);
    setError('');
    setView('add');
  };

  const handleReset = () => {
    setForm(blankPerson());
    setLastContactChoice('today');
    setCustomLastContact('');
    setRhythmSuggestion(null);
    setReachout(null);
    setSelectedId(null);
    setLogNote('');
    setError('');
    setView(people.length ? 'dashboard' : 'welcome');
  };

  canSubmitRef.current = screen === 'add' ? !!form.name.trim() : (screen === 'person' && !reachoutLoading);
  submitRef.current = screen === 'add'
    ? savePerson
    : (screen === 'person' && selected ? () => generateReachout(selected) : null);

  const buildFullText = useCallback(() => {
    if (!reachout || !selected) return '';
    const lines = [`${tool?.icon ?? '💔'} ${t('ffa_copy_starters_title', { name: selected.name })}`, ''];
    if (reachout.encouragement) lines.push(reachout.encouragement, '');
    APPROACHES.forEach(([key, labelKey], i) => {
      const a = reachout[key];
      if (a && a.message) lines.push(t('ffa_copy_option', { n: i + 1, tone: t(labelKey) }), a.message, '');
    });
    lines.push(BRAND);
    return lines.join('\n');
  }, [reachout, selected, tool, t]);

  useRegisterActions(buildFullText(), tool?.title || 'Friendship Fade Alerter');

  return (
    <div className={`max-w-4xl mx-auto space-y-4 ${c.text}`}>
      {/* ── PF-30 header ── */}
      <section className={`rounded-2xl border ${c.border} ${c.card} px-5 pt-2.5 pb-5`}>
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div className="flex-1 min-w-0">
            {/* PF-30 — the wrapper already prints the name as the page <h1>. */}
            <p className="text-base">
              <span className="me-2 text-lg">{tool?.icon ?? '💔'}</span>{tool?.tagline ?? t('ffa_tagline')}
            </p>
            {/* The catalog description above the tool now carries this same
                sentence, but only in English — src/data/tools.js is English by
                design. Repeating it here would show an English reader the same
                paragraph twice; omitting it entirely would leave the other
                twelve languages with no translated version at all. */}
            {i18n.language !== 'en' && (
              <p className={`mt-1 text-sm max-w-2xl ${c.textSecondary}`}>{t('ffa_description')}</p>
            )}
            {(screen === 'welcome' || screen === 'add') && (
              <button onClick={loadExample}
                style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }}
                className="mt-2 px-4 py-2 rounded-full text-sm font-semibold border border-black/25 text-zinc-900 shadow-sm hover:brightness-105 hover:shadow transition whitespace-nowrap">
                ✨ {t('try_example')}
              </button>
            )}
          </div>
          {/* Only where there is something to back out of. On the dashboard this
              read "Start over" and did nothing: it set the view to the screen you
              were already on, and the form and selection it cleared are not
              visible from there. The people list is durable data, not a session,
              so the only thing "start over" could honestly mean on the dashboard
              is deleting everyone — which belongs behind Remove, per person, not
              behind a quiet header button. */}
          {(screen === 'add' || screen === 'person') && (
            <button className={`shrink-0 px-3 py-2 rounded-lg text-sm font-bold ${c.btnSecondary}`} onClick={handleReset}>
              ↺ {t('ffa_back_people')}
            </button>
          )}
        </div>
      </section>

      {error && <div className={`rounded-xl border p-3 text-sm ${c.danger}`}>{error}</div>}

      <div ref={stageRef} className="scroll-mt-24 space-y-4">
        {screen === 'welcome' && (
          <section className={`rounded-2xl border ${c.border} p-7 text-center ${c.card}`}>
            <div className="text-4xl mb-3">👥</div>
            <h2 className="text-2xl font-black">{t('ffa_welcome_title')}</h2>
            <p className={`mt-2 mx-auto max-w-xl ${c.textSecondary}`}>{t('ffa_welcome_body')}</p>
            <button onClick={startAdding} className={`mt-6 rounded-xl px-6 py-3 font-bold ${c.btnPrimary}`}>{t('ffa_add_someone')}</button>
          </section>
        )}

        {screen === 'add' && (
          <section className={`rounded-2xl border ${c.border} p-5 sm:p-6 ${c.card}`}>
            <h2 className="text-xl font-black">{t('ffa_add_title')}</h2>
            <p className={`text-sm mt-1 mb-6 ${c.textSecondary}`}>{t('ffa_add_body')}</p>

            <label className="block font-semibold mb-2" htmlFor="ffa-name">{t('ffa_who')} <span className={c.required}>*</span></label>
            <input id="ffa-name" value={form.name} onChange={e => setForm(p => ({ ...p, name: e.target.value }))}
              placeholder={t('ffa_name_placeholder')} className={`w-full rounded-xl border px-4 py-3 outline-none ${c.input}`} />

            <div className="mt-6">
              <div className="font-semibold mb-2">{t('ffa_relationship_q')}</div>
              <div className="flex flex-wrap gap-2">
                {RELATIONSHIPS.map(([value, labelKey]) => (
                  <button key={value} type="button" onClick={() => setForm(p => ({ ...p, relationshipType: value }))}
                    aria-pressed={form.relationshipType === value}
                    className={`rounded-xl border px-4 py-2 ${form.relationshipType === value ? c.pillActive : c.pillInactive}`}>{t(labelKey)}</button>
                ))}
              </div>
            </div>

            <div className="mt-6">
              <div className="font-semibold mb-2">{t('ffa_last_contact_q')}</div>
              <div className="flex flex-wrap gap-2">
                {LAST_CONTACT_CHOICES.map(([value, labelKey]) => (
                  <button key={value} type="button" onClick={() => setLastContactChoice(value)}
                    aria-pressed={lastContactChoice === value}
                    className={`rounded-xl border px-4 py-2 ${lastContactChoice === value ? c.pillActive : c.pillInactive}`}>{t(labelKey)}</button>
                ))}
                <button type="button" onClick={() => setLastContactChoice('custom')}
                  aria-pressed={lastContactChoice === 'custom'}
                  className={`rounded-xl border px-4 py-2 ${lastContactChoice === 'custom' ? c.pillActive : c.pillInactive}`}>{t('ffa_choose_date')}</button>
              </div>
              {lastContactChoice === 'custom' && (
                <input type="date" value={customLastContact} onChange={e => setCustomLastContact(e.target.value)}
                  className={`mt-3 rounded-xl border px-4 py-2 ${c.input}`} />
              )}
            </div>

            <div className="mt-6">
              <div className="font-semibold">{t('ffa_rhythm_q')}</div>
              <p className={`text-sm mt-1 mb-3 ${c.textMuted}`}>{t('ffa_rhythm_hint')}</p>
              <div className="flex flex-wrap gap-2">
                {RHYTHMS.map(([value, labelKey]) => (
                  <button key={value} type="button" onClick={() => setForm(p => ({ ...p, rhythm: value }))}
                    aria-pressed={form.rhythm === value}
                    className={`rounded-xl border px-4 py-2 ${form.rhythm === value ? c.pillActive : c.pillInactive}`}>{t(labelKey)}</button>
                ))}
                <button type="button" onClick={askForRhythm} disabled={rhythmHelpLoading}
                  className={`rounded-xl border px-4 py-2 font-semibold disabled:opacity-40 ${c.pillInactive}`}>
                  {rhythmHelpLoading
                    ? <><span className="animate-spin inline-block me-1">{tool?.icon ?? '💔'}</span>{t('ffa_thinking')}</>
                    : `✨ ${t('ffa_help_choose')}`}
                </button>
              </div>
              {rhythmSuggestion && (
                <div className={`mt-3 rounded-xl border ${c.border} p-3 text-sm ${c.cardAlt}`}>
                  <strong>{t('ffa_suggested')} {t(rhythmKey(rhythmSuggestion.suggested_frequency))}</strong>
                  <div className={`mt-1 ${c.textSecondary}`}>{rhythmSuggestion.reasoning}</div>
                </div>
              )}
            </div>

            <div className="mt-6">
              <label className="block font-semibold mb-2" htmlFor="ffa-notes">
                {t('ffa_remember_q')} <span className={`font-normal ${c.textMuted}`}>{t('ffa_optional')}</span>
              </label>
              <textarea id="ffa-notes" value={form.contextNotes} onChange={e => setForm(p => ({ ...p, contextNotes: e.target.value }))}
                placeholder={t('ffa_remember_placeholder')} rows={3} className={`w-full rounded-xl border px-4 py-3 outline-none ${c.input}`} />
            </div>

            <button onClick={savePerson} className={`mt-6 w-full rounded-xl px-5 py-3 font-bold ${c.btnPrimary}`}>
              {form.id ? t('ffa_save_changes') : t('ffa_add_to_people')}
              <span className={`ms-2 text-xs font-normal opacity-70`}>⌘↵</span>
            </button>
          </section>
        )}

        {screen === 'dashboard' && (
          <>
            <section className={`rounded-2xl border ${c.border} p-5 ${c.card}`}>
              <div className="flex items-center justify-between gap-3">
                <div>
                  <h2 className="text-xl font-black">{t('ffa_my_people')}</h2>
                  <p className={`text-sm ${c.textSecondary}`}>{t('ffa_dashboard_hint')}</p>
                </div>
                <button onClick={startAdding} className={`shrink-0 rounded-xl px-4 py-2 font-bold ${c.btnPrimary}`}>+ {t('ffa_add_person')}</button>
              </div>
            </section>

            <div className="space-y-3">
              {sortedPeople.map(p => {
                const s = personStatus(p);
                const tone = s.key === 'while'
                  ? (isDark ? 'border-amber-700 bg-amber-950/10' : 'border-amber-200 bg-amber-50/40')
                  : s.key === 'hello'
                    ? (isDark ? 'border-sky-800 bg-sky-950/10' : 'border-sky-200 bg-sky-50/40')
                    : c.card;
                return (
                  <button key={p.id} onClick={() => openPerson(p.id)}
                    className={`w-full text-start rounded-2xl border p-5 transition hover:-translate-y-0.5 ${tone}`}>
                    <div className="flex flex-wrap items-center justify-between gap-3">
                      <div>
                        <div className="text-lg font-black">{p.name}</div>
                        <div className={`text-sm ${c.textSecondary}`}>{t(relationKey(p.relationshipType))} · {t(rhythmKey(p.rhythm))}</div>
                      </div>
                      <div className="text-end">
                        <div className="font-bold">{s.label}</div>
                        <div className={`text-xs ${c.textMuted}`}>{s.detail}</div>
                      </div>
                    </div>
                  </button>
                );
              })}
            </div>
          </>
        )}

        {screen === 'person' && selected && (
          <section className={`rounded-2xl border ${c.border} p-5 sm:p-6 ${c.card}`}>
            <div className="flex flex-wrap justify-between gap-4">
              <div>
                <h2 className="text-2xl font-black">{selected.name}</h2>
                <p className={c.textSecondary}>{t(relationKey(selected.relationshipType))} · {t(rhythmKey(selected.rhythm))}</p>
              </div>
              <div>
                <div className="font-bold">{personStatus(selected).label}</div>
                <div className={`text-xs ${c.textMuted}`}>{personStatus(selected).detail}</div>
              </div>
            </div>

            {selected.contextNotes && (
              <div className={`mt-5 rounded-xl border ${c.border} p-4 ${c.cardAlt}`}>
                <div className="text-xs font-bold uppercase tracking-wide mb-1">{t('ffa_worth_remembering')}</div>
                <div className={c.textSecondary}>{selected.contextNotes}</div>
              </div>
            )}

            <div className="grid sm:grid-cols-2 gap-3 mt-5">
              <button onClick={() => generateReachout(selected)} disabled={reachoutLoading}
                className={`rounded-xl px-5 py-3 font-bold disabled:opacity-40 ${c.btnPrimary}`}>
                {reachoutLoading
                  ? <><span className="animate-spin inline-block me-1">{tool?.icon ?? '💔'}</span>{t('ffa_writing')}</>
                  : `💬 ${t('ffa_help_reachout')}`}
              </button>
              <button onClick={() => setLoggingKind(v => !v)} aria-expanded={loggingKind}
                className={`rounded-xl border px-5 py-3 font-bold ${c.pillInactive}`}>✓ {t('ffa_we_connected')}</button>
            </div>

            {loggingKind && (
              <div className={`mt-3 rounded-xl border ${c.border} p-4 ${c.cardAlt}`}>
                <div className="font-semibold mb-2">{t('ffa_what_happened')}</div>
                <div className="flex flex-wrap gap-2">
                  {CONNECTION_KINDS.map(kind => (
                    <button key={kind[0]} type="button" onClick={() => logContact(selected, kind)}
                      className={`rounded-xl border px-4 py-2 text-sm font-semibold ${c.pillInactive}`}>{t(kind[1])}</button>
                  ))}
                </div>
              </div>
            )}

            <div className="mt-5">
              <label className="block text-sm font-semibold mb-2" htmlFor="ffa-log">{t('ffa_log_note')}</label>
              <input id="ffa-log" value={logNote} onChange={e => setLogNote(e.target.value)}
                placeholder={t('ffa_log_placeholder')} className={`w-full rounded-xl border px-4 py-3 ${c.input}`} />
            </div>

            {results && (
              <div className={`mt-6 rounded-2xl border ${c.border} p-5 ${c.cardAlt}`}>
                <h3 className="font-black text-lg">{t('ffa_ways_in')}</h3>
                <p className={`text-sm mt-1 ${c.textSecondary}`}>{reachout.encouragement}</p>
                <div className="space-y-3 mt-4">
                  {APPROACHES.map(([key, labelKey]) => {
                    const a = reachout[key];
                    if (!a || !a.message) return null;
                    return (
                      <div key={key} className={`rounded-xl border ${c.border} p-4 ${c.card}`}>
                        <div className={`text-xs font-bold uppercase ${c.accentTxt}`}>{t(labelKey)}</div>
                        <div className="mt-2">{a.message}</div>
                        {a.why && <div className={`text-xs mt-2 ${c.textMuted}`}>{a.why}</div>}
                      </div>
                    );
                  })}
                </div>
                <p className={`mt-4 text-center text-sm ${c.textMuted}`}>
                  {t('ffa_xref_after')}{' '}
                  <a href="/GratitudeDebtClearer" className={linkStyle}>{t('ffa_related_gratitude')}</a>
                </p>
              </div>
            )}

            <div className={`mt-6 rounded-xl border ${c.border} p-4 ${c.cardAlt}`}>
              <div className="font-bold">{t('ffa_busy')}</div>
              <p className={`text-sm mt-1 ${c.textSecondary}`}>{t('ffa_pause_hint')}</p>
              <div className="flex flex-wrap gap-2 mt-3 items-center">
                <label className="sr-only" htmlFor="ffa-snooze">{t('ffa_busy')}</label>
                <select id="ffa-snooze" value={snoozeDays} onChange={e => setSnoozeDays(e.target.value)}
                  className={`rounded-xl border px-3 py-2 ${c.input}`}>
                  {SNOOZE_CHOICES.map(([d, labelKey]) => <option key={d} value={d}>{t(labelKey)}</option>)}
                </select>
                <button onClick={() => snooze(selected)} className={`rounded-xl border px-4 py-2 ${c.pillInactive}`}>{t('ffa_pause_now')}</button>
              </div>
            </div>

            {(selected.contactLog || []).length > 0 && (
              <div className={`mt-6 rounded-xl border ${c.border} p-4 ${c.cardAlt}`}>
                <div className="text-xs font-bold uppercase tracking-wide mb-2">{t('ffa_log_title')}</div>
                <ul className="space-y-1.5">
                  {(selected.contactLog || []).slice(0, 6).map((entry, i) => (
                    <li key={i} className="text-sm flex gap-3">
                      <span className={`shrink-0 tabular-nums ${c.textMuted}`}>
                        {new Intl.DateTimeFormat(locale, { month: 'short', day: 'numeric' }).format(new Date(`${entry.date}T12:00:00`))}
                      </span>
                      <span className={c.textSecondary}>{String(entry.note || '').slice(0, 40)}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            <div className="flex flex-wrap gap-2 mt-6">
              <button onClick={() => editPerson(selected)} className={`rounded-xl border px-4 py-2 ${c.pillInactive}`}>{t('ffa_edit')}</button>
              <button onClick={() => removePerson(selected)}
                className={`rounded-xl border px-4 py-2 ${c.danger}`}>{t('ffa_remove')}</button>
            </div>
          </section>
        )}
      </div>

      {!results && (
        <p className={`text-center text-sm ${c.textMuted}`}>
          {t('ffa_xref_q')}{' '}
          <a href="/DifficultTalkCoach" className={linkStyle}>{t('ffa_related_difficult_talk')}</a>
        </p>
      )}
    </div>
  );
};

FriendshipFadeAlerter.displayName = 'FriendshipFadeAlerter';
export default FriendshipFadeAlerter;
