import React, { useState, useRef, useCallback, useEffect } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { CopyBtn, ActionBar } from '../components/ActionButtons';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

// ════════════════════════════════════════════════════════════
// THEME — Navy & Gold
// ════════════════════════════════════════════════════════════

// ════════════════════════════════════════════════════════════
// CONSTANTS
// ════════════════════════════════════════════════════════════
const LETTER_TYPES = [
  { value: 'job', label: '💼 Job recommendation' },
  { value: 'grad-school', label: '🎓 Graduate school' },
  { value: 'linkedin', label: '💬 LinkedIn recommendation' },
  { value: 'scholarship', label: '🏆 Scholarship' },
  { value: 'rental', label: '🏠 Rental/housing reference' },
  { value: 'character', label: '🤝 Character reference' },
  { value: 'other', label: '📝 Other' },
];

const FORMALITY_OPTIONS = [
  { value: 'casual', label: 'Casual (LinkedIn, brief reference)' },
  { value: 'professional', label: 'Professional (job rec, standard)' },
  { value: 'formal', label: 'Formal (grad school, legal, scholarship)' },
];

const QUALITY_OPTIONS = [
  'Leadership', 'Problem-solving', 'Communication', 'Work ethic',
  'Creativity', 'Teamwork', 'Technical skills', 'Reliability',
  'Initiative', 'Empathy', 'Attention to detail', 'Adaptability',
  'Mentorship', 'Strategic thinking', 'Resilience',
];

const VERSION_ICONS = { narrative: '📖', structured: '📋', concise: '⚡' };


// ════════════════════════════════════════════════════════════
// MAIN COMPONENT
// ════════════════════════════════════════════════════════════
const GhostWriter = ({ tool }) => {
  const { callToolEndpoint, loading } = useClaudeAPI();
  const resultsRef = useRef(null);

  // Persistent
  const { isDark } = useTheme();


  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-600 hover:text-cyan-700 underline underline-offset-2';

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-500' : 'text-gray-400',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-200 text-red-800',
    infoBox:       isDark ? 'bg-sky-900/20 border-sky-700 text-sky-200' : 'bg-sky-50 border-sky-200 text-sky-800',
    successBox:    isDark ? 'bg-emerald-900/20 border-emerald-700' : 'bg-emerald-50 border-emerald-300',
    successTxt:    isDark ? 'text-emerald-300' : 'text-emerald-800',
    warningBox:    isDark ? 'bg-amber-900/20 border-amber-700' : 'bg-amber-50 border-amber-300',
    warningTxt:    isDark ? 'text-amber-300' : 'text-amber-800',
    pillActive:    isDark ? 'border-cyan-500 bg-cyan-900/30 text-cyan-200' : 'border-cyan-600 bg-cyan-100 text-cyan-900',
    pillInactive:  isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500' : 'border-gray-300 text-gray-500 hover:border-gray-400',
  };

  const [history, setHistory] = usePersistentState('ghost-writer-history', []);
  const [showHistory, setShowHistory] = useState(false);

  // Input
  const [recipientName, setRecipientName] = useState('');
  const [yourRelationship, setYourRelationship] = useState('');
  const [whatFor, setWhatFor] = useState('');
  const [letterType, setLetterType] = useState('job');
  const [formalityLevel, setFormalityLevel] = useState('professional');
  const [qualities, setQualities] = useState([]);
  const [anecdotes, setAnecdotes] = useState(['']);
  const [duration, setDuration] = useState('');
  const [additionalContext, setAdditionalContext] = useState('');

  // Results
  const [results, setResults] = usePersistentState('ghostwriter-result', null);
  const [error, setError] = useState('');
  const [activeVersion, setActiveVersion] = useState('narrative');

  // Refinement
  const [refiningVersion, setRefiningVersion] = useState(null);
  const [refinementText, setRefinementText] = useState('');
  const [refinedVersions, setRefinedVersions] = useState({});
  const [refineLoading, setRefineLoading] = useState(false);

  // Sections
  const [showPlaceholders, setShowPlaceholders] = useState(true);
  const [showPowerPhrases, setShowPowerPhrases] = useState(false);
  const [showWritingTips, setShowWritingTips] = useState(false);

  useEffect(() => {
    if (results && resultsRef.current) {
      setTimeout(() => resultsRef.current.scrollIntoView({ behavior: 'smooth', block: 'start' }), 200);
    }
  }, [results]);

  // ══════════════════════════════════════════
  // HANDLERS
  // ══════════════════════════════════════════
  const toggleQuality = useCallback((val) => {
    setQualities(prev => prev.includes(val) ? prev.filter(q => q !== val) : [...prev, val]);
  }, []);

  const updateAnecdote = useCallback((idx, val) => {
    setAnecdotes(prev => prev.map((a, i) => i === idx ? val : a));
  }, []);

  const addAnecdote = useCallback(() => {
    if (anecdotes.length < 5) setAnecdotes(prev => [...prev, '']);
  }, [anecdotes.length]);

  const removeAnecdote = useCallback((idx) => {
    if (anecdotes.length > 1) setAnecdotes(prev => prev.filter((_, i) => i !== idx));
  }, [anecdotes.length]);

  const generate = useCallback(async () => {
    if (!recipientName.trim() || !yourRelationship.trim()) {
      setError('We need the person\'s name and your relationship to them'); return;
    }
    setError(''); setResults(null); setRefinedVersions({});
    setRefiningVersion(null); setActiveVersion('narrative');
    try {
      const data = await callToolEndpoint('ghost-writer', {
        recipientName: recipientName.trim(),
        yourRelationship: yourRelationship.trim(),
        whatTheyreApplyingFor: whatFor.trim() || null,
        letterType: LETTER_TYPES.find(t => t.value === letterType)?.label || letterType,
        qualities: qualities.length > 0 ? qualities : null,
        anecdotes: anecdotes.filter(a => a.trim()).length > 0 ? anecdotes.filter(a => a.trim()) : null,
        duration: duration.trim() || null,
        formalityLevel,
        additionalContext: additionalContext.trim() || null,
      });
      setResults(data);
      saveToHistory(data);
    } catch (err) { setError(err.message || 'Failed to generate letter.'); }
  }, [recipientName, yourRelationship, whatFor, letterType, qualities, anecdotes, duration, formalityLevel, additionalContext, callToolEndpoint]);

  const handleRefine = useCallback(async (version) => {
    if (!refinementText.trim()) return;
    setRefineLoading(true);
    try {
      const data = await callToolEndpoint('ghost-writer/refine', {
        letterText: version.letter,
        refinementRequest: refinementText.trim(),
        letterType, formalityLevel,
      });
      if (data.refined_letter) {
        setRefinedVersions(prev => ({ ...prev, [version.style]: data.refined_letter }));
      }
      setRefiningVersion(null); setRefinementText('');
    } catch (err) { setError(err.message || 'Failed to refine.'); }
    finally { setRefineLoading(false); }
  }, [refinementText, letterType, formalityLevel, callToolEndpoint]);

  const revertRefinement = useCallback((style) => {
    setRefinedVersions(prev => { const n = { ...prev }; delete n[style]; return n; });
  }, []);

  const handleReset = useCallback(() => {
    setRecipientName(''); setYourRelationship(''); setWhatFor('');
    setQualities([]); setAnecdotes(['']); setDuration('');
    setAdditionalContext(''); setResults(null); setError('');
    setRefinedVersions({}); setRefiningVersion(null);
  }, []);

  // ══════════════════════════════════════════
  // HISTORY
  // ══════════════════════════════════════════
  const saveToHistory = useCallback((data) => {
    const entry = {
      id: `gw_${Date.now()}`, date: new Date().toISOString(),
      preview: `Letter for ${recipientName}`,
      type: letterType, results: data,
    };
    setHistory(prev => [entry, ...prev].slice(0, 6));
  }, [recipientName, letterType, setHistory]);

  // ══════════════════════════════════════════
  // COPY
  // ══════════════════════════════════════════
  const buildLetterCopy = useCallback((version) => {
    const text = refinedVersions[version.style] || version.letter;
    return `${text}\n\n— Generated by DeftBrain · deftbrain.com`;
  }, [refinedVersions]);

  const buildAllCopy = useCallback(() => {
    if (!results?.versions) return '';
    const lines = ['✍️ Ghost Writer — Recommendation Letters', ''];
    results.versions.forEach(v => {
      const text = refinedVersions[v.style] || v.letter;
      lines.push(`══ ${v.label || v.style} ══`, text, '');
    });
    lines.push('— Generated by DeftBrain · deftbrain.com');
    return lines.join('\n');
  }, [results, refinedVersions]);

  // ══════════════════════════════════════════
  // RENDER HELPERS
  // ══════════════════════════════════════════
  const Pill = ({ active, onClick, children }) => (
    <button onClick={onClick}
      className={`px-3 py-1.5 rounded-lg border text-xs font-semibold transition-all ${active ? c.pillActive : c.pillInactive}`}>
      {active && <span className="mr-1">✓</span>}{children}
    </button>
  );

  const Section = ({ title, emoji, open, onToggle, badge, children }) => (
    <div className={`${c.card} ${c.border} border rounded-xl overflow-hidden`}>
      <button onClick={onToggle} className="w-full flex items-center justify-between p-5 text-left hover:opacity-80">
        <div className="flex items-center gap-3">
          <span className="text-lg">{emoji}</span>
          <span className={`text-base font-semibold ${c.text}`}>{title}</span>
          {badge && <span className={`text-xs px-2 py-0.5 rounded-full ${c.badge}`}>{badge}</span>}
        </div>
        <span className={`text-xs ${c.textMuteded}`}>{open ? '▲' : '▼'}</span>
      </button>
      {open && <div className={`px-5 pb-5 border-t ${c.border}`}>{children}</div>}
    </div>
  );

  // ══════════════════════════════════════════
  // RENDER: Input
  // ══════════════════════════════════════════
  const renderInput = () => (
    <div className="space-y-4">
      <div className={`${c.card} ${c.border} border rounded-xl p-5 space-y-4`}>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div>
            <label className={`text-xs font-bold ${c.textSecondaryondary} uppercase tracking-wide mb-1 block`}>👤 Who is this for?</label>
            <input type="text" value={recipientName} onChange={e => setRecipientName(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') generate(); }}
              placeholder="Their name" className={`w-full px-4 py-2.5 rounded-xl border text-sm ${c.input} outline-none`} />
          </div>
          <div>
            <label className={`text-xs font-bold ${c.textSecondaryondary} uppercase tracking-wide mb-1 block`}>🤝 Your relationship</label>
            <input type="text" value={yourRelationship} onChange={e => setYourRelationship(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') generate(); }}
              placeholder="e.g., 'their manager for 2 years'" className={`w-full px-4 py-2.5 rounded-xl border text-sm ${c.input} outline-none`} />
          </div>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div>
            <label className={`text-xs font-bold ${c.textSecondaryondary} uppercase tracking-wide mb-1 block`}>🎯 What they're applying for</label>
            <input type="text" value={whatFor} onChange={e => setWhatFor(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') generate(); }}
              placeholder="e.g., 'Senior Product Manager at Google'" className={`w-full px-4 py-2.5 rounded-xl border text-sm ${c.input} outline-none`} />
          </div>
          <div>
            <label className={`text-xs font-bold ${c.textSecondaryondary} uppercase tracking-wide mb-1 block`}>⏱️ How long you've known them</label>
            <input type="text" value={duration} onChange={e => setDuration(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') generate(); }}
              placeholder="e.g., '3 years'" className={`w-full px-4 py-2.5 rounded-xl border text-sm ${c.input} outline-none`} />
          </div>
        </div>
      </div>

      {/* Letter type */}
      <div className={`${c.card} ${c.border} border rounded-xl p-5`}>
        <label className={`text-xs font-bold ${c.textSecondaryondary} uppercase tracking-wide mb-2 block`}>📄 Letter type</label>
        <div className="flex flex-wrap gap-1.5">
          {LETTER_TYPES.map(opt => (
            <Pill key={opt.value} active={letterType === opt.value} onClick={() => setLetterType(opt.value)}>{opt.label}</Pill>
          ))}
        </div>
        <label className={`text-xs font-bold ${c.textSecondaryondary} uppercase tracking-wide mt-4 mb-2 block`}>📏 Formality</label>
        <div className="flex flex-wrap gap-1.5">
          {FORMALITY_OPTIONS.map(opt => (
            <Pill key={opt.value} active={formalityLevel === opt.value} onClick={() => setFormalityLevel(opt.value)}>{opt.label}</Pill>
          ))}
        </div>
      </div>

      {/* Qualities */}
      <div className={`${c.card} ${c.border} border rounded-xl p-5`}>
        <label className={`text-xs font-bold ${c.textSecondaryondary} uppercase tracking-wide mb-1 block`}>⭐ Qualities to highlight</label>
        <p className={`text-xs ${c.textMuteded} mb-2`}>Select the traits that stand out about this person</p>
        <div className="flex flex-wrap gap-1.5">
          {QUALITY_OPTIONS.map(q => (
            <Pill key={q} active={qualities.includes(q)} onClick={() => toggleQuality(q)}>{q}</Pill>
          ))}
        </div>
      </div>

      {/* Anecdotes */}
      <div className={`${c.card} ${c.border} border rounded-xl p-5`}>
        <label className={`text-xs font-bold ${c.textSecondaryondary} uppercase tracking-wide mb-1 block`}>📝 Specific examples or stories</label>
        <p className={`text-xs ${c.textMuteded} mb-3`}>Even rough bullet points work — we'll turn them into compelling mini-stories</p>
        <div className="space-y-2">
          {anecdotes.map((a, idx) => (
            <div key={idx} className="flex gap-2">
              <input type="text" value={a} onChange={e => updateAnecdote(idx, e.target.value)}
                placeholder={`e.g., "${idx === 0 ? 'Led the Q3 product launch that exceeded targets by 20%' : 'Mentored two junior team members who both got promoted'}"`}
                className={`flex-1 px-4 py-2.5 rounded-xl border text-sm ${c.input} outline-none`} />
              {anecdotes.length > 1 && (
                <button onClick={() => removeAnecdote(idx)} className={`px-3 rounded-lg text-xs ${c.btnGhost} hover:text-zinc-400`}>✕</button>
              )}
            </div>
          ))}
        </div>
        {anecdotes.length < 5 && (
          <button onClick={addAnecdote} className={`mt-2 text-xs font-semibold ${linkStyle}`}>➕ Add another</button>
        )}
      </div>

      {/* Context */}
      <div className={`${c.card} ${c.border} border rounded-xl p-5`}>
        <label className={`text-xs font-bold ${c.textSecondaryondary} uppercase tracking-wide mb-1 block`}>💬 Anything else?</label>
        <input type="text" value={additionalContext} onChange={e => setAdditionalContext(e.target.value)}
          placeholder="e.g., 'They're career-switching from marketing to product management'"
          className={`w-full px-4 py-2.5 rounded-xl border text-sm ${c.input} outline-none`} />
      </div>

      <button onClick={generate}
        disabled={loading || !recipientName.trim() || !yourRelationship.trim()}
        className={`w-full py-4 rounded-2xl text-sm font-bold flex items-center justify-center gap-2 transition-all ${
          loading || !recipientName.trim() || !yourRelationship.trim() ? c.btnDisabled : c.btnPrimary
        }`}>
        {loading ? <><span className="animate-spin inline-block">{tool?.icon ?? '✍️'}</span> Writing your letter...</>
          : <><span>✍️</span> Generate Letter</>}
      </button>
    </div>
  );

  // ══════════════════════════════════════════
  // RENDER: Results
  // ══════════════════════════════════════════
  const renderResults = () => {
    if (!results?.versions?.length) return null;

    return (
      <div ref={resultsRef} className="space-y-4 mt-4">
        {/* Version tabs */}
        <div className={`${c.card} ${c.border} border rounded-xl overflow-hidden`}>
          <div className={`flex border-b ${c.border}`}>
            {results.versions.map(v => (
              <button key={v.style} onClick={() => setActiveVersion(v.style)}
                className={`flex-1 flex items-center justify-center gap-2 px-4 py-4 text-sm font-semibold transition-all ${
                  activeVersion === v.style ? c.tabActive : c.tabInactive
                }`}>
                <span>{VERSION_ICONS[v.style] || '📝'}</span>
                <span className="hidden sm:inline">{v.label?.split('—')[0]?.trim() || v.style}</span>
                <span className="sm:hidden capitalize">{v.style}</span>
              </button>
            ))}
          </div>

          {results.versions.map(v => {
            if (v.style !== activeVersion) return null;
            const displayText = refinedVersions[v.style] || v.letter;
            const isRefined = !!refinedVersions[v.style];

            return (
              <div key={v.style} className="p-6 space-y-4">
                {/* Best for + word count */}
                <div className="flex items-center justify-between flex-wrap gap-2">
                  {v.best_for && <span className={`text-sm ${c.textMuteded}`}>💡 {v.best_for}</span>}
                  {v.word_count && <span className={`text-xs px-2 py-0.5 rounded-full ${c.badge}`}>{v.word_count} words</span>}
                </div>

                {/* Strengths */}
                {v.strengths?.length > 0 && (
                  <div className="flex flex-wrap gap-1.5">
                    {v.strengths.map((s, i) => (
                      <span key={i} className={`text-xs px-2.5 py-1 rounded-full ${c.badge}`}>{s}</span>
                    ))}
                  </div>
                )}

                {/* The letter */}
                <div className={`p-5 rounded-xl border ${c.letterBg}`}>
                  {isRefined && (
                    <div className={`text-xs font-medium mb-2 flex items-center gap-1 ${c.tipText}`}>
                      <span>✏️</span> Refined version
                      <button onClick={() => revertRefinement(v.style)} className="ml-2 underline hover:no-underline">Revert</button>
                    </div>
                  )}
                  <p className={`text-sm leading-relaxed whitespace-pre-wrap ${c.text}`}>{displayText}</p>
                </div>

                {/* Customize prompts */}
                {v.customize_prompts?.length > 0 && (
                  <div className={`p-4 rounded-xl border ${c.placeholderBg}`}>
                    <p className={`text-xs font-bold ${c.placeholderText} mb-2`}>✏️ Personalize these parts</p>
                    {v.customize_prompts.map((prompt, i) => (
                      <p key={i} className={`text-xs ${c.placeholderText} mb-1`}>• {prompt}</p>
                    ))}
                  </div>
                )}

                {/* Actions */}
                <div className="flex flex-wrap gap-3">
                  <CopyBtn content={buildLetterCopy(v)} label="Copy Letter" />
                  <button onClick={() => { setRefiningVersion(refiningVersion === v.style ? null : v.style); setRefinementText(''); }}
                    className={`${c.btnSecondaryondary} px-4 py-2.5 rounded-lg text-sm font-medium flex items-center gap-2`}>
                    <span>✏️</span> Refine
                  </button>
                </div>

                {/* Refinement input */}
                {refiningVersion === v.style && (
                  <div className={`${c.cardAlt} ${c.border} border rounded-xl p-4 space-y-3`}>
                    <label className={`text-sm font-semibold ${c.textSecondaryondary}`}>How should I adjust this?</label>
                    <textarea value={refinementText} onChange={e => setRefinementText(e.target.value)}
                      placeholder='e.g., "Make it shorter", "Add the client presentation story", "Sound warmer"'
                      className={`w-full p-3 border rounded-lg ${c.input} outline-none focus:ring-2 resize-none text-sm`} rows={2} />
                    <div className="flex gap-2">
                      <button onClick={() => handleRefine(v)}
                        disabled={refineLoading || !refinementText.trim()}
                        className={`${refineLoading || !refinementText.trim() ? c.btnDisabled : c.btnPrimary} px-4 py-2 rounded-lg text-sm font-semibold flex items-center gap-2`}>
                        {refineLoading ? <span className="animate-spin inline-block">{tool?.icon ?? '✍️'}</span> : <span>✨</span>} Refine
                      </button>
                      <button onClick={() => { setRefiningVersion(null); setRefinementText(''); }}
                        className={`${c.btnSecondaryondary} px-4 py-2 rounded-lg text-sm`}>Cancel</button>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Placeholders */}
        {results.placeholders_to_fill?.length > 0 && (
          <Section title="Fill In These Details" emoji="📝" open={showPlaceholders}
            onToggle={() => setShowPlaceholders(!showPlaceholders)} badge={`${results.placeholders_to_fill.length} items`}>
            <div className="space-y-2 mt-4">
              {results.placeholders_to_fill.map((p, idx) => (
                <div key={idx} className={`p-3 rounded-lg ${c.cardAlt} ${c.border} flex items-start gap-3`}>
                  <code className={`text-xs font-mono px-1.5 py-0.5 rounded ${c.badge} flex-shrink-0`}>{p.placeholder}</code>
                  <span className={`text-xs ${c.textSecondaryondary}`}>→ {p.suggestion}</span>
                </div>
              ))}
            </div>
          </Section>
        )}

        {/* Power Phrases */}
        {results.power_phrases?.length > 0 && (
          <Section title="Power Phrases" emoji="💪" open={showPowerPhrases}
            onToggle={() => setShowPowerPhrases(!showPowerPhrases)}>
            <div className="space-y-2 mt-4">
              {results.power_phrases.map((phrase, idx) => (
                <div key={idx} className={`p-3 rounded-lg border ${c.powerBg}`}>
                  <p className={`text-sm ${c.powerText} italic`}>"{phrase}"</p>
                </div>
              ))}
            </div>
          </Section>
        )}

        {/* Writing Tips */}
        {results.writing_tips?.length > 0 && (
          <Section title="Writing Tips" emoji="💡" open={showWritingTips}
            onToggle={() => setShowWritingTips(!showWritingTips)}>
            <div className="space-y-2 mt-4">
              {results.writing_tips.map((tip, idx) => (
                <p key={idx} className={`text-sm ${c.textSecondaryondary}`}>• {tip}</p>
              ))}
            </div>
          </Section>
        )}

        {/* Actions */}
        <div className="flex gap-2">
          <ActionBar content={buildAllCopy()} subject="Reference letter from GhostWriter" className="flex-1" />
          <button onClick={handleReset}
            className={`px-4 py-3 rounded-xl text-xs font-bold flex items-center justify-center gap-1.5 ${c.btnSecondaryondary}`}>
            <span>🔄</span> New Letter
          </button>
        </div>

        {/* Cross-references */}
        <div className={`p-4 rounded-2xl border ${c.card} ${c.border}`}>
          <p className={`text-xs font-bold ${c.textMuteded} uppercase tracking-wide mb-2`}>🔗 Related Tools</p>
          <div className={`space-y-1.5 text-xs ${c.textSecondaryondary}`}>
            <p>Writing a tough message instead? <a href="/VelvetHammer" target="_blank" rel="noopener noreferrer" className={linkStyle}>Velvet Hammer</a> transforms angry drafts into professional messages.</p>
            <p>Need to craft a social caption about your team? <a href="/CaptionMagic" target="_blank" rel="noopener noreferrer" className={linkStyle}>Caption Magic</a> generates authentic social media captions.</p>
          </div>
        </div>
      </div>
    );
  };

  // History
  const renderHistory = () => {
    if (history.length === 0) return null;
    const formatDate = (iso) => {
      try { const d = new Date(iso); const diff = Math.floor((new Date() - d) / 86400000); return diff === 0 ? 'Today' : diff === 1 ? 'Yesterday' : diff < 7 ? `${diff}d ago` : d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' }); } catch { return ''; }
    };
    return (
      <div className={`mt-6 p-4 rounded-2xl border ${c.histBg}`}>
        <button onClick={() => setShowHistory(!showHistory)} className="w-full flex items-center gap-2 text-left">
          <span className={`text-base ${c.histAccent}`}>✍️</span>
          <span className={`text-sm font-bold ${c.text} flex-1`}>Past Letters</span>
          <span className={`text-xs ${c.textMuteded}`}>{history.length}</span>
          <span className={`text-xs ${c.textMuteded}`}>{showHistory ? '▲' : '▼'}</span>
        </button>
        {showHistory && (
          <div className="mt-3 space-y-2">
            {history.map(entry => (
              <div key={entry.id} className={`rounded-xl border ${c.card} ${c.border} p-3 flex items-center gap-3`}>
                <div className="flex-1 min-w-0">
                  <div className={`text-sm font-semibold ${c.text} truncate`}>{entry.preview}</div>
                  <div className={`text-xs ${c.textMuteded} mt-0.5`}>{formatDate(entry.date)} · {entry.type}</div>
                </div>
                <button onClick={() => { setResults(entry.results); setShowHistory(false); setRefinedVersions({}); setActiveVersion('narrative'); }}
                  className={`px-3 py-1.5 rounded-lg text-xs font-bold ${c.btnSecondaryondary}`}>View</button>
                <button onClick={() => setHistory(prev => prev.filter(h => h.id !== entry.id))}
                  className={`px-2 py-1.5 rounded-lg text-xs ${c.btnGhost} hover:text-zinc-400`}>🗑️</button>
              </div>
            ))}
          </div>
        )}
      </div>
    );
  };

  return (
    <div>
      <div className="flex items-center gap-3 mb-5">
        <div>
          <h2 className={`text-2xl font-bold ${c.text}`}>Ghost Writer <span className="text-xl">✍️</span></h2>
          <p className={`text-sm ${c.textMuteded}`}>Turn rough notes into polished recommendation letters in seconds</p>
        </div>
      </div>
      {!results && renderInput()}
      {results && renderResults()}
      {error && (
        <div className={`mt-4 p-4 ${c.danger} border rounded-xl flex items-start gap-3`}>
          <span className={`text-base ${c.danger}`}>⚠️</span>
          <p className={`text-sm ${c.danger}`}>{error}</p>
        </div>
      )}
      {renderHistory()}
    </div>
  );
};

GhostWriter.displayName = 'GhostWriter';
export default GhostWriter;
