import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';
import { pickExample } from '../utils/exampleRotation';
import Caret from '../components/Caret';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

const EXAMPLES = [
  {
    recipientName: 'Marcus',
    gratitudePoints: "Drove 4 hours to help me move with a truck he'd never driven before. Didn't complain once and bought me dinner after.",
    relationship: 'Friend',
  },
  {
    recipientName: 'Sarah',
    gratitudePoints: 'Went to bat for me during a reorg and helped protect my role. Then coached me through a rough stretch at work without making me feel judged.',
    relationship: 'Coworker / professional',
  },
];

const RELATIONSHIPS = ['Friend', 'Family', 'Coworker / professional', 'Neighbor / community', 'Other'];
const TONES = ['Let DeftBrain choose', 'Warm & casual', 'Heartfelt', 'Professional', 'Brief'];
const LENGTHS = ['Short', 'Moderate', 'Detailed'];

const GratitudeDebtClearer = ({ tool }) => {
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();
  const resultsRef = useRef(null);

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20'
                          : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-400' : 'text-gray-500',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white'
                          : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200'
                          : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200'
                          : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200'
                          : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200'
                          : 'bg-red-50 border-red-200 text-red-800',
    required:      isDark ? 'text-amber-400' : 'text-amber-700',
    accentSoft:    isDark ? 'bg-cyan-950/30 border-cyan-800' : 'bg-cyan-50 border-cyan-200',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';

  const [recipientName, setRecipientName] = useState('');
  const [gratitudePoints, setGratitudePoints] = useState('');
  const [relationship, setRelationship] = useState('Friend');
  const [tone, setTone] = useState('Let DeftBrain choose');
  const [length, setLength] = useState('Moderate');
  const [extraContext, setExtraContext] = useState('');
  const [showOptions, setShowOptions] = useState(false);
  const [results, setResults] = usePersistentState('gratitudedebtclearer-result-v2', null);
  const [editedMessages, setEditedMessages] = useState({});
  const [editingIndex, setEditingIndex] = useState(null);
  const [adjustingIndex, setAdjustingIndex] = useState(null);
  const [error, setError] = useState('');



  // Refs, not deps: attach the listener once and never read a stale closure.
  const submitRef = useRef(null);
  const canSubmitRef = useRef(false);
  useEffect(() => {
    const handler = (e) => {
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && canSubmitRef.current) submitRef.current?.();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, []);

  const getMessageText = (index, fallback) => editedMessages[index] ?? fallback;

  const copyText = useMemo(() => {
    if (!results?.thank_you_messages?.length) return '';
    const messages = results.thank_you_messages.map((m, i) =>
      `${m.version}\n${getMessageText(i, m.message_text)}\n\n${m.choose_if || ''}`.trim()
    ).join('\n\n──────────\n\n');
    return `Thank-you for ${recipientName}\n\n${messages}${BRAND}`;
  }, [results, editedMessages, recipientName]);

  useRegisterActions(copyText, tool?.title || 'Gratitude Debt Clearer');

  const hasInput = !!(
    recipientName.trim() || gratitudePoints.trim() || extraContext.trim() ||
    relationship !== 'Friend' || tone !== 'Let DeftBrain choose' || length !== 'Moderate' ||
    results
  );

  const handleReset = () => {
    setRecipientName('');
    setGratitudePoints('');
    setRelationship('Friend');
    setTone('Let DeftBrain choose');
    setLength('Moderate');
    setExtraContext('');
    setShowOptions(false);
    setResults(null);
    setEditedMessages({});
    setEditingIndex(null);
    setError('');
  };

  const loadExample = () => {
    // pickExample(toolKey, list) — the key is what rotates the choice between
    // visits. Called with one argument it returns undefined and the handler
    // throws, so the button silently did nothing.
    const ex = pickExample('GratitudeDebtClearer', EXAMPLES);
    setRecipientName(ex.recipientName);
    setGratitudePoints(ex.gratitudePoints);
    setRelationship(ex.relationship);
    setTone('Let DeftBrain choose');
    setLength('Moderate');
    setExtraContext('');
    setResults(null);
    setEditedMessages({});
    setError('');
  };

  const generate = async () => {
    if (!recipientName.trim() || !gratitudePoints.trim()) {
      setError(!recipientName.trim() ? t('gdc_err_who') : t('gdc_err_what'));
      return;
    }
    setError('');
    try {
      const data = await callToolEndpoint('gratitude-debt-clearer', {
        recipientName: recipientName.trim(),
        gratitudePoints: gratitudePoints.trim(),
        relationship,
        tone,
        length,
        extraContext: extraContext.trim(),
        userLocale,
        userCurrency,
        userRegion,
      });
      setResults(data);
      setEditedMessages({});
      setEditingIndex(null);
      setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 50);
    } catch (err) {
      setError(err?.message || t('gdc_err_failed'));
    }
  };

  const adjust = async (index, adjustment) => {
    const message = results?.thank_you_messages?.[index];
    if (!message) return;
    setAdjustingIndex(index);
    setError('');
    try {
      const data = await callToolEndpoint('gratitude-debt-clearer', {
        recipientName,
        gratitudePoints,
        relationship,
        tone,
        length,
        extraContext,
        adjustmentPrompt: adjustment,
        originalMessage: getMessageText(index, message.message_text),
        userLocale,
        userCurrency,
        userRegion,
      });
      const adjusted = data?.thank_you_messages?.[0];
      if (adjusted?.message_text) {
        setEditedMessages(prev => ({ ...prev, [index]: adjusted.message_text }));
      }
    } catch (err) {
      setError(err?.message || t('gdc_err_adjust'));
    } finally {
      setAdjustingIndex(null);
    }
  };

  const fieldClass = `w-full rounded-xl border px-4 py-3 outline-none focus:ring-2 focus:ring-cyan-500/20 ${c.input}`;

  return (
    <div className={`max-w-3xl mx-auto space-y-4 ${c.text}`}>
      <section className={`rounded-2xl border p-5 sm:p-6 ${c.border} ${c.card}`}>
        <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3 border-b pb-5 mb-5 border-gray-300/40">
          <div>
            <h2 className={`font-semibold ${c.text}`}>
              <span className="me-2">{tool?.icon ?? '💝'}</span>
              {tool?.tagline ?? t('gdc_tagline')}
            </h2>
            <button
              type="button"
              onClick={loadExample}
              disabled={loading}
              style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }}
              className="mt-3 px-4 py-2 rounded-full text-sm font-semibold border border-black/20 text-zinc-900 hover:brightness-105 disabled:opacity-50"
            >
              ✨ {t('try_example')}
            </button>
          </div>
          {hasInput && (
            <button type="button" onClick={handleReset} className={`px-4 py-2 rounded-lg border text-sm font-semibold ${c.btnSecondary}`}>
              ↺ {t('start_over')}
            </button>
          )}
        </div>

        <div className="space-y-5">
          <div>
            <label className={`block font-semibold mb-2 ${c.text}`}>{t('gdc_who_thanking')} <span className={c.required}>*</span></label>
            <input
              value={recipientName}
              onChange={e => setRecipientName(e.target.value)}
              className={fieldClass}
              placeholder={t('gdc_ph_recipient')}
            />
          </div>

          <div>
            <label className={`block font-semibold mb-2 ${c.text}`}>{t('gdc_what_grateful')} <span className={c.required}>*</span></label>
            <textarea
              value={gratitudePoints}
              onChange={e => setGratitudePoints(e.target.value)}
              rows={6}
              className={fieldClass}
              placeholder={t('gdc_ph_gratitude')}
            />
            <p className={`mt-2 text-sm ${c.textMuted}`}>💡 {t('gdc_be_specific')}</p>
          </div>

          <div>
            <label className={`block font-semibold mb-2 ${c.text}`}>{t('gdc_your_relationship')}</label>
            <select value={relationship} onChange={e => setRelationship(e.target.value)} className={fieldClass}>
              {RELATIONSHIPS.map(r => <option key={r} value={r}>{r}</option>)}
            </select>
          </div>

          <button
            type="button"
            onClick={() => setShowOptions(v => !v)}
            className={`text-sm font-semibold ${c.accentTxt}`}
          >
            <Caret open={showOptions} /> Optional: make it fit better
          </button>

          {showOptions && (
            <div className={`rounded-xl border p-4 space-y-4 ${c.border} ${c.cardAlt}`}>
              <div>
                <label className={`block text-sm font-semibold mb-2 ${c.text}`}>{t('gdc_tone_preference')}</label>
                <select value={tone} onChange={e => setTone(e.target.value)} className={fieldClass}>
                  {TONES.map(v => <option key={v} value={v}>{v}</option>)}
                </select>
              </div>
              <div>
                <label className={`block text-sm font-semibold mb-2 ${c.text}`}>{t('gdc_msg_length')}</label>
                <select value={length} onChange={e => setLength(e.target.value)} className={fieldClass}>
                  {LENGTHS.map(v => <option key={v} value={v}>{v}</option>)}
                </select>
              </div>
              <div>
                <label className={`block text-sm font-semibold mb-2 ${c.text}`}>Anything else that should shape the message?</label>
                <textarea
                  value={extraContext}
                  onChange={e => setExtraContext(e.target.value)}
                  rows={3}
                  className={fieldClass}
                  placeholder="e.g., Keep it low-key; we don't usually get emotional. Or: This is for a formal note after an interview."
                />
              </div>
            </div>
          )}

          {error && <div className="rounded-lg border border-red-300 bg-red-50 text-red-800 px-4 py-3 text-sm">{error}</div>}

          <button
            type="button"
            onClick={generate}
            disabled={loading}
            style={{ backgroundColor: tool?.headerColor ?? '#0891b2' }}
            title={t('cmd_enter')}
            className="relative w-full rounded-xl px-5 py-3 font-bold text-zinc-900 border border-black/20 hover:brightness-105 disabled:opacity-50 flex items-center justify-center"
          >
            {loading
              ? <><span className="animate-spin inline-block me-1">{tool?.icon ?? '💝'}</span>{t('gdc_crafting')}</>
              : <><span className="me-1">{tool?.icon ?? '💝'}</span>{t('gdc_generate_messages')}</>}
            {!loading && (
              <kbd aria-hidden="true"
                className="hidden sm:flex items-center absolute end-3 top-1/2 -translate-y-1/2 px-1.5 py-0.5 rounded border border-black/25 bg-black/10 text-[10px] font-bold tracking-wide">
                ⌘↵
              </kbd>
            )}
          </button>
        </div>
      </section>

      {!results && (
        <p className={`text-center text-sm ${c.textMuted}`}>
          {t('gdc_xref_pre')}{' '}
          <a href="/Mend" className={linkStyle}>{t('gdc_xref_mend')}</a>
        </p>
      )}

      {results && (
        <section ref={resultsRef} className="space-y-4 scroll-mt-4">
          <div>
            <h2 className={`text-2xl font-bold ${c.text}`}>{t('gdc_your_messages')}</h2>
            <p className={`mt-1 ${c.textSecondary}`}>Three different ways to say the same true thing. Pick the one that sounds most like you.</p>
          </div>

          {(results.thank_you_messages || []).map((message, index) => {
            const text = getMessageText(index, message.message_text);
            const editing = editingIndex === index;
            const adjusting = adjustingIndex === index;
            return (
              <article key={`${message.version}-${index}`} className={`rounded-2xl border p-5 ${c.border} ${c.card}`}>
                <div className="flex flex-wrap items-center justify-between gap-2 mb-3">
                  <h3 className={`text-lg font-bold ${c.text}`}>{message.version}</h3>
                  {message.feel && <span className={`text-sm ${c.textMuted}`}>{message.feel}</span>}
                </div>

                {message.choose_if && (
                  <div className={`rounded-lg border px-3 py-2 mb-4 text-sm ${c.accentSoft} ${c.textSecondary}`}>
                    <strong className={c.text}>Choose this if:</strong> {message.choose_if}
                  </div>
                )}

                {editing ? (
                  <textarea
                    value={text}
                    onChange={e => setEditedMessages(prev => ({ ...prev, [index]: e.target.value }))}
                    rows={7}
                    className={fieldClass}
                  />
                ) : (
                  <div className={`rounded-xl border p-4 whitespace-pre-wrap leading-relaxed ${c.border} ${c.cardAlt} ${c.text}`}>{text}</div>
                )}

                <div className="flex flex-wrap gap-2 mt-4">
                  <button type="button" onClick={() => setEditingIndex(editing ? null : index)} className={`px-3 py-2 rounded-lg border text-sm font-semibold ${c.btnSecondary}`}>
                    ✏ {editing ? t('gdc_done_editing') : t('gdc_edit')}
                  </button>
                  <button type="button" disabled={adjusting} onClick={() => adjust(index, 'Make it less emotional and less mushy. Keep every factual detail grounded in the user input.')} className={`px-3 py-2 rounded-lg border text-sm font-semibold ${c.btnSecondary} disabled:opacity-50`}>
                    − {t('gdc_too_mushy')}
                  </button>
                  <button type="button" disabled={adjusting} onClick={() => adjust(index, 'Make it more specific using ONLY details the user supplied. Do not invent any new facts, history, feelings, habits, or relationship details.')} className={`px-3 py-2 rounded-lg border text-sm font-semibold ${c.btnSecondary} disabled:opacity-50`}>
                    + {t('gdc_more_specific')}
                  </button>
                  <button type="button" disabled={adjusting} onClick={() => adjust(index, 'Make this sound more natural and conversational, like something an ordinary person would actually send. Preserve the meaning and do not invent details.')} className={`px-3 py-2 rounded-lg border text-sm font-semibold ${c.btnSecondary} disabled:opacity-50`}>
                    More like me
                  </button>
                </div>
              </article>
            );
          })}

          {results.personalization_prompt && (
            <details className={`rounded-xl border p-4 ${c.border} ${c.card}`}>
              <summary className={`cursor-pointer font-semibold ${c.text}`}>Make it even more personal</summary>
              <p className={`mt-3 ${c.textSecondary}`}>{results.personalization_prompt}</p>
            </details>
          )}

          <p className={`text-center text-sm ${c.textMuted}`}>
            {t('gdc_xref_post')}{' '}
            <a href="/Mend" className={linkStyle}>{t('gdc_xref_mend')}</a>
          </p>
        </section>
      )}
    </div>
  );
};

GratitudeDebtClearer.displayName = 'GratitudeDebtClearer';
export default GratitudeDebtClearer;
