import React, { useState, useEffect, useRef, useCallback } from 'react';
import { useTheme } from '../hooks/useTheme';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useRegisterActions } from '../components/ActionBarContext';
import { usePersistentState } from '../hooks/usePersistentState';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

const TARGET_TYPES = [
  { id: 'mentor', label: '🧭 Mentor', icon: '🧭' },
  { id: 'investor', label: '💰 Investor', icon: '💰' },
  { id: 'collaborator', label: '🤝 Collaborator', icon: '🤝' },
  { id: 'employer', label: '💼 Employer / Hiring Manager', icon: '💼' },
  { id: 'friend', label: '👥 Friend', icon: '👥' },
  { id: 'partner', label: '❤️ Partner', icon: '❤️' },
  { id: 'client', label: '📦 Client', icon: '📦' },
  { id: 'connector', label: '🌐 Super-connector', icon: '🌐' },
];

const PHASE_COLORS = [
  { border: 'border-amber-500', bg: (d) => d ? 'bg-amber-900/10' : 'bg-amber-50', text: (d) => d ? 'text-amber-300' : 'text-amber-800' },
  { border: 'border-cyan-600', bg: (d) => d ? 'bg-cyan-900/10' : 'bg-cyan-50', text: (d) => d ? 'text-cyan-300' : 'text-cyan-800' },
  { border: 'border-emerald-500', bg: (d) => d ? 'bg-emerald-900/10' : 'bg-emerald-50', text: (d) => d ? 'text-emerald-300' : 'text-emerald-800' },
];

const GravityWell = ({ tool }) => {
  const { callToolEndpoint, loading } = useClaudeAPI();
  const { isDark } = useTheme();


  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-500' : 'text-gray-400',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-200 text-red-800',
    infoBox:       isDark ? 'bg-sky-900/20 border-sky-700 text-sky-200' : 'bg-sky-50 border-sky-200 text-sky-800',
    successBox:    isDark ? 'bg-emerald-900/20 border-emerald-700' : 'bg-emerald-50 border-emerald-300',
    successTxt:    isDark ? 'text-emerald-300' : 'text-emerald-800',
    warningBox:    isDark ? 'bg-amber-900/20 border-amber-700' : 'bg-amber-50 border-amber-300',
    warningTxt:    isDark ? 'text-amber-300' : 'text-amber-800',
    pillActive:    isDark ? 'border-cyan-500 bg-cyan-900/30 text-cyan-200' : 'border-cyan-600 bg-cyan-100 text-cyan-900',
    pillInactive:  isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500' : 'border-gray-300 text-gray-500 hover:border-gray-400',
    required:      isDark ? 'text-amber-400' : 'text-amber-500',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-600 hover:text-cyan-700 underline underline-offset-2';

  const [targetDescription, setTargetDescription] = usePersistentState('gw-target-desc', '');
  const [history, setHistory] = usePersistentState('gravitywell-history', []);
  const [targetType, setTargetType] = useState('');
  const [whyThemContext, setWhyThemContext] = useState('');
  const [yourBackground, setYourBackground] = useState('');
  const resultsRef = React.useRef(null);
  const [results, setResults] = useState(null);
  const [error, setError] = useState('');
  const [expanded, setExpanded] = useState({ profile: false, value: false });
  const toggle = (k) => setExpanded(p => ({ ...p, [k]: !p[k] }));

  const handleSubmit = async () => {
    if (!targetDescription.trim()) return;
    setError(''); setResults(null);
    try {
      const data = await callToolEndpoint('gravity-well', {
        targetDescription: targetDescription.trim(),
        targetType: targetType || undefined,
        whyThemContext: whyThemContext.trim() || undefined,
        yourBackground: yourBackground.trim() || undefined,
      });
      setResults(data);
      setHistory(prev => [{ id: Date.now(), date: new Date().toISOString(), preview: (data.the_90_day_plan?.phase_1?.theme || targetDescription).slice(0, 40) }, ...prev].slice(0, 6));
    } catch (e) { setError(e.message || 'Failed to design gravity strategy.'); }
  };

  const buildFullText = useCallback(() => {
    if (!results) return '';
    let t = `🌀 GRAVITY WELL — 90-DAY ORBIT STRATEGY\n\nTarget: ${targetDescription}\nCurrent gravity: ${results.your_gravity_score?.current}\n\n`;
    ['phase_1', 'phase_2', 'phase_3'].forEach(ph => {
      const p = results.the_90_day_plan?.[ph];
      if (!p) return;
      t += `${p.name}\n${p.objective}\n`;
      p.actions?.forEach(a => { t += `• ${a.action} (${a.platform_or_venue})\n`; });
      t += '\n';
    });
    if (results.the_first_contact?.what_to_say) t += `FIRST CONTACT:\n${results.the_first_contact.what_to_say}\n\n`;
    if (results.the_one_thing_today) t += `DO TODAY: ${results.the_one_thing_today}\n`;
    return t + BRAND;
  }, [results, targetDescription]);

  useRegisterActions(buildFullText(), tool?.title || 'Gravity Well');

  const handleSubmitRef = useRef(null);
  const canSubmitRef = useRef(false);
  handleSubmitRef.current = handleSubmit;
  canSubmitRef.current = !!targetDescription.trim();

  useEffect(() => {
    if (!results || !resultsRef.current) return;
    const t = setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 200);
    return () => clearTimeout(t);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [results]);

  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if ((e.metaKey || e.ctrlKey) && e.key === 'Enter' && !loading && canSubmitRef.current) {
        e.preventDefault();
        handleSubmitRef.current?.();
      }
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading]);

  const plan = results?.the_90_day_plan;
  const phases = plan ? [
    { key: 'phase_1', data: plan.phase_1, cfg: PHASE_COLORS[0] },
    { key: 'phase_2', data: plan.phase_2, cfg: PHASE_COLORS[1] },
    { key: 'phase_3', data: plan.phase_3, cfg: PHASE_COLORS[2] },
  ] : [];

  return (
    <div className={`space-y-4 ${c.text}`}>

      {/* ── Persistent Header ── */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm`}>
        <div className="px-5 pt-5">
          <div className="pb-3 border-b border-zinc-500">
            <h2 className={`text-xl font-bold ${c.text}`}>
              <span className="mr-2">{tool?.icon ?? '🌀'}</span>{tool?.title ?? 'Gravity Well'}
            </h2>
            <p className={`text-sm ${c.textSecondary}`}>{tool?.tagline ?? "A 90-day plan to naturally enter someone's orbit."}</p>
          </div>
        </div>
      </div>

        {!results && (
          <div className={`rounded-2xl border p-6 shadow-sm space-y-4 ${c.card} ${c.border}`}>
            <div>
              <label className={`block text-sm font-semibold mb-1.5 ${c.text}`}>
                Describe the person you want in your life <span className={c.required}>*</span>
              </label>
              <textarea value={targetDescription} onChange={e => setTargetDescription(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && targetDescription.trim()) handleSubmit(); }}
                placeholder="Their role, what they're known for, what world they operate in — specific enough to design a real strategy…"
                rows={3} maxLength={500}
                className={`w-full px-4 py-3 rounded-xl border text-sm resize-none ${c.input}`} />
            </div>

            <div>
              <label className={`block text-sm font-semibold mb-2 ${c.text}`}>Type of relationship<br /><span className={`font-normal ${c.textMuteded}`}>(optional)</span></label>
              <div className="flex flex-wrap gap-2">
                {TARGET_TYPES.map(t => (
                  <button key={t.id} onClick={() => setTargetType(targetType === t.id ? '' : t.id)}
                    className={`px-3 py-1.5 rounded-lg text-xs font-semibold border transition-all ${
                      targetType === t.id ? 'bg-cyan-700 text-white border-cyan-700' : c.btnSecondary
                    }`}>
                    {t.label}
                  </button>
                ))}
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className={`block text-sm font-semibold mb-1.5 ${c.text}`}>Why this person? <span className={`font-normal ${c.textMuteded}`}>(optional)</span></label>
                <textarea value={whyThemContext} onChange={e => setWhyThemContext(e.target.value)}
                  placeholder="What you'd learn from them, why they specifically…"
                  rows={2} maxLength={300}
                  className={`w-full px-4 py-3 rounded-xl border text-sm resize-none ${c.input}`} />
              </div>
              <div>
                <label className={`block text-sm font-semibold mb-1.5 ${c.text}`}>Your background / what you bring <span className={`font-normal ${c.textMuteded}`}>(optional)</span></label>
                <textarea value={yourBackground} onChange={e => setYourBackground(e.target.value)}
                  placeholder="Skills, work, perspective — what makes you worth knowing…"
                  rows={2} maxLength={300}
                  className={`w-full px-4 py-3 rounded-xl border text-sm resize-none ${c.input}`} />
              </div>
            </div>

            {error && <div className={`p-3 rounded-xl border text-sm ${c.danger}`}><span className="mr-1">⚠️</span>{error}</div>}

            <button onClick={handleSubmit} disabled={loading || !targetDescription.trim()}
              className={`w-full py-3 rounded-xl font-bold disabled:opacity-40 ${c.btnPrimary}`}>
              {loading ? <><span className="animate-spin inline-block mr-2">{tool?.icon ?? '🌀'}</span>Designing your orbit strategy…</> : <><span className="mr-1">{tool?.icon ?? '🌀'}</span>Build My Gravity Strategy</>}
            </button>

            <p className={`text-xs text-center ${c.textMuteded}`}>Not cold outreach. Gravitational pull — so when you finally connect, they already know who you are.</p>

            <div className={`rounded-xl border p-4 ${c.cardAlt} ${c.border}`}>
              <p className={`text-[10px] font-bold ${c.textMuted} uppercase mb-2`}>🔗 Related tools</p>
              <div className="flex flex-wrap gap-3">
                <a href="/VelvetHammer" className={`text-xs ${linkStyle}`}>🔨 Velvet Hammer</a>
                <a href="/HecklerPrep" className={`text-xs ${linkStyle}`}>🎤 HecklerPrep</a>
                <a href="/LuckSurface" className={`text-xs ${linkStyle}`}>🧲 Luck Surface</a>
              </div>
            </div>
          </div>
        )}

        {results && (
          <div className="space-y-4">

            {/* Gravity score */}
            {results.your_gravity_score && (
              <div className={`rounded-2xl border p-5 ${c.card} ${c.border}`}>
                <div className="flex items-center justify-between mb-3">
                  <p className={`text-xs font-black uppercase tracking-widest ${c.textMuteded}`}>Current Gravity Score</p>
                  <div className="text-right">
                    <span className={`text-3xl font-black ${isDark ? 'text-red-300' : 'text-red-700'}`}>{results.your_gravity_score.current}</span>
                    {results.gravity_score_target && (
                      <span className={`text-lg font-bold ml-2 ${isDark ? 'text-emerald-300' : 'text-emerald-700'}`}>→ {results.gravity_score_target}</span>
                    )}
                  </div>
                </div>
                <div className={`h-2.5 rounded-full mb-3 ${isDark ? 'bg-zinc-700' : 'bg-gray-200'}`}>
                  <div className="h-full rounded-full bg-gradient-to-r from-red-600 to-red-400" style={{ width: results.your_gravity_score.current }} />
                </div>
                <p className={`text-sm mb-2 ${c.textSecondary}`}>{results.your_gravity_score.the_gap}</p>
                {results.your_gravity_score.your_natural_advantages && (
                  <p className={`text-xs ${c.textMuteded}`}><span className="font-semibold">Your advantage:</span> {results.your_gravity_score.your_natural_advantages}</p>
                )}
              </div>
            )}

            {/* Target profile */}
            {results.target_profile && (
              <div className={`rounded-2xl border overflow-hidden ${c.card} ${c.border}`}>
                <button onClick={() => toggle('profile')} className="w-full text-left px-5 py-4 flex items-center justify-between">
                  <p className={`text-xs font-bold uppercase tracking-wider ${c.textMuteded}`}>🎯 Understanding Their World</p>
                  <span className={`text-sm ${c.textMuteded}`}>{expanded.profile ? '▲' : '▼'}</span>
                </button>
                {expanded.profile && (
                  <div className={`px-5 pb-5 space-y-2 border-t ${c.border} pt-4`}>
                    {[
                      { key: 'what_they_care_about', label: 'What they care about' },
                      { key: 'what_gets_their_attention', label: 'What breaks through their noise' },
                      { key: 'what_they_avoid', label: 'What marks you as not worth their time' },
                      { key: 'their_world', label: 'Where they already exist' },
                    ].map(row => results.target_profile[row.key] && (
                      <p key={row.key} className={`text-sm ${c.textSecondary}`}>
                        <span className={`font-semibold ${c.text}`}>{row.label}:</span> {results.target_profile[row.key]}
                      </p>
                    ))}
                  </div>
                )}
              </div>
            )}

            {/* 90-day phases */}
            <p className={`text-xs font-black uppercase tracking-widest px-1 ${c.textMuteded}`}>📅 The 90-Day Plan</p>
            {phases.map(({ key, data, cfg }) => data && (
              <div key={key} className="rounded-2xl overflow-hidden border-2" style={{ borderColor: cfg.border }}>
                <div className={`px-5 py-4 ${cfg.bg(isDark)}`}>
                  <p className={`text-xs font-black uppercase tracking-widest mb-0.5 ${cfg.text(isDark)}`}>{data.name}</p>
                  <p className={`text-sm font-semibold ${c.text}`}>{data.objective}</p>
                </div>
                <div className={`px-5 py-4 space-y-3 ${c.card} ${c.border}`}>
                  {data.actions?.map((action, j) => (
                    <div key={j} className={`p-3 rounded-xl border ${c.cardAlt} ${c.border}`}>
                      <p className={`text-sm font-semibold mb-0.5 ${c.text}`}>{action.action}</p>
                      {action.platform_or_venue && (
                        <p className={`text-xs ${c.textMuteded}`}><span className="font-semibold">Where:</span> {action.platform_or_venue}</p>
                      )}
                      {action.the_signal_it_sends && (
                        <p className={`text-xs italic mt-0.5 ${c.textMuteded}`}>Signal: {action.the_signal_it_sends}</p>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            ))}

            {/* First contact */}
            {results.the_first_contact && (
              <div className={`rounded-2xl border p-5 ${c.card} ${c.border}`}>
                <p className={`text-xs font-bold uppercase tracking-wider mb-3 ${c.textMuteded}`}>✉️ The First Contact</p>
                {results.the_first_contact.when_to_reach_out && (
                  <p className={`text-sm mb-2 ${c.textSecondary}`}><span className={`font-semibold ${c.text}`}>When to reach out:</span> {results.the_first_contact.when_to_reach_out}</p>
                )}
                {results.the_first_contact.the_frame && (
                  <p className={`text-sm mb-3 ${c.textSecondary}`}><span className={`font-semibold ${c.text}`}>The frame:</span> {results.the_first_contact.the_frame}</p>
                )}
                {results.the_first_contact.what_to_say && (
                  <div className={`p-3 rounded-xl border font-mono text-sm mb-2 ${isDark ? 'bg-zinc-900 border-zinc-700' : 'bg-slate-50 border-gray-200'} ${c.textSecondary}`}>
                    {results.the_first_contact.what_to_say}
                  </div>
                )}
                {results.the_first_contact.what_not_to_say && (
                  <p className={`text-xs ${isDark ? 'text-red-300' : 'text-red-700'}`}><span className="font-semibold">Don't say:</span> {results.the_first_contact.what_not_to_say}</p>
                )}

              </div>
            )}

            {/* Value offer */}
            {results.the_value_offer && (
              <div onClick={() => toggle('value')} className={`rounded-2xl border overflow-hidden ${c.card} ${c.border}`}>
                <button className="w-full text-left px-5 py-4 flex items-center justify-between">
                  <p className={`text-xs font-bold uppercase tracking-wider ${c.textMuteded}`}>🎁 The Value Offer</p>
                  <span className={`text-sm ${c.textMuteded}`}>{expanded.value ? '▲' : '▼'}</span>
                </button>
                {expanded.value && (
                  <div className={`px-5 pb-5 space-y-2 border-t ${c.border} pt-4`}>
                    {[
                      { key: 'what_you_can_give', label: 'What you can give' },
                      { key: 'why_its_genuine', label: 'Why it\'s genuine' },
                      { key: 'the_asymmetry', label: 'The asymmetry' },
                    ].map(row => results.the_value_offer[row.key] && (
                      <p key={row.key} className={`text-sm ${c.textSecondary}`}>
                        <span className={`font-semibold ${c.text}`}>{row.label}:</span> {results.the_value_offer[row.key]}
                      </p>
                    ))}
                  </div>
                )}
              </div>
            )}

            {/* Do today */}
            {results.the_one_thing_today && (
              <div className={`rounded-2xl border-2 p-5 ${isDark ? 'border-cyan-700 bg-cyan-900/10' : 'border-cyan-300 bg-cyan-50'}`}>
                <p className={`text-xs font-black uppercase tracking-widest mb-2 ${isDark ? 'text-cyan-300' : 'text-cyan-700'}`}>⚡ Do Today — First Step</p>
                <p className={`text-sm font-medium ${c.text}`}>{results.the_one_thing_today}</p>
              </div>
            )}

            <div className="flex items-center gap-3 flex-wrap">
              <button onClick={() => { setResults(null); setTargetDescription(''); setTargetType(''); setWhyThemContext(''); setYourBackground(''); }}
                className={`px-4 py-2 rounded-lg text-sm font-medium ${c.btnSecondary}`}>
                🔄 New Target
              </button>
            </div>

            <div className={`rounded-xl border p-4 ${c.cardAlt} ${c.border}`}>
              <p className={`text-[10px] font-bold ${c.textMuted} uppercase mb-2`}>🔗 Related tools</p>
              <div className="flex flex-wrap gap-3">
                <a href="/LuckSurface" className={`text-xs ${linkStyle}`}>🧲 Luck Surface</a>
                <a href="/VelvetHammer" className={`text-xs ${linkStyle}`}>🔨 Velvet Hammer</a>
                <a href="/HecklerPrep" className={`text-xs ${linkStyle}`}>🎤 HecklerPrep</a>
              </div>
            </div>
          </div>
        )}
      {/* Disclaimer */}
      <div className={`${c.cardAlt} border ${c.border} rounded-xl p-3 text-center`}>
        <p className={`text-xs ${c.textMuted}`}>
          AI-generated strategy — use your own judgement about timing and approach.
        </p>
      </div>

    </div>
  );
};

GravityWell.displayName = 'GravityWell';
export default GravityWell;
