import React, { useState, useEffect, useRef, useCallback } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';
import { currencySymbol } from '../utils/formatLocale';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

const IDEA_STAGES = [
  { id: 'idea',      labelKey: 'ia_stage_idea',      icon: '💡' },
  { id: 'exploring', labelKey: 'ia_stage_exploring', icon: '🔭' },
  { id: 'building',  labelKey: 'ia_stage_building',  icon: '🔨' },
  { id: 'launched',  labelKey: 'ia_stage_launched',  icon: '🚀' },
];

const FOCUS_AREAS = [
  { id: 'market',      labelKey: 'ia_focus_market' },
  { id: 'competition', labelKey: 'ia_focus_competition' },
  { id: 'business',    labelKey: 'ia_focus_business' },
  { id: 'timing',      labelKey: 'ia_focus_timing' },
  { id: 'execution',   labelKey: 'ia_focus_execution' },
  { id: 'founder',     labelKey: 'ia_focus_founder' },
  { id: 'moat',        labelKey: 'ia_focus_moat' },
  { id: 'regulation',  labelKey: 'ia_focus_regulation' },
];

const EXAMPLE = {
  ideaStage: 'exploring',
  focusAreas: ['market', 'competition', 'business', 'execution'],
};

const RISK_LEVELS = {
  critical: { icon: '💀', labelKey: 'ia_risk_critical', bg: isDark => isDark ? 'bg-red-900/30 border-red-700' : 'bg-red-50 border-red-300', txt: isDark => isDark ? 'text-red-300' : 'text-red-800' },
  high:     { icon: '🚨', labelKey: 'ia_risk_high',     bg: isDark => isDark ? 'bg-orange-900/30 border-orange-700' : 'bg-orange-50 border-orange-300', txt: isDark => isDark ? 'text-orange-300' : 'text-orange-800' },
  medium:   { icon: '⚠️',  labelKey: 'ia_risk_medium',  bg: isDark => isDark ? 'bg-amber-900/30 border-amber-700' : 'bg-amber-50 border-amber-300', txt: isDark => isDark ? 'text-amber-300' : 'text-amber-800' },
  low:      { icon: '✅',  labelKey: 'ia_risk_low',     bg: isDark => isDark ? 'bg-emerald-900/30 border-emerald-700' : 'bg-emerald-50 border-emerald-300', txt: isDark => isDark ? 'text-emerald-300' : 'text-emerald-800' },
};

function IdeaAutopsy({ tool }) {
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();
  const sym = currencySymbol(userLocale, userCurrency);

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20'
                          : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-400' : 'text-gray-500',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white'
                          : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200'
                          : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    pillActive:    isDark ? 'border-cyan-500 bg-cyan-900/30 text-cyan-200'
                          : 'border-cyan-600 bg-cyan-100 text-cyan-900',
    pillInactive:  isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500'
                          : 'border-gray-300 text-gray-500 hover:border-gray-400',
    required:      isDark ? 'text-amber-400' : 'text-amber-700',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200'   : 'bg-red-50 border-red-200 text-red-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    infoBox:       isDark ? 'bg-sky-900/20 border-sky-700 text-sky-200'   : 'bg-sky-50 border-sky-200 text-sky-800',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';

  const [ideaStage, setIdeaStage]           = useState('idea');
  const [ideaDescription, setIdeaDescription] = useState('');
  const [founderContext, setFounderContext] = useState('');
  const [focusAreas, setFocusAreas]         = useState([]);
  const [results, setResults]               = usePersistentState('ideaautopsy-results', null);
  const [sessionHistory, setSessionHistory]               = usePersistentState('ideaautopsy-history', []);
  const [error, setError]                   = useState('');
  const [activeTab, setActiveTab]           = useState('risks');

  const resultsRef    = useRef(null);
  const handleRunRef  = useRef(null);
  const canSubmitRef  = useRef(false);

  const canSubmit = ideaDescription.trim().length >= 30;

  const handleReset = useCallback(() => {
    setResults(null);
    setError('');
    setIdeaStage('idea');
    setIdeaDescription('');
    setFounderContext('');
    setFocusAreas([]);
    setActiveTab('risks');
  }, [setResults]);

  const loadExample = useCallback(() => {
    setIdeaStage(EXAMPLE.ideaStage);
    setIdeaDescription(t('ia_ex_desc'));
    setFounderContext(t('ia_ex_founder', { sym }));
    setFocusAreas(EXAMPLE.focusAreas);
    setResults(null);
    setError('');
  }, [setResults, t, sym]);

  const toggleFocus = useCallback(id =>
    setFocusAreas(prev => prev.includes(id) ? prev.filter(f => f !== id) : [...prev, id]), []);

  const handleRun = useCallback(async () => {
    if (!canSubmit || loading) return;
    setError('');
    setResults(null);
    setActiveTab('risks');

    try {
      const parsed = await callToolEndpoint('idea-autopsy/stream', {
        ideaDescription: ideaDescription.trim(),
        ideaStage,
        founderContext: founderContext.trim() || null,
        focusAreas,
        userLocale,
        userCurrency,
        userRegion,
      });
      setResults(parsed);
      // PF-25 exception: 80 is an idea-description preview length, not a history cap.
      setSessionHistory(prev => [{
        preview: ideaDescription.slice(0, 80) + (ideaDescription.length > 80 ? '…' : ''),
        verdict: parsed.verdict ?? null,
        score:   parsed.viability_score ?? null,
        ts:      Date.now(),
      }, ...prev].slice(0, 6));
    } catch (err) {
      setError(err.message || t('ia_error'));
    }
  }, [canSubmit, loading, ideaDescription, ideaStage, founderContext, focusAreas, callToolEndpoint, setResults, setSessionHistory, userLocale, userCurrency, userRegion, t]);

  handleRunRef.current = handleRun;
  canSubmitRef.current = canSubmit;

  const buildFullText = useCallback(() => {
    if (!results) return '';
    const lines = [t('ia_copy_header'), ''];
    if (results.viability_score != null) lines.push(`${t('ia_copy_score')} ${results.viability_score}/10 — ${results.verdict ?? ''}`);
    if (results.one_liner) lines.push(`\n${results.one_liner}`);
    if (results.risks?.length) {
      lines.push(`\n${t('ia_copy_failures')}`);
      results.risks.forEach(r => {
        const lvlLabel = RISK_LEVELS[r.risk_level]?.labelKey ? t(RISK_LEVELS[r.risk_level].labelKey) : (r.risk_level ?? '');
        lines.push(`\n[${lvlLabel}] ${r.title}`);
        lines.push(r.description);
        if (r.mitigation) lines.push(`${t('ia_copy_mitigation')} ${r.mitigation}`);
      });
    }
    if (results.strengths?.length) {
      lines.push(`\n${t('ia_copy_strengths')}`);
      results.strengths.forEach(s => lines.push(`• ${s}`));
    }
    if (results.kill_questions?.length) {
      lines.push(`\n${t('ia_copy_questions')}`);
      results.kill_questions.forEach((q, i) => lines.push(`${i + 1}. ${q}`));
    }
    if (results.next_steps?.length) {
      lines.push(`\n${t('ia_copy_next')}`);
      results.next_steps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
    }
    lines.push(BRAND);
    return lines.join('\n');
  }, [results, t]);

  useRegisterActions(buildFullText(), tool?.title || 'IdeaAutopsy');

  useEffect(() => {
    if (!results || !resultsRef.current) return;
    const timer = setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 200);
    return () => clearTimeout(timer);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [results]);

  useEffect(() => {
    const handler = (e) => {
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && !loading && canSubmitRef.current)
        handleRunRef.current?.();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading]);

  const scoreColor = score => {
    if (score >= 7) return isDark ? 'text-emerald-400' : 'text-emerald-600';
    if (score >= 5) return isDark ? 'text-amber-400' : 'text-amber-600';
    return isDark ? 'text-red-400' : 'text-red-600';
  };

  const TABS = [
    { id: 'risks',     label: t('ia_tab_risks') },
    { id: 'strengths', label: t('ia_tab_strengths') },
    { id: 'questions', label: t('ia_tab_questions') },
    { id: 'next',      label: t('ia_tab_next') },
  ];

  const renderInput = () => (
    <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5 space-y-4`}>

      {/* Stage */}
      <div>
        <label className={`block text-sm font-medium ${c.labelText} mb-2`}>{t('ia_stage_label')}</label>
        <div className="flex flex-wrap gap-2">
          {IDEA_STAGES.map(s => (
            <button key={s.id} onClick={() => setIdeaStage(s.id)}
              className={`px-3 py-1.5 rounded-lg border text-xs font-medium transition-colors ${ideaStage === s.id ? c.pillActive : c.pillInactive}`}>
              <span className="mr-1">{s.icon}</span>{t(s.labelKey)}
            </button>
          ))}
        </div>
      </div>

      {/* Idea description */}
      <div>
        <label className={`block text-sm font-medium ${c.labelText} mb-1`}>
          {t('ia_desc_label')} <span className={c.required}>*</span>
        </label>
        <textarea
          value={ideaDescription}
          onChange={e => setIdeaDescription(e.target.value)}
          placeholder={t('ia_desc_ph')}
          rows={5}
          className={`w-full px-3 py-2.5 border rounded-xl text-sm resize-y focus:outline-none focus:ring-2 ${c.input}`}
        />
      </div>

      {/* Founder context */}
      <div>
        <label className={`block text-sm font-medium ${c.labelText} mb-1`}>
          {t('ia_founder_label')} <span className={`text-xs font-normal ${c.textMuted}`}>{t('ia_founder_hint')}</span>
        </label>
        <textarea
          value={founderContext}
          onChange={e => setFounderContext(e.target.value)}
          placeholder={t('ia_founder_ph')}
          rows={3}
          className={`w-full px-3 py-2.5 border rounded-xl text-sm resize-y focus:outline-none focus:ring-2 ${c.input}`}
        />
      </div>

      {/* Focus areas */}
      <div>
        <label className={`block text-sm font-medium ${c.labelText} mb-2`}>
          {t('ia_focus_label')} <span className={`text-xs font-normal ${c.textMuted}`}>{t('ia_focus_hint')}</span>
        </label>
        <div className="flex flex-wrap gap-2">
          {FOCUS_AREAS.map(fa => (
            <button key={fa.id} onClick={() => toggleFocus(fa.id)}
              className={`px-3 py-1.5 rounded-lg border text-xs font-medium transition-colors ${focusAreas.includes(fa.id) ? c.pillActive : c.pillInactive}`}>
              {t(fa.labelKey)}
            </button>
          ))}
        </div>
      </div>

      {error && <p className={`text-sm ${c.danger} border rounded-lg px-3 py-2`}>{error}</p>}

      <p className={`text-xs ${c.textMuted}`}>
        {t('ia_xref_pitch')} <a href="/PreMortem" className={linkStyle}>🪦 {t('ia_premortem')}</a> {t('ia_xref_pitch_after')}
      </p>

      <button onClick={handleRun} disabled={!canSubmit || loading}
        className={`w-full ${c.btnPrimary} disabled:opacity-40 font-bold py-3 rounded-lg flex items-center justify-center gap-2 min-h-[48px]`}>
        {loading
          ? <><span className="inline-block animate-spin">{tool?.icon ?? '🔬'}</span> {t('ia_running')}</>
          : <><span className="mr-1">{tool?.icon ?? '🔬'}</span> {t('ia_run')}</>}
      </button>

      {sessionHistory.length > 0 && (
        <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
          <div className="flex items-center justify-between mb-3">
            <p className={`text-xs font-bold ${c.textMuted} uppercase tracking-wide`}>🕓 {t('ia_prev')}</p>
            <button onClick={() => setSessionHistory([])} className={`text-xs ${c.textMuted}`}>{t('ia_clear')}</button>
          </div>
          <ul className="space-y-1.5">
            {sessionHistory.map((h, i) => (
              <li key={i} className={`text-xs ${c.textSecondary} flex items-start gap-2`}>
                {h.score != null && <span className={`font-bold flex-shrink-0 ${scoreColor(h.score)}`}>{h.score}/10</span>}
                <span className={c.textMuted}>{h.preview}</span>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );

  const renderResults = () => {
    if (!results) return null;
    return (
      <div className="space-y-4" ref={resultsRef}>

        {/* Verdict banner */}
        <div className={`${c.card} border ${c.border} rounded-xl p-5`}>
          <div className="flex items-start gap-4">
            {results.viability_score != null && (
              <div className="text-center flex-shrink-0">
                <p className={`text-4xl font-black ${scoreColor(results.viability_score)}`}>{results.viability_score}</p>
                <p className={`text-[10px] font-bold ${c.textMuted} uppercase`}>{t('ia_score_of')}</p>
              </div>
            )}
            <div className="flex-1">
              {results.verdict && <p className={`font-bold text-base ${c.text} mb-1`}>{results.verdict}</p>}
              {results.one_liner && <p className={`text-sm ${c.textSecondary}`}>{results.one_liner}</p>}
            </div>
          </div>
        </div>

        {/* Tab nav */}
        <div className={`${c.card} border ${c.border} rounded-xl overflow-hidden`}>
          <div className={`flex border-b ${c.border} overflow-x-auto`}>
            {TABS.map(tab => (
              <button key={tab.id} onClick={() => setActiveTab(tab.id)}
                className={`flex-1 min-w-max px-3 py-2.5 text-xs font-medium transition-colors whitespace-nowrap ${
                  activeTab === tab.id
                    ? isDark ? 'bg-zinc-700 text-zinc-50 border-b-2 border-cyan-500' : 'bg-slate-50 text-gray-900 border-b-2 border-cyan-600'
                    : `${c.textMuted} hover:${c.textSecondary}`
                }`}>
                {tab.label}
              </button>
            ))}
          </div>

          <div className="p-4 space-y-3">

            {/* Risks tab */}
            {activeTab === 'risks' && results?.risks?.map((risk, i) => {
              const cfg = RISK_LEVELS[risk.risk_level] ?? RISK_LEVELS.medium;
              return (
                <div key={i} className={`border rounded-xl p-4 ${cfg.bg(isDark)}`}>
                  <div className="flex items-center gap-2 flex-wrap mb-1">
                    <span className="text-base">{cfg.icon}</span>
                    <span className={`font-bold text-sm ${cfg.txt(isDark)}`}>{risk.title}</span>
                    <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full border ${cfg.bg(isDark)} ${cfg.txt(isDark)}`}>{t(cfg.labelKey)}</span>
                  </div>
                  <p className={`text-sm ${cfg.txt(isDark)} mb-2`}>{risk.description}</p>
                  {risk.mitigation && (
                    <p className={`text-xs ${cfg.txt(isDark)} opacity-80`}>
                      <span className="font-semibold">{t('ia_mitigation')}</span>{risk.mitigation}
                    </p>
                  )}
                </div>
              );
            })}

            {/* Strengths tab */}
            {activeTab === 'strengths' && (
              <ul className="space-y-2">
                {results?.strengths?.map((s, i) => (
                  <li key={i} className={`text-sm ${c.success} border rounded-lg px-3 py-2.5 flex gap-2`}>
                    <span className="flex-shrink-0">✅</span><span>{s}</span>
                  </li>
                ))}
              </ul>
            )}

            {/* Kill questions tab */}
            {activeTab === 'questions' && (
              <div className="space-y-2">
                <p className={`text-xs ${c.textMuted} mb-3`}>{t('ia_questions_intro')}</p>
                {results?.kill_questions?.map((q, i) => (
                  <div key={i} className={`text-sm ${c.warning} border rounded-lg px-3 py-2.5 flex gap-2`}>
                    <span className={`flex-shrink-0 font-bold ${c.accentTxt}`}>{i + 1}.</span><span>{q}</span>
                  </div>
                ))}
              </div>
            )}

            {/* Next steps tab */}
            {activeTab === 'next' && (
              <div className="space-y-2">
                <p className={`text-xs ${c.textMuted} mb-3`}>{t('ia_next_intro')}</p>
                {results?.next_steps?.map((s, i) => (
                  <div key={i} className={`text-sm ${c.infoBox} border rounded-lg px-3 py-2.5 flex gap-2`}>
                    <span className={`flex-shrink-0 font-bold ${c.accentTxt}`}>{i + 1}.</span><span>{s}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Post-result cross-refs */}
        <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
          <p className={`text-[10px] font-bold ${c.textMuted} uppercase mb-2`}>🔗 {t('ia_related')}</p>
          <div className="flex flex-wrap gap-3">
            <a href="/PreMortem" className={`text-xs ${linkStyle}`}>🪦 {t('ia_premortem')}</a>
            <a href="/LeverageLogic" className={`text-xs ${linkStyle}`}>⚖️ {t('ia_leverage')}</a>
          </div>
        </div>
      </div>
    );
  };

  return (
    <div className={`space-y-4 ${c.text}`}>
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5`}>
        <div className="flex items-start justify-between">
          <div>
            <h2 className={`text-xl font-bold ${c.text}`}>
              <span className="mr-2">{tool?.icon ?? '🔬'}</span>{tool?.title ?? t('ia_title')}
            </h2>
            <p className={`text-sm ${c.textSecondary}`}>{tool?.tagline ?? t('ia_tagline')}</p>
            <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className={`mt-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium border disabled:opacity-40 ${isDark ? 'text-white border-white/40' : 'text-gray-800 border-transparent'}`}>{t('try_example')}</button>
          </div>
          <button
            onClick={handleReset}
            style={{ visibility: (results || ideaDescription.trim()) ? 'visible' : 'hidden' }}
            className={`${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs font-bold`}
          >
            ↺ {t('ia_new')}
          </button>
        </div>
      </div>
      {!results && <p className={`text-xs ${c.textMuted} px-1`}>{t('ia_xref_pitch')} <a href="/PreMortem" className={linkStyle}>🪦 {t('ia_premortem')}</a> {t('ia_xref_pitch_after')}</p>}
      {!results && renderInput()}
      {results && renderResults()}
    </div>
  );
}

IdeaAutopsy.displayName = 'IdeaAutopsy';
export default IdeaAutopsy;
