import React, { useState, useEffect, useRef, useCallback } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

const DOC_TYPES = [
  { id: 'general', icon: '📄', labelKey: 'jarg_dt_general' }, { id: 'legal', icon: '⚖️', labelKey: 'jarg_dt_legal' },
  { id: 'medical', icon: '🏥', labelKey: 'jarg_dt_medical' }, { id: 'technical', icon: '🔧', labelKey: 'jarg_dt_technical' },
  { id: 'financial', icon: '💰', labelKey: 'jarg_dt_financial' }, { id: 'academic', icon: '🎓', labelKey: 'jarg_dt_academic' },
  { id: 'government', icon: '🏛️', labelKey: 'jarg_dt_government' }, { id: 'insurance', icon: '🛡️', labelKey: 'jarg_dt_insurance' },
];

const LEVELS = [
  { id: 'eli5', icon: '👶', labelKey: 'jarg_lvl_eli5', dKey: 'jarg_lvl_eli5_d' },
  { id: '5th-grade', icon: '📖', labelKey: 'jarg_lvl_5th', dKey: 'jarg_lvl_5th_d' },
  { id: '8th-grade', icon: '📝', labelKey: 'jarg_lvl_8th', dKey: 'jarg_lvl_8th_d' },
  { id: 'professional', icon: '💼', labelKey: 'jarg_lvl_pro', dKey: 'jarg_lvl_pro_d' },
];

const FLAG = { important: { i: '🚩', lKey: 'jarg_flag_important' }, decision: { i: '⚠️', lKey: 'jarg_flag_decision' }, red_flag: { i: '🔴', lKey: 'jarg_flag_red_flag' }, deadline: { i: '⏰', lKey: 'jarg_flag_deadline' } };
const DANGER = { safe: '✅', caution: '🟡', warning: '🟠', danger: '🔴' };

const JargonAssassin = ({ tool }) => {
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();
  const fileRef = useRef(null);
  const resultsRef = React.useRef(null);

  const c = {
    card:          isDark ? 'bg-zinc-800'     : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50'  : 'bg-slate-50',
    text:          isDark ? 'text-zinc-50'    : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300'   : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-500'   : 'text-gray-400',
    input:         isDark ? 'bg-zinc-700 border-zinc-600 text-zinc-100 placeholder-zinc-400' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-100' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-green-900/20 border-green-700 text-green-200' : 'bg-green-50 border-green-300 text-green-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-200 text-red-800',
    pillOn:        isDark ? 'bg-emerald-600 text-white' : 'bg-emerald-600 text-white',
    pillOff:       isDark ? 'bg-zinc-700 text-zinc-300 hover:bg-zinc-600' : 'bg-gray-100 text-gray-600 hover:bg-gray-200',
    accentCard:    isDark ? 'bg-emerald-900/20 border-emerald-700' : 'bg-emerald-50 border-emerald-200',
    highlight:     isDark ? 'bg-cyan-900/20 border-cyan-700 text-cyan-200' : 'bg-cyan-50 border-cyan-200 text-cyan-800',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    required:      isDark ? 'text-amber-400' : 'text-amber-500',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-600 hover:text-cyan-700 underline underline-offset-2';


  // ─── State ───
  const [mode, setMode] = useState('input');
  const [error, setError] = useState('');
  const [docText, setDocText] = useState('');
  const [docType, setDocType] = useState('general');
  const [readLevel, setReadLevel] = useState('5th-grade');
  const [fileName, setFileName] = useState('');
  const [fileBase64, setFileBase64] = useState(null);
  const [fileMediaType, setFileMediaType] = useState(null);
  const [results, setResults] = usePersistentState('jargon-results', null);
  const [activeTab, setActiveTab] = useState('translation');

  // Q&A
  const [question, setQuestion] = useState('');
  const [qaHistory, setQaHistory] = usePersistentState('ja-history', []);

  // Compare
  const [cmpT1, setCmpT1] = useState('');
  const [cmpT2, setCmpT2] = useState('');
  const [cmpData, setCmpData] = useState(null);

  // Section drill
  const [secData, setSecData] = useState(null);

  // Suggestions
  const [sugData, setSugData] = useState(null);

  // Explain To
  const [expAudience, setExpAudience] = useState('');
  const [expSection, setExpSection] = useState('');
  const [expData, setExpData] = useState(null);

  // Red-Line
  const [rlRole] = useState('');
  const [rlData, setRlData] = useState(null);

  // Template Compare
  const [tplContext] = useState('');
  const [tplData, setTplData] = useState(null);

  // Action Plan
  const [apSituation] = useState('');
  const [apData, setApData] = useState(null);

  // Dossier
  const [dossDocs, setDossDocs] = useState([{ title: '', text: '', type: 'general' }, { title: '', text: '', type: 'general' }]);
  const [dossData, setDossData] = useState(null);

  // Letter
  const [ltrIntent, setLtrIntent] = useState('');
  const [ltrPoints, setLtrPoints] = useState('');
  const [ltrTone, setLtrTone] = useState('professional but firm');
  const [ltrData, setLtrData] = useState(null);

  // Persistent
  const [savedDocs, setSavedDocs] = usePersistentState('jargon-assassin-saved', []);
  const [showSaved, setShowSaved] = useState(false);

  // ═══ HANDLERS ═══
  const handleFile = async (e) => {
    const f = e.target.files?.[0]; if (!f) return;
    setFileName(f.name); setError('');
    const isPdf = f.type === 'application/pdf' || f.name.toLowerCase().endsWith('.pdf');
    const isImg = f.type.startsWith('image/');
    if (!isPdf && !isImg && f.type !== 'text/plain' && !f.name.toLowerCase().endsWith('.txt')) {
      setError(t('jarg_err_filetype')); return;
    }
    if (isPdf || isImg) {
      const reader = new FileReader();
      reader.onload = (ev) => {
        const b64 = ev.target.result.split(',')[1];
        setFileBase64(b64);
        setFileMediaType(isPdf ? 'application/pdf' : f.type);
        setDocText('');
      };
      reader.readAsDataURL(f);
    } else {
      try { setDocText(await f.text()); setFileBase64(null); setFileMediaType(null); }
      catch { setError(t('jarg_err_read_file')); }
    }
  };

  const handleTranslate = async () => {
    if (!docText.trim() && !fileBase64) { setError(t('jarg_err_paste_upload')); return; }
    setError(''); setResults(null); setQaHistory([]); setSugData(null); setRlData(null); setTplData(null); setApData(null);
    const data = await callToolEndpoint('jargon-assassin', { documentText: docText, documentType: docType, readingLevel: readLevel, imageBase64: fileBase64 || null, mediaType: fileMediaType || null, userLocale, userCurrency, userRegion });
    if (data) { setResults(data); setActiveTab('translation'); setMode('results'); setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth' }), 100); }
  };

  const handleAsk = async () => {
    if (!question.trim()) return; setError('');
    const data = await callToolEndpoint('jargon-assassin-ask', { question, documentText: docText.substring(0, 8000), documentType: docType, translationSummary: results?.summary, readingLevel: readLevel, userLocale, userCurrency, userRegion });
    if (data) { setQaHistory(prev => [...prev, { q: question, a: data }]); setQuestion(''); }
  };

  const handleCompare = async () => {
    if (!cmpT1.trim() || !cmpT2.trim()) { setError(t('jarg_err_both_versions')); return; }
    setError(''); setCmpData(null);
    const data = await callToolEndpoint('jargon-assassin-compare', { text1: cmpT1, text2: cmpT2, documentType: docType, readingLevel: readLevel, userLocale, userCurrency, userRegion });
    if (data) setCmpData(data);
  };

  const handleSection = async (text) => {
    if (!text?.trim()) return; setError(''); setSecData(null);
    const data = await callToolEndpoint('jargon-assassin-section', { sectionText: text, documentType: docType, readingLevel: readLevel, fullDocumentContext: docText.substring(0, 3000), userLocale, userCurrency, userRegion });
    if (data) { setSecData(data); setMode('section'); }
  };

  const handleSuggest = async () => {
    setError('');
    const text = docText.trim() || results?.translation || '';
    const data = await callToolEndpoint('jargon-assassin-suggest', { documentText: text.substring(0, 6000), documentType: docType, translationSummary: results?.summary, userLocale, userCurrency, userRegion });
    if (data) setSugData(data);
  };

  const handleExplainTo = async () => {
    if (!expAudience.trim()) { setError(t('jarg_err_explain_who')); return; }
    setError('');
    const data = await callToolEndpoint('jargon-assassin-explain-to', { sectionText: expSection || results?.translation?.substring(0, 3000), audience: expAudience, translationSummary: results?.summary, documentType: docType, userLocale, userCurrency, userRegion });
    if (data) setExpData(data);
  };

  const handleRedLine = async () => {
    const text = docText.trim() || results?.translation?.substring(0, 8000);
    if (!text) { setError(t('jarg_err_translate_first')); return; }
    setError('');
    const data = await callToolEndpoint('jargon-assassin-redline', { documentText: text, documentType: docType, userRole: rlRole, userLocale, userCurrency, userRegion });
    if (data) setRlData(data);
  };

  const handleTemplate = async () => {
    const text = docText.trim() || results?.translation?.substring(0, 8000);
    if (!text) { setError(t('jarg_err_translate_first')); return; }
    setError('');
    const data = await callToolEndpoint('jargon-assassin-template', { documentText: text, documentType: docType, context: tplContext, userLocale, userCurrency, userRegion });
    if (data) setTplData(data);
  };

  const handleActionPlan = async () => {
    setError('');
    const text = docText.trim() || results?.translation || '';
    const data = await callToolEndpoint('jargon-assassin-action-plan', { documentText: text.substring(0, 5000), documentType: docType, translationSummary: results?.summary, keySections: results?.key_sections?.slice(0, 5), userSituation: apSituation, userLocale, userCurrency, userRegion });
    if (data) setApData(data);
  };

  const handleDossier = async () => {
    const valid = dossDocs.filter(d => d.text.trim());
    if (valid.length < 2) { setError(t('jarg_err_two_docs')); return; }
    setError(''); setDossData(null);
    const data = await callToolEndpoint('jargon-assassin-dossier', { documents: valid, userLocale, userCurrency, userRegion });
    if (data) setDossData(data);
  };

  const handleLetter = async () => {
    if (!ltrIntent.trim()) { setError(t('jarg_err_intent')); return; }
    setError('');
    const data = await callToolEndpoint('jargon-assassin-letter', { documentText: docText.substring(0, 5000), documentType: docType, intent: ltrIntent, specificPoints: ltrPoints, tone: ltrTone, userLocale, userCurrency, userRegion });
    if (data) setLtrData(data);
  };

  const saveDoc = () => { if (!results) return; setSavedDocs(prev => [{ title: fileName || results.summary?.substring(0, 50), docType, readLevel, summary: results.summary, danger: results.danger_score?.level, timestamp: new Date().toISOString(), results, docText: docText.substring(0, 500), preview: (fileName || docText || '').slice(0, 40) }, ...prev].slice(0, 6)); };

  const loadSaved = (s) => { setResults(s.results); setDocType(s.docType); setReadLevel(s.readLevel); setDocText(s.docText || ''); setMode('results'); setActiveTab('translation'); setQaHistory([]); setSugData(null); setRlData(null); setTplData(null); setApData(null); setShowSaved(false); };

  const handleReset = () => { setMode('input'); setDocText(''); setFileName(''); setResults(null); setQaHistory([]); setSugData(null); setRlData(null); setTplData(null); setApData(null); setCmpData(null); setSecData(null); setExpData(null); setLtrData(null); setDossData(null); setError(''); };

  const loadExample = () => {
    setMode('input');
    setDocType('lease');
    setReadLevel('5th-grade');
    setFileName(''); setFileBase64(null); setFileMediaType(null);
    setDocText(t('jarg_example_doc'));
    setResults(null); setQaHistory([]); setSugData(null); setRlData(null);
    setTplData(null); setApData(null); setError('');
  };

  const handleTranslateRef = useRef(null);
  const canSubmitRef = useRef(false);
  const dossDocsInputRefs = useRef([]);
  const shouldFocusNewDossDocsRef = useRef(false);
  handleTranslateRef.current = handleTranslate;
  canSubmitRef.current = !!docText.trim() || !!fileBase64;

  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && !loading && canSubmitRef.current)
        handleTranslateRef.current?.();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading]);

  useEffect(() => {
    if (shouldFocusNewDossDocsRef.current) {
      const last = dossDocsInputRefs.current[dossDocs.length - 1];
      if (last) last.focus();
      shouldFocusNewDossDocsRef.current = false;
    }
  }, [dossDocs.length]);

  const buildFullText = useCallback(() => {
    if (!results) return '';
    let out = `🗡️ ${t('jarg_title')}\n\n📖 ${results.summary}\n📊 ${results.reading_level}\n\n${results.translation}\n`;
    if (results.glossary?.length) { out += `\n${t('jarg_glossary')}:\n`; results.glossary.forEach(g => { out += `• ${g.term}: ${g.definition}\n`; }); }
    if (results.checklist?.length) { out += `\n${t('jarg_before_sign')}:\n`; results.checklist.forEach(ch => { out += `☐ ${ch}\n`; }); }
    return out + BRAND;
  }, [results, t]);

  useRegisterActions(buildFullText(), tool?.title || 'Jargon Assassin');

  const Tab = ({ id, icon, label }) => <button onClick={() => setActiveTab(id)} className={`px-3 py-1.5 rounded-lg text-xs font-medium ${activeTab === id ? c.pillOn : c.pillOff}`}>{icon} {label}</button>;
  const PRI_COLORS = { 'must-change': c.danger, 'should-change': c.warning, 'nice-to-have': c.highlight };
  const VER_COLORS = { red_flag: c.danger, worse_than_usual: c.warning, unusual: c.warning, standard: c.cardAlt, better_than_usual: c.success };


  return (
    <div className={`space-y-4 ${c.text}`}>
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm`}>
        <div className="px-5 pt-5">
          <div className="flex items-start justify-between pb-3 border-b border-zinc-500">
            <div>
              <h2 className={`text-xl font-bold ${c.text}`}>
                <span className="mr-2">{tool?.icon ?? '🗡️'}</span>{tool?.title ?? t('jarg_title')}
              </h2>
              <p className={`text-sm ${c.textSecondary}`}>{tool?.tagline ?? t('jarg_tagline')}</p>
              <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className={`mt-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium border disabled:opacity-40 ${isDark ? 'text-white border-white/40' : 'text-gray-800 border-transparent'}`}>{t('try_example')}</button>
            </div>
            {(results || cmpData || dossData || docText.trim() || fileBase64) && (
              <button onClick={handleReset}
                className={`px-3 py-1.5 rounded-lg text-xs font-medium ${c.btnSecondary} border ${c.border} disabled:opacity-40`}>
                ↻ {t('jarg_reset')}
              </button>
            )}
          </div>
        </div>
        <p className={`text-xs ${c.textMuteded} px-5 pt-3`}>
          {t('jarg_pretool_q')} <a href="/VelvetHammer" className={linkStyle}>🔨 {t('jarg_xref_velvet')}</a>.
        </p>
        <div className="px-5 py-4">

      {/* Nav */}
      <div className="flex flex-wrap gap-1.5">
        {results && <button onClick={() => setMode('results')} className={`px-3 py-1.5 rounded-lg text-xs font-medium ${mode === 'results' ? c.pillOn : c.pillOff}`}>📖 {t('jarg_nav_results')}</button>}
        <button onClick={() => { setMode('compare'); setError(''); }} className={`px-3 py-1.5 rounded-lg text-xs font-medium ${mode === 'compare' ? c.pillOn : c.pillOff}`}>🔀 {t('jarg_nav_compare')}</button>
        <button onClick={() => { setMode('dossier'); setError(''); }} className={`px-3 py-1.5 rounded-lg text-xs font-medium ${mode === 'dossier' ? c.pillOn : c.pillOff}`}>📁 {t('jarg_nav_dossier')}</button>
        {results && <button onClick={() => { setMode('letter'); setError(''); }} className={`px-3 py-1.5 rounded-lg text-xs font-medium ${mode === 'letter' ? c.pillOn : c.pillOff}`}>✉️ {t('jarg_nav_letter')}</button>}
        <button onClick={() => setShowSaved(!showSaved)} className={`px-3 py-1.5 rounded-lg text-xs font-medium ${showSaved ? c.pillOn : c.pillOff}`}>💾 {t('jarg_nav_saved')}{savedDocs.length ? ` (${savedDocs.length})` : ''}</button>
      </div>
        </div>
      </div>

      {/* Saved */}
      {showSaved && <div className={`${c.card} ${c.border} border ${c.border} rounded-xl p-5 space-y-3`}>
        <h3 className={`font-bold ${c.text}`}>💾 {t('jarg_saved_title')}</h3>
        {savedDocs.length === 0 ? <p className={`text-sm ${c.textMuteded}`}>{t('jarg_saved_empty')}</p> : savedDocs.map((s, i) => <div key={i} className={`${c.cardAlt} rounded-lg p-3 flex items-start justify-between gap-2`}><div className="flex-1 cursor-pointer" onClick={() => loadSaved(s)}><div className="flex items-center gap-2"><p className={`text-sm font-bold ${c.text}`}>{s.title}</p>{s.danger && s.danger !== 'safe' && <span className="text-xs">{DANGER[s.danger]}</span>}</div><p className={`text-xs ${c.textMuteded}`}>{(() => { const dt = DOC_TYPES.find(d => d.id === s.docType); return dt ? `${dt.icon} ${t(dt.labelKey)}` : s.docType; })()} · {new Date(s.timestamp).toLocaleDateString()}</p></div><button onClick={() => setSavedDocs(prev => prev.filter((_, idx) => idx !== i))} className={`text-xs ${c.textMuteded}`}>🗑️</button></div>)}
      </div>}

      {/* ═══ INPUT ═══ */}
      {mode === 'input' && <div className={`${c.card} ${c.border} border ${c.border} rounded-xl p-5 space-y-5`}>
        <div><h3 className={`font-bold text-lg ${c.text}`}>🗡️ {t('jarg_input_heading')} <span className={c.required}>*</span></h3><p className={`text-sm ${c.textMuteded} mt-1`}>{t('jarg_input_sub')}</p></div>
        <div><p className={`text-xs font-bold ${c.text} mb-2`}>{t('jarg_doc_type')}</p><div className="flex flex-wrap gap-1.5">{DOC_TYPES.map(dt => <button key={dt.id} onClick={() => setDocType(dt.id)} className={`px-3 py-1.5 rounded-lg text-xs font-medium border ${docType === dt.id ? c.pillOn : `${c.pillOff} ${c.border}`}`}>{dt.icon} {t(dt.labelKey)}</button>)}</div></div>
        <div><p className={`text-xs font-bold ${c.text} mb-2`}>{t('jarg_reading_level')}</p><div className="grid grid-cols-2 sm:grid-cols-4 gap-2">{LEVELS.map(rl => <button key={rl.id} onClick={() => setReadLevel(rl.id)} className={`p-2 rounded-xl border text-center ${readLevel === rl.id ? `${c.accentCard} border-emerald-500` : `${c.cardAlt} ${c.border}`}`}><span className="text-lg">{rl.icon}</span><p className={`text-xs font-bold ${c.text}`}>{t(rl.labelKey)}</p><p className={`text-xs ${c.textMuteded}`}>{t(rl.dKey)}</p></button>)}</div></div>
        <div>
          <input ref={fileRef} type="file" accept=".txt,.pdf,.jpg,.jpeg,.png,.heic,image/*,application/pdf" onChange={handleFile} className="hidden" id="ja-f" />
          {fileName ? (
            <div className={`${c.cardAlt} border-2 ${fileBase64 ? (isDark ? 'border-emerald-600' : 'border-emerald-400') : c.border} rounded-xl p-3 flex items-center gap-3`}>
              <span className="text-2xl">{fileMediaType === 'application/pdf' ? '📑' : fileMediaType?.startsWith('image') ? '🖼️' : '📄'}</span>
              <div className="flex-1 min-w-0">
                <p className={`text-sm font-semibold truncate ${c.text}`}>{fileName}</p>
                <p className={`text-xs ${c.textMuted}`}>{fileBase64 ? (fileMediaType === 'application/pdf' ? t('jarg_file_pdf_ready') : t('jarg_file_img_ready')) : t('jarg_file_text_loaded')}</p>
              </div>
              <label htmlFor="ja-f" className={`px-2.5 py-1.5 rounded-lg text-xs font-bold cursor-pointer ${c.btnSecondary} flex-shrink-0`}>{t('jarg_change')}</label>
            </div>
          ) : (
            <label htmlFor="ja-f" className={`flex flex-col items-center gap-2 p-5 rounded-xl border-2 border-dashed cursor-pointer transition-colors ${isDark ? 'border-zinc-600 bg-zinc-800/50 hover:border-sky-500' : 'border-gray-300 bg-gray-50 hover:border-sky-400'}`}>
              <div className="flex gap-3 text-2xl">📄📑🖼️</div>
              <p className={`text-xs font-semibold ${c.textSecondary}`}>{t('jarg_upload_file')} <span className={c.textMuted}>{t('jarg_or_paste')}</span></p>
              <p className={`text-[10px] ${c.textMuted}`}>{t('jarg_file_types')}</p>
            </label>
          )}
        </div>
        <textarea value={docText} onChange={e => { setDocText(e.target.value); if (e.target.value) { setFileBase64(null); setFileMediaType(null); setFileName(''); } }} placeholder={fileBase64 ? t('jarg_ph_file') : t('jarg_ph_paste')} rows={fileBase64 ? 3 : 8} className={`w-full px-3 py-2 rounded-lg border text-sm font-mono ${c.input}`} />
        <div className="flex justify-between"><span className={`text-xs ${c.textMuteded}`}>{t('jarg_chars', { count: docText.length.toLocaleString() })}</span>{docText.length > 12000 && <span className={`text-xs ${c.danger} border rounded px-2 py-0.5`}>⚠️ {t('jarg_may_truncate')}</span>}</div>
        <div className="flex gap-2">
          <button onClick={handleTranslate} disabled={loading || (!docText.trim() && !fileBase64)} className={`flex-1 py-3 rounded-xl font-bold text-sm ${c.btnPrimary} disabled:opacity-40`}>{loading ? <><span className="inline-block animate-spin">{tool?.icon ?? '🗡️'}</span> {t('jarg_working')}</> : <><span className='mr-1'>{tool?.icon ?? '🗡️'}</span> {t('jarg_translate')}</>}</button>
        </div>
      </div>}

      {/* ═══ RESULTS ═══ */}
      {mode === 'results' && results && <div ref={resultsRef} className="space-y-4">
        {/* Summary + Danger */}
        <div className={`${c.accentCard} border rounded-xl p-5`}>
          <div className="flex items-start justify-between gap-3"><div className="flex-1"><h3 className={`font-bold ${c.textSecondary} text-sm`}>📖 {t('jarg_summary')}</h3><p className={`text-sm ${c.text} mt-1`}>{results.summary}</p></div><div className="flex flex-col items-end gap-1">{results.reading_level && <span className={`text-xs px-2 py-0.5 rounded-full ${c.highlight} border`}>📖 {results.reading_level}</span>}{results.danger_score && <span className={`text-xs px-2 py-0.5 rounded-full ${results.danger_score.level === 'safe' ? c.success : results.danger_score.level === 'caution' ? c.warning : c.danger} border`}>{DANGER[results.danger_score.level]} {results.danger_score.level}</span>}</div></div>
          {results.danger_score?.explanation && results.danger_score.level !== 'safe' && <p className={`text-xs ${c.textSecondary} mt-2`}>{results.danger_score.explanation}</p>}
        </div>

        {/* Actions */}
        <div className="flex flex-wrap gap-1.5">
          <button onClick={saveDoc} className={`px-3 py-1.5 rounded-lg text-xs font-bold ${c.btnSecondary} border ${c.border}`}>💾 {t('jarg_save')}</button>
          <button onClick={handleSuggest} disabled={loading} className={`px-3 py-1.5 rounded-lg text-xs font-bold ${c.btnSecondary} border ${c.border} disabled:opacity-40`}>{sugData ? `✅ ${t('jarg_questions')}` : `🤔 ${t('jarg_questions_to_ask')}`}</button>
          <button onClick={() => { setRlData(null); handleRedLine(); }} disabled={loading} className={`px-3 py-1.5 rounded-lg text-xs font-bold ${c.btnSecondary} border ${c.border} disabled:opacity-40`}>{rlData ? `✅ ${t('jarg_redline')}` : `✏️ ${t('jarg_redline')}`}</button>
          <button onClick={() => { setTplData(null); handleTemplate(); }} disabled={loading} className={`px-3 py-1.5 rounded-lg text-xs font-bold ${c.btnSecondary} border ${c.border} disabled:opacity-40`}>{tplData ? `✅ ${t('jarg_vs_normal')}` : `📊 ${t('jarg_vs_normal')}`}</button>
          <button onClick={() => { setApData(null); handleActionPlan(); }} disabled={loading} className={`px-3 py-1.5 rounded-lg text-xs font-bold ${c.btnSecondary} border ${c.border} disabled:opacity-40`}>{apData ? `✅ ${t('jarg_plan')}` : `📋 ${t('jarg_action_plan')}`}</button>

        </div>

        {/* Tabs */}
        <div className="flex flex-wrap gap-1.5">
          <Tab id="translation" icon="📖" label={t('jarg_tab_translation')} />
          <Tab id="side-by-side" icon="📑" label={t('jarg_tab_side')} />
          <Tab id="highlights" icon="🚩" label={t('jarg_tab_sections')} />
          <Tab id="glossary" icon="📚" label={t('jarg_tab_glossary')} />
          <Tab id="qa" icon="❓" label={`${t('jarg_tab_qa')}${qaHistory.length ? ` (${qaHistory.length})` : ''}`} />
          <Tab id="explain" icon="🗣️" label={t('jarg_tab_explain')} />
        </div>

        {/* Translation */}
        {activeTab === 'translation' && <div className={`${c.card} ${c.border} border ${c.border} rounded-xl p-5`}><h3 className={`font-bold ${c.text} mb-3`}>📖 {t('jarg_translation')}</h3><div className={`${c.accentCard} border rounded-lg p-4`}><p className={`${c.text} leading-relaxed whitespace-pre-wrap`}>{results.translation}</p></div>
          {results.jargon_highlights?.length > 0 && <div className="mt-3"><p className={`text-xs font-bold ${c.textSecondary} mb-1`}>🔤 {t('jarg_jargon_replaced')} ({results.jargon_highlights.length})</p><div className="flex flex-wrap gap-1.5">{results.jargon_highlights.map((j, i) => <span key={i} className={`text-xs px-2 py-0.5 rounded-full ${c.cardAlt} border ${c.border}`} title={`${j.location ? `📍 ${j.location} · ` : ''}→ ${j.replaced_with}`}><s className={c.textMuteded}>{j.original}</s> → {j.replaced_with}</span>)}</div></div>}
        </div>}

        {/* Side-by-Side */}
        {activeTab === 'side-by-side' && <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          <div className={`${c.card} ${c.border} border ${c.border} rounded-xl p-4`}><h3 className={`font-bold text-sm ${c.text} mb-2`}>{t('jarg_original')}</h3><div className={`${c.cardAlt} rounded-lg p-3 max-h-96 overflow-y-auto`}>{docText ? <pre className={`whitespace-pre-wrap font-sans ${c.textSecondary}`}>{docText}</pre> : <p className={`text-xs ${c.textMuted} italic text-center py-4`}>{fileName ? `📑 ${fileName} — ${t('jarg_file_no_side')}` : t('jarg_original_na')}</p>}</div></div>
          <div className={`${c.card} ${c.border} border ${c.border} rounded-xl p-4`}><h3 className={`font-bold text-sm ${c.text} mb-2`}>{t('jarg_translated')}</h3><div className={`${c.accentCard} border rounded-lg p-3 max-h-96 overflow-y-auto`}><p className={`${c.text} whitespace-pre-wrap`}>{results.translation}</p></div></div>
        </div>}

        {/* Key Sections */}
        {activeTab === 'highlights' && <div className="space-y-3">{!results.key_sections?.length ? <p className={`text-sm ${c.textMuteded} text-center py-4`}>{t('jarg_no_sections')}</p> : results.key_sections.map((s, i) => {
          const bg = s.type === 'red_flag' ? c.danger : s.type === 'deadline' ? c.highlight : s.type === 'decision' ? c.warning : c.highlight;
          return <div key={i} className={`${bg} border rounded-xl p-4 space-y-2`}>
            <div className="flex items-center gap-2"><span>{FLAG[s.type]?.i}</span><span className="text-xs font-bold">{FLAG[s.type]?.lKey ? t(FLAG[s.type].lKey) : ''}</span><span className="font-bold text-sm">{s.title}</span></div>
            <p className="text-xs italic">"{s.original_text}"</p><p className="text-sm">{s.simplified}</p><p className="text-xs"><strong>{t('jarg_why')}</strong> {s.why_it_matters}</p>
            {s.enforceability_note && <div className={`${c.highlight} border rounded-lg p-2`}><p className="text-xs">⚖️ {s.enforceability_note}</p></div>}
            <button onClick={() => handleSection(s.original_text)} disabled={loading} className={`text-xs font-bold ${c.textSecondary} disabled:opacity-40`}>🔍 {t('jarg_deep_dive')}</button>
          </div>;
        })}</div>}

        {/* Glossary */}
        {activeTab === 'glossary' && <div className={`${c.card} ${c.border} border ${c.border} rounded-xl p-5`}><h3 className={`font-bold ${c.text} mb-3`}>📚 {t('jarg_glossary')}</h3>{!results.glossary?.length ? <p className={`text-sm ${c.textMuteded}`}>{t('jarg_no_terms')}</p> : <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{results.glossary.map((g, i) => <div key={i} className={`${c.cardAlt} rounded-lg p-3`}><p className={`text-sm font-bold ${c.text}`}>{g.term}</p><p className={`text-xs ${c.textSecondary}`}>{g.definition}</p>{g.context && <p className={`text-xs ${c.textMuteded}`}>{g.context}</p>}</div>)}</div>}</div>}

        {/* Q&A */}
        {activeTab === 'qa' && <div className="space-y-4">
          <div className={`${c.card} ${c.border} border ${c.border} rounded-xl p-4 space-y-3`}><h3 className={`font-bold ${c.text}`}>❓ {t('jarg_qa_title')}</h3><div className="flex gap-2"><input value={question} onChange={e => setQuestion(e.target.value)} placeholder={t('jarg_qa_ph')} className={`flex-1 px-3 py-2 rounded-lg border text-sm ${c.input}`} onKeyDown={e => { if (e.key === 'Enter') handleAsk(); }} /><button onClick={handleAsk} disabled={loading || !question.trim()} className={`px-4 py-2 rounded-lg text-xs font-bold ${c.btnPrimary} disabled:opacity-40`}>{t('jarg_ask')}</button></div></div>
          {qaHistory.map((qa, i) => <div key={i} className="space-y-2"><div className={`${c.accentCard} border rounded-xl p-3`}><p className={`text-sm font-medium ${c.text}`}>❓ {qa.q}</p></div><div className={`${c.card} ${c.border} border ${c.border} rounded-xl p-4 space-y-2`}><p className={`text-sm ${c.textSecondary}`}>{qa.a.answer}</p>{qa.a.found_in_document && <p className={`text-xs ${c.textMuteded} italic`}>📍 {qa.a.found_in_document}{qa.a.relevant_section ? ` — ${qa.a.relevant_section}` : ''}</p>}{qa.a.warning && <div className={`${c.danger} border rounded-lg p-2`}><p className="text-xs">⚠️ {qa.a.warning}</p></div>}{qa.a.who_to_ask && <p className={`text-xs ${c.textMuteded}`}>👤 {t('jarg_ask_who')} {qa.a.who_to_ask}</p>}{qa.a.follow_up && <button onClick={() => setQuestion(qa.a.follow_up)} className={`text-xs ${c.textSecondary}`}>→ {qa.a.follow_up}</button>}</div></div>)}
        </div>}

        {/* Explain To */}
        {activeTab === 'explain' && <div className="space-y-4">
          <div className={`${c.card} ${c.border} border ${c.border} rounded-xl p-4 space-y-3`}>
            <h3 className={`font-bold ${c.text}`}>🗣️ {t('jarg_explain_title')}</h3>
            <p className={`text-xs ${c.textMuteded}`}>{t('jarg_explain_sub')}</p>
            <input value={expAudience} onChange={e => setExpAudience(e.target.value)} placeholder={t('jarg_explain_ph_who')} className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} />
            <textarea value={expSection} onChange={e => setExpSection(e.target.value)} placeholder={t('jarg_explain_ph_section')} rows={2} className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} />
            <button onClick={handleExplainTo} disabled={loading} className={`w-full py-2.5 rounded-xl font-bold text-sm ${c.btnPrimary} disabled:opacity-40`}>{loading ? <><span className="inline-block animate-spin">{tool?.icon ?? '🗡️'}</span> {t('jarg_working')}</> : <><span className='mr-1'>{tool?.icon ?? '🗡️'}</span> {t('jarg_reframe')}</>}</button>
          </div>
          {expData && <div className="space-y-3">
            <div className={`${c.card} ${c.border} border ${c.border} rounded-xl p-5`}><p className={`text-sm ${c.textSecondary} whitespace-pre-line`}>{expData.explanation}</p></div>
            {expData.their_main_concern && <div className={`${c.warning} border rounded-xl p-4`}><p className="text-xs font-bold">😟 {t('jarg_their_concern')}</p><p className="text-sm mt-1">{expData.their_main_concern}</p></div>}
            {expData.skip && <div className={`${c.success} border rounded-xl p-4`}><p className="text-xs font-bold">😌 {t('jarg_skip')}</p><p className="text-sm mt-1">{expData.skip}</p></div>}
            {expData.key_points_for_them?.length > 0 && <div className={`${c.highlight} border rounded-xl p-4`}><p className="text-xs font-bold mb-1">🎯 {t('jarg_key_points')}</p>{expData.key_points_for_them.map((p, i) => <p key={i} className="text-xs">• {p}</p>)}</div>}
            {expData.how_to_deliver && <div className={`${c.highlight} border rounded-xl p-4`}><p className="text-xs font-bold">💬 {t('jarg_how_deliver')}</p><p className="text-sm mt-1">{expData.how_to_deliver}</p></div>}
            {expData.their_questions?.length > 0 && <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}><p className="text-xs font-bold mb-1">❓ {t('jarg_their_questions')}</p>{expData.their_questions.map((q, i) => <p key={i} className="text-xs mb-0.5">• {q}</p>)}</div>}
          </div>}
        </div>}

        {/* Checklist */}
        {results.checklist?.length > 0 && activeTab === 'translation' && <div className={`${c.warning} border rounded-xl p-5`}><h3 className="font-bold text-sm mb-3">⚠️ {t('jarg_before_sign')}</h3>{results.checklist.map((item, i) => <label key={i} className="flex items-start gap-3 mb-2 cursor-pointer"><input type="checkbox" className="mt-1 w-4 h-4 rounded" /><span className="text-sm">{item}</span></label>)}</div>}
        {results.suggested_questions?.length > 0 && activeTab === 'translation' && (
          <div className={`${c.highlight} border rounded-xl p-5`}>
            <h3 className="font-bold text-sm mb-3">❓ {t('jarg_questions_to_ask')}</h3>
            {results.suggested_questions.map((q, i) => (
              <div key={i} className={`${c.cardAlt} border ${c.border} rounded-lg p-3 mb-2`}>
                <p className="text-sm font-medium">{q.question}</p>
                {q.why && <p className={`text-xs ${c.textSecondary} mt-0.5`}>{q.why}</p>}
                {q.who_to_ask && <p className={`text-xs ${c.textMuteded}`}>👤 {q.who_to_ask}</p>}
              </div>
            ))}
          </div>
        )}

        {/* Suggested Questions */}
        {sugData && <div className={`${c.card} ${c.border} border ${c.border} rounded-xl p-5 space-y-3`}><h3 className={`font-bold ${c.text}`}>🤔 {t('jarg_sug_title')}</h3>
          {sugData.must_ask?.map((q, i) => <div key={i} className={`${c.danger} border rounded-lg p-3`}><p className="text-sm font-medium">{q.question}</p><p className="text-xs">{q.why} · 👤 {q.who_to_ask}</p>{q.what_good_looks_like && <p className={`text-xs ${c.textSecondary}`}>✅ {t('jarg_good_answer')} {q.what_good_looks_like}</p>}</div>)}
          {sugData.negotiate?.map((n, i) => <div key={i} className={`${c.highlight} border rounded-lg p-3`}><p className="text-sm font-medium">💪 {n.point}</p><p className="text-xs">{t('jarg_now')} {n.current} → {t('jarg_ask_for')} {n.better}</p><p className={`text-xs ${isDark ? 'text-cyan-300' : 'text-cyan-700'}`}>{t('jarg_how')} {n.how_to_ask}</p></div>)}
          {sugData.overall_advice && <div className={`${c.accentCard} border rounded-lg p-3`}><p className={`text-sm ${c.textSecondary}`}>☕ {sugData.overall_advice}</p></div>}
        </div>}

        {/* Red-Line */}
        {rlData && <div className={`${c.card} ${c.border} border ${c.border} rounded-xl p-5 space-y-3`}>
          <div className="flex items-center justify-between"><h3 className={`font-bold ${c.text}`}>✏️ {t('jarg_redline_title')}</h3>{rlData.fairness_score && <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${rlData.fairness_score.score <= 3 ? c.danger : rlData.fairness_score.score <= 6 ? c.warning : c.success} border`}>{rlData.fairness_score.score}/10 {rlData.fairness_score.label}</span>}</div>
          <p className={`text-xs ${isDark ? 'text-amber-300' : 'text-amber-700'}`}>⚖️ {t('jarg_redline_disclaimer')}</p>
          {rlData.overview && <p className={`text-sm ${c.textSecondary}`}>{rlData.overview}</p>}
          {rlData.redlines?.map((r, i) => <div key={i} className={`${PRI_COLORS[r.priority] || c.highlight} border rounded-lg p-3 space-y-1`}>
            <div className="flex items-center gap-2"><span className={`text-xs font-bold px-2 py-0.5 rounded-full ${isDark ? 'bg-zinc-600 text-zinc-200' : 'bg-gray-200 text-gray-700'}`}>{r.priority}</span>{r.clause && <span className={`text-xs ${c.textMuteded}`}>{r.clause}</span>}</div>
            <p className="text-sm font-medium">{r.problem}</p>
            <p className={`text-xs ${c.textSecondary}`}>{t('jarg_current')} {r.current_text}</p>
            <div className={`${c.success} border rounded p-2`}><p className="text-xs">✏️ {t('jarg_change_to')} {r.suggested_change}</p></div>
            {r.negotiation_tip && <p className={`text-xs ${c.textMuteded}`}>💡 {r.negotiation_tip}</p>}
          </div>)}
          {rlData.add_these?.length > 0 && <div className={`${c.highlight} border rounded-lg p-3`}><p className="text-xs font-bold mb-1">➕ {t('jarg_add_protections')}</p>{rlData.add_these.map((a, i) => <div key={i} className="mt-1"><p className="text-xs font-medium">{a.what}</p><p className="text-xs">{a.why}</p>{a.suggested_language && <p className={`text-xs italic ${c.textSecondary} mt-0.5`}>{t('jarg_draft')} "{a.suggested_language}"</p>}</div>)}</div>}
          {rlData.remove_these?.length > 0 && <div className={`${c.danger} border rounded-lg p-3`}><p className="text-xs font-bold mb-1">🗑️ {t('jarg_remove_clauses')}</p>{rlData.remove_these.map((r, i) => <div key={i} className="mt-1"><p className="text-xs font-medium">{r.what}</p><p className="text-xs">{r.why}</p></div>)}</div>}
          {rlData.non_negotiable_warning && <div className={`${c.warning} border rounded-lg p-3`}><p className="text-xs font-bold mb-1">⚠️ {t('jarg_non_negotiable')}</p><p className="text-xs">{rlData.non_negotiable_warning}</p></div>}
          {rlData.overall_strategy && <div className={`${c.accentCard} border rounded-lg p-3`}><p className={`text-xs font-bold ${c.textSecondary}`}>🎯 {t('jarg_strategy')}</p><p className={`text-sm ${c.text}`}>{rlData.overall_strategy}</p></div>}
        </div>}

        {/* Template Compare */}
        {tplData && <div className={`${c.card} ${c.border} border ${c.border} rounded-xl p-5 space-y-3`}>
          <div className="flex items-center justify-between"><h3 className={`font-bold ${c.text}`}>📊 {t('jarg_vs_normal_title')}</h3>{tplData.normal_score && <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${tplData.normal_score.score <= 3 ? c.danger : tplData.normal_score.score <= 6 ? c.warning : c.success} border`}>{tplData.normal_score.score}/10 {tplData.normal_score.label}</span>}</div>
          {tplData.overall_assessment && <p className={`text-sm ${c.textSecondary}`}>{tplData.overall_assessment}</p>}
          {tplData.comparisons?.map((comp, i) => <div key={i} className={`${VER_COLORS[comp.verdict] || c.cardAlt} border ${c.border} rounded-lg p-3 space-y-1`}>
            <div className="flex items-center gap-2"><span className="text-sm font-bold">{comp.clause_area}</span><span className={`text-xs px-2 py-0.5 rounded-full ${comp.verdict === 'red_flag' ? (isDark ? 'bg-red-900/40 text-red-200' : 'bg-red-100 text-red-700') : comp.verdict === 'better_than_usual' ? (isDark ? 'bg-green-900/40 text-green-200' : 'bg-green-100 text-green-700') : (isDark ? 'bg-zinc-600 text-zinc-200' : 'bg-gray-200 text-gray-700')}`}>{comp.verdict.replace(/_/g, ' ')}</span></div>
            <p className="text-xs">{t('jarg_this_doc')} {comp.this_document}</p>
            <p className="text-xs">{t('jarg_normal')} {comp.typical_range}</p>
            {comp.context && <p className={`text-xs ${c.textMuteded}`}>{comp.context}</p>}
          </div>)}
          {tplData.missing_protections?.length > 0 && <div className={`${c.danger} border rounded-lg p-3`}><p className="text-xs font-bold mb-1">🚫 {t('jarg_missing_protections')}</p>{tplData.missing_protections.map((m, i) => <p key={i} className="text-xs">• {m}</p>)}</div>}
          {tplData.unusually_good?.length > 0 && <div className={`${c.success} border rounded-lg p-3`}><p className="text-xs font-bold mb-1">✅ {t('jarg_better_usual')}</p>{tplData.unusually_good.map((g, i) => <p key={i} className="text-xs">• {g}</p>)}</div>}
          {tplData.bottom_line && <div className={`${c.accentCard} border rounded-lg p-3`}><p className={`text-sm ${c.textSecondary}`}>☕ {tplData.bottom_line}</p></div>}
        </div>}

        {/* Action Plan */}
        {apData && <div className={`${c.card} ${c.border} border ${c.border} rounded-xl p-5 space-y-3`}>
          <h3 className={`font-bold ${c.text}`}>📋 {t('jarg_ap_title')}</h3>
          {apData.summary && <p className={`text-sm ${c.textSecondary}`}>{apData.summary}</p>}
          {apData.quick_wins?.length > 0 && <div className={`${c.success} border rounded-lg p-3`}><p className="text-xs font-bold">⚡ {t('jarg_quick_wins')}</p>{apData.quick_wins.map((w, i) => <p key={i} className="text-xs">• {w}</p>)}</div>}
          {apData.steps?.map((s, i) => <div key={i} className={`${c.cardAlt} border ${c.border} rounded-lg p-3 space-y-1`}>
            <div className="flex items-center gap-2"><span className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold ${c.pillOn}`}>{s.order}</span><span className={`text-sm font-bold ${c.text}`}>{s.action}</span></div>
            <p className={`text-xs ${c.textSecondary}`}>{s.why}</p>
            {s.deadline && <p className={`text-xs font-bold ${c.textSecondary}`}>⏰ {s.deadline}</p>}
            {s.who && <p className={`text-xs ${c.textMuteded}`}>👤 {s.who}</p>}
            {s.how && <p className={`text-xs ${c.textMuteded}`}>{t('jarg_how')} {s.how}</p>}
            {s.template && <div className={`${c.highlight} border rounded p-2 mt-1`}><p className="text-xs font-bold">📝 {t('jarg_script')}</p><p className="text-xs">{s.template}</p></div>}
          </div>)}
          {apData.if_you_do_nothing && <div className={`${c.danger} border rounded-lg p-3`}><p className="text-xs font-bold">⚠️ {t('jarg_if_nothing')}</p><p className="text-xs">{apData.if_you_do_nothing}</p></div>}
          {apData.timeline && <p className={`text-xs ${c.textSecondary}`}>📅 {t('jarg_timeline')} {apData.timeline}</p>}
          {apData.cost_estimate && <p className={`text-xs ${c.textMuteded}`}>💰 {t('jarg_cost_estimate')} {apData.cost_estimate}</p>}
        </div>}

      </div>}

      {/* ═══ SECTION DRILL ═══ */}
      {mode === 'section' && secData && <div className="space-y-4">
        <button onClick={() => setMode('results')} className={`text-xs ${c.textSecondary} font-bold`}>← {t('jarg_back')}</button>
        <div className={`${c.accentCard} border rounded-xl p-4`}><p className={`text-sm ${c.text}`}>{secData.section_summary}</p></div>
        {secData.line_by_line?.map((l, i) => <div key={i} className={`${c.card} ${c.border} border ${c.border} rounded-xl p-4 space-y-2`}><p className={`text-xs ${c.textMuteded} italic`}>"{l.original}"</p><p className={`text-sm ${c.text}`}>{l.meaning}</p><p className={`text-xs ${c.textSecondary}`}>→ {l.implication}</p>{l.hidden_catch && <div className={`${c.danger} border rounded-lg p-2`}><p className="text-xs">🔍 {l.hidden_catch}</p></div>}</div>)}
        {secData.what_this_means_for_you && <div className={`${c.highlight} border rounded-xl p-4`}><p className="text-sm">{secData.what_this_means_for_you}</p></div>}
      </div>}

      {/* ═══ COMPARE ═══ */}
      {mode === 'compare' && <div className="space-y-4">
        <div className={`${c.card} ${c.border} border ${c.border} rounded-xl p-5 space-y-4`}><h3 className={`font-bold ${c.text}`}>🔀 {t('jarg_compare_title')}</h3><div className="flex flex-wrap gap-1.5 mb-2">{DOC_TYPES.slice(0, 5).map(dt => <button key={dt.id} onClick={() => setDocType(dt.id)} className={`px-2.5 py-1 rounded-lg text-xs ${docType === dt.id ? c.pillOn : c.pillOff}`}>{dt.icon} {t(dt.labelKey)}</button>)}</div><textarea value={cmpT1} onChange={e => setCmpT1(e.target.value)} placeholder={t('jarg_ph_v1')} rows={4} className={`w-full px-3 py-2 rounded-lg border text-sm font-mono ${c.input}`} /><textarea value={cmpT2} onChange={e => setCmpT2(e.target.value)} placeholder={t('jarg_ph_v2')} rows={4} className={`w-full px-3 py-2 rounded-lg border text-sm font-mono ${c.input}`} /><button onClick={handleCompare} disabled={loading} className={`w-full py-3 rounded-xl font-bold text-sm ${c.btnPrimary} disabled:opacity-40`}>{loading ? <><span className="inline-block animate-spin">{tool?.icon ?? '🗡️'}</span> {t('jarg_working')}</> : <><span className='mr-1'>{tool?.icon ?? '🗡️'}</span> {t('jarg_compare')}</>}</button></div>
        {cmpData && <div className="space-y-3">
          <div className={`${cmpData.overall_assessment?.direction === 'better' ? c.success : cmpData.overall_assessment?.direction === 'worse' ? c.danger : c.warning} border rounded-xl p-4`}><p className="text-lg font-bold">{cmpData.overall_assessment?.direction === 'better' ? `✅ ${t('jarg_better')}` : cmpData.overall_assessment?.direction === 'worse' ? `🔴 ${t('jarg_worse')}` : `🟡 ${t('jarg_mixed')}`}</p><p className="text-sm mt-1">{cmpData.summary}</p>{cmpData.overall_assessment?.recommendation && <p className="text-xs mt-1">{cmpData.overall_assessment.recommendation}</p>}</div>
          {cmpData.changes?.map((ch, i) => <div key={i} className={`${ch.impact === 'negative' ? c.danger : ch.impact === 'positive' ? c.success : `${c.cardAlt} border ${c.border}`} ${ch.impact !== 'neutral' ? 'border' : ''} rounded-xl p-3 space-y-1`}><span className={`text-xs font-bold px-2 py-0.5 rounded-full ${isDark ? 'bg-zinc-600 text-zinc-200' : 'bg-gray-200 text-gray-700'}`}>{ch.severity}</span><p className={`text-sm font-medium ${c.text}`}>{ch.what_changed}</p><p className="text-xs">{t('jarg_before')} {ch.before}</p><p className="text-xs">{t('jarg_after')} {ch.after}</p></div>)}
          {cmpData.removed?.length > 0 && <div className={`${c.danger} border rounded-lg p-3`}><p className="text-xs font-bold">🗑️ {t('jarg_removed')}</p>{cmpData.removed.map((r, i) => <p key={i} className="text-xs">• {r}</p>)}</div>}
          {cmpData.added?.length > 0 && <div className={`${c.success} border rounded-lg p-3`}><p className="text-xs font-bold">➕ {t('jarg_added')}</p>{cmpData.added.map((a, i) => <p key={i} className="text-xs">• {a}</p>)}</div>}
        </div>}
      </div>}

      {/* ═══ DOSSIER ═══ */}
      {mode === 'dossier' && <div className="space-y-4">
        <div className={`${c.card} ${c.border} border ${c.border} rounded-xl p-5 space-y-4`}>
          <div><h3 className={`font-bold ${c.text}`}>📁 {t('jarg_dossier_title')}</h3><p className={`text-sm ${c.textMuteded}`}>{t('jarg_dossier_sub')}</p></div>
          {dossDocs.map((d, i) => <div key={i} className={`${c.cardAlt} border ${c.border} rounded-lg p-3 space-y-2`}><div className="flex gap-2"><input ref={el => { dossDocsInputRefs.current[i] = el; }} value={d.title} onChange={e => setDossDocs(prev => prev.map((p, j) => j === i ? { ...p, title: e.target.value } : p))} placeholder={t('jarg_doc_title_ph', { n: i + 1 })} className={`flex-1 px-2 py-1 rounded border text-xs ${c.input}`} /><select value={d.type} onChange={e => setDossDocs(prev => prev.map((p, j) => j === i ? { ...p, type: e.target.value } : p))} className={`px-2 py-1 rounded border text-xs ${c.input}`}>{DOC_TYPES.map(dt => <option key={dt.id} value={dt.id}>{t(dt.labelKey)}</option>)}</select></div><textarea value={d.text} onChange={e => setDossDocs(prev => prev.map((p, j) => j === i ? { ...p, text: e.target.value } : p))} placeholder={t('jarg_doc_text_ph')} rows={3} className={`w-full px-2 py-1 rounded border text-xs font-mono ${c.input}`} /></div>)}
          <button onClick={() => { shouldFocusNewDossDocsRef.current = true; setDossDocs(prev => [...prev, { title: '', text: '', type: 'general' }]); }} className={`text-xs ${c.textSecondary} font-bold`}>➕ {t('jarg_add_document')}</button>
          <button onClick={handleDossier} disabled={loading} className={`w-full py-3 rounded-xl font-bold text-sm ${c.btnPrimary} disabled:opacity-40`}>{loading ? <><span className="inline-block animate-spin">{tool?.icon ?? '🗡️'}</span> {t('jarg_working')}</> : <><span className='mr-1'>{tool?.icon ?? '🗡️'}</span> {t('jarg_cross_reference')}</>}</button>
        </div>
        {dossData && <div className="space-y-3">
          {dossData.relationship && <div className={`${c.accentCard} border rounded-xl p-4`}><p className={`text-sm ${c.text}`}>{dossData.relationship}</p></div>}
          {dossData.conflicts?.length > 0 && <div className={`${c.danger} border rounded-xl p-4 space-y-2`}><h3 className="font-bold text-sm">⚡ {t('jarg_conflicts')}</h3>{dossData.conflicts.map((con, i) => <div key={i}><p className="text-sm">{con.conflict}</p><p className="text-xs">{con.doc1} {t('jarg_vs')} {con.doc2} · {con.which_wins}</p><p className="text-xs">{t('jarg_risk')} {con.risk}</p></div>)}</div>}
          {dossData.interactions?.length > 0 && <div className={`${c.highlight} border rounded-xl p-4 space-y-2`}><h3 className="font-bold text-sm">🔗 {t('jarg_interactions')}</h3>{dossData.interactions.map((int, i) => <div key={i} className="mb-1"><p className="text-xs font-medium">{int.documents}: {int.how}</p>{int.watch_out && <p className={`text-xs ${isDark ? 'text-amber-300' : 'text-amber-700'}`}>⚠️ {int.watch_out}</p>}</div>)}</div>}
          {dossData.gaps?.length > 0 && <div className={`${c.warning} border rounded-xl p-4`}><p className="text-xs font-bold">🚫 {t('jarg_gaps')}</p>{dossData.gaps.map((g, i) => <p key={i} className="text-xs">• {g}</p>)}</div>}
          {dossData.combined_checklist?.length > 0 && <div className={`${c.warning} border rounded-xl p-4`}><p className="text-xs font-bold mb-2">☑️ {t('jarg_combined_checklist')}</p>{dossData.combined_checklist.map((item, i) => <label key={i} className="flex items-start gap-2 mb-1 cursor-pointer"><input type="checkbox" className="mt-0.5 w-3 h-3 rounded" /><span className="text-xs">{item}</span></label>)}</div>}
          {dossData.overall && <div className={`${c.highlight} border rounded-xl p-4`}><p className="text-sm">{dossData.overall}</p></div>}
        </div>}
      </div>}

      {/* ═══ LETTER ═══ */}
      {mode === 'letter' && <div className="space-y-4">
        <div className={`${c.card} ${c.border} border ${c.border} rounded-xl p-5 space-y-4`}>
          <div><h3 className={`font-bold ${c.text}`}>✉️ {t('jarg_letter_title')}</h3><p className={`text-sm ${c.textMuteded}`}>{t('jarg_letter_sub')}</p></div>
          <input value={ltrIntent} onChange={e => setLtrIntent(e.target.value)} placeholder={t('jarg_letter_ph_intent')} className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} />
          <textarea value={ltrPoints} onChange={e => setLtrPoints(e.target.value)} placeholder={t('jarg_letter_ph_points')} rows={2} className={`w-full px-3 py-2 rounded-lg border text-sm ${c.input}`} />
          <div><p className={`text-xs font-bold ${c.text} mb-1`}>{t('jarg_tone')}</p><div className="flex flex-wrap gap-1.5">{[{ value: 'professional but firm', labelKey: 'jarg_tone_firm' }, { value: 'friendly but clear', labelKey: 'jarg_tone_friendly' }, { value: 'formal and assertive', labelKey: 'jarg_tone_formal' }, { value: 'conciliatory', labelKey: 'jarg_tone_concil' }].map(opt => <button key={opt.value} onClick={() => setLtrTone(opt.value)} className={`px-3 py-1.5 rounded-lg text-xs ${ltrTone === opt.value ? c.pillOn : c.pillOff}`}>{t(opt.labelKey)}</button>)}</div></div>
          <button onClick={handleLetter} disabled={loading} className={`w-full py-3 rounded-xl font-bold text-sm ${c.btnPrimary} disabled:opacity-40`}>{loading ? <><span className="inline-block animate-spin">{tool?.icon ?? '🗡️'}</span> {t('jarg_working')}</> : <><span className='mr-1'>{tool?.icon ?? '🗡️'}</span> {t('jarg_generate_letter')}</>}</button>
        </div>
        {ltrData && <div className="space-y-3">
          {ltrData.subject_line && <div className={`${c.cardAlt} border ${c.border} rounded-lg p-3`}><p className={`text-xs font-bold ${c.text}`}>{t('jarg_subject')} {ltrData.subject_line}</p></div>}
          <div className={`${c.card} ${c.border} border ${c.border} rounded-xl p-5`}><div className="flex justify-between mb-2"><h3 className={`font-bold ${c.text}`}>{t('jarg_your_letter')}</h3></div><p className={`text-sm ${c.textSecondary} whitespace-pre-line`}>{ltrData.letter}</p></div>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
            {ltrData.send_to && <div className={`${c.cardAlt} rounded-lg p-2 text-center`}><p className={`text-xs ${c.textMuteded}`}>{t('jarg_to')}</p><p className={`text-xs font-bold ${c.text}`}>{ltrData.send_to}</p></div>}
            {ltrData.send_via && <div className={`${c.cardAlt} rounded-lg p-2 text-center`}><p className={`text-xs ${c.textMuteded}`}>{t('jarg_via')}</p><p className={`text-xs font-bold ${c.text}`}>{ltrData.send_via}</p></div>}
            {ltrData.timing && <div className={`${c.cardAlt} rounded-lg p-2 text-center`}><p className={`text-xs ${c.textMuteded}`}>{t('jarg_when')}</p><p className={`text-xs font-bold ${c.text}`}>{ltrData.timing}</p></div>}
            {ltrData.escalation && <div className={`${c.cardAlt} rounded-lg p-2 text-center`}><p className={`text-xs ${c.textMuteded}`}>{t('jarg_if_no_response')}</p><p className={`text-xs font-bold ${c.text}`}>{ltrData.escalation}</p></div>}
          </div>
          {ltrData.warnings?.length > 0 && <div className={`${c.warning} border rounded-lg p-3`}><p className="text-xs font-bold">⚠️ {t('jarg_before_sending')}</p>{ltrData.warnings.map((w, i) => <p key={i} className="text-xs">• {w}</p>)}</div>}
        </div>}
      </div>}

      {/* Error */}
      {error && <div className={`${c.danger} border rounded-xl p-4 text-sm`}>⚠️ {error}</div>}

      <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
        <p className={`text-[10px] font-bold ${c.textMuted} uppercase mb-2`}>🔗 {t('jarg_related')}</p>
        <div className="flex flex-wrap gap-3">
          <a href="/VelvetHammer" className={`text-xs ${linkStyle}`}>🔨 {t('jarg_xref_velvet')}</a>
          <a href="/BrainDumpBuddy" className={`text-xs ${linkStyle}`}>🧠 {t('jarg_xref_braindump')}</a>
          <a href="/ResearchDecoder" className={`text-xs ${linkStyle}`}>📄 {t('jarg_xref_research')}</a>
        </div>
      </div>
    </div>
  );
};

JargonAssassin.displayName = 'JargonAssassin';
export default JargonAssassin;
