import React, { useState } from 'react';
import { useTheme } from '../hooks/useTheme';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { CopyBtn, ActionBar } from '../components/ActionButtons';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

const MECHANISM_CONFIG = {
  broadcast:  { label: '📢 Broadcast a Signal',         color: (d) => d ? 'bg-[#2c4a6e]/20 text-[#a8b9ce] border-[#2c4a6e]/40'  : 'bg-[#e8eef5] text-[#1e3a58] border-[#b0c4d8]' },
  infiltrate: { label: '🚪 Infiltrate a New Room',       color: (d) => d ? 'bg-[#c8872e]/15 text-[#d9a04e] border-[#c8872e]/40'  : 'bg-[#fdf3e4] text-[#93541f] border-[#e0c49a]' },
  create:     { label: '✍️ Create a Serendipity Artifact', color: (d) => d ? 'bg-[#5a8a5c]/15 text-[#8aba8c] border-[#5a8a5c]/40' : 'bg-[#e8f0e8] text-[#3d6e3f] border-[#a8c4a8]' },
  curate:     { label: '🧲 Curate a High-Value Connection', color: (d) => d ? 'bg-[#b54a3f]/15 text-[#e8a9a3] border-[#b54a3f]/40' : 'bg-[#fceae8] text-[#8a3028] border-[#d4908a]' },
  compound:   { label: '⚡ Compound an Existing Asset',  color: (d) => d ? 'bg-[#3d3630]/60 text-[#c8c3b9] border-[#3d3630]'     : 'bg-[#f3efe8] text-[#5e5042] border-[#d5cab8]' },
};

const EXAMPLES = [
  {
    desc: 'Software engineer, WFH, same team for 3 years. Live in Denver. Go to the gym, cook, watch TV. Small tight friend group. Work is fine but I feel invisible professionally.',
    goals: 'Better job opportunities, interesting collaborators, maybe a co-founder someday',
  },
  {
    desc: 'Freelance designer, mostly work through referrals from 2 clients. Active on Instagram but not professionally. Go to the same coffee shop every day. Haven\'t been to an industry event in 2 years.',
    goals: 'More and better clients, creative collaborators, maybe an agent or gallery connection',
  },
];

const LuckSurface = () => {
  const { theme } = useTheme();
  const isDark = theme === 'dark';
  const { callToolEndpoint, loading } = useClaudeAPI();

  const c = {
    pageBg:       isDark ? 'bg-[#1a1816]'    : 'bg-[#faf8f5]',
    card:         isDark ? 'bg-[#2a2623]'     : 'bg-white',
    cardAlt:      isDark ? 'bg-[#332e2a]'     : 'bg-[#faf8f5]',
    cardBorder:   isDark ? 'border-[#3d3630]' : 'border-[#e8e1d5]',
    input:        isDark ? 'bg-[#1a1816] border-[#3d3630] text-[#f0eeea] placeholder:text-[#8a8275]'
                         : 'bg-[#faf8f5] border-[#d5cab8] text-[#3d3935] placeholder:text-[#8a8275]',
    inputFocus:   'focus:outline-none focus:ring-2 focus:ring-[#2c4a6e]/20 focus:border-[#4a6a8a]',
    text:          isDark ? 'text-[#f0eeea]'  : 'text-[#3d3935]',
    textSecondary: isDark ? 'text-[#c8c3b9]'  : 'text-[#5a544a]',
    textMuted:     isDark ? 'text-[#8a8275]'  : 'text-[#8a8275]',
    heading:       isDark ? 'text-[#f3efe8]'  : 'text-[#1e2a3a]',
    btnPrimary:    isDark ? 'bg-[#2c4a6e] hover:bg-[#4a6a8a] text-white' : 'bg-[#2c4a6e] hover:bg-[#1e3a58] text-white',
    btnSecondary:  isDark ? 'bg-[#332e2a] hover:bg-[#3d3630] text-[#c8c3b9] border border-[#3d3630]' : 'bg-[#f3efe8] hover:bg-[#e8e1d5] text-[#5e5042] border border-[#d5cab8]',
    divider:       isDark ? 'border-[#3d3630]' : 'border-[#e8e1d5]',
    error:         isDark ? 'bg-[#b54a3f]/15 border-[#b54a3f]/50 text-[#e8a9a3]' : 'bg-[#fceae8] border-[#d4908a] text-[#8a3028]',
    goldBg:        isDark ? 'bg-[#c8872e]/15 border-[#c8872e]/40' : 'bg-[#fdf3e4] border-[#e0c49a]',
    goldText:      isDark ? 'text-[#d9a04e]' : 'text-[#93541f]',
  };

  const [description, setDescription] = useState('');
  const [goals, setGoals] = useState('');
  const [currentExposures, setCurrentExposures] = useState('');
  const [results, setResults] = useState(null);
  const [error, setError] = useState('');
  const [expanded, setExpanded] = useState({});
  const toggle = (k) => setExpanded(p => ({ ...p, [k]: !p[k] }));

  const handleSubmit = async () => {
    if (!description.trim()) return;
    setError(''); setResults(null);
    try {
      const data = await callToolEndpoint('luck-surface', {
        description: description.trim(),
        goals: goals.trim() || undefined,
        currentExposures: currentExposures.trim() || undefined,
      });
      setResults(data);
    } catch (e) { setError(e.message || 'Failed to calculate luck surface.'); }
  };

  const handleExample = () => {
    const ex = EXAMPLES[Math.floor(Math.random() * EXAMPLES.length)];
    setDescription(ex.desc); setGoals(ex.goals); setResults(null);
  };

  const buildText = () => {
    if (!results) return '';
    const a = results.audit;
    let t = `🧲 LUCK SURFACE ANALYSIS\n\nCurrent surface area: ${a?.current_surface_area}\n${a?.the_diagnosis}\n\n`;
    t += `THE INVISIBLE WALL: ${a?.the_invisible_wall}\n\n`;
    t += `5 MOVES:\n`;
    results.the_five_moves?.forEach((m, i) => {
      t += `${i + 1}. ${m.title}\n${m.the_move}\nWhy it works: ${m.why_asymmetric}\n\n`;
    });
    if (results.the_one_to_start) t += `START HERE: ${results.the_one_to_start}\n`;
    return t + BRAND;
  };

  return (
    <div className={`min-h-screen py-8 px-4 ${c.pageBg}`}>
      <div className="max-w-2xl mx-auto">

        <div className="text-center mb-8">
          <div className="text-5xl mb-3">🧲</div>
          <h1 className={`text-3xl font-black tracking-tight mb-2 ${c.heading}`}>Luck Surface</h1>
          <p className={`text-sm ${c.textMuted}`}>Calculate your luck surface area. Expand it with 5 specific moves.</p>
        </div>

        {!results && (
          <div className={`rounded-2xl border p-6 shadow-sm space-y-4 ${c.card} ${c.cardBorder}`}>
            <div>
              <label className={`block text-sm font-semibold mb-1.5 ${c.text}`}>
                Describe your life — what you do, where you go, who you know <span className="text-red-400">*</span>
              </label>
              <textarea value={description} onChange={e => setDescription(e.target.value)}
                placeholder="Your work, hobbies, social patterns, where you spend time, what you make or share publicly…"
                rows={5} maxLength={800}
                className={`w-full px-4 py-3 rounded-xl border text-sm resize-none ${c.input} ${c.inputFocus}`} />
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className={`block text-sm font-semibold mb-1.5 ${c.text}`}>What kind of luck do you want? <span className={`font-normal ${c.textMuted}`}>(optional)</span></label>
                <input type="text" value={goals} onChange={e => setGoals(e.target.value)}
                  placeholder="Better opportunities, collaborators, investors, mentors…"
                  className={`w-full px-4 py-3 rounded-xl border text-sm ${c.input} ${c.inputFocus}`} />
              </div>
              <div>
                <label className={`block text-sm font-semibold mb-1.5 ${c.text}`}>What you already do to put yourself out there <span className={`font-normal ${c.textMuted}`}>(optional)</span></label>
                <input type="text" value={currentExposures} onChange={e => setCurrentExposures(e.target.value)}
                  placeholder="Events, online presence, communities…"
                  className={`w-full px-4 py-3 rounded-xl border text-sm ${c.input} ${c.inputFocus}`} />
              </div>
            </div>
            {error && <div className={`p-3 rounded-xl border text-sm ${c.error}`}><span className="mr-1">⚠️</span>{error}</div>}
            <div className="flex gap-2">
              <button onClick={handleSubmit} disabled={loading || !description.trim()}
                className={`flex-1 py-3 rounded-xl font-bold disabled:opacity-40 ${c.btnPrimary}`}>
                {loading ? <><span className="animate-spin inline-block mr-2">⏳</span>Calculating…</> : '🧲 Calculate My Luck Surface'}
              </button>
              <button onClick={handleExample} disabled={loading}
                className={`px-4 py-3 rounded-xl text-sm font-medium ${c.btnSecondary}`}>
                Example
              </button>
            </div>
          </div>
        )}

        {results && (
          <div className="space-y-4">

            {/* Audit — the gauge */}
            {results.audit && (
              <div className={`rounded-2xl border p-6 ${c.card} ${c.cardBorder}`}>
                <div className="flex items-center justify-between mb-4">
                  <p className={`text-xs font-black uppercase tracking-widest ${c.textMuted}`}>Current Luck Surface Area</p>
                  <span className={`text-4xl font-black ${isDark ? 'text-[#d9a04e]' : 'text-[#93541f]'}`}>{results.audit.current_surface_area}</span>
                </div>
                {/* Progress bar */}
                <div className={`h-3 rounded-full mb-4 ${isDark ? 'bg-[#3d3630]' : 'bg-[#e8e1d5]'}`}>
                  <div className="h-full rounded-full transition-all"
                    style={{
                      width: results.audit.current_surface_area,
                      background: 'linear-gradient(90deg, #c8872e, #d9a04e)',
                    }} />
                </div>
                <p className={`text-sm leading-relaxed mb-3 ${c.textSecondary}`}>{results.audit.the_diagnosis}</p>
                {results.audit.the_invisible_wall && (
                  <div className={`p-3 rounded-xl border ${isDark ? 'bg-[#b54a3f]/10 border-[#b54a3f]/30' : 'bg-[#fceae8] border-[#d4908a]'}`}>
                    <p className={`text-xs font-bold uppercase tracking-wide mb-1 ${isDark ? 'text-[#e8a9a3]' : 'text-[#8a3028]'}`}>🧱 The Invisible Wall</p>
                    <p className={`text-sm ${c.textSecondary}`}>{results.audit.the_invisible_wall}</p>
                  </div>
                )}
                {results.audit.what_theyre_good_at && (
                  <p className={`text-xs mt-3 ${c.textMuted}`}><span className="font-semibold">What's already working:</span> {results.audit.what_theyre_good_at}</p>
                )}
              </div>
            )}

            {/* Five moves */}
            {results.the_five_moves?.length > 0 && (
              <div className="space-y-3">
                <p className={`text-xs font-black uppercase tracking-widest px-1 ${c.textMuted}`}>⚡ The Five Moves</p>
                {results.the_five_moves.map((move, i) => {
                  const mcfg = MECHANISM_CONFIG[move.mechanism] || MECHANISM_CONFIG.broadcast;
                  const isOpen = expanded[i];
                  return (
                    <div key={i} className={`rounded-2xl border overflow-hidden ${c.card} ${c.cardBorder}`}>
                      <button onClick={() => toggle(i)} className="w-full text-left p-5">
                        <div className="flex items-start justify-between gap-3">
                          <div className="flex items-center gap-3 min-w-0">
                            <span className={`flex-shrink-0 w-7 h-7 rounded-full flex items-center justify-center text-sm font-black ${isDark ? 'bg-[#2c4a6e] text-white' : 'bg-[#2c4a6e] text-white'}`}>{i + 1}</span>
                            <div className="min-w-0">
                              <p className={`font-bold text-sm ${c.text}`}>{move.title}</p>
                              <span className={`text-xs font-semibold px-2 py-0.5 rounded-full border ${mcfg.color(isDark)}`}>{mcfg.label}</span>
                            </div>
                          </div>
                          <span className={`flex-shrink-0 text-sm mt-1 ${c.textMuted}`}>{isOpen ? '▲' : '▼'}</span>
                        </div>
                        {!isOpen && <p className={`text-sm mt-2 line-clamp-2 ${c.textMuted}`}>{move.the_move}</p>}
                      </button>
                      {isOpen && (
                        <div className={`px-5 pb-5 space-y-3 border-t ${c.divider}`}>
                          <div className="pt-3">
                            <p className={`text-xs font-bold uppercase tracking-wide mb-1 ${c.textMuted}`}>The Move</p>
                            <p className={`text-sm ${c.text}`}>{move.the_move}</p>
                          </div>
                          {move.why_asymmetric && (
                            <p className={`text-xs ${c.textMuted}`}><span className="font-semibold">Why it's asymmetric:</span> {move.why_asymmetric}</p>
                          )}
                          <div className="flex flex-wrap gap-3 text-xs">
                            {move.luck_multiplier && (
                              <span className={`px-2 py-1 rounded-lg ${c.cardAlt} ${c.cardBorder} border ${c.textMuted}`}>🍀 {move.luck_multiplier}</span>
                            )}
                            {move.time_to_first_result && (
                              <span className={`px-2 py-1 rounded-lg ${c.cardAlt} ${c.cardBorder} border ${c.textMuted}`}>⏱️ {move.time_to_first_result}</span>
                            )}
                          </div>
                          <CopyBtn content={`Move ${i + 1}: ${move.title}\n\n${move.the_move}${BRAND}`} label="Copy this move" />
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            )}

            {/* Target */}
            {results.the_target && (
              <div className={`rounded-2xl border p-5 ${isDark ? 'bg-[#c8872e]/10 border-[#c8872e]/40' : 'bg-[#fdf3e4] border-[#e0c49a]'}`}>
                <div className="flex items-center justify-between mb-3">
                  <p className={`text-xs font-black uppercase tracking-widest ${c.goldText}`}>After 5 Moves</p>
                  <span className={`text-3xl font-black ${c.goldText}`}>{results.the_target.new_surface_area}</span>
                </div>
                <div className={`h-3 rounded-full mb-3 ${isDark ? 'bg-[#3d3630]' : 'bg-[#e8e1d5]'}`}>
                  <div className="h-full rounded-full" style={{ width: results.the_target.new_surface_area, background: 'linear-gradient(90deg, #2c4a6e, #4a6a8a)' }} />
                </div>
                {results.the_target.what_becomes_possible && (
                  <p className={`text-sm mb-2 ${c.textSecondary}`}>{results.the_target.what_becomes_possible}</p>
                )}
                {results.the_target.the_compound_effect && (
                  <p className={`text-xs italic ${c.textMuted}`}>{results.the_target.the_compound_effect}</p>
                )}
              </div>
            )}

            {/* Start here */}
            {results.the_one_to_start && (
              <div className={`rounded-2xl border-2 p-5 ${isDark ? 'border-[#2c4a6e] bg-[#2c4a6e]/10' : 'border-[#2c4a6e] bg-[#e8eef5]'}`}>
                <p className={`text-xs font-black uppercase tracking-widest mb-2 ${isDark ? 'text-[#a8b9ce]' : 'text-[#2c4a6e]'}`}>⚡ Start Here — Today</p>
                <p className={`text-sm font-medium ${c.text}`}>{results.the_one_to_start}</p>
              </div>
            )}

            <div className="flex items-center gap-3 flex-wrap">
              <ActionBar content={buildText()} title="Luck Surface" />
              <button onClick={() => { setResults(null); setDescription(''); setGoals(''); setCurrentExposures(''); setExpanded({}); }}
                className={`px-4 py-2 rounded-lg text-sm font-medium ${c.btnSecondary}`}>
                🔄 New Analysis
              </button>
            </div>

            <div className={`rounded-xl border p-4 ${c.cardAlt} ${c.cardBorder}`}>
              <p className={`text-xs font-semibold uppercase tracking-wide mb-3 ${c.textMuted}`}>Related tools</p>
              <div className="flex flex-wrap gap-2">
                {[
                  { id: 'GravityWell', icon: '🌀', label: 'Pull a specific person into your orbit' },
                  { id: 'ChaosPilot', icon: '🎰', label: 'One calculated disruption' },
                  { id: 'RulebookBreaker', icon: '🏴‍☠️', label: 'Find the cheat codes in any system' },
                ].map(r => (
                  <a key={r.id} href={`/tool/${r.id}`} target="_blank" rel="noopener noreferrer"
                    className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${c.btnSecondary}`}>
                    {r.icon} {r.label}
                  </a>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

LuckSurface.displayName = 'LuckSurface';
export default LuckSurface;
