import React, { useState, useRef, useCallback, useEffect } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';
import { compressImage, CompressionPresets } from '../utils/imageCompression';

// ════════════════════════════════════════════════════════════
// THEME — Navy & Gold
// ════════════════════════════════════════════════════════════

// ════════════════════════════════════════════════════════════
// CONSTANTS
// ════════════════════════════════════════════════════════════
// `value` is the English token sent to the backend (contract); `key` is the
// translation key for the user-facing label.
const DIETARY_OPTIONS = [
  { value: 'Vegetarian', key: 'mep_diet_vegetarian' },
  { value: 'Vegan', key: 'mep_diet_vegan' },
  { value: 'Gluten-free', key: 'mep_diet_glutenfree' },
  { value: 'Dairy-free', key: 'mep_diet_dairyfree' },
  { value: 'Keto/Low-carb', key: 'mep_diet_keto' },
  { value: 'Nut-free', key: 'mep_diet_nutfree' },
  { value: 'Halal', key: 'mep_diet_halal' },
  { value: 'Kosher', key: 'mep_diet_kosher' },
  { value: 'Low-sodium', key: 'mep_diet_lowsodium' },
  { value: 'No restrictions', key: 'mep_diet_none' },
];

const SKILL_OPTIONS = [
  { value: 'beginner', emoji: '🔰', key: 'mep_skill_beginner', descKey: 'mep_skill_beginner_desc' },
  { value: 'intermediate', emoji: '🍳', key: 'mep_skill_intermediate', descKey: 'mep_skill_intermediate_desc' },
  { value: 'advanced', emoji: '👨‍🍳', key: 'mep_skill_advanced', descKey: 'mep_skill_advanced_desc' },
];

const MEAL_OPTIONS = [
  { value: 'breakfast', emoji: '🌅', key: 'mep_meal_breakfast' },
  { value: 'lunch', emoji: '☀️', key: 'mep_meal_lunch' },
  { value: 'dinner', emoji: '🌙', key: 'mep_meal_dinner' },
  { value: 'snack', emoji: '🍿', key: 'mep_meal_snack' },
  { value: 'meal-prep', emoji: '📦', key: 'mep_meal_prep' },
];

const TIME_OPTIONS = [
  { value: '15', emoji: '⚡', key: 'mep_time_15' },
  { value: '30', emoji: '🕐', key: 'mep_time_30' },
  { value: '45', emoji: '🕐', key: 'mep_time_45' },
  { value: '60', emoji: '🕐', key: 'mep_time_60' },
  { value: '90', emoji: '🕐', key: 'mep_time_90' },
  { value: '120+', emoji: '🕐', key: 'mep_time_120' },
];

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';


const EXAMPLE = {
  ingredients: 'chicken thighs, rice, frozen broccoli, garlic, soy sauce, sesame oil, ginger, scallions, eggs',
  servings: '2-4',
  timeAvailable: '45',
  skillLevel: 'intermediate',
  mealType: 'dinner',
  preferences: 'one-pan if possible, leaning savory and a little spicy',
};
const EQUIPMENT_OPTIONS = [
  { value: 'Oven', key: 'mep_equip_oven' },
  { value: 'Stovetop', key: 'mep_equip_stovetop' },
  { value: 'Microwave', key: 'mep_equip_microwave' },
  { value: 'Air fryer', key: 'mep_equip_airfryer' },
  { value: 'Instant Pot / pressure cooker', key: 'mep_equip_instantpot' },
  { value: 'Slow cooker', key: 'mep_equip_slowcooker' },
  { value: 'Blender', key: 'mep_equip_blender' },
  { value: 'Food processor', key: 'mep_equip_foodprocessor' },
  { value: 'Grill', key: 'mep_equip_grill' },
];

// ════════════════════════════════════════════════════════════
// MAIN COMPONENT
// ════════════════════════════════════════════════════════════
const MiseEnPlace = ({ tool }) => {
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20'
                          : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-400' : 'text-gray-500',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white'
                          : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200'
                          : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200'
                          : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200'
                          : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200'
                          : 'bg-red-50 border-red-200 text-red-800',
    pillActive:    isDark ? 'border-cyan-500 bg-cyan-900/30 text-cyan-200'
                          : 'border-cyan-600 bg-cyan-100 text-cyan-900',
    pillInactive:  isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500'
                          : 'border-gray-300 text-gray-500 hover:border-gray-400',
    required:      isDark ? 'text-amber-400' : 'text-amber-700',
    // Tool-specific semantic aliases
    badge:         isDark ? 'bg-zinc-700 text-zinc-300' : 'bg-slate-100 text-slate-700',
    criticalBg:    isDark ? 'bg-red-900/20 border-red-700' : 'bg-red-50 border-red-200',
    criticalText:  isDark ? 'text-red-300' : 'text-red-700',
    parallelBg:    isDark ? 'bg-emerald-900/20 border-emerald-700' : 'bg-emerald-50 border-emerald-200',
    parallelText:  isDark ? 'text-emerald-300' : 'text-emerald-700',
    tipBg:         isDark ? 'bg-sky-900/20 border-sky-700' : 'bg-sky-50 border-sky-200',
    tipText:       isDark ? 'text-sky-300' : 'text-sky-700',
    timelineBg:    isDark ? 'bg-zinc-800 border-zinc-700' : 'bg-white border-gray-200',
    timelineDot:   isDark ? 'bg-cyan-500' : 'bg-cyan-600',
    timelineLine:  isDark ? 'bg-zinc-700' : 'bg-gray-200',
    inset:         isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    dropzone:      isDark ? 'border-zinc-600 bg-zinc-800/50' : 'border-gray-300 bg-slate-50',
    dropActive:    isDark ? 'border-cyan-500 bg-cyan-900/20' : 'border-cyan-400 bg-cyan-50',
    histBg:        isDark ? 'bg-zinc-800 border-zinc-700' : 'bg-white border-gray-200',
    histAccent:    isDark ? 'text-amber-400' : 'text-amber-600',
    histCard:      isDark ? 'border-zinc-700' : 'border-gray-100',
    deleteHover:   isDark ? 'hover:bg-red-900/30 hover:text-red-300' : 'hover:bg-red-50 hover:text-red-600',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';
  const resultsRef = useRef(null);
  const fileInputRef = useRef(null);

  // Persistent
  const [showHistory, setShowHistory] = useState(false);

  // Input
  const [imagePreview, setImagePreview] = useState(null);
  const [imageBase64, setImageBase64] = useState(null);
  const [ingredients, setIngredients] = useState('');
  const [servings, setServings] = useState('2-4');
  const [dietary, setDietary] = useState([]);
  const [timeAvailable, setTimeAvailable] = useState('60');
  const [skillLevel, setSkillLevel] = useState('intermediate');
  const [equipment, setEquipment] = useState([]);
  const [mealType, setMealType] = useState('dinner');
  const [preferences, setPreferences] = useState('');
  const [compressing, setCompressing] = useState(false);
  const [isDragging, setIsDragging] = useState(false);

  // Results
  const [results, setResults] = usePersistentState('miseenplace-results', null);
  const [error, setError] = useState('');
  const [showMeals, setShowMeals] = useState(true);
  const [showShopping, setShowShopping] = useState(false);
  const [showTips, setShowTips] = useState(false);
  const [showLeftovers, setShowLeftovers] = useState(false);
  const [sessionHistory, setSessionHistory] = usePersistentState('mise-en-place-history', []);

  useEffect(() => {
    if (results && resultsRef.current) {
      setTimeout(() => resultsRef.current.scrollIntoView({ behavior: 'smooth', block: 'start' }), 200);
    }
  }, [results]);

  // ══════════════════════════════════════════
  // IMAGE HANDLING
  // ══════════════════════════════════════════
  const processFile = useCallback(async (file) => {
    if (!file || !file.type.startsWith('image/')) { setError(t('mep_err_image')); return; }
    setError(''); setCompressing(true);
    try {
      const compressed = await compressImage(file, CompressionPresets.API_UPLOAD);
      setImagePreview(compressed); setImageBase64(compressed);
    } catch (err) { setError(err.message || t('mep_err_process')); }
    finally { setCompressing(false); }
  }, [t]);

  const handleImageUpload = useCallback((e) => { if (e.target.files[0]) processFile(e.target.files[0]); }, [processFile]);
  const handleDragOver = useCallback((e) => { e.preventDefault(); setIsDragging(true); }, []);
  const handleDragLeave = useCallback(() => setIsDragging(false), []);
  const handleDrop = useCallback((e) => { e.preventDefault(); setIsDragging(false); if (e.dataTransfer.files[0]) processFile(e.dataTransfer.files[0]); }, [processFile]);
  const clearImage = useCallback(() => { setImagePreview(null); setImageBase64(null); if (fileInputRef.current) fileInputRef.current.value = ''; }, []);

  // ══════════════════════════════════════════
  // TOGGLES
  // ══════════════════════════════════════════
  const toggleDietary = useCallback((val) => {
    setDietary(prev => prev.includes(val) ? prev.filter(d => d !== val) : [...prev, val]);
  }, []);

  const toggleEquipment = useCallback((val) => {
    setEquipment(prev => prev.includes(val) ? prev.filter(e => e !== val) : [...prev, val]);
  }, []);

  // ══════════════════════════════════════════
  // API
  // ══════════════════════════════════════════
  const plan = useCallback(async () => {
    if (!ingredients.trim() && !imageBase64) { setError(t('mep_err_ingredients')); return; }
    setError(''); setResults(null);
    try {
      const data = await callToolEndpoint('mise-en-place', {
        imageBase64: imageBase64 || null,
        ingredients: ingredients.trim() || null,
        servings, dietary, timeAvailable: `${timeAvailable} minutes`,
        skillLevel, equipment, mealType,
        preferences: preferences.trim() || null,
        userLocale, userCurrency, userRegion,
      });
      setResults(data);
      saveToHistory(data);
    } catch (err) { setError(err.message || t('mep_err_plan')); }
  }, [ingredients, imageBase64, servings, dietary, timeAvailable, skillLevel, equipment, mealType, preferences, callToolEndpoint, userLocale, userCurrency, userRegion, t]);

  const loadExample = useCallback(() => {
    setIngredients(EXAMPLE.ingredients);
    setServings(EXAMPLE.servings);
    setTimeAvailable(EXAMPLE.timeAvailable);
    setSkillLevel(EXAMPLE.skillLevel);
    setMealType(EXAMPLE.mealType);
    setPreferences(EXAMPLE.preferences);
    setResults(null);
  }, [setResults]);

  const handleReset = useCallback(() => {
    clearImage(); setIngredients(''); setPreferences('');
    setResults(null); setError('');
  }, [clearImage]);

  // ══════════════════════════════════════════
  // HISTORY
  // ══════════════════════════════════════════
  const saveToHistory = useCallback((data) => {
    const entry = {
      id: `mep_${Date.now()}`, date: new Date().toISOString(),
      meal: data.selected_meal?.name || data.meals?.[0]?.name || t('mep_meal_plan'),
      totalTime: data.battle_plan?.total_time || '',
      results: data,
      // PF-25 exception: 40-char preview-text truncation; session history is capped at 6.
      preview: (data.selected_meal?.name || data.meals?.[0]?.name || t('mep_meal_plan')).slice(0, 40),
    };
    setSessionHistory(prev => [entry, ...prev].slice(0, 6));
  }, [setSessionHistory, t]);

  // ══════════════════════════════════════════
  // COPY
  // ══════════════════════════════════════════
  const buildFullText = useCallback(() => {
    if (!results) return '';
    const lines = [`🍳 ${t('mep_copy_header')}`, ''];
    if (results.selected_meal) lines.push(`${t('mep_copy_making')} ${results.selected_meal.name}`, results.selected_meal.reason, '');
    if (results.battle_plan?.phases) {
      lines.push(t('mep_copy_timeline'));
      results.battle_plan.phases.forEach(p => {
        lines.push(`[${p.time_mark}] ${p.action} (${p.duration})`);
        if (p.parallel_task) lines.push(`  ↳ ${t('mep_copy_meanwhile')} ${p.parallel_task}`);
      });
      lines.push('');
    }
    if (results.shopping_list?.essential?.length) {
      lines.push(t('mep_copy_quickshop'), ...results.shopping_list.essential.map(i => `  • ${i}`), '');
    }
    lines.push(BRAND);
    return lines.join('\n');
  }, [results, t]);

  useRegisterActions(buildFullText(), tool?.title || 'Mise en Place');

  // ── Keyboard shortcut ──
  const handleSubmitRef = useRef(null);
  const canSubmitRef = useRef(false);
  handleSubmitRef.current = plan;
  canSubmitRef.current = !!(ingredients.trim() || imageBase64);

  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if ((e.metaKey || e.ctrlKey) && e.key === 'Enter' && !loading && canSubmitRef.current) {
        e.preventDefault();
        handleSubmitRef.current?.();
      }
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, [loading]);

  // ══════════════════════════════════════════
  // RENDER HELPERS
  // ══════════════════════════════════════════
  const Pill = ({ active, onClick, children }) => (
    <button onClick={onClick}
      className={`px-3 py-1.5 rounded-lg border text-xs font-semibold transition-all ${active ? c.pillActive : c.pillInactive}`}>
      {active && <span className="mr-1">✓</span>}{children}
    </button>
  );

  const Section = ({ title, emoji, open, onToggle, badge, children }) => (
    <div className={`${c.card} border ${c.border} rounded-xl shadow-sm overflow-hidden`}>
      <button onClick={onToggle} className="w-full flex items-center justify-between p-5 text-left hover:opacity-80">
        <div className="flex items-center gap-3">
          <span className="text-lg">{emoji}</span>
          <span className={`text-base font-semibold ${c.text}`}>{title}</span>
          {badge && <span className={`text-xs px-2 py-0.5 rounded-full ${c.badge}`}>{badge}</span>}
        </div>
        <span className={`text-xs ${c.textMuted}`}>{open ? '▲' : '▼'}</span>
      </button>
      {open && <div className={`px-5 pb-5 border-t ${c.border}`}>{children}</div>}
    </div>
  );

  // ══════════════════════════════════════════
  // RENDER: Input
  // ══════════════════════════════════════════
  const renderInput = () => (
    <div className="space-y-4">
      {/* Ingredients */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5`}>
        <label className={`text-base font-bold ${c.text} mb-1 block`}>{t('mep_kitchen_q')} <span className={c.required}>*</span></label>
        <p className={`text-sm ${c.textMuted} mb-4`}>{t('mep_kitchen_help')}</p>
        <textarea value={ingredients} onChange={e => setIngredients(e.target.value)}
          placeholder={t('mep_kitchen_ph')}
          className={`w-full h-24 p-4 border-2 rounded-xl ${c.input} outline-none focus:ring-2 resize-none text-sm`} />
      </div>

      {/* Fridge photo */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5`}>
        <label className={`text-xs font-bold ${c.textSecondary} uppercase tracking-wide mb-3 block`}>📷 {t('mep_photo_label')}</label>
        {compressing ? (
          <div className={`border-2 border-dashed rounded-xl p-6 text-center ${c.dropActive}`}>
            <span className="animate-spin inline-block text-2xl mb-2">{tool?.icon ?? '🍳'}</span>
            <p className={`text-sm font-semibold ${c.text}`}>{t('mep_processing')}</p>
          </div>
        ) : !imagePreview ? (
          <div className={`border-2 border-dashed rounded-xl p-5 text-center transition-colors ${isDragging ? c.dropActive : c.dropzone}`}
            onDragOver={handleDragOver} onDragLeave={handleDragLeave} onDrop={handleDrop}>
            <input ref={fileInputRef} type="file" accept="image/*" onChange={handleImageUpload} className="hidden" id="mep-upload" />
            <span className="text-2xl block mb-2">🥑</span>
            <label htmlFor="mep-upload" className={`px-4 py-2 rounded-lg text-xs font-bold cursor-pointer ${c.btnPrimary}`}>{t('mep_upload_photo')}</label>
            <p className={`text-xs ${c.textMuted} mt-2`}>{isDragging ? t('mep_drop_it') : t('mep_snap_fridge')}</p>
          </div>
        ) : (
          <div className="relative">
            <img src={imagePreview} alt={t('mep_img_alt')} className={`w-full max-h-48 object-contain rounded-xl border ${c.border}`} />
            <button onClick={clearImage} className="absolute top-2 right-2 bg-red-500 hover:bg-red-600 text-white px-2 py-1 rounded-lg text-xs font-bold">✕</button>
          </div>
        )}
      </div>

      {/* Settings grid */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5 space-y-4`}>
        <div>
          <label className={`text-xs font-bold ${c.textSecondary} uppercase tracking-wide mb-2 block`}>🍽️ {t('mep_meal_type')}</label>
          <div className="flex flex-wrap gap-1.5">
            {MEAL_OPTIONS.map(opt => (
              <Pill key={opt.value} active={mealType === opt.value} onClick={() => setMealType(opt.value)}>{opt.emoji} {t(opt.key)}</Pill>
            ))}
          </div>
        </div>

        <div>
          <label className={`text-xs font-bold ${c.textSecondary} uppercase tracking-wide mb-2 block`}>⏱️ {t('mep_time_available')}</label>
          <div className="flex flex-wrap gap-1.5">
            {TIME_OPTIONS.map(opt => (
              <Pill key={opt.value} active={timeAvailable === opt.value} onClick={() => setTimeAvailable(opt.value)}>{opt.emoji} {t(opt.key)}</Pill>
            ))}
          </div>
        </div>

        <div>
          <label className={`text-xs font-bold ${c.textSecondary} uppercase tracking-wide mb-2 block`}>🔰 {t('mep_skill_level')}</label>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
            {SKILL_OPTIONS.map(opt => (
              <button key={opt.value} onClick={() => setSkillLevel(opt.value)}
                className={`p-3 rounded-xl border-2 text-left transition-all ${
                  skillLevel === opt.value ? `${c.pillActive} border-[rgb(74,106,138)]` : `${c.card} hover:border-[rgb(138,130,117)]`
                }`}>
                <span className={`text-sm font-medium ${skillLevel === opt.value ? '' : c.textSecondary}`}>{opt.emoji} {t(opt.key)}</span>
                <p className={`text-xs mt-0.5 ${c.textMuted}`}>{t(opt.descKey)}</p>
              </button>
            ))}
          </div>
        </div>

        <div>
          <label className={`text-xs font-bold ${c.textSecondary} uppercase tracking-wide mb-2 block`}>🥗 {t('mep_dietary_needs')}</label>
          <div className="flex flex-wrap gap-1.5">
            {DIETARY_OPTIONS.map(opt => (
              <Pill key={opt.value} active={dietary.includes(opt.value)} onClick={() => toggleDietary(opt.value)}>{t(opt.key)}</Pill>
            ))}
          </div>
        </div>

        <div>
          <label className={`text-xs font-bold ${c.textSecondary} uppercase tracking-wide mb-2 block`}>🔧 {t('mep_equipment')}</label>
          <div className="flex flex-wrap gap-1.5">
            {EQUIPMENT_OPTIONS.map(opt => (
              <Pill key={opt.value} active={equipment.includes(opt.value)} onClick={() => toggleEquipment(opt.value)}>{t(opt.key)}</Pill>
            ))}
          </div>
        </div>

        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className={`text-xs font-bold ${c.textSecondary} uppercase tracking-wide mb-1 block`}>👥 {t('mep_servings')}</label>
            <input type="text" value={servings} onChange={e => setServings(e.target.value)}
              placeholder={t('mep_servings_ph')} className={`w-full px-3 py-2 rounded-xl border text-sm ${c.input} outline-none`} />
          </div>
          <div>
            <label className={`text-xs font-bold ${c.textSecondary} uppercase tracking-wide mb-1 block`}>💬 {t('mep_preferences')}</label>
            <input type="text" value={preferences} onChange={e => setPreferences(e.target.value)}
              placeholder={t('mep_preferences_ph')} className={`w-full px-3 py-2 rounded-xl border text-sm ${c.input} outline-none`} />
          </div>
        </div>
      </div>

        <button onClick={plan}
      disabled={loading || (!ingredients.trim() && !imageBase64)}
      className={`w-full py-4 rounded-2xl text-sm font-bold flex items-center justify-center gap-2 transition-all ${
        loading || (!ingredients.trim() && !imageBase64) ? `${c.btnSecondary} opacity-50` : c.btnPrimary
      } disabled:opacity-40`}>
      {loading ? <><span className="animate-spin inline-block">{tool?.icon ?? '🍳'}</span> {t('mep_building')}</>
        : <><span>🍳</span> {t('mep_build_btn')}</>}
      </button>
    </div>
  );

  // ══════════════════════════════════════════
  // RENDER: Battle Plan Timeline
  // ══════════════════════════════════════════
  const renderBattlePlan = () => {
    const bp = results?.battle_plan;
    if (!bp?.phases?.length) return null;

    return (
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5`}>
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <span className="text-lg">⚔️</span>
            <span className={`text-base font-bold ${c.text}`}>{t('mep_battle_plan')}</span>
          </div>
          {bp.total_time && <span className={`text-xs font-bold px-3 py-1 rounded-full ${c.badge}`}>🕐 {bp.total_time}</span>}
        </div>

        <div className="relative">
          {/* Timeline line */}
          <div className={`absolute left-3 top-3 bottom-3 w-0.5 ${c.timelineLine}`} />

          <div className="space-y-3">
            {bp.phases.map((phase, idx) => (
              <div key={idx} className={`relative pl-9 ${phase.critical_timing ? '' : ''}`}>
                {/* Dot */}
                <div className={`absolute left-1.5 top-3 w-3 h-3 rounded-full ${phase.critical_timing ? 'bg-[rgb(181,74,63)]' : c.timelineDot}`} />

                <div className={`p-4 rounded-xl border ${phase.critical_timing ? c.criticalBg : c.timelineBg}`}>
                  <div className="flex items-center gap-2 mb-1 flex-wrap">
                    <span className={`text-xs font-mono font-bold ${c.textMuted}`}>{phase.time_mark}</span>
                    <span className={`text-xs px-2 py-0.5 rounded-full ${c.badge}`}>{phase.duration}</span>
                    {phase.critical_timing && <span className={`text-xs font-bold ${c.criticalText}`}>⏰ {t('mep_timing_critical')}</span>}
                  </div>
                  <p className={`text-sm font-semibold ${c.text} mb-1`}>{phase.action}</p>
                  {phase.details && <p className={`text-xs ${c.textSecondary}`}>{phase.details}</p>}
                  {phase.parallel_task && (
                    <div className={`mt-2 p-2 rounded-lg border ${c.parallelBg}`}>
                      <p className={`text-xs ${c.parallelText}`}>↳ <strong>{t('mep_meanwhile')}</strong> {phase.parallel_task}</p>
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Checkpoints */}
        {bp.checkpoints?.length > 0 && (
          <div className="mt-4 space-y-2">
            <p className={`text-xs font-bold ${c.textMuted} uppercase`}>🔍 {t('mep_checkpoints')}</p>
            {bp.checkpoints.map((cp, idx) => (
              <div key={idx} className={`p-3 rounded-lg ${c.inset}`}>
                <p className={`text-xs ${c.text}`}>
                  <strong className={c.textMuted}>@{cp.at}:</strong> {cp.check}
                </p>
                {cp.if_not_ready && <p className={`text-xs ${c.textMuted} mt-0.5`}>{t('mep_if_not_ready')} {cp.if_not_ready}</p>}
              </div>
            ))}
          </div>
        )}
      </div>
    );
  };

  // ══════════════════════════════════════════
  // RENDER: Results
  // ══════════════════════════════════════════
  const renderResults = () => {
    if (!results) return null;

    return (
      <div ref={resultsRef} className="space-y-4 mt-4">
        {/* Selected Meal header */}
        {results.selected_meal && (
          <div className={`p-5 rounded-2xl border-2 ${c.tipBg}`}>
            <div className="flex items-center gap-2 mb-2">
              <span className="text-lg">👨‍🍳</span>
              <span className={`text-sm font-bold ${c.tipText}`}>{t('mep_tonights_move')}</span>
            </div>
            <p className={`text-lg font-bold ${c.text}`}>{results.selected_meal.name}</p>
            <p className={`text-sm ${c.tipText} mt-1`}>{results.selected_meal.reason}</p>
          </div>
        )}

        {/* Detected ingredients */}
        {results.detected_ingredients?.length > 0 && (
          <div className={`p-4 rounded-xl ${c.inset}`}>
            <p className={`text-xs font-bold ${c.textMuted} mb-2`}>🥑 {t('mep_working_with')}</p>
            <div className="flex flex-wrap gap-1.5">
              {results.detected_ingredients.map((ing, i) => (
                <span key={i} className={`px-2 py-0.5 rounded text-xs font-medium ${c.badge}`}>{ing}</span>
              ))}
            </div>
          </div>
        )}

        {/* Meal options */}
        {results.meals?.length > 0 && (
          <Section title={t('mep_meal_options')} emoji="🍽️" open={showMeals} onToggle={() => setShowMeals(!showMeals)}
            badge={t('mep_ideas', { count: results.meals.length })}>
            <div className="space-y-3 mt-4">
              {results.meals.map((meal, idx) => (
                <div key={idx} className={`p-4 rounded-xl border ${c.cardAlt}`}>
                  <div className="flex items-center justify-between mb-1">
                    <span className={`text-sm font-bold ${c.text}`}>{meal.name}</span>
                    <div className="flex gap-1.5">
                      {meal.total_time && <span className={`text-xs px-2 py-0.5 rounded-full ${c.badge}`}>🕐 {meal.total_time}</span>}
                      {meal.difficulty && <span className={`text-xs px-2 py-0.5 rounded-full ${c.badge}`}>{meal.difficulty}</span>}
                    </div>
                  </div>
                  <p className={`text-xs ${c.textSecondary} mb-2`}>{meal.description}</p>
                  <p className={`text-xs ${c.textMuted} italic`}>💡 {meal.why_this_works}</p>
                  {meal.flavor_tags?.length > 0 && (
                    <div className="flex flex-wrap gap-1 mt-2">
                      {meal.flavor_tags.map((tag, i) => (
                        <span key={i} className={`text-[10px] px-1.5 py-0.5 rounded ${c.pillInactive}`}>{tag}</span>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </Section>
        )}

        {/* THE BATTLE PLAN */}
        {renderBattlePlan()}

        {/* Shopping list */}
        {results.shopping_list && (
          <Section title={t('mep_shopping_title')} emoji="🛒" open={showShopping}
            onToggle={() => setShowShopping(!showShopping)}>
            <div className="mt-4 space-y-3">
              {results.shopping_list.essential?.length > 0 && (
                <div>
                  <p className={`text-xs font-bold ${c.label} mb-1`}>{t('mep_essential')}</p>
                  {results.shopping_list.essential.map((item, i) => (
                    <p key={i} className={`text-sm ${c.text} mb-0.5`}>• {item}</p>
                  ))}
                </div>
              )}
              {results.shopping_list.nice_to_have?.length > 0 && (
                <div>
                  <p className={`text-xs font-bold ${c.textMuted} mb-1`}>{t('mep_nice_to_have')}</p>
                  {results.shopping_list.nice_to_have.map((item, i) => (
                    <p key={i} className={`text-sm ${c.textMuted} mb-0.5`}>• {item}</p>
                  ))}
                </div>
              )}
            </div>
          </Section>
        )}

        {/* Technique Tips */}
        {results.technique_tips?.length > 0 && (
          <Section title={t('mep_pro_tips')} emoji="💡" open={showTips} onToggle={() => setShowTips(!showTips)}>
            <div className="space-y-3 mt-4">
              {results.technique_tips.map((tip, idx) => (
                <div key={idx} className={`p-4 rounded-xl border ${c.tipBg}`}>
                  <p className={`text-sm font-semibold ${c.tipText} mb-1`}>{tip.tip}</p>
                  <p className={`text-xs ${c.tipText}`}>{tip.why}</p>
                  <span className={`text-[10px] ${c.textMuted} mt-1 block`}>{t('mep_level_suffix', { level: tip.skill_level })}</span>
                </div>
              ))}
            </div>
          </Section>
        )}

        {/* Leftovers */}
        {results.leftovers_strategy && (
          <Section title={t('mep_leftovers_title')} emoji="♻️" open={showLeftovers}
            onToggle={() => setShowLeftovers(!showLeftovers)}>
            <div className="mt-4 space-y-2">
              <p className={`text-xs ${c.textMuted}`}>📦 <strong>{t('mep_storage')}</strong> {results.leftovers_strategy.storage}</p>
              <div className={`p-4 rounded-xl border ${c.success}`}>
                <p className={`text-sm font-bold ${c.success} mb-1`}>🔄 {t('mep_transform')} {results.leftovers_strategy.transform_into}</p>
                <p className={`text-xs ${c.success}`}>{results.leftovers_strategy.instructions}</p>
              </div>
            </div>
          </Section>
        )}

        {results.scaling_notes && (
          <div className={`p-3 rounded-xl ${c.inset}`}>
            <p className={`text-xs ${c.textMuted}`}>📏 <strong>{t('mep_scaling')}</strong> {results.scaling_notes}</p>
          </div>
        )}

      </div>
    );
  };

  // History
  const renderHistory = () => {
    if (sessionHistory.length === 0) return null;
    const formatDate = (iso) => {
      try { const d = new Date(iso); const diff = Math.floor((new Date() - d) / 86400000); return diff === 0 ? t('mep_today') : diff === 1 ? t('mep_yesterday') : diff < 7 ? t('mep_days_ago', { count: diff }) : d.toLocaleDateString(userLocale || undefined, { month: 'short', day: 'numeric' }); } catch { return ''; }
    };
    return (
      <div className={`mt-6 p-4 rounded-2xl border ${c.histBg}`}>
        <button onClick={() => setShowHistory(!showHistory)} className="w-full flex items-center gap-2 text-left">
          <span className={`text-base ${c.histAccent}`}>🍳</span>
          <span className={`text-sm font-bold ${c.text} flex-1`}>{t('mep_past_plans')}</span>
          <span className={`text-xs ${c.textMuted}`}>{sessionHistory.length}</span>
          <span className={`text-xs ${c.textMuted}`}>{showHistory ? '▲' : '▼'}</span>
        </button>
        {showHistory && (
          <div className="mt-3 space-y-2">
            {sessionHistory.map(entry => (
              <div key={entry.id} className={`rounded-xl border ${c.histCard} p-3 flex items-center gap-3`}>
                <div className="flex-1 min-w-0">
                  <div className={`text-sm font-semibold ${c.text} truncate`}>{entry.meal}</div>
                  <div className={`text-xs ${c.textMuted} mt-0.5`}>{formatDate(entry.date)}{entry.totalTime ? ` · ${entry.totalTime}` : ''}</div>
                </div>
                <button onClick={() => { setResults(entry.results); setShowHistory(false); }}
                  className={`px-3 py-1.5 rounded-lg text-xs font-bold ${c.btnSecondary}`}>{t('mep_view')}</button>
                <button onClick={() => setSessionHistory(prev => prev.filter(h => h.id !== entry.id))}
                  className={`px-2 py-1.5 rounded-lg text-xs ${c.btnSecondary} ${c.deleteHover}`}>🗑️</button>
              </div>
            ))}
          </div>
        )}

        <p className={`text-xs ${c.textMuted} mt-3`}>
          {t('mep_hist_xref_q')} <a href="/RecipeChaosSolver" className={linkStyle}>🍳 {t('mep_recipechaos')}</a> {t('mep_hist_xref_tail')}
        </p>
      </div>
    );
  };


  return (
    <div className={`space-y-4 ${c.text}`}>

      {/* ── Persistent Header ── */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm`}>
        <div className="px-5 pt-5">
          <div className="pb-3 border-b border-zinc-500 flex items-start justify-between gap-3">
            <div>
              <h2 className={`text-xl font-bold ${c.text}`}>
                <span className="mr-2">{tool?.icon ?? '🍳'}</span>{tool?.title ?? t('mep_title')}
              </h2>
              <p className={`text-sm ${c.textSecondary}`}>{tool?.tagline ?? t('mep_tagline')}</p>
              <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className={`mt-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium border disabled:opacity-40 ${isDark ? 'text-white border-white/40' : 'text-gray-800 border-transparent'}`}>{t('try_example')}</button>
            </div>
            {(results || ingredients.trim()) && (
              <button onClick={handleReset} className={`flex-shrink-0 ${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs font-medium`}>
                ↺ {t('start_over')}
              </button>
            )}
          </div>
        </div>
        <div className="p-5">
          {error && (
            <div className={`${c.danger} border rounded-xl p-4 flex items-start gap-3`}>
              <span>⚠️</span>
              <p className="text-sm">{error}</p>
            </div>
          )}
        </div>
      </div>

      {!results && (
        <p className={`text-xs ${c.textMuted}`}>
          {t('mep_pre_xref_q')} <a href="/TaskAvalancheBreaker" className={linkStyle}>⛏️ {t('mep_taskavalanche')}</a> {t('mep_pre_xref_tail')}
        </p>
      )}

      {!results && renderInput()}
      {results && renderResults()}
      {renderHistory()}

      {/* Disclaimer */}
      <div className={`${c.cardAlt} border ${c.border} rounded-xl p-3 text-center`}>
        <p className={`text-xs ${c.textMuted}`}>
          {t('mep_disclaimer')}
        </p>
      </div>

      {/* Cross-refs */}
      <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
        <p className={`text-[10px] font-bold ${c.textMuted} uppercase mb-2`}>🔗 {t('mep_related')}</p>
        <div className="flex flex-wrap gap-3">
          <a href="/PlotTwist" className={`text-xs ${linkStyle}`}>🔀 {t('mep_plottwist')}</a>
          <a href="/GhostWriter" className={`text-xs ${linkStyle}`}>✍️ {t('mep_ghostwriter')}</a>
        </div>
      </div>

    </div>
  );
};

MiseEnPlace.displayName = 'MiseEnPlace';
export default MiseEnPlace;
