import React, { useState, useCallback, useEffect, useRef } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

const LANGUAGE_FLAGS = {
  'English': '🇬🇧', 'Japanese': '🇯🇵', 'German': '🇩🇪', 'Portuguese': '🇧🇷',
  'Danish': '🇩🇰', 'Korean': '🇰🇷', 'Finnish': '🇫🇮', 'Welsh': '🏴',
  'Swedish': '🇸🇪', 'French': '🇫🇷', 'Spanish': '🇪🇸', 'Italian': '🇮🇹',
  'Norwegian': '🇳🇴', 'Czech': '🇨🇿', 'Arabic': '🇸🇦', 'Hindi': '🇮🇳',
  'Greek': '🇬🇷', 'Russian': '🇷🇺', 'Turkish': '🇹🇷', 'Tagalog': '🇵🇭',
};

// ════════════════════════════════════════════════════════════
// COMPONENT
// ════════════════════════════════════════════════════════════
const NameThatFeeling = ({ tool }) => {
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();

  const STARTER_PROMPTS = [
    t('ntf_starter1'),
    t('ntf_starter2'),
    t('ntf_starter3'),
    t('ntf_starter4'),
    t('ntf_starter5'),
    t('ntf_starter6'),
    t('ntf_starter7'),
    t('ntf_starter8'),
  ];

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20'
                          : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-400' : 'text-gray-500',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white'
                          : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200'
                          : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200'
                          : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200'
                          : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200'
                          : 'bg-red-50 border-red-200 text-red-800',
    required:      isDark ? 'text-amber-400' : 'text-amber-700',
    // Tool-specific display keys
    warm:          isDark ? 'bg-amber-900/20 border-amber-700/50' : 'bg-amber-50 border-amber-200',
    quoteBg:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    world:         isDark ? 'bg-sky-900/20 border-sky-700/50' : 'bg-sky-50 border-sky-200',
    poetic:        isDark ? 'bg-amber-900/20 border-amber-700/50' : 'bg-amber-50 border-amber-200',
    hug:           isDark ? 'bg-emerald-900/20 border-emerald-700/50' : 'bg-emerald-50 border-emerald-200',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';

  // ── Refs ──
  const resultsRef = useRef(null);
  const runSearchRef = useRef(null);
  const canSubmitRef = useRef(false);

  // ── State ──
  const [description, setDescription] = useState('');
  const [context, setContext] = useState('');
  const [results, setResults] = usePersistentState('namethatfeeling-result', null);
  const [sessionHistory, setSessionHistory] = usePersistentState('namethatfeeling-history', []);
  const [error, setError] = useState('');

  // ── API ──
  const runSearch = useCallback(async () => {
    if (!description.trim()) return;
    setError('');
    setResults(null);
    try {
      const data = await callToolEndpoint('name-that-feeling', {
        description: description.trim(),
        context: context.trim() || undefined,
        userLocale, userCurrency, userRegion,
      });
      setResults(data)
      // PF-25 exception: 40-char preview-text truncation; session history is capped at 6.
      setSessionHistory(prev => [{ id: Date.now(), date: new Date().toISOString(), preview: (description || '').slice(0, 40) }, ...prev].slice(0, 6));
    } catch (err) {
      setError(err.message || t('ntf_error'));
    }
  }, [description, context, callToolEndpoint, setResults, setSessionHistory, userLocale, userCurrency, userRegion, t]);

  const loadExample = useCallback(() => {
    setDescription(t('ntf_ex_desc'));
    setContext(t('ntf_ex_context'));
    setResults(null);
  }, [setResults, t]);

  // ── Build text ──
  const buildFullText = useCallback(() => {
    if (!results) return '';
    const lines = [`🎭 NameThatFeeling`, '', `"${description}"`, ''];
    if (results?.best_match) {
      lines.push(`✨ ${t('ntf_copy_best')} ${results?.best_match?.word} (${results?.best_match?.language})`);
      lines.push(results?.best_match?.definition, '');
    }
    if (results?.close_matches?.length) {
      lines.push(`🎯 ${t('ntf_copy_close')}`);
      results?.close_matches?.forEach(m => {
        lines.push(`  ${LANGUAGE_FLAGS[m.language] || '🌍'} ${m.word} (${m.language})`);
        lines.push(`  ${m.definition}`);
        if (m.what_it_misses) lines.push(`  ${t('ntf_copy_missing')} ${m.what_it_misses}`);
      });
      lines.push('');
    }
    if (results?.from_other_languages?.length) {
      lines.push(t('ntf_copy_other'));
      results?.from_other_languages?.forEach(w => {
        lines.push(`  ${LANGUAGE_FLAGS[w.language] || '🌍'} ${w.word} (${w.language}) — ${w.actual_meaning}`);
      });
      lines.push('');
    }
    if (results?.the_poetic_name) lines.push(`🪶 "${results?.the_poetic_name}"`);
    if (results?.you_are_not_alone) lines.push('', results?.you_are_not_alone);
    if (results?.share_line) lines.push('', `📸 ${results?.share_line}`);
    return lines.join('\n') + BRAND;
  }, [results, description, t]);

  // Ref assignments — always fresh
  runSearchRef.current = runSearch;
  canSubmitRef.current = !!description.trim();

  useRegisterActions(buildFullText(), tool?.title || t('ntf_title'));

  // ── Scroll to results ──
  useEffect(() => {
    if (!results || !resultsRef.current) return;
    const timer = setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 200);
    return () => clearTimeout(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [results]);

  // ── Keyboard submit ──
  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && !loading && canSubmitRef.current)
        runSearchRef.current?.();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading]);

  const getFlag = (lang) => LANGUAGE_FLAGS[lang] || '🌍';

  // ════════════════════════════════════════════════════════════
  // RENDER
  // ════════════════════════════════════════════════════════════
  return (
    <div className={`space-y-4 ${c.text}`}>
      {/* ── Input ── */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm`}>
        <div className="px-5 pt-5">
          <div className="pb-3 border-b border-zinc-500">
            <h2 className={`text-xl font-bold ${c.text}`}>
              <span className="me-2">{tool?.icon ?? '🎭'}</span>{tool?.title ?? t('ntf_title')}
            </h2>
            <p className={`text-sm ${c.textSecondary}`}>{tool?.tagline ?? t('ntf_tagline')}</p>
            <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className={`mt-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium border disabled:opacity-40 ${isDark ? 'text-white border-white/40' : 'text-gray-800 border-transparent'}`}>{t('try_example')}</button>
          </div>
        </div>
        <div className="px-5 pb-5 pt-4 space-y-4">

        {/* Description */}
        <div>
          <label className={`text-sm font-medium ${c.labelText} block mb-1.5`}>{t('ntf_q_label')} <span className={c.required}>*</span></label>
          <textarea
            value={description}
            onChange={e => setDescription(e.target.value)}
            placeholder={t('ntf_ph_desc')}
            rows={4}
            className={`w-full px-3 py-2.5 border rounded-lg text-sm ${c.input} outline-none focus:ring-2 resize-none`}
          />
        </div>

        {/* Starters */}
        <div>
          <p className={`text-[10px] font-bold ${c.labelText} uppercase mb-1.5`}>{t('ntf_starters_label')}</p>
          <div className="flex flex-wrap gap-1.5">
            {STARTER_PROMPTS.map((s, i) => (
              <button
                key={i}
                onClick={() => setDescription(s)}
                className={`${c.btnSecondary} px-2.5 py-1.5 rounded-lg text-[11px] font-medium min-h-[28px] text-start`}
              >
                {s.length > 50 ? s.slice(0, 50) + '...' : s}
              </button>
            ))}
          </div>
        </div>

        {/* Optional context */}
        <details className={`mb-5 ${c.textSecondary}`}>
          <summary className={`text-xs font-bold cursor-pointer ${c.accentTxt} mb-2`}>{t('ntf_add_context')}</summary>
          <input
            type="text"
            value={context}
            onChange={e => setContext(e.target.value)}
            placeholder={t('ntf_ph_context')}
            className={`w-full px-3 py-2 border rounded-lg text-sm ${c.input} outline-none focus:ring-2 mt-2`}
          />
        </details>

        <button
          onClick={runSearch}
          disabled={!description.trim() || loading}
          className={`w-full ${c.btnPrimary} disabled:opacity-40 font-bold py-3 rounded-lg flex items-center justify-center gap-2 min-h-[48px]`}
        >
          {loading
            ? <><span className="inline-block animate-spin">{tool?.icon ?? '🎭'}</span> {t('ntf_searching')}</>
            : <><span className="me-1">{tool?.icon ?? '🎭'}</span> {t('ntf_submit')}</>}
        </button>
        <p className={`text-xs ${c.textMuted}`}>{t('ntf_xref_pre')} <a href="/SpiralStopper" className={linkStyle}>🌀 {t('ntf_spiralstopper')}</a> {t('ntf_xref_post')}</p>
        </div>
      </div>

      {/* ── Error ── */}
      {error && (
        <div className={`${c.danger} border rounded-lg p-4 flex items-start gap-3`}>
          <span className="flex-shrink-0">⚠️</span>
          <p className="text-sm">{error}</p>
        </div>
      )}

      {/* ── Results ── */}
      {results && (
        <div ref={resultsRef} className="space-y-4">

          {/* Best match */}
          {results?.best_match && (
            <div className={`${c.warm} border-2 rounded-xl p-6 text-center`}>
              <span className="text-3xl block mb-2">✨</span>
              <p className={`text-[10px] font-bold uppercase mb-1 ${c.textMuteded}`}>{t('ntf_the_word')}</p>
              <p className={`text-3xl font-black ${c.text} mb-1`}>{results?.best_match?.word}</p>
              <p className={`text-xs ${c.textMuteded} mb-3`}>
                {getFlag(results?.best_match?.language)} {results?.best_match?.language}
                {results?.best_match?.pronunciation && ` · ${results?.best_match?.pronunciation}`}
              </p>
              <p className={`text-sm max-w-md mx-auto mb-3`}>{results?.best_match?.definition}</p>
              {results?.best_match?.why_this_fits && (
                <p className={`text-xs ${c.textMuteded} italic max-w-sm mx-auto`}>{results?.best_match?.why_this_fits}</p>
              )}
            </div>
          )}

          {/* Close matches */}
          {results?.close_matches?.length > 0 && (
            <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
              <h3 className={`text-sm font-bold ${c.text} mb-3`}>🎯 {t('ntf_close_matches')}</h3>
              <div className="space-y-2">
                {results?.close_matches?.map((m, i) => (
                  <div key={i} className={`${c.quoteBg} rounded-lg p-3`}>
                    <div className="flex items-center gap-2 mb-1">
                      <span className={`text-sm font-bold ${c.text}`}>{m.word}</span>
                      <span className={`text-[9px] ${c.textMuteded}`}>{getFlag(m.language)} {m.language}</span>
                    </div>
                    <p className={`text-xs ${c.textSecondary} mb-1`}>{m.definition}</p>
                    {m.what_it_misses && (
                      <p className={`text-[10px] ${c.textMuteded} italic`}>{t('ntf_missing')} {m.what_it_misses}</p>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* From other languages */}
          {results?.from_other_languages?.length > 0 && (
            <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
              <h3 className={`text-sm font-bold ${c.text} mb-3`}>🌍 {t('ntf_other_langs')}</h3>
              <div className="space-y-3">
                {results?.from_other_languages?.map((w, i) => (
                  <div key={i} className={`${c.world} border rounded-lg p-4`}>
                    <div className="flex items-center gap-2 mb-1">
                      <span className="text-lg">{getFlag(w.language)}</span>
                      <span className={`text-lg font-black ${c.text}`}>{w.word}</span>
                    </div>
                    <p className={`text-[10px] ${c.textMuteded} mb-1`}>
                      {w.language} {w.pronunciation && `· ${w.pronunciation}`}
                      {w.literal_meaning && ` · ${t('ntf_lit')} "${w.literal_meaning}"`}
                    </p>
                    <p className={`text-sm mb-1.5`}>{w.actual_meaning}</p>
                    {w.beauty_note && (
                      <p className={`text-xs ${c.textMuteded} italic`}>💎 {w.beauty_note}</p>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* The poetic name */}
          {results?.the_poetic_name && (
            <div className={`${c.poetic} border-2 rounded-xl p-5 text-center`}>
              <span className="text-2xl block mb-2">🪶</span>
              <p className={`text-[10px] font-bold uppercase mb-2`}>{t('ntf_poetic_label')}</p>
              <p className={`text-lg font-bold italic`}>"{results?.the_poetic_name}"</p>
            </div>
          )}

          {/* You are not alone */}
          {results?.you_are_not_alone && (
            <div className={`${c.hug} border-2 rounded-xl p-5 text-center`}>
              <span className="text-2xl block mb-2">💚</span>
              <p className={`text-sm`}>{results?.you_are_not_alone}</p>
            </div>
          )}

          {/* Share line */}
          {results?.share_line && (
            <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
              <p className={`text-[10px] font-bold ${c.label} uppercase mb-1`}>📸 {t('ntf_share_label')}</p>
              <p className={`text-sm font-bold ${c.text}`}>{results?.share_line}</p>
            </div>
          )}

          {/* Go again */}
          <button
            onClick={() => { setResults(null); setDescription(''); setContext(''); }}
            className={`${c.btnSecondary} px-4 py-2 rounded-lg text-xs font-bold min-h-[36px]`}
          >
            {t('ntf_go_again')}
          </button>
        </div>
      )}

      {results && (
        <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
          <p className={`text-[10px] font-bold ${c.textMuted} uppercase mb-2`}>🔗 {t('ntf_related')}</p>
          <div className="flex flex-wrap gap-3">
            <a href="/SpiralStopper" className={`text-xs ${linkStyle}`}>🌀 {t('ntf_spiralstopper')}</a>
            <a href="/NerveCheck" className={`text-xs ${linkStyle}`}>🫁 {t('ntf_nervecheck')}</a>
          </div>
        </div>
      )}
      <p className={`text-xs text-center ${c.textMuted}`}>{t('ntf_disclaimer')}</p>
      {sessionHistory.length > 0 && (<div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}><p className={`text-xs font-bold ${c.textMuted} mb-2`}>📋 {t('ntf_recent')}</p><div className="space-y-1">{sessionHistory.map(s => (<div key={s.id} className="flex items-center justify-between"><span className={`text-xs ${c.textSecondary} truncate`}>{s.preview || t('ntf_session')}</span><span className={`text-xs ${c.textMuted} ms-2`}>{new Date(s.date).toLocaleDateString()}</span></div>))}</div></div>)}
    </div>
  );
};

NameThatFeeling.displayName = 'NameThatFeeling';
export default NameThatFeeling;
