import React, { useState, useMemo, useEffect, useRef, useCallback } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';
import { pickExample } from '../utils/exampleRotation';
import { revealSection } from '../utils/revealSection';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

const SIT_TYPES = [
  { value: 'interview', tkey: 'nck_sit_interview', icon: '💼' },
  { value: 'presentation', tkey: 'nck_sit_presentation', icon: '🎤' },
  { value: 'confrontation', tkey: 'nck_sit_confrontation', icon: '😤' },
  { value: 'date', tkey: 'nck_sit_date', icon: '💕' },
  { value: 'medical', tkey: 'nck_sit_medical', icon: '🏥' },
  { value: 'performance', tkey: 'nck_sit_performance', icon: '🎭' },
  { value: 'phone_call', tkey: 'nck_sit_phone_call', icon: '📞' },
  { value: 'other', tkey: 'nck_sit_other', icon: '🌀' },
];
const TIME_OPTIONS = [
  { value: 'right_now', tkey: 'nck_time_right_now', icon: '🔴' },
  { value: 'today', tkey: 'nck_time_today', icon: '🟡' },
  { value: 'tomorrow', tkey: 'nck_time_tomorrow', icon: '🟢' },
  { value: 'this_week', tkey: 'nck_time_this_week', icon: '📅' },
  { value: 'later', tkey: 'nck_time_later', icon: '🔵' },
];
const COACH_RELATIONS = [
  { value: 'child', tkey: 'nck_rel_child', icon: '👶' },
  { value: 'partner', tkey: 'nck_rel_partner', icon: '💑' },
  { value: 'friend', tkey: 'nck_rel_friend', icon: '🤝' },
  { value: 'coworker', tkey: 'nck_rel_coworker', icon: '💼' },
  { value: 'student', tkey: 'nck_rel_student', icon: '📚' },
  { value: 'other', tkey: 'nck_rel_other', icon: '🌀' },
];
const MINUTES_OPTIONS = [1, 2, 5, 10, 15];

const sitTypeMeta = (value) => SIT_TYPES.find(s => s.value === value);

// ════════════════════════════════════════════════════════════
// COMPONENT
// ════════════════════════════════════════════════════════════
const NerveCheck = ({ tool }) => {
  const { callToolEndpoint, loading } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20'
                          : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-400' : 'text-gray-500',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white'
                          : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    // Waiting for input: an outline, not a smudge. Empty fill keeps "filled"
    // meaning "ready"; the border and label carry the visibility. Important
    // modifiers because tools carry their own border/text utilities on the
    // submit and Tailwind resolves conflicts by stylesheet order, not class
    // order. See the PF-13 exception in audit/audit_v2-3-2.py.
    btnIdle:       isDark ? '!bg-transparent !border-2 !border-cyan-500/85 !text-cyan-300 cursor-not-allowed'
                          : '!bg-transparent !border-2 !border-cyan-600/85 !text-cyan-800 cursor-not-allowed',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200'
                          : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200'
                          : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200'
                          : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200'
                          : 'bg-red-50 border-red-200 text-red-800',
    required:      isDark ? 'text-amber-400' : 'text-amber-700',
    btnDanger:     isDark ? 'bg-red-700 hover:bg-red-600 text-white' : 'bg-red-600 hover:bg-red-700 text-white',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';

  // ── Refs (always-fresh pattern for the keyboard shortcut) ──
  const resultsRef = useRef(null);
  // Always-mounted, regardless of which view is showing — unlike resultsRef,
  // which only exists inside a results branch. Needed for the reframe-on-
  // view-change effect below, which has to fire for views that never attach
  // resultsRef at all (Focus Mode) and during the loading gap before a
  // results branch mounts (the Help Me Now form, before liveResults exists).
  const containerRef = useRef(null);
  const viewRef = useRef('form');
  const runMainRef = useRef(null);
  const canMainRef = useRef(false);
  const runLiveRef = useRef(null);
  const canLiveRef = useRef(false);
  const runDebriefRef = useRef(null);
  const canDebriefRef = useRef(false);
  const runCoachRef = useRef(null);
  const canCoachRef = useRef(false);

  // ── Views ──
  // form -> results -> live -> focus, or results -> debrief, or a standalone
  // coach flow. No ladder/patterns/journal views — see tool notes for why.
  const [view, setView] = useState('form');
  viewRef.current = view;

  // ── Primary input ──
  const [situation, setSituation] = useState('');
  const [situationType, setSituationType] = useState('');
  // "Confidence" renamed to "readiness" throughout, including this variable
  // name — a self-reported readiness marker that adjusts how much and how
  // immediate the preparation is, never treated as a psychological reading.
  const [readinessLevel, setReadinessLevel] = useState(4);
  const [specificFears, setSpecificFears] = useState('');
  const [timeUntil, setTimeUntil] = useState('today');
  const [results, setResults] = usePersistentState('nervecheck-result-v2', null);
  const [error, setError] = useState('');

  // ── Help Me Now ──
  const [minutesUntil, setMinutesUntil] = useState(5);
  const [liveResults, setLiveResults] = usePersistentState('nervecheck-live-result-v2', null);
  const [liveError, setLiveError] = useState('');

  // ── Focus mode ──
  const [focusStep, setFocusStep] = useState(0);

  // ── Debrief ──
  const [howItWent, setHowItWent] = useState('');
  const [readinessAfter, setReadinessAfter] = useState(6);
  const [whatSurprised, setWhatSurprised] = useState('');
  const [debriefResults, setDebriefResults] = usePersistentState('nervecheck-debrief-result-v2', null);
  const [debriefError, setDebriefError] = useState('');

  // ── Help Someone Else ──
  const [coachWho, setCoachWho] = useState('');
  const [coachSituation, setCoachSituation] = useState('');
  const [coachRelation, setCoachRelation] = useState('');
  const [coachAge, setCoachAge] = useState('adult');
  const [coachResults, setCoachResults] = usePersistentState('nervecheck-coach-result-v2', null);
  const [coachError, setCoachError] = useState('');

  // ── History — one simple list, replacing the old journal + patterns +
  // fear ladders + templates + auto check-ins. Each entry is a plan,
  // enriched in place with readinessAfter/quote once debriefed, so the
  // list shows one row per situation rather than a duplicate row per step. ──
  const [sessionHistory, setSessionHistory] = usePersistentState('nervecheck-history-v2', []);

  const matchStyle = (n) => {
    if (n >= 7) return c.success;
    if (n >= 4) return c.warning;
    return c.danger;
  };

  // ── Main plan ──
  const runMain = useCallback(async () => {
    if (!situation.trim()) return;
    setError('');
    setResults(null);
    try {
      const data = await callToolEndpoint('nerve-check', {
        situation: situation.trim(),
        situationType: situationType || undefined,
        readinessLevel,
        specificFears: specificFears.trim() || undefined,
        timeUntil,
        // Section 17.2/section on past experiences: only ever the visitor's
        // own most recent debrief for the SAME kind of situation, passed
        // verbatim — never an aggregated pattern across sessions.
        pastExperience: (() => {
          const match = sessionHistory.find(h => h.situationType === situationType && h.quote);
          return match ? `Before a past ${sitTypeMeta(match.situationType)?.value || 'similar'} situation, readiness was rated ${match.readinessBefore}/10. Afterward: ${match.quote}` : undefined;
        })(),
      });
      setResults(data);
      setSessionHistory(prev => [{
        id: Date.now(),
        date: new Date().toISOString(),
        situation: situation.trim(),
        // PF-25 exception: this 40 is string-preview truncation, not a
        // history cap — the array itself is capped at 15, right below.
        preview: situation.trim().slice(0, 40),
        situationType,
        readinessBefore: readinessLevel,
        readinessAfter: null,
        quote: '',
        planResults: data,
        debriefResults: null,
        // PF-25 exception: history is a browse/discovery list the visitor
        // can debrief or reopen from later, not a preview cap — 15, not 6.
      }, ...prev].slice(0, 15));
      setView('results');
    } catch (err) {
      setError(err.message || t('nck_err_analyze'));
    }
  }, [situation, situationType, readinessLevel, specificFears, timeUntil, sessionHistory, callToolEndpoint, setResults, setSessionHistory, t]);

  // ── Help Me Now ──
  const runLive = useCallback(async () => {
    const s = situation.trim();
    if (!s) return;
    setLiveError('');
    setLiveResults(null);
    setFocusStep(0);
    try {
      const data = await callToolEndpoint('nerve-check/live', { situation: s, minutesUntil });
      setLiveResults(data);
      setView('live');
    } catch (err) {
      setLiveError(err.message || t('nck_err_live'));
    }
  }, [situation, minutesUntil, callToolEndpoint, setLiveResults, t]);

  const goLive = useCallback(() => {
    setView('live');
    if (!liveResults) runLiveRef.current?.();
  }, [liveResults]);

  // ── Debrief ──
  const runDebrief = useCallback(async () => {
    if (!howItWent.trim()) return;
    setDebriefError('');
    setDebriefResults(null);
    try {
      const data = await callToolEndpoint('nerve-check/debrief', {
        situation: situation.trim() || undefined,
        howItWent: howItWent.trim(),
        readinessBefore: readinessLevel,
        readinessAfter,
        whatSurprised: whatSurprised.trim() || undefined,
      });
      setDebriefResults(data);
      // Enrich the matching history entry rather than adding a second row —
      // the most recent entry for this exact situation, per the mockup
      // showing one row per situation, "before" alone until debriefed.
      setSessionHistory(prev => {
        const idx = prev.findIndex(h => h.situation === situation.trim());
        if (idx === -1) return prev;
        const next = [...prev];
        next[idx] = {
          ...next[idx],
          readinessAfter,
          quote: (data.save_this || data.what_happened?.[0] || '').slice(0, 100),
          debriefResults: data,
        };
        return next;
      });
      setView('debrief-results');
    } catch (err) {
      setDebriefError(err.message || t('nck_err_debrief'));
    }
  }, [situation, howItWent, readinessLevel, readinessAfter, whatSurprised, callToolEndpoint, setDebriefResults, setSessionHistory, t]);

  // ── Help Someone Else ──
  const runCoach = useCallback(async () => {
    if (!coachSituation.trim()) return;
    setCoachError('');
    setCoachResults(null);
    try {
      const data = await callToolEndpoint('nerve-check/coach', {
        whoIsNervous: coachWho.trim() || undefined,
        theirSituation: coachSituation.trim(),
        relationship: coachRelation || undefined,
        theirAge: coachAge,
      });
      setCoachResults(data);
    } catch (err) {
      setCoachError(err.message || t('nck_err_coach'));
    }
  }, [coachWho, coachSituation, coachRelation, coachAge, callToolEndpoint, setCoachResults, t]);

  const openHistoryEntry = useCallback((entry) => {
    setSituation(entry.situation);
    setSituationType(entry.situationType || '');
    setReadinessLevel(entry.readinessBefore || 4);
    if (entry.planResults) setResults(entry.planResults);
    if (entry.debriefResults) {
      setReadinessAfter(entry.readinessAfter || 6);
      setDebriefResults(entry.debriefResults);
      setView('debrief-results');
    } else {
      setView(entry.planResults ? 'results' : 'form');
    }
  }, [setResults, setDebriefResults]);

  const removeHistoryEntry = useCallback((id) => {
    setSessionHistory(prev => prev.filter(h => h.id !== id));
  }, [setSessionHistory]);

  const resetAll = () => {
    setSituation(''); setSituationType(''); setReadinessLevel(4); setSpecificFears(''); setTimeUntil('today');
    setResults(null); setError('');
    setLiveResults(null); setLiveError('');
    setHowItWent(''); setReadinessAfter(6); setWhatSurprised(''); setDebriefResults(null); setDebriefError('');
    setView('form');
  };

  // ── Focus mode cards — a compression layer over the CURRENT liveResults,
  // never a second generation pass: every card below reuses text the main
  // call already produced, nothing new is invented for Focus specifically.
  // Fixed 5-slot structure (DO THIS FIRST / REMEMBER / SAY THIS / IF YOU
  // NEED A MOMENT / THEN GO), each card included only when the underlying
  // field is actually present — settle/tell-yourself deliberately dropped
  // from this compressed view (still shown in the full Help Me Now results
  // above Focus) to keep this to 3-5 cards, not the full result restated. ──
  const focusCards = useMemo(() => {
    if (!liveResults) return [];
    const cards = [];
    if (liveResults?.first) cards.push({ label: t('nck_focus_do_first'), text: liveResults?.first });
    if (liveResults?.remember) cards.push({ label: t('nck_focus_remember'), text: liveResults?.remember });
    if (liveResults?.words?.opening) cards.push({ label: t('nck_focus_say_this'), text: liveResults?.words.opening });
    if (liveResults?.words?.if_you_need_a_moment) cards.push({ label: t('nck_focus_if_blank'), text: liveResults?.words.if_you_need_a_moment });
    cards.push({ label: t('nck_focus_go'), text: liveResults?.go || t('nck_focus_go_default') });
    return cards;
  }, [liveResults, t]);

  // ── Build text for copy/share ──
  const buildFullText = useCallback(() => {
    if (view === 'debrief-results' && debriefResults) {
      const lines = [`🫁 ${t('nck_title')}`, '', `🧾 ${t('nck_copy_debrief_header')}`, ''];
      lines.push(debriefResults?.headline, '');
      if (debriefResults?.what_happened?.length) lines.push(t('nck_copy_what_happened'), ...debriefResults?.what_happened, '');
      if (debriefResults?.useful_evidence_for_next_time?.length) lines.push(t('nck_copy_evidence'), ...debriefResults?.useful_evidence_for_next_time, '');
      if (debriefResults?.save_this) lines.push(t('nck_copy_save_this'), debriefResults?.save_this);
      return lines.join('\n') + BRAND;
    }
    if (!results) return '';
    const lines = [`🫁 ${t('nck_title')}`, '', `"${situation}"`, ''];
    if (results?.opening) lines.push(results?.opening, '');
    if (results?.what_you_can_prepare?.length) {
      lines.push(`📋 ${t('nck_copy_prepare')}`);
      results?.what_you_can_prepare.forEach(p => lines.push(`- ${p.action}`));
      lines.push('');
    }
    if (results?.words_if_you_need_them?.length) {
      lines.push(`🗣️ ${t('nck_copy_words')}`);
      results?.words_if_you_need_them.forEach(w => lines.push(`${w.moment}: ${w.script}`));
      lines.push('');
    }
    if (results?.remember) lines.push(`📌 ${t('nck_copy_remember')}`, results?.remember, '');
    if (results?.do_this_next) lines.push(`➡️ ${t('nck_copy_next')}`, results?.do_this_next);
    return lines.join('\n') + BRAND;
  }, [results, debriefResults, view, situation, t]);

  runMainRef.current = runMain;
  canMainRef.current = !!situation.trim();
  runLiveRef.current = runLive;
  canLiveRef.current = !!situation.trim();
  runDebriefRef.current = runDebrief;
  canDebriefRef.current = !!howItWent.trim();
  runCoachRef.current = runCoach;
  canCoachRef.current = !!coachSituation.trim();

  useRegisterActions(buildFullText(), tool?.title || t('nck_title'));

  // ── Reframe on every view change ──
  // Every view in this tool is a whole-screen replacement, not content
  // appended below a form that stays visible (unlike NameAudit/NameThatFeeling,
  // where the input stays on screen and this reframe would be wrong). Switching
  // to a much shorter screen — Focus Mode's few centered lines, or the brief
  // Help Me Now form during the loading gap before liveResults exists — leaves
  // the browser's scroll position wherever it numerically was on the taller
  // previous screen, which can now land on unrelated content further down the
  // page (guides, newsletter, footer) that reads as "jumped to the bottom."
  // Framing to the tool's own section on every view change fixes this
  // regardless of content height, independent of whichever specific results
  // effect below (which only runs once real content exists).
  useEffect(() => {
    const target = containerRef.current;
    if (!target) return;
    const timer = setTimeout(() => revealSection(target, { frame: true }), 50);
    return () => clearTimeout(timer);
  }, [view]);

  // ── Scroll to results ──
  useEffect(() => {
    if (!(results || liveResults || debriefResults || coachResults)) return;
    const target = resultsRef.current;
    if (!target) return;
    const timer = setTimeout(() => revealSection(target), 150);
    return () => clearTimeout(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [results, liveResults, debriefResults, coachResults]);

  // ── Keyboard submit ──
  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (e.key !== 'Enter' || !(e.metaKey || e.ctrlKey) || loading) return;
      const v = viewRef.current;
      if (v === 'form' && canMainRef.current) runMainRef.current?.();
      else if (v === 'live' && canLiveRef.current) runLiveRef.current?.();
      else if (v === 'debrief' && canDebriefRef.current) runDebriefRef.current?.();
      else if (v === 'coach' && canCoachRef.current) runCoachRef.current?.();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, [loading]);

  const readinessLabel = (n) => n <= 3 ? t('nck_terrified') : n >= 8 ? t('nck_feeling_good') : '';

  const loadExample = useCallback(() => {
    const ex = pickExample('NerveCheck', [
      { situation: 'nck_ex_situation', fears: 'nck_ex_fears', type: 'interview' },
      { situation: 'nck_ex2_situation', fears: 'nck_ex2_fears', type: 'confrontation' },
    ]);
    setSituation(t(ex.situation));
    setSpecificFears(t(ex.fears));
    setSituationType(ex.type);
    setResults(null);
  }, [t, setResults]);

  const loadDebriefExample = useCallback(() => {
    const ex = pickExample('NerveCheckDebrief', [
      { situation: 'nck_debex_situation', how: 'nck_debex_how', surprised: 'nck_debex_surprised', before: 4, after: 7 },
      { situation: 'nck_debex2_situation', how: 'nck_debex2_how', surprised: '', before: 6, after: 3 },
    ]);
    setSituation(t(ex.situation));
    setHowItWent(t(ex.how));
    setWhatSurprised(ex.surprised ? t(ex.surprised) : '');
    setReadinessLevel(ex.before);
    setReadinessAfter(ex.after);
    setDebriefResults(null);
  }, [t, setDebriefResults]);

  const loadCoachExample = useCallback(() => {
    const ex = pickExample('NerveCheckCoach', [
      { who: 'nck_coex_who', situation: 'nck_coex_situation', relation: 'child', age: 'child' },
      { who: 'nck_coex2_who', situation: 'nck_coex2_situation', relation: 'partner', age: 'adult' },
    ]);
    setCoachWho(t(ex.who));
    setCoachSituation(t(ex.situation));
    setCoachRelation(ex.relation);
    setCoachAge(ex.age);
    setCoachResults(null);
  }, [t, setCoachResults]);

  // ════════════════════════════════════════════════════════════
  // Shared: the input recap shown at the top of a result screen
  // ════════════════════════════════════════════════════════════
  const renderRecap = () => {
    const meta = sitTypeMeta(situationType);
    return (
      <div className={`${c.cardAlt} border ${c.border} rounded-lg p-3 text-xs ${c.textSecondary} space-y-1`}>
        <p className="flex flex-wrap items-center gap-x-2 gap-y-1">
          {meta && <span>{meta.icon} {t(meta.tkey)}</span>}
          <span>{t('nck_conf_now')} {readinessLevel}/10</span>
          {timeUntil && <span>· {t(TIME_OPTIONS.find(o => o.value === timeUntil)?.tkey || 'nck_time_today')}</span>}
        </p>
        <p className="italic truncate">"{situation}"</p>
      </div>
    );
  };

  // ════════════════════════════════════════════════════════════
  // RENDER
  // ════════════════════════════════════════════════════════════
  return (
    <div ref={containerRef} className={`space-y-4 ${c.text}`}>

      {/* ═══ Header row ═══ */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm`}>
        <div className="px-5 pt-2.5">
          <div className="pb-3 border-b border-zinc-500 flex items-start justify-between gap-3">
            <div>
              <p className={`text-base ${c.textSecondary}`}>
                <span className="me-2 text-lg">{tool?.icon ?? '💪'}</span>{tool?.tagline ?? t('nck_tagline')}
              </p>
              {view === 'form' && (
                <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className="mt-2 px-4 py-2 rounded-full text-sm font-semibold border border-black/25 text-zinc-900 shadow-sm hover:brightness-105 hover:shadow transition disabled:opacity-40 whitespace-nowrap">✨ {t('try_example')}</button>
              )}
            </div>
            {(view !== 'form' || situation.trim()) && (
              <button onClick={resetAll} className={`${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs font-semibold flex-shrink-0 whitespace-nowrap`}>
                ↺ {t('start_over')}
              </button>
            )}
          </div>
        </div>

        <div className="px-5 pb-5 pt-4 space-y-4">

        {/* ── FORM VIEW ── */}
        {view === 'form' && (
          <>
            <div className="grid grid-cols-2 gap-2">
              <button onClick={goLive} className={`${c.btnDanger} rounded-lg py-2.5 text-sm font-bold`}>{t('nck_help_now')}</button>
              <button onClick={() => setView('coach')} className={`${c.btnSecondary} rounded-lg py-2.5 text-sm font-bold`}>{t('nck_help_someone')}</button>
            </div>

            <div>
              <label className={`text-sm font-medium ${c.labelText} block mb-1.5`}>{t('nck_q_label')} <span className={c.required}>*</span></label>
              <textarea value={situation} onChange={e => setSituation(e.target.value)} placeholder={t('nck_q_ph')} rows={3}
                className={`w-full px-3 py-2.5 border rounded-lg text-sm ${c.input} outline-none focus:ring-2 resize-none`} />
            </div>

            <div>
              <p className={`text-xs font-bold ${c.labelText} uppercase mb-1.5`}>{t('nck_kind_label')}</p>
              <div className="grid grid-cols-4 gap-1.5">
                {SIT_TYPES.map(s => (
                  <button key={s.value} onClick={() => setSituationType(situationType === s.value ? '' : s.value)}
                    className={`px-2 py-2 rounded-lg text-[11px] font-medium flex flex-col items-center gap-0.5 ${situationType === s.value ? c.btnPrimary : c.btnSecondary}`}>
                    <span className="text-base">{s.icon}</span>{t(s.tkey)}
                  </button>
                ))}
              </div>
            </div>

            <div>
              <label className={`text-sm font-medium ${c.labelText} block mb-1.5`}>{t('nck_conf_now')}
                <span className={`ms-2 font-bold ${c.accentTxt}`}>{readinessLevel}/10</span>
                {readinessLabel(readinessLevel) && <span className={`ms-1.5 text-xs ${c.textMuted}`}>{readinessLabel(readinessLevel)}</span>}
              </label>
              <input type="range" min="1" max="10" value={readinessLevel} onChange={e => setReadinessLevel(Number(e.target.value))} className="w-full accent-cyan-600" />
            </div>

            <div>
              <label className={`text-sm font-medium ${c.labelText} block mb-1.5`}>{t('nck_fears_label')}</label>
              <textarea value={specificFears} onChange={e => setSpecificFears(e.target.value)} placeholder={t('nck_fears_ph')} rows={2}
                className={`w-full px-3 py-2 border rounded-lg text-sm ${c.input} outline-none focus:ring-2 resize-none`} />
            </div>

            <div>
              <p className={`text-xs font-bold ${c.labelText} uppercase mb-1.5`}>{t('nck_when_label')}</p>
              <div className="flex flex-wrap gap-1.5">
                {TIME_OPTIONS.map(o => (
                  <button key={o.value} onClick={() => setTimeUntil(o.value)}
                    className={`px-3 py-1.5 rounded-lg text-xs font-medium ${timeUntil === o.value ? c.btnPrimary : c.btnSecondary}`}>
                    {o.icon} {t(o.tkey)}
                  </button>
                ))}
              </div>
            </div>

            {error && (
              <div className={`${c.danger} border rounded-lg p-3 flex items-start gap-2 text-sm`}><span>⚠️</span><p>{error}</p></div>
            )}

            <button title={t('cmd_enter')} onClick={runMain} disabled={!situation.trim() || loading}
              className={`relative w-full ${!situation.trim() ? c.btnIdle : c.btnPrimary} font-bold py-3 rounded-lg flex items-center justify-center gap-2 min-h-[48px] disabled:opacity-40`}>
              {loading
                ? <><span className="inline-block animate-spin">{tool?.icon ?? '💪'}</span> {t('nck_building_courage')}</>
                : <><span className="me-1">{tool?.icon ?? '💪'}</span> {t('nck_check_nerves')}</>}
              {!loading && (
                <kbd aria-hidden="true" className="hidden sm:flex items-center absolute end-3 top-1/2 -translate-y-1/2 px-1.5 py-0.5 rounded border border-white/30 bg-white/15 text-[10px] font-bold tracking-wide">⌘↵</kbd>
              )}
            </button>

            <p className={`text-xs ${c.textMuted}`}>
              {t('nck_rehearse_hint')} <a href="/DifficultTalkCoach" className={linkStyle}>{t('nck_xref_dtc')}</a> {t('nck_rehearse_hint_end')}
            </p>

            {sessionHistory.length > 0 && (
              <button onClick={() => setView('history')} className={`${c.btnSecondary} w-full rounded-lg py-2 text-xs font-semibold`}>
                📋 {t('nck_history')} ({sessionHistory.length})
              </button>
            )}
          </>
        )}

        {/* ── RESULTS VIEW (main plan) ── */}
        {view === 'results' && results && (
          <div ref={resultsRef} className="scroll-mt-24 space-y-4">
            <h2 className={`text-lg font-black ${c.text}`}>💪 {t('nck_heres_plan')}</h2>
            {renderRecap()}
            {results?.opening && <p className={`text-sm ${c.textSecondary}`}>{results?.opening}</p>}

            {results?.what_youre_worried_about && (
              <div className={`${c.card} border ${c.border} rounded-xl p-4 space-y-3`}>
                <h3 className={`text-sm font-bold ${c.text}`}>🎯 {t('nck_worried_about')}</h3>
                {results?.what_youre_worried_about.established?.length > 0 && (
                  <div>
                    <p className={`text-[10px] font-bold uppercase ${c.textMuted} mb-1`}>{t('nck_what_you_know')}</p>
                    <ul className="space-y-1">{results?.what_youre_worried_about.established.map((x, i) => <li key={i} className={`text-sm ${c.textSecondary}`}>• {x}</li>)}</ul>
                  </div>
                )}
                {results?.what_youre_worried_about.possible?.length > 0 && (
                  <div>
                    <p className={`text-[10px] font-bold uppercase ${c.textMuted} mb-1`}>{t('nck_what_could_happen')}</p>
                    <ul className="space-y-1">{results?.what_youre_worried_about.possible.map((x, i) => <li key={i} className={`text-sm ${c.textSecondary}`}>• {x}</li>)}</ul>
                  </div>
                )}
                {results?.what_youre_worried_about.unknown?.length > 0 && (
                  <div>
                    <p className={`text-[10px] font-bold uppercase ${c.textMuted} mb-1`}>{t('nck_what_cant_know')}</p>
                    <ul className="space-y-1">{results?.what_youre_worried_about.unknown.map((x, i) => <li key={i} className={`text-sm ${c.textSecondary}`}>• {x}</li>)}</ul>
                  </div>
                )}
              </div>
            )}

            {results?.what_you_can_prepare?.length > 0 && (
              <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
                <h3 className={`text-sm font-bold ${c.text} mb-2`}>📋 {t('nck_have_ready')}</h3>
                <div className="space-y-3">
                  {results?.what_you_can_prepare.map((p, i) => (
                    <div key={i} className={`${c.cardAlt} rounded-lg p-3`}>
                      <p className={`text-sm font-semibold ${c.text}`}>{i + 1}. {p.action}</p>
                      {p.why_it_helps_here && <p className={`text-xs ${c.textMuted} mt-1`}>{t('nck_why_helps')} {p.why_it_helps_here}</p>}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {results?.words_if_you_need_them?.length > 0 && (
              <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
                <h3 className={`text-sm font-bold ${c.text} mb-2`}>🗣️ {t('nck_words_need')}</h3>
                <div className="space-y-2">
                  {results?.words_if_you_need_them.map((w, i) => (
                    <div key={i} className={`${c.cardAlt} rounded-lg p-3`}>
                      <p className={`text-[10px] font-bold uppercase ${c.textMuted} mb-1`}>{w.moment}</p>
                      <p className={`text-sm ${c.textSecondary} italic`}>"{w.script}"</p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {results?.if_the_moment_gets_awkward?.action && (
              <div className={`${c.warning} border rounded-xl p-4`}>
                <h3 className={`text-sm font-bold mb-1`}>😬 {t('nck_gets_awkward')}</h3>
                <p className="text-sm">{results?.if_the_moment_gets_awkward.action}</p>
                {results?.if_the_moment_gets_awkward.script && <p className="text-sm italic mt-1">"{results?.if_the_moment_gets_awkward.script}"</p>}
              </div>
            )}

            {results?.settle_yourself?.length > 0 && (
              <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
                <h3 className={`text-sm font-bold ${c.text} mb-2`}>🫁 {t('nck_settle')}</h3>
                <ul className="space-y-1">{results?.settle_yourself.map((s, i) => <li key={i} className={`text-sm ${c.textSecondary}`}>• {s}</li>)}</ul>
              </div>
            )}

            {results?.remember && (
              <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
                <h3 className={`text-[10px] font-bold uppercase ${c.textMuted} mb-1`}>📌 {t('nck_remember')}</h3>
                <p className={`text-sm ${c.text}`}>{results?.remember}</p>
              </div>
            )}

            {results?.do_this_next && (
              <div className={`${c.success} border rounded-xl p-4`}>
                <h3 className={`text-[10px] font-bold uppercase mb-1`}>➡️ {t('nck_do_next')}</h3>
                <p className="text-sm font-medium">{results?.do_this_next}</p>
              </div>
            )}

            {/* Two labeled follow-up actions — not icon-only. */}
            <div className="grid grid-cols-2 gap-2">
              <button onClick={goLive} className={`${c.btnDanger} rounded-lg py-2.5 text-sm font-bold`}>🔴 {t('nck_go_live')}</button>
              <button onClick={() => setView('debrief')} className={`${c.btnSecondary} rounded-lg py-2.5 text-sm font-bold`}>📊 {t('nck_debrief_btn')}</button>
            </div>
          </div>
        )}

        {/* ── LIVE / HELP ME NOW VIEW ── */}
        {view === 'live' && (
          <div className="space-y-4">
            <h2 className={`text-lg font-black ${c.text}`}>🔴 {t('nck_live_mode')}</h2>
            {!liveResults ? (
              <>
                {!situation.trim() && (
                  <div>
                    <label className={`text-sm font-medium ${c.labelText} block mb-1.5`}>{t('nck_about_to_do_ph')} <span className={c.required}>*</span></label>
                    <textarea value={situation} onChange={e => setSituation(e.target.value)} rows={2} placeholder={t('nck_q_ph')}
                      className={`w-full px-3 py-2.5 border rounded-lg text-sm ${c.input} outline-none focus:ring-2 resize-none`} />
                  </div>
                )}
                <div>
                  <p className={`text-xs font-bold ${c.labelText} uppercase mb-1.5`}>{t('nck_minutes')}</p>
                  <div className="flex gap-1.5">
                    {MINUTES_OPTIONS.map(m => (
                      <button key={m} onClick={() => setMinutesUntil(m)} className={`px-3 py-1.5 rounded-lg text-xs font-bold ${minutesUntil === m ? c.btnDanger : c.btnSecondary}`}>{m}{t('nck_min_suffix')}</button>
                    ))}
                  </div>
                </div>
                {liveError && <div className={`${c.danger} border rounded-lg p-3 text-sm`}>{liveError}</div>}
                <button onClick={runLive} disabled={!situation.trim() || loading}
                  className={`w-full ${c.btnDanger} font-bold py-3 rounded-lg min-h-[48px] disabled:opacity-40`}>
                  {loading ? t('nck_getting_ready') : t('nck_get_ready')}
                </button>
              </>
            ) : (
              <div ref={resultsRef} className="scroll-mt-24 space-y-3">
                {renderRecap()}
                {liveResults?.first && (
                  <div className={`${c.danger} border rounded-xl p-4`}><p className="text-sm font-semibold">{liveResults?.first}</p></div>
                )}
                {liveResults?.settle?.instruction && (
                  <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
                    <h3 className={`text-[10px] font-bold uppercase ${c.textMuted} mb-1`}>🫁 {t('nck_focus_settle')}</h3>
                    <p className={`text-sm ${c.textSecondary}`}>{liveResults?.settle.instruction}</p>
                  </div>
                )}
                {(liveResults?.words?.to_yourself || liveResults?.words?.opening || liveResults?.words?.if_you_need_a_moment) && (
                  <div className={`${c.card} border ${c.border} rounded-xl p-4 space-y-2`}>
                    <h3 className={`text-sm font-bold ${c.text}`}>🎬 {t('nck_your_lines')}</h3>
                    {liveResults?.words.to_yourself && <p className={`text-sm ${c.textSecondary}`}><span className={`text-[10px] font-bold uppercase ${c.textMuted}`}>{t('nck_tell_yourself')}: </span>{liveResults?.words.to_yourself}</p>}
                    {liveResults?.words.opening && <p className={`text-sm ${c.textSecondary}`}><span className={`text-[10px] font-bold uppercase ${c.textMuted}`}>{t('nck_first_thing_say')}: </span>"{liveResults?.words.opening}"</p>}
                    {liveResults?.words.if_you_need_a_moment && <p className={`text-sm ${c.textSecondary}`}><span className={`text-[10px] font-bold uppercase ${c.textMuted}`}>{t('nck_if_panic')}: </span>"{liveResults?.words.if_you_need_a_moment}"</p>}
                  </div>
                )}
                {liveResults?.remember && <p className={`text-sm ${c.textSecondary} italic`}>{liveResults?.remember}</p>}
                {liveResults?.if_you_need_to_step_away && (
                  <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
                    <p className={`text-sm ${c.textSecondary}`}>{liveResults?.if_you_need_to_step_away}</p>
                  </div>
                )}
                {liveResults?.go && <p className={`text-sm font-bold ${c.text} text-center`}>{liveResults?.go}</p>}
                <button onClick={() => { setFocusStep(0); setView('focus'); }} className={`w-full ${c.btnPrimary} rounded-lg py-2.5 text-sm font-bold`}>👁️ {t('nck_focus')}</button>
              </div>
            )}
          </div>
        )}

        {/* ── FOCUS MODE ── */}
        {view === 'focus' && focusCards.length > 0 && (
          <div className="flex flex-col items-center justify-center text-center py-8 space-y-6 min-h-[300px]">
            <p className={`text-[10px] font-bold uppercase tracking-wide ${c.accentTxt}`}>{focusCards[focusStep].label}</p>
            <p className={`text-2xl sm:text-3xl font-black ${c.text} max-w-md`}>{focusCards[focusStep].text}</p>
            <div className="flex items-center gap-3">
              <button onClick={() => setFocusStep(s => Math.max(0, s - 1))} disabled={focusStep === 0} className={`${c.btnSecondary} px-4 py-2 rounded-lg text-sm font-bold disabled:opacity-30`}>←</button>
              <span className={`text-xs ${c.textMuted}`}>{focusStep + 1}/{focusCards.length}</span>
              {focusStep < focusCards.length - 1 ? (
                <button onClick={() => setFocusStep(s => Math.min(focusCards.length - 1, s + 1))} className={`${c.btnPrimary} px-4 py-2 rounded-lg text-sm font-bold`}>→</button>
              ) : (
                <button onClick={() => setView('debrief')} className={`${c.btnPrimary} px-4 py-2 rounded-lg text-sm font-bold`}>📊 {t('nck_debrief_btn')}</button>
              )}
            </div>
          </div>
        )}

        {/* ── DEBRIEF INPUT ── */}
        {view === 'debrief' && (
          <div className="space-y-4">
            <h2 className={`text-lg font-black ${c.text}`}>📊 {t('nck_debrief_title')}</h2>
            <button onClick={loadDebriefExample} disabled={loading} className={`${c.btnSecondary} px-3 py-1.5 rounded-full text-xs font-semibold`}>✨ {t('try_example')}</button>
            <div>
              <label className={`text-sm font-medium ${c.labelText} block mb-1.5`}>{t('nck_how_go_label')} <span className={c.required}>*</span></label>
              <textarea value={howItWent} onChange={e => setHowItWent(e.target.value)} placeholder={t('nck_how_go_ph')} rows={3}
                className={`w-full px-3 py-2.5 border rounded-lg text-sm ${c.input} outline-none focus:ring-2 resize-none`} />
            </div>
            <div>
              <label className={`text-sm font-medium ${c.labelText} block mb-1.5`}>{t('nck_conf_now_label')} <span className={`ms-2 font-bold ${c.accentTxt}`}>{readinessAfter}/10</span></label>
              <input type="range" min="1" max="10" value={readinessAfter} onChange={e => setReadinessAfter(Number(e.target.value))} className="w-full accent-cyan-600" />
            </div>
            <div>
              <label className={`text-sm font-medium ${c.labelText} block mb-1.5`}>{t('nck_surprised_label')}</label>
              <input type="text" value={whatSurprised} onChange={e => setWhatSurprised(e.target.value)} placeholder={t('nck_surprised_ph')}
                className={`w-full px-3 py-2 border rounded-lg text-sm ${c.input} outline-none focus:ring-2`} />
            </div>
            {debriefError && <div className={`${c.danger} border rounded-lg p-3 text-sm`}>{debriefError}</div>}
            <button title={t('cmd_enter')} onClick={runDebrief} disabled={!howItWent.trim() || loading}
              className={`w-full ${!howItWent.trim() ? c.btnIdle : c.btnPrimary} font-bold py-3 rounded-lg min-h-[48px] disabled:opacity-40`}>
              {loading ? t('nck_processing') : t('nck_debrief_me')}
            </button>
          </div>
        )}

        {/* ── DEBRIEF RESULTS ── */}
        {view === 'debrief-results' && debriefResults && (
          <div ref={resultsRef} className="scroll-mt-24 space-y-4">
            <h2 className={`text-lg font-black ${c.text}`}>{debriefResults?.headline}</h2>
            {(debriefResults?.before_and_after?.readiness_before != null || debriefResults?.before_and_after?.readiness_after != null) && (
              <div className="flex items-center justify-center gap-3 text-sm">
                <span className={`px-3 py-1 rounded-lg font-bold border ${matchStyle(debriefResults?.before_and_after.readiness_before || 0)}`}>{debriefResults?.before_and_after.readiness_before ?? '?'}/10</span>
                <span className={c.textMuted}>→</span>
                <span className={`px-3 py-1 rounded-lg font-bold border ${matchStyle(debriefResults?.before_and_after.readiness_after || 0)}`}>{debriefResults?.before_and_after.readiness_after ?? '?'}/10</span>
              </div>
            )}

            <div className={`${c.card} border ${c.border} rounded-xl p-4 space-y-3`}>
              <h3 className={`text-sm font-bold ${c.text}`}>🧾 {t('nck_what_happened_header')}</h3>
              {debriefResults?.what_you_expected?.length > 0 && (
                <div>
                  <p className={`text-[10px] font-bold uppercase ${c.textMuted} mb-1`}>{t('nck_expected')}</p>
                  <ul className="space-y-1">{debriefResults?.what_you_expected.map((x, i) => <li key={i} className={`text-sm ${c.textSecondary}`}>• {x}</li>)}</ul>
                </div>
              )}
              {debriefResults?.what_happened?.length > 0 && (
                <div>
                  <p className={`text-[10px] font-bold uppercase ${c.textMuted} mb-1`}>{t('nck_actually_happened')}</p>
                  <ul className="space-y-1">{debriefResults?.what_happened.map((x, i) => <li key={i} className={`text-sm ${c.textSecondary}`}>• {x}</li>)}</ul>
                </div>
              )}
              {debriefResults?.what_was_different?.length > 0 && (
                <div>
                  <p className={`text-[10px] font-bold uppercase ${c.textMuted} mb-1`}>{t('nck_the_difference')}</p>
                  <ul className="space-y-1">{debriefResults?.what_was_different.map((x, i) => <li key={i} className={`text-sm ${c.textSecondary}`}>• {x}</li>)}</ul>
                </div>
              )}
            </div>

            {debriefResults?.useful_evidence_for_next_time?.length > 0 && (
              <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
                <h3 className={`text-sm font-bold ${c.text} mb-2`}>✅ {t('nck_evidence_next_time')}</h3>
                <ul className="space-y-1">{debriefResults?.useful_evidence_for_next_time.map((x, i) => <li key={i} className={`text-sm ${c.textSecondary}`}>• {x}</li>)}</ul>
              </div>
            )}

            {debriefResults?.what_you_might_change?.length > 0 && (
              <div className={`${c.warning} border rounded-xl p-4`}>
                <h3 className={`text-sm font-bold mb-2`}>🔧 {t('nck_might_change')}</h3>
                <ul className="space-y-1">{debriefResults?.what_you_might_change.map((x, i) => <li key={i} className="text-sm">• {x}</li>)}</ul>
              </div>
            )}

            {debriefResults?.save_this && (
              <div className={`${c.success} border rounded-xl p-4`}>
                <h3 className={`text-[10px] font-bold uppercase mb-1`}>📌 {t('nck_save_next')}</h3>
                <p className="text-sm font-medium italic">"{debriefResults?.save_this}"</p>
              </div>
            )}
          </div>
        )}

        {/* ── HELP SOMEONE ELSE ── */}
        {view === 'coach' && (
          <div className="space-y-4">
            <h2 className={`text-lg font-black ${c.text}`}>🤝 {t('nck_coach_mode')}</h2>
            {!coachResults ? (
              <>
                <button onClick={loadCoachExample} disabled={loading} className={`${c.btnSecondary} px-3 py-1.5 rounded-full text-xs font-semibold`}>✨ {t('try_example')}</button>
                <div>
                  <label className={`text-sm font-medium ${c.labelText} block mb-1.5`}>{t('nck_coach_who_label')}</label>
                  <input type="text" value={coachWho} onChange={e => setCoachWho(e.target.value)} placeholder={t('nck_coach_who_ph')}
                    className={`w-full px-3 py-2 border rounded-lg text-sm ${c.input} outline-none focus:ring-2`} />
                </div>
                <div>
                  <label className={`text-sm font-medium ${c.labelText} block mb-1.5`}>{t('nck_coach_what_label')} <span className={c.required}>*</span></label>
                  <textarea value={coachSituation} onChange={e => setCoachSituation(e.target.value)} placeholder={t('nck_coach_what_ph')} rows={2}
                    className={`w-full px-3 py-2.5 border rounded-lg text-sm ${c.input} outline-none focus:ring-2 resize-none`} />
                </div>
                <div>
                  <p className={`text-xs font-bold ${c.labelText} uppercase mb-1.5`}>{t('nck_relationship')}</p>
                  <div className="flex flex-wrap gap-1.5">
                    {COACH_RELATIONS.map(r => (
                      <button key={r.value} onClick={() => setCoachRelation(r.value)} className={`px-3 py-1.5 rounded-lg text-xs font-medium ${coachRelation === r.value ? c.btnPrimary : c.btnSecondary}`}>{r.icon} {t(r.tkey)}</button>
                    ))}
                  </div>
                </div>
                <div>
                  <p className={`text-xs font-bold ${c.labelText} uppercase mb-1.5`}>{t('nck_age')}</p>
                  <div className="flex gap-1.5">
                    {['child', 'teen', 'adult'].map(a => (
                      <button key={a} onClick={() => setCoachAge(a)} className={`px-3 py-1.5 rounded-lg text-xs font-medium ${coachAge === a ? c.btnPrimary : c.btnSecondary}`}>{t(`nck_age_${a}`)}</button>
                    ))}
                  </div>
                </div>
                {coachError && <div className={`${c.danger} border rounded-lg p-3 text-sm`}>{coachError}</div>}
                <button title={t('cmd_enter')} onClick={runCoach} disabled={!coachSituation.trim() || loading}
                  className={`w-full ${!coachSituation.trim() ? c.btnIdle : c.btnPrimary} font-bold py-3 rounded-lg min-h-[48px] disabled:opacity-40`}>
                  {loading ? t('nck_thinking') : t('nck_how_help')}
                </button>
              </>
            ) : (
              <div ref={resultsRef} className="scroll-mt-24 space-y-3">
                {coachResults?.what_to_say && (
                  <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
                    <h3 className={`text-sm font-bold ${c.text} mb-1`}>💬 {t('nck_say_this_title')}</h3>
                    <p className={`text-sm ${c.textSecondary}`}>{coachResults?.what_to_say}</p>
                  </div>
                )}
                {coachResults?.what_not_to_push && (
                  <div className={`${c.warning} border rounded-xl p-4`}>
                    <h3 className={`text-sm font-bold mb-1`}>🚫 {t('nck_not_to_push')}</h3>
                    <p className="text-sm">{coachResults?.what_not_to_push}</p>
                  </div>
                )}
                {coachResults?.practical_help_you_could_offer?.length > 0 && (
                  <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
                    <h3 className={`text-sm font-bold ${c.text} mb-2`}>🤲 {t('nck_do_this')}</h3>
                    <ul className="space-y-1">{coachResults?.practical_help_you_could_offer.map((x, i) => <li key={i} className={`text-sm ${c.textSecondary}`}>• {x}</li>)}</ul>
                  </div>
                )}
                {coachResults?.if_they_dont_want_help && (
                  <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
                    <h3 className={`text-[10px] font-bold uppercase ${c.textMuted} mb-1`}>{t('nck_if_no_help')}</h3>
                    <p className={`text-sm ${c.textSecondary}`}>{coachResults?.if_they_dont_want_help}</p>
                  </div>
                )}
                <button onClick={() => { setCoachResults(null); setCoachWho(''); setCoachSituation(''); setCoachRelation(''); }} className={`${c.btnSecondary} w-full rounded-lg py-2 text-xs font-bold`}>{t('nck_coach_again')}</button>
              </div>
            )}
          </div>
        )}

        {/* ── HISTORY ── */}
        {view === 'history' && (
          <div className="space-y-3">
            <h2 className={`text-lg font-black ${c.text}`}>📋 {t('nck_past_checks')}</h2>
            {sessionHistory.length === 0 ? (
              <p className={`text-sm ${c.textMuted}`}>{t('nck_no_entries')}</p>
            ) : (
              <div className="space-y-1.5">
                {sessionHistory.map(entry => (
                  <div key={entry.id} className="flex items-center gap-1.5">
                    <button onClick={() => openHistoryEntry(entry)} className={`flex-1 min-w-0 flex items-center justify-between gap-2 px-3 py-2.5 rounded-lg ${c.cardAlt} hover:brightness-95 dark:hover:brightness-125 transition text-start`}>
                      <span className="min-w-0 flex-1">
                        <span className={`text-sm font-semibold ${c.text} truncate block`}>{entry.preview || entry.situation}</span>
                        <span className={`text-[11px] ${c.textMuted} truncate block`}>
                          {t('nck_before')} {entry.readinessBefore}
                          {entry.readinessAfter != null && ` · ${t('nck_after')} ${entry.readinessAfter}`}
                          {entry.quote && ` — "${entry.quote}"`}
                        </span>
                      </span>
                      <span className={`text-[10px] ${c.textMuted} flex-shrink-0`}>{new Date(entry.date).toLocaleDateString()}</span>
                    </button>
                    <button onClick={() => removeHistoryEntry(entry.id)} aria-label={t('nck_remove')} title={t('nck_remove')}
                      className={`flex-shrink-0 w-8 h-8 flex items-center justify-center rounded-lg text-sm ${c.textMuted} opacity-60 hover:opacity-100 transition`}>✕</button>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        </div>
      </div>

      {/* ── Related tools (results screens only) ── */}
      {(view === 'results' || view === 'debrief-results') && (
        <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
          <p className={`text-[10px] font-bold ${c.textMuted} uppercase mb-2`}>🔗 {t('nck_related')}</p>
          <div className="flex flex-wrap gap-3">
            <a href="/DifficultTalkCoach" className={`text-xs ${linkStyle}`}>{t('nck_xref_dtc_short')}</a>
            <a href="/SpiralStopper" className={`text-xs ${linkStyle}`}>{t('nck_xref_spiral')}</a>
            {situationType === 'medical' && <a href="/DoctorVisitTranslator" className={`text-xs ${linkStyle}`}>{t('nck_xref_dvt')}</a>}
          </div>
        </div>
      )}

      <p className={`text-xs text-center ${c.textMuted}`}>{t('nck_disclaimer')}</p>
    </div>
  );
};

NerveCheck.displayName = 'NerveCheck';
export default NerveCheck;
