import React, { useState, useMemo, useEffect, useRef, useCallback } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { CopyBtn } from '../components/ActionButtons';
import { useRegisterActions } from '../components/ActionBarContext';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

const SIT_TYPES = [
  { value: 'interview', label: 'Job Interview', icon: '💼' },
  { value: 'presentation', label: 'Presentation', icon: '🎤' },
  { value: 'confrontation', label: 'Hard Conversation', icon: '😤' },
  { value: 'date', label: 'Date / Social', icon: '💕' },
  { value: 'medical', label: 'Medical Appt', icon: '🏥' },
  { value: 'performance', label: 'Performance', icon: '🎭' },
  { value: 'phone_call', label: 'Phone Call', icon: '📞' },
  { value: 'other', label: 'Other', icon: '🌀' },
];
const TIME_OPTIONS = [
  { value: 'right_now', label: 'Right now', icon: '🔴' },
  { value: 'today', label: 'Today', icon: '🟡' },
  { value: 'tomorrow', label: 'Tomorrow', icon: '🟢' },
  { value: 'this_week', label: 'This week', icon: '📅' },
  { value: 'later', label: 'Later', icon: '🔵' },
];
const COACH_RELATIONS = [
  { value: 'child', label: 'My child', icon: '👶' },
  { value: 'partner', label: 'Partner', icon: '💑' },
  { value: 'friend', label: 'Friend', icon: '🤝' },
  { value: 'coworker', label: 'Coworker', icon: '💼' },
  { value: 'student', label: 'Student', icon: '📚' },
  { value: 'other', label: 'Other', icon: '🌀' },
];

const NerveCheck = ({ tool }) => {
  const { callToolEndpoint } = useClaudeAPI();
  const { isDark } = useTheme();

  // ── Ref declarations ──
  const resultsRef = useRef(null);
  const analyzeRef = useRef(null);
  const canSubmitRef = useRef(false);
  const viewRef = useRef('form');
  const runDebriefRef = useRef(null);
  const canDebriefRef = useRef(false);
  const runCoachRef = useRef(null);
  const canCoachRef = useRef(false);
  const runLadderRef = useRef(null);
  const canLadderRef = useRef(false);

  // ── c block ──
  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20'
                          : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-500' : 'text-gray-400',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white'
                          : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200'
                          : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200'
                          : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200'
                          : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200'
                          : 'bg-red-50 border-red-200 text-red-800',
    infoBox:       isDark ? 'bg-sky-900/20 border-sky-700 text-sky-200'
                          : 'bg-sky-50 border-sky-200 text-sky-800',
    successBox:    isDark ? 'bg-emerald-900/20 border-emerald-700' : 'bg-emerald-50 border-emerald-300',
    successTxt:    isDark ? 'text-emerald-300' : 'text-emerald-800',
    warningBox:    isDark ? 'bg-amber-900/20 border-amber-700' : 'bg-amber-50 border-amber-300',
    warningTxt:    isDark ? 'text-amber-300' : 'text-amber-800',
    pillActive:    isDark ? 'border-cyan-500 bg-cyan-900/30 text-cyan-200'
                          : 'border-cyan-600 bg-cyan-100 text-cyan-900',
    pillInactive:  isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500'
                          : 'border-gray-300 text-gray-500 hover:border-gray-400',
    required:      isDark ? 'text-amber-400' : 'text-amber-500',
    // Tool-specific
    btnDanger:     isDark ? 'bg-red-700 hover:bg-red-600 text-white' : 'bg-red-600 hover:bg-red-700 text-white',
    btnSoft:       isDark ? 'bg-zinc-700/50 hover:bg-zinc-700 text-zinc-300' : 'bg-gray-50 hover:bg-gray-100 text-gray-500',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-600 hover:text-cyan-700 underline underline-offset-2';

  // ── Views ──
  const [view, setView] = useState('form');

  // ── Form ──
  const [situation, setSituation] = useState('');
  const [situationType, setSituationType] = useState('');
  const [confidenceLevel, setConfidenceLevel] = useState(4);
  const [specificFears, setSpecificFears] = useState('');
  const [timeUntil, setTimeUntil] = useState('today');
  const [error, setError] = useState('');

  // ── Results ──
  const [loading, setLoading] = useState(false);
  const [expandedSections, setExpandedSections] = useState({});

  // ── Walkthrough ──
  const [walkStep, setWalkStep] = useState(0);

  // ── Live / SOS ──
  const [panicLevel, setPanicLevel] = useState(7);
  const [minutesUntil, setMinutesUntil] = useState(5);
  const [liveResults, setLiveResults] = useState(null);
  const [liveLoading, setLiveLoading] = useState(false);
  const [breathingActive, setBreathingActive] = useState(false);
  const [breathPhase, setBreathPhase] = useState('');
  const [breathCount, setBreathCount] = useState(0);
  const [sosResults, setSosResults] = useState(null);
  const [sosLoading, setSosLoading] = useState(false);
  const [sosWhat, setSosWhat] = useState('');

  // ── Debrief ──
  const [howItWent, setHowItWent] = useState('');
  const [confAfter, setConfAfter] = useState(6);
  const [whatSurprised, setWhatSurprised] = useState('');
  const [debriefResults, setDebriefResults] = useState(null);
  const [debriefLoading, setDebriefLoading] = useState(false);

  // ── Specific Prep ──
  const [specResults, setSpecResults] = useState(null);
  const [specLoading, setSpecLoading] = useState(false);

  // ── Coach ──
  const [coachWho, setCoachWho] = useState('');
  const [coachSituation, setCoachSituation] = useState('');
  const [coachRelation, setCoachRelation] = useState('');
  const [coachAge, setCoachAge] = useState('adult');
  const [coachResults, setCoachResults] = useState(null);
  const [coachLoading, setCoachLoading] = useState(false);

  // ── Templates ──
  const [showSaveTemplate, setShowSaveTemplate] = useState(false);
  const [templateName, setTemplateName] = useState('');

  // ── Fear Ladder ──
  const [ladderResults, setLadderResults] = useState(null);
  const [ladderLoading, setLadderLoading] = useState(false);
  const [ladderFear, setLadderFear] = useState('');
  const [activeLadder, setActiveLadder] = useState(null);

  // ── Voice Mode ──
  const [voiceStep, setVoiceStep] = useState(0);

  // ── Persistent (after all useState) ──
  const [journal, setJournal] = usePersistentState('nc-journal', []);
  const [templates, setTemplates] = usePersistentState('nc-templates', []);
  const [ladders, setLadders] = usePersistentState('nc-ladders', []);
  const [pendingCheckins, setPendingCheckins] = usePersistentState('nc-pending', []);
  const [results, setResults] = usePersistentState('nervecheck-result', null);
  const [history, setHistory] = usePersistentState('nervecheck-history', []);

  const toggle = (key) => setExpandedSections(prev => ({ ...prev, [key]: !prev[key] }));
  const confColor = (n) => { if (n >= 8) return isDark ? 'text-emerald-400' : 'text-emerald-700'; if (n >= 5) return isDark ? 'text-amber-400' : 'text-amber-700'; return isDark ? 'text-red-400' : 'text-red-700'; };

  // ── Template helpers ──
  const saveTemplate = () => { if (!templateName.trim()) return; setTemplates(prev => [{ id: Date.now(), name: templateName.trim(), situation, situationType, specificFears, timeUntil, confidenceLevel }, ...prev].slice(0, 6)); setTemplateName(''); setShowSaveTemplate(false); };
  const loadTemplate = (t) => { setSituation(t.situation); setSituationType(t.situationType); setSpecificFears(t.specificFears || ''); setTimeUntil(t.timeUntil || 'today'); setConfidenceLevel(t.confidenceLevel || 4); };

  // ── Pattern analytics (computed from journal) ──
  const patterns = useMemo(() => {
    if (journal.length < 3) return null;
    const byType = {}; const fears = []; const gaps = []; const confOverTime = [];
    journal.forEach(j => {
      if (j.type) byType[j.type] = (byType[j.type] || 0) + 1;
      if (j.confBefore && j.confAfter) { gaps.push(j.confAfter - j.confBefore); confOverTime.push({ date: j.date, before: j.confBefore, after: j.confAfter }); }
    });
    const topTypes = Object.entries(byType).sort((a, b) => b[1] - a[1]).slice(0, 3);
    const avgGap = gaps.length ? (gaps.reduce((a, b) => a + b, 0) / gaps.length).toFixed(1) : 0;
    const avgBefore = journal.filter(j => j.confBefore).length ? (journal.reduce((a, j) => a + (j.confBefore || 0), 0) / journal.filter(j => j.confBefore).length).toFixed(1) : 0;
    const braveRate = journal.length ? Math.round(journal.filter(j => j.verdict === 'brave').length / journal.length * 100) : 0;
    const growing = gaps.length >= 3 && gaps.slice(0, 3).reduce((a, b) => a + b, 0) / 3 > gaps.slice(-3).reduce((a, b) => a + b, 0) / 3;
    return { topTypes, avgGap: Number(avgGap), avgBefore: Number(avgBefore), braveRate, growing, confOverTime: confOverTime.slice(0, 10).reverse(), total: journal.length };
  }, [journal]);

  // ── Reframe library (mine journal for matching courage receipts) ──
  const getReframes = (type) => {
    return journal.filter(j => j.type === type && j.confAfter > j.confBefore && j.saveThis).slice(0, 3);
  };
  const matchingReframes = useMemo(() => situationType ? getReframes(situationType) : [], [situationType, journal]);

  // ── Accountability: check for overdue check-ins ──
  const overdueCheckins = useMemo(() => {
    const now = Date.now();
    return pendingCheckins.filter(p => p.dueAt <= now && !p.completed);
  }, [pendingCheckins]);

  const scheduleCheckin = () => {
    const dueTimes = { right_now: 60 * 60 * 1000, today: 8 * 60 * 60 * 1000, tomorrow: 24 * 60 * 60 * 1000, this_week: 3 * 24 * 60 * 60 * 1000, later: 7 * 24 * 60 * 60 * 1000 };
    const dueAt = Date.now() + (dueTimes[timeUntil] || dueTimes.today);
    setPendingCheckins(prev => [{ id: Date.now(), situation: situation.trim(), type: situationType, dueAt, completed: false, createdAt: Date.now() }, ...prev].slice(0, 6));
  };

  const completeCheckin = (id) => {
    setPendingCheckins(prev => prev.map(p => p.id === id ? { ...p, completed: true } : p));
  };

  // ════════════════════════════════════
  // API CALLS
  // ════════════════════════════════════
  const analyze = useCallback(async () => {
    if (!situation.trim()) { setError('Describe what you\'re nervous about'); return; }
    setError(''); setResults(null); setLoading(true);
    try {
      const pastWins = journal.filter(j => j.confAfter > j.confBefore).slice(0, 3).map(j => ({ situation: j.situation, outcome: j.outcome || 'survived it' }));
      const data = await callToolEndpoint('nerve-check', { situation: situation.trim(), situationType, confidenceLevel, specificFears: specificFears.trim() || null, timeUntil, pastWins });
      setResults(data);
      setHistory(prev => [{ id: Date.now(), date: new Date().toISOString(), preview: situation.trim().slice(0, 40) }, ...prev].slice(0, 6));
      setView('results'); scheduleCheckin();
    } catch (err) { setError(err.message || 'Failed to analyze'); }
    finally { setLoading(false); }
  }, [situation, situationType, confidenceLevel, specificFears, timeUntil, journal, callToolEndpoint, setResults, setHistory]);
  const goLive = async () => {
    setLiveLoading(true); setLiveResults(null);
    try { const data = await callToolEndpoint('nerve-check/live', { situation: situation.trim() || 'something scary', panicLevel, minutesUntil }); setLiveResults(data); }
    catch (err) { setError(err.message || 'Failed to load live mode'); }
    finally { setLiveLoading(false); }
  };
  const goSOS = async () => {
    setSosLoading(true); setSosResults(null);
    try { const data = await callToolEndpoint('nerve-check/sos', { situation: situation.trim() || 'something scary', whatsHappening: sosWhat.trim() || 'panicking' }); setSosResults(data); }
    catch (err) { setError(err.message || 'Failed'); }
    finally { setSosLoading(false); }
  };
  const runDebrief = async () => {
    if (!howItWent.trim()) { setError('Tell me how it went'); return; }
    setDebriefLoading(true); setDebriefResults(null); setError('');
    try {
      const data = await callToolEndpoint('nerve-check/debrief', { situation: situation.trim() || 'something scary', howItWent: howItWent.trim(), confidenceBefore: confidenceLevel, confidenceAfter: confAfter, whatSurprised: whatSurprised.trim() || null });
      setDebriefResults(data);
      setJournal(prev => [{ id: Date.now(), date: new Date().toLocaleDateString(), situation: situation.trim(), type: situationType, confBefore: confidenceLevel, confAfter, outcome: howItWent.trim(), verdict: data?.verdict || 'brave', saveThis: data?.save_this || '', headline: data?.headline || '' }, ...prev].slice(0, 6));
      // Complete any pending check-in for this situation
      const match = pendingCheckins.find(p => !p.completed && p.situation === situation.trim());
      if (match) completeCheckin(match.id);
    } catch (err) { setError(err.message || 'Failed to debrief'); }
    finally { setDebriefLoading(false); }
  };
  const runSpecificPrep = async () => {
    setSpecLoading(true); setSpecResults(null);
    try { const data = await callToolEndpoint('nerve-check/specific-prep', { situation: situation.trim(), situationType, specificFears: specificFears.trim() || null }); setSpecResults(data); }
    catch (err) { setError(err.message || 'Failed to generate specific prep'); }
    finally { setSpecLoading(false); }
  };
  const runCoach = async () => {
    if (!coachSituation.trim()) { setError('What are they nervous about?'); return; }
    setCoachLoading(true); setCoachResults(null); setError('');
    try { const data = await callToolEndpoint('nerve-check/coach', { whoIsNervous: coachWho.trim() || 'someone', theirSituation: coachSituation.trim(), relationship: coachRelation, theirAge: coachAge }); setCoachResults(data); }
    catch (err) { setError(err.message || 'Failed to generate coaching advice'); }
    finally { setCoachLoading(false); }
  };
  const runLadder = async () => {
    if (!ladderFear.trim()) { setError('What fear do you want to conquer?'); return; }
    setLadderLoading(true); setLadderResults(null); setError('');
    try {
      const data = await callToolEndpoint('nerve-check/fear-ladder', { bigFear: ladderFear.trim(), currentComfort: `confidence ${confidenceLevel}/10`, situationType });
      setLadderResults(data);
      // Save ladder to persistent storage
      setLadders(prev => [{ id: Date.now(), name: data?.ladder_name || ladderFear.trim(), fear: ladderFear.trim(), rungs: data?.rungs || [], completedRungs: [], rule: data?.rule || '', timeframe: data?.timeframe || '' }, ...prev].slice(0, 6));
    } catch (err) { setError(err.message || 'Failed to build fear ladder'); }
    finally { setLadderLoading(false); }
  };
  const toggleRung = (ladderId, level) => {
    setLadders(prev => prev.map(l => l.id === ladderId ? { ...l, completedRungs: l.completedRungs.includes(level) ? l.completedRungs.filter(r => r !== level) : [...l.completedRungs, level] } : l));
  };

  const resetAll = () => {
    setSituation(''); setSituationType(''); setConfidenceLevel(4); setSpecificFears(''); setTimeUntil('today');
    setResults(null); setLiveResults(null); setDebriefResults(null); setHowItWent(''); setConfAfter(6);
    setWhatSurprised(''); setError(''); setExpandedSections({}); setView('form'); setBreathingActive(false);
    setSosResults(null); setSpecResults(null); setCoachResults(null); setWalkStep(0); setLadderResults(null);
  };

  const buildFullText = useCallback(() => {
    if (!results) return '';
    const lines = ['🫁 NerveCheck — Confidence Builder', '', `Situation: ${situation}`];
    if (results.fear_breakdown) { const fb = results.fear_breakdown; lines.push('', `Surface fear: ${fb.surface_fear}`, `Real fear: ${fb.real_fear}`, `Reality check: ${fb.reality_check}`); }
    if (results.scripts) { const s = results.scripts; lines.push('', 'Scripts:', `  Opening: "${s.opening_line}"`, `  If you blank: "${s.if_you_blank}"`, `  If it goes wrong: "${s.if_it_goes_wrong}"`); }
    if (results.mantra) lines.push('', `Mantra: ${results.mantra}`);
    if (results.permission_slip) lines.push('', results.permission_slip);
    return lines.join('\n') + BRAND;
  }, [results, situation]);

  // Ref assignments — always fresh
  analyzeRef.current = analyze;
  canSubmitRef.current = !!situation.trim();
  viewRef.current = view;
  runDebriefRef.current = runDebrief;
  canDebriefRef.current = !!howItWent.trim();
  runCoachRef.current = runCoach;
  canCoachRef.current = !!coachSituation.trim();
  runLadderRef.current = runLadder;
  canLadderRef.current = !!ladderFear.trim();

  useRegisterActions(buildFullText(), tool?.title || 'NerveCheck');

  // ── Scroll to results ──
  useEffect(() => {
    if (!results || !resultsRef.current) return;
    const t = setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 200);
    return () => clearTimeout(t);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [results]);

  // ── Keyboard submit ──
  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (!(e.key === 'Enter' && (e.metaKey || e.ctrlKey))) return;
      const v = viewRef.current;
      if (v === 'form'    && !loading       && canSubmitRef.current)  { analyzeRef.current?.();    return; }
      if (v === 'debrief' && !debriefLoading && canDebriefRef.current) { runDebriefRef.current?.(); return; }
      if (v === 'coach'   && !coachLoading   && canCoachRef.current)   { runCoachRef.current?.();   return; }
      if (v === 'ladder'  && !ladderLoading  && canLadderRef.current)  { runLadderRef.current?.();  return; }
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading, debriefLoading, coachLoading, ladderLoading]);

  // ── Breathing animation ──
  useEffect(() => {
    if (!breathingActive) return;
    const phases = [{ label: 'Breathe in...', duration: 4000 }, { label: 'Hold...', duration: 7000 }, { label: 'Breathe out slowly...', duration: 8000 }];
    let phaseIdx = 0; let rounds = 0;
    setBreathPhase(phases[0].label); setBreathCount(1);
    const advance = () => { phaseIdx++; if (phaseIdx >= phases.length) { phaseIdx = 0; rounds++; setBreathCount(rounds + 1); } if (rounds >= 3) { setBreathingActive(false); setBreathPhase('Done. You\'re ready.'); return; } setBreathPhase(phases[phaseIdx].label); };
    let timeout;
    const run = () => { timeout = setTimeout(() => { advance(); if (breathingActive) run(); }, phases[phaseIdx].duration); };
    run();
    return () => clearTimeout(timeout);
  }, [breathingActive]);

  const walkSteps = useMemo(() => {
    if (!results) return [];
    const steps = [];
    if (results.mantra) steps.push({ key: 'mantra', title: 'Your Mantra', icon: '🔮' });
    if (results.fear_breakdown) steps.push({ key: 'fear', title: 'What\'s Really Going On', icon: '🔍' });
    if (results.why_youre_readier_than_you_think?.length) steps.push({ key: 'ready', title: 'Why You\'re Ready', icon: '💪' });
    if (results.prep_plan?.length) steps.push({ key: 'prep', title: 'Prep Plan', icon: '📋' });
    if (results.scripts) steps.push({ key: 'scripts', title: 'What to Say', icon: '🎬' });
    if (results.body_hacks?.length) steps.push({ key: 'body', title: 'Body Hacks', icon: '🧘' });
    if (results.worst_case_autopsy) steps.push({ key: 'worst', title: 'Worst Case Autopsy', icon: '💀' });
    if (results.permission_slip) steps.push({ key: 'permission', title: 'Permission Slip', icon: '💌' });
    return steps;
  }, [results]);

  // Voice mode steps — large text, minimal, auto-advancing-friendly
  const voiceCards = useMemo(() => {
    if (!liveResults) return [];
    const cards = [];
    if (liveResults.first_thing) cards.push({ text: liveResults.first_thing, label: 'DO THIS FIRST' });
    cards.push({ text: 'Breathe in 4... Hold 7... Out 8...', label: 'BREATHE' });
    if (liveResults.body_reset) cards.push({ text: liveResults.body_reset, label: 'BODY RESET' });
    if (liveResults.last_words?.tell_yourself) cards.push({ text: liveResults.last_words.tell_yourself, label: 'TELL YOURSELF' });
    if (liveResults.last_words?.first_thing_to_say) cards.push({ text: liveResults.last_words.first_thing_to_say, label: 'SAY THIS FIRST' });
    if (liveResults.perspective) cards.push({ text: liveResults.perspective, label: 'REMEMBER' });
    cards.push({ text: 'You\'re ready. Go.', label: '🫁' });
    return cards;
  }, [liveResults]);

  // ═══════════════════════════════════
  // RENDER HELPERS
  // ═══════════════════════════════════
  const renderWalkContent = (step) => {
    if (!results) return null;
    switch(step.key) {
      case 'mantra': return (<div className={`p-6 rounded-2xl text-center ${isDark ? 'bg-cyan-900/20 border-2 border-cyan-700/50' : 'bg-cyan-50 border-2 border-cyan-300'}`}><p className={`text-xl font-black ${isDark ? 'text-cyan-300' : 'text-cyan-700'}`}>"{results.mantra}"</p><p className={`text-xs ${c.textMuteded} mt-3`}>Say it out loud. Repeat it three times.</p><div className="mt-3"><CopyBtn content={results.mantra} label="Copy" /></div></div>);
      case 'fear': return (<div className="space-y-3"><div className={`p-4 rounded-xl ${isDark ? 'bg-red-900/15' : 'bg-red-50'}`}><p className={`text-[10px] font-bold ${isDark ? 'text-red-400' : 'text-red-700'}`}>YOU THINK YOU'RE SCARED OF</p><p className={`text-sm ${c.text}`}>{results.fear_breakdown.surface_fear}</p></div><div className={`p-4 rounded-xl ${isDark ? 'bg-amber-900/15' : 'bg-amber-50'}`}><p className={`text-[10px] font-bold ${isDark ? 'text-amber-400' : 'text-amber-700'}`}>BUT REALLY IT'S</p><p className={`text-sm font-bold ${c.text}`}>{results.fear_breakdown.real_fear}</p></div><div className={`p-4 rounded-xl ${isDark ? 'bg-emerald-900/15' : 'bg-emerald-50'}`}><p className={`text-[10px] font-bold ${isDark ? 'text-emerald-400' : 'text-emerald-700'}`}>REALITY CHECK</p><p className={`text-sm ${c.text}`}>{results.fear_breakdown.reality_check}</p>{results.fear_breakdown.probability && <p className={`text-xs ${c.textMuteded} mt-1`}>Worst-case probability: {results.fear_breakdown.probability}</p>}</div></div>);
      case 'ready': return (<div className="space-y-2.5">{results.why_youre_readier_than_you_think.map((r, i) => (<div key={i} className={`p-4 rounded-xl ${c.cardAlt} border`}><p className={`text-sm font-bold ${c.text}`}>{r.reason}</p><p className={`text-xs ${c.textSecondary} mt-1`}>Evidence: {r.evidence}</p></div>))}</div>);
      case 'prep': return (<div className="space-y-2">{results.prep_plan.map((s, i) => (<div key={i} className="flex items-start gap-2"><span className={`text-[10px] font-bold px-1.5 py-0.5 rounded-full shrink-0 mt-0.5 ${s.priority === 'must_do' ? (isDark ? 'bg-red-900/30 text-red-300' : 'bg-red-100 text-red-700') : s.priority === 'should_do' ? (isDark ? 'bg-amber-900/30 text-amber-300' : 'bg-amber-100 text-amber-700') : (isDark ? 'bg-zinc-700 text-zinc-300' : 'bg-zinc-100 text-gray-600')}`}>{s.priority?.replace(/_/g, ' ')}</span><div className="flex-1"><p className={`text-xs font-bold ${c.text}`}>{s.step}</p><p className={`text-[10px] ${c.textSecondary}`}>{s.why}</p></div><span className={`text-[10px] ${c.textMuteded} shrink-0`}>{s.time}</span></div>))}</div>);
      case 'scripts': return (<div className="space-y-3">{[{ key: 'opening_line', label: 'Your opening line', icon: '🎯' }, { key: 'if_you_blank', label: 'If your mind goes blank', icon: '😶' }, { key: 'if_it_goes_wrong', label: 'If things go sideways', icon: '🔄' }, { key: 'exit_line', label: 'Graceful exit', icon: '🚪' }].map(s => results.scripts[s.key] && (<div key={s.key} className={`${c.cardAlt} border rounded-xl p-4`}><p className={`text-[10px] font-bold ${c.accentTxt} mb-1`}>{s.icon} {s.label}</p><p className={`text-sm font-bold ${c.text} mb-2`}>"{results.scripts[s.key]}"</p><CopyBtn content={results.scripts[s.key]} label="Copy" /></div>))}</div>);
      case 'body': return (<div className="space-y-2.5">{results.body_hacks.map((h, i) => (<div key={i} className={`${c.cardAlt} border rounded-xl p-3`}><div className="flex items-center justify-between mb-1"><p className={`text-xs font-bold ${c.text}`}>{h.technique}</p><span className={`text-[10px] px-1.5 py-0.5 rounded-full ${isDark ? 'bg-zinc-700 text-zinc-300' : 'bg-zinc-100 text-gray-600'}`}>{h.when} · {h.time}</span></div><p className={`text-xs ${c.textSecondary}`}>{h.how}</p></div>))}</div>);
      case 'worst': return (<div className="space-y-2.5"><div className={`p-3.5 rounded-xl ${isDark ? 'bg-red-900/15' : 'bg-red-50'}`}><p className={`text-[10px] font-bold ${isDark ? 'text-red-400' : 'text-red-700'}`}>ACTUAL WORST CASE</p><p className={`text-xs ${c.text}`}>{results.worst_case_autopsy.actual_worst}</p></div><div className={`p-3.5 rounded-xl ${isDark ? 'bg-emerald-900/15' : 'bg-emerald-50'}`}><p className={`text-[10px] font-bold ${isDark ? 'text-emerald-400' : 'text-emerald-700'}`}>YOU'D SURVIVE BECAUSE</p><p className={`text-xs ${c.text}`}>{results.worst_case_autopsy.would_you_survive}</p></div><p className={`text-xs ${c.textSecondary}`}>⏱️ {results.worst_case_autopsy.how_long_it_stings}</p><p className={`text-xs ${c.textSecondary}`}>🔄 {results.worst_case_autopsy.recovery}</p></div>);
      case 'permission': return (<div className={`p-6 rounded-2xl text-center ${isDark ? 'bg-cyan-900/15 border border-cyan-800/40' : 'bg-cyan-50 border border-cyan-200'}`}><p className={`text-base font-bold ${isDark ? 'text-cyan-300' : 'text-cyan-700'}`}>💌 {results.permission_slip}</p></div>);
      default: return null;
    }
  };

  return (
    <div className={`space-y-4 ${c.text}`}>
      {/* ── Persistent header card ── */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm`}>
        <div className="px-5 pt-5">
          <div className="pb-3 border-b border-zinc-500">
            <h2 className={`text-xl font-bold ${c.text}`}>
              <span className="mr-2">{tool?.icon ?? '🫁'}</span>{tool?.title ?? 'NerveCheck'}
            </h2>
            <p className={`text-sm ${c.textSecondary}`}>{tool?.tagline ?? 'Real confidence for scary moments'}</p>
          </div>
        </div>
        <div className="px-5 pb-4 pt-3">
          {error && <div className={`p-3 rounded-xl border mb-3 ${c.danger}`}><span className="mr-1">⚠️</span> {error}</div>}
        </div>
      </div>

        {/* ════════ FORM ════════ */}
        {view === 'form' && (
          <div className="space-y-5">
            {/* Overdue check-ins */}
            {overdueCheckins.length > 0 && (
              <div className={`p-4 rounded-2xl border-2 ${isDark ? 'bg-amber-900/15 border-amber-700/50' : 'bg-amber-50 border-amber-300'}`}>
                <p className={`text-xs font-bold ${isDark ? 'text-amber-300' : 'text-amber-700'} mb-2`}>📬 How did it go?</p>
                {overdueCheckins.slice(0, 2).map(p => (
                  <div key={p.id} className="flex items-center justify-between mb-1.5">
                    <p className={`text-xs ${c.text} truncate flex-1`}>{p.situation}</p>
                    <div className="flex gap-1.5 shrink-0 ml-2">
                      <button onClick={() => { setSituation(p.situation); setSituationType(p.type || ''); completeCheckin(p.id); setView('debrief'); }} className={`px-2.5 py-1 rounded-lg text-[10px] font-bold ${c.btnPrimary}`}>Debrief</button>
                      <button onClick={() => completeCheckin(p.id)} className={`px-2 py-1 rounded-lg text-[10px] ${c.btnSoft}`}>Dismiss</button>
                    </div>
                  </div>
                ))}
              </div>
            )}

            <div className="grid grid-cols-2 gap-2">
              <button onClick={() => { setView('live'); goLive(); }} className={`py-3 rounded-2xl font-black text-sm ${c.btnDanger}`}>🔴 Help me NOW</button>
              <button onClick={() => setView('coach')} className={`py-3 rounded-2xl font-bold text-sm ${c.btnSecondary}`}>🤝 Help someone else</button>
            </div>

            {templates.length > 0 && (
              <div className={`${c.card} border rounded-2xl p-4`}>
                <p className={`text-[10px] font-bold uppercase tracking-wider mb-2 ${c.textMuteded}`}>⚡ Quick Load</p>
                <div className="flex gap-2 flex-wrap">
                  {templates.map(t => (
                    <button key={t.id} onClick={() => loadTemplate(t)} className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold border transition-all ${isDark ? 'border-zinc-600 hover:border-cyan-500 hover:bg-cyan-900/10' : 'border-zinc-200 hover:border-cyan-400 hover:bg-cyan-50'}`}>
                      <span>{SIT_TYPES.find(s => s.value === t.situationType)?.icon || '🌀'}</span><span className={c.text}>{t.name}</span>
                      <span onClick={(e) => { e.stopPropagation(); setTemplates(prev => prev.filter(p => p.id !== t.id)); }} className={`text-[9px] ${c.textMuteded} hover:text-zinc-400 ml-1`}>✕</span>
                    </button>
                  ))}
                </div>
              </div>
            )}

            <div className={`${c.card} border rounded-2xl p-5 space-y-5`}>
              <div>
                <label className={`block text-xs font-bold uppercase tracking-wider mb-1.5 ${c.textMuted}`}>What are you nervous about? <span className={c.required}>*</span></label>
                <textarea value={situation} onChange={e => setSituation(e.target.value)} placeholder='e.g., "Job interview at Google tomorrow"' rows={3} className={`w-full p-3 border-2 rounded-xl text-sm resize-y focus:outline-none focus:ring-2 ${c.input}`} />
              </div>
              <div>
                <label className={`block text-xs font-bold uppercase tracking-wider mb-1.5 ${c.textMuteded}`}>What kind of situation?</label>
                <div className="grid grid-cols-4 gap-2">
                  {SIT_TYPES.map(st => (<button key={st.value} onClick={() => setSituationType(st.value)} className={`p-2 rounded-xl border text-center transition-all ${situationType === st.value ? (isDark ? 'border-cyan-500 bg-cyan-900/20' : 'border-cyan-500 bg-cyan-50') : (isDark ? 'border-zinc-600 hover:border-zinc-500' : 'border-zinc-200 hover:border-zinc-300')}`}><span className="text-lg block">{st.icon}</span><span className={`text-[9px] font-bold leading-tight block ${c.text}`}>{st.label}</span></button>))}
                </div>
              </div>
              {/* Reframe library teaser */}
              {matchingReframes.length > 0 && (
                <div className={`p-3 rounded-xl ${isDark ? 'bg-emerald-900/15 border border-emerald-800/30' : 'bg-emerald-50 border border-emerald-200'}`}>
                  <p className={`text-[10px] font-bold ${isDark ? 'text-emerald-400' : 'text-emerald-700'} mb-1`}>🪞 You've done {SIT_TYPES.find(s => s.value === situationType)?.label?.toLowerCase() || 'this'} before and survived:</p>
                  {matchingReframes.map((r, i) => <p key={i} className={`text-xs italic ${c.textSecondary}`}>"{r.saveThis}"</p>)}
                </div>
              )}
              <div>
                <label className={`block text-xs font-bold uppercase tracking-wider mb-1.5 ${c.textMuteded}`}>Confidence right now: <span className={`text-base font-black ${confColor(confidenceLevel)}`}>{confidenceLevel}/10</span></label>
                <input type="range" min="1" max="10" value={confidenceLevel} onChange={e => setConfidenceLevel(Number(e.target.value))} className="w-full accent-teal-500" />
                <div className="flex justify-between"><span className={`text-[10px] ${c.textMuteded}`}>Terrified</span><span className={`text-[10px] ${c.textMuteded}`}>Feeling good</span></div>
              </div>
              <div>
                <label className={`block text-xs font-bold uppercase tracking-wider mb-1.5 ${c.textMuteded}`}>Specific fears? (optional)</label>
                <textarea value={specificFears} onChange={e => setSpecificFears(e.target.value)} placeholder={`"I'll freeze up" or "They'll think I'm stupid"`} rows={2} className={`w-full p-3 border-2 rounded-xl text-sm resize-y focus:outline-none focus:ring-2 ${c.input}`} />
              </div>
              <div>
                <label className={`block text-xs font-bold uppercase tracking-wider mb-1.5 ${c.textMuteded}`}>When is it?</label>
                <div className="flex gap-2 flex-wrap">{TIME_OPTIONS.map(t => (<button key={t.value} onClick={() => setTimeUntil(t.value)} className={`px-3 py-1.5 rounded-xl text-xs font-bold border transition-all ${timeUntil === t.value ? (isDark ? 'border-cyan-500 bg-cyan-900/20' : 'border-cyan-500 bg-cyan-50') : (isDark ? 'border-zinc-600' : 'border-zinc-200')}`}>{t.icon} {t.label}</button>))}</div>
              </div>
              <button onClick={analyze} disabled={loading || !situation.trim()} className={`w-full ${c.btnPrimary} disabled:opacity-40 font-bold py-3 rounded-lg flex items-center justify-center gap-2 min-h-[48px]`}>
                {loading ? <><span className="inline-block animate-spin">{tool?.icon ?? '⚙️'}</span> Building your courage...</> : <><span className="mr-1">{tool?.icon ?? '🫁'}</span> Check My Nerves</>}
              </button>
              <p className={`text-xs ${c.textMuted}`}>Need to rehearse what you'll say? <a href="/DifficultTalkCoach" className={linkStyle}>🗣️ Difficult Talk Coach</a> can help you prepare.</p>
              {situation.trim() && situationType && (
                <div>{!showSaveTemplate ? (<button onClick={() => setShowSaveTemplate(true)} className={`w-full py-2 rounded-xl text-xs font-bold ${c.btnSoft}`}>💾 Save as template</button>) : (
                  <div className="flex gap-2"><input type="text" value={templateName} onChange={e => setTemplateName(e.target.value)} placeholder='"Weekly standup anxiety"' className={`flex-1 p-2 border-2 rounded-xl text-xs ${c.input}`} /><button onClick={saveTemplate} disabled={!templateName.trim()} className={`px-4 py-2 rounded-xl text-xs font-bold ${c.btnPrimary} disabled:opacity-40`}>Save</button><button onClick={() => setShowSaveTemplate(false)} className={`px-3 py-2 rounded-xl text-xs ${c.btnSoft}`}>✕</button></div>
                )}</div>
              )}
            </div>

            {/* Bottom nav */}
            <div className="grid grid-cols-3 gap-2">
              {patterns && <button onClick={() => setView('patterns')} className={`py-2.5 rounded-xl text-xs font-bold ${c.btnSecondary}`}>📊 Patterns</button>}
              {journal.length > 0 && <button onClick={() => setView('journal')} className={`py-2.5 rounded-xl text-xs font-bold ${c.btnSecondary}`}>🏆 Journal ({journal.length})</button>}
              <button onClick={() => setView('ladder')} className={`py-2.5 rounded-xl text-xs font-bold ${c.btnSecondary}`}>🪜 Fear Ladder{ladders.length > 0 ? ` (${ladders.length})` : ''}</button>
            </div>
          </div>
        )}

        {/* ════════ RESULTS ════════ */}
        {view === 'results' && results && (
          <div ref={resultsRef} className="space-y-5">
            <div className="flex gap-2 flex-wrap">
              <button onClick={resetAll} className={`text-sm font-semibold px-4 py-2 rounded-xl ${c.btnSecondary}`}>← New</button>
              <button onClick={() => { setWalkStep(0); setView('walkthrough'); }} className={`text-sm font-semibold px-4 py-2 rounded-xl ${c.btnPrimary}`}>🚶 Guided</button>
            </div>
            {results.mantra && (<div className={`p-5 rounded-2xl text-center ${isDark ? 'bg-cyan-900/20 border-2 border-cyan-700/50' : 'bg-cyan-50 border-2 border-cyan-300'}`}><p className={`text-lg font-black ${isDark ? 'text-cyan-300' : 'text-cyan-700'}`}>"{results.mantra}"</p><div className="mt-2"><CopyBtn content={results.mantra} label="Copy mantra" /></div></div>)}
            {/* Reframe library in results */}
            {matchingReframes.length > 0 && (
              <div className={`p-4 rounded-xl ${isDark ? 'bg-emerald-900/15 border border-emerald-800/30' : 'bg-emerald-50 border border-emerald-200'}`}>
                <p className={`text-[10px] font-bold ${isDark ? 'text-emerald-400' : 'text-emerald-700'} mb-2`}>🪞 FROM YOUR COURAGE JOURNAL — you've been here before:</p>
                {matchingReframes.map((r, i) => (<div key={i} className="mb-1.5"><p className={`text-xs italic font-bold ${c.text}`}>"{r.saveThis}"</p><p className={`text-[10px] ${c.textMuteded}`}>{r.situation} · {confColor(r.confBefore) ? '' : ''}{r.confBefore}→{r.confAfter}</p></div>))}
              </div>
            )}
            {results.fear_breakdown && (<div className={`${c.card} border rounded-2xl p-5`}><p className={`text-xs font-bold uppercase tracking-wider mb-3 ${c.accentTxt}`}>🔍 What's Really Going On</p>{renderWalkContent({ key: 'fear' })}</div>)}
            {results.why_youre_readier_than_you_think?.length > 0 && (<div className={`${c.card} border-2 rounded-2xl p-5 ${isDark ? 'border-cyan-700/50' : 'border-cyan-300'}`}><p className={`text-xs font-bold uppercase tracking-wider mb-3 ${c.accentTxt}`}>💪 Why You're Readier Than You Think</p>{renderWalkContent({ key: 'ready' })}</div>)}
            {results.prep_plan?.length > 0 && (<div className={`${c.card} border rounded-2xl p-5`}><button onClick={() => toggle('prep')} className="w-full flex items-center justify-between"><p className={`text-xs font-bold uppercase tracking-wider ${c.accentTxt}`}>📋 Prep Plan</p><span className={`text-xs ${c.textMuteded}`}>{expandedSections.prep !== false ? '▼' : '▶'}</span></button>{expandedSections.prep !== false && <div className="mt-3">{renderWalkContent({ key: 'prep' })}</div>}</div>)}
            {results.scripts && (<div className={`${c.card} border rounded-2xl p-5`}><p className={`text-xs font-bold uppercase tracking-wider mb-3 ${c.accentTxt}`}>🎬 What to Say</p>{renderWalkContent({ key: 'scripts' })}</div>)}
            {results.body_hacks?.length > 0 && (<div className={`${c.card} border rounded-2xl p-5`}><button onClick={() => toggle('body')} className="w-full flex items-center justify-between"><p className={`text-xs font-bold uppercase tracking-wider ${c.accentTxt}`}>🧘 Body Hacks</p><span className={`text-xs ${c.textMuteded}`}>{expandedSections.body ? '▼' : '▶'}</span></button>{expandedSections.body && <div className="mt-3">{renderWalkContent({ key: 'body' })}</div>}</div>)}
            {results.worst_case_autopsy && (<div className={`${c.card} border rounded-2xl p-5`}><button onClick={() => toggle('worst')} className="w-full flex items-center justify-between"><p className={`text-xs font-bold uppercase tracking-wider ${c.accentTxt}`}>💀 Worst Case Autopsy</p><span className={`text-xs ${c.textMuteded}`}>{expandedSections.worst ? '▼' : '▶'}</span></button>{expandedSections.worst && <div className="mt-3">{renderWalkContent({ key: 'worst' })}</div>}</div>)}
            {results.permission_slip && (<div className={`p-4 rounded-xl ${isDark ? 'bg-cyan-900/15 border border-cyan-800/40' : 'bg-cyan-50 border border-cyan-200'}`}><p className={`text-sm font-bold ${isDark ? 'text-cyan-300' : 'text-cyan-700'}`}>💌 {results.permission_slip}</p></div>)}
            <div className={`${c.card} border rounded-2xl p-5 space-y-2`}>
              <p className={`text-xs font-bold uppercase tracking-wider mb-2 ${c.textMuteded}`}>🔧 Next Steps</p>
              <button onClick={() => { setView('live'); goLive(); }} className={`w-full py-3 rounded-xl font-bold text-sm ${c.btnDanger}`}>🔴 Go Live</button>
              <div className="grid grid-cols-2 gap-2">
                <button onClick={() => { setView('specific'); runSpecificPrep(); }} className={`py-2.5 rounded-xl text-xs font-bold ${c.btnSecondary}`}>🎯 {situationType ? SIT_TYPES.find(s => s.value === situationType)?.label : 'Specific'} prep</button>
                <button onClick={() => setView('debrief')} className={`py-2.5 rounded-xl text-xs font-bold ${c.btnSecondary}`}>📊 Debrief</button>
              </div>
            </div>
          </div>
        )}

        {/* ════════ WALKTHROUGH ════════ */}
        {view === 'walkthrough' && results && walkSteps.length > 0 && (
          <div className="space-y-5">
            <div className="flex items-center justify-between"><button onClick={() => setView('results')} className={`text-sm font-semibold px-4 py-2 rounded-xl ${c.btnSecondary}`}>← Full view</button><p className={`text-xs font-bold ${c.textMuteded}`}>{walkStep + 1} / {walkSteps.length}</p></div>
            <div className="flex justify-center gap-1.5">{walkSteps.map((_, i) => (<button key={i} onClick={() => setWalkStep(i)} className={`w-2.5 h-2.5 rounded-full transition-all ${i === walkStep ? (isDark ? 'bg-cyan-400 scale-125' : 'bg-cyan-600 scale-125') : i < walkStep ? (isDark ? 'bg-cyan-700' : 'bg-cyan-300') : (isDark ? 'bg-zinc-700' : 'bg-zinc-300')}`} />))}</div>
            <div className={`${c.card} border-2 rounded-2xl p-6 ${isDark ? 'border-cyan-700/50' : 'border-cyan-300'}`}><p className={`text-xs font-bold uppercase tracking-wider mb-4 ${c.accentTxt}`}>{walkSteps[walkStep].icon} {walkSteps[walkStep].title}</p>{renderWalkContent(walkSteps[walkStep])}</div>
            <div className="flex gap-3">
              <button onClick={() => setWalkStep(Math.max(0, walkStep - 1))} disabled={walkStep === 0} className={`flex-1 py-3 rounded-xl font-bold text-sm ${c.btnSecondary} disabled:opacity-30`}>← Back</button>
              {walkStep < walkSteps.length - 1 ? (<button onClick={() => setWalkStep(walkStep + 1)} className={`flex-1 py-3 rounded-xl font-bold text-sm ${c.btnPrimary}`}>Next →</button>) : (<button onClick={() => { setView('live'); goLive(); }} className={`flex-1 py-3 rounded-xl font-bold text-sm ${c.btnDanger}`}>🔴 Go Live</button>)}
            </div>
          </div>
        )}

        {/* ════════ LIVE MODE ════════ */}
        {view === 'live' && (
          <div className="space-y-5">
            <div className="flex gap-2">
              <button onClick={() => results ? setView('results') : setView('form')} className={`text-sm font-semibold px-4 py-2 rounded-xl ${c.btnSecondary}`}>← Back</button>
              <div className="flex-1" />
              <button onClick={() => { setView('sos'); goSOS(); }} className={`text-sm font-black px-4 py-2 rounded-xl ${c.btnDanger}`}>🆘 SOS</button>
            </div>
            {!liveResults && !liveLoading && (
              <div className={`${c.card} border-2 rounded-2xl p-5 ${isDark ? 'border-red-700/50' : 'border-red-300'}`}>
                <p className={`text-lg font-black ${c.text} mb-1`}>🔴 Live Mode</p><p className={`text-xs ${c.textSecondary} mb-4`}>You're about to do it.</p>
                <div className="space-y-3">
                  <div><label className={`text-xs font-bold ${c.textMuteded}`}>Panic level: <span className={`font-black ${confColor(11 - panicLevel)}`}>{panicLevel}/10</span></label><input type="range" min="1" max="10" value={panicLevel} onChange={e => setPanicLevel(Number(e.target.value))} className="w-full accent-red-500" /></div>
                  <div><label className={`text-xs font-bold ${c.textMuteded}`}>Minutes:</label><div className="flex gap-2 mt-1">{[1, 2, 5, 10, 15].map(m => (<button key={m} onClick={() => setMinutesUntil(m)} className={`flex-1 py-2 rounded-xl text-xs font-bold border ${minutesUntil === m ? (isDark ? 'border-red-500 bg-red-900/20' : 'border-red-500 bg-red-50') : (isDark ? 'border-zinc-600' : 'border-zinc-200')}`}>{m}m</button>))}</div></div>
                  {!situation.trim() && <textarea value={situation} onChange={e => setSituation(e.target.value)} placeholder="What are you about to do?" rows={2} className={`w-full p-3 border-2 rounded-xl text-sm ${c.input}`} />}
                  <button onClick={goLive} disabled={liveLoading} className={`w-full ${c.btnDanger} disabled:opacity-40 font-bold py-3 rounded-lg flex items-center justify-center gap-2 min-h-[48px]`}>{liveLoading ? <><span className="inline-block animate-spin">{tool?.icon ?? '⚙️'}</span> Loading...</> : <><span className="mr-1">{tool?.icon ?? '🫁'}</span> Get Me Ready</>}</button>
                </div>
              </div>
            )}
            {liveLoading && (<div className={`${c.card} border-2 rounded-2xl p-8 text-center ${isDark ? 'border-red-700/50' : 'border-red-300'}`}><span className="inline-block animate-spin">{tool?.icon ?? '⚙️'}</span><p className={`text-sm font-bold ${c.text} mt-2`}>Getting you ready...</p></div>)}
            {liveResults && (
              <div className="space-y-4">
                <div className={`${c.card} border-2 rounded-2xl p-5 text-center ${isDark ? 'border-cyan-700/50' : 'border-cyan-300'}`}>
                  {!breathingActive && !breathPhase && (<button onClick={() => setBreathingActive(true)} className={`w-full py-4 rounded-xl font-black text-base ${c.btnPrimary}`}>🫁 Start Breathing Exercise</button>)}
                  {breathingActive && (<div><p className={`text-3xl font-black ${isDark ? 'text-cyan-300' : 'text-cyan-700'} mb-2`}>{breathPhase}</p><p className={`text-xs ${c.textMuteded}`}>Round {breathCount} of 3</p><button onClick={() => { setBreathingActive(false); setBreathPhase(''); }} className={`mt-3 text-xs ${c.textMuteded}`}>Skip</button></div>)}
                  {!breathingActive && breathPhase && (<div><p className={`text-xl font-black ${isDark ? 'text-emerald-400' : 'text-emerald-700'}`}>✅ {breathPhase}</p><button onClick={() => { setBreathPhase(''); setBreathingActive(true); setBreathCount(0); }} className={`mt-2 text-xs ${c.accentTxt}`}>Again</button></div>)}
                </div>
                {liveResults.first_thing && (<div className={`p-4 rounded-xl ${isDark ? 'bg-amber-900/15 border border-amber-800/40' : 'bg-amber-50 border border-amber-200'}`}><p className={`text-sm font-black ${isDark ? 'text-amber-300' : 'text-amber-700'}`}>👉 {liveResults.first_thing}</p></div>)}
                {liveResults.body_reset && (<div className={`${c.card} border rounded-2xl p-4`}><p className={`text-[10px] font-bold ${c.accentTxt} mb-1`}>🧍 30-SECOND BODY RESET</p><p className={`text-sm ${c.text}`}>{liveResults.body_reset}</p></div>)}
                {liveResults.last_words && (
                  <div className={`${c.card} border-2 rounded-2xl p-5 ${isDark ? 'border-cyan-700/50' : 'border-cyan-300'}`}>
                    <p className={`text-xs font-bold uppercase tracking-wider mb-3 ${c.accentTxt}`}>🎬 Your Lines</p>
                    <div className="space-y-2.5">
                      <div className={`p-3 rounded-xl ${isDark ? 'bg-zinc-700/50' : 'bg-zinc-100'}`}><p className={`text-[10px] font-bold ${c.textMuteded}`}>TELL YOURSELF</p><p className={`text-sm font-bold ${c.text}`}>"{liveResults.last_words.tell_yourself}"</p></div>
                      <div className={`p-3 rounded-xl ${isDark ? 'bg-emerald-900/15' : 'bg-emerald-50'}`}><p className={`text-[10px] font-bold ${isDark ? 'text-emerald-400' : 'text-emerald-700'}`}>FIRST THING TO SAY</p><p className={`text-sm font-bold ${c.text}`}>"{liveResults.last_words.first_thing_to_say}"</p><div className="mt-1"><CopyBtn content={liveResults.last_words.first_thing_to_say} label="Copy" /></div></div>
                      <div className={`p-3 rounded-xl ${isDark ? 'bg-red-900/15' : 'bg-red-50'}`}><p className={`text-[10px] font-bold ${isDark ? 'text-red-400' : 'text-red-700'}`}>IF PANIC HITS</p><p className={`text-xs ${c.text}`}>{liveResults.last_words.if_panic_hits}</p></div>
                    </div>
                  </div>
                )}
                {liveResults.perspective && (<div className={`p-4 rounded-xl text-center ${isDark ? 'bg-cyan-900/15 border border-cyan-800/40' : 'bg-cyan-50 border border-cyan-200'}`}><p className={`text-sm font-bold ${isDark ? 'text-cyan-300' : 'text-cyan-700'}`}>🌍 {liveResults.perspective}</p></div>)}
                {liveResults.after && (<div className={`${c.card} border rounded-2xl p-4`}><p className={`text-[10px] font-bold ${c.textMuteded}`}>AFTER (no matter what)</p><p className={`text-xs ${c.text}`}>{liveResults.after}</p></div>)}
                <div className="grid grid-cols-4 gap-2">
                  <button onClick={() => { setVoiceStep(0); setView('voice'); }} className={`py-3 rounded-xl font-bold text-xs ${c.btnPrimary}`}>👁️ Focus</button>
                  <button onClick={() => { setView('sos'); goSOS(); }} className={`py-3 rounded-xl font-bold text-xs ${c.btnDanger}`}>🆘</button>
                  <button onClick={() => setView('debrief')} className={`py-3 rounded-xl font-bold text-xs ${c.btnPrimary}`}>📊</button>
                  <button onClick={() => { setLiveResults(null); setBreathPhase(''); goLive(); }} className={`py-3 rounded-xl font-bold text-xs ${c.btnSoft}`}>🔄</button>
                </div>
              </div>
            )}
          </div>
        )}

        {/* ════════ VOICE / FOCUS MODE ════════ */}
        {view === 'voice' && voiceCards.length > 0 && (
          <div className="space-y-6">
            <div className="flex items-center justify-between">
              <button onClick={() => setView('live')} className={`text-sm font-semibold px-4 py-2 rounded-xl ${c.btnSecondary}`}>← Back</button>
              <p className={`text-xs font-bold ${c.textMuteded}`}>{voiceStep + 1} / {voiceCards.length}</p>
            </div>
            <div className={`p-8 rounded-3xl text-center min-h-[40vh] flex flex-col items-center justify-center ${isDark ? 'bg-zinc-800 border-2 border-zinc-600' : 'bg-white border-2 border-zinc-300'}`}>
              <p className={`text-[10px] font-bold uppercase tracking-widest mb-4 ${isDark ? 'text-cyan-400' : 'text-cyan-700'}`}>{voiceCards[voiceStep].label}</p>
              <p className={`text-2xl sm:text-3xl font-black leading-snug ${c.text}`}>{voiceCards[voiceStep].text}</p>
            </div>
            <div className="flex gap-3">
              <button onClick={() => setVoiceStep(Math.max(0, voiceStep - 1))} disabled={voiceStep === 0} className={`flex-1 py-4 rounded-xl font-bold text-lg ${c.btnSecondary} disabled:opacity-30`}>←</button>
              {voiceStep < voiceCards.length - 1 ? (
                <button onClick={() => setVoiceStep(voiceStep + 1)} className={`flex-1 py-4 rounded-xl font-bold text-lg ${c.btnPrimary}`}>→</button>
              ) : (
                <button onClick={() => setView('debrief')} className={`flex-1 py-4 rounded-xl font-bold text-lg ${c.btnPrimary}`}>📊 Done</button>
              )}
            </div>
          </div>
        )}

        {/* ════════ SOS ════════ */}
        {view === 'sos' && (
          <div className="space-y-5">
            <button onClick={() => liveResults ? setView('live') : results ? setView('results') : setView('form')} className={`text-sm font-semibold px-4 py-2 rounded-xl ${c.btnSecondary}`}>← Back</button>
            {sosLoading && (<div className={`${c.card} border-2 rounded-2xl p-8 text-center ${isDark ? 'border-red-700/50' : 'border-red-300'}`}><span className="inline-block animate-spin">{tool?.icon ?? '⚙️'}</span><p className={`text-sm font-bold ${c.text} mt-2`}>Hold on...</p></div>)}
            {sosResults && (
              <div className="space-y-3">
                <div className={`p-5 rounded-2xl text-center ${isDark ? 'bg-red-900/20 border-2 border-red-700/50' : 'bg-red-50 border-2 border-red-300'}`}><p className={`text-[10px] font-bold ${isDark ? 'text-red-400' : 'text-red-700'} mb-2`}>DO THIS NOW</p><p className={`text-lg font-black ${c.text}`}>{sosResults.do_now}</p></div>
                <div className={`p-5 rounded-2xl text-center ${isDark ? 'bg-cyan-900/20 border-2 border-cyan-700/50' : 'bg-cyan-50 border-2 border-cyan-300'}`}><p className={`text-[10px] font-bold ${isDark ? 'text-cyan-400' : 'text-cyan-700'} mb-2`}>THINK THIS</p><p className={`text-xl font-black ${c.text}`}>{sosResults.think_this}</p></div>
                {sosResults.say_this && (<div className={`p-4 rounded-xl ${isDark ? 'bg-emerald-900/15 border border-emerald-800/40' : 'bg-emerald-50 border border-emerald-200'}`}><p className={`text-[10px] font-bold ${isDark ? 'text-emerald-400' : 'text-emerald-700'}`}>SAY THIS</p><p className={`text-sm font-bold ${c.text}`}>"{sosResults.say_this}"</p></div>)}
                {sosResults.remember && (<div className={`p-3 rounded-xl ${isDark ? 'bg-zinc-700/50' : 'bg-zinc-100'}`}><p className={`text-xs font-bold text-center ${c.text}`}>🧠 {sosResults.remember}</p></div>)}
                <div className="grid grid-cols-2 gap-2"><button onClick={() => { setSosResults(null); goSOS(); }} className={`py-3 rounded-xl font-bold text-xs ${c.btnDanger}`}>🆘 Again</button><button onClick={() => setBreathingActive(true)} className={`py-3 rounded-xl font-bold text-xs ${c.btnPrimary}`}>🫁 Breathe</button></div>
                {breathingActive && (<div className={`${c.card} border-2 rounded-2xl p-5 text-center ${isDark ? 'border-cyan-700/50' : 'border-cyan-300'}`}><p className={`text-2xl font-black ${isDark ? 'text-cyan-300' : 'text-cyan-700'} mb-2`}>{breathPhase}</p><p className={`text-xs ${c.textMuteded}`}>Round {breathCount} of 3</p><button onClick={() => { setBreathingActive(false); setBreathPhase(''); }} className={`mt-2 text-xs ${c.textMuteded}`}>Stop</button></div>)}
              </div>
            )}
            {!sosResults && !sosLoading && (
              <div className={`${c.card} border-2 rounded-2xl p-5 ${isDark ? 'border-red-700/50' : 'border-red-300'}`}>
                <p className={`text-lg font-black ${c.text} mb-2`}>🆘 Mid-Event SOS</p><p className={`text-xs ${c.textSecondary} mb-3`}>What's happening right now?</p>
                <textarea value={sosWhat} onChange={e => setSosWhat(e.target.value)} placeholder="e.g., 'I blanked on my answer'" rows={2} className={`w-full p-3 border-2 rounded-xl text-sm mb-3 ${c.input}`} />
                <button onClick={goSOS} className={`w-full py-3 rounded-xl font-bold ${c.btnDanger}`}>🆘 Help Me Now</button>
              </div>
            )}
          </div>
        )}

        {/* ════════ SPECIFIC PREP ════════ */}
        {view === 'specific' && (
          <div className="space-y-5">
            <button onClick={() => results ? setView('results') : setView('form')} className={`text-sm font-semibold px-4 py-2 rounded-xl ${c.btnSecondary}`}>← Back</button>
            {specLoading && (<div className={`${c.card} border rounded-2xl p-8 text-center`}><span className="inline-block animate-spin">{tool?.icon ?? '⚙️'}</span><p className={`text-sm ${c.textSecondary} mt-2`}>Building {situationType ? SIT_TYPES.find(s => s.value === situationType)?.label?.toLowerCase() : 'specific'} prep...</p></div>)}
            {specResults && (
              <div className="space-y-4">
                {specResults.situation_intel && (
                  <div className={`${c.card} border-2 rounded-2xl p-5 ${isDark ? 'border-cyan-700/50' : 'border-cyan-300'}`}>
                    <p className={`text-xs font-bold uppercase tracking-wider mb-3 ${c.accentTxt}`}>🎯 Intel</p>
                    <div className="space-y-2.5">
                      <div><p className={`text-[10px] font-bold ${c.textMuteded}`}>WHAT TO EXPECT</p><p className={`text-xs ${c.text}`}>{specResults.situation_intel.what_to_expect}</p></div>
                      <div className="flex gap-3">{specResults.situation_intel.typical_duration && <p className={`text-[10px] ${c.textMuteded}`}>⏱️ {specResults.situation_intel.typical_duration}</p>}{specResults.situation_intel.hardest_part && <p className={`text-[10px] ${isDark ? 'text-amber-400' : 'text-amber-700'}`}>⚠️ {specResults.situation_intel.hardest_part}</p>}</div>
                      {specResults.situation_intel.secret && (<div className={`p-3 rounded-xl ${isDark ? 'bg-amber-900/15' : 'bg-amber-50'}`}><p className={`text-[10px] font-bold ${isDark ? 'text-amber-400' : 'text-amber-700'}`}>🤫 SECRET</p><p className={`text-xs ${c.text}`}>{specResults.situation_intel.secret}</p></div>)}
                    </div>
                  </div>
                )}
                {specResults.targeted_prep?.length > 0 && (<div className={`${c.card} border rounded-2xl p-5`}><p className={`text-xs font-bold uppercase tracking-wider mb-3 ${c.accentTxt}`}>📋 Targeted Prep</p><div className="space-y-2.5">{specResults.targeted_prep.map((p, i) => (<div key={i} className={`${c.cardAlt} border rounded-xl p-3.5`}><p className={`text-xs font-bold ${c.text} mb-1`}>{p.task}</p><p className={`text-[10px] ${c.textSecondary}`}>{p.why} · {p.time}</p>{p.script && <div className="mt-1.5 flex items-center gap-2"><p className={`text-xs font-bold ${isDark ? 'text-cyan-400' : 'text-cyan-700'}`}>"{p.script}"</p><CopyBtn content={p.script} label="Copy" /></div>}</div>))}</div></div>)}
                {specResults.likely_challenges?.length > 0 && (<div className={`${c.card} border rounded-2xl p-5`}><p className={`text-xs font-bold uppercase tracking-wider mb-3 ${c.accentTxt}`}>⚡ Challenges</p><div className="space-y-2.5">{specResults.likely_challenges.map((ch, i) => (<div key={i} className={`${c.cardAlt} border rounded-xl p-3.5`}><div className="flex items-center justify-between mb-1"><p className={`text-xs font-bold ${c.text}`}>{ch.challenge}</p><span className={`text-[10px] font-bold px-1.5 py-0.5 rounded-full ${ch.probability === 'likely' ? (isDark ? 'bg-red-900/30 text-red-300' : 'bg-red-100 text-red-700') : ch.probability === 'possible' ? (isDark ? 'bg-amber-900/30 text-amber-300' : 'bg-amber-100 text-amber-700') : (isDark ? 'bg-zinc-700 text-zinc-300' : 'bg-zinc-100 text-gray-600')}`}>{ch.probability}</span></div><p className={`text-xs ${isDark ? 'text-emerald-400' : 'text-emerald-700'}`}>→ {ch.handle_it}</p>{ch.script && <div className="mt-1 flex items-center gap-2"><p className={`text-xs font-bold ${c.text}`}>"{ch.script}"</p><CopyBtn content={ch.script} label="Copy" /></div>}</div>))}</div></div>)}
                {specResults.power_moves?.length > 0 && (<div className={`${c.card} border rounded-2xl p-5`}><p className={`text-xs font-bold uppercase tracking-wider mb-3 ${c.accentTxt}`}>💪 Power Moves</p>{specResults.power_moves.map((m, i) => (<div key={i} className="mb-2.5"><p className={`text-xs font-bold ${c.text}`}>{m.move}</p><p className={`text-[10px] ${c.textSecondary}`}>{m.when} · {m.why_it_works}</p></div>))}</div>)}
                {specResults.cheat_sheet?.length > 0 && (<div className={`p-4 rounded-xl ${isDark ? 'bg-cyan-900/15 border border-cyan-800/40' : 'bg-cyan-50 border border-cyan-200'}`}><div className="flex items-center justify-between mb-2"><p className={`text-xs font-bold ${isDark ? 'text-cyan-400' : 'text-cyan-700'}`}>📝 Cheat Sheet</p><CopyBtn content={specResults.cheat_sheet.join('\n')} label="Copy" /></div>{specResults.cheat_sheet.map((item, i) => <p key={i} className={`text-xs ${c.text} mb-0.5`}>• {item}</p>)}</div>)}
              </div>
            )}
          </div>
        )}

        {/* ════════ COACH ════════ */}
        {view === 'coach' && (
          <div className="space-y-5">
            <button onClick={() => setView('form')} className={`text-sm font-semibold px-4 py-2 rounded-xl ${c.btnSecondary}`}>← Back</button>
            {!coachResults && !coachLoading && (
              <div className={`${c.card} border-2 rounded-2xl p-5 ${isDark ? 'border-cyan-700/50' : 'border-cyan-300'}`}>
                <p className={`text-lg font-black ${c.text} mb-1`}>🤝 Coach Mode</p><p className={`text-xs ${c.textSecondary} mb-4`}>Help someone who's nervous.</p>
                <div className="space-y-3">
                  <input type="text" value={coachWho} onChange={e => setCoachWho(e.target.value)} placeholder='Who? (e.g., "my daughter")' className={`w-full p-2.5 border-2 rounded-xl text-sm ${c.input}`} />
                  <textarea value={coachSituation} onChange={e => setCoachSituation(e.target.value)} placeholder="What are they nervous about?" rows={3} className={`w-full p-3 border-2 rounded-xl text-sm resize-y ${c.input}`} />
                  <div><p className={`text-[10px] font-bold ${c.textMuteded} mb-1.5`}>RELATIONSHIP</p><div className="grid grid-cols-3 gap-2">{COACH_RELATIONS.map(r => (<button key={r.value} onClick={() => setCoachRelation(r.value)} className={`p-2 rounded-xl border text-center text-xs font-bold ${coachRelation === r.value ? (isDark ? 'border-cyan-500 bg-cyan-900/20' : 'border-cyan-500 bg-cyan-50') : (isDark ? 'border-zinc-600' : 'border-zinc-200')}`}>{r.icon} {r.label}</button>))}</div></div>
                  <div><p className={`text-[10px] font-bold ${c.textMuteded} mb-1.5`}>AGE</p><div className="flex gap-2">{['child', 'teen', 'adult'].map(a => (<button key={a} onClick={() => setCoachAge(a)} className={`flex-1 py-2 rounded-xl text-xs font-bold border ${coachAge === a ? (isDark ? 'border-cyan-500 bg-cyan-900/20' : 'border-cyan-500 bg-cyan-50') : (isDark ? 'border-zinc-600' : 'border-zinc-200')}`}>{a === 'child' ? '👶' : a === 'teen' ? '🧑' : '🧑‍💼'} {a}</button>))}</div></div>
                  <button onClick={runCoach} disabled={coachLoading || !coachSituation.trim()} className={`w-full ${c.btnPrimary} disabled:opacity-40 font-bold py-3 rounded-lg flex items-center justify-center gap-2 min-h-[48px]`}>{coachLoading ? <><span className="inline-block animate-spin">{tool?.icon ?? '⚙️'}</span> Thinking...</> : <><span className="mr-1">{tool?.icon ?? '🫁'}</span> How Do I Help?</>}</button>
                </div>
              </div>
            )}
            {coachLoading && (<div className={`${c.card} border rounded-2xl p-8 text-center`}><span className="inline-block animate-spin">{tool?.icon ?? '⚙️'}</span></div>)}
            {coachResults && (
              <div className="space-y-4">
                {coachResults.key_insight && (<div className={`p-5 rounded-2xl text-center ${isDark ? 'bg-cyan-900/20 border-2 border-cyan-700/50' : 'bg-cyan-50 border-2 border-cyan-300'}`}><p className={`text-sm font-black ${isDark ? 'text-cyan-300' : 'text-cyan-700'}`}>💡 {coachResults.key_insight}</p></div>)}
                {coachResults.dont_say?.length > 0 && (<div className={`p-4 rounded-xl ${isDark ? 'bg-red-900/15 border border-red-800/30' : 'bg-red-50 border border-red-200'}`}><p className={`text-xs font-bold ${isDark ? 'text-red-300' : 'text-red-700'} mb-2`}>🚫 Don't Say</p>{coachResults.dont_say.map((d, i) => <p key={i} className={`text-xs ${c.textSecondary} mb-1`}>• {d}</p>)}</div>)}
                {coachResults.do_say?.length > 0 && (<div className={`${c.card} border-2 rounded-2xl p-5 ${isDark ? 'border-cyan-700/50' : 'border-cyan-300'}`}><p className={`text-xs font-bold uppercase tracking-wider mb-3 ${isDark ? 'text-cyan-400' : 'text-cyan-700'}`}>💬 Say This</p><div className="space-y-3">{coachResults.do_say.map((s, i) => (<div key={i} className={`${c.cardAlt} border rounded-xl p-3.5`}><p className={`text-[10px] font-bold ${c.textMuteded} mb-1`}>{s.when}</p><p className={`text-sm font-bold ${c.text} mb-1`}>"{s.script}"</p><div className="flex items-center justify-between"><p className={`text-[10px] ${c.textSecondary}`}>{s.why_it_helps}</p><CopyBtn content={s.script} label="Copy" /></div></div>))}</div></div>)}
                {coachResults.do_this?.length > 0 && (<div className={`${c.card} border rounded-2xl p-5`}><p className={`text-xs font-bold uppercase tracking-wider mb-3 ${isDark ? 'text-cyan-400' : 'text-cyan-700'}`}>🤲 Do This</p>{coachResults.do_this.map((d, i) => (<div key={i} className="mb-2.5"><p className={`text-xs font-bold ${c.text}`}>{d.action}</p><p className={`text-[10px] ${c.textSecondary}`}>{d.when} · {d.why}</p></div>))}</div>)}
                {coachResults.after && (<div className={`${c.card} border rounded-2xl p-5`}><p className={`text-xs font-bold uppercase tracking-wider mb-3 ${isDark ? 'text-cyan-400' : 'text-cyan-700'}`}>📞 After</p><div className="space-y-2">{coachResults.after.if_it_went_well && <div className={`p-3 rounded-xl ${isDark ? 'bg-emerald-900/15' : 'bg-emerald-50'}`}><p className={`text-[10px] font-bold ${isDark ? 'text-emerald-400' : 'text-emerald-700'}`}>WENT WELL</p><p className={`text-xs ${c.text}`}>{coachResults.after.if_it_went_well}</p></div>}{coachResults.after.if_it_went_badly && <div className={`p-3 rounded-xl ${isDark ? 'bg-amber-900/15' : 'bg-amber-50'}`}><p className={`text-[10px] font-bold ${isDark ? 'text-amber-400' : 'text-amber-700'}`}>DIDN'T GO WELL</p><p className={`text-xs ${c.text}`}>{coachResults.after.if_it_went_badly}</p></div>}{coachResults.after.either_way && <div className={`p-3 rounded-xl ${isDark ? 'bg-zinc-700/50' : 'bg-zinc-100'}`}><p className={`text-[10px] font-bold ${c.textMuteded}`}>EITHER WAY</p><p className={`text-xs ${c.text}`}>{coachResults.after.either_way}</p></div>}</div></div>)}
                <button onClick={() => { setCoachResults(null); setCoachSituation(''); setCoachWho(''); }} className={`w-full py-3 rounded-xl font-bold ${c.btnSecondary}`}>← Again</button>
              </div>
            )}
          </div>
        )}

        {/* ════════ FEAR LADDER ════════ */}
        {view === 'ladder' && (
          <div className="space-y-5">
            <button onClick={() => setView('form')} className={`text-sm font-semibold px-4 py-2 rounded-xl ${c.btnSecondary}`}>← Back</button>

            {/* Active ladders */}
            {!activeLadder && ladders.length > 0 && (
              <div className="space-y-3">
                <p className={`text-xs font-bold uppercase tracking-wider ${c.textMuteded}`}>🪜 Your Ladders</p>
                {ladders.map(l => {
                  const done = l.completedRungs?.length || 0;
                  const total = l.rungs?.length || 6;
                  const pct = Math.round(done / total * 100);
                  return (
                    <div key={l.id} className={`${c.card} border rounded-2xl p-4`}>
                      <div className="flex items-center justify-between mb-2">
                        <p className={`text-sm font-bold ${c.text}`}>{l.name}</p>
                        <div className="flex gap-1.5 shrink-0">
                          <button onClick={() => setActiveLadder(l)} className={`px-3 py-1 rounded-lg text-xs font-bold ${c.btnPrimary}`}>Open</button>
                          <button onClick={() => setLadders(prev => prev.filter(p => p.id !== l.id))} className={`px-2 py-1 rounded-lg text-xs ${c.btnSoft}`}>✕</button>
                        </div>
                      </div>
                      <div className={`w-full h-2 rounded-full ${isDark ? 'bg-zinc-700' : 'bg-zinc-200'}`}>
                        <div className={`h-2 rounded-full transition-all ${pct >= 100 ? 'bg-emerald-500' : isDark ? 'bg-cyan-500' : 'bg-cyan-600'}`} style={{ width: `${pct}%` }} />
                      </div>
                      <p className={`text-[10px] ${c.textMuteded} mt-1`}>{done}/{total} rungs · {pct}%{pct >= 100 ? ' 🎉' : ''}</p>
                    </div>
                  );
                })}
              </div>
            )}

            {/* Active ladder detail */}
            {activeLadder && (
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <button onClick={() => setActiveLadder(null)} className={`text-xs font-bold ${c.accentTxt}`}>← All ladders</button>
                  <p className={`text-xs font-bold ${c.textMuteded}`}>{activeLadder.completedRungs?.length || 0}/{activeLadder.rungs?.length || 0}</p>
                </div>
                <div className={`p-4 rounded-2xl text-center ${isDark ? 'bg-cyan-900/15 border border-cyan-800/40' : 'bg-cyan-50 border border-cyan-200'}`}>
                  <p className={`text-lg font-black ${c.text}`}>🪜 {activeLadder.name}</p>
                  {activeLadder.rule && <p className={`text-xs ${c.textSecondary} mt-1`}>📌 {activeLadder.rule}</p>}
                  {activeLadder.timeframe && <p className={`text-[10px] ${c.textMuteded} mt-1`}>⏱️ {activeLadder.timeframe}</p>}
                </div>
                <div className="space-y-2">
                  {(activeLadder.rungs || []).map((rung, i) => {
                    const done = (activeLadder.completedRungs || []).includes(rung.level);
                    const diffColor = rung.difficulty === 'easy' ? (isDark ? 'text-emerald-400' : 'text-emerald-700') : rung.difficulty === 'moderate' ? (isDark ? 'text-amber-400' : 'text-amber-700') : rung.difficulty === 'hard' ? (isDark ? 'text-amber-400' : 'text-amber-700') : (isDark ? 'text-red-400' : 'text-red-700');
                    return (
                      <div key={i} className={`${c.card} border rounded-2xl p-4 ${done ? 'opacity-60' : ''}`}>
                        <div className="flex items-start gap-3">
                          <button onClick={() => toggleRung(activeLadder.id, rung.level)} className={`w-7 h-7 rounded-full border-2 flex items-center justify-center shrink-0 mt-0.5 transition-all ${done ? (isDark ? 'bg-cyan-600 border-cyan-500' : 'bg-cyan-500 border-cyan-400') : (isDark ? 'border-zinc-600' : 'border-zinc-300')}`}>
                            {done && <span className="text-white text-xs">✓</span>}
                          </button>
                          <div className="flex-1">
                            <div className="flex items-center gap-2 mb-1">
                              <span className={`text-[10px] font-bold ${diffColor}`}>{rung.difficulty?.toUpperCase()}</span>
                              <span className={`text-[10px] ${c.textMuteded}`}>Rung {rung.level}</span>
                            </div>
                            <p className={`text-sm font-bold ${c.text} ${done ? 'line-through' : ''}`}>{rung.challenge}</p>
                            <p className={`text-[10px] ${c.textSecondary} mt-0.5`}>{rung.why_this_step}</p>
                            {rung.tip && <p className={`text-[10px] ${isDark ? 'text-cyan-400' : 'text-cyan-700'} mt-0.5`}>💡 {rung.tip}</p>}
                            {rung.you_know_youre_ready_when && <p className={`text-[10px] ${c.textMuteded} mt-0.5`}>✅ Ready for next: {rung.you_know_youre_ready_when}</p>}
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}

            {/* New ladder */}
            {!activeLadder && (
              <div className={`${c.card} border-2 rounded-2xl p-5 ${isDark ? 'border-cyan-700/50' : 'border-cyan-300'}`}>
                <p className={`text-lg font-black ${c.text} mb-1`}>🪜 Build a Fear Ladder</p>
                <p className={`text-xs ${c.textSecondary} mb-4`}>Break a big fear into small, progressively braver steps.</p>
                <div className="space-y-3">
                  <textarea value={ladderFear} onChange={e => setLadderFear(e.target.value)} placeholder='e.g., "Speaking in front of large groups" or "Going on dates"' rows={2} className={`w-full p-3 border-2 rounded-xl text-sm ${c.input}`} />
                  <button onClick={runLadder} disabled={ladderLoading || !ladderFear.trim()} className={`w-full ${c.btnPrimary} disabled:opacity-40 font-bold py-3 rounded-lg flex items-center justify-center gap-2 min-h-[48px]`}>{ladderLoading ? <><span className="inline-block animate-spin">{tool?.icon ?? '⚙️'}</span> Building ladder...</> : <><span className="mr-1">{tool?.icon ?? '🫁'}</span> Build My Ladder</>}</button>
                </div>
                {ladderResults && (
                  <div className={`mt-3 p-3 rounded-xl ${isDark ? 'bg-emerald-900/15' : 'bg-emerald-50'}`}>
                    <p className={`text-xs font-bold ${isDark ? 'text-emerald-400' : 'text-emerald-700'}`}>✅ Ladder "{ladderResults.ladder_name}" created! Tap "Open" above to start.</p>
                  </div>
                )}
              </div>
            )}
          </div>
        )}

        {/* ════════ PATTERNS ════════ */}
        {view === 'patterns' && patterns && (
          <div className="space-y-5">
            <button onClick={() => setView('form')} className={`text-sm font-semibold px-4 py-2 rounded-xl ${c.btnSecondary}`}>← Back</button>
            <div className={`${c.card} border-2 rounded-2xl p-5 text-center ${isDark ? 'border-cyan-700/50' : 'border-cyan-300'}`}>
              <p className="text-3xl mb-2">📊</p>
              <p className={`text-lg font-black ${c.text}`}>Your Anxiety Patterns</p>
              <p className={`text-xs ${c.textSecondary} mt-1`}>Based on {patterns.total} entries</p>
            </div>

            {/* Stats grid */}
            <div className="grid grid-cols-2 gap-3">
              <div className={`${c.card} border rounded-2xl p-4 text-center`}>
                <p className={`text-3xl font-black ${patterns.avgGap > 0 ? (isDark ? 'text-emerald-400' : 'text-emerald-700') : (isDark ? 'text-amber-400' : 'text-amber-700')}`}>{patterns.avgGap > 0 ? '+' : ''}{patterns.avgGap}</p>
                <p className={`text-[10px] ${c.textMuteded}`}>Avg confidence shift</p>
              </div>
              <div className={`${c.card} border rounded-2xl p-4 text-center`}>
                <p className={`text-3xl font-black ${isDark ? 'text-cyan-400' : 'text-cyan-700'}`}>{patterns.braveRate}%</p>
                <p className={`text-[10px] ${c.textMuteded}`}>Brave rate 🦁</p>
              </div>
            </div>

            {/* Key insight */}
            <div className={`p-4 rounded-xl ${isDark ? 'bg-cyan-900/15 border border-cyan-800/40' : 'bg-cyan-50 border border-cyan-200'}`}>
              <p className={`text-sm font-bold ${isDark ? 'text-cyan-300' : 'text-cyan-700'}`}>
                {patterns.avgGap > 1 ? '📈 Your confidence consistently goes UP after facing fears. Your fear overestimates danger.' :
                 patterns.avgGap > 0 ? '📊 You tend to feel slightly better after than before. The pattern is working.' :
                 '🔄 Your confidence sometimes dips after hard things. That\'s okay — growth isn\'t linear.'}
              </p>
            </div>

            {/* Top situation types */}
            {patterns.topTypes.length > 0 && (
              <div className={`${c.card} border rounded-2xl p-5`}>
                <p className={`text-xs font-bold uppercase tracking-wider mb-3 ${c.accentTxt}`}>🎯 Where You Push Yourself Most</p>
                {patterns.topTypes.map(([type, count], i) => {
                  const st = SIT_TYPES.find(s => s.value === type);
                  return (
                    <div key={i} className="flex items-center gap-3 mb-2">
                      <span className="text-lg">{st?.icon || '🌀'}</span>
                      <div className="flex-1">
                        <p className={`text-xs font-bold ${c.text}`}>{st?.label || type}</p>
                        <div className={`w-full h-1.5 rounded-full mt-1 ${isDark ? 'bg-zinc-700' : 'bg-zinc-200'}`}>
                          <div className={`h-1.5 rounded-full ${isDark ? 'bg-cyan-500' : 'bg-cyan-600'}`} style={{ width: `${Math.round(count / patterns.total * 100)}%` }} />
                        </div>
                      </div>
                      <span className={`text-xs font-bold ${c.textMuteded}`}>{count}×</span>
                    </div>
                  );
                })}
              </div>
            )}

            {/* Confidence over time */}
            {patterns.confOverTime.length >= 3 && (
              <div className={`${c.card} border rounded-2xl p-5`}>
                <p className={`text-xs font-bold uppercase tracking-wider mb-3 ${c.accentTxt}`}>📈 Confidence Over Time</p>
                <div className="flex items-end gap-1 h-24">
                  {patterns.confOverTime.map((entry, i) => (
                    <div key={i} className="flex-1 flex flex-col items-center gap-0.5">
                      <div className="flex flex-col items-center gap-0.5 flex-1 justify-end w-full">
                        <div className={`w-full rounded-t ${isDark ? 'bg-emerald-600' : 'bg-emerald-400'}`} style={{ height: `${entry.after * 10}%` }} title={`After: ${entry.after}`} />
                        <div className={`w-full rounded-b ${isDark ? 'bg-zinc-600' : 'bg-zinc-300'}`} style={{ height: `${entry.before * 10}%` }} title={`Before: ${entry.before}`} />
                      </div>
                    </div>
                  ))}
                </div>
                <div className="flex items-center gap-3 mt-2 justify-center">
                  <div className="flex items-center gap-1"><div className={`w-2 h-2 rounded ${isDark ? 'bg-zinc-600' : 'bg-zinc-300'}`} /><span className={`text-[9px] ${c.textMuteded}`}>Before</span></div>
                  <div className="flex items-center gap-1"><div className={`w-2 h-2 rounded ${isDark ? 'bg-emerald-600' : 'bg-emerald-400'}`} /><span className={`text-[9px] ${c.textMuteded}`}>After</span></div>
                </div>
              </div>
            )}

            {/* Trend */}
            <div className={`p-4 rounded-xl text-center ${isDark ? 'bg-zinc-700/50' : 'bg-zinc-100'}`}>
              <p className={`text-sm font-bold ${c.text}`}>
                {patterns.growing ? '🌱 Trend: Your baseline confidence is rising over time.' : patterns.total >= 5 ? '📊 Trend: Steady — you keep showing up, which is what matters.' : '📝 Keep logging to reveal your trend.'}
              </p>
            </div>
          </div>
        )}

        {/* ════════ DEBRIEF ════════ */}
        {view === 'debrief' && (
          <div className="space-y-5">
            <button onClick={() => results ? setView('results') : setView('form')} className={`text-sm font-semibold px-4 py-2 rounded-xl ${c.btnSecondary}`}>← Back</button>
            {!debriefResults && !debriefLoading && (
              <div className={`${c.card} border-2 rounded-2xl p-5 ${isDark ? 'border-emerald-700/50' : 'border-emerald-300'}`}>
                <p className={`text-lg font-black ${c.text} mb-1`}>📊 You Did It. Let's Debrief.</p>
                <p className={`text-xs ${c.textSecondary} mb-4`}>No matter how it went, you showed up. That counts.</p>
                <div className="space-y-3">
                  <div><label className={`block text-xs font-bold uppercase tracking-wider mb-1.5 ${c.textMuted}`}>How did it go? <span className={c.required}>*</span></label><textarea value={howItWent} onChange={e => setHowItWent(e.target.value)} placeholder='"It was actually fine. Got the second interview."' rows={3} className={`w-full p-3 border-2 rounded-xl text-sm resize-y focus:outline-none focus:ring-2 ${c.input}`} /></div>
                  <div><label className={`block text-xs font-bold uppercase tracking-wider mb-1.5 ${c.textMuteded}`}>Confidence now: <span className={`font-black ${confColor(confAfter)}`}>{confAfter}/10</span></label><input type="range" min="1" max="10" value={confAfter} onChange={e => setConfAfter(Number(e.target.value))} className="w-full accent-teal-500" /></div>
                  <div><label className={`block text-xs font-bold uppercase tracking-wider mb-1.5 ${c.textMuteded}`}>What surprised you? (optional)</label><input type="text" value={whatSurprised} onChange={e => setWhatSurprised(e.target.value)} placeholder={`"I didn't freeze up like I thought"`} className={`w-full p-2.5 border-2 rounded-xl text-sm ${c.input}`} /></div>
                  <button onClick={runDebrief} disabled={debriefLoading || !howItWent.trim()} className={`w-full ${c.btnPrimary} disabled:opacity-40 font-bold py-3 rounded-lg flex items-center justify-center gap-2 min-h-[48px]`}>{debriefLoading ? <><span className="inline-block animate-spin">{tool?.icon ?? '⚙️'}</span> Processing...</> : <><span className="mr-1">{tool?.icon ?? '🫁'}</span> Debrief Me</>}</button>
                </div>
              </div>
            )}
            {debriefLoading && (<div className={`${c.card} border rounded-2xl p-8 text-center`}><span className="inline-block animate-spin">{tool?.icon ?? '⚙️'}</span><p className={`text-sm ${c.textSecondary} mt-2`}>Processing your experience...</p></div>)}
            {debriefResults && (
              <div className="space-y-4">
                <div className={`${c.card} border-2 rounded-2xl p-5 text-center ${isDark ? 'border-emerald-700/50' : 'border-emerald-300'}`}>
                  <p className="text-4xl mb-2">{debriefResults.verdict === 'brave' ? '🦁' : debriefResults.verdict === 'you_showed_up' ? '💪' : '📝'}</p>
                  <p className={`text-lg font-black ${c.text}`}>{debriefResults.headline}</p>
                </div>
                <div className={`${c.card} border rounded-2xl p-5 text-center`}>
                  <p className={`text-[10px] font-bold ${c.textMuteded} mb-2`}>CONFIDENCE SHIFT</p>
                  <div className="flex items-center justify-center gap-4">
                    <div><p className={`text-3xl font-black ${confColor(confidenceLevel)}`}>{confidenceLevel}</p><p className={`text-[10px] ${c.textMuteded}`}>Before</p></div>
                    <span className={`text-2xl ${confAfter > confidenceLevel ? (isDark ? 'text-emerald-400' : 'text-emerald-600') : confAfter < confidenceLevel ? (isDark ? 'text-red-400' : 'text-red-600') : c.textMuteded}`}>{confAfter > confidenceLevel ? '↑' : confAfter < confidenceLevel ? '↓' : '→'}</span>
                    <div><p className={`text-3xl font-black ${confColor(confAfter)}`}>{confAfter}</p><p className={`text-[10px] ${c.textMuteded}`}>After</p></div>
                  </div>
                </div>
                {debriefResults.courage_receipt && (
                  <div className={`${c.card} border rounded-2xl p-5`}>
                    <p className={`text-xs font-bold uppercase tracking-wider mb-3 ${c.accentTxt}`}>🧾 Courage Receipt</p>
                    <div className="space-y-2">
                      <div className={`p-3 rounded-xl ${isDark ? 'bg-red-900/15' : 'bg-red-50'}`}><p className={`text-[10px] font-bold ${isDark ? 'text-red-400' : 'text-red-700'}`}>FEARED</p><p className={`text-xs ${c.text}`}>{debriefResults.courage_receipt.fear_before}</p></div>
                      <div className={`p-3 rounded-xl ${isDark ? 'bg-emerald-900/15' : 'bg-emerald-50'}`}><p className={`text-[10px] font-bold ${isDark ? 'text-emerald-400' : 'text-emerald-700'}`}>REALITY</p><p className={`text-xs ${c.text}`}>{debriefResults.courage_receipt.what_actually_happened}</p></div>
                      <div className={`p-3 rounded-xl ${isDark ? 'bg-cyan-900/15' : 'bg-cyan-50'}`}><p className={`text-[10px] font-bold ${isDark ? 'text-cyan-400' : 'text-cyan-700'}`}>THE GAP</p><p className={`text-xs font-bold ${c.text}`}>{debriefResults.courage_receipt.gap}</p></div>
                    </div>
                  </div>
                )}
                {debriefResults.what_you_proved?.length > 0 && (<div className={`${c.card} border rounded-2xl p-5`}><p className={`text-[10px] font-bold ${c.accentTxt} mb-2`}>✅ WHAT YOU PROVED</p>{debriefResults.what_you_proved.map((p, i) => <p key={i} className={`text-xs ${c.textSecondary} mb-0.5`}>✓ {p}</p>)}</div>)}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {debriefResults.growth_note && (<div className={`p-3 rounded-xl ${isDark ? 'bg-cyan-900/15' : 'bg-cyan-50'}`}><p className={`text-[10px] font-bold ${isDark ? 'text-cyan-400' : 'text-cyan-700'}`}>🌱 GROWTH</p><p className={`text-xs ${c.textSecondary}`}>{debriefResults.growth_note}</p></div>)}
                  {debriefResults.next_stretch && (<div className={`p-3 rounded-xl ${isDark ? 'bg-amber-900/15' : 'bg-amber-50'}`}><p className={`text-[10px] font-bold ${isDark ? 'text-amber-400' : 'text-amber-700'}`}>🎯 NEXT STRETCH</p><p className={`text-xs ${c.textSecondary}`}>{debriefResults.next_stretch}</p></div>)}
                </div>
                {debriefResults.save_this && (
                  <div className={`p-4 rounded-xl text-center ${isDark ? 'bg-cyan-900/20 border-2 border-cyan-700/50' : 'bg-cyan-50 border-2 border-cyan-300'}`}>
                    <p className={`text-[10px] font-bold ${c.textMuteded} mb-1`}>📌 SAVE THIS FOR NEXT TIME</p>
                    <p className={`text-sm font-black ${isDark ? 'text-cyan-300' : 'text-cyan-700'}`}>"{debriefResults.save_this}"</p>
                    <div className="mt-2"><CopyBtn content={debriefResults.save_this} label="Copy" /></div>
                  </div>
                )}
                <button onClick={resetAll} className={`w-full py-3 rounded-xl font-bold ${c.btnPrimary}`}>← Done — What's Next?</button>
              </div>
            )}
          </div>
        )}

        {/* ════════ JOURNAL ════════ */}
        {view === 'journal' && (
          <div className="space-y-5">
            <div className="flex items-center justify-between">
              <button onClick={() => results ? setView('results') : setView('form')} className={`text-sm font-semibold px-4 py-2 rounded-xl ${c.btnSecondary}`}>← Back</button>
              <div className="flex gap-2">
                {patterns && <button onClick={() => setView('patterns')} className={`text-xs font-bold px-3 py-1.5 rounded-lg ${c.btnSecondary}`}>📊 Patterns</button>}
                <p className={`text-xs font-bold ${c.textMuteded} self-center`}>{journal.length}</p>
              </div>
            </div>
            <div className={`${c.card} border-2 rounded-2xl p-5 text-center ${isDark ? 'border-cyan-700/50' : 'border-cyan-300'}`}>
              <p className="text-3xl mb-2">🏆</p>
              <p className={`text-lg font-black ${c.text}`}>Courage Journal</p>
              <p className={`text-xs ${c.textSecondary} mt-1`}>Every scary thing you did anyway.</p>
              {journal.length > 0 && (
                <div className="flex items-center justify-center gap-4 mt-3">
                  <div><p className={`text-2xl font-black ${isDark ? 'text-cyan-400' : 'text-cyan-700'}`}>{journal.length}</p><p className={`text-[10px] ${c.textMuteded}`}>Faced</p></div>
                  <div><p className={`text-2xl font-black ${isDark ? 'text-emerald-400' : 'text-emerald-700'}`}>{journal.filter(j => j.confAfter > j.confBefore).length}</p><p className={`text-[10px] ${c.textMuteded}`}>Grew</p></div>
                  <div><p className={`text-2xl font-black ${isDark ? 'text-amber-400' : 'text-amber-700'}`}>{journal.filter(j => j.verdict === 'brave').length}</p><p className={`text-[10px] ${c.textMuteded}`}>Brave 🦁</p></div>
                </div>
              )}
            </div>

            {/* Reframe library highlight */}
            {journal.filter(j => j.saveThis).length >= 2 && (
              <div className={`p-4 rounded-xl ${isDark ? 'bg-emerald-900/15 border border-emerald-800/30' : 'bg-emerald-50 border border-emerald-200'}`}>
                <p className={`text-xs font-bold ${isDark ? 'text-emerald-400' : 'text-emerald-700'} mb-2`}>🪞 Your Reframe Library — proof it worked out:</p>
                {journal.filter(j => j.saveThis).slice(0, 3).map((j, i) => (
                  <div key={i} className="mb-1.5">
                    <p className={`text-xs italic font-bold ${c.text}`}>"{j.saveThis}"</p>
                    <p className={`text-[10px] ${c.textMuteded}`}>{j.situation}</p>
                  </div>
                ))}
              </div>
            )}

            {journal.length === 0 && (
              <div className={`${c.card} border rounded-2xl p-8 text-center`}>
                <p className={`text-sm ${c.textSecondary}`}>No entries yet. Do something scary and come back to debrief.</p>
                <button onClick={() => setView('form')} className={`mt-3 px-4 py-2 rounded-xl text-xs font-bold ${c.btnPrimary}`}>Get Started</button>
              </div>
            )}
            <div className="space-y-2">
              {journal.map(j => (
                <div key={j.id} className={`${c.card} border rounded-2xl p-4`}>
                  <div className="flex items-start justify-between mb-1.5">
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        <span>{j.verdict === 'brave' ? '🦁' : j.verdict === 'you_showed_up' ? '💪' : '📝'}</span>
                        <p className={`text-sm font-bold ${c.text} truncate`}>{j.situation}</p>
                      </div>
                      {j.headline && <p className={`text-xs ${c.textSecondary}`}>{j.headline}</p>}
                    </div>
                    <div className="flex items-center gap-1.5 shrink-0 ml-2">
                      <span className={`text-sm font-black ${confColor(j.confBefore)}`}>{j.confBefore}</span>
                      <span className={`${j.confAfter > j.confBefore ? (isDark ? 'text-emerald-400' : 'text-emerald-600') : c.textMuteded}`}>→</span>
                      <span className={`text-sm font-black ${confColor(j.confAfter)}`}>{j.confAfter}</span>
                    </div>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className={`text-[10px] ${c.textMuteded}`}>{j.date}</span>
                    <button onClick={() => setJournal(prev => prev.filter(p => p.id !== j.id))} className={`text-[10px] ${c.textMuteded} hover:text-zinc-400`}>✕</button>
                  </div>
                  {j.saveThis && (
                    <div className={`mt-2 p-2 rounded-lg ${isDark ? 'bg-cyan-900/10' : 'bg-cyan-50'}`}>
                      <p className={`text-[10px] italic ${isDark ? 'text-cyan-400' : 'text-cyan-700'}`}>"{j.saveThis}"</p>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}

      {/* ── Post-result cross-refs ── */}
      {results && (
        <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
          <p className={`text-[10px] font-bold ${c.textMuted} uppercase mb-2`}>🔗 Related tools</p>
          <div className="flex flex-wrap gap-3">
            <a href="/DifficultTalkCoach" className={`text-xs ${linkStyle}`}>🗣️ Difficult Talk Coach</a>
            <a href="/SpiralStopper" className={`text-xs ${linkStyle}`}>🌀 Spiral Stopper</a>
          </div>
        </div>
      )}
      <p className={`text-xs text-center ${c.textMuted}`}>Results are AI-generated for reflection — not a substitute for professional support.</p>
      {history.length > 0 && (<div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}><p className={`text-xs font-bold ${c.textMuted} mb-2`}>📋 Recent</p><div className="space-y-1">{history.map(s => (<div key={s.id} className="flex items-center justify-between"><span className={`text-xs ${c.textSecondary} truncate`}>{s.preview || 'Session'}</span><span className={`text-xs ${c.textMuted} ml-2`}>{new Date(s.date).toLocaleDateString()}</span></div>))}</div></div>)}
    </div>
  );
};

NerveCheck.displayName = 'NerveCheck';
export default NerveCheck;
