import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';
import { pickExample } from '../utils/exampleRotation';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';
const RECENT_KEY = 'phrase-decoder-recent-log';
const MAX_RECENT = 20;

const CLASSIFICATION_META = {
  IDIOM: ['🧩', 'pd_class_idiom', 'Idiom'],
  SLANG: ['🗯️', 'pd_class_slang', 'Slang'],
  JARGON: ['🧠', 'pd_class_jargon', 'Jargon'],
  METAPHOR: ['🎭', 'pd_class_metaphor', 'Metaphor'],
  EUPHEMISM: ['🌫️', 'pd_class_euphemism', 'Euphemism'],
  REGIONAL_EXPRESSION: ['🗺️', 'pd_class_regional', 'Regional expression'],
  WORKPLACE_PHRASE: ['💼', 'pd_class_workplace', 'Workplace phrase'],
  CULTURAL_REFERENCE: ['📚', 'pd_class_cultural', 'Cultural reference'],
  PROVERB: ['📜', 'pd_class_proverb', 'Proverb'],
  LITERAL: ['🔤', 'pd_class_literal', 'Literal'],
};

const LANGUAGES = [
  ['en', 'English'], ['es', 'Español'], ['zh', '中文'], ['hi', 'हिन्दी'],
  ['ar', 'العربية'], ['pt', 'Português'], ['fr', 'Français'], ['de', 'Deutsch'],
  ['ja', '日本語'], ['ko', '한국어'], ['ru', 'Русский'], ['th', 'ไทย'], ['vi', 'Tiếng Việt'],
];

const EXAMPLES = [
  {
    phrase: "Let's not boil the ocean.",
    context: 'My manager said this when we were talking about everything we wanted to include in the first version of a project.',
  },
  {
    phrase: "That's above my pay grade.",
    context: 'A coworker said this after I asked who could approve an exception.',
  },
  {
    phrase: 'He let him go.',
    context: '',
  },
  {
    phrase: 'The endpoint is idempotent.',
    context: 'An engineer said this while explaining an API to me.',
  },
];

function firstNonEmpty(...values) {
  return values.find(v => typeof v === 'string' && v.trim()) || '';
}

const PhraseDecoder = ({ tool }) => {
  const { callToolEndpoint, loading, userLocale } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();
  const resultsRef = useRef(null);
  const submitRef = useRef(null);
  const canSubmitRef = useRef(false);

  const tr = useCallback((key, fallback) => {
    const value = t(key);
    return !value || value === key ? fallback : value;
  }, [t]);

  const c = {
    card: isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt: isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    text: isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted: isDark ? 'text-zinc-400' : 'text-gray-500',
    required: isDark ? 'text-amber-400' : 'text-amber-700',
    input: isDark
      ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-500 focus:border-cyan-500 focus:ring-cyan-500/20'
      : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-600 focus:ring-cyan-100',
    border: isDark ? 'border-zinc-700' : 'border-gray-200',
    btnPrimary: isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-700 hover:bg-cyan-800 text-white',
    btnSecondary: isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-100 border-zinc-600' : 'bg-gray-100 hover:bg-gray-200 text-gray-700 border-gray-200',
    highlight: isDark ? 'bg-cyan-950/40 border-cyan-800' : 'bg-cyan-50 border-cyan-200',
    warning: isDark ? 'bg-amber-950/35 border-amber-700 text-amber-100' : 'bg-amber-50 border-amber-300 text-amber-900',
    success: isDark ? 'bg-emerald-950/35 border-emerald-700' : 'bg-emerald-50 border-emerald-200',
    danger: isDark ? 'bg-red-950/35 border-red-700 text-red-100' : 'bg-red-50 border-red-300 text-red-900',
    chip: isDark ? 'bg-zinc-700 border-zinc-600 text-zinc-100' : 'bg-white border-gray-200 text-gray-700',
    labelText: isDark ? 'text-zinc-200' : 'text-gray-700',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';

  const [phrase, setPhrase] = useState('');
  const [context, setContext] = useState('');
  const [decoded, setDecoded] = useState(null);
  const [error, setError] = useState('');
  const [showMore, setShowMore] = useState(false);
  const [showResponses, setShowResponses] = useState(false);
  const [showRecent, setShowRecent] = useState(false);
  const [recentLog, setRecentLog] = usePersistentState(RECENT_KEY, []);
  const [equivLanguage, setEquivLanguage] = useState('es');
  const [equivResult, setEquivResult] = useState(null);
  const [equivLoading, setEquivLoading] = useState(false);
  const [refineContext, setRefineContext] = useState('');
  const hasRecentLog = recentLog.length > 0;

  const resetResultOnly = useCallback(() => {
    setDecoded(null);
    setError('');
    setShowMore(false);
    setShowResponses(false);
    setEquivResult(null);
    setRefineContext('');
  }, []);

  const startOver = useCallback(() => {
    setPhrase('');
    setContext('');
    resetResultOnly();
    window.scrollTo?.({ top: 0, behavior: 'smooth' });
  }, [resetResultOnly]);

  const loadExample = useCallback(() => {
    const ex = pickExample('PhraseDecoder', EXAMPLES);
    setPhrase(ex.phrase);
    setContext(ex.context);
    resetResultOnly();
  }, [resetResultOnly]);

  const saveToRecentLog = useCallback((entry) => {
    setRecentLog(prev => {
      const cleaned = (Array.isArray(prev) ? prev : []).filter(x => x.id !== entry.id);
      return [entry, ...cleaned].slice(0, MAX_RECENT);
    });
  }, [setRecentLog]);

  const runDecode = useCallback(async (overrideContext = null) => {
    if (!phrase.trim()) {
      setError(tr('pd_err_phrase', 'Enter the phrase you want to understand.'));
      return;
    }
    setError('');
    setEquivResult(null);
    const actualContext = overrideContext === null ? context.trim() : overrideContext.trim();
    try {
      const data = await callToolEndpoint('phrase-decoder', {
        phrase: phrase.trim(),
        context: actualContext,
        userLanguage: userLocale || 'en',
      });
      setDecoded(data);
      setContext(actualContext);
      setShowMore(false);
      setShowResponses(false);
      setRefineContext('');
      const cleanPhrase = phrase.trim();
      saveToRecentLog({
        id: `${Date.now()}-${cleanPhrase.slice(0, 24)}`,
        phrase: cleanPhrase,
        preview: cleanPhrase.slice(0, 40),
        context: actualContext,
        result: data,
        date: new Date().toISOString(),
      });
      setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 80);
    } catch (e) {
      setError(e?.message || tr('pd_err_request', 'Phrase Decoder could not complete that request. Please try again.'));
    }
  }, [phrase, context, callToolEndpoint, userLocale, saveToRecentLog, tr]);

  // Keyboard shortcut (Cmd/Ctrl+Enter) — refs kept current every render.
  canSubmitRef.current = !!phrase.trim();
  submitRef.current = () => runDecode();
  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && !loading && canSubmitRef.current) submitRef.current?.();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, [loading]);

  const revisitRecentLog = useCallback((entry) => {
    setPhrase(entry.phrase || '');
    setContext(entry.context || '');
    setDecoded(null);
    setShowRecent(false);
    setEquivResult(null);
    window.scrollTo?.({ top: 0, behavior: 'smooth' });
  }, []);

  const viewRecentLog = useCallback((entry) => {
    setPhrase(entry.phrase || '');
    setContext(entry.context || '');
    setDecoded(entry.result || null);
    setShowRecent(false);
    setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 80);
  }, []);

  const runEquivalent = useCallback(async () => {
    if (!decoded || !phrase.trim()) return;
    setEquivLoading(true);
    setEquivResult(null);
    setError('');
    try {
      const data = await callToolEndpoint('phrase-decoder/equivalent', {
        phrase: phrase.trim(),
        plainMeaning: decoded.plain_meaning || '',
        contextualMeaning: decoded.contextual_meaning?.meaning || '',
        sourceContext: context.trim(),
        targetLanguage: equivLanguage,
        userLanguage: userLocale || 'en',
      });
      setEquivResult(data);
    } catch (e) {
      setError(e?.message || tr('pd_err_equivalent', 'Could not find an equivalent right now.'));
    } finally {
      setEquivLoading(false);
    }
  }, [decoded, phrase, context, equivLanguage, callToolEndpoint, userLocale, tr]);

  const runRefinedContext = useCallback(() => {
    const merged = [context.trim(), refineContext.trim()].filter(Boolean).join('\n');
    if (!refineContext.trim()) return;
    runDecode(merged);
  }, [context, refineContext, runDecode]);

  const classBadges = useMemo(() => {
    const list = Array.isArray(decoded?.classifications) ? decoded.classifications : [];
    return list.map((item, idx) => {
      const code = typeof item === 'string' ? item : item?.type;
      const meta = CLASSIFICATION_META[code] || ['🏷️', '', code || ''];
      const label = meta[1] ? tr(meta[1], meta[2]) : meta[2];
      return { code, label, icon: meta[0], why: typeof item === 'object' ? item.why : '', idx };
    }).filter(x => x.code);
  }, [decoded, tr]);

  const buildFullText = useCallback(() => {
    if (!decoded) return '';
    const parts = [
      `Phrase Decoder`,
      `\n${phrase}`,
      classBadges.length ? `\nWhat kind of phrase: ${classBadges.map(x => x.label).join(' · ')}` : '',
      decoded.plain_meaning ? `\nPlain meaning: ${decoded.plain_meaning}` : '',
      decoded.contextual_meaning?.available && decoded.contextual_meaning?.meaning ? `\nWhat it means here: ${decoded.contextual_meaning.meaning}` : '',
      decoded.tone?.available && decoded.tone?.description ? `\nTone: ${decoded.tone.description}` : '',
      decoded.say_it_plainly ? `\nSay it plainly: ${decoded.say_it_plainly}` : '',
      decoded.background?.available && decoded.background?.explanation ? `\n${decoded.background.heading || 'Background'}: ${decoded.background.explanation}` : '',
      decoded.regional_note?.available && decoded.regional_note?.explanation ? `\nRegional note: ${decoded.regional_note.explanation}` : '',
    ];
    return parts.filter(Boolean).join('\n') + BRAND;
  }, [decoded, phrase, classBadges]);

  useRegisterActions(buildFullText(), tool?.title || tr('pd_title', 'Phrase Decoder'));

  const ambiguous = decoded?.ambiguity?.needs_context;
  const responseOptions = Array.isArray(decoded?.response_help?.responses) ? decoded.response_help.responses : [];
  const results = decoded; // alias for the pre/post-result JSX split below

  return (
    <div className={`space-y-4 ${c.text}`}>
      <div className={`${c.card} border ${c.border} rounded-xl p-4 sm:p-5`}>
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <div className="text-lg font-bold"><span className="me-2">{tool?.icon ?? '💬'}</span>{tr('pd_tagline', 'What they said. What kind of expression it is. What it actually means.')}</div>
            <p className={`mt-1 text-sm ${c.textSecondary}`}>
              {tr('pd_intro', "Heard or read a phrase that doesn't make sense? Enter it—or paste the sentence around it. Phrase Decoder identifies what kind of expression it is and explains what it means in plain language and in your context.")}
            </p>
          </div>
          {(phrase || decoded) && (
            <button onClick={startOver} className={`${c.btnSecondary} border px-3 py-2 rounded-lg text-xs font-bold min-h-[40px]`}>
              ↺ {tr('pd_start_over', 'Start Over')}
            </button>
          )}
        </div>

        <button onClick={loadExample} disabled={loading}
          style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }}
          className="mt-4 px-4 py-2 rounded-full text-sm font-semibold border border-black/25 text-zinc-900 shadow-sm hover:brightness-105 hover:shadow transition disabled:opacity-40 whitespace-nowrap">
          ✨ {tr('pd_try_example', 'Try an example')}
        </button>

        <div className={`mt-5 pt-5 border-t ${c.border} space-y-4`}>
          <label className="block">
            <span className="text-sm font-bold">{tr('pd_phrase_label', 'What did they say?')} <span className={c.required}>*</span></span>
            <textarea
              value={phrase}
              onChange={e => { setPhrase(e.target.value); resetResultOnly(); }}
              rows={2}
              placeholder={tr('pd_phrase_placeholder', 'e.g. “We don’t want to boil the ocean.”')}
              className={`mt-2 w-full rounded-xl border p-3 text-base ${c.input}`}
            />
          </label>

          <label className="block">
            <span className="text-sm font-bold">{tr('pd_context_label', 'Where did you hear or read it?')} <span className={`font-normal ${c.textMuted}`}>{tr('pd_optional', 'optional')}</span></span>
            <span className={`block text-xs mt-1 ${c.textMuted}`}>{tr('pd_context_help', 'Paste the sentence or a little of the conversation. Context can change the meaning.')}</span>
            <textarea
              value={context}
              onChange={e => { setContext(e.target.value); resetResultOnly(); }}
              rows={3}
              placeholder={tr('pd_context_placeholder', 'e.g. “My manager said this while we were deciding what to include in the first release.”')}
              className={`mt-2 w-full rounded-xl border p-3 text-sm ${c.input}`}
            />
          </label>

          {error && <div className={`${c.danger} border rounded-lg p-3 text-sm`}>{error}</div>}

          <button
            onClick={() => runDecode()}
            disabled={loading || !phrase.trim()}
            className={`w-full rounded-xl px-5 py-3 font-bold min-h-[48px] transition disabled:opacity-40 ${phrase.trim() && !loading ? c.btnPrimary : `${c.btnSecondary} cursor-not-allowed`}`}
          >
            {loading
              ? <><span className="inline-block animate-spin">{tool?.icon ?? '💬'}</span> {tr('pd_working', 'Decoding…')}</>
              : <>{tool?.icon ?? '💬'} {tr('pd_submit', 'Decode This Phrase')} →</>}
          </button>
        </div>
      </div>

      {hasRecentLog && (
        <div className={`${c.card} border ${c.border} rounded-xl overflow-hidden`}>
          <button onClick={() => setShowRecent(v => !v)} className="w-full p-4 flex items-center justify-between text-start">
            <span className="font-bold">🕘 {tr('pd_recent', 'Recent')}</span>
            <span>{showRecent ? '▲' : '▼'}</span>
          </button>
          {showRecent && (
            <div className={`border-t ${c.border} p-3 space-y-2`}>
              {recentLog.map(entry => {
                const classes = (entry.result?.classifications || []).map(x => CLASSIFICATION_META[typeof x === 'string' ? x : x.type]?.[2]).filter(Boolean).slice(0, 3);
                return (
                  <div key={entry.id} className={`${c.cardAlt} rounded-lg p-3 flex flex-col sm:flex-row sm:items-center justify-between gap-3`}>
                    <div className="min-w-0">
                      <div className="font-semibold truncate">“{entry.preview || entry.phrase}”</div>
                      {classes.length > 0 && <div className={`text-xs mt-1 ${c.textMuted}`}>{classes.join(' · ')}</div>}
                    </div>
                    <div className="flex gap-2 shrink-0">
                      <button onClick={() => viewRecentLog(entry)} className={`${c.btnSecondary} border px-3 py-1.5 rounded-lg text-xs font-bold`}>{tr('pd_view', 'View')}</button>
                      <button onClick={() => revisitRecentLog(entry)} className={`${c.btnSecondary} border px-3 py-1.5 rounded-lg text-xs font-bold`}>{tr('pd_revisit', 'Revisit')}</button>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      )}

      {!results && (
        <p className={`text-xs ${c.textMuted} text-center`}>
          {tr('pd_xref_pre', 'Need a whole document explained, not just one phrase?')} <a href="/JargonAssassin" className={linkStyle}>🗡️ {tr('pd_xref_jargon', 'Jargon Assassin')}</a>
        </p>
      )}

      {results && (
        <div ref={resultsRef} className="space-y-4 scroll-mt-24">
          <div className={`${c.card} border ${c.border} rounded-xl p-5`}>
            <div className={`text-xs font-bold uppercase tracking-wide ${c.textMuted}`}>{tr('pd_what_they_said', 'What they said')}</div>
            <div className="text-xl sm:text-2xl font-bold mt-1">“{phrase}”</div>
          </div>

          <div className={`${c.card} border ${c.border} rounded-xl p-5`}>
            <div className="font-bold">🏷️ {tr('pd_kind', 'What kind of phrase is it?')}</div>
            {decoded.classification_status === 'UNCLEAR' || ambiguous ? (
              <div className={`${c.warning} border rounded-lg p-3 mt-3 font-semibold`}>
                {tr('pd_unclear', 'Unclear / needs context')}
              </div>
            ) : null}
            {classBadges.length > 0 && (
              <div className="flex flex-wrap gap-2 mt-3">
                {classBadges.map(item => (
                  <span key={`${item.code}-${item.idx}`} className={`${c.chip} border rounded-full px-3 py-1.5 text-xs font-bold`} title={item.why || ''}>
                    {item.icon} {item.label}
                  </span>
                ))}
              </div>
            )}
          </div>

          {decoded.plain_meaning && (
            <div className={`${c.highlight} border rounded-xl p-5`}>
              <div className="font-bold">💡 {tr('pd_plain_meaning', 'Plain meaning')}</div>
              <div className="mt-2 text-base leading-relaxed">{decoded.plain_meaning}</div>
            </div>
          )}

          {decoded.contextual_meaning?.available && decoded.contextual_meaning?.meaning && (
            <div className={`${c.card} border ${c.border} rounded-xl p-5`}>
              <div className="font-bold">💬 {tr('pd_here', 'What it means here')}</div>
              <div className={`mt-2 leading-relaxed ${c.textSecondary}`}>{decoded.contextual_meaning.meaning}</div>
            </div>
          )}

          {decoded.tone?.available && decoded.tone?.description && (
            <div className={`${c.card} border ${c.border} rounded-xl p-5`}>
              <div className="font-bold">🎭 {tr('pd_tone', 'The tone')}</div>
              <div className={`mt-2 ${c.textSecondary}`}>{decoded.tone.description}</div>
              {decoded.tone.depends_on_delivery && <div className={`mt-2 text-xs ${c.textMuted}`}>{tr('pd_delivery_note', 'Delivery and surrounding context can change the tone.')}</div>}
            </div>
          )}

          {decoded.say_it_plainly && (
            <div className={`${c.success} border rounded-xl p-5`}>
              <div className="font-bold">📝 {tr('pd_say_plainly', 'Say it plainly')}</div>
              <div className="mt-2 text-base">“{decoded.say_it_plainly}”</div>
            </div>
          )}

          {ambiguous && (
            <div className={`${c.card} border ${c.border} rounded-xl p-5`}>
              <div className="font-bold">🤔 {tr('pd_possible_readings', 'Possible readings')}</div>
              <div className="mt-3 space-y-3">
                {(decoded.ambiguity?.possible_readings || []).map((r, i) => (
                  <div key={i} className={`${c.cardAlt} rounded-lg p-3`}>
                    <div className="font-semibold text-sm">{r.classification || tr('pd_possible', 'Possible meaning')}</div>
                    <div className={`text-sm mt-1 ${c.textSecondary}`}>{r.meaning}</div>
                  </div>
                ))}
              </div>
              {decoded.ambiguity?.what_would_help && (
                <div className={`mt-3 text-sm ${c.textSecondary}`}><strong>{tr('pd_what_settle', 'What would settle it:')}</strong> {decoded.ambiguity.what_would_help}</div>
              )}
            </div>
          )}

          <div className={`${c.card} border ${c.border} rounded-xl overflow-hidden`}>
            <button onClick={() => setShowMore(v => !v)} className="w-full p-4 flex justify-between items-center text-start font-bold">
              <span>➕ {tr('pd_more', 'More about this phrase')}</span><span>{showMore ? '▲' : '▼'}</span>
            </button>
            {showMore && (
              <div className={`border-t ${c.border} p-4 space-y-4`}>
                {decoded.background?.available && decoded.background?.explanation && (
                  <div>
                    <div className="font-semibold">📚 {firstNonEmpty(decoded.background.heading, tr('pd_background', 'Background'))}</div>
                    <div className={`mt-1 text-sm ${c.textSecondary}`}>{decoded.background.explanation}</div>
                  </div>
                )}
                {decoded.regional_note?.available && decoded.regional_note?.explanation && (
                  <div>
                    <div className="font-semibold">🗺️ {tr('pd_regional_note', 'Regional note')}</div>
                    <div className={`mt-1 text-sm ${c.textSecondary}`}>{decoded.regional_note.explanation}</div>
                  </div>
                )}
                {!decoded.background?.available && !decoded.regional_note?.available && (
                  <div className={`text-sm ${c.textMuted}`}>{tr('pd_no_extra', 'There is no extra background you need in order to understand this phrase.')}</div>
                )}

                <div className={`pt-3 border-t ${c.border}`}>
                  <div className="font-semibold">🌍 {tr('pd_equiv_title', 'Something similar in another language')}</div>
                  <div className="flex flex-col sm:flex-row gap-2 mt-2">
                    <select value={equivLanguage} onChange={e => setEquivLanguage(e.target.value)} className={`rounded-lg border px-3 py-2 text-sm ${c.input}`}>
                      {LANGUAGES.map(([code, label]) => <option key={code} value={code}>{label}</option>)}
                    </select>
                    <button onClick={runEquivalent} disabled={equivLoading} className={`${c.btnSecondary} border rounded-lg px-4 py-2 text-sm font-bold disabled:opacity-40`}>
                      {equivLoading ? tr('pd_working', 'Working…') : tr('pd_find_equiv', 'Find an equivalent')}
                    </button>
                  </div>
                  {equivResult && (
                    <div className={`${c.cardAlt} rounded-lg p-3 mt-3 text-sm`}>
                      {equivResult.equivalent_type === 'FUNCTIONAL_EQUIVALENT' && equivResult.equivalent ? (
                        <>
                          <div className="font-semibold">{equivResult.equivalent}</div>
                          <div className={`mt-1 ${c.textSecondary}`}>{equivResult.explanation}</div>
                        </>
                      ) : (
                        <div className={c.textSecondary}>{equivResult.plain_explanation || equivResult.explanation}</div>
                      )}
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>

          {decoded.response_help?.available && responseOptions.length > 0 && (
            <div className={`${c.card} border ${c.border} rounded-xl overflow-hidden`}>
              <button onClick={() => setShowResponses(v => !v)} className="w-full p-4 flex justify-between items-center text-start font-bold">
                <span>💬 {tr('pd_respond', 'How could I respond?')}</span><span>{showResponses ? '▲' : '▼'}</span>
              </button>
              {showResponses && (
                <div className={`border-t ${c.border} p-4 space-y-3`}>
                  {responseOptions.map((r, i) => (
                    <div key={i} className={`${c.cardAlt} rounded-lg p-3`}>
                      {r.label && <div className={`text-xs font-bold uppercase tracking-wide ${c.textMuted}`}>{r.label}</div>}
                      <div className="mt-1">“{r.text}”</div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          <div className={`${c.card} border ${c.border} rounded-xl p-5`}>
            <div className="font-bold">➕ {tr('pd_whole_sentence', 'What about the whole sentence?')}</div>
            <div className={`text-xs mt-1 ${c.textMuted}`}>{tr('pd_refine_help', 'Add more of the sentence or conversation. Phrase Decoder will re-evaluate the contextual meaning without treating its earlier interpretation as fact.')}</div>
            <textarea value={refineContext} onChange={e => setRefineContext(e.target.value)} rows={3} className={`mt-3 w-full rounded-xl border p-3 text-sm ${c.input}`} placeholder={tr('pd_refine_placeholder', 'Add the surrounding sentence or a little more context…')} />
            <button onClick={runRefinedContext} disabled={!refineContext.trim() || loading} className={`${c.btnSecondary} border mt-2 rounded-lg px-4 py-2 text-sm font-bold disabled:opacity-40`}>
              {tr('pd_recheck_context', 'Recheck with this context')} →
            </button>
          </div>

          <p className={`text-xs ${c.textMuted} text-center`}>
            {tr('pd_xref_post', 'Got a whole document full of unfamiliar language instead of one phrase?')} <a href="/JargonAssassin" className={linkStyle}>🗡️ {tr('pd_xref_jargon', 'Jargon Assassin')}</a>
          </p>
        </div>
      )}
    </div>
  );
};

PhraseDecoder.displayName = 'PhraseDecoder';
export default PhraseDecoder;
