import React, { useState, useRef, useMemo, useCallback, useEffect } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { CopyBtn } from '../components/ActionButtons';
import { useRegisterActions } from '../components/ActionBarContext';
import { usePersistentState } from '../hooks/usePersistentState';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

// ════════════════════════════════════════════════════════════
// CONSTANTS
// ════════════════════════════════════════════════════════════

const TEXT_TYPES = [
  { id: 'auto', label: 'Auto-Detect', emoji: '🔍' },
  { id: 'legal', label: 'Legal / Contract', emoji: '⚖️' },
  { id: 'medical', label: 'Medical', emoji: '🏥' },
  { id: 'academic', label: 'Academic / Research', emoji: '🎓' },
  { id: 'financial', label: 'Financial', emoji: '💰' },
  { id: 'technical', label: 'Technical / Manual', emoji: '🔧' },
  { id: 'literary', label: 'Literary / Creative', emoji: '📖' },
  { id: 'political', label: 'Political / Policy', emoji: '🏛️' },
  { id: 'bureaucratic', label: 'Government / Forms', emoji: '📋' },
  { id: 'scientific', label: 'Scientific', emoji: '🔬' },
];

const TABS = [
  { id: 'overview', label: 'Overview', emoji: '📊' },
  { id: 'translation', label: 'Full Translation', emoji: '💬' },
  { id: 'xray', label: 'X-Ray', emoji: '🔬' },
  { id: 'sidebyside', label: 'Side-by-Side', emoji: '↔️' },
  { id: 'compare', label: 'Compare', emoji: '🔀' },
];

const SEVERITY_COLORS = {
  critical: { light: 'bg-red-50 border-red-200', dark: 'bg-red-900/20 border-red-800/40', dot: 'bg-red-500', badge: 'bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300' },
  significant: { light: 'bg-amber-50 border-amber-200', dark: 'bg-amber-900/20 border-amber-800/40', dot: 'bg-amber-500', badge: 'bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300' },
  minor: { light: 'bg-sky-50 border-sky-200', dark: 'bg-sky-900/20 border-sky-800/40', dot: 'bg-sky-400', badge: 'bg-sky-100 text-sky-700 dark:bg-sky-900/40 dark:text-sky-300' },
  cosmetic: { light: 'bg-zinc-50 border-zinc-200', dark: 'bg-zinc-700/30 border-zinc-600', dot: 'bg-zinc-400', badge: 'bg-zinc-100 text-zinc-600 dark:bg-zinc-600 dark:text-zinc-300' },
};

const CHANGE_CATEGORY_LABELS = {
  added: { emoji: '➕', label: 'Added', color: 'text-emerald-600 dark:text-emerald-400' },
  removed: { emoji: '➖', label: 'Removed', color: 'text-red-600 dark:text-red-400' },
  modified: { emoji: '✏️', label: 'Modified', color: 'text-amber-600 dark:text-amber-400' },
  reworded: { emoji: '🔄', label: 'Reworded', color: 'text-cyan-600 dark:text-cyan-400' },
};

const IMPORTANCE_COLORS = {
  high: { light: 'bg-red-50 border-red-200', dark: 'bg-red-900/20 border-red-800/40', dot: 'bg-red-500', label: 'text-red-700 dark:text-red-300' },
  medium: { light: 'bg-amber-50 border-amber-200', dark: 'bg-amber-900/20 border-amber-800/40', dot: 'bg-amber-500', label: 'text-amber-700 dark:text-amber-300' },
  low: { light: 'bg-zinc-50 border-zinc-200', dark: 'bg-zinc-700/30 border-zinc-600', dot: 'bg-zinc-400', label: 'text-zinc-600 dark:text-zinc-400' },
};

const SPECIALIST_TOOLS = {
  OfferDissector: { label: 'Offer Dissector', emoji: '💼', desc: 'Analyze compensation packages and job offers' },
  DoctorVisitTranslator: { label: 'Doctor Visit Translator', emoji: '🏥', desc: 'Decode medical notes and test results' },
  BillGuiltEraser: { label: 'Bill Guilt Eraser', emoji: '💳', desc: 'Analyze billing statements and charges' },
  ComplaintEscalationWriter: { label: 'Complaint Escalation Writer', emoji: '📨', desc: 'Draft effective complaint letters' },
  JargonAssassin: { label: 'Jargon Assassin', emoji: '🗡️', desc: 'Deep-dive jargon replacement' },
  FakeReviewDetective: { label: 'Fake Review Detective', emoji: '🔎', desc: 'Analyze authenticity of reviews' },
};

const SAMPLE_TEXTS = [
  {
    label: '⚖️ Lease clause',
    text: `Tenant shall be liable for and shall indemnify and hold harmless Landlord from and against any and all claims, actions, damages, liability and expense in connection with loss of life, personal injury or damage to property arising from or out of any occurrence in, upon or at the Premises, or the occupancy or use by Tenant of the Premises or any part thereof, or occasioned wholly or in part by any act or omission of Tenant, its agents, contractors, employees, servants, invitees, licensees or concessionaires.`,
  },
  {
    label: '🏥 Lab result',
    text: `Hemoglobin A1c: 6.8% (Reference: <5.7% normal, 5.7-6.4% prediabetes, ≥6.5% diabetes). Fasting glucose: 142 mg/dL (Reference: 70-100 mg/dL). eGFR: 62 mL/min/1.73m² (Reference: >90 normal, 60-89 mildly decreased). TSH: 2.4 mIU/L (Reference: 0.4-4.0 mIU/L). Recommend endocrinology referral for glycemic management optimization. Continue current ACE inhibitor for renal protective effect. Recheck in 3 months with comprehensive metabolic panel.`,
  },
  {
    label: '🎓 Abstract',
    text: `We demonstrate that autoregressive language models exhibit emergent few-shot learning capabilities that scale predictably with model size. Specifically, we find that performance on downstream NLP tasks follows a power-law relationship with compute budget, suggesting that continued scaling will yield further improvements. However, we observe that this relationship exhibits phase transitions at certain scale thresholds, where qualitatively new capabilities appear discontinuously. These findings have significant implications for the allocation of research resources and the development of AI safety frameworks.`,
  },
];

// ════════════════════════════════════════════════════════════
// STREAMING PROGRESS
// ════════════════════════════════════════════════════════════


// ════════════════════════════════════════════════════════════
// MAIN COMPONENT
// ════════════════════════════════════════════════════════════

const PlainTalk = ({ tool }) => {
  const { callToolEndpoint, loading } = useClaudeAPI();
  const { isDark } = useTheme();

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-500' : 'text-gray-400',
    required:      isDark ? 'text-amber-400' : 'text-amber-500',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-200 text-red-800',
    infoBox:       isDark ? 'bg-sky-900/20 border-sky-700 text-sky-200' : 'bg-sky-50 border-sky-200 text-sky-800',
    successBox:    isDark ? 'bg-emerald-900/20 border-emerald-700' : 'bg-emerald-50 border-emerald-300',
    successTxt:    isDark ? 'text-emerald-300' : 'text-emerald-800',
    warningBox:    isDark ? 'bg-amber-900/20 border-amber-700' : 'bg-amber-50 border-amber-300',
    warningTxt:    isDark ? 'text-amber-300' : 'text-amber-800',
    pillActive:    isDark ? 'border-cyan-500 bg-cyan-900/30 text-cyan-200' : 'border-cyan-600 bg-cyan-100 text-cyan-900',
    pillInactive:  isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500'
                          : 'border-gray-300 text-gray-500 hover:border-gray-400',
  };
  c.textMuteded = c.textMuted;
  c.label       = c.labelText;
  // PlainTalk-specific extensions
  c.tabActive   = isDark ? 'border-cyan-500 text-cyan-300 bg-zinc-700/30' : 'border-cyan-600 text-cyan-700 bg-cyan-50';
  c.tabInactive = isDark ? 'border-transparent text-zinc-400 hover:text-zinc-200' : 'border-transparent text-gray-500 hover:text-gray-700';

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-600 hover:text-cyan-700 underline underline-offset-2';

  // ── useState ──
  const [inputText, setInputText] = useState('');
  const [textType, setTextType] = useState('auto');
  const [focusQuestion, setFocusQuestion] = useState('');
  const [fileName, setFileName] = useState('');
  const [error, setError] = useState('');
  const [activeTab, setActiveTab] = useState('overview');
  const [expandedSections, setExpandedSections] = useState({});
  const [followUpQuestion, setFollowUpQuestion] = useState('');
  const [followUpAnswers, setFollowUpAnswers] = useState([]);
  const [followUpLoading, setFollowUpLoading] = useState(false);
  const [showGlossary, setShowGlossary] = useState(false);
  const [compareTextA, setCompareTextA] = useState('');
  const [compareTextB, setCompareTextB] = useState('');
  const [compareLabelA, setCompareLabelA] = useState('Original');
  const [compareLabelB, setCompareLabelB] = useState('Revised');
  const [compareResult, setCompareResult] = useState(null);
  const [compareLoading, setCompareLoading] = useState(false);
  const [sectionFilter, setSectionFilter] = useState('all'); // all|high|flagged
  const [changeFilter, setChangeFilter] = useState('all'); // all|critical|significant|minor
  const [editingNote, setEditingNote] = useState(null); // section id
  const [noteText, setNoteText] = useState('');
  const [reviewedSections, setReviewedSections] = useState({});

  // ── useRef ──
  const fileInputRef = useRef(null);
  const resultsRef = useRef(null);

  // ── usePersistentState ──
  const [result, setResult] = usePersistentState('plaintalk-result', null);
  const [history, setHistory] = usePersistentState('plaintalk-history', []);
  const [annotations, setAnnotations] = usePersistentState('pt-annotations', {});

  // ═══════════════════════════════════════
  // FILE HANDLING
  // ═══════════════════════════════════════

  const handleFileUpload = async (e) => {
    const file = e.target.files[0];
    if (!file) return;
    setError('');
    setFileName(file.name);

    try {
      if (file.type === 'application/pdf') {
        // Read PDF as text — basic extraction
        const arrayBuffer = await file.arrayBuffer();
        const bytes = new Uint8Array(arrayBuffer);
        // Simple PDF text extraction — look for text between stream markers
        let text = '';
        const decoder = new TextDecoder('utf-8', { fatal: false });
        const rawText = decoder.decode(bytes);

        // Try to extract readable text content from PDF
        const textMatches = rawText.match(/\(([^)]+)\)/g);
        if (textMatches && textMatches.length > 10) {
          text = textMatches.map(m => m.slice(1, -1)).join(' ');
        }

        // Fallback: extract anything that looks like sentences
        if (text.length < 50) {
          const lines = rawText.split('\n').filter(line => {
            const clean = line.replace(/[^a-zA-Z\s]/g, '').trim();
            return clean.length > 20 && /[a-z]/.test(clean);
          });
          text = lines.join('\n');
        }

        if (text.trim().length < 30) {
          setError('Could not extract text from this PDF. For scanned documents, try copying and pasting the text instead.');
          return;
        }
        setInputText(text.trim());
      } else {
        // Plain text / other readable formats
        const text = await file.text();
        setInputText(text);
      }
    } catch (err) {
      setError('Failed to read file. Try a .txt or .pdf file, or paste text directly.');
    }
  };

  // ═══════════════════════════════════════
  // ANALYSIS
  // ═══════════════════════════════════════

  const handleAnalyze = async () => {
    if (!inputText.trim()) { setError('Paste or upload some text first'); return; }
    if (inputText.trim().length < 30) { setError('Text is too short — paste at least a paragraph'); return; }
    setError(''); setResult(null); setFollowUpAnswers([]);
    try {
      const data = await callToolEndpoint('plaintalk', {
        text: inputText.trim(),
        textType,
        focusQuestion: focusQuestion.trim() || null,
      });
      setResult(data);
      setHistory(prev => [{ id: Date.now(), date: new Date().toISOString(), preview: (inputText || '').slice(0, 40) }, ...prev].slice(0, 6));
      setActiveTab('overview');
      const autoExpand = {};
      (data.sections || []).forEach(s => { if (s.importance === 'high') autoExpand[s.id] = true; });
      setExpandedSections(autoExpand);
    } catch (err) {
      setError(err.message || 'Analysis failed. Please try again.');
    }
  };

  const handleFollowUp = async () => {
    if (!followUpQuestion.trim() || !result) return;
    setFollowUpLoading(true);
    try {
      const data = await callToolEndpoint('plaintalk/followup', {
        originalText: inputText.trim(),
        question: followUpQuestion.trim(),
        previousAnalysis: result,
      });
      setFollowUpAnswers(prev => [...prev, { question: followUpQuestion.trim(), ...data }]);
      setFollowUpQuestion('');
    } catch (err) {
      setError(err.message || 'Failed to answer follow-up question');
    } finally {
      setFollowUpLoading(false);
    }
  };

  const handleReset = () => {
    setInputText(''); setTextType('auto'); setFocusQuestion('');
    setFileName(''); setResult(null); setError('');
    setActiveTab('overview'); setExpandedSections({});
    setFollowUpAnswers([]); setFollowUpQuestion('');
    setShowGlossary(false); setCompareTextA(''); setCompareTextB('');
    setCompareResult(null); setSectionFilter('all'); setChangeFilter('all');
    setEditingNote(null); setNoteText(''); setReviewedSections({});
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  const toggleSection = (id) => {
    setExpandedSections(prev => ({ ...prev, [id]: !prev[id] }));
  };

  const expandAll = () => {
    const all = {};
    (result?.sections || []).forEach(s => { all[s.id] = true; });
    setExpandedSections(all);
  };
  const collapseAll = () => setExpandedSections({});

  // ═══════════════════════════════════════
  // COMPARE MODE
  // ═══════════════════════════════════════

  const handleCompare = async () => {
    if (!compareTextA.trim() || !compareTextB.trim()) {
      setError('Paste both documents to compare'); return;
    }
    setCompareLoading(true); setError(''); setCompareResult(null);
    try {
      const data = await callToolEndpoint('plaintalk/compare', {
        textA: compareTextA.trim(),
        textB: compareTextB.trim(),
        labelA: compareLabelA,
        labelB: compareLabelB,
        textType,
      });
      setCompareResult(data);
    } catch (err) {
      setError(err.message || 'Comparison failed');
    } finally {
      setCompareLoading(false);
    }
  };

  // ═══════════════════════════════════════
  // SECTION FILTERING
  // ═══════════════════════════════════════

  const filteredSections = useMemo(() => {
    if (!result?.sections) return [];
    let sections = result.sections;
    if (sectionFilter === 'high') sections = sections.filter(s => s.importance === 'high');
    if (sectionFilter === 'flagged') sections = sections.filter(s => s.flags?.length > 0);
    return sections;
  }, [result, sectionFilter]);

  const sectionCounts = useMemo(() => {
    if (!result?.sections) return { all: 0, high: 0, flagged: 0 };
    return {
      all: result.sections.length,
      high: result.sections.filter(s => s.importance === 'high').length,
      flagged: result.sections.filter(s => s.flags?.length > 0).length,
    };
  }, [result]);

  // ═══════════════════════════════════════
  // ANNOTATIONS / NOTES
  // ═══════════════════════════════════════

  const saveNote = useCallback((sectionId) => {
    if (!noteText.trim()) { setEditingNote(null); return; }
    setAnnotations(prev => ({
      ...prev,
      [sectionId]: { text: noteText.trim(), date: new Date().toISOString() },
    }));
    setEditingNote(null);
    setNoteText('');
  }, [noteText, setAnnotations]);

  const deleteNote = useCallback((sectionId) => {
    setAnnotations(prev => {
      const next = { ...prev };
      delete next[sectionId];
      return next;
    });
  }, [setAnnotations]);

  const startEditing = useCallback((sectionId) => {
    setEditingNote(sectionId);
    setNoteText(annotations[sectionId]?.text || '');
  }, [annotations]);

  const annotationCount = useMemo(() => Object.keys(annotations).length, [annotations]);

  // ═══════════════════════════════════════
  // HIGHLIGHT-TO-ASK
  // ═══════════════════════════════════════

  const handleTextSelection = useCallback(() => {
    const selection = window.getSelection();
    if (selection && selection.toString().trim().length > 10) {
      const selectedText = selection.toString().trim().slice(0, 300);
      setFollowUpQuestion(`What does this mean: "${selectedText}"`);
    }
  }, []);

  // ═══════════════════════════════════════
  // READING PROGRESS
  // ═══════════════════════════════════════

  const markReviewed = useCallback((sectionId) => {
    setReviewedSections(prev => ({ ...prev, [sectionId]: !prev[sectionId] }));
  }, []);

  const reviewProgress = useMemo(() => {
    if (!result?.sections) return null;
    const total = result.sections.length;
    const reviewed = Object.values(reviewedSections).filter(Boolean).length;
    return { total, reviewed, percent: total > 0 ? Math.round((reviewed / total) * 100) : 0 };
  }, [result, reviewedSections]);

  // ═══════════════════════════════════════
  // COMPUTED
  // ═══════════════════════════════════════

  const wordCount = useMemo(() => inputText.trim().split(/\s+/).filter(Boolean).length, [inputText]);

  const buildFullText = useCallback(() => {
    if (!result) return '';
    const lines = [
      `📄 PlainTalk Analysis — ${result.detected_type_label || result.detected_type}`,
      '',
      `📊 Reading Level: ${result.reading_level?.original || '?'} → ${result.reading_level?.translated || '?'}`,
      '',
      '═══ OVERVIEW ═══',
      result.overview?.one_sentence || '',
      '',
      'Key Takeaways:',
      ...(result.overview?.key_takeaways || []).map((t, i) => `${i + 1}. ${t}`),
      '',
    ];
    if (result.overview?.red_flags?.length) {
      lines.push('⚠️ Red Flags:', ...result.overview.red_flags.map(f => `• ${f}`), '');
    }
    if (result.overview?.action_items?.length) {
      lines.push('✅ Action Items:', ...result.overview.action_items.map(a => `• ${a}`), '');
    }
    if (result.type_insights?.power_analysis) {
      lines.push('⚖️ Power Analysis:', result.type_insights.power_analysis, '');
    }
    if (result.type_insights?.vs_standard) {
      lines.push('📏 vs Standard:', result.type_insights.vs_standard, '');
    }
    lines.push('═══ FULL TRANSLATION ═══', '', result.full_translation || '', '');
    lines.push('═══ STRUCTURE ═══', '', result.structure?.architecture || '', '');
    if (result.structure?.what_they_buried) {
      lines.push('', '🔍 What They Buried:', result.structure.what_they_buried);
    }
    // Annotations
    if (annotationCount > 0) {
      lines.push('', '═══ MY NOTES ═══');
      Object.entries(annotations).forEach(([secId, note]) => {
        const section = (result.sections || []).find(s => s.id === secId);
        lines.push(`📝 [${section?.title || secId}]: ${note.text}`);
      });
    }
    lines.push(BRAND);
    return lines.join('\n');
  }, [result, annotations, annotationCount]);

  useRegisterActions(buildFullText(), tool?.title || 'Plain Talk');

  // ── Scroll to results ──
  useEffect(() => {
    if (!result || !resultsRef.current) return;
    const t = setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 200);
    return () => clearTimeout(t);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [result]);

  // ── Keyboard shortcut ──
  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && !loading && inputText.trim())
        handleAnalyze();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading]);

  // ═══════════════════════════════════════
  // READING LEVEL BAR
  // ═══════════════════════════════════════

  const ReadingLevelBar = ({ level }) => {
    if (!level) return null;
    const origGrade = level.original_grade || 12;
    const transGrade = level.translated_grade || 8;
    return (
      <div className={`p-4 rounded-xl border ${c.warningBox}`}>
        <div className="flex items-center justify-between mb-2">
          <span className={`text-xs font-bold ${c.accentTxt}`}>📐 Reading Level</span>
          <span className={`text-xs font-bold ${isDark ? 'text-emerald-400' : 'text-emerald-600'}`}>
            Simplified by {origGrade - transGrade} grade levels
          </span>
        </div>
        <div className="flex items-center gap-3">
          <div className="flex-1">
            <div className="flex justify-between text-[10px] mb-1">
              <span className={c.textMuteded}>Original: {level.original}</span>
              <span className={c.textMuteded}>Grade {origGrade}</span>
            </div>
            <div className={`w-full h-2 rounded-full ${isDark ? 'bg-zinc-700' : 'bg-zinc-200'}`}>
              <div className="h-full rounded-full bg-red-400 transition-all"
                style={{ width: `${Math.min(100, (origGrade / 20) * 100)}%` }} />
            </div>
          </div>
          <span className={`text-lg font-bold ${c.accentTxt}`}>→</span>
          <div className="flex-1">
            <div className="flex justify-between text-[10px] mb-1">
              <span className={c.textMuteded}>Translated: {level.translated}</span>
              <span className={c.textMuteded}>Grade {transGrade}</span>
            </div>
            <div className={`w-full h-2 rounded-full ${isDark ? 'bg-zinc-700' : 'bg-zinc-200'}`}>
              <div className="h-full rounded-full bg-emerald-400 transition-all"
                style={{ width: `${Math.min(100, (transGrade / 20) * 100)}%` }} />
            </div>
          </div>
        </div>
      </div>
    );
  };

  // ═══════════════════════════════════════
  // RENDER
  // ═══════════════════════════════════════

  return (
    <div className={`space-y-4 ${c.text}`}>

      {/* ── Persistent header ── */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm overflow-hidden`}>
        <div className="px-5 pt-5">
          <div className="pb-3 border-b border-zinc-500">
            <h2 className={`text-xl font-bold ${c.text}`}>
              <span className="mr-2">{tool?.icon ?? '📄'}</span>{tool?.title ?? 'Plain Talk'}
            </h2>
            <p className={`text-sm ${c.textSecondary}`}>{tool?.tagline ?? 'Translate complex text into plain language'}</p>
          </div>
        </div>

        {/* Input mode: textarea below divider */}
        {!result && (
          <div className="px-5 pb-5 pt-3 space-y-3">
            <label className={`block text-sm font-bold ${c.text}`}>
              📄 Paste your text
            </label>
            <textarea
              value={inputText}
              onChange={e => setInputText(e.target.value)}
              placeholder="Paste any complex text — a contract, medical report, research paper, policy document, legal notice, technical manual…"
              rows={10}
              className={`w-full p-4 border rounded-xl text-sm leading-relaxed resize-y outline-none focus:ring-2 transition-colors ${c.input}`}
            />
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <input type="file" ref={fileInputRef} accept=".txt,.pdf,.md,.html,.rtf"
                  onChange={handleFileUpload} className="hidden" id="pt-file" />
                <label htmlFor="pt-file"
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold cursor-pointer transition-colors ${c.btnSecondary}`}>
                  📎 Upload File
                </label>
                {fileName && <span className={`text-xs ${c.textMuteded}`}>{fileName}</span>}
              </div>
              <span className={`text-xs ${c.textMuteded}`}>
                {wordCount > 0 ? `${wordCount.toLocaleString()} words` : ''}
              </span>
            </div>
          </div>
        )}

        {/* Results mode: type badge + actions below divider */}
        {result && (
          <div className="px-5 pb-5 pt-3">
            <div className="flex flex-wrap items-center gap-3">
              <span className={`px-3 py-1 rounded-full text-xs font-bold border ${c.warningBox} ${c.accentTxt}`}>
                {TEXT_TYPES.find(t => t.id === result.detected_type)?.emoji || '📄'}{' '}
                {result.detected_type_label || result.detected_type}
                {result.confidence && <span className={`ml-1 ${c.textMuteded}`}>· {result.confidence} confidence</span>}
              </span>
              <div className="flex-1" />
              <CopyBtn content={buildFullText()} label="Copy All" />
              <button onClick={handleReset}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold border transition-colors ${
                  isDark ? 'border-zinc-600 text-zinc-300 hover:border-cyan-500 hover:text-cyan-300' : 'border-zinc-300 text-zinc-600 hover:border-cyan-400 hover:text-cyan-600'
                }`}>
                <span>🔍</span> New Text
              </button>
            </div>
          </div>
        )}
      </div>

        {/* ─── INPUT PHASE ─── */}
        {!result && (
          <>

            {/* Sample texts */}
            <div className={`${c.card} border rounded-2xl shadow-lg p-5`}>
              <label className={`block text-xs font-bold ${c.textMuteded} mb-2`}>
                ⚡ Try a sample
              </label>
              <div className="flex flex-wrap gap-2">
                {SAMPLE_TEXTS.map((s, i) => (
                  <button key={i} onClick={() => setInputText(s.text)}
                    className={`px-3 py-1.5 rounded-lg text-xs font-bold border transition-all ${
                      isDark ? 'border-zinc-600 text-zinc-300 hover:border-cyan-500 hover:bg-cyan-900/20'
                        : 'border-zinc-200 text-zinc-600 hover:border-cyan-400 hover:bg-cyan-50'
                    }`}>
                    {s.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Options */}
            <div className={`${c.card} border rounded-2xl shadow-lg p-5 space-y-5`}>
              {/* Text type */}
              <div>
                <label className={`block text-sm font-bold ${c.text} mb-2`}>
                  🏷️ What type of text is this?
                </label>
                <div className="flex flex-wrap gap-1.5">
                  {TEXT_TYPES.map(t => (
                    <button key={t.id} onClick={() => setTextType(t.id)}
                      className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold border transition-all ${
                        textType === t.id
                          ? isDark ? 'border-cyan-500 bg-cyan-900/40 text-cyan-300' : 'border-cyan-400 bg-cyan-50 text-cyan-700'
                          : isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500' : 'border-zinc-200 text-zinc-500 hover:border-zinc-300'
                      }`}>
                      <span>{t.emoji}</span> {t.label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Focus question */}
              <div>
                <label className={`block text-sm font-bold ${c.text} mb-1`}>
                  🎯 What do you want to understand? <span className={`font-normal ${c.textMuteded}`}>(optional)</span>
                </label>
                <p className={`text-xs ${c.textMuteded} mb-2`}>
                  Focus the analysis on your specific question
                </p>
                <input
                  type="text"
                  value={focusQuestion}
                  onChange={e => setFocusQuestion(e.target.value)}
                  placeholder="e.g., What obligations am I taking on? What are the exit terms? What does this diagnosis mean?"
                  className={`w-full p-3 border rounded-xl text-sm outline-none focus:ring-2 transition-colors ${c.input}`}
                  onKeyDown={e => { if (e.key === 'Enter' && inputText.trim()) handleAnalyze(); }}
                />
              </div>
            </div>

            {/* Analyze button */}
            <button onClick={handleAnalyze}
              disabled={loading || !inputText.trim() || inputText.trim().length < 30}
              className={`w-full flex items-center justify-center gap-3 px-6 py-4 rounded-2xl font-bold text-lg transition-all ${
                inputText.trim().length >= 30
                  ? `${c.btnPrimary} shadow-indigo-200 dark:shadow-indigo-900/40`
                  : isDark ? 'bg-zinc-700 text-zinc-500 cursor-not-allowed' : 'bg-zinc-200 text-zinc-400 cursor-not-allowed'
              }`}>
              {loading
                ? <><span className="inline-block animate-spin">{tool?.icon ?? '⚙️'}</span> Analyzing your text…</>
                : <><span className="mr-1">{tool?.icon ?? '📄'}</span> Analyze &amp; Translate</>}
            </button>

            {/* Pre-result cross-ref */}
            <p className={`text-xs text-center ${c.textMuted}`}>
              Also try: <a href="/JargonAssassin" className={linkStyle}>🗡️ Jargon Assassin</a> · <a href="/DoctorVisitTranslator" className={linkStyle}>🏥 Doctor Visit Translator</a>
            </p>

            {/* Loading skeleton */}
            {loading && (
              <div className="space-y-3 pt-1">
                {[1, 0.7, 0.85, 0.6].map((w, i) => (
                  <div key={i} className={`h-4 rounded-full animate-pulse ${isDark ? 'bg-zinc-700' : 'bg-zinc-200'}`}
                    style={{ width: `${w * 100}%` }} />
                ))}
                <div className={`h-24 rounded-2xl animate-pulse mt-2 ${isDark ? 'bg-zinc-700' : 'bg-zinc-200'}`} />
                <div className="flex gap-2">
                  {[0.4, 0.3, 0.3].map((w, i) => (
                    <div key={i} className={`h-8 rounded-xl animate-pulse ${isDark ? 'bg-zinc-700' : 'bg-zinc-200'}`}
                      style={{ width: `${w * 100}%` }} />
                  ))}
                </div>
              </div>
            )}

            {/* Compare entry */}
            <button onClick={() => { setResult({ _compareOnly: true }); setActiveTab('compare'); }}
              className={`w-full flex items-center justify-center gap-2 px-4 py-3 rounded-2xl text-sm font-bold border-2 border-dashed transition-all ${
                isDark ? 'border-zinc-600 text-zinc-400 hover:border-cyan-500 hover:text-cyan-300' : 'border-zinc-300 text-zinc-500 hover:border-cyan-400 hover:text-cyan-600'
              }`}>
              🔀 Or: Compare Two Documents
            </button>

            {error && (
              <div className={`p-4 rounded-xl flex items-start gap-3 border ${c.danger}`}>
                <span>⚠️</span>
                <p className="text-sm">{error}</p>
              </div>
            )}
          </>
        )}

        {/* ─── RESULTS PHASE ─── */}
        {result && (
          <div ref={resultsRef} className="space-y-4">

            {/* Reading Level Bar */}
            <ReadingLevelBar level={result.reading_level} />

            {/* Tab bar */}
            <div className="flex gap-1 overflow-x-auto pb-1">
              {TABS.filter(tab => !result._compareOnly || tab.id === 'compare').map(tab => (
                <button key={tab.id} onClick={() => setActiveTab(tab.id)}
                  className={`flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold border-b-2 whitespace-nowrap transition-all ${
                    activeTab === tab.id ? c.tabActive : c.tabInactive
                  }`}>
                  <span>{tab.emoji}</span> {tab.label}
                </button>
              ))}
            </div>

            {/* Selection hint */}
            {(activeTab === 'xray' || activeTab === 'sidebyside') && (
              <p className={`text-[10px] ${c.textMuteded} text-center`}>
                💡 Select any text to ask a follow-up question about it
              </p>
            )}

            {/* ═══ TAB: OVERVIEW ═══ */}
            {activeTab === 'overview' && (
              <div className="space-y-4">
                {/* One-sentence summary */}
                <div className={`${c.card} border rounded-2xl shadow-lg p-5`}>
                  <h3 className={`text-lg font-bold ${c.text} mb-2`}>
                    {result.overview?.one_sentence}
                  </h3>
                  {result.overview?.what_matters_to_you && (
                    <div className={`mt-3 p-3 rounded-xl border ${c.warningBox}`}>
                      <p className={`text-xs font-bold ${c.accentTxt} mb-1`}>🎯 What matters to you</p>
                      <p className={`text-sm leading-relaxed ${c.text}`}>{result.overview.what_matters_to_you}</p>
                    </div>
                  )}
                </div>

                {/* Key takeaways */}
                {result.overview?.key_takeaways?.length > 0 && (
                  <div className={`${c.card} border rounded-2xl shadow-lg p-5`}>
                    <h4 className={`text-sm font-bold ${c.text} mb-3`}>📌 Key Takeaways</h4>
                    <div className="space-y-2">
                      {result.overview.key_takeaways.map((t, i) => (
                        <div key={i} className={`flex items-start gap-3 p-3 rounded-xl ${isDark ? 'bg-zinc-700/30' : 'bg-zinc-50'}`}>
                          <span className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0 ${
                            isDark ? 'bg-cyan-900/40 text-cyan-300' : 'bg-cyan-100 text-cyan-700'
                          }`}>{i + 1}</span>
                          <p className={`text-sm leading-relaxed ${c.text}`}>{t}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Red flags + Action items + Deadlines */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {result.overview?.red_flags?.length > 0 && (
                    <div className={`p-4 rounded-2xl border ${c.danger}`}>
                      <h4 className="text-sm font-bold mb-2">🚩 Red Flags</h4>
                      <ul className="space-y-1.5">
                        {result.overview.red_flags.map((f, i) => (
                          <li key={i} className="text-sm leading-relaxed flex items-start gap-2">
                            <span className="mt-1 flex-shrink-0">•</span>{f}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {result.overview?.action_items?.length > 0 && (
                    <div className={`p-4 rounded-2xl border ${c.success}`}>
                      <h4 className="text-sm font-bold mb-2">✅ Action Items</h4>
                      <ul className="space-y-1.5">
                        {result.overview.action_items.map((a, i) => (
                          <li key={i} className="text-sm leading-relaxed flex items-start gap-2">
                            <span className="mt-1 flex-shrink-0">•</span>{a}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {result.overview?.deadlines?.length > 0 && (
                    <div className={`p-4 rounded-2xl border ${c.highlight}`}>
                      <h4 className="text-sm font-bold mb-2">⏰ Deadlines & Time Windows</h4>
                      <ul className="space-y-1.5">
                        {result.overview.deadlines.map((d, i) => (
                          <li key={i} className="text-sm leading-relaxed flex items-start gap-2">
                            <span className="mt-1 flex-shrink-0">•</span>{d}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>

                {/* Specialist suggestion */}
                {result.specialist_suggestion?.tool && result.specialist_suggestion.tool !== 'null' && (
                  <div className={`${c.card} border rounded-2xl shadow-lg p-5`}>
                    <p className={`text-xs font-bold ${c.textMuteded} mb-2`}>💡 Specialist Tool Suggestion</p>
                    <a href={`/${result.specialist_suggestion.tool}`}
                      className={`flex items-center gap-3 p-3 rounded-xl border transition-all hover:shadow-md ${
                        isDark ? 'border-zinc-600 hover:border-cyan-500' : 'border-zinc-200 hover:border-cyan-300'
                      }`}>
                      <span className="text-2xl">
                        {SPECIALIST_TOOLS[result.specialist_suggestion.tool]?.emoji || '🔧'}
                      </span>
                      <div className="flex-1">
                        <p className={`text-sm font-bold ${c.text}`}>
                          {SPECIALIST_TOOLS[result.specialist_suggestion.tool]?.label || result.specialist_suggestion.tool}
                        </p>
                        <p className={`text-xs ${c.textMuteded}`}>{result.specialist_suggestion.reason}</p>
                      </div>
                      <span className={c.textMuteded}>→</span>
                    </a>
                  </div>
                )}

                {/* Type-specific insights */}
                {result.type_insights && (
                  <div className={`${c.card} border rounded-2xl shadow-lg p-5 space-y-4`}>
                    <h4 className={`text-sm font-bold ${c.text}`}>
                      ⚖️ Deep Analysis — {result.detected_type_label || result.detected_type}
                    </h4>

                    {result.type_insights.power_analysis && (
                      <div className={`p-3 rounded-xl border ${c.highlight}`}>
                        <p className="text-xs font-bold mb-1">⚖️ Power / Obligation Analysis</p>
                        <p className="text-sm leading-relaxed">{result.type_insights.power_analysis}</p>
                      </div>
                    )}

                    {result.type_insights.vs_standard && (
                      <div className={`p-3 rounded-xl border ${c.warningBox}`}>
                        <p className={`text-xs font-bold ${c.accentTxt} mb-1`}>📏 Compared to Standard</p>
                        <p className={`text-sm leading-relaxed ${c.text}`}>{result.type_insights.vs_standard}</p>
                      </div>
                    )}

                    {result.type_insights.negotiable_items?.length > 0 && (
                      <div>
                        <p className={`text-xs font-bold ${c.textMuteded} mb-2`}>🤝 Commonly Negotiated</p>
                        <div className="flex flex-wrap gap-1.5">
                          {result.type_insights.negotiable_items.map((item, i) => (
                            <span key={i} className={`text-xs px-2.5 py-1 rounded-lg border ${
                              isDark ? 'border-cyan-700/50 bg-cyan-900/20 text-cyan-300' : 'border-cyan-200 bg-cyan-50 text-cyan-700'
                            }`}>
                              {item}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}

                    {result.type_insights.urgency && result.type_insights.urgency !== 'none' && (
                      <div className={`flex items-center gap-2 p-3 rounded-xl border ${
                        result.type_insights.urgency === 'critical' ? c.danger
                          : result.type_insights.urgency === 'high' ? c.highlight
                          : c.success
                      }`}>
                        <span className="text-lg">
                          {result.type_insights.urgency === 'critical' ? '🚨' : result.type_insights.urgency === 'high' ? '⏰' : 'ℹ️'}
                        </span>
                        <div>
                          <p className="text-xs font-bold">Urgency: {result.type_insights.urgency.toUpperCase()}</p>
                        </div>
                      </div>
                    )}
                  </div>
                )}

                {/* Reading progress */}
                {reviewProgress && reviewProgress.total > 3 && (
                  <div className={`${c.card} border rounded-2xl shadow-lg p-4`}>
                    <div className="flex items-center justify-between mb-2">
                      <p className={`text-xs font-bold ${c.textMuteded}`}>📖 Reading Progress</p>
                      <span className={`text-xs font-bold ${c.accentTxt}`}>{reviewProgress.reviewed}/{reviewProgress.total} sections reviewed</span>
                    </div>
                    <div className={`w-full h-2 rounded-full overflow-hidden ${isDark ? 'bg-zinc-700' : 'bg-zinc-200'}`}>
                      <div className="h-full rounded-full bg-cyan-500 transition-all duration-500"
                        style={{ width: `${reviewProgress.percent}%` }} />
                    </div>
                    {annotationCount > 0 && (
                      <p className={`text-[10px] ${c.textMuteded} mt-1.5`}>📝 {annotationCount} note{annotationCount !== 1 ? 's' : ''} saved</p>
                    )}
                  </div>
                )}
              </div>
            )}

            {/* ═══ TAB: FULL TRANSLATION ═══ */}
            {activeTab === 'translation' && (
              <div className="space-y-4">
                <div className={`${c.card} border rounded-2xl shadow-lg p-6`}>
                  <div className="flex items-center justify-between mb-4">
                    <h4 className={`text-sm font-bold ${c.text}`}>💬 Plain-English Translation</h4>
                    <CopyBtn content={(result.full_translation || '') + BRAND} label="Copy Translation" />
                  </div>
                  <div className={`text-sm leading-relaxed ${c.text} whitespace-pre-line`}>
                    {result.full_translation || 'No translation available'}
                  </div>
                </div>

                {/* Jargon glossary */}
                {result.jargon_glossary?.length > 0 && (
                  <div className={`${c.card} border rounded-2xl shadow-lg p-5`}>
                    <button onClick={() => setShowGlossary(!showGlossary)}
                      className={`flex items-center justify-between w-full`}>
                      <h4 className={`text-sm font-bold ${c.text}`}>
                        📚 Jargon Glossary ({result.jargon_glossary.length} terms)
                      </h4>
                      <span className={c.textMuteded}>{showGlossary ? '▲' : '▼'}</span>
                    </button>
                    {showGlossary && (
                      <div className="mt-3 space-y-2">
                        {result.jargon_glossary.map((j, i) => (
                          <div key={i} className={`p-3 rounded-xl ${isDark ? 'bg-zinc-700/30' : 'bg-zinc-50'}`}>
                            <span className={`text-sm font-bold ${c.accentTxt}`}>{j.term}</span>
                            <span className={`text-sm ${c.textSecondary}`}> — {j.definition}</span>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                )}
              </div>
            )}

            {/* ═══ TAB: X-RAY ═══ */}
            {activeTab === 'xray' && (
              <div className="space-y-4">
                {/* Structural architecture */}
                <div className={`${c.card} border rounded-2xl shadow-lg p-5`}>
                  <h4 className={`text-sm font-bold ${c.text} mb-3`}>🏗️ Document Architecture</h4>
                  <p className={`text-sm leading-relaxed ${c.textSecondary}`}>{result.structure?.architecture}</p>
                </div>

                {/* Persuasion techniques */}
                {result.structure?.persuasion_techniques?.length > 0 && (
                  <div className={`${c.card} border rounded-2xl shadow-lg p-5`}>
                    <h4 className={`text-sm font-bold ${c.text} mb-3`}>🧠 Persuasion & Rhetoric</h4>
                    <div className="space-y-2">
                      {result.structure.persuasion_techniques.map((t, i) => (
                        <div key={i} className={`flex items-start gap-2 p-2 rounded-lg ${isDark ? 'bg-zinc-700/30' : 'bg-zinc-50'}`}>
                          <span className="text-sm">🎯</span>
                          <p className={`text-sm ${c.text}`}>{t}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* What they buried */}
                {result.structure?.what_they_buried && (
                  <div className={`p-4 rounded-2xl border ${c.highlight}`}>
                    <h4 className="text-sm font-bold mb-2">🔍 What They Buried</h4>
                    <p className="text-sm leading-relaxed">{result.structure.what_they_buried}</p>
                  </div>
                )}

                {/* Internal contradictions */}
                {result.structure?.internal_contradictions?.length > 0 && (
                  <div className={`p-4 rounded-2xl border ${c.danger}`}>
                    <h4 className="text-sm font-bold mb-2">⚡ Internal Contradictions</h4>
                    <ul className="space-y-1.5">
                      {result.structure.internal_contradictions.map((ct, i) => (
                        <li key={i} className="text-sm leading-relaxed flex items-start gap-2">
                          <span className="mt-1 flex-shrink-0">•</span>{ct}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {/* Section-by-section breakdown */}
                <div className={`${c.card} border rounded-2xl shadow-lg p-5`}>
                  <div className="flex items-center justify-between mb-3">
                    <h4 className={`text-sm font-bold ${c.text}`}>📋 Section-by-Section Breakdown</h4>
                    <div className="flex items-center gap-2">
                      <button onClick={expandAll} className={`text-[10px] font-bold ${c.accentTxt}`}>Expand All</button>
                      <span className={c.textMuteded}>·</span>
                      <button onClick={collapseAll} className={`text-[10px] font-bold ${c.accentTxt}`}>Collapse All</button>
                    </div>
                  </div>

                  {/* Filter bar */}
                  <div className="flex flex-wrap items-center gap-1.5 mb-4">
                    {[
                      { id: 'all', label: `All (${sectionCounts.all})` },
                      { id: 'high', label: `⚠️ High (${sectionCounts.high})` },
                      { id: 'flagged', label: `🚩 Flagged (${sectionCounts.flagged})` },
                    ].map(f => (
                      <button key={f.id} onClick={() => setSectionFilter(f.id)}
                        className={`px-2.5 py-1 rounded-lg text-[10px] font-bold border transition-all ${
                          sectionFilter === f.id
                            ? isDark ? 'border-cyan-500 bg-cyan-900/40 text-cyan-300' : 'border-cyan-400 bg-cyan-50 text-cyan-700'
                            : isDark ? 'border-zinc-600 text-zinc-400' : 'border-zinc-200 text-zinc-500'
                        }`}>
                        {f.label}
                      </button>
                    ))}
                  </div>

                  <div className="space-y-2" onMouseUp={handleTextSelection}>
                    {filteredSections.map((section) => {
                      const imp = IMPORTANCE_COLORS[section.importance] || IMPORTANCE_COLORS.low;
                      const isOpen = expandedSections[section.id];
                      const hasNote = annotations[section.id];
                      const isReviewed = reviewedSections[section.id];
                      return (
                        <div key={section.id} className={`rounded-xl border overflow-hidden ${isDark ? imp.dark : imp.light}`}>
                          <button onClick={() => toggleSection(section.id)}
                            className="w-full flex items-center gap-3 p-3 text-left">
                            <span className={`w-2.5 h-2.5 rounded-full flex-shrink-0 ${imp.dot}`} />
                            <div className="flex-1 min-w-0">
                              <p className={`text-sm font-bold ${c.text} truncate`}>
                                {section.title}
                                {hasNote && <span className="ml-1">📝</span>}
                              </p>
                              <p className={`text-xs ${c.textMuteded} truncate`}>{section.purpose}</p>
                            </div>
                            <span className={`text-xs px-2 py-0.5 rounded-full font-bold ${
                              section.importance === 'high' ? (isDark ? 'bg-red-900/40 text-red-300' : 'bg-red-100 text-red-700')
                              : section.importance === 'medium' ? (isDark ? 'bg-amber-900/40 text-amber-300' : 'bg-amber-100 text-amber-700')
                              : (isDark ? 'bg-zinc-600 text-zinc-300' : 'bg-zinc-200 text-zinc-600')
                            }`}>
                              {section.importance}
                            </span>
                            <span className={c.textMuteded}>{isOpen ? '▲' : '▼'}</span>
                          </button>
                          {isOpen && (
                            <div className={`px-4 pb-4 border-t ${isDark ? 'border-zinc-600' : 'border-zinc-200'}`}>
                              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-3">
                                <div>
                                  <p className={`text-[10px] font-bold uppercase tracking-wider ${c.textMuteded} mb-1.5`}>Original</p>
                                  <p className={`text-xs leading-relaxed ${c.textSecondary} italic`}>{section.original}</p>
                                </div>
                                <div>
                                  <p className={`text-[10px] font-bold uppercase tracking-wider ${c.accentTxt} mb-1.5`}>Plain English</p>
                                  <p className={`text-sm leading-relaxed ${c.text}`}>{section.translation}</p>
                                </div>
                              </div>
                              {section.flags?.length > 0 && (
                                <div className="mt-3 flex flex-wrap gap-1.5">
                                  {section.flags.map((f, i) => (
                                    <span key={i} className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                                      isDark ? 'bg-amber-900/30 text-amber-300' : 'bg-amber-50 text-amber-700'
                                    }`}>
                                      🚩 {f}
                                    </span>
                                  ))}
                                </div>
                              )}
                              {/* Annotation + Review */}
                              <div className={`mt-3 pt-3 border-t flex items-start gap-2 ${isDark ? 'border-zinc-600' : 'border-zinc-200'}`}>
                                <button onClick={() => markReviewed(section.id)}
                                  className={`flex items-center gap-1 px-2 py-1 rounded-lg text-[10px] font-bold transition-all flex-shrink-0 ${
                                    isReviewed
                                      ? isDark ? 'bg-emerald-900/30 text-emerald-300' : 'bg-emerald-50 text-emerald-700'
                                      : isDark ? 'text-zinc-500 hover:text-zinc-300' : 'text-zinc-400 hover:text-zinc-600'
                                  }`}>
                                  {isReviewed ? '✅ Reviewed' : '☐ Mark reviewed'}
                                </button>
                                {editingNote === section.id ? (
                                  <div className="flex-1 flex items-center gap-1.5">
                                    <input type="text" value={noteText} onChange={e => setNoteText(e.target.value)}
                                      onKeyDown={e => { if (e.key === 'Enter') saveNote(section.id); if (e.key === 'Escape') setEditingNote(null); }}
                                      placeholder="Add a note…"
                                      className={`flex-1 px-2 py-1 text-xs border rounded-lg outline-none ${c.input}`}
                                      autoFocus />
                                    <button onClick={() => saveNote(section.id)}
                                      className={`text-xs font-bold ${c.accentTxt}`}>Save</button>
                                    <button onClick={() => setEditingNote(null)}
                                      className={`text-xs ${c.textMuteded}`}>✕</button>
                                  </div>
                                ) : hasNote ? (
                                  <div className="flex-1 flex items-center gap-1.5">
                                    <span className={`text-xs ${c.textSecondary}`}>📝 {hasNote.text}</span>
                                    <button onClick={() => startEditing(section.id)}
                                      className={`text-[10px] ${c.textMuteded}`}>Edit</button>
                                    <button onClick={() => deleteNote(section.id)}
                                      className={`text-[10px] ${c.textMuteded}`}>✕</button>
                                  </div>
                                ) : (
                                  <button onClick={() => startEditing(section.id)}
                                    className={`text-[10px] font-bold ${c.textMuteded} hover:${c.accentTxt}`}>
                                    📝 Add note
                                  </button>
                                )}
                              </div>
                            </div>
                          )}
                        </div>
                      );
                    })}
                    {filteredSections.length === 0 && (
                      <p className={`text-sm ${c.textMuteded} text-center py-4`}>No sections match the filter</p>
                    )}
                  </div>
                </div>
              </div>
            )}

            {/* ═══ TAB: SIDE-BY-SIDE ═══ */}
            {activeTab === 'sidebyside' && (
              <div className="space-y-4">
                <div className={`${c.card} border rounded-2xl shadow-lg p-5`}>
                  <div className="flex items-center justify-between mb-3">
                    <h4 className={`text-sm font-bold ${c.text}`}>↔️ Side-by-Side Comparison</h4>
                    <div className="flex items-center gap-2">
                      <button onClick={expandAll} className={`text-[10px] font-bold ${c.accentTxt}`}>Expand All</button>
                      <span className={c.textMuteded}>·</span>
                      <button onClick={collapseAll} className={`text-[10px] font-bold ${c.accentTxt}`}>Collapse All</button>
                    </div>
                  </div>

                  {/* Filter bar */}
                  <div className="flex flex-wrap items-center gap-1.5 mb-4">
                    {[
                      { id: 'all', label: `All (${sectionCounts.all})` },
                      { id: 'high', label: `⚠️ High (${sectionCounts.high})` },
                      { id: 'flagged', label: `🚩 Flagged (${sectionCounts.flagged})` },
                    ].map(f => (
                      <button key={f.id} onClick={() => setSectionFilter(f.id)}
                        className={`px-2.5 py-1 rounded-lg text-[10px] font-bold border transition-all ${
                          sectionFilter === f.id
                            ? isDark ? 'border-cyan-500 bg-cyan-900/40 text-cyan-300' : 'border-cyan-400 bg-cyan-50 text-cyan-700'
                            : isDark ? 'border-zinc-600 text-zinc-400' : 'border-zinc-200 text-zinc-500'
                        }`}>
                        {f.label}
                      </button>
                    ))}
                  </div>

                  <div className="space-y-3" onMouseUp={handleTextSelection}>
                    {filteredSections.map((section) => {
                      const imp = IMPORTANCE_COLORS[section.importance] || IMPORTANCE_COLORS.low;
                      const isOpen = expandedSections[section.id];
                      return (
                        <div key={section.id} className={`rounded-xl border overflow-hidden ${isDark ? 'border-zinc-600' : 'border-zinc-200'}`}>
                          <button onClick={() => toggleSection(section.id)}
                            className={`w-full flex items-center gap-3 p-3 text-left ${isDark ? 'bg-zinc-700/30' : 'bg-zinc-50'}`}>
                            <span className={`w-2.5 h-2.5 rounded-full flex-shrink-0 ${imp.dot}`} />
                            <p className={`text-sm font-bold ${c.text} flex-1`}>
                              {section.title}
                              {annotations[section.id] && <span className="ml-1">📝</span>}
                            </p>
                            <span className={c.textMuteded}>{isOpen ? '▲' : '▼'}</span>
                          </button>
                          {isOpen && (
                            <div className="grid grid-cols-1 md:grid-cols-2">
                              <div className={`p-4 ${isDark ? 'bg-zinc-800 border-r border-zinc-700' : 'bg-white border-r border-zinc-200'}`}>
                                <p className={`text-[10px] font-bold uppercase tracking-wider ${c.textMuteded} mb-2`}>Original</p>
                                <p className={`text-xs leading-relaxed ${c.textSecondary}`}>{section.original}</p>
                              </div>
                              <div className={`p-4 ${isDark ? 'bg-zinc-700/20' : 'bg-cyan-50/50'}`}>
                                <p className={`text-[10px] font-bold uppercase tracking-wider ${c.accentTxt} mb-2`}>Plain English</p>
                                <p className={`text-sm leading-relaxed ${c.text}`}>{section.translation}</p>
                                {section.flags?.length > 0 && (
                                  <div className="mt-2 flex flex-wrap gap-1">
                                    {section.flags.map((f, i) => (
                                      <span key={i} className={`text-[10px] px-1.5 py-0.5 rounded ${
                                        isDark ? 'bg-amber-900/30 text-amber-300' : 'bg-amber-100 text-amber-700'
                                      }`}>🚩 {f}</span>
                                    ))}
                                  </div>
                                )}
                              </div>
                            </div>
                          )}
                        </div>
                      );
                    })}
                    {filteredSections.length === 0 && (
                      <p className={`text-sm ${c.textMuteded} text-center py-4`}>No sections match the filter</p>
                    )}
                  </div>
                </div>
              </div>
            )}

            {/* ═══ TAB: COMPARE ═══ */}
            {activeTab === 'compare' && (
              <div className="space-y-4">
                {!compareResult ? (
                  <>
                    <div className={`${c.card} border rounded-2xl shadow-lg p-5`}>
                      <h4 className={`text-sm font-bold ${c.text} mb-1`}>🔀 Compare Two Documents</h4>
                      <p className={`text-xs ${c.textMuteded} mb-4`}>
                        Paste both versions — the AI finds every change and explains who it benefits
                      </p>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                          <div className="flex items-center gap-2 mb-2">
                            <input type="text" value={compareLabelA} onChange={e => setCompareLabelA(e.target.value)}
                              className={`px-2 py-1 text-xs border rounded-lg font-bold ${c.input}`}
                              placeholder="Label A" />
                          </div>
                          <textarea value={compareTextA}
                            onChange={e => setCompareTextA(e.target.value)}
                            placeholder="Paste the original / earlier version here…"
                            rows={8}
                            className={`w-full p-3 border rounded-xl text-xs leading-relaxed resize-y outline-none focus:ring-2 ${c.input}`} />
                          {inputText && !compareTextA && (
                            <button onClick={() => setCompareTextA(inputText)}
                              className={`mt-1 text-[10px] font-bold ${c.accentTxt}`}>
                              ← Use analyzed text as Document A
                            </button>
                          )}
                        </div>
                        <div>
                          <div className="flex items-center gap-2 mb-2">
                            <input type="text" value={compareLabelB} onChange={e => setCompareLabelB(e.target.value)}
                              className={`px-2 py-1 text-xs border rounded-lg font-bold ${c.input}`}
                              placeholder="Label B" />
                          </div>
                          <textarea value={compareTextB}
                            onChange={e => setCompareTextB(e.target.value)}
                            placeholder="Paste the revised / newer version here…"
                            rows={8}
                            className={`w-full p-3 border rounded-xl text-xs leading-relaxed resize-y outline-none focus:ring-2 ${c.input}`} />
                        </div>
                      </div>
                    </div>
                    <button onClick={handleCompare}
                      disabled={compareLoading || !compareTextA.trim() || !compareTextB.trim()}
                      className={`w-full flex items-center justify-center gap-3 px-6 py-4 rounded-2xl font-bold text-lg transition-all ${
                        compareTextA.trim() && compareTextB.trim()
                          ? `${c.btnPrimary} shadow-indigo-200 dark:shadow-indigo-900/40`
                          : isDark ? 'bg-zinc-700 text-zinc-500 cursor-not-allowed' : 'bg-zinc-200 text-zinc-400 cursor-not-allowed'
                      }`}>
                      {compareLoading ? <><span className="inline-block animate-spin">{tool?.icon ?? '⚙️'}</span> Comparing documents…</> : '🔀 Compare'}
                    </button>
                  </>
                ) : (
                  <>
                    {/* Compare results */}
                    <div className={`${c.card} border rounded-2xl shadow-lg p-5`}>
                      <div className="flex items-center justify-between mb-3">
                        <h4 className={`text-sm font-bold ${c.text}`}>🔀 Comparison Results</h4>
                        <button onClick={() => setCompareResult(null)}
                          className={`text-xs font-bold ${c.accentTxt}`}>← New Comparison</button>
                      </div>
                      <p className={`text-sm leading-relaxed ${c.text} mb-3`}>{compareResult.summary}</p>

                      {/* Direction badge */}
                      <div className={`inline-flex items-center gap-2 px-3 py-1.5 rounded-full border text-xs font-bold ${
                        compareResult.change_direction === 'more_favorable' ? c.success
                          : compareResult.change_direction === 'less_favorable' ? c.danger
                          : c.highlight
                      }`}>
                        {compareResult.change_direction === 'more_favorable' ? '✅ More favorable for you'
                          : compareResult.change_direction === 'less_favorable' ? '⚠️ Less favorable for you'
                          : compareResult.change_direction === 'neutral' ? '↔️ Neutral changes'
                          : '🔀 Mixed changes'}
                      </div>
                      {compareResult.change_direction_for_whom && (
                        <p className={`text-xs ${c.textSecondary} mt-2`}>{compareResult.change_direction_for_whom}</p>
                      )}
                    </div>

                    {/* Changes list */}
                    <div className={`${c.card} border rounded-2xl shadow-lg p-5`}>
                      <div className="flex items-center justify-between mb-3">
                        <h4 className={`text-sm font-bold ${c.text}`}>📋 Changes ({(compareResult.changes || []).length})</h4>
                        <div className="flex gap-1.5">
                          {['all', 'critical', 'significant'].map(f => (
                            <button key={f} onClick={() => setChangeFilter(f)}
                              className={`px-2 py-0.5 rounded-lg text-[10px] font-bold border transition-all ${
                                changeFilter === f
                                  ? isDark ? 'border-cyan-500 bg-cyan-900/40 text-cyan-300' : 'border-cyan-400 bg-cyan-50 text-cyan-700'
                                  : isDark ? 'border-zinc-600 text-zinc-400' : 'border-zinc-200 text-zinc-500'
                              }`}>
                              {f === 'all' ? 'All' : f.charAt(0).toUpperCase() + f.slice(1)}
                            </button>
                          ))}
                        </div>
                      </div>
                      <div className="space-y-3">
                        {(compareResult.changes || [])
                          .filter(ch => changeFilter === 'all' || ch.severity === changeFilter)
                          .map(change => {
                            const cat = CHANGE_CATEGORY_LABELS[change.category] || CHANGE_CATEGORY_LABELS.modified;
                            const sev = SEVERITY_COLORS[change.severity] || SEVERITY_COLORS.minor;
                            return (
                              <div key={change.id} className={`rounded-xl border overflow-hidden ${isDark ? sev.dark : sev.light}`}>
                                <div className="p-3">
                                  <div className="flex items-center gap-2 mb-2">
                                    <span className={`text-xs font-bold ${cat.color}`}>{cat.emoji} {cat.label}</span>
                                    <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${isDark ? sev.badge.replace('dark:', '') : sev.badge}`}>
                                      {change.severity}
                                    </span>
                                    <span className={`text-xs font-bold ${c.text}`}>{change.topic}</span>
                                  </div>
                                  <p className={`text-sm leading-relaxed ${c.text} mb-2`}>{change.plain_explanation}</p>
                                  {change.text_a && (
                                    <div className={`p-2 rounded-lg mb-1.5 ${isDark ? 'bg-red-900/10' : 'bg-red-50/50'}`}>
                                      <p className={`text-[10px] font-bold ${isDark ? 'text-red-400' : 'text-red-600'} mb-0.5`}>{compareLabelA}:</p>
                                      <p className={`text-xs ${c.textSecondary}`}>{change.text_a}</p>
                                    </div>
                                  )}
                                  {change.text_b && (
                                    <div className={`p-2 rounded-lg mb-1.5 ${isDark ? 'bg-emerald-900/10' : 'bg-emerald-50/50'}`}>
                                      <p className={`text-[10px] font-bold ${isDark ? 'text-emerald-400' : 'text-emerald-600'} mb-0.5`}>{compareLabelB}:</p>
                                      <p className={`text-xs ${c.textSecondary}`}>{change.text_b}</p>
                                    </div>
                                  )}
                                  {change.who_benefits && (
                                    <p className={`text-xs ${c.textMuteded} mt-1`}>👤 {change.who_benefits}</p>
                                  )}
                                  {change.risk_note && (
                                    <p className={`text-xs mt-1 ${isDark ? 'text-amber-400' : 'text-amber-700'}`}>⚠️ {change.risk_note}</p>
                                  )}
                                </div>
                              </div>
                            );
                        })}
                      </div>
                    </div>

                    {/* Hidden changes */}
                    {compareResult.hidden_changes?.length > 0 && (
                      <div className={`p-4 rounded-2xl border ${c.danger}`}>
                        <h4 className="text-sm font-bold mb-2">🕵️ Hidden Changes (Quiet Rewordings)</h4>
                        <ul className="space-y-1.5">
                          {compareResult.hidden_changes.map((h, i) => (
                            <li key={i} className="text-sm leading-relaxed flex items-start gap-2">
                              <span className="mt-1 flex-shrink-0">•</span>{h}
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {/* Unchanged important */}
                    {compareResult.unchanged_important?.length > 0 && (
                      <div className={`p-4 rounded-2xl border ${c.success}`}>
                        <h4 className="text-sm font-bold mb-2">✅ Unchanged (Important Items That Stayed)</h4>
                        <ul className="space-y-1.5">
                          {compareResult.unchanged_important.map((u, i) => (
                            <li key={i} className="text-sm leading-relaxed flex items-start gap-2">
                              <span className="mt-1 flex-shrink-0">•</span>{u}
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {/* Recommendation */}
                    {compareResult.recommendation && (
                      <div className={`p-4 rounded-2xl border ${c.warningBox}`}>
                        <h4 className={`text-sm font-bold ${c.accentTxt} mb-1`}>💡 Recommendation</h4>
                        <p className={`text-sm leading-relaxed ${c.text}`}>{compareResult.recommendation}</p>
                      </div>
                    )}
                  </>
                )}
              </div>
            )}

            {/* ─── FOLLOW-UP QUESTIONS ─── */}
            <div className={`${c.card} border rounded-2xl shadow-lg p-5`}>
              <h4 className={`text-sm font-bold ${c.text} mb-3`}>💬 Ask a Follow-Up Question</h4>
              <div className="flex items-center gap-2">
                <input
                  type="text"
                  value={followUpQuestion}
                  onChange={e => setFollowUpQuestion(e.target.value)}
                  placeholder="What does section 4.2 mean for me? What happens if I miss the deadline?"
                  className={`flex-1 p-3 border rounded-xl text-sm outline-none focus:ring-2 transition-colors ${c.input}`}
                  onKeyDown={e => { if (e.key === 'Enter' && followUpQuestion.trim()) handleFollowUp(); }}
                  disabled={followUpLoading}
                />
                <button onClick={handleFollowUp} disabled={followUpLoading || !followUpQuestion.trim()}
                  className={`px-4 py-3 rounded-xl text-sm font-bold transition-all ${
                    followUpQuestion.trim() ? c.btnPrimary : isDark ? 'bg-zinc-700 text-zinc-500 cursor-not-allowed' : 'bg-zinc-200 text-zinc-400 cursor-not-allowed'
                  }`}>
                  {followUpLoading ? (tool?.icon ?? '⚙️') : '→'}
                </button>
              </div>

              {/* Previous follow-up answers */}
              {followUpAnswers.length > 0 && (
                <div className="mt-4 space-y-3">
                  {followUpAnswers.map((fu, i) => (
                    <div key={i} className={`rounded-xl border p-4 ${isDark ? 'bg-zinc-700/20 border-zinc-600' : 'bg-zinc-50 border-zinc-200'}`}>
                      <p className={`text-xs font-bold ${c.accentTxt} mb-2`}>❓ {fu.question}</p>
                      <p className={`text-sm leading-relaxed ${c.text} mb-3`}>{fu.answer}</p>
                      {fu.key_quote && (
                        <blockquote className={`text-xs italic pl-3 border-l-2 ${isDark ? 'border-cyan-600 text-zinc-400' : 'border-cyan-300 text-zinc-500'}`}>
                          "{fu.key_quote}"
                        </blockquote>
                      )}
                      {fu.practical_implication && (
                        <div className={`mt-2 p-2 rounded-lg ${isDark ? 'bg-emerald-900/20' : 'bg-emerald-50'}`}>
                          <p className={`text-xs ${isDark ? 'text-emerald-300' : 'text-emerald-700'}`}>
                            💡 {fu.practical_implication}
                          </p>
                        </div>
                      )}
                      {fu.follow_up_suggestions?.length > 0 && (
                        <div className="mt-2 flex flex-wrap gap-1.5">
                          {fu.follow_up_suggestions.map((s, j) => (
                            <button key={j} onClick={() => setFollowUpQuestion(s)}
                              className={`text-[10px] font-bold px-2.5 py-1 rounded-lg border transition-all ${
                                isDark ? 'border-zinc-600 text-zinc-400 hover:border-cyan-500 hover:text-cyan-300' : 'border-zinc-200 text-zinc-500 hover:border-cyan-300 hover:text-cyan-600'
                              }`}>
                              {s}
                            </button>
                          ))}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* ─── CROSS-REFERENCES ─── */}
            <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
              <p className={`text-xs font-bold ${c.textMuted} uppercase tracking-wide mb-3`}>🔗 Related tools</p>
              <div className="flex flex-wrap gap-3">
                <a href="/JargonAssassin" className={`text-xs ${linkStyle}`}>🗡️ Jargon Assassin</a>
                <a href="/ComplaintEscalationWriter" className={`text-xs ${linkStyle}`}>📨 Complaint Escalation Writer</a>
                <a href="/DoctorVisitTranslator" className={`text-xs ${linkStyle}`}>🏥 Doctor Visit Translator</a>
              </div>
            </div>

            {error && (
              <div className={`p-4 rounded-xl flex items-start gap-3 border ${c.danger}`}>
                <span>⚠️</span>
                <p className="text-sm">{error}</p>
              </div>
            )}
          </div>
        )}
      {/* eslint-disable-next-line no-restricted-globals */}
      {history.length > 0 && (<div className={`${c.cardAlt} border ${c.border} rounded-xl p-4 mt-4`}><p className={`text-xs font-bold ${c.textMuted} mb-2`}>📋 Recent</p><div className="space-y-1">{history.map(s => (<div key={s.id} className="flex items-center justify-between"><span className={`text-xs ${c.textSecondary} truncate`}>{s.preview||'Session'}</span><span className={`text-xs ${c.textMuted} ml-2`}>{new Date(s.date).toLocaleDateString()}</span></div>))}</div></div>)}
    </div>
  );
};

PlainTalk.displayName = 'PlainTalk';
export default PlainTalk;
