import React, { useState, useRef, useCallback, useEffect } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';
import { pickExample } from '../utils/exampleRotation';
import { revealSection } from '../utils/revealSection';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

// V2 REWRITE, 2026-09-06 (renamed from Plot Hole). The old tool forced
// 4-7 "holes" and inflated its Swiss Cheese Rating for entertainment; the
// new one sorts a genuine contradiction from an unexplained gap, a
// debatable character decision, or a convenience BEFORE deciding whether
// the story actually broke its own logic. See audit/tool-notes/PLOTHOLE-NOTES.md.
const EXAMPLES = [
  {
    view: 'find',
    mediaType: 'movie',
    title: 'The Dark Knight Rises',
    whatToLookAt: 'How does Bruce get from a foreign prison pit back into sealed Gotham in time for the climax?',
  },
  {
    view: 'find',
    mediaType: 'show',
    title: 'Severance',
    whatToLookAt: '',
  },
];

const PlotHoleFinder = ({ tool }) => {
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();

  const MEDIA_TYPES = [
    { value: 'movie', label: t('plh_type_movie'), icon: '🎬' },
    { value: 'show',  label: t('plh_type_show'),  icon: '📺' },
    { value: 'book',  label: t('plh_type_book'),  icon: '📖' },
    { value: 'game',  label: t('plh_type_game'),  icon: '🎮' },
  ];

  // ── Theme — verbatim from CONVENTIONS.md PF-2 ──
  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20'
                          : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-400' : 'text-gray-500',
    required:      isDark ? 'text-amber-400' : 'text-amber-700',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white'
                          : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnIdle:       isDark ? '!bg-transparent !border-2 !border-cyan-500/85 !text-cyan-300 cursor-not-allowed'
                          : '!bg-transparent !border-2 !border-cyan-600/85 !text-cyan-800 cursor-not-allowed',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200'
                          : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200'
                          : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200'
                          : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200'
                          : 'bg-red-50 border-red-200 text-red-800',
    warningBox:    isDark ? 'bg-amber-900/20 border-amber-700' : 'bg-amber-50 border-amber-300',
    warningTxt:    isDark ? 'text-amber-300' : 'text-amber-800',
    pillActive:    isDark ? 'border-cyan-500 bg-cyan-900/30 text-cyan-200'
                          : 'border-cyan-600 bg-cyan-100 text-cyan-900',
    pillInactive:  isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500'
                          : 'border-gray-300 text-gray-500 hover:border-gray-400',
    quoteBg:       isDark ? 'bg-zinc-700/60' : 'bg-slate-100',
  };
  c.label = c.labelText;
  c.textMuteded = c.textMuted;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';

  // ── State ──
  const [view, setView]               = useState('find');
  const [title, setTitle]             = useState('');
  const [mediaType, setMediaType]     = useState('movie');
  const [whatToLookAt, setWhatToLookAt] = useState('');
  const [allegedHole, setAllegedHole] = useState('');
  const [whatFeelsWrong, setWhatFeelsWrong] = useState('');
  const [defendResults, setDefendResults] = useState(null);
  const [error, setError]             = useState('');
  const [viewingHistoryId, setViewingHistoryId] = useState(null);

  // ── Refs ──
  const resultsRef   = useRef(null);
  const submitRef    = useRef(null);
  const canSubmitRef = useRef(false);

  // ── Persistent state — keys deliberately kept from the pre-rename tool ──
  const [results, setResults] = usePersistentState('plothole-result', null);
  const [sessionHistory, setSessionHistory] = usePersistentState('plothole-history', []);

  // ── Label maps — enum values stay exact English (the backend pins them);
  //    only the displayed text is localized. See i18n-enum-vs-English-literals
  //    in the project's known gotchas. ──
  const overallVerdictLabel = (l) => ({
    'TIGHT': t('plh_ov_tight'),
    'MOSTLY HOLDS TOGETHER': t('plh_ov_mostly'),
    'A FEW REAL GAPS': t('plh_ov_few_gaps'),
    'PRETTY WOBBLY': t('plh_ov_wobbly'),
    'LOGIC TAKES A VACATION': t('plh_ov_vacation'),
  }[l] || l);
  const overallVerdictStyle = (l) => ({
    'TIGHT': c.success,
    'MOSTLY HOLDS TOGETHER': c.success,
    'A FEW REAL GAPS': c.warningBox,
    'PRETTY WOBBLY': c.warning,
    'LOGIC TAKES A VACATION': c.danger,
  }[l] || c.cardAlt);
  const findingTypeLabel = (ty) => ({
    'REAL CONTRADICTION': t('plh_type_real_contradiction'),
    'UNEXPLAINED GAP': t('plh_type_unexplained_gap'),
    'PLOT CONVENIENCE': t('plh_type_plot_convenience'),
    'QUESTIONABLE DECISION': t('plh_type_questionable_decision'),
    'CONTINUITY ISSUE': t('plh_type_continuity_issue'),
    'TIMELINE PROBLEM': t('plh_type_timeline_problem'),
    'RULE-BREAK': t('plh_type_rule_break'),
    'NOT ACTUALLY A HOLE': t('plh_type_not_a_hole'),
  }[ty] || ty);
  const findingTypeIcon = (ty) => ({
    'REAL CONTRADICTION': '🕳️',
    'UNEXPLAINED GAP': '❓',
    'PLOT CONVENIENCE': '🎲',
    'QUESTIONABLE DECISION': '🤔',
    'CONTINUITY ISSUE': '🧩',
    'TIMELINE PROBLEM': '⏰',
    'RULE-BREAK': '📏',
    'NOT ACTUALLY A HOLE': '✅',
  }[ty] || '🕳️');
  const verdictLabel = (v) => ({
    'YES — REAL HOLE': t('plh_verdict_yes'),
    'MAYBE — THE STORY LEAVES A GAP': t('plh_verdict_maybe'),
    'NO — EXPLAINABLE': t('plh_verdict_no'),
    'NOT A HOLE — DIFFERENT KIND OF STORY PROBLEM': t('plh_verdict_different'),
  }[v] || v);
  const verdictStyle = (v) => ({
    'YES — REAL HOLE': c.danger,
    'MAYBE — THE STORY LEAVES A GAP': c.warningBox,
    'NO — EXPLAINABLE': c.success,
    'NOT A HOLE — DIFFERENT KIND OF STORY PROBLEM': c.cardAlt,
  }[v] || c.cardAlt);
  const severityLabel = (s) => ({ MINOR: t('plh_sev_minor'), MAJOR: t('plh_sev_major'), 'STORY-BREAKING': t('plh_sev_breaking') }[s] || s);
  const defenseBasisLabel = (b) => ({
    ESTABLISHED: t('plh_basis_established'),
    'REASONABLE INFERENCE': t('plh_basis_inference'),
    'GENRE CONVENTION': t('plh_basis_genre'),
    'THEMATIC READING': t('plh_basis_thematic'),
    'THEMATIC DEFENSE': t('plh_basis_thematic'),
    STRETCH: t('plh_basis_stretch'),
    UNKNOWN: t('plh_basis_unknown'),
  }[b] || b);
  const defenseStrengthLabel = (s) => ({ STRONG: t('plh_strength_strong'), DECENT: t('plh_strength_decent'), WEAK: t('plh_strength_weak') }[s] || s);
  const defenseVerdictLabel = (v) => ({
    ACQUITTED: t('plh_dv_acquitted'),
    'REDUCED CHARGES': t('plh_dv_reduced'),
    'TECHNICALLY GUILTY': t('plh_dv_technically'),
    'GUILTY AS CHARGED': t('plh_dv_guilty'),
  }[v] || v);
  const defenseVerdictStyle = (v) => ({
    ACQUITTED: c.success,
    'REDUCED CHARGES': c.warningBox,
    'TECHNICALLY GUILTY': c.warning,
    'GUILTY AS CHARGED': c.danger,
  }[v] || c.cardAlt);

  // ── Handlers ──
  const runAnalysis = useCallback(async () => {
    if (!title.trim()) return;
    setError(''); setResults(null); setViewingHistoryId(null);
    try {
      const data = await callToolEndpoint('plot-hole', {
        title: title.trim(), whatToLookAt: whatToLookAt.trim(), mediaType,
        userLocale, userCurrency, userRegion,
      });
      setResults(data);
      // Recent stores enough to restore the past RESULT on its own — never
      // re-run silently and present a new analysis as though it were the old
      // one. "Look again" (below) is the explicit action for a fresh take.
      setSessionHistory(prev => [{
        id: Date.now(), date: new Date().toISOString(),
        title: title.trim(), mediaType, whatToLookAt: whatToLookAt.trim(),
        verdictLabel: data?.overall_verdict?.label || '',
        strongestFinding: data?.strongest_case?.show ? data.strongest_case.finding : (data?.findings?.[0]?.name || ''),
        result: data,
      }, ...prev].slice(0, 6));
    } catch (err) { setError(err.message || t('plh_error_analysis')); }
  }, [title, whatToLookAt, mediaType, callToolEndpoint, setResults, setSessionHistory, userLocale, userCurrency, userRegion, t]);

  const runDefend = useCallback(async () => {
    if (!allegedHole.trim()) return;
    setError(''); setDefendResults(null);
    try {
      const data = await callToolEndpoint('plot-hole/defend', {
        title: title.trim(), allegedHole: allegedHole.trim(), whatFeelsWrong: whatFeelsWrong.trim(),
        userLocale, userCurrency, userRegion,
      });
      setDefendResults(data);
    } catch (err) { setError(err.message || t('plh_error_defense')); }
  }, [title, allegedHole, whatFeelsWrong, callToolEndpoint, userLocale, userCurrency, userRegion, t]);

  const handleReset = () => {
    setResults(null); setDefendResults(null); setViewingHistoryId(null);
    setTitle(''); setWhatToLookAt(''); setAllegedHole(''); setWhatFeelsWrong('');
    setError('');
  };

  const loadExample = useCallback(() => {
    const ex = pickExample('PlotHole', EXAMPLES);
    setView(ex.view);
    setMediaType(ex.mediaType);
    setTitle(ex.title);
    setWhatToLookAt(ex.whatToLookAt);
    setResults(null); setViewingHistoryId(null);
  }, [setView, setMediaType, setTitle, setWhatToLookAt, setResults]);

  // Explicit handoff from a Find Holes finding into Defend mode — carries
  // the title (per spec: "Required unless already carried from Find Holes")
  // and seeds the alleged hole from the finding itself, nothing invented.
  const handleDefendFinding = (finding) => {
    setAllegedHole(finding.what_happens || finding.name || '');
    setWhatFeelsWrong('');
    setDefendResults(null);
    setView('defend');
  };

  // "View analysis" restores the stored RESULT exactly as it was — no model
  // call. "Look again" runs a genuinely fresh analysis; a fresh run may
  // disagree with the stored one, and the stored findings are never fed
  // back in as though they were established story facts.
  const handleViewHistoryAnalysis = (entry) => {
    setResults(entry.result); setTitle(entry.title); setMediaType(entry.mediaType);
    setWhatToLookAt(entry.whatToLookAt || ''); setView('find'); setViewingHistoryId(entry.id);
  };
  const handleLookAgain = (entry) => {
    setResults(null); setTitle(entry.title); setMediaType(entry.mediaType);
    setWhatToLookAt(entry.whatToLookAt || ''); setView('find'); setViewingHistoryId(null);
    setTimeout(() => submitRef.current?.(), 0);
  };

  const buildFullText = useCallback(() => {
    if (view === 'find') {
      if (!results) return '';
      const lines = [`🕳️ ${t('plh_copy_header')} ${results?.title_analyzed || title}`, ''];
      if (results?.overall_verdict) lines.push(`${overallVerdictLabel(results.overall_verdict.label)} — ${results.overall_verdict.summary}`, '');
      if (typeof results?.swiss_cheese_rating === 'number') lines.push(`🧀 ${t('plh_copy_swiss')} ${results.swiss_cheese_rating}/10`, '');
      if (results?.focus_answer?.show) {
        lines.push(`🎯 ${results.focus_answer.question}`, verdictLabel(results.focus_answer.verdict), results.focus_answer.explanation, '');
      }
      (results?.findings || []).forEach((f) => {
        lines.push(`• [${findingTypeLabel(f.type)}] ${f.name}`);
        if (f.what_happens) lines.push(`  ${f.what_happens}`);
        lines.push(`  ${verdictLabel(f.verdict)} — ${f.why}`, '');
      });
      if (results?.strongest_case?.show) lines.push(`🕳️ ${t('plh_copy_strongest')} ${results.strongest_case.finding}`, '');
      return lines.join('\n') + BRAND;
    }
    if (!defendResults) return '';
    return `⚖️ ${t('plh_copy_defense_header')} ${defendResults.hole_summary}\n\n${defenseVerdictLabel(defendResults.defense_verdict)} — ${defendResults.verdict_reason}\n\n${defendResults.best_defense || ''}\n\n${defendResults.closing_statement || ''}` + BRAND;
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [results, defendResults, view, title, t]);

  submitRef.current    = view === 'find' ? runAnalysis : runDefend;
  canSubmitRef.current = view === 'find' ? !!title.trim() : !!allegedHole.trim();

  useRegisterActions(buildFullText(), tool?.title || t('plh_title'));

  useEffect(() => {
    if (!results && !defendResults) return;
    const timer = setTimeout(() => revealSection(resultsRef.current), 100);
    return () => clearTimeout(timer);
  }, [results, defendResults]);

  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && !loading && canSubmitRef.current)
        submitRef.current?.();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading]);

  return (
    <div className={`space-y-4 ${c.text}`}>

      {/* ── Persistent header + tab nav ── */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm overflow-hidden`}>
        <div className="px-5 pt-2.5">
          <div className="pb-3 border-b border-zinc-500">
            <div className="flex items-start justify-between gap-3">
              <div>
                <p className={`text-base ${c.textSecondary}`}>
                  <span className="me-2 text-lg">{tool?.icon ?? '🕳️'}</span>{tool?.tagline ?? t('plh_tagline')}
                </p>
                <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className={`mt-2 px-4 py-2 rounded-full text-sm font-semibold border ${isDark ? 'border-white/25 text-zinc-50' : 'border-black/25 text-zinc-900'} shadow-sm hover:brightness-105 hover:shadow transition disabled:opacity-40 whitespace-nowrap`}>✨ {t('try_example')}</button>
              </div>
              {(results || defendResults || title.trim() || allegedHole.trim()) && (
                <button onClick={handleReset} className={`${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs font-bold flex-shrink-0`}>
                  ↺ {t('start_over')}
                </button>
              )}
            </div>
          </div>
        </div>
        <div className="px-5 py-3 flex gap-2">
          {[
            { key: 'find',   label: `🕳️ ${t('plh_tab_find')}` },
            { key: 'defend', label: `⚖️ ${t('plh_tab_defend')}` },
          ].map(tabItem => (
            <button key={tabItem.key} onClick={() => { setView(tabItem.key); setError(''); }}
              className={`px-4 py-2 rounded-lg text-xs font-bold border transition-colors min-h-[36px] ${
                view === tabItem.key ? c.pillActive : c.pillInactive}`}>
              {tabItem.label}
            </button>
          ))}
        </div>
      </div>

      {/* ── Find Holes ── */}
      {view === 'find' && (
        <>
          <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-4`}>
            <div>
              <label className={`text-xs font-bold ${c.label} uppercase block mb-2`}>{t('plh_type')}</label>
              <div className="flex flex-wrap gap-2">
                {MEDIA_TYPES.map(m => (
                  <button key={m.value} onClick={() => setMediaType(m.value)}
                    className={`px-3 py-1.5 rounded-lg text-xs font-bold border min-h-[32px] ${
                      mediaType === m.value ? c.pillActive : c.pillInactive}`}>
                    <span className="me-1">{m.icon}</span>{m.label}
                  </button>
                ))}
              </div>
            </div>

            <div>
              <label className={`text-xs font-bold ${c.label} block mb-1.5`}>{t('plh_title_label')} <span className={c.required}>*</span></label>
              <input type="text" value={title} onChange={e => setTitle(e.target.value)}
                placeholder={t('plh_title_ph')}
                className={`w-full px-3 py-2.5 border rounded-lg text-sm ${c.input} outline-none focus:ring-2`}
                onKeyDown={e => e.key === 'Enter' && title.trim() && runAnalysis()} />
            </div>

            <div>
              <label className={`text-xs font-bold ${c.label} block mb-1.5`}>
                {t('plh_lookat_label')} <span className={`font-normal ${c.textMuted}`}>({t('plh_optional')})</span>
              </label>
              <textarea value={whatToLookAt} onChange={e => setWhatToLookAt(e.target.value)}
                placeholder={t('plh_lookat_ph')}
                rows={2} className={`w-full px-3 py-2 border rounded-lg text-sm ${c.input} outline-none focus:ring-2 resize-y`} />
            </div>

            <button title={t('cmd_enter')} onClick={runAnalysis} disabled={!title.trim() || loading}
              className={`relative w-full ${(!title.trim()) ? c.btnIdle : c.btnPrimary} font-bold py-3 rounded-lg flex items-center justify-center gap-2 min-h-[48px]`}>
              {loading
                ? <><span className="inline-block animate-spin">{tool?.icon ?? '🕳️'}</span> {t('plh_analyzing')}</>
                : <><span>{tool?.icon ?? '🕳️'}</span> {t('plh_find_holes')}</>}
              {!loading && (
                <kbd aria-hidden="true"
                  className="hidden sm:flex items-center absolute end-3 top-1/2 -translate-y-1/2 px-1.5 py-0.5 rounded border border-white/30 bg-white/15 text-[10px] font-bold tracking-wide">
                  ⌘↵
                </kbd>
              )}
            </button>

            <p className={`text-[11px] text-center ${c.textMuted}`}>⚠️ {t('plh_spoiler_notice')}</p>

            <p className={`text-xs text-center ${c.textMuted}`}>
              {t('plh_xref_find')} <a href="/PlotTwist" className={linkStyle}>🔀 {t('plh_plottwist')}</a> {t('plh_xref_find_tail')}
            </p>
          </div>

          {/* Results */}
          {results && (
            <div className="scroll-mt-24 space-y-4" ref={resultsRef}>
              {viewingHistoryId && (
                <div className={`${c.cardAlt} border ${c.border} rounded-lg p-2 text-center`}>
                  <p className={`text-[11px] ${c.textMuted}`}>{t('plh_viewing_saved')}</p>
                </div>
              )}

              <div className={`${overallVerdictStyle(results?.overall_verdict?.label)} border-2 rounded-xl p-5 text-center`}>
                <span className="text-3xl block mb-2">🕳️</span>
                <p className={`text-lg font-black ${c.text} mb-1`}>{results?.title_analyzed}</p>
                <p className={`text-sm font-bold ${c.text} mb-1`}>{overallVerdictLabel(results?.overall_verdict?.label)}</p>
                <p className={`text-sm ${c.textSecondary} mb-3`}>{results?.overall_verdict?.summary}</p>
                {typeof results?.swiss_cheese_rating === 'number' && (
                  <div className="inline-block">
                    <span className="text-2xl">🧀</span>{' '}
                    <span className={`text-3xl font-black ${c.accentTxt}`}>{results.swiss_cheese_rating}</span>
                    <span className={`text-sm ${c.textMuted}`}>/10 {t('plh_swiss_rating')}</span>
                    {results?.swiss_cheese_note && <p className={`text-xs ${c.textMuted} mt-1`}>{results.swiss_cheese_note}</p>}
                  </div>
                )}
              </div>

              {results?.focus_answer?.show && (
                <div className={`${c.card} border ${c.border} rounded-xl p-5`}>
                  <h3 className={`text-xs font-bold ${c.label} uppercase mb-2`}>🎯 {t('plh_your_question')}</h3>
                  <p className={`text-sm italic ${c.text} mb-2`}>“{results.focus_answer.question}”</p>
                  <span className={`text-[10px] font-black px-2 py-0.5 rounded border inline-block mb-2 ${verdictStyle(results.focus_answer.verdict)}`}>{verdictLabel(results.focus_answer.verdict)}</span>
                  <p className={`text-sm ${c.textSecondary}`}>{results.focus_answer.explanation}</p>
                </div>
              )}

              {results?.findings?.length > 0 && (
                <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
                  <h3 className={`text-sm font-bold ${c.text} mb-3`}>🕳️ {t('plh_findings_heading')} ({results.findings.length})</h3>
                  <div className="space-y-3">
                    {results.findings.map((f, i) => (
                      <div key={i} className={`${c.quoteBg} rounded-lg p-4`}>
                        <div className="flex items-start justify-between gap-2 mb-2">
                          <p className={`text-sm font-bold ${c.text}`}>{findingTypeIcon(f.type)} {f.name}</p>
                          <span className={`text-[9px] font-black px-2 py-0.5 rounded border whitespace-nowrap ${c.pillInactive}`}>{findingTypeLabel(f.type)}</span>
                        </div>
                        {f.severity && <p className={`text-[10px] font-bold ${c.textMuted} mb-1`}>{severityLabel(f.severity)}</p>}
                        {f.what_happens && <p className={`text-xs ${c.textSecondary} mb-2`}>{f.what_happens}</p>}
                        {f.case_against && <p className={`text-[11px] ${c.textMuted} mb-1`}>💥 {f.case_against}</p>}
                        {f.best_defense && <p className={`text-[11px] ${c.textMuted} mb-1`}>🛡️ {f.best_defense} <span className="italic">({defenseBasisLabel(f.defense_basis)})</span></p>}
                        <div className="flex items-center gap-2 mt-2">
                          <span className={`text-[9px] font-black px-2 py-0.5 rounded border whitespace-nowrap ${verdictStyle(f.verdict)}`}>{verdictLabel(f.verdict)}</span>
                          <p className={`text-[11px] ${c.textMuted}`}>{f.why}</p>
                        </div>
                        {f.snarky_version && (
                          <p className={`text-[11px] ${c.textMuted} italic mt-2`}>💬 {t('plh_snarky_prefix')} “{f.snarky_version}”</p>
                        )}
                        <button onClick={() => handleDefendFinding(f)}
                          className={`text-[10px] font-bold ${c.accentTxt} mt-2 min-h-[24px]`}>
                          ⚖️ {t('plh_defend_this')}
                        </button>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {results?.strongest_case?.show && (
                <div className={`${c.danger} border rounded-xl p-4`}>
                  <p className="text-[10px] font-bold uppercase mb-1">🕳️ {t('plh_strongest_case')}</p>
                  <p className="text-sm font-bold">{results.strongest_case.finding}</p>
                  <p className="text-xs mt-1">{results.strongest_case.why}</p>
                </div>
              )}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {results?.what_the_story_gets_right?.show && (
                  <div className={`${c.success} border rounded-xl p-4`}>
                    <p className="text-[10px] font-bold uppercase mb-1">✨ {t('plh_gets_right')}</p>
                    <p className="text-xs">{results.what_the_story_gets_right.text}</p>
                  </div>
                )}
                {results?.why_it_still_works?.show && (
                  <div className={`${c.warning} border rounded-xl p-4`}>
                    <p className="text-[10px] font-bold uppercase mb-1">❤️ {t('plh_still_works')}</p>
                    <p className="text-xs">{results.why_it_still_works.text}</p>
                  </div>
                )}
              </div>

              {/* Post-result cross-refs */}
              <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
                <p className={`text-xs font-bold ${c.textMuted} uppercase tracking-wide mb-3`}>🔗 {t('plh_related')}</p>
                <div className="flex flex-wrap gap-3">
                  <a href="/FanTheory" className={`text-xs ${linkStyle}`}>🔭 {t('plh_fantheory')}</a>
                </div>
              </div>
            </div>
          )}
        </>
      )}

      {/* ── Defend ── */}
      {view === 'defend' && (
        <>
          <div className={`${c.card} border ${c.border} rounded-xl p-5 space-y-4`}>
            <p className={`text-sm font-bold ${c.textSecondary}`}>{t('plh_defend_intro')}</p>

            <div>
              <label className={`text-xs font-bold ${c.label} block mb-1.5`}>
                {t('plh_story_title')} <span className={`font-normal ${c.textMuted}`}>({t('plh_optional')})</span>
              </label>
              <input type="text" value={title} onChange={e => setTitle(e.target.value)}
                placeholder={t('plh_story_title_ph')}
                className={`w-full px-3 py-2.5 border rounded-lg text-sm ${c.input} outline-none focus:ring-2`} />
            </div>

            <div>
              <label className={`text-xs font-bold ${c.label} block mb-1.5`}>{t('plh_the_hole')} <span className={c.required}>*</span></label>
              <textarea value={allegedHole} onChange={e => setAllegedHole(e.target.value)}
                placeholder={t('plh_the_hole_ph')}
                rows={3} className={`w-full px-3 py-2.5 border rounded-lg text-sm ${c.input} outline-none focus:ring-2 resize-y`} />
            </div>

            <div>
              <label className={`text-xs font-bold ${c.label} block mb-1.5`}>
                {t('plh_feels_wrong')} <span className={`font-normal ${c.textMuted}`}>({t('plh_optional')})</span>
              </label>
              <textarea value={whatFeelsWrong} onChange={e => setWhatFeelsWrong(e.target.value)}
                placeholder={t('plh_feels_wrong_ph')}
                rows={2} className={`w-full px-3 py-2.5 border rounded-lg text-sm ${c.input} outline-none focus:ring-2 resize-y`} />
            </div>

            <button title={t('cmd_enter')} onClick={runDefend} disabled={!allegedHole.trim() || loading}
              className={`relative w-full ${(!allegedHole.trim()) ? c.btnIdle : c.btnPrimary} font-bold py-3 rounded-lg flex items-center justify-center gap-2 min-h-[48px]`}>
              {loading
                ? <><span className="inline-block animate-spin">{tool?.icon ?? '🕳️'}</span> {t('plh_building')}</>
                : <><span>{tool?.icon ?? '🕳️'}</span> {t('plh_defend_it')}</>}
              {!loading && (
                <kbd aria-hidden="true"
                  className="hidden sm:flex items-center absolute end-3 top-1/2 -translate-y-1/2 px-1.5 py-0.5 rounded border border-white/30 bg-white/15 text-[10px] font-bold tracking-wide">
                  ⌘↵
                </kbd>
              )}
            </button>

            <p className={`text-[11px] text-center ${c.textMuted}`}>⚠️ {t('plh_spoiler_notice')}</p>
          </div>

          {defendResults && (
            <div className="scroll-mt-24 space-y-4" ref={resultsRef}>
              <div className={`${c.card} border ${c.border} rounded-xl p-5`}>
                <h3 className={`text-xs font-bold ${c.label} uppercase mb-2`}>⚖️ {t('plh_the_case')}</h3>
                <p className={`text-sm ${c.text}`}>{defendResults.hole_summary}</p>
              </div>

              <div className={`${defenseVerdictStyle(defendResults.defense_verdict)} border-2 rounded-xl p-5 text-center`}>
                <p className={`text-xs font-bold ${c.textMuted} uppercase mb-1`}>{t('plh_the_verdict')}</p>
                <p className={`text-xl font-black ${c.text} mb-2`}>{defenseVerdictLabel(defendResults.defense_verdict)}</p>
                <p className={`text-sm ${c.textSecondary}`}>{defendResults.verdict_reason}</p>
              </div>

              {defendResults.defense_arguments?.length > 0 && (
                <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
                  <h3 className={`text-sm font-bold ${c.text} mb-3`}>🛡️ {t('plh_the_defense')}</h3>
                  <div className="space-y-2">
                    {defendResults.defense_arguments.map((a, i) => (
                      <div key={i} className={`${c.quoteBg} rounded-lg p-3`}>
                        <div className="flex items-start justify-between gap-2 mb-1">
                          <p className={`text-xs font-bold ${c.text}`}>{t('plh_argument_n', { n: i + 1 })}</p>
                          <div className="flex gap-1 flex-shrink-0">
                            <span className={`text-[8px] font-black px-1.5 py-0.5 rounded border ${c.pillInactive}`}>{defenseBasisLabel(a.basis)}</span>
                            <span className={`text-[8px] font-black px-1.5 py-0.5 rounded border ${c.pillInactive}`}>{defenseStrengthLabel(a.strength)}</span>
                          </div>
                        </div>
                        <p className={`text-xs ${c.text} mb-1`}>{a.argument}</p>
                        {a.support && <p className={`text-[10px] ${c.textMuted} mb-1`}>{a.support}</p>}
                        {a.counterpoint && <p className={`text-[10px] ${c.warningTxt}`}>{t('plh_but')} {a.counterpoint}</p>}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {defendResults.best_defense && (
                <div className={`${c.success} border rounded-xl p-4`}>
                  <p className="text-[10px] font-bold uppercase mb-1">🏆 {t('plh_best_defense')}</p>
                  <p className="text-sm">{defendResults.best_defense}</p>
                </div>
              )}

              {defendResults.closing_statement && (
                <div className={`${c.warningBox} border rounded-xl p-4`}>
                  <p className={`text-[10px] font-bold ${c.accentTxt} uppercase mb-1`}>⚖️ {t('plh_closing')}</p>
                  <p className={`text-sm ${c.text} italic`}>{defendResults.closing_statement}</p>
                </div>
              )}

              {defendResults.final_call && (
                <div className={`${c.quoteBg} border ${c.border} rounded-xl p-4`}>
                  <p className={`text-[10px] font-bold ${c.textMuted} uppercase mb-1`}>🔎 {t('plh_hat_off')}</p>
                  <p className={`text-xs ${c.textSecondary}`}>{defendResults.final_call}</p>
                </div>
              )}

              {/* Post-result cross-refs */}
              <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
                <p className={`text-xs font-bold ${c.textMuted} uppercase tracking-wide mb-3`}>🔗 {t('plh_related')}</p>
                <div className="flex flex-wrap gap-3">
                  <a href="/PlotTwist" className={`text-xs ${linkStyle}`}>🔀 {t('plh_plottwist')}</a>
                </div>
              </div>
            </div>
          )}
        </>
      )}

      {/* ── Error ── */}
      {error && (
        <div className={`${c.danger} border rounded-lg p-4 flex items-start gap-3`}>
          <span>⚠️</span><p className="text-sm">{error}</p>
        </div>
      )}

      {/* ── History — richer than a title preview: restores the previous
          RESULT verbatim (View analysis) or explicitly runs a fresh take
          (Look again). Never silently reruns and presents a new answer as
          the old one, and never feeds the stored findings back as facts. ── */}
      {sessionHistory.length > 0 && (
        <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
          <p className={`text-xs font-bold ${c.textMuted} mb-2`}>📋 {t('plh_recent')}</p>
          <div className="space-y-2">
            {sessionHistory.map(s => (
              <div key={s.id} className="flex items-center justify-between gap-2">
                <div className="min-w-0 flex-1">
                  <p className={`text-xs font-bold ${c.text} truncate`}>{s.title}</p>
                  <p className={`text-[11px] ${c.textMuted} truncate`}>
                    {s.verdictLabel ? overallVerdictLabel(s.verdictLabel) : ''}{s.strongestFinding ? ` — ${s.strongestFinding}` : ''}
                  </p>
                </div>
                <span className={`text-[10px] ${c.textMuted} whitespace-nowrap`}>{new Date(s.date).toLocaleDateString()}</span>
                <button onClick={() => handleViewHistoryAnalysis(s)} className={`${c.btnSecondary} px-2 py-1 rounded text-[10px] font-bold whitespace-nowrap`}>{t('plh_view_analysis')}</button>
                <button onClick={() => handleLookAgain(s)} className={`${c.btnSecondary} px-2 py-1 rounded text-[10px] font-bold whitespace-nowrap`}>{t('plh_look_again')}</button>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

PlotHoleFinder.displayName = 'PlotHoleFinder';
export default PlotHoleFinder;
