import React, { useState, useRef, useCallback, useEffect } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { CopyBtn } from '../components/ActionButtons';
import { useRegisterActions } from '../components/ActionBarContext';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

// ════════════════════════════════════════════════════════════
// CONSTANTS
// ════════════════════════════════════════════════════════════
const CATEGORIES = [
  { value: 'name',      emoji: '👤', label: 'Name',           placeholder: 'Siobhan, Nguyễn, Xiomara...' },
  { value: 'food',      emoji: '🍝', label: 'Food / Drink',   placeholder: 'Gnocchi, Pho, Gewürztraminer...' },
  { value: 'place',     emoji: '📍', label: 'Place',          placeholder: 'Reykjavik, Worcestershire...' },
  { value: 'brand',     emoji: '👗', label: 'Brand',          placeholder: 'Hermès, Givenchy, Loewe...' },
  { value: 'music_art', emoji: '🎵', label: 'Music / Art',    placeholder: 'Chopin, Caravaggio, Dvořák...' },
  { value: 'science',   emoji: '🔬', label: 'Science',        placeholder: 'Acetaminophen, Euler...' },
  { value: 'phrase',    emoji: '💬', label: 'Phrase',          placeholder: 'Schadenfreude, coup de grâce...' },
  { value: 'other',     emoji: '❓', label: 'Other',           placeholder: 'Any word you want to get right...' },
];

const LANGUAGES = [
  'English (American)', 'English (British)', 'Spanish', 'French', 'German',
  'Italian', 'Portuguese', 'Mandarin Chinese', 'Japanese', 'Korean',
  'Arabic', 'Hindi', 'Russian', 'Dutch', 'Swedish', 'Turkish', 'Polish', 'Other',
];

const EXAMPLES = [
  { word: 'Gnocchi', category: 'food' },
  { word: 'Hermès', category: 'brand' },
  { word: 'Siobhan', category: 'name' },
  { word: 'Worcestershire', category: 'place' },
  { word: 'Chopin', category: 'music_art' },
  { word: 'Schadenfreude', category: 'phrase' },
  { word: 'Quinoa', category: 'food' },
  { word: 'Dvořák', category: 'music_art' },
];

// ════════════════════════════════════════════════════════════
// MAIN
// ════════════════════════════════════════════════════════════
const PronounceItRight = ({ tool }) => {
  const { callToolEndpoint, loading } = useClaudeAPI();
  const { isDark } = useTheme();

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20'
                          : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-500' : 'text-gray-400',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white'
                          : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200'
                          : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200'
                          : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200'
                          : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200'
                          : 'bg-red-50 border-red-200 text-red-800',
    infoBox:       isDark ? 'bg-sky-900/20 border-sky-700 text-sky-200'
                          : 'bg-sky-50 border-sky-200 text-sky-800',
    successBox:    isDark ? 'bg-emerald-900/20 border-emerald-700' : 'bg-emerald-50 border-emerald-300',
    successTxt:    isDark ? 'text-emerald-300' : 'text-emerald-800',
    warningBox:    isDark ? 'bg-amber-900/20 border-amber-700' : 'bg-amber-50 border-amber-300',
    warningTxt:    isDark ? 'text-amber-300' : 'text-amber-800',
    pillActive:    isDark ? 'border-cyan-500 bg-cyan-900/30 text-cyan-200'
                          : 'border-cyan-600 bg-cyan-100 text-cyan-900',
    pillInactive:  isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500'
                          : 'border-gray-300 text-gray-500 hover:border-gray-400',
    // Bespoke keys for this tool
    tipBg:         isDark ? 'bg-amber-900/20 border-amber-700/40' : 'bg-amber-50 border-amber-200',
    tipText:       isDark ? 'text-amber-300' : 'text-amber-700',
    phonBg:        isDark ? 'bg-sky-900/20 border-sky-700/40' : 'bg-sky-50 border-sky-200',
    inset:         isDark ? 'bg-zinc-900/60' : 'bg-slate-50',
    ipaBg:         isDark ? 'bg-zinc-700' : 'bg-slate-100',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-600 hover:text-cyan-700 underline underline-offset-2';

  const resultsRef = useRef(null);

  const [history, setHistory] = usePersistentState('pronounce-it-right-history', []);
  const [showHistory, setShowHistory] = useState(false);

  // Input
  const [word, setWord] = useState('');
  const [category, setCategory] = useState('other');
  const [context, setContext] = useState('');
  const [nativeLang, setNativeLang] = useState('English (American)');
  const [showIPA, setShowIPA] = useState(false);

  // Batch mode
  const [batchMode, setBatchMode] = useState(false);
  const [batchWords, setBatchWords] = useState('');

  // Results
  const [results, setResults] = useState(null);
  const [batchResults, setBatchResults] = useState(null);
  const [error, setError] = useState('');
  const [expandedSections, setExpandedSections] = useState({});

  // Audio
  const [audioUrl, setAudioUrl] = useState(null);
  const [audioLoading, setAudioLoading] = useState(false);

  useEffect(() => {
    if (!(results || batchResults) || !resultsRef.current) return;
    const t = setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 200);
    return () => clearTimeout(t);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [results, batchResults]);

  const toggleSection = useCallback((key) => setExpandedSections(prev => ({ ...prev, [key]: !prev[key] })), []);

  const activeCat = CATEGORIES.find(cat => cat.value === category) || CATEGORIES[7];

  const submit = useCallback(async () => {
    setError(''); setResults(null); setBatchResults(null);
    try {
      if (batchMode) {
        const words = batchWords.split(/[,\n]/).map(w => w.trim()).filter(Boolean);
        if (words.length < 2) { setError('Enter at least 2 words, separated by commas or newlines'); return; }
        const data = await callToolEndpoint('pronounce-it-right/batch', { words, category, nativeLang });
        setBatchResults(data);
        words.forEach(w => {
          const entry = { id: 'sir_' + Date.now() + Math.random(), date: new Date().toISOString(), word: w, category, emoji: activeCat.emoji };
          setHistory(prev => [entry, ...prev].slice(0, 6));
        });
      } else {
        if (!word.trim()) { setError('Enter a word to pronounce'); return; }
        const data = await callToolEndpoint('pronounce-it-right', { word: word.trim(), category, context: context.trim() || null, nativeLang });
        setResults(data);
        const entry = { id: 'sir_' + Date.now(), date: new Date().toISOString(), word: word.trim(), category, emoji: activeCat.emoji, phonetic: data?.pronunciation?.phonetic };
        setHistory(prev => [entry, ...prev].slice(0, 6));
      }
    } catch (err) { setError(err.message || 'Pronunciation guide failed.'); }
  }, [word, category, context, nativeLang, batchMode, batchWords, callToolEndpoint, setHistory, activeCat.emoji]);

  const handleReset = useCallback(() => {
    setWord(''); setContext(''); setResults(null); setBatchResults(null); setError('');
    setBatchWords(''); setExpandedSections({}); setAudioUrl(null);
  }, []);

  const loadExample = useCallback((ex) => {
    setWord(ex.word); setCategory(ex.category);
    setResults(null); setBatchResults(null); setError(''); setBatchMode(false); setAudioUrl(null);
  }, []);

  const fetchAudio = useCallback(async () => {
    if (!results?.word) return;
    setAudioLoading(true); setAudioUrl(null); setError('');
    try {
      const res = await fetch('/api/tools/pronounce-it-right/audio', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ word: results.word, languageOfOrigin: results.language_of_origin || null }),
      });
      if (!res.ok) throw new Error('Audio unavailable');
      const blob = await res.blob();
      setAudioUrl(URL.createObjectURL(blob));
    } catch {
      setError('Audio unavailable for this word — try the phonetic guide above');
    } finally { setAudioLoading(false); }
  }, [results]);

  const buildCopy = useCallback(() => {
    if (!results) return '';
    const p = results.pronunciation;
    const lines = [
      `🗣️ Pronounce It Right — ${results.word}`,
      '',
      `Pronunciation: ${p?.phonetic || ''}`,
      p?.ipa ? `IPA: ${p.ipa}` : '',
      p?.syllables?.length ? `Syllables: ${p.syllables.join(' · ')}` : '',
      p?.stress ? `Stress: ${p.stress}` : '',
      p?.sounds_like ? `Sounds like: ${p.sounds_like}` : '',
      '',
      results.context_info?.what_it_is ? `What it is: ${results.context_info.what_it_is}` : '',
      results.fun_fact ? `Fun fact: ${results.fun_fact}` : '',
      '',
      BRAND,
    ].filter(Boolean);
    return lines.join('\n');
  }, [results]);

  useRegisterActions(buildCopy(), tool?.title || 'Pronounce It Right');

  const submitRef = useRef(null);
  const canSubmitRef = useRef(false);
  submitRef.current = submit;
  canSubmitRef.current = batchMode ? !!batchWords.trim() : !!word.trim();

  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && !loading && canSubmitRef.current)
        submitRef.current?.();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading]);

  const Pill = ({ active, onClick, children }) => (
    <button onClick={onClick} className={'px-3 py-1.5 rounded-lg border text-xs font-semibold transition-all ' + (active ? c.pillActive : c.pillInactive)}>
      {active && <span className="mr-1">✓</span>}{children}
    </button>
  );

  const Section = ({ title, emoji, sKey, defaultOpen = false, children }) => {
    const open = expandedSections[sKey] ?? defaultOpen;
    return (
      <div className={c.card + ' border rounded-xl overflow-hidden'}>
        <button onClick={() => toggleSection(sKey)} className="w-full flex items-center justify-between p-4 text-left hover:opacity-80">
          <div className="flex items-center gap-2">
            <span className="text-base">{emoji}</span>
            <span className={'text-sm font-semibold ' + c.text}>{title}</span>
          </div>
          <span className={'text-xs ' + c.textMuted}>{open ? '▲' : '▼'}</span>
        </button>
        {open && <div className={'px-4 pb-4 border-t ' + c.border}>{children}</div>}
      </div>
    );
  };

  // ════════════════════════════════════════════════════════════
  // INPUT
  // ════════════════════════════════════════════════════════════
  const renderInput = () => (
    <div className="space-y-4">
      {/* Category picker */}
      <div className="flex gap-1.5 overflow-x-auto pb-1">
        {CATEGORIES.map(cat => (
          <button key={cat.value} onClick={() => setCategory(cat.value)}
            className={'flex items-center gap-1.5 px-3 py-2.5 rounded-xl border-2 transition-all flex-shrink-0 ' +
              (category === cat.value ? c.pillActive + ' border-2' : c.pillInactive)}>
            <span className="text-base">{cat.emoji}</span>
            <span className={'text-xs font-bold ' + (category === cat.value ? '' : c.textMuted)}>{cat.label}</span>
          </button>
        ))}
      </div>

      {/* Word input */}
      <div className={c.card + ' border rounded-xl p-5'}>
        <div className="flex items-center justify-between mb-2">
          <label className={'text-base font-bold ' + c.text}>
            {activeCat.emoji} {batchMode ? 'Enter multiple words' : 'What do you want to say right?'}
          </label>
          <button onClick={() => { setBatchMode(!batchMode); setResults(null); setBatchResults(null); }}
            className={'text-[10px] font-bold px-2.5 py-1 rounded-lg border ' + (batchMode ? c.pillActive : c.pillInactive)}>
            {batchMode ? '✓ Batch mode' : 'Batch mode'}
          </button>
        </div>

        {batchMode ? (
          <>
            <p className={'text-xs ' + c.textMuted + ' mb-3'}>Enter 2-10 words, one per line or separated by commas.</p>
            <textarea value={batchWords} onChange={e => setBatchWords(e.target.value)}
              placeholder={'e.g.,\nGnocchi\nBruschetta\nProsciutto'}
              className={'w-full h-28 p-4 border-2 rounded-xl ' + c.input + ' outline-none focus:ring-2 resize-none text-sm'} />
          </>
        ) : (
          <>
            <p className={'text-xs ' + c.textMuted + ' mb-3'}>We'll show you exactly how to say it, calibrated to your native language.</p>
            <input type="text" value={word} onChange={e => setWord(e.target.value)}
              placeholder={activeCat.placeholder}
              className={'w-full px-4 py-3 border-2 rounded-xl ' + c.input + ' outline-none focus:ring-2 text-sm'}
              onKeyDown={e => { if (e.key === 'Enter' && word.trim()) submit(); }} />
          </>
        )}
      </div>

      {/* Options */}
      <div className={c.card + ' border rounded-xl p-5 space-y-3'}>
        <div>
          <label className={'text-xs font-bold ' + c.textSecondary + ' uppercase tracking-wide mb-2 block'}>🗣️ Your native language</label>
          <div className="flex flex-wrap gap-1.5">
            {LANGUAGES.slice(0, 8).map(lang => (
              <Pill key={lang} active={nativeLang === lang} onClick={() => setNativeLang(lang)}>{lang}</Pill>
            ))}
            <select value={LANGUAGES.slice(0, 8).includes(nativeLang) ? '' : nativeLang}
              onChange={e => { if (e.target.value) setNativeLang(e.target.value); }}
              className={'px-2 py-1.5 rounded-lg border text-xs ' + c.input + ' outline-none'}>
              <option value="">More...</option>
              {LANGUAGES.slice(8).map(lang => <option key={lang} value={lang}>{lang}</option>)}
            </select>
          </div>
        </div>
        {!batchMode && (
          <div>
            <label className={'text-xs font-bold ' + c.textSecondary + ' uppercase tracking-wide mb-1 block'}>📝 Extra context (optional)</label>
            <input type="text" value={context} onChange={e => setContext(e.target.value)}
              placeholder="e.g., 'It's a coworker's name', 'Ordering at a French restaurant'"
              className={'w-full px-3 py-2 rounded-xl border text-sm ' + c.input + ' outline-none'} />
          </div>
        )}
      </div>

      {/* Examples */}
      {!batchMode && (
        <div className={'p-4 rounded-xl ' + c.inset}>
          <p className={'text-xs font-bold ' + c.textMuted + ' mb-2'}>💡 Try one:</p>
          <div className="flex flex-wrap gap-1.5">
            {EXAMPLES.map((ex, i) => (
              <button key={i} onClick={() => loadExample(ex)}
                className={'px-3 py-1.5 rounded-lg border text-xs font-semibold ' + c.pillInactive}>
                {CATEGORIES.find(c2 => c2.value === ex.category)?.emoji} {ex.word}
              </button>
            ))}
          </div>
        </div>
      )}

      <button onClick={submit} disabled={loading || (!batchMode && !word.trim()) || (batchMode && !batchWords.trim())}
        className={'w-full py-4 rounded-2xl text-sm font-bold flex items-center justify-center gap-2 transition-all disabled:opacity-40 ' +
          c.btnPrimary}>
        {loading ? <><span className="inline-block animate-spin">{tool?.icon ?? '🗣️'}</span> Looking it up...</>
          : <><span className="mr-1">{tool?.icon ?? '🗣️'}</span> Pronounce It Right</>}
      </button>
    </div>
  );

  // ════════════════════════════════════════════════════════════
  // SINGLE RESULT
  // ════════════════════════════════════════════════════════════
  const renderResult = () => {
    if (!results) return null;
    const p = results.pronunciation;
    const ctx = results.context_info;

    return (
      <div ref={resultsRef} className="space-y-4 mt-4">
        {/* Hero pronunciation */}
        <div className={'p-6 rounded-2xl border-2 ' + c.phonBg + ' text-center'}>
          <p className={'text-xs font-bold ' + c.textMuted + ' uppercase mb-1'}>{results.language_of_origin || 'Pronunciation'}</p>
          <p className={'text-3xl font-black tracking-wide ' + c.text + ' mb-2'}>{results.word}</p>
          <p className={'text-xl font-bold ' + c.tipText + ' mb-3'}>{p?.phonetic}</p>

          {/* Hear it */}
          <div className="flex flex-col items-center gap-2">
            {!audioUrl ? (
              <button onClick={fetchAudio} disabled={audioLoading}
                className={'text-sm font-bold px-4 py-2 rounded-xl border disabled:opacity-40 ' + c.btnSecondary}>
                {audioLoading
                  ? <><span className="inline-block animate-spin mr-1">{tool?.icon ?? '🗣️'}</span> Loading...</>
                  : '🔊 Hear it'}
              </button>
            ) : (
              <div className="flex flex-col items-center gap-1.5">
                <audio controls autoPlay src={audioUrl} className="h-8 w-48"
                  onEnded={() => { URL.revokeObjectURL(audioUrl); setAudioUrl(null); }} />
                <button onClick={() => { URL.revokeObjectURL(audioUrl); setAudioUrl(null); }}
                  className={'text-[10px] ' + c.textMuted}>✕ close</button>
              </div>
            )}
            <p className={'text-[10px] ' + c.textMuted}>AI-generated — phonetic guide above is more reliable for edge cases</p>
          </div>

          {p?.ipa && (
            <button onClick={() => setShowIPA(!showIPA)} className={'text-xs mt-3 block mx-auto ' + linkStyle}>
              {showIPA ? `IPA: ${p.ipa}` : 'Show IPA'}
            </button>
          )}
        </div>

        {/* Syllables & stress */}
        {p?.syllables?.length > 0 && (
          <div className={'p-4 rounded-xl ' + c.inset + ' flex items-center justify-center gap-1'}>
            {p.syllables.map((syl, i) => (
              <React.Fragment key={i}>
                {i > 0 && <span className={'text-lg font-light ' + c.textMuted}>·</span>}
                <span className={'text-lg font-bold px-2 py-1 rounded-lg ' +
                  (p.stress?.toLowerCase().includes(syl.toLowerCase()) || p.phonetic?.includes(syl.toUpperCase())
                    ? c.tipBg + ' ' + c.tipText : c.text)}>
                  {syl}
                </span>
              </React.Fragment>
            ))}
          </div>
        )}

        {/* Sounds like + Mouth guide */}
        {(p?.sounds_like || p?.mouth_guide) && (
          <div className={c.card + ' border rounded-xl p-4 space-y-3'}>
            {p.sounds_like && (
              <div>
                <p className={'text-xs font-bold ' + c.textMuted + ' uppercase mb-1'}>👂 Sounds like</p>
                <p className={'text-sm ' + c.text}>{p.sounds_like}</p>
              </div>
            )}
            {p.mouth_guide && (
              <div>
                <p className={'text-xs font-bold ' + c.textMuted + ' uppercase mb-1'}>👄 Mouth guide</p>
                <p className={'text-sm ' + c.text}>{p.mouth_guide}</p>
              </div>
            )}
            {p.stress && (
              <div>
                <p className={'text-xs font-bold ' + c.textMuted + ' uppercase mb-1'}>💪 Stress</p>
                <p className={'text-xs ' + c.textSecondary}>{p.stress}</p>
              </div>
            )}
          </div>
        )}

        {/* Common mistakes */}
        {results.common_mistakes?.length > 0 && (
          <Section title="Common Mistakes" emoji="❌" sKey="mistakes" defaultOpen>
            <div className="space-y-2 mt-3">
              {results.common_mistakes.map((m, i) => (
                <div key={i} className={'p-3 rounded-lg border ' + c.warning}>
                  <div className="flex items-center gap-2 mb-1">
                    <span className={'text-xs font-bold line-through ' + c.warningTxt}>{m.wrong}</span>
                    <span className={'text-xs ' + c.textMuted}>→</span>
                    <span className={'text-xs font-bold ' + c.successTxt}>{m.fix}</span>
                  </div>
                  <p className={'text-[10px] ' + c.textSecondary}>{m.why}</p>
                </div>
              ))}
            </div>
          </Section>
        )}

        {/* Context info */}
        {ctx && (
          <div className={c.card + ' border rounded-xl p-4 space-y-3'}>
            {ctx.what_it_is && (
              <div>
                <p className={'text-xs font-bold ' + c.textMuted + ' uppercase mb-1'}>{activeCat.emoji} What it is</p>
                <p className={'text-sm ' + c.text}>{ctx.what_it_is}</p>
              </div>
            )}
            {ctx.origin_story && (
              <div>
                <p className={'text-xs font-bold ' + c.textMuted + ' uppercase mb-1'}>📖 Origin</p>
                <p className={'text-xs ' + c.textSecondary}>{ctx.origin_story}</p>
              </div>
            )}
            {ctx.use_in_sentence && (
              <div className={'p-3 rounded-lg ' + c.inset}>
                <p className={'text-xs font-bold ' + c.textMuted + ' mb-1'}>💬 Use it in a sentence</p>
                <p className={'text-sm italic ' + c.text}>"{ctx.use_in_sentence}"</p>
              </div>
            )}
            {ctx.pro_tip && (
              <div className={'p-3 rounded-lg ' + c.tipBg}>
                <p className={'text-xs font-bold ' + c.tipText}>💡 Pro tip: {ctx.pro_tip}</p>
              </div>
            )}
          </div>
        )}

        {/* Don't confuse with */}
        {results.dont_confuse_with?.length > 0 && (
          <Section title="Don't Confuse With" emoji="⚠️" sKey="confuse">
            <div className="space-y-2 mt-3">
              {results.dont_confuse_with.map((item, i) => (
                <div key={i} className={'p-3 rounded-lg ' + c.inset}>
                  <p className={'text-xs font-bold ' + c.text}>{item.word}</p>
                  <p className={'text-[10px] ' + c.textSecondary}>{item.difference}</p>
                </div>
              ))}
            </div>
          </Section>
        )}

        {/* Regional variants */}
        {results.regional_variants?.length > 0 && (
          <Section title="Regional Variants" emoji="🌍" sKey="regional">
            <div className="space-y-2 mt-3">
              {results.regional_variants.map((v, i) => (
                <div key={i} className={'p-3 rounded-lg ' + c.inset}>
                  <div className="flex items-center gap-2">
                    <span className={'text-xs font-bold ' + c.text}>{v.region}</span>
                    <span className={'text-xs ' + c.tipText}>{v.pronunciation}</span>
                  </div>
                  {v.note && <p className={'text-[10px] ' + c.textMuted + ' mt-0.5'}>{v.note}</p>}
                </div>
              ))}
            </div>
          </Section>
        )}

        {/* Confidence script */}
        {results.confidence_script && (
          <div className={'p-4 rounded-xl border ' + c.successBox}>
            <p className={'text-xs font-bold ' + c.successTxt + ' mb-1'}>💬 If you're unsure in the moment</p>
            <p className={'text-sm italic ' + c.successTxt}>"{results.confidence_script}"</p>
          </div>
        )}

        {/* Fun fact */}
        {results.fun_fact && (
          <div className={'p-3 rounded-lg ' + c.infoBox}>
            <p className={'text-xs ' + c.accentTxt}>🧠 {results.fun_fact}</p>
          </div>
        )}

      </div>
    );
  };

  // ════════════════════════════════════════════════════════════
  // BATCH RESULTS
  // ════════════════════════════════════════════════════════════
  const renderBatch = () => {
    if (!batchResults?.guides?.length) return null;
    return (
      <div ref={resultsRef} className="space-y-3 mt-4">
        <p className={'text-xs font-bold ' + c.textMuted + ' uppercase'}>🗣️ {batchResults.guides.length} Pronunciations</p>
        {batchResults.guides.map((g, i) => (
          <div key={i} className={c.card + ' border rounded-xl p-4'}>
            <div className="flex items-start justify-between mb-2">
              <div>
                <p className={'text-lg font-bold ' + c.text}>{g.word}</p>
                <p className={'text-base font-bold ' + c.tipText}>{g.phonetic}</p>
              </div>
              {g.ipa && <span className={'text-[10px] font-mono px-2 py-0.5 rounded ' + c.ipaBg + ' ' + c.textMuted}>{g.ipa}</span>}
            </div>
            {g.syllables?.length > 0 && (
              <p className={'text-xs ' + c.textSecondary + ' mb-1'}>{g.syllables.join(' · ')}</p>
            )}
            {g.sounds_like && <p className={'text-xs ' + c.text + ' mb-1'}>👂 {g.sounds_like}</p>}
            {g.top_mistake && (
              <div className={'p-2 rounded-lg ' + c.warning + ' mt-2'}>
                <p className={'text-[10px] ' + c.warningTxt}>❌ {g.top_mistake}</p>
              </div>
            )}
            {g.what_it_is && <p className={'text-[10px] ' + c.textMuted + ' mt-1'}>{activeCat.emoji} {g.what_it_is}</p>}
            {g.fun_fact && <p className={'text-[10px] ' + c.textMuted + ' mt-0.5 italic'}>🧠 {g.fun_fact}</p>}
          </div>
        ))}
      </div>
    );
  };

  // ════════════════════════════════════════════════════════════
  // HISTORY
  // ════════════════════════════════════════════════════════════
  const renderHistory = () => {
    if (history.length === 0) return null;
    return (
      <div className={'mt-6 p-4 rounded-2xl border ' + c.cardAlt}>
        <button onClick={() => setShowHistory(!showHistory)} className="w-full flex items-center gap-2 text-left">
          <span>🗣️</span>
          <span className={'text-sm font-bold ' + c.text + ' flex-1'}>Words You've Looked Up</span>
          <span className={'text-xs ' + c.textMuted}>{history.length}</span>
          <span className={'text-xs ' + c.textMuted}>{showHistory ? '▲' : '▼'}</span>
        </button>
        {showHistory && (
          <div className="mt-3 flex flex-wrap gap-1.5">
            {history.map(entry => (
              <button key={entry.id}
                onClick={() => { setWord(entry.word); setCategory(entry.category); setResults(null); setBatchResults(null); setBatchMode(false); }}
                className={'px-3 py-1.5 rounded-lg border text-xs font-semibold ' + c.pillInactive}>
                {entry.emoji} {entry.word}
                {entry.phonetic && <span className={'ml-1.5 ' + c.textMuted}>({entry.phonetic})</span>}
              </button>
            ))}
          </div>
        )}
      </div>
    );
  };

  // ════════════════════════════════════════════════════════════
  // MAIN RENDER
  // ════════════════════════════════════════════════════════════
  return (
    <div className={`space-y-4 ${c.text}`}>
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5`}>
        <div className="pb-3 border-b border-zinc-500">
          <h2 className={`text-xl font-bold ${c.text}`}>
            <span className="mr-2">{tool?.icon ?? '🗣️'}</span>{tool?.title ?? 'Pronounce It Right'}
          </h2>
          <p className={`text-sm ${c.textSecondary}`}>{tool?.tagline ?? 'Names, food, places, brands — never mispronounce anything again'}</p>
        </div>
      </div>
      {!results && !batchResults && renderInput()}
      {renderResult()}
      {renderBatch()}
      {(results || batchResults) && (
        <div className="mt-4 space-y-3">
          <div className="flex gap-2">
            <button onClick={handleReset} className={'flex-1 py-3 rounded-xl text-xs font-bold flex items-center justify-center gap-1.5 ' + c.btnPrimary}>
              <span>🗣️</span> New Word
            </button>
            <button onClick={() => { setResults(null); setBatchResults(null); setError(''); setAudioUrl(null); }}
              className={'flex-1 py-3 rounded-xl text-xs font-bold flex items-center justify-center gap-1.5 ' + c.btnSecondary}>
              <span>✏️</span> Edit Input
            </button>
          </div>
          <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
            <p className={`text-[10px] font-bold ${c.textMuted} uppercase mb-2`}>🔗 Related tools</p>
            <div className="flex flex-wrap gap-3">
              <a href="/DecoderRing" className={`text-xs ${linkStyle}`}>💬 Decoder Ring</a>
              <a href="/TipOfTongue" className={`text-xs ${linkStyle}`}>💡 Tip of My Tongue</a>
            </div>
          </div>
        </div>
      )}
      {error && (
        <div className={`mt-4 p-4 border rounded-xl flex items-start gap-3 ${c.danger}`}>
          <span className="text-base">⚠️</span>
          <p className="text-sm">{error}</p>
        </div>
      )}
      {renderHistory()}
    </div>
  );
};

PronounceItRight.displayName = 'PronounceItRight';
export default PronounceItRight;
