import React, { useState, useRef, useCallback, useEffect } from 'react';
import Caret from '../components/Caret';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';
import { pickExample } from '../utils/exampleRotation';
import { revealSection } from '../utils/revealSection';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

// ════════════════════════════════════════════════════════════
// CONSTANTS
// ════════════════════════════════════════════════════════════
// `value` and `labelKey`/`placeholderKey` are stable identifiers; the visible
// text is resolved through t() at render time.
const CATEGORIES = [
  { value: 'name',      emoji: '👤', labelKey: 'pir_cat_name',      placeholderKey: 'pir_ph_name' },
  { value: 'food',      emoji: '🍝', labelKey: 'pir_cat_food',      placeholderKey: 'pir_ph_food' },
  { value: 'place',     emoji: '📍', labelKey: 'pir_cat_place',     placeholderKey: 'pir_ph_place' },
  { value: 'brand',     emoji: '👜', labelKey: 'pir_cat_brand',     placeholderKey: 'pir_ph_brand' },
  { value: 'music_art', emoji: '🎵', labelKey: 'pir_cat_music_art', placeholderKey: 'pir_ph_music_art' },
  { value: 'science',   emoji: '🔬', labelKey: 'pir_cat_science',   placeholderKey: 'pir_ph_science' },
  { value: 'phrase',    emoji: '💬', labelKey: 'pir_cat_phrase',    placeholderKey: 'pir_ph_phrase' },
  { value: 'other',     emoji: '❓', labelKey: 'pir_cat_other',     placeholderKey: 'pir_ph_other' },
];

// `value` is the backend identifier (kept English); `labelKey` is the localized label.
const LANGUAGES = [
  { value: 'English (American)', labelKey: 'pir_lang_en_us' },
  { value: 'English (British)',  labelKey: 'pir_lang_en_gb' },
  { value: 'Spanish',            labelKey: 'pir_lang_es' },
  { value: 'French',             labelKey: 'pir_lang_fr' },
  { value: 'German',             labelKey: 'pir_lang_de' },
  { value: 'Italian',            labelKey: 'pir_lang_it' },
  { value: 'Portuguese',         labelKey: 'pir_lang_pt' },
  { value: 'Mandarin Chinese',   labelKey: 'pir_lang_zh' },
  { value: 'Japanese',           labelKey: 'pir_lang_ja' },
  { value: 'Korean',             labelKey: 'pir_lang_ko' },
  { value: 'Arabic',             labelKey: 'pir_lang_ar' },
  { value: 'Hindi',              labelKey: 'pir_lang_hi' },
  { value: 'Russian',            labelKey: 'pir_lang_ru' },
  { value: 'Dutch',              labelKey: 'pir_lang_nl' },
  { value: 'Swedish',            labelKey: 'pir_lang_sv' },
  { value: 'Turkish',            labelKey: 'pir_lang_tr' },
  { value: 'Polish',             labelKey: 'pir_lang_pl' },
  { value: 'Other',              labelKey: 'pir_lang_other' },
];

const CONTEXT_EXAMPLE_KEYS = ['pir_context_ex_1', 'pir_context_ex_2', 'pir_context_ex_3', 'pir_context_ex_4'];

// Whichever prosody feature actually organizes a word's pronunciation —
// not every language uses stress. See backend prosody_label.
const PROSODY_LABEL_KEYS = {
  STRESS: 'pir_prosody_stress',
  TONE: 'pir_prosody_tone',
  RHYTHM: 'pir_prosody_rhythm',
  VOWEL_LENGTH: 'pir_prosody_vowel_length',
};

// A spelling doesn't always settle a reading — these map the backend's
// honest uncertainty into a short, calm badge instead of hiding it.
const STATUS_LABEL_KEYS = {
  MULTIPLE_ESTABLISHED_READINGS: 'pir_status_multiple',
  PERSON_SPECIFIC: 'pir_status_person_specific',
  CONTEXT_DEPENDENT: 'pir_status_context_dependent',
  UNCERTAIN: 'pir_status_uncertain',
};

const EXAMPLES = [
  { word: 'Gnocchi', category: 'food' },
  { word: 'Hermès', category: 'brand' },
  { word: 'Siobhan', category: 'name' },
  { word: 'Worcestershire', category: 'place' },
  { word: 'Chopin', category: 'music_art' },
  { word: 'Schadenfreude', category: 'phrase' },
  { word: 'Quinoa', category: 'food' },
  { word: 'Dvořák', category: 'music_art' },
];

// ════════════════════════════════════════════════════════════
// MAIN
// ════════════════════════════════════════════════════════════
const PronounceItRight = ({ tool }) => {
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20'
                          : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-400' : 'text-gray-500',
    required:      isDark ? 'text-amber-400' : 'text-amber-700',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white'
                          : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    // Waiting for input: an outline, not a smudge. Empty fill keeps "filled"
    // meaning "ready"; the border and label carry the visibility. Important
    // modifiers because tools carry their own border/text utilities on the
    // submit and Tailwind resolves conflicts by stylesheet order, not class
    // order. See the PF-13 exception in audit/audit_v2-3-2.py.
    btnIdle:       isDark ? '!bg-transparent !border-2 !border-cyan-500/85 !text-cyan-300 cursor-not-allowed'
                          : '!bg-transparent !border-2 !border-cyan-600/85 !text-cyan-800 cursor-not-allowed',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200'
                          : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200'
                          : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200'
                          : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200'
                          : 'bg-red-50 border-red-200 text-red-800',
    infoBox:       isDark ? 'bg-sky-900/20 border-sky-700 text-sky-200'
                          : 'bg-sky-50 border-sky-200 text-sky-800',
    successBox:    isDark ? 'bg-emerald-900/20 border-emerald-700' : 'bg-emerald-50 border-emerald-300',
    successTxt:    isDark ? 'text-emerald-300' : 'text-emerald-800',
    warningTxt:    isDark ? 'text-amber-300' : 'text-amber-800',
    pillActive:    isDark ? 'border-cyan-500 bg-cyan-900/30 text-cyan-200'
                          : 'border-cyan-600 bg-cyan-100 text-cyan-900',
    pillInactive:  isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500'
                          : 'border-gray-300 text-gray-500 hover:border-gray-400',
    // Bespoke keys for this tool
    tipBg:         isDark ? 'bg-amber-900/20 border-amber-700/40' : 'bg-amber-50 border-amber-200',
    tipText:       isDark ? 'text-amber-300' : 'text-amber-700',
    phonBg:        isDark ? 'bg-sky-900/20 border-sky-700/40' : 'bg-sky-50 border-sky-200',
    inset:         isDark ? 'bg-zinc-900/60' : 'bg-slate-50',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';

  const resultsRef = useRef(null);

  const [showHistory, setShowHistory] = useState(false);

  // Input
  const [word, setWord] = useState('');
  const [category, setCategory] = useState('other');
  const [context, setContext] = useState('');
  const [nativeLang, setNativeLang] = useState('English (American)');
  const [showIPA, setShowIPA] = useState(false);

  // Batch mode
  const [batchMode, setBatchMode] = useState(false);
  const [batchWords, setBatchWords] = useState('');

  // Results (transient session state — not persisted)
  const [batchResults, setBatchResults] = useState(null);
  const [error, setError] = useState('');
  const [expandedSections, setExpandedSections] = useState({});

  // Audio
  const [audioUrl, setAudioUrl] = useState(null);
  const [audioLoading, setAudioLoading] = useState(false);

  // Persistent
  const [sessionHistory, setSessionHistory] = usePersistentState('pronounce-it-right-history', []);
  const [results, setResults] = usePersistentState('pronounce-it-right-results-v2', null);

  useEffect(() => {
    if (!(results || batchResults) || !resultsRef.current) return;
    const timer = setTimeout(() => revealSection(resultsRef.current), 200);
    return () => clearTimeout(timer);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [results, batchResults]);

  const toggleSection = useCallback((key) => setExpandedSections(prev => ({ ...prev, [key]: !prev[key] })), []);

  const activeCat = CATEGORIES.find(cat => cat.value === category) || CATEGORIES[7];

  const submit = useCallback(async () => {
    setError(''); setResults(null); setBatchResults(null);
    try {
      if (batchMode) {
        const words = batchWords.split(/[,\n]/).map(w => w.trim()).filter(Boolean);
        if (words.length < 2) { setError(t('pir_err_min_words')); return; }
        const data = await callToolEndpoint('pronounce-it-right/batch', { words, category, nativeLang, userLocale, userCurrency, userRegion });
        setBatchResults(data);
        words.forEach(w => {
          const entry = { id: 'sir_' + Date.now() + Math.random(), date: new Date().toISOString(), word: w, category, emoji: activeCat.emoji, preview: `${activeCat.emoji} ${w}` };
          setSessionHistory(prev => [entry, ...prev].slice(0, 6));
        });
      } else {
        if (!word.trim()) { setError(t('pir_err_enter_word')); return; }
        const data = await callToolEndpoint('pronounce-it-right', { word: word.trim(), category, context: context.trim() || null, nativeLang, userLocale, userCurrency, userRegion });
        setResults(data);
        const entry = { id: 'sir_' + Date.now(), date: new Date().toISOString(), word: word.trim(), category, emoji: activeCat.emoji, phonetic: data?.pronunciation?.phonetic, preview: `${activeCat.emoji} ${word.trim()}` };
        setSessionHistory(prev => [entry, ...prev].slice(0, 6));
      }
    } catch (err) { setError(err.message || t('pir_err_failed')); }
  }, [word, category, context, nativeLang, batchMode, batchWords, callToolEndpoint, setSessionHistory, activeCat.emoji, userLocale, userCurrency, userRegion, t]);

  const handleReset = useCallback(() => {
    setWord(''); setContext(''); setResults(null); setBatchResults(null); setError('');
    setBatchWords(''); setExpandedSections({}); setAudioUrl(null);
  }, []);

  const loadExample = useCallback(() => {
    const ex = pickExample('PronounceItRight', EXAMPLES);
    setWord(ex.word); setCategory(ex.category);
    setResults(null); setBatchResults(null); setError(''); setBatchMode(false); setAudioUrl(null);
  }, []);

  const audioSafe = !!(results?.audio?.safe_to_offer && results?.audio?.reading_is_constrained);

  const fetchAudio = useCallback(async () => {
    if (!results?.word || !audioSafe) return;
    setAudioLoading(true); setAudioUrl(null); setError('');
    try {
      const base = process.env.REACT_APP_API_URL || 'http://localhost:3001';
      const res = await fetch(`${base}/api/pronounce-it-right-audio`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          source_text: results.word,
          target_language_or_locale: results.audio?.language_or_locale || results.language || null,
          selected_reading: results.pronunciation?.phonetic || null,
        }),
      });
      if (!res.ok) throw new Error('Audio unavailable');
      const blob = await res.blob();
      setAudioUrl(URL.createObjectURL(blob));
    } catch {
      setError(t('pir_err_audio'));
    } finally { setAudioLoading(false); }
  }, [results, audioSafe, t]);

  const buildCopy = useCallback(() => {
    if (!results) return '';
    const p = results.pronunciation;
    const prosodyLabelKey = PROSODY_LABEL_KEYS[p?.prosody_label];
    const lines = [
      `🗣️ ${t('pir_title')} — ${results.word}`,
      '',
      p?.phonetic ? `${t('pir_copy_pronunciation')} ${p.phonetic}` : '',
      p?.ipa ? `${t('pir_copy_ipa')} ${p.ipa}` : '',
      p?.syllables?.length ? `${t('pir_copy_syllables')} ${p.syllables.join(' · ')}` : '',
      (p?.prosody && prosodyLabelKey) ? `${t(prosodyLabelKey)}: ${p.prosody}` : '',
      p?.sounds_like ? `${t('pir_copy_sounds_like')} ${p.sounds_like}` : '',
      '',
      results.context_info?.what_it_is ? `${t('pir_copy_what_it_is')} ${results.context_info.what_it_is}` : '',
      results.watch_out_for?.[0]?.trap ? `${t('pir_copy_watch_out')} ${results.watch_out_for[0].trap}` : '',
      '',
      BRAND,
    ].filter(Boolean);
    return lines.join('\n');
  }, [results, t]);

  useRegisterActions(buildCopy(), tool?.title || 'Pronounce It Right');

  const submitRef = useRef(null);
  const canSubmitRef = useRef(false);
  submitRef.current = submit;
  canSubmitRef.current = batchMode ? !!batchWords.trim() : !!word.trim();

  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && !loading && canSubmitRef.current)
        submitRef.current?.();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading]);

  const Pill = ({ active, onClick, children }) => (
    <button onClick={onClick} className={'px-3 py-1.5 rounded-lg border text-xs font-semibold transition-all ' + (active ? c.pillActive : c.pillInactive)}>
      {active && <span className="me-1">✓</span>}{children}
    </button>
  );

  const Section = ({ title, emoji, sKey, defaultOpen = false, children }) => {
    const open = expandedSections[sKey] ?? defaultOpen;
    return (
      <div className={c.card + ' border rounded-xl overflow-hidden'}>
        <button onClick={() => toggleSection(sKey)} className="w-full flex items-center justify-between p-4 text-start hover:opacity-80">
          <div className="flex items-center gap-2">
            <span className="text-base">{emoji}</span>
            <span className={'text-sm font-semibold ' + c.text}>{title}</span>
          </div>
          <Caret open={open} />
        </button>
        {open && <div className={'px-4 pb-4 border-t ' + c.border}>{children}</div>}
      </div>
    );
  };

  // ════════════════════════════════════════════════════════════
  // INPUT
  // ════════════════════════════════════════════════════════════
  const renderInput = () => (
    <div className="space-y-4">
      {/* What do you want to pronounce? */}
      <div className={c.card + ' border rounded-xl p-5'}>
        <div className="flex items-center justify-between mb-2">
          <label className={'text-base font-bold ' + c.text}>
            {activeCat.emoji} {batchMode ? t('pir_enter_multiple') : t('pir_what_say_right')} <span className={c.required}>*</span>
          </label>
          <button onClick={() => { setBatchMode(!batchMode); setResults(null); setBatchResults(null); }}
            className={'text-[10px] font-bold px-2.5 py-1 rounded-lg border ' + (batchMode ? c.pillActive : c.pillInactive)}>
            {batchMode ? '✓ ' + t('pir_batch_mode') : t('pir_batch_mode')}
          </button>
        </div>

        {batchMode ? (
          <>
            <label className={`text-xs font-bold ${c.labelText} block mb-1.5`}>{t('pir_batch_words_label')} <span className={c.required}>*</span></label>
            <p className={'text-xs ' + c.textMuted + ' mb-3'}>{t('pir_batch_hint')}</p>
            <textarea value={batchWords} onChange={e => setBatchWords(e.target.value)}
              placeholder={t('pir_batch_ph')}
              className={'w-full h-28 p-4 border-2 rounded-xl ' + c.input + ' outline-none focus:ring-2 resize-none text-sm'} />
          </>
        ) : (
          <>
            <p className={'text-xs ' + c.textMuted + ' mb-3'}>{t('pir_word_hint')}</p>
            <input type="text" value={word} onChange={e => setWord(e.target.value)}
              placeholder={t(activeCat.placeholderKey)}
              className={'w-full px-4 py-3 border-2 rounded-xl ' + c.input + ' outline-none focus:ring-2 text-sm'}
              onKeyDown={e => { if (e.key === 'Enter' && word.trim()) submit(); }} />
          </>
        )}
      </div>

      {/* What kind of thing is it? (optional) */}
      <div className={c.card + ' border rounded-xl p-5'}>
        <label className={'text-xs font-bold ' + c.textSecondary + ' uppercase tracking-wide mb-2 block'}>{t('pir_category_label')}</label>
        <div className="flex gap-1.5 overflow-x-auto pb-1">
          {CATEGORIES.map(cat => (
            <button key={cat.value} onClick={() => setCategory(cat.value)}
              className={'flex items-center gap-1.5 px-3 py-2.5 rounded-xl border-2 transition-all flex-shrink-0 ' +
                (category === cat.value ? c.pillActive + ' border-2' : c.pillInactive)}>
              <span className="text-base">{cat.emoji}</span>
              <span className={'text-xs font-bold ' + (category === cat.value ? '' : c.textMuted)}>{t(cat.labelKey)}</span>
            </button>
          ))}
        </div>
      </div>

      {/* What language do you speak? (required) + extra context (optional) */}
      <div className={c.card + ' border rounded-xl p-5 space-y-4'}>
        <div>
          <label className={'text-xs font-bold ' + c.textSecondary + ' uppercase tracking-wide mb-1 block'}>
            🗣️ {t('pir_native_lang')} <span className={c.required}>*</span>
          </label>
          <p className={'text-xs ' + c.textMuted + ' mb-2'}>{t('pir_native_lang_hint')}</p>
          <div className="flex flex-wrap gap-1.5">
            {LANGUAGES.slice(0, 8).map(lang => (
              <Pill key={lang.value} active={nativeLang === lang.value} onClick={() => setNativeLang(lang.value)}>{t(lang.labelKey)}</Pill>
            ))}
            <select value={LANGUAGES.slice(0, 8).some(l => l.value === nativeLang) ? '' : nativeLang}
              onChange={e => { if (e.target.value) setNativeLang(e.target.value); }}
              className={'px-2 py-1.5 rounded-lg border text-xs ' + c.input + ' outline-none'}>
              <option value="">{t('pir_more')}</option>
              {LANGUAGES.slice(8).map(lang => <option key={lang.value} value={lang.value}>{t(lang.labelKey)}</option>)}
            </select>
          </div>
        </div>
        {!batchMode && (
          <div className={'pt-3 border-t ' + c.border}>
            <label className={'text-xs font-bold ' + c.textSecondary + ' uppercase tracking-wide mb-1 block'}>📝 {t('pir_extra_context')}</label>
            <p className={'text-xs ' + c.textMuted + ' mb-2'}>{t('pir_context_hint')}</p>
            <input type="text" value={context} onChange={e => setContext(e.target.value)}
              placeholder={t('pir_context_ph')}
              className={'w-full px-3 py-2 rounded-xl border text-sm ' + c.input + ' outline-none mb-2'} />
            <div className="space-y-0.5">
              {CONTEXT_EXAMPLE_KEYS.map(key => (
                <p key={key} className={'text-[11px] italic ' + c.textMuted}>{t(key)}</p>
              ))}
            </div>
          </div>
        )}
      </div>

      <button title={t('cmd_enter')} onClick={submit} disabled={loading || (!batchMode && !word.trim()) || (batchMode && !batchWords.trim())}
        className={'relative w-full py-4 rounded-2xl text-sm font-bold flex items-center justify-center gap-2 transition-all ' +
          (((!batchMode && !word.trim()) || (batchMode && !batchWords.trim())) ? c.btnIdle : c.btnPrimary)}>
        {loading ? <><span className="relative inline-block animate-spin">{tool?.icon ?? '🗣️'}</span> {t('pir_looking_up')}</>
          : <><span className="me-1">{tool?.icon ?? '🗣️'}</span> {t('pir_cta')}</>}
      {!loading && (
        <kbd aria-hidden="true"
          className="hidden sm:flex items-center absolute end-3 top-1/2 -translate-y-1/2 px-1.5 py-0.5 rounded border border-white/30 bg-white/15 text-[10px] font-bold tracking-wide">
          ⌘↵
        </kbd>
      )}
      </button>
    </div>
  );

  // ════════════════════════════════════════════════════════════
  // SINGLE RESULT
  // ════════════════════════════════════════════════════════════
  const renderResult = () => {
    if (!results) return null;
    const p = results.pronunciation || {};
    const ctx = results.context_info;
    const statusKey = STATUS_LABEL_KEYS[results.reading_status];
    const prosodyLabelKey = PROSODY_LABEL_KEYS[p.prosody_label];
    const hasHero = !!p.phonetic;
    const needsContext = results.needs_context?.needed;
    const hasContextInfo = ctx && (ctx.what_it_is || ctx.background || ctx.useful_in_context);

    return (
      <div data-copy-results ref={resultsRef} className="scroll-mt-24 space-y-4 mt-4">
        {/* Hero pronunciation, or an honest "not enough to go on" state */}
        {hasHero ? (
          <div className={'p-6 rounded-2xl border-2 ' + c.phonBg + ' text-center'}>
            {statusKey && <p className={'text-[11px] font-semibold ' + c.textMuted + ' mb-1'}>{t(statusKey)}</p>}
            <p className={'text-xs font-bold ' + c.textMuted + ' uppercase mb-1'}>{results.language || t('pir_pronunciation')}</p>
            <p className={'text-3xl font-black tracking-wide ' + c.text + ' mb-2'}>{results.word}</p>
            <p className={'text-xl font-bold ' + c.tipText + ' mb-3'}>{p.phonetic}</p>

            {audioSafe && (
              <div className="flex flex-col items-center gap-2">
                {!audioUrl ? (
                  <button onClick={fetchAudio} disabled={audioLoading}
                    className={'text-sm font-bold px-4 py-2 rounded-xl border disabled:opacity-40 ' + c.btnSecondary}>
                    {audioLoading
                      ? <><span className="inline-block animate-spin me-1">{tool?.icon ?? '🗣️'}</span> {t('pir_loading')}</>
                      : <>🔊 {t('pir_hear_it')}</>}
                  </button>
                ) : (
                  <div className="flex flex-col items-center gap-1.5">
                    <audio controls autoPlay src={audioUrl} className="h-8 w-48"
                      onEnded={() => { URL.revokeObjectURL(audioUrl); setAudioUrl(null); }} />
                    <button onClick={() => { URL.revokeObjectURL(audioUrl); setAudioUrl(null); }}
                      className={'text-[10px] ' + c.textMuted}>✕ {t('pir_close')}</button>
                  </div>
                )}
                <p className={'text-[10px] ' + c.textMuted}>{t('pir_audio_note')}</p>
              </div>
            )}

            {p.ipa && (
              <button onClick={() => setShowIPA(!showIPA)} className={'text-xs mt-3 block mx-auto ' + linkStyle}>
                {showIPA ? `${t('pir_copy_ipa')} ${p.ipa}` : t('pir_show_ipa')}
              </button>
            )}
          </div>
        ) : (
          <div className={'p-6 rounded-2xl border-2 ' + c.phonBg + ' text-center'}>
            {statusKey && <p className={'text-[11px] font-semibold ' + c.textMuted + ' mb-1'}>{t(statusKey)}</p>}
            <p className={'text-3xl font-black tracking-wide ' + c.text}>{results.word}</p>
          </div>
        )}

        {/* This needs more context to answer well */}
        {needsContext && (results.needs_context?.reason || results.needs_context?.helpful_context) && (
          <div className={'p-4 rounded-xl border ' + c.infoBox}>
            {results.needs_context.reason && <p className="text-sm">{results.needs_context.reason}</p>}
            {results.needs_context.helpful_context && (
              <p className="text-xs mt-1"><span className="font-bold">{t('pir_needs_context_helper_label')}</span> {results.needs_context.helpful_context}</p>
            )}
          </div>
        )}

        {/* Syllables */}
        {p.syllables?.length > 0 && (
          <div className={'p-4 rounded-xl ' + c.inset + ' flex items-center justify-center gap-1 flex-wrap'}>
            {p.syllables.map((syl, i) => (
              <React.Fragment key={i}>
                {i > 0 && <span className={'text-lg font-light ' + c.textMuted}>·</span>}
                <span className={'text-lg font-bold px-2 py-1 rounded-lg ' + c.text}>{syl}</span>
              </React.Fragment>
            ))}
          </div>
        )}

        {/* Sounds like + mouth guide + prosody */}
        {(p.sounds_like || p.mouth_guide || (p.prosody && prosodyLabelKey)) && (
          <div className={c.card + ' border rounded-xl p-4 space-y-3'}>
            {p.sounds_like && (
              <div>
                <p className={'text-xs font-bold ' + c.textMuted + ' uppercase mb-1'}>👂 {t('pir_sounds_like')}</p>
                <p className={'text-sm ' + c.text}>{p.sounds_like}</p>
              </div>
            )}
            {p.mouth_guide && (
              <div>
                <p className={'text-xs font-bold ' + c.textMuted + ' uppercase mb-1'}>👄 {t('pir_mouth_guide')}</p>
                <p className={'text-sm ' + c.text}>{p.mouth_guide}</p>
              </div>
            )}
            {p.prosody && prosodyLabelKey && (
              <div>
                <p className={'text-xs font-bold ' + c.textMuted + ' uppercase mb-1'}>💪 {t(prosodyLabelKey)}</p>
                <p className={'text-xs ' + c.textSecondary}>{p.prosody}</p>
              </div>
            )}
          </div>
        )}

        {/* Watch out for */}
        {results.watch_out_for?.length > 0 && (
          <Section title={t('pir_watch_out_for')} emoji="⚠️" sKey="watch" defaultOpen>
            <div className="space-y-2 mt-3">
              {results.watch_out_for.map((w, i) => (
                <div key={i} className={'p-3 rounded-lg border ' + c.warning}>
                  <p className={'text-xs ' + c.warningTxt}>{w.trap}</p>
                  {w.fix && <p className={'text-[10px] font-semibold ' + c.successTxt + ' mt-1'}>→ {w.fix}</p>}
                </div>
              ))}
            </div>
          </Section>
        )}

        {/* Another established pronunciation */}
        {results.variants?.length > 0 && (
          <Section title={t('pir_variants_title')} emoji="🔀" sKey="variants">
            <div className="space-y-2 mt-3">
              {results.variants.map((v, i) => (
                <div key={i} className={'p-3 rounded-lg ' + c.inset}>
                  <div className="flex items-center gap-2 flex-wrap">
                    {v.label && <span className={'text-xs font-bold ' + c.text}>{v.label}</span>}
                    {v.phonetic && <span className={'text-xs ' + c.tipText}>{v.phonetic}</span>}
                    {v.ipa && <span className={'text-[10px] font-mono ' + c.textMuted}>{v.ipa}</span>}
                  </div>
                  {v.when_used && <p className={'text-[10px] ' + c.textMuted + ' mt-0.5'}>{v.when_used}</p>}
                </div>
              ))}
            </div>
          </Section>
        )}

        {/* Context info */}
        {hasContextInfo && (
          <div className={c.card + ' border rounded-xl p-4 space-y-3'}>
            {ctx.what_it_is && (
              <div>
                <p className={'text-xs font-bold ' + c.textMuted + ' uppercase mb-1'}>{activeCat.emoji} {t('pir_what_it_is')}</p>
                <p className={'text-sm ' + c.text}>{ctx.what_it_is}</p>
              </div>
            )}
            {ctx.background && (
              <div>
                <p className={'text-xs font-bold ' + c.textMuted + ' uppercase mb-1'}>📖 {t('pir_background')}</p>
                <p className={'text-xs ' + c.textSecondary}>{ctx.background}</p>
              </div>
            )}
            {ctx.useful_in_context && (
              <div className={'p-3 rounded-lg ' + c.tipBg}>
                <p className={'text-xs font-bold ' + c.tipText}>💬 {t('pir_useful_in_context')}</p>
                <p className={'text-sm ' + c.tipText}>{ctx.useful_in_context}</p>
              </div>
            )}
          </div>
        )}

        {/* If you're unsure */}
        {results.confirmation_script && (
          <div className={'p-4 rounded-xl border ' + c.successBox}>
            <p className={'text-xs font-bold ' + c.successTxt + ' mb-1'}>💬 {t('pir_unsure_moment')}</p>
            <p className={'text-sm italic ' + c.successTxt}>"{results.confirmation_script}"</p>
          </div>
        )}

        {/* Post-result cross-ref */}
        <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
          <p className={`text-[10px] font-bold ${c.textMuted} uppercase mb-2`}>{t('pir_next_step')}</p>
          <p className={`text-xs ${c.textSecondary}`}>
            {t('pir_xref_nervecheck_q')} <a href="/NerveCheck" className={linkStyle}>💪 {t('pir_nervecheck')}</a> {t('pir_xref_nervecheck_tail')}
          </p>
        </div>

      </div>
    );
  };

  // ════════════════════════════════════════════════════════════
  // BATCH RESULTS
  // ════════════════════════════════════════════════════════════
  const renderBatch = () => {
    if (!batchResults?.guides?.length) return null;
    return (
      <div data-copy-results ref={resultsRef} className="scroll-mt-24 space-y-3 mt-4">
        <p className={'text-xs font-bold ' + c.textMuted + ' uppercase'}>🗣️ {t('pir_batch_count', { count: batchResults.guides.length })}</p>
        {batchResults.guides.map((g, i) => (
          <div key={i} className={c.card + ' border rounded-xl p-4'}>
            <div className="mb-2">
              <p className={'text-lg font-bold ' + c.text}>{g.word}</p>
              {g.phonetic
                ? <p className={'text-base font-bold ' + c.tipText}>{g.phonetic}</p>
                : <p className={'text-[10px] font-bold uppercase ' + c.textMuted}>{t('pir_batch_needs_context')}</p>}
            </div>
            {g.prosody && <p className={'text-xs ' + c.textSecondary + ' mb-1'}>{g.prosody}</p>}
            {g.sound_note && <p className={'text-xs ' + c.text + ' mb-1'}>👂 {g.sound_note}</p>}
            {g.watch_out_for && (
              <div className={'p-2 rounded-lg ' + c.warning + ' mt-2'}>
                <p className={'text-[10px] ' + c.warningTxt}>⚠️ {g.watch_out_for}</p>
              </div>
            )}
            {!g.phonetic && g.context_needed && <p className={'text-[10px] italic ' + c.textMuted + ' mt-1'}>{g.context_needed}</p>}
          </div>
        ))}
      </div>
    );
  };

  // ════════════════════════════════════════════════════════════
  // HISTORY
  // ════════════════════════════════════════════════════════════
  const renderHistory = () => {
    if (sessionHistory.length === 0) return null;
    return (
      <div className={'mt-6 p-4 rounded-2xl border ' + c.cardAlt}>
        <button onClick={() => setShowHistory(!showHistory)} className="w-full flex items-center gap-2 text-start">
          <span>🗣️</span>
          <span className={'text-sm font-bold ' + c.text + ' flex-1'}>{t('pir_words_looked_up')}</span>
          <span className={'text-xs ' + c.textMuted}>{sessionHistory.length}</span>
          <Caret open={showHistory} />
        </button>
        {showHistory && (
          <div className="mt-3 flex flex-wrap gap-1.5">
            {sessionHistory.map(entry => (
              <button key={entry.id}
                onClick={() => { setWord(entry.word); setCategory(entry.category); setResults(null); setBatchResults(null); setBatchMode(false); }}
                className={'px-3 py-1.5 rounded-lg border text-xs font-semibold ' + c.pillInactive}>
                {entry.emoji} {entry.word}
                {entry.phonetic && <span className={'ms-1.5 ' + c.textMuted}>({entry.phonetic})</span>}
              </button>
            ))}
          </div>
        )}
      </div>
    );
  };

  // ════════════════════════════════════════════════════════════
  // MAIN RENDER
  // ════════════════════════════════════════════════════════════
  return (
    <div className={`space-y-4 ${c.text}`}>
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm px-5 pt-2.5 pb-5`}>
        <div className="pb-3 border-b border-zinc-500 flex items-start justify-between gap-3">
          <div>
            {/* PF-30 — the wrapper already prints the name as the page <h1>. */}
            <p className={`text-base ${c.textSecondary}`}>
              <span className="me-2 text-lg">{tool?.icon ?? '🗣️'}</span>{t('pir_tagline')}
            </p>
            <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className="mt-2 px-4 py-2 rounded-full text-sm font-semibold border border-black/25 text-zinc-900 shadow-sm hover:brightness-105 hover:shadow transition disabled:opacity-40 whitespace-nowrap">✨ {t('try_example')}</button>
          </div>
          {(results || batchResults || word.trim()) && (
            <button onClick={handleReset} className={`flex-shrink-0 ${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs font-medium`}>
              ↺ {t('start_over')}
            </button>
          )}
        </div>
      </div>
      {!results && !batchResults && renderInput()}
      {!results && !batchResults && (
        <p className={`text-[11px] ${c.textMuted} text-center`}>
          {t('pir_xref_plaintalk_q')} <a href="/PlainTalk" className={linkStyle}>📄 {t('pir_plaintalk')}</a> {t('pir_xref_plaintalk_tail')}
        </p>
      )}
      {renderResult()}
      {renderBatch()}
      {(results || batchResults) && (
        <div className="mt-4 space-y-3">
          <div className="flex gap-2">
            <button onClick={() => { setResults(null); setBatchResults(null); setError(''); setAudioUrl(null); }}
              className={'flex-1 py-3 rounded-xl text-xs font-bold flex items-center justify-center gap-1.5 ' + c.btnSecondary}>
              <span>✏️</span> {t('pir_edit_input')}
            </button>
          </div>
          <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
            <p className={`text-[10px] font-bold ${c.textMuted} uppercase mb-2`}>🔗 {t('pir_related_tools')}</p>
            <div className="flex flex-wrap gap-3">
              <a href="/DecoderRing" className={`text-xs ${linkStyle}`}>💬 {t('pir_decoder_ring')}</a>
              <a href="/TipOfTongue" className={`text-xs ${linkStyle}`}>💡 {t('pir_tip_of_tongue')}</a>
            </div>
          </div>
        </div>
      )}
      {error && (
        <div className={`mt-4 p-4 border rounded-xl flex items-start gap-3 ${c.danger}`}>
          <span className="text-base">⚠️</span>
          <p className="text-sm">{error}</p>
        </div>
      )}
      {renderHistory()}
    </div>
  );
};

PronounceItRight.displayName = 'PronounceItRight';
export default PronounceItRight;
