import React, { useState, useCallback, useEffect, useRef } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';
import { currencySymbol, formatDate } from '../utils/formatLocale';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';


const EXAMPLE = {
  country: 'US',
  region: 'California',
  address: '1428 Elm Street',
  unit: 'Apt 3B',
  landlordName: 'Pacific Bay Property Management',
  landlordEmail: 'admin@pacificbaypm.com',
  moveInDate: '2024-09-01',
  depositAmount: '4200',
};
// ════════════════════════════════════════════════════════════
// CONSTANTS
// ════════════════════════════════════════════════════════════
const US_STATES = [
  'Alabama','Alaska','Arizona','Arkansas','California','Colorado','Connecticut',
  'Delaware','District of Columbia','Florida','Georgia','Hawaii','Idaho','Illinois',
  'Indiana','Iowa','Kansas','Kentucky','Louisiana','Maine','Maryland','Massachusetts',
  'Michigan','Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada',
  'New Hampshire','New Jersey','New Mexico','New York','North Carolina','North Dakota',
  'Ohio','Oklahoma','Oregon','Pennsylvania','Rhode Island','South Carolina',
  'South Dakota','Tennessee','Texas','Utah','Vermont','Virginia','Washington',
  'West Virginia','Wisconsin','Wyoming',
];

const CA_PROVINCES = [
  'Alberta','British Columbia','Manitoba','New Brunswick','Newfoundland and Labrador',
  'Northwest Territories','Nova Scotia','Nunavut','Ontario','Prince Edward Island',
  'Quebec','Saskatchewan','Yukon',
];

const AU_STATES = [
  'Australian Capital Territory','New South Wales','Northern Territory','Queensland',
  'South Australia','Tasmania','Victoria','Western Australia',
];

const COUNTRIES = [
  { code: 'US', label: 'United States', regionLabel: 'State', regions: US_STATES },
  { code: 'CA', label: 'Canada', regionLabel: 'Province', regions: CA_PROVINCES },
  { code: 'UK', label: 'United Kingdom', regionLabel: 'Region (optional)', regions: ['England','Scotland','Wales','Northern Ireland'] },
  { code: 'AU', label: 'Australia', regionLabel: 'State / Territory', regions: AU_STATES },
  { code: 'IE', label: 'Ireland', regionLabel: 'County (optional)', regions: null },
  { code: 'NZ', label: 'New Zealand', regionLabel: 'Region (optional)', regions: null },
  { code: 'DE', label: 'Germany', regionLabel: 'State (optional)', regions: null },
  { code: 'NL', label: 'Netherlands', regionLabel: 'Province (optional)', regions: null },
  { code: 'FR', label: 'France', regionLabel: 'Region (optional)', regions: null },
  { code: 'OTHER', label: 'Other country', regionLabel: 'Country & Region', regions: null },
];

const ROOM_TEMPLATES = [
  {
    name: 'Living Room', emoji: '🛋️',
    checkpoints: [
      'Walls (scuffs, holes, paint)','Ceiling (stains, cracks)','Flooring (scratches, stains, damage)',
      'Windows (cracks, locks, screens)','Light fixtures & switches','Electrical outlets',
      'Doors (hinges, locks, damage)','Baseboards & trim',
    ],
  },
  {
    name: 'Kitchen', emoji: '🍳',
    checkpoints: [
      'Countertops (chips, stains, burns)','Cabinets (doors, hinges, interior)','Sink & faucet (leaks, stains)',
      'Stove/Oven (burners, interior, knobs)','Refrigerator (interior, seals, ice maker)',
      'Dishwasher (interior, racks, door)','Microwave (if built-in)','Flooring (stains, damage)',
      'Walls & backsplash','Garbage disposal',
    ],
  },
  {
    name: 'Bedroom', emoji: '🛏️', duplicable: true,
    checkpoints: [
      'Walls (scuffs, holes, paint)','Ceiling (stains, cracks)','Flooring (scratches, stains)',
      'Windows (cracks, locks, screens)','Closet (doors, shelves, rods)',
      'Light fixtures & switches','Electrical outlets','Doors (hinges, locks)',
    ],
  },
  {
    name: 'Bathroom', emoji: '🚿', duplicable: true,
    checkpoints: [
      'Toilet (flush, base, seat)','Sink & faucet (leaks, stains)','Bathtub/Shower (caulking, drain, tiles)',
      'Mirror & medicine cabinet','Tile & grout (mold, cracks)','Exhaust fan',
      'Towel bars & hardware','Flooring (water damage, stains)',
    ],
  },
  {
    name: 'Hallway / Entry', emoji: '🚪',
    checkpoints: [
      'Front door (lock, deadbolt, frame)','Walls & paint','Flooring',
      'Light fixtures','Closet (if present)','Doorbell / intercom',
    ],
  },
  {
    name: 'Laundry Area', emoji: '🧺',
    checkpoints: [
      'Washer connections','Dryer vent & connections','Flooring (water stains)',
      'Walls & paint','Cabinets/shelving',
    ],
  },
  {
    name: 'Outdoor / Patio', emoji: '🌿',
    checkpoints: [
      'Patio/Balcony surface','Railings','Exterior door & lock',
      'Outdoor lighting','Screens / storm doors',
    ],
  },
];

const DEFAULT_INCLUDED = ['Living Room', 'Kitchen', 'Bedroom', 'Bathroom', 'Hallway / Entry'];

const buildDefaultRooms = () =>
  ROOM_TEMPLATES.map(t => ({
    name: t.name,
    emoji: t.emoji,
    duplicable: !!t.duplicable,
    included: DEFAULT_INCLUDED.includes(t.name),
    checkpoints: t.checkpoints.map(cp => ({ label: cp, condition: '', notes: '' })),
  }));

const CONDITION_OPTIONS = [
  { value: 'good',    label: 'Good',    dot: 'bg-emerald-500', light: 'bg-emerald-50 border-emerald-200 text-emerald-700',  dark: 'bg-emerald-900/30 border-emerald-700 text-emerald-300' },
  { value: 'fair',    label: 'Fair',    dot: 'bg-amber-500',   light: 'bg-amber-50 border-amber-200 text-amber-700',        dark: 'bg-amber-900/30 border-amber-700 text-amber-300' },
  { value: 'poor',    label: 'Poor',    dot: 'bg-amber-500',  light: 'bg-amber-50 border-amber-200 text-amber-700',      dark: 'bg-amber-900/30 border-amber-700 text-amber-300' },
  { value: 'damaged', label: 'Damaged', dot: 'bg-red-500',     light: 'bg-red-50 border-red-200 text-red-700',              dark: 'bg-red-900/30 border-red-700 text-red-300' },
  { value: 'na',      label: 'N/A',     dot: 'bg-zinc-400',    light: 'bg-zinc-50 border-zinc-200 text-zinc-500',        dark: 'bg-zinc-700 border-zinc-600 text-zinc-400' },
];

const TODAY = new Date().toISOString().split('T')[0];

// Skeleton placeholder shown while a section is being generated
const SectionSkeleton = ({ isDark, c, generatingLabel }) => (
  <div className={`${c.card} border ${c.border} rounded-2xl shadow-sm p-5 sm:p-6 animate-pulse`}>
    <div className="flex items-center gap-3 mb-4">
      <div className={`w-6 h-6 rounded-full ${isDark ? 'bg-zinc-700' : 'bg-zinc-200'}`} />
      <div className={`h-5 w-48 rounded ${isDark ? 'bg-zinc-700' : 'bg-zinc-200'}`} />
    </div>
    <div className={`rounded-xl border p-5 ${isDark ? 'bg-zinc-900 border-zinc-700' : 'bg-zinc-50 border-zinc-200'}`}>
      <div className="space-y-2.5">
        {[100, 85, 92, 70, 88, 60].map((w, i) => (
          <div key={i} className={`h-3 rounded ${isDark ? 'bg-zinc-700' : 'bg-zinc-300'}`} style={{ width: `${w}%` }} />
        ))}
      </div>
    </div>
    <p className={`text-xs mt-3 ${isDark ? 'text-zinc-500' : 'text-zinc-400'}`}>{generatingLabel}</p>
  </div>
);


const RentersDepositSaver = ({ tool }) => {
  const { callToolEndpoint, loading, userLanguage, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();
  const sym = currencySymbol(userLocale, userCurrency);

  // Display-only lookups. Stored room `name` and condition `value` stay English
  // (logic/matching depend on them); these map them to localized labels at render.
  const ROOM_LABELS = {
    'Living Room':     t('rds_room_living'),
    'Kitchen':         t('rds_room_kitchen'),
    'Bedroom':         t('rds_room_bedroom'),
    'Bathroom':        t('rds_room_bathroom'),
    'Hallway / Entry': t('rds_room_hallway'),
    'Laundry Area':    t('rds_room_laundry'),
    'Outdoor / Patio': t('rds_room_outdoor'),
  };
  const roomLabel = (name) => {
    if (ROOM_LABELS[name]) return ROOM_LABELS[name];
    // Handle duplicated names like "Bedroom 2" → "<translated Bedroom> 2"
    const m = name.match(/^(.*?)(\s+\d+)$/);
    if (m && ROOM_LABELS[m[1]]) return ROOM_LABELS[m[1]] + m[2];
    return name;
  };
  const CONDITION_LABELS = {
    good:    t('rds_cond_good'),
    fair:    t('rds_cond_fair'),
    poor:    t('rds_cond_poor'),
    damaged: t('rds_cond_damaged'),
    na:      t('rds_cond_na'),
  };

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-400' : 'text-gray-500',
    required:      isDark ? 'text-amber-400' : 'text-amber-700',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-200 text-red-800',
  };
  c.textMuteded = c.textMuted;
  c.label       = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';

  // ── Ephemeral state ──
  const [step, setStep]               = useState(1); // 1=walkthrough, 2=details, 3=results
  const [activeRoom, setActiveRoom]    = useState(() => {
    const first = buildDefaultRooms().findIndex(r => r.included);
    return first >= 0 ? first : 0;
  });
  const [customRoomName, setCustomRoomName] = useState('');
  const [results, setResults]          = useState(null);
  const [streamLoading, setStreamLoading] = useState(false);
  const [error, setError]              = useState('');
  const [expandedSection, setExpandedSection] = useState('report');

  // ── Rights quick-lookup state ──
  const [rightsResult, setRightsResult]   = useState(null);
  const [rightsLoading, setRightsLoading] = useState(false);
  const [rightsError, setRightsError]     = useState('');
  const [showRights, setShowRights]       = useState(false);

  // ── Refs ──
  const resultsRef   = useRef(null);
  const submitRef    = useRef(null);
  const canSubmitRef = useRef(false);

  // ── Persisted state (survives tab close) ──
  const [country, setCountry]           = usePersistentState('rds-country', 'US');
  const [region, setRegion]             = usePersistentState('rds-region', '');
  const [rooms, setRooms]               = usePersistentState('rds-rooms', buildDefaultRooms());
  const [address, setAddress]           = usePersistentState('rds-address', '');
  const [unit, setUnit]                 = usePersistentState('rds-unit', '');
  const [landlordName, setLandlordName] = usePersistentState('rds-landlordName', '');
  const [sessionHistory, setSessionHistory] = usePersistentState('rentersdepositsaver-history', []);
  const [landlordEmail, setLandlordEmail] = usePersistentState('rds-landlordEmail', '');
  const [moveInDate, setMoveInDate]     = usePersistentState('rds-moveInDate', TODAY);
  const [depositAmount, setDepositAmount] = usePersistentState('rds-depositAmount', '');

  // ── Derived ──
  const countryObj = COUNTRIES.find(co => co.code === country) || COUNTRIES[0];
  const hasDropdownRegions = countryObj.regions && countryObj.regions.length > 0;
  const regionRequired = country === 'US' || country === 'CA' || country === 'AU';

  const locationString = (() => {
    if (country === 'OTHER') return region.trim();
    const parts = [];
    if (region.trim()) parts.push(region.trim());
    parts.push(countryObj.label);
    return parts.join(', ');
  })();
  const locationValid = country === 'OTHER' ? region.trim().length >= 2 : (!regionRequired || region.trim().length > 0);

  const includedRooms = rooms.filter(r => r.included);
  const completionStats = includedRooms.reduce(
    (acc, room) => {
      const total = room.checkpoints.length;
      const done = room.checkpoints.filter(cp => cp.condition).length;
      return { total: acc.total + total, done: acc.done + done };
    },
    { total: 0, done: 0 }
  );

  const step2Valid = address.trim() && moveInDate && locationValid;

  // ═══════════════════════════════════════
  // HANDLERS
  // ═══════════════════════════════════════

  const toggleRoom = (idx) => {
    setRooms(prev => prev.map((r, i) => i === idx ? { ...r, included: !r.included } : r));
  };

  const updateCheckpoint = (roomIdx, cpIdx, field, value) => {
    setRooms(prev =>
      prev.map((r, ri) =>
        ri === roomIdx
          ? { ...r, checkpoints: r.checkpoints.map((cp, ci) => ci === cpIdx ? { ...cp, [field]: value } : cp) }
          : r
      )
    );
  };

  const updateCheckpointLabel = (roomIdx, cpIdx, label) => {
    setRooms(prev =>
      prev.map((r, ri) =>
        ri === roomIdx
          ? { ...r, checkpoints: r.checkpoints.map((cp, ci) => ci === cpIdx ? { ...cp, label } : cp) }
          : r
      )
    );
  };

  const removeCheckpoint = (roomIdx, cpIdx) => {
    setRooms(prev =>
      prev.map((r, ri) =>
        ri === roomIdx ? { ...r, checkpoints: r.checkpoints.filter((_, ci) => ci !== cpIdx) } : r
      )
    );
  };

  const addCheckpoint = (roomIdx) => {
    setRooms(prev =>
      prev.map((r, i) =>
        i === roomIdx
          ? { ...r, checkpoints: [...r.checkpoints, { label: '', condition: '', notes: '' }] }
          : r
      )
    );
  };

  const addCustomRoom = () => {
    if (!customRoomName.trim()) return;
    const newRoom = {
      name: customRoomName.trim(),
      emoji: '📋',
      duplicable: true,
      included: true,
      checkpoints: [
        { label: 'Walls & paint', condition: '', notes: '' },
        { label: 'Flooring', condition: '', notes: '' },
        { label: 'Windows', condition: '', notes: '' },
        { label: 'Light fixtures', condition: '', notes: '' },
        { label: 'Doors', condition: '', notes: '' },
      ],
    };
    setRooms(prev => [...prev, newRoom]);
    setActiveRoom(rooms.length); // jump to new room
    setCustomRoomName('');
  };

  // ── NEW: Mark remaining unrated items in a room as Good ──
  const markRemainingGood = (roomIdx) => {
    setRooms(prev =>
      prev.map((r, ri) =>
        ri === roomIdx
          ? { ...r, checkpoints: r.checkpoints.map(cp => cp.condition ? cp : { ...cp, condition: 'good' }) }
          : r
      )
    );
  };

  // ── NEW: Duplicate a room (for multiple bedrooms/bathrooms) ──
  const duplicateRoom = (idx) => {
    const room = rooms[idx];
    const baseName = room.name.replace(/\s+\d+$/, ''); // "Bedroom 2" → "Bedroom"
    const existing = rooms.filter(r => r.name === baseName || r.name.match(new RegExp(`^${baseName}\\s+\\d+$`))).length;
    const newName = `${baseName} ${existing + 1}`;

    // Also rename the original if it has no number yet
    const needsRename = room.name === baseName && existing === 1;

    const newRoom = {
      name: newName,
      emoji: room.emoji,
      duplicable: true,
      included: true,
      checkpoints: ROOM_TEMPLATES.find(t => t.name === baseName)
        ? ROOM_TEMPLATES.find(t => t.name === baseName).checkpoints.map(cp => ({ label: cp, condition: '', notes: '' }))
        : room.checkpoints.map(cp => ({ label: cp.label, condition: '', notes: '' })),
    };

    setRooms(prev => {
      let updated = [...prev];
      if (needsRename) {
        updated = updated.map((r, i) => i === idx ? { ...r, name: `${baseName} 1` } : r);
      }
      updated.splice(idx + 1, 0, newRoom);
      return updated;
    });
    setActiveRoom(idx + 1);
  };

  // ── NEW: Quick rights lookup ──
  const lookupRights = async () => {
    if (!locationValid) return;
    setRightsLoading(true);
    setRightsError('');
    setRightsResult(null);
    setShowRights(true);
    try {
      const data = await callToolEndpoint('renters-deposit-saver/rights', { location: locationString });
      setRightsResult(data);
    } catch (err) {
      setRightsError(err.message || t('rds_rights_failed'));
    } finally {
      setRightsLoading(false);
    }
  };

  // ── Generate full report (SSE streaming — sections render as they arrive) ──
  const generateReport = async () => {
    setError('');
    setResults(null);
    setStreamLoading(true);
    // Stay on step 2 so the spinning button is visible; jump to step 3 on first section

    const checklistData = includedRooms.map(room => ({
      room: room.name,
      items: room.checkpoints
        .filter(cp => cp.condition && cp.condition !== 'na')
        .map(cp => ({ item: cp.label, condition: cp.condition, notes: cp.notes || null })),
    }));

    let stepped = false;
    try {
      const response = await fetch('/api/renters-deposit-saver/stream', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          address: address.trim(), unit: unit.trim(),
          landlordName: landlordName.trim(), landlordEmail: landlordEmail.trim(),
          moveInDate, location: locationString,
          depositAmount: depositAmount.trim(), checklist: checklistData,
          userLanguage, userLocale, userCurrency, userRegion,
        }),
      });

      if (!response.ok) {
        const err = await response.json().catch(() => ({}));
        throw new Error(err.error || t('rds_generate_failed'));
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop();
        for (const line of lines) {
          if (!line.startsWith('data: ')) continue;
          let event;
          try {
            event = JSON.parse(line.slice(6));
          } catch (parseErr) {
            if (!(parseErr instanceof SyntaxError)) throw parseErr;
            continue; // partial/malformed SSE line — skip it
          }
          if (event.error) {
            // A section group failed — keep whatever already arrived and flag it inline
            setError(t('rds_sections_failed'));
            continue;
          }
          if (event.done) continue;
          if (event.section && event.content) {
            if (!stepped) {
              // First section arrived — jump to step 3 with results initialized
              setResults({ [event.section]: event.content });
              setStep(3);
              stepped = true;
            } else {
              setResults(prev => ({ ...prev, [event.section]: event.content }));
            }
          }
        }
      }

      setSessionHistory(prev => [
        { id: Date.now(), date: new Date().toISOString(), preview: (address || region || '').substring(0, 40) },
        ...prev,
      ].slice(0, 6));
    } catch (err) {
      if (stepped) {
        // Some sections already rendered — keep them, show an inline error instead of wiping
        setError(t('rds_sections_failed'));
      } else {
        setError(err.message || t('rds_generate_failed'));
        setStep(2);
        setResults(null);
      }
    } finally {
      setStreamLoading(false);
    }
  };

  // ── Load Example ──
  const loadExample = useCallback(() => {
    setCountry(EXAMPLE.country);
    setRegion(EXAMPLE.region);
    setAddress(EXAMPLE.address);
    setUnit(EXAMPLE.unit);
    setLandlordName(EXAMPLE.landlordName);
    setLandlordEmail(EXAMPLE.landlordEmail);
    setMoveInDate(EXAMPLE.moveInDate);
    setDepositAmount(EXAMPLE.depositAmount);
    setResults(null);
  }, [setCountry, setRegion, setAddress, setUnit, setLandlordName, setLandlordEmail, setMoveInDate, setDepositAmount, setResults]);




  // ── Reset ──
  const reset = () => {
    setStep(1);
    setCountry('US');
    setRegion('');
    setAddress('');
    setUnit('');
    setLandlordName('');
    setLandlordEmail('');
    setMoveInDate(TODAY);
    setDepositAmount('');
    setRooms(buildDefaultRooms());
    setActiveRoom(0);
    setResults(null);
    setStreamLoading(false);
    setError('');
    setExpandedSection('report');
    setRightsResult(null);
    setRightsError('');
    setShowRights(false);
  };

  // Check if user has any persisted progress
  const hasProgress = rooms.some(r => r.included && r.checkpoints.some(cp => cp.condition));

  // ── buildFullText ──
  const buildFullText = useCallback(() => {
    if (!results && !rightsResult) return '';
    const divider = '\n\n' + '═'.repeat(50) + '\n\n';
    const sections = [];
    if (results?.condition_report) sections.push(t('rds_copy_condition') + '\n' + results.condition_report);
    if (results?.landlord_letter)  sections.push(t('rds_copy_letter') + '\n' + results.landlord_letter);
    if (results?.photo_shot_list)  sections.push(t('rds_copy_photos') + '\n' + results.photo_shot_list);
    if (results?.deposit_rights)   sections.push(t('rds_copy_rights') + '\n' + results.deposit_rights);
    if (results?.move_out_tips)    sections.push(t('rds_copy_tips') + '\n' + results.move_out_tips);
    if (rightsResult) {
      const rl = [t('rds_copy_rights') + (locationString ? ` — ${locationString}` : '')];
      if (rightsResult.rights_summary) rl.push(rightsResult.rights_summary);
      if (Array.isArray(rightsResult.key_rights) && rightsResult.key_rights.length > 0)
        rl.push(rightsResult.key_rights.map(k => `• ${k}`).join('\n'));
      if (rightsResult.caution) rl.push(rightsResult.caution);
      sections.push(rl.join('\n\n'));
    }
    return sections.join(divider) + BRAND;
  }, [results, rightsResult, locationString, t]);

  submitRef.current    = generateReport;
  canSubmitRef.current = step === 2 && !streamLoading && !!step2Valid;

  useRegisterActions(buildFullText(), tool?.title || "Renter's Deposit Saver");

  // ── Scroll to results when step 3 begins ──
  useEffect(() => {
    if (step !== 3 || !resultsRef.current) return;
    const t = setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 200);
    return () => clearTimeout(t);
  }, [step]);

  // ── Keyboard shortcut (Cmd/Ctrl+Enter on step 2) ──
  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && canSubmitRef.current)
        submitRef.current?.();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [streamLoading, step]);

  // ── Room sync: if activeRoom gets excluded, jump to first included ──
  useEffect(() => {
    if (!rooms[activeRoom]?.included) {
      const first = rooms.findIndex(r => r.included);
      if (first >= 0) setActiveRoom(first);
    }
  }, [rooms, activeRoom]);

  // ════════════════════════════════════════════════════════════
  // RENDER
  // ════════════════════════════════════════════════════════════

  return (
    <div className={`space-y-4 ${c.text}`}>

      {/* ── Persistent header ── */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm overflow-hidden print:hidden`}>
        <div className="px-5 pt-5">
          <div className="flex items-start justify-between pb-3 border-b border-zinc-500">
            <div>
              <h2 className={`text-xl font-bold ${c.text}`}>
                <span className="me-2">{tool?.icon ?? '🏦'}</span>{tool?.title ?? t('rds_title')}
              </h2>
              <p className={`text-sm ${c.textSecondary}`}>{tool?.tagline ?? t('rds_tagline')}</p>
              <button onClick={loadExample} disabled={loading || streamLoading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className={`mt-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium border disabled:opacity-40 ${isDark ? 'text-white border-white/40' : 'text-gray-800 border-transparent'}`}>{t('try_example')}</button>
            </div>
            <div className="flex items-center gap-3">
              {hasProgress && step < 3 && !results && !streamLoading ? (
                <div className={`flex items-center gap-1.5 text-xs ${isDark ? 'text-cyan-400' : 'text-cyan-600'}`}>
                  <span className="font-medium">{t('rds_progress_saved')}</span>
                </div>
              ) : null}
              {(hasProgress || address.trim() || results || streamLoading) ? (
                <button onClick={reset} className={`${c.btnSecondary} px-3 py-1.5 rounded-lg text-sm font-semibold transition-colors whitespace-nowrap`}>
                  ↺ {t('start_over')}
                </button>
              ) : null}
            </div>
          </div>
        </div>
      </div>

      {/* ── Step indicator ── */}
      <div className="flex items-center justify-center gap-2 mb-6 print:hidden">
        {[
          { num: 1, label: t('rds_step_walkthrough') },
          { num: 2, label: t('rds_step_details') },
          { num: 3, label: t('rds_step_report') },
        ].map(({ num, label }) => (
          <React.Fragment key={num}>
            {num > 1 && (
              <div className={`w-8 h-px ${step >= num ? 'bg-cyan-400' : isDark ? 'bg-zinc-600' : 'bg-zinc-300'}`} />
            )}
            <button
              onClick={() => { if (num < step) setStep(num); }}
              disabled={num > step}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-bold transition-colors ${
                step === num
                  ? `bg-cyan-600 text-white shadow-md ${isDark ? 'shadow-emerald-900/40' : 'shadow-emerald-200'}`
                  : step > num
                  ? isDark ? 'bg-cyan-900/40 text-cyan-300 hover:bg-cyan-800/50 cursor-pointer'
                    : 'bg-cyan-100 text-cyan-700 hover:bg-cyan-200 cursor-pointer'
                  : isDark ? 'bg-zinc-700 text-zinc-500' : 'bg-zinc-100 text-zinc-400'
              }`}
            >
              <span className={`w-5 h-5 rounded-full flex items-center justify-center text-[10px] font-black ${
                step > num ? 'bg-cyan-500 text-white' : step === num ? 'bg-white/20 text-white' : ''
              }`}>
                {step > num ? '✓' : num}
              </span>
              <span className="hidden sm:inline">{label}</span>
            </button>
          </React.Fragment>
        ))}
      </div>

      {/* ═══════════════════════════════════════════════════ */}
      {/* STEP 1: WALKTHROUGH (the urgent part)              */}
      {/* ═══════════════════════════════════════════════════ */}
      {step === 1 && (
        <div className="space-y-4">

          {/* ── Location bar + Rights lookup ── */}
          <div className={`${c.card} border ${c.border} rounded-2xl shadow-sm p-4 sm:p-5`}>
            <div className="flex items-center gap-2 mb-3">
              <span className={`${isDark ? 'text-cyan-400' : 'text-cyan-600'}`}>⚖️</span>
              <h3 className={`text-sm font-bold ${c.text}`}>{t('rds_your_location')}</h3>
              <span className={`text-xs ${c.textMuteded}`}>{t('rds_for_law')}</span>
            </div>

            <div className="flex flex-col sm:flex-row gap-3 mb-3">
              {/* Country */}
              <select
                value={country}
                onChange={e => { setCountry(e.target.value); setRegion(''); setRightsResult(null); setShowRights(false); }}
                className={`sm:w-48 p-2.5 border rounded-lg text-base outline-none focus:ring-2 transition-colors ${c.input}`}
              >
                {COUNTRIES.map(co => (
                  <option key={co.code} value={co.code}>{co.label}</option>
                ))}
              </select>

              {/* Region: dropdown for US/CA/UK/AU, freetext for others */}
              <div className="flex-1">
                {hasDropdownRegions ? (
                  <select
                    value={region}
                    onChange={e => { setRegion(e.target.value); setRightsResult(null); setShowRights(false); }}
                    className={`w-full p-2.5 border rounded-lg text-base outline-none focus:ring-2 transition-colors ${c.input}`}
                  >
                    <option value="">{t('rds_select_region', { label: countryObj.regionLabel })}</option>
                    {countryObj.regions.map(r => (
                      <option key={r} value={r}>{r}</option>
                    ))}
                  </select>
                ) : (
                  <input
                    type="text"
                    value={region}
                    onChange={e => { setRegion(e.target.value); setRightsResult(null); setShowRights(false); }}
                    placeholder={countryObj.regionLabel}
                    className={`w-full p-2.5 border rounded-lg text-base outline-none focus:ring-2 transition-colors ${c.input}`}
                  />
                )}
              </div>

              {/* Rights lookup button */}
              <button
                onClick={lookupRights}
                disabled={!locationValid || rightsLoading}
                className={`flex items-center gap-1.5 px-4 py-2.5 rounded-lg text-xs font-bold transition-colors whitespace-nowrap ${
                  !locationValid
                    ? isDark ? 'bg-zinc-700 text-zinc-500 cursor-not-allowed' : 'bg-zinc-200 text-zinc-400 cursor-not-allowed'
                    : 'bg-cyan-600 hover:bg-cyan-700 text-white'
                } disabled:opacity-40`}
              >
                {rightsLoading ? <span className='inline-block animate-spin'>{tool?.icon ?? '🏦'}</span> : null}
                {rightsLoading ? t('rds_looking_up') : t('rds_look_up_rights')}
              </button>
            </div>

            {/* Quick rights result */}
            {showRights && (
              <div className={`mt-3 rounded-xl border p-4 ${isDark ? 'bg-zinc-900 border-zinc-700' : 'bg-zinc-50 border-zinc-200'}`}>
                {rightsLoading && (
                  <div className={`flex items-center gap-2 ${c.textMuteded} text-sm`}>
                    
                    {t('rds_looking_up_loc', { loc: locationString })}
                  </div>
                )}
                {rightsError && (
                  <div className="flex items-start gap-2">
                    
                    <p className={`text-sm ${isDark ? 'text-red-300' : 'text-red-700'}`}>{rightsError}</p>
                  </div>
                )}
                {rightsResult && (
                  <>
                    <div className="flex items-start justify-between mb-2">
                      <h4 className={`text-sm font-bold ${c.text} flex items-center gap-1.5`}>
                        <span className={`${isDark ? 'text-cyan-400' : 'text-cyan-600'}`}>⚖️</span>
                        {t('rds_deposit_rights_loc', { loc: locationString })}
                      </h4>
                      <div className="flex gap-1.5">
                        <button
                          onClick={() => setShowRights(false)}
                          className={`p-1 rounded-lg transition-colors ${isDark ? 'hover:bg-zinc-700 text-zinc-400' : 'hover:bg-zinc-200 text-zinc-400'}`}
                        >
                          ✕
                        </button>
                      </div>
                    </div>
                    <div className={`text-xs leading-relaxed max-h-80 overflow-y-auto ${isDark ? 'text-zinc-300' : 'text-gray-700'}`}>
                      {rightsResult.rights_summary && (
                        <p className="mb-2">{rightsResult.rights_summary}</p>
                      )}
                      {Array.isArray(rightsResult.key_rights) && rightsResult.key_rights.length > 0 && (
                        <ul className="space-y-1 list-none">
                          {rightsResult.key_rights.map((kr, i) => (
                            <li key={i} className="flex items-start gap-1.5">
                              <span className={`${isDark ? 'text-cyan-400' : 'text-cyan-600'} shrink-0`}>•</span>
                              <span>{kr}</span>
                            </li>
                          ))}
                        </ul>
                      )}
                      {rightsResult.caution && (
                        <p className={`mt-2 italic ${c.textMuteded}`}>{rightsResult.caution}</p>
                      )}
                    </div>
                    <div className={`mt-3 p-2 rounded-lg text-xs ${isDark ? 'bg-amber-900/20 text-amber-300' : 'bg-amber-50 text-amber-800'}`}>
                      {t('rds_legal_info')}
                    </div>
                  </>
                )}
              </div>
            )}
          </div>

          {/* ── Room selector bar ── */}
          <div className={`${c.card} border ${c.border} rounded-2xl shadow-sm p-4`}>
            <div className="flex items-center justify-between mb-3">
              <h2 className={`text-lg font-bold ${c.text} flex items-center gap-2`}>
                <span className={`${isDark ? 'text-cyan-400' : 'text-cyan-600'}`}>📋</span>
                {t('rds_room_walkthrough')}
              </h2>
              <span className={`text-xs font-bold px-2.5 py-1 rounded-full ${
                completionStats.done === completionStats.total && completionStats.total > 0
                  ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300'
                  : isDark ? 'bg-zinc-700 text-zinc-300' : 'bg-zinc-100 text-gray-600'
              }`}>
                {t('rds_items_count', { done: completionStats.done, total: completionStats.total })}
              </span>
            </div>

            {/* Room tabs with per-room progress */}
            <div className="flex flex-wrap gap-1.5 mb-3">
              {rooms.map((room, idx) => {
                const roomDone = room.included ? room.checkpoints.filter(cp => cp.condition).length : 0;
                const roomTotal = room.included ? room.checkpoints.length : 0;
                const isComplete = room.included && roomDone === roomTotal && roomTotal > 0;

                return (
                  <button
                    key={idx}
                    onClick={() => {
                      if (!room.included) toggleRoom(idx);
                      setActiveRoom(idx);
                    }}
                    className={`flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-xs font-semibold transition-colors border ${
                      !room.included
                        ? isDark ? 'border-zinc-700 text-zinc-500 hover:text-zinc-300 hover:border-zinc-600'
                          : 'border-zinc-200 text-zinc-400 hover:text-gray-600 hover:border-zinc-300'
                        : activeRoom === idx
                        ? 'border-cyan-300 bg-cyan-50 text-cyan-700 dark:border-cyan-600 dark:bg-cyan-900/40 dark:text-cyan-300'
                        : isComplete
                        ? 'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300'
                        : isDark ? 'border-zinc-600 bg-zinc-700 text-zinc-200' : 'border-zinc-200 bg-white text-gray-700'
                    }`}
                  >
                    <span className="text-sm">{room.emoji}</span>
                    <span className="hidden sm:inline">{roomLabel(room.name)}</span>
                    {room.included && isComplete && <span>✓</span>}
                    {room.included && !isComplete && roomTotal > 0 && (
                      <span className={`text-[10px] font-bold ms-0.5 ${isDark ? 'text-zinc-400' : 'text-zinc-400'}`}>
                        {roomDone}/{roomTotal}
                      </span>
                    )}
                    {!room.included && null}
                  </button>
                );
              })}
            </div>

            {/* Add custom room — flex row: the input's flex-1 is inert without it */}
            <div className="flex gap-2">
              <input
                type="text"
                value={customRoomName}
                onChange={e => setCustomRoomName(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && addCustomRoom()}
                placeholder={t('rds_add_custom_room')}
                className={`flex-1 p-2 border rounded-lg text-xs outline-none focus:ring-2 transition-colors ${c.input}`}
              />
              <button
                onClick={addCustomRoom}
                disabled={!customRoomName.trim()}
                className={`px-3 py-2 rounded-lg text-xs font-bold ${c.btnPrimary} disabled:opacity-40 transition-colors min-h-[32px]`}
              >
                ➕
              </button>
            </div>
          </div>

          {/* ── Active room checklist ── */}
          {rooms[activeRoom] && rooms[activeRoom].included && (
            <div className={`${c.card} border ${c.border} rounded-2xl shadow-sm p-4 sm:p-6`}>
              <div className="flex items-center justify-between mb-4">
                <h3 className={`text-lg font-bold ${c.text} flex items-center gap-2`}>
                  <span className="text-xl">{rooms[activeRoom].emoji}</span>
                  {roomLabel(rooms[activeRoom].name)}
                </h3>
                <div className="flex items-center gap-2">
                  {/* Duplicate button */}
                  {(rooms[activeRoom].duplicable || ROOM_TEMPLATES.find(t => rooms[activeRoom].name.replace(/\s+\d+$/, '') === t.name)?.duplicable) && (
                    <button
                      onClick={() => duplicateRoom(activeRoom)}
                      className={`flex items-center gap-1 text-xs font-medium px-2.5 py-1 rounded-lg transition-colors ${
                        isDark ? 'text-cyan-400 hover:bg-cyan-900/30' : 'text-cyan-600 hover:bg-cyan-50'
                      }`}
                    >
                      ⧉
                      <span className="hidden sm:inline">{t('rds_duplicate')}</span>
                    </button>
                  )}
                  <button
                    onClick={() => toggleRoom(activeRoom)}
                    className={`text-xs font-medium px-2.5 py-1 rounded-lg transition-colors ${
                      isDark ? 'text-red-400 hover:bg-red-900/30' : 'text-red-500 hover:bg-red-50'
                    }`}
                  >
                    {t('rds_remove')}
                  </button>
                </div>
              </div>

              {/* Mark remaining as Good */}
              {rooms[activeRoom].checkpoints.some(cp => !cp.condition) && (
                <button
                  onClick={() => markRemainingGood(activeRoom)}
                  className={`w-full mb-4 flex items-center justify-center gap-2 py-2.5 rounded-xl border-2 text-sm font-bold transition-colors ${
                    isDark
                      ? 'border-emerald-700 text-emerald-400 hover:bg-emerald-900/20'
                      : 'border-emerald-200 text-emerald-700 hover:bg-emerald-50'
                  }`}
                >

                  {t('rds_mark_remaining_good', { count: rooms[activeRoom].checkpoints.filter(cp => !cp.condition).length })}
                </button>
              )}

              <div className="space-y-3">
                {rooms[activeRoom].checkpoints.map((cp, cpIdx) => (
                  <div
                    key={cpIdx}
                    className={`rounded-xl border p-3 transition-colors ${
                      cp.condition === 'damaged'
                        ? isDark ? 'border-red-800 bg-red-900/20' : 'border-red-200 bg-red-50/50'
                        : cp.condition === 'poor'
                        ? isDark ? 'border-amber-800 bg-amber-900/20' : 'border-amber-200 bg-amber-50/50'
                        : isDark ? 'border-zinc-700 bg-zinc-800/50' : 'border-zinc-200 bg-white'
                    }`}
                  >
                    {/* Checkpoint label */}
                    <div className="flex items-center justify-between mb-2">
                      <input
                        type="text"
                        value={cp.label}
                        onChange={e => updateCheckpointLabel(activeRoom, cpIdx, e.target.value)}
                        className={`font-semibold text-sm bg-transparent outline-none flex-1 ${c.text}`}
                        placeholder={t('rds_item_to_check')}
                      />
                      <button
                        onClick={() => removeCheckpoint(activeRoom, cpIdx)}
                        className={`p-1 rounded-lg transition-colors ${isDark ? 'hover:bg-zinc-700 text-zinc-500' : 'hover:bg-zinc-100 text-zinc-400'}`}
                      >
                        ✕
                      </button>
                    </div>

                    {/* Condition buttons */}
                    <div className="flex flex-wrap gap-1.5 mb-2">
                      {CONDITION_OPTIONS.map(opt => (
                        <button
                          key={opt.value}
                          onClick={() => updateCheckpoint(activeRoom, cpIdx, 'condition', opt.value)}
                          className={`flex items-center gap-1 px-2.5 py-1 rounded-lg text-xs font-bold border transition-all ${
                            cp.condition === opt.value
                              ? `${isDark ? opt.dark : opt.light} ring-1 ring-offset-1 ${isDark ? 'ring-offset-zinc-800' : 'ring-offset-white'} ring-current`
                              : isDark ? 'border-zinc-600 text-zinc-400 hover:text-zinc-200'
                                : 'border-zinc-200 text-zinc-400 hover:text-gray-600'
                          }`}
                        >
                          <span className={`w-1.5 h-1.5 rounded-full ${cp.condition === opt.value ? opt.dot : isDark ? 'bg-zinc-600' : 'bg-zinc-300'}`} />
                          {CONDITION_LABELS[opt.value]}
                        </button>
                      ))}
                    </div>

                    {/* Notes */}
                    {(cp.condition === 'poor' || cp.condition === 'damaged' || cp.condition === 'fair' || cp.notes) && (
                      <textarea
                        value={cp.notes}
                        onChange={e => updateCheckpoint(activeRoom, cpIdx, 'notes', e.target.value)}
                        placeholder={
                          cp.condition === 'damaged'
                            ? t('rds_notes_damaged')
                            : cp.condition === 'poor'
                            ? t('rds_notes_poor')
                            : t('rds_notes_optional')
                        }
                        rows={2}
                        className={`w-full p-2.5 border rounded-lg text-xs outline-none focus:ring-2 resize-none transition-colors ${c.input}`}
                      />
                    )}
                  </div>
                ))}

                {/* Add checkpoint */}
                <button
                  onClick={() => addCheckpoint(activeRoom)}
                  className={`w-full flex items-center justify-center gap-1.5 py-2.5 rounded-xl border-2 border-dashed text-xs font-bold transition-colors ${
                    isDark
                      ? 'border-zinc-600 text-zinc-400 hover:border-cyan-600 hover:text-cyan-400'
                      : 'border-zinc-300 text-zinc-400 hover:border-cyan-400 hover:text-cyan-600'
                  }`}
                >

                  {t('rds_add_item')}
                </button>
              </div>
            </div>
          )}

          {/* Photo tips card */}
          <div className={`${c.card} border ${c.border} rounded-2xl shadow-sm p-4 sm:p-5`}>
            <div className="flex items-start gap-3">
              <span className={`flex-shrink-0 mt-0.5 ${isDark ? 'text-cyan-400' : 'text-cyan-600'}`}>📷</span>
              <div>
                <h4 className={`text-sm font-bold ${c.text} mb-1.5`}>{t('rds_photo_tips')}</h4>
                <div className={`text-xs ${c.textSecondary} space-y-1`}>
                  <p>{t('rds_photo_tip1')}</p>
                  <p>{t('rds_photo_tip2')}</p>
                  <p>{t('rds_photo_tip3')}</p>
                  <p>{t('rds_photo_tip4')}</p>
                </div>
              </div>
            </div>
          </div>

          {/* Cross-ref */}
          <p className={`text-xs text-center ${c.textMuted}`}>
            {t('rds_xref_walkthrough')} <a href="/LeaseTrapDetector" className={linkStyle}>🏠 {t('rds_lease_trap')}</a> {t('rds_xref_walkthrough_after')}
          </p>

          {/* Navigation */}
          <div className="flex items-center justify-end">
            <button
              onClick={() => setStep(2)}
              className={`flex items-center gap-2 px-6 py-3 rounded-xl font-bold ${c.btnPrimary} transition-colors min-h-[44px]`}
            >
              {t('rds_next_details')}
            </button>
          </div>
        </div>
      )}

      {/* ═══════════════════════════════════════════════════ */}
      {/* STEP 2: PROPERTY DETAILS                           */}
      {/* ═══════════════════════════════════════════════════ */}
      {step === 2 && (
        <div className={`${c.card} border ${c.border} rounded-2xl shadow-sm p-6 sm:p-8`}>
          <div className="flex items-center gap-2 mb-6">
            <span className={`${isDark ? 'text-cyan-400' : 'text-cyan-600'}`}>🏠</span>
            <h2 className={`text-xl font-bold ${c.text}`}>{t('rds_property_details')}</h2>
          </div>

          <div className="space-y-5">
            {/* Address */}
            <div>
              <label className={`block text-sm font-semibold ${c.text} mb-1.5`}>
                {t('rds_property_address')} <span className={c.required}>*</span>
              </label>
              <input
                type="text"
                value={address}
                onChange={e => setAddress(e.target.value)}
                placeholder={t('rds_address_ph')}
                className={`w-full p-3 border rounded-lg outline-none focus:ring-2 transition-colors ${c.input}`}
              />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {/* Unit */}
              <div>
                <label className={`block text-sm font-semibold ${c.text} mb-1.5`}>{t('rds_unit_apt')}</label>
                <input
                  type="text"
                  value={unit}
                  onChange={e => setUnit(e.target.value)}
                  placeholder={t('rds_unit_ph')}
                  className={`w-full p-3 border rounded-lg outline-none focus:ring-2 transition-colors ${c.input}`}
                />
              </div>

              {/* Move-in date (defaults to today) */}
              <div>
                <label className={`block text-sm font-semibold ${c.text} mb-1.5`}>
                  {t('rds_move_in_date')} <span className={c.required}>*</span>
                </label>
                <input
                  type="date"
                  value={moveInDate}
                  onChange={e => setMoveInDate(e.target.value)}
                  className={`w-full p-3 border rounded-lg outline-none focus:ring-2 transition-colors ${c.input}`}
                />
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {/* Location display (set in step 1) */}
              <div>
                <label className={`block text-sm font-semibold ${c.text} mb-1.5`}>
                  {t('rds_location')} <span className={c.required}>*</span>
                </label>
                <div className={`flex items-center gap-2 p-3 border rounded-lg ${isDark ? 'bg-zinc-700/50 border-zinc-600' : 'bg-zinc-50 border-zinc-200'}`}>
                  <span className={`text-sm ${locationValid ? c.text : isDark ? 'text-red-400' : 'text-red-600'}`}>
                    {locationValid ? locationString : t('rds_set_location_step1')}
                  </span>
                  {!locationValid && (
                    <button onClick={() => setStep(1)} className="text-xs font-bold text-cyan-600 hover:underline ms-auto">{t('rds_edit')}</button>
                  )}
                </div>
              </div>

              {/* Deposit amount */}
              <div>
                <label className={`block text-sm font-semibold ${c.text} mb-1.5`}>{t('rds_deposit_amount')}</label>
                <input
                  type="text"
                  value={depositAmount}
                  onChange={e => setDepositAmount(e.target.value)}
                  placeholder={t('rds_deposit_ph', { sym })}
                  className={`w-full p-3 border rounded-lg outline-none focus:ring-2 transition-colors ${c.input}`}
                />
              </div>
            </div>

            <div className={`border-t ${isDark ? 'border-zinc-700' : 'border-zinc-200'} pt-5`}>
              <p className={`text-xs font-bold uppercase tracking-wider ${c.textMuteded} mb-3`}>{t('rds_landlord_optional')}</p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className={`block text-sm font-medium ${c.textSecondary} mb-1.5`}>{t('rds_name')}</label>
                  <input
                    type="text"
                    value={landlordName}
                    onChange={e => setLandlordName(e.target.value)}
                    placeholder={t('rds_name_ph')}
                    className={`w-full p-3 border rounded-lg outline-none focus:ring-2 transition-colors ${c.input}`}
                  />
                </div>
                <div>
                  <label className={`block text-sm font-medium ${c.textSecondary} mb-1.5`}>{t('rds_email')}</label>
                  <input
                    type="email"
                    value={landlordEmail}
                    onChange={e => setLandlordEmail(e.target.value)}
                    placeholder={t('rds_email_ph')}
                    className={`w-full p-3 border rounded-lg outline-none focus:ring-2 transition-colors ${c.input}`}
                  />
                </div>
              </div>
            </div>
          </div>

          {/* Navigation */}
          <div className="mt-8 flex items-center justify-between">
            <button
              onClick={() => setStep(1)}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold transition-colors ${
                isDark ? 'text-zinc-300 hover:bg-zinc-700' : 'text-gray-600 hover:bg-zinc-100'
              }`}
            >
              {t('back')}
            </button>
            <button
            onClick={generateReport}
            disabled={streamLoading || !step2Valid}
            className={`flex items-center gap-2 px-6 py-3 rounded-xl font-bold ${c.btnPrimary} disabled:opacity-40 transition-colors min-h-[48px]`}
            >
            {streamLoading ? (
              <>
                <span className="inline-block animate-spin">{tool?.icon ?? '🏦'}</span>
                {t('rds_generating')}
              </>
            ) : (
              <><span>{tool?.icon ?? '🏦'}</span> {t('rds_generate_report')}</>
            )}
            </button>
          </div>

          {error && (
            <div className={`mt-4 p-4 rounded-xl border flex items-start gap-3 ${c.danger}`}>
              <p className="text-sm">{error}</p>
            </div>
          )}
        </div>
      )}

      {/* ═══════════════════════════════════════════════════ */}
      {/* STEP 3: GENERATED RESULTS                          */}
      {/* ═══════════════════════════════════════════════════ */}
      {step === 3 && results && (
        <div className="space-y-4" ref={resultsRef}>
          {/* Section tabs — hidden on print so all sections flow cleanly */}
          <div className={`${c.card} border ${c.border} rounded-2xl shadow-sm p-3 flex flex-wrap items-center gap-1.5 print:hidden`}>
            {streamLoading && (
              <span className={`flex items-center gap-1.5 text-xs font-semibold me-2 ${isDark ? 'text-cyan-400' : 'text-cyan-600'}`}>
                <span className="inline-block animate-spin">{tool?.icon ?? '🏦'}</span>
                {t('rds_generating')}
              </span>
            )}
            {[
              { key: 'report', label: t('rds_tab_condition'), icon: '📋' },
              { key: 'letter', label: t('rds_tab_letter'), icon: '📄' },
              { key: 'photos', label: t('rds_tab_photos'), icon: '📷' },
              { key: 'rights', label: t('rds_tab_rights'), icon: '⚖️' },
            ].map(({ key, label, icon }) => (
              <button
                key={key}
                onClick={() => setExpandedSection(key)}
                className={`flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-bold transition-colors ${
                  expandedSection === key
                    ? 'bg-cyan-600 text-white shadow-md'
                    : isDark ? 'text-zinc-300 hover:bg-zinc-700' : 'text-gray-600 hover:bg-zinc-100'
                }`}
              >
                <span>{icon}</span>
                <span className="hidden sm:inline">{label}</span>
              </button>
            ))}
          </div>

          {/* ── Condition Report ── always in DOM; hidden on screen when not active; print:block shows all */}
          {results.condition_report ? (
            <div className={`${c.card} border ${c.border} rounded-2xl shadow-sm p-5 sm:p-6 ${expandedSection !== 'report' ? 'hidden print:block' : ''}`}>
              <div className="mb-4">
                <h3 className={`text-xl font-bold ${c.text} flex items-center gap-2`}>
                  <span className={`${isDark ? 'text-cyan-400' : 'text-cyan-600'}`}>📋</span>
                  {t('rds_condition_report')}
                </h3>
                <p className={`text-xs ${c.textMuteded} mt-1`}>{t('rds_condition_sub')}</p>
              </div>
              <div className={`rounded-xl border p-5 text-sm leading-relaxed whitespace-pre-wrap font-mono ${
                isDark ? 'bg-zinc-900 border-zinc-700 text-zinc-200' : 'bg-zinc-50 border-zinc-200 text-gray-800'
              }`}>
                {results.condition_report}
              </div>
            </div>
          ) : streamLoading && expandedSection === 'report' ? (
            <SectionSkeleton isDark={isDark} c={c} />
          ) : null}

          {/* ── Landlord Letter ── */}
          {results.landlord_letter ? (
            <div className={`${c.card} border ${c.border} rounded-2xl shadow-sm p-5 sm:p-6 ${expandedSection !== 'letter' ? 'hidden print:block' : ''}`}>
              <div className="mb-4">
                <h3 className={`text-xl font-bold ${c.text} flex items-center gap-2`}>
                  <span>📄</span>
                  {t('rds_landlord_letter')}
                </h3>
                <p className={`text-xs ${c.textMuteded} mt-1`}>{t('rds_landlord_letter_sub')}</p>
              </div>
              <div className={`rounded-xl border p-5 text-sm leading-relaxed whitespace-pre-wrap ${
                isDark ? 'bg-zinc-900 border-zinc-700 text-zinc-200' : 'bg-zinc-50 border-zinc-200 text-gray-800'
              }`}>
                {results.landlord_letter}
              </div>
            </div>
          ) : streamLoading && expandedSection === 'letter' ? (
            <SectionSkeleton isDark={isDark} c={c} />
          ) : null}

          {/* ── Photo Shot List ── */}
          {results.photo_shot_list ? (
            <div className={`${c.card} border ${c.border} rounded-2xl shadow-sm p-5 sm:p-6 ${expandedSection !== 'photos' ? 'hidden print:block' : ''}`}>
              <div className="mb-4">
                <h3 className={`text-xl font-bold ${c.text} flex items-center gap-2`}>
                  <span>📷</span>
                  {t('rds_photo_shot_list')}
                </h3>
                <p className={`text-xs ${c.textMuteded} mt-1`}>{t('rds_photo_shot_list_sub')}</p>
              </div>
              <div className={`rounded-xl border p-5 text-sm leading-relaxed whitespace-pre-wrap ${
                isDark ? 'bg-zinc-900 border-zinc-700 text-zinc-200' : 'bg-zinc-50 border-zinc-200 text-gray-800'
              }`}>
                {results.photo_shot_list}
              </div>
            </div>
          ) : streamLoading && expandedSection === 'photos' ? (
            <SectionSkeleton isDark={isDark} c={c} />
          ) : null}

          {/* ── Your Rights ── */}
          {results.deposit_rights ? (
            <div className={`${c.card} border ${c.border} rounded-2xl shadow-sm p-5 sm:p-6 ${expandedSection !== 'rights' ? 'hidden print:block' : ''}`}>
              <div className="mb-4">
                <h3 className={`text-xl font-bold ${c.text} flex items-center gap-2`}>
                  <span className={`${isDark ? 'text-cyan-400' : 'text-cyan-600'}`}>⚖️</span>
                  {t('rds_your_rights')}
                </h3>
                <p className={`text-xs ${c.textMuteded} mt-1`}>{t('rds_your_rights_sub', { loc: locationString })}</p>
              </div>
              <div className={`rounded-xl border p-5 text-sm leading-relaxed whitespace-pre-wrap ${
                isDark ? 'bg-zinc-900 border-zinc-700 text-zinc-200' : 'bg-zinc-50 border-zinc-200 text-gray-800'
              }`}>
                {results.deposit_rights}
              </div>
              <div className={`mt-4 p-3 rounded-lg text-xs ${isDark ? 'bg-amber-900/20 text-amber-300' : 'bg-amber-50 text-amber-800'}`}>
                <strong>{t('rds_rights_note_label')}</strong> {t('rds_rights_note')}
              </div>
            </div>
          ) : streamLoading && expandedSection === 'rights' ? (
            <SectionSkeleton isDark={isDark} c={c} />
          ) : null}

          {/* Move-out reminder */}
          {results.move_out_tips ? (
            <div className={`${c.card} border ${c.border} rounded-2xl shadow-sm p-5`}>
              <div className="flex items-start gap-3">
                <span>💡</span>
                <div>
                  <h4 className={`text-sm font-bold ${c.text} mb-1.5`}>{t('rds_when_move_out')}</h4>
                  <div className={`text-xs ${c.textSecondary} whitespace-pre-wrap leading-relaxed`}>
                    {results.move_out_tips}
                  </div>
                </div>
              </div>
            </div>
          ) : streamLoading ? (
            <div className={`${c.card} border ${c.border} rounded-2xl shadow-sm p-5 animate-pulse`}>
              <div className="flex items-start gap-3">
                <div className={`w-5 h-5 rounded-full ${isDark ? 'bg-zinc-700' : 'bg-zinc-200'}`} />
                <div className="flex-1 space-y-2">
                  <div className={`h-3.5 w-36 rounded ${isDark ? 'bg-zinc-700' : 'bg-zinc-200'}`} />
                  <div className={`h-3 w-64 rounded ${isDark ? 'bg-zinc-700' : 'bg-zinc-300'}`} />
                </div>
              </div>
            </div>
          ) : null}

          {/* Cross-references */}
          <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
            <p className={`text-xs font-bold ${c.textMuted} uppercase tracking-wide mb-3`}>🔗 {t('rds_related')}</p>
            <div className="flex flex-wrap gap-3">
              <a href="/LeaseTrapDetector"         className={`text-xs ${linkStyle}`}>🏠 {t('rds_lease_trap')}</a>
              <a href="/ComplaintEscalationWriter" className={`text-xs ${linkStyle}`}>📝 {t('rds_complaint_writer')}</a>
            </div>
          </div>

          {/* Navigation — Edit Walkthrough goes back to step 1; reset is in header */}
          <div className="flex items-center print:hidden">
            <button
              onClick={() => setStep(1)}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold transition-colors ${
                isDark ? 'text-zinc-300 hover:bg-zinc-800' : 'text-gray-600 hover:bg-white'
              }`}
            >
              {t('rds_edit_walkthrough')}
            </button>
          </div>
        </div>
      )}
      {/* ── Past Reports ── */}
      {sessionHistory.length > 0 && (
        <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
          <p className={`text-xs font-bold ${c.textMuted} uppercase tracking-wide mb-3`}>🕐 {t('rds_past_reports')}</p>
          <div className="space-y-2">
            {sessionHistory.map(h => (
              <div key={h.id} className={`flex items-center justify-between text-xs ${c.textSecondary}`}>
                <span className="truncate">{h.preview || t('rds_untitled')}</span>
                <span className={`ms-3 shrink-0 ${c.textMuted}`}>{formatDate(h.date, userLocale)}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

RentersDepositSaver.displayName = 'RentersDepositSaver';
export default RentersDepositSaver;
