import React, { useState, useEffect, useRef, useCallback } from 'react';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

// Noise-type → catalog key + badge color class. Labels are resolved via t().
const NOISE_TYPE_CONFIG = {
  marketing:            { key: 'svn_nt_marketing',      cls: 'amber' },
  methodology_problem:  { key: 'svn_nt_methodology',    cls: 'red' },
  cherry_picked:        { key: 'svn_nt_cherry',         cls: 'red' },
  outdated:             { key: 'svn_nt_outdated',       cls: 'zinc' },
  oversimplified:       { key: 'svn_nt_oversimplified', cls: 'amber' },
  ideology:             { key: 'svn_nt_ideology',       cls: 'cyan' },
  individual_variation: { key: 'svn_nt_variation',      cls: 'cyan' },
  media_distortion:     { key: 'svn_nt_media',          cls: 'sky' },
};

const SignalVsNoise = ({ tool }) => {
  const { isDark } = useTheme();
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { t } = useTranslation();


  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-400' : 'text-gray-500',
    required:      isDark ? 'text-amber-400' : 'text-amber-700',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-200 text-red-800',
    // Bespoke keys
    signalBg:      isDark ? 'bg-emerald-900/20 border-emerald-700/50' : 'bg-emerald-50 border-emerald-200',
    signalText:    isDark ? 'text-emerald-300' : 'text-emerald-700',
    debatedText:   isDark ? 'text-sky-300' : 'text-sky-700',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  // Noise-type badge classes — resolved here so isDark is in scope
  const noiseClsMap = {
    amber: isDark ? 'bg-amber-900/30 border-amber-600/50 text-amber-300' : 'bg-amber-50 border-amber-300 text-amber-800',
    red:   isDark ? 'bg-red-900/30 border-red-700/50 text-red-300'       : 'bg-red-50 border-red-300 text-red-800',
    zinc:  isDark ? 'bg-zinc-700/60 border-zinc-600 text-zinc-300'       : 'bg-gray-100 border-gray-300 text-gray-600',
    cyan:  isDark ? 'bg-cyan-900/30 border-cyan-700/50 text-cyan-300'    : 'bg-cyan-50 border-cyan-300 text-cyan-800',
    sky:   isDark ? 'bg-sky-900/30 border-sky-700/50 text-sky-300'       : 'bg-sky-50 border-sky-300 text-sky-800',
  };

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';

  // Example topics — localized; loaded into the form by loadExample().
  const EXAMPLE_TOPICS = [
    { topic: t('svn_ex1_topic'), conflict: t('svn_ex1_conflict') },
    { topic: t('svn_ex2_topic'), conflict: t('svn_ex2_conflict') },
    { topic: t('svn_ex3_topic'), conflict: t('svn_ex3_conflict') },
    { topic: t('svn_ex4_topic'), conflict: t('svn_ex4_conflict') },
    { topic: t('svn_ex5_topic'), conflict: t('svn_ex5_conflict') },
  ];

  const [topic, setTopic] = useState('');
  const [conflictingAdvice, setConflictingAdvice] = useState('');
  const [userContext, setUserContext] = useState('');
  const [results, setResults] = usePersistentState('signalvsnoise-result', null);
  const [sessionHistory, setSessionHistory] = usePersistentState('signalvsnoise-history', []);
  const [error, setError] = useState('');
  const [expanded, setExpanded] = useState({ noise: true, debated: false, sources: false });

  const toggle = (k) => setExpanded(p => ({ ...p, [k]: !p[k] }));

  const handleSubmit = async () => {
    if (!topic.trim()) return;
    setError(''); setResults(null);
    try {
      const data = await callToolEndpoint('signal-vs-noise', {
        topic: topic.trim(),
        conflictingAdvice: conflictingAdvice.trim() || undefined,
        userContext: userContext.trim() || undefined,
        userLocale, userCurrency, userRegion,
      });
      setResults(data);
      // PF-25 exception: 40-char preview-text truncation; session history is capped at 6.
      setSessionHistory(prev => [{ id: Date.now(), date: new Date().toISOString(), preview: (topic || '').slice(0, 40) }, ...prev].slice(0, 6));
    } catch (e) { setError(e.message || t('svn_error')); }
  };

  const loadExample = () => {
    const ex = EXAMPLE_TOPICS[Math.floor(Math.random() * EXAMPLE_TOPICS.length)];
    setTopic(ex.topic);
    setConflictingAdvice(ex.conflict);
    setResults(null);
  };

  const buildText = useCallback(() => {
    if (!results) return '';
    let out = `${t('svn_copy_header')} ${results?.topic_as_understood}\n\n`;
    out += `${t('svn_copy_why_noisy')}\n${results?.why_this_field_is_noisy}\n\n`;
    out += `${t('svn_copy_signal')}\n`;
    results?.the_signal?.items?.forEach(s => { out += `• ${s.claim}\n  ${t('svn_copy_why_know')} ${s.why_we_know_this}\n`; });
    out += `\n${t('svn_copy_noise')}\n`;
    results?.the_noise?.forEach(n => { out += `• ${n.claim} [${n.noise_label}]\n  ${n.the_problem}\n`; });
    if (results?.genuinely_debated?.length) {
      out += `\n${t('svn_copy_debated')}\n`;
      results?.genuinely_debated?.forEach(d => { out += `• ${d.question}\n`; });
    }
    if (results?.the_bottom_line) {
      out += `\n${t('svn_copy_bottom')}\n${t('svn_copy_do')} ${results?.the_bottom_line?.what_to_do}\n${t('svn_copy_ignore')} ${results?.the_bottom_line?.what_to_ignore}\n`;
    }
    return out + BRAND;
  }, [results, t]);

  useRegisterActions(buildText(), tool?.title || 'Signal vs. Noise');

  const resultsRef = useRef(null);
  useEffect(() => {
    if (!results || !resultsRef.current) return;
    const timer = setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 200);
    return () => clearTimeout(timer);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [results]);

  const handleSubmitRef = useRef(null);
  const canSubmitRef = useRef(false);
  handleSubmitRef.current = handleSubmit;
  canSubmitRef.current = !!topic.trim();

  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && !loading && canSubmitRef.current)
        handleSubmitRef.current?.();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading]);

  return (
    <div className={`space-y-4 ${c.text}`}>

        {/* Input */}
        {!results && (
          <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5 space-y-4`}>
            <div className="pb-3 border-b border-zinc-500">
              <h2 className={`text-xl font-bold ${c.text}`}>
                <span className="me-2">{tool?.icon ?? '📡'}</span>{tool?.title ?? t('svn_title')}
              </h2>
              <p className={`text-sm ${c.textSecondary}`}>{tool?.tagline ?? t('svn_tagline')}</p>
              <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className={`mt-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium border disabled:opacity-40 ${isDark ? 'text-white border-white/40' : 'text-gray-800 border-transparent'}`}>{t('try_example')}</button>
            </div>
            <div>
              <p className={`text-xs ${c.textMuted} mb-2`}>
                {t('svn_xref_intro')} <a href="/ResearchDecoder" className={linkStyle}>📄 {t('svn_research_decoder')}</a> {t('svn_xref_intro_end')}
              </p>
              <label className={`block text-sm font-semibold mb-1.5 ${c.text}`}>{t('svn_topic_label')} <span className={c.required}>*</span></label>
              <input type="text" value={topic} onChange={e => setTopic(e.target.value)}
                placeholder={t('svn_topic_ph')}
                className={`w-full px-4 py-3 rounded-xl border text-sm ${c.input} `} />
            </div>
            <div>
              <label className={`block text-sm font-semibold mb-1.5 ${c.text}`}>{t('svn_conflict_label')} <span className={`font-normal ${c.textMuted}`}>{t('svn_conflict_hint')}</span></label>
              <textarea value={conflictingAdvice} onChange={e => setConflictingAdvice(e.target.value)}
                placeholder={t('svn_conflict_ph')}
                rows={3} maxLength={600}
                className={`w-full px-4 py-3 rounded-xl border text-sm resize-none ${c.input} `} />
            </div>
            <div>
              <label className={`block text-sm font-semibold mb-1.5 ${c.text}`}>{t('svn_context_label')} <span className={`font-normal ${c.textMuted}`}>{t('svn_context_hint')}</span></label>
              <input type="text" value={userContext} onChange={e => setUserContext(e.target.value)}
                placeholder={t('svn_context_ph')}
                className={`w-full px-4 py-3 rounded-xl border text-sm ${c.input} `} />
            </div>
            {error && <div className={`p-3 rounded-xl border text-sm ${c.danger}`}><span className="me-1">⚠️</span>{error}</div>}
            <button onClick={handleSubmit} disabled={loading || !topic.trim()}
              className={`w-full py-3 rounded-xl font-bold disabled:opacity-40 ${c.btnPrimary}`}>
              {loading ? <><span className="inline-block animate-spin">{tool?.icon ?? '📡'}</span>{t('svn_separating')}</> : t('svn_find_signal')}
            </button>
          </div>
        )}

        {/* Results */}
        {results && (
          <div ref={resultsRef} className="space-y-4">

            {/* Topic + why noisy */}
            <div className={`rounded-xl border ${c.border} p-5 ${c.card}`}>
              <p className={`text-xs font-bold uppercase tracking-wider mb-1 ${c.textMuted}`}>{t('svn_analyzing')}</p>
              <p className={`font-bold text-base mb-3 ${c.text}`}>{results?.topic_as_understood}</p>
              <p className={`text-xs font-bold uppercase tracking-wider mb-1 ${c.textMuted}`}>{t('svn_why_noisy')}</p>
              <p className={`text-sm leading-relaxed ${c.textSecondary}`}>{results?.why_this_field_is_noisy}</p>
            </div>

            {/* THE SIGNAL */}
            {results?.the_signal?.items?.length > 0 && (
              <div className={`rounded-2xl border p-5 ${c.signalBg}`}>
                <p className={`text-xs font-black uppercase tracking-widest mb-3 ${c.signalText}`}>{t('svn_signal_header')}</p>
                <div className="space-y-4">
                  {results?.the_signal?.items.map((item, i) => (
                    <div key={i} className={`p-4 rounded-xl ${isDark ? 'bg-zinc-900/60' : 'bg-white/80'}`}>
                      <p className={`text-sm font-semibold mb-1 ${c.text}`}>{item.claim}</p>
                      <p className={`text-xs mb-1 ${c.textMuted}`}>
                        <span className="font-semibold">{t('svn_why_we_know')}</span> {item.why_we_know_this}
                      </p>
                      {item.the_nuance && (
                        <p className={`text-xs italic mt-1 ${c.textMuted}`}>{t('svn_nuance')} {item.the_nuance}</p>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* THE NOISE */}
            {results?.the_noise?.length > 0 && (
              <div className={`rounded-xl border ${c.border} overflow-hidden ${c.card}`}>
                <button onClick={() => toggle('noise')} className="w-full text-start px-5 py-4 flex items-center justify-between">
                  <p className={`text-xs font-black uppercase tracking-widest ${isDark ? 'text-amber-300' : 'text-amber-700'}`}>
                    {t('svn_noise_header_a')} {results?.the_noise?.length} {t('svn_noise_header_b')}
                  </p>
                  <span className={`text-sm ${c.textMuted}`}>{expanded.noise ? '▲' : '▼'}</span>
                </button>
                {expanded.noise && (
                  <div className={`border-t ${c.border}`}>
                    {results?.the_noise?.map((item, i) => {
                      const cfg = NOISE_TYPE_CONFIG[item.noise_type] || NOISE_TYPE_CONFIG.oversimplified;
                      return (
                        <div key={i} className={`px-5 py-4 ${i > 0 ? `border-t ${c.border}` : ''}`}>
                          <div className="flex items-start gap-2 mb-2 flex-wrap">
                            <span className={`text-xs font-bold px-2 py-0.5 rounded-full border ${noiseClsMap[cfg.cls] || noiseClsMap.zinc}`}>{t(cfg.key)}</span>
                          </div>
                          <p className={`text-sm font-semibold mb-1 ${c.text}`}>"{item.claim}"</p>
                          <p className={`text-sm ${c.textSecondary}`}>{item.the_problem}</p>
                          {item.kernel_of_truth && (
                            <p className={`text-xs mt-2 ${c.textMuted}`}><span className="font-semibold">{t('svn_kernel')}</span> {item.kernel_of_truth}</p>
                          )}
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>
            )}

            {/* GENUINELY DEBATED */}
            {results?.genuinely_debated?.length > 0 && (
              <div className={`rounded-xl border ${c.border} overflow-hidden ${c.card}`}>
                <button onClick={() => toggle('debated')} className="w-full text-start px-5 py-4 flex items-center justify-between">
                  <p className={`text-xs font-black uppercase tracking-widest ${c.debatedText}`}>
                    {t('svn_debated_header_a')} {results?.genuinely_debated?.length} {t('svn_debated_header_b')}
                  </p>
                  <span className={`text-sm ${c.textMuted}`}>{expanded.debated ? '▲' : '▼'}</span>
                </button>
                {expanded.debated && (
                  <div className={`border-t ${c.border}`}>
                    {results?.genuinely_debated?.map((item, i) => (
                      <div key={i} className={`px-5 py-4 ${i > 0 ? `border-t ${c.border}` : ''}`}>
                        <p className={`text-sm font-semibold mb-2 ${c.text}`}>{item.question}</p>
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                          <div className={`p-2.5 rounded-lg text-xs ${c.signalBg}`}>
                            <p className={`font-bold mb-1 ${c.signalText}`}>{t('svn_one_view')}</p>
                            <p className={c.textSecondary}>{item.side_a}</p>
                          </div>
                          <div className={`p-2.5 rounded-lg text-xs ${isDark ? 'bg-amber-900/20 border border-amber-700/30' : 'bg-amber-50 border border-amber-200'}`}>
                            <p className={`font-bold mb-1 ${isDark ? 'text-amber-300' : 'text-amber-700'}`}>{t('svn_another_view')}</p>
                            <p className={c.textSecondary}>{item.side_b}</p>
                          </div>
                        </div>
                        {item.why_unsettled && (
                          <p className={`text-xs mt-2 italic ${c.textMuted}`}>{t('svn_why_unsettled')} {item.why_unsettled}</p>
                        )}
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}

            {/* THE BOTTOM LINE */}
            {results?.the_bottom_line && (
              <div className={`rounded-2xl border-2 p-5 space-y-3 ${isDark ? 'border-cyan-700 bg-cyan-900/20' : 'border-cyan-600 bg-cyan-50'}`}>
                <p className={`text-xs font-black uppercase tracking-widest ${isDark ? 'text-cyan-300' : 'text-cyan-800'}`}>{t('svn_bottom_line')}</p>
                {results?.the_bottom_line?.what_to_do && (
                  <div>
                    <p className={`text-xs font-bold uppercase tracking-wide mb-1 ${c.signalText}`}>{t('svn_what_evidence')}</p>
                    <p className={`text-sm ${c.textSecondary}`}>{results?.the_bottom_line?.what_to_do}</p>
                  </div>
                )}
                {results?.the_bottom_line?.what_to_ignore && (
                  <div>
                    <p className={`text-xs font-bold uppercase tracking-wide mb-1 ${isDark ? 'text-amber-300' : 'text-amber-700'}`}>{t('svn_what_ignore')}</p>
                    <p className={`text-sm ${c.textSecondary}`}>{results?.the_bottom_line?.what_to_ignore}</p>
                  </div>
                )}
                {results?.the_bottom_line?.the_honest_uncertainty && (
                  <div>
                    <p className={`text-xs font-bold uppercase tracking-wide mb-1 ${c.textMuted}`}>{t('svn_honest_uncertainty')}</p>
                    <p className={`text-sm ${c.textSecondary}`}>{results?.the_bottom_line?.the_honest_uncertainty}</p>
                  </div>
                )}
              </div>
            )}

            {/* NOISE SOURCES */}
            {results?.sources_of_noise?.length > 0 && (
              <div className={`rounded-xl border ${c.border} overflow-hidden ${c.card}`}>
                <button onClick={() => toggle('sources')} className="w-full text-start px-5 py-4 flex items-center justify-between">
                  <p className={`text-xs font-bold uppercase tracking-wider ${c.textMuted}`}>{t('svn_sources_header')}</p>
                  <span className={`text-sm ${c.textMuted}`}>{expanded.sources ? '▲' : '▼'}</span>
                </button>
                {expanded.sources && (
                  <div className={`border-t ${c.border}`}>
                    {results?.sources_of_noise?.map((src, i) => (
                      <div key={i} className={`px-5 py-4 ${i > 0 ? `border-t ${c.border}` : ''}`}>
                        <p className={`text-sm font-semibold mb-0.5 ${c.text}`}>{src.actor}</p>
                        <p className={`text-xs mb-1 ${c.textMuted}`}><span className="font-semibold">{t('svn_incentive')}</span> {src.incentive}</p>
                        <p className={`text-xs ${c.textMuted}`}><span className="font-semibold">{t('svn_how_to_spot')}</span> {src.how_to_spot_it}</p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}

            {/* Actions */}
            <div className="flex items-center gap-3 flex-wrap">
              <button onClick={() => { setResults(null); setTopic(''); setConflictingAdvice(''); setUserContext(''); }}
                className={`px-4 py-2 rounded-lg text-sm font-medium ${c.btnSecondary}`}>
                {t('svn_new_topic')}
              </button>
            </div>

            {/* Cross-references */}
            <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
              <p className={`text-[10px] font-bold ${c.textMuted} uppercase mb-2`}>{t('svn_related')}</p>
              <div className="flex flex-wrap gap-3">
                <a href="/BeliefStressTest" className={`text-xs ${linkStyle}`}>🧪 {t('svn_belief_stress_test')}</a>
                <a href="/TheFinalWord" className={`text-xs ${linkStyle}`}>⚖️ {t('svn_the_final_word')}</a>
                <a href="/FutureProof" className={`text-xs ${linkStyle}`}>🔮 {t('svn_future_proof')}</a>
              </div>
            </div>
          </div>
        )}

      {/* eslint-disable-next-line no-restricted-globals */}
      {sessionHistory.length > 0 && (<div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}><p className={`text-xs font-bold ${c.textMuted} mb-2`}>{t('svn_recent')}</p><div className="space-y-1">{sessionHistory.map(s => (<div key={s.id} className="flex items-center justify-between"><span className={`text-xs ${c.textSecondary} truncate`}>{s.preview||t('svn_session')}</span><span className={`text-xs ${c.textMuted} ms-2`}>{new Date(s.date).toLocaleDateString()}</span></div>))}</div></div>)}
    </div>
  );
};

SignalVsNoise.displayName = 'SignalVsNoise';
export default SignalVsNoise;
