import React, { useState, useEffect, useRef } from 'react';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';
import { pickExample } from '../utils/exampleRotation';
import { useScrollToSection } from '../hooks/useScrollToSection';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

const SmallChangeBigDifference = ({ tool }) => {
  const { isDark } = useTheme();
  const { callToolEndpointStreaming, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { t } = useTranslation();

  const EXAMPLES = [
    {
      routine: t('op_ex1_routine'),
      goals: t('op_ex1_goals'),
      pain: t('op_ex1_pain'),
    },
    {
      routine: t('op_ex2_routine'),
      goals: t('op_ex2_goals'),
      pain: t('op_ex2_pain'),
    },
  ];

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-400' : 'text-gray-500',
    required:      isDark ? 'text-amber-400' : 'text-amber-700',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    // Waiting for input: an outline, not a smudge. Empty fill keeps "filled"
    // meaning "ready"; the border and label carry the visibility. Important
    // modifiers because tools carry their own border/text utilities on the
    // submit and Tailwind resolves conflicts by stylesheet order, not class
    // order. See the PF-13 exception in audit/audit_v2-3-2.py.
    btnIdle:       isDark ? '!bg-transparent !border-2 !border-cyan-500/85 !text-cyan-300 cursor-not-allowed'
                          : '!bg-transparent !border-2 !border-cyan-600/85 !text-cyan-800 cursor-not-allowed',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-200 text-red-800',
    greenBg:       isDark ? 'bg-emerald-900/20 border-emerald-700' : 'bg-emerald-50 border-emerald-300',
    greenText:     isDark ? 'text-emerald-300' : 'text-emerald-800',
    navyBg:        isDark ? 'bg-sky-900/20 border-sky-700' : 'bg-sky-50 border-sky-300',
    navyText:      isDark ? 'text-sky-300' : 'text-sky-800',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';

  const [routine, setRoutine] = useState('');
  const [goals, setGoals] = useState('');
  const [painPoints, setPainPoints] = useState('');
  const [error, setError] = useState('');
  const [streamStage, setStreamStage] = useState('');
  // -v2: the result shape changed completely in the Small Change, Big
  // Difference rewrite (routine_diagnosis/the_one_change/the_year_from_now
  // → what_i_notice/change_to_try/why_not_start_elsewhere/what_to_watch_for).
  const [results, setResults] = usePersistentState('onepercenter-result-v2', null);
  const [sessionHistory, setSessionHistory] = usePersistentState('onepercenter-history', []);

  const getStreamStage = (text) => {
    if (text.includes('"what_to_watch_for"'))       return t('op_stage_watch');
    if (text.includes('"why_not_start_elsewhere"'))  return t('op_stage_alternatives');
    if (text.includes('"change_to_try"'))            return t('op_stage_change');
    if (text.includes('"what_i_notice"'))            return t('op_stage_notice');
    return t('op_stage_default');
  };

  // Reveal the answer when it arrives: frame the tool if its header fits,
  // otherwise put the answer on top. Focus moves either way.
  const revealRef = useRef(null);
  useScrollToSection(revealRef, results);

  const handleSubmit = async () => {
    if (!routine.trim()) return;
    setError(''); setResults(null); setStreamStage(t('op_stage_default'));
    callToolEndpointStreaming(
      'one-percenter',
      { routine: routine.trim(), goals: goals.trim() || undefined, painPoints: painPoints.trim() || undefined, userLocale, userCurrency, userRegion },
      {
        onChunk: (accumulated) => setStreamStage(getStreamStage(accumulated)),
        onDone: (finalText, serverParsed) => {
          setStreamStage('');
          try {
            let parsed = serverParsed;
            if (!parsed) {
              const start = finalText.indexOf('{');
              const end   = finalText.lastIndexOf('}');
              if (start === -1 || end === -1) throw new Error('No JSON object found in response');
              parsed = JSON.parse(finalText.slice(start, end + 1));
            }
            if (!parsed.what_i_notice || !parsed.change_to_try) {
              setError(t('op_err_analyze'));
            } else {
              setResults(parsed);
              // PF-25 exception: 40-char preview-text truncation; session history is capped at 6.
              setSessionHistory(prev => [{ id: Date.now(), date: new Date().toISOString(), preview: (routine || '').slice(0, 40) }, ...prev].slice(0, 6));
            }
          } catch (e) {
            console.error('[SmallChangeBigDifference] JSON parse failed:', e.message);
            console.error('[SmallChangeBigDifference] Raw text (first 500):', finalText.slice(0, 500));
            setError(t('op_err_parse'));
          }
        },
        onError: (msg) => { setStreamStage(''); setError(msg || t('op_err_generic')); },
      }
    );
  };


  const handleRef = useRef(handleSubmit);
  useEffect(() => { handleRef.current = handleSubmit; });

  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && !loading) handleRef.current();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, [loading]);

    const loadExample = () => {
    const ex = pickExample('SmallChangeBigDifference', EXAMPLES);
    setRoutine(ex.routine);
    setGoals(ex.goals || '');
    setPainPoints(ex.pain || '');
    setResults(null);
  };

  const buildText = () => {
    if (!results) return '';
    const ch = results?.change_to_try;
    let out = `⚡ ${t('op_copy_header')}\n\n`;
    out += `${t('op_copy_notice')}\n${results?.what_i_notice?.pattern}\n\n`;
    out += `${t('op_copy_change')}\n${ch?.change}\n\n`;
    if (ch?.what_it_may_change) out += `${t('op_copy_mechanism')}\n${ch.what_it_may_change}\n\n`;
    if (ch?.math) out += `${t('op_copy_math')} ${ch.math}\n\n`;
    out += `${t('op_copy_implement')}\n${ch?.how_to_try_it}\n\n`;
    if (results?.what_to_watch_for?.signs_it_is_helping?.length) {
      out += `${t('op_copy_watch')}\n`;
      results.what_to_watch_for.signs_it_is_helping.forEach(s => out += `  • ${s}\n`);
      out += '\n';
    }
    return out + BRAND;
  };

  useRegisterActions(buildText(), tool?.title || 'Small Change, Big Difference');

  return (
    <div className={`space-y-4 ${c.text}`}>

      <div className="max-w-2xl mx-auto">

        {/* Header */}
        <div className={`mb-4 pb-3 border-b ${c.border}`}>
          <div className="flex items-start justify-between gap-3">
            <div>
              {/* PF-30 — the wrapper already prints the name as the page <h1>. */}
              <p className={`text-base ${c.textSecondary}`}>
                <span className="me-2 text-lg">{tool?.icon ?? '⚡'}</span>{t('op_tagline')}
              </p>
              <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className="mt-2 px-4 py-2 rounded-full text-sm font-semibold border border-black/25 text-zinc-900 shadow-sm hover:brightness-105 hover:shadow transition disabled:opacity-40 whitespace-nowrap">✨ {t('try_example')}</button>
            </div>
            {(results || routine.trim()) && (
              <button onClick={() => { setResults(null); setRoutine(''); setGoals(''); setPainPoints(''); setError(''); }}
                className={`${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs font-bold flex-shrink-0`}>
                ↺ {t('start_over')}
              </button>
            )}
          </div>
        </div>

        {/* Input */}
        {!results && (
          <div className={`rounded-2xl border p-6 shadow-sm space-y-4 ${c.card} ${c.border}`}>
            <p className={`text-xs ${c.textMuted}`}>
              {t('op_xref_intro')} <a href="/BrainDumpBuddy" className={linkStyle}>🧠 {t('op_braindump')}</a> {t('op_braindump_after')}
            </p>
            <div>
              <label className={`block text-sm font-semibold mb-1.5 ${c.text}`}>
                {t('op_routine_label')} <span className={c.required}>*</span>
              </label>
              <textarea value={routine} onChange={e => setRoutine(e.target.value)}
                placeholder={t('op_routine_ph')}
                rows={5} maxLength={800}
                className={`w-full px-4 py-3 rounded-xl border text-sm resize-none ${c.input} `} />
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className={`block text-sm font-semibold mb-1.5 ${c.text}`}>{t('op_goals_label')} <span className={`font-normal ${c.textMuteded}`}>({t('optional')})</span></label>
                <input type="text" value={goals} onChange={e => setGoals(e.target.value)}
                  placeholder={t('op_goals_ph')}
                  className={`w-full px-4 py-3 rounded-xl border text-sm ${c.input} `} />
              </div>
              <div>
                <label className={`block text-sm font-semibold mb-1.5 ${c.text}`}>{t('op_pain_label')} <span className={`font-normal ${c.textMuteded}`}>({t('optional')})</span></label>
                <input type="text" value={painPoints} onChange={e => setPainPoints(e.target.value)}
                  placeholder={t('op_pain_ph')}
                  className={`w-full px-4 py-3 rounded-xl border text-sm ${c.input} `} />
              </div>
            </div>

            {error && <div className={`p-3 rounded-xl border text-sm ${c.danger}`}><span className="me-1">⚠️</span>{error}</div>}

            <div>
              <button title={t('cmd_enter')} onClick={handleSubmit} disabled={loading || !routine.trim()}
                className={`relative w-full py-3 rounded-xl font-bold ${(!routine.trim()) ? c.btnIdle : c.btnPrimary}`}>
                {loading
                  ? <><span className="inline-block animate-spin">{tool?.icon ?? '⚡'}</span> {streamStage || t('op_stage_default')}</>
                  : <><span>{tool?.icon ?? '⚡'}</span> {t('op_submit')}</>}
              {!loading && (
                <kbd aria-hidden="true"
                  className="hidden sm:flex items-center absolute end-3 top-1/2 -translate-y-1/2 px-1.5 py-0.5 rounded border border-white/30 bg-white/15 text-[10px] font-bold tracking-wide">
                  ⌘↵
                </kbd>
              )}
              </button>
            </div>
          </div>
        )}

        {/* Results */}
        {results && (
          <div ref={revealRef} className="scroll-mt-24 space-y-4">

            {/* What I Notice */}
            {results?.what_i_notice && (
              <div className={`rounded-2xl border p-5 ${c.card} ${c.border}`}>
                <p className={`text-xs font-black uppercase tracking-widest mb-3 ${c.textMuteded}`}>🔎 {t('op_notice_label')}</p>
                {results?.what_i_notice?.pattern && (
                  <p className={`text-sm leading-relaxed mb-2 ${c.textSecondary}`}>{results?.what_i_notice?.pattern}</p>
                )}
                {results?.what_i_notice?.why_it_matters && (
                  <p className={`text-sm ${c.textMuted}`}>{results?.what_i_notice?.why_it_matters}</p>
                )}
              </div>
            )}

            {/* THE SMALL CHANGE — hero card */}
            {results?.change_to_try && (
              <div className={`rounded-2xl border-2 overflow-hidden ${isDark ? 'border-cyan-800 bg-zinc-800' : 'border-cyan-800 bg-white'}`}>
                <div style={{ background: isDark ? 'linear-gradient(135deg, #1e2a3a, #2c4a6e)' : 'linear-gradient(135deg, #2c4a6e, #4a6a8a)' }}
                  className="px-6 py-5">
                  <p className="text-xs font-black uppercase tracking-widest text-white/70 mb-2">⚡ {t('op_the_change_label')}</p>
                  <h2 className="text-xl font-black text-white leading-snug">{results?.change_to_try?.change}</h2>
                </div>

                <div className="px-6 py-5 space-y-4">
                  {results?.change_to_try?.why_this_one && (
                    <div>
                      <p className={`text-xs font-bold uppercase tracking-wider mb-1 ${c.textMuteded}`}>{t('op_why_this_one')}</p>
                      <p className={`text-sm leading-relaxed ${c.textSecondary}`}>{results?.change_to_try?.why_this_one}</p>
                    </div>
                  )}

                  {results?.change_to_try?.how_to_try_it && (
                    <div>
                      <p className={`text-xs font-bold uppercase tracking-wider mb-1 ${c.textMuteded}`}>✅ {t('op_how_implement')}</p>
                      <p className={`text-sm ${c.textSecondary}`}>{results?.change_to_try?.how_to_try_it}</p>
                    </div>
                  )}

                  {results?.change_to_try?.what_it_may_change && (
                    <div>
                      <p className={`text-xs font-bold uppercase tracking-wider mb-1 ${c.textMuteded}`}>⚙️ {t('op_what_it_may_change')}</p>
                      <p className={`text-sm leading-relaxed ${c.textSecondary}`}>{results?.change_to_try?.what_it_may_change}</p>
                    </div>
                  )}

                  {results?.change_to_try?.math && (
                    <div className={`p-3 rounded-xl border font-mono ${c.navyBg}`}>
                      <p className={`text-xs font-bold uppercase tracking-wide mb-1 ${c.navyText}`}>📊 {t('op_the_math')}</p>
                      <p className={`text-sm font-semibold ${c.navyText}`}>{results?.change_to_try?.math}</p>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* Why not start somewhere else — optional */}
            {(results?.why_not_start_elsewhere?.alternatives || results?.why_not_start_elsewhere?.reason) && (
              <div className={`rounded-2xl border p-5 ${c.card} ${c.border}`}>
                <p className={`text-xs font-bold uppercase tracking-wider mb-3 ${c.textMuteded}`}>🤔 {t('op_but_what_about')}</p>
                {results?.why_not_start_elsewhere?.alternatives && (
                  <p className={`text-sm mb-2 ${c.textSecondary}`}>
                    <span className={`font-semibold ${c.text}`}>{t('op_tempted_to')}</span> {results?.why_not_start_elsewhere?.alternatives}
                  </p>
                )}
                {results?.why_not_start_elsewhere?.reason && (
                  <p className={`text-sm ${c.textSecondary}`}>
                    <span className={`font-semibold ${c.text}`}>{t('op_why_after')}</span> {results?.why_not_start_elsewhere?.reason}
                  </p>
                )}
              </div>
            )}

            {/* What to watch for */}
            {(results?.what_to_watch_for?.signs_it_is_helping?.length > 0 || results?.what_to_watch_for?.signs_to_rethink_it?.length > 0) && (
              <div className={`rounded-2xl border p-5 ${c.greenBg}`}>
                <p className={`text-xs font-black uppercase tracking-widest mb-3 ${c.greenText}`}>👀 {t('op_watch_for')}</p>
                {results?.what_to_watch_for?.signs_it_is_helping?.length > 0 && (
                  <div className="mb-3">
                    <p className={`text-xs font-bold uppercase tracking-wide mb-1 ${c.greenText}`}>{t('op_watch_helping')}</p>
                    <div className="space-y-1">
                      {results.what_to_watch_for.signs_it_is_helping.map((s, i) => (
                        <p key={i} className={`text-sm ${c.textSecondary}`}>• {s}</p>
                      ))}
                    </div>
                  </div>
                )}
                {results?.what_to_watch_for?.signs_to_rethink_it?.length > 0 && (
                  <div>
                    <p className={`text-xs font-bold uppercase tracking-wide mb-1 ${c.greenText}`}>{t('op_watch_rethink')}</p>
                    <div className="space-y-1">
                      {results.what_to_watch_for.signs_to_rethink_it.map((s, i) => (
                        <p key={i} className={`text-sm ${c.textSecondary}`}>• {s}</p>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}

            {/* Cross-references */}
            <div className={`rounded-xl border p-4 ${c.cardAlt} ${c.border}`}>
              <p className={`text-xs font-semibold uppercase tracking-wide mb-3 ${c.textMuteded}`}>{t('op_related')}</p>
              <div className="flex flex-wrap gap-2">
                {[
                  { id: 'ChaosPilot', icon: '🎰', label: t('op_xref_chaospilot') },
                  { id: 'PreMortem', icon: '💀', label: t('op_xref_premortem') },
                  { id: 'FutureProof', icon: '🔮', label: t('op_xref_futureproof') },
                ].map(r => (
                  <a key={r.id} href={`/${r.id}`}
                    className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${c.btnSecondary}`}>
                    {r.icon} {r.label}
                  </a>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>

      {/* eslint-disable-next-line no-restricted-globals */}
      {sessionHistory.length > 0 && (<div className={`${c.cardAlt} border ${c.border} rounded-xl p-4 mt-4`}><p className={`text-xs font-bold ${c.textMuted} mb-2`}>📋 {t('op_recent')}</p><div className="space-y-1">{sessionHistory.map(s => (<div key={s.id} className="flex items-center justify-between"><span className={`text-xs ${c.textSecondary} truncate`}>{s.preview||t('op_session')}</span><span className={`text-xs ${c.textMuted} ms-2`}>{new Date(s.date).toLocaleDateString()}</span></div>))}</div></div>)}
    </div>
  );
};

SmallChangeBigDifference.displayName = 'SmallChangeBigDifference';
export default SmallChangeBigDifference;
