import React, { useState, useRef, useCallback, useEffect, useMemo } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

// ════════════════════════════════════════════════════════════
// CONSTANTS — value keys are stable; visible labels resolved via t()
// ════════════════════════════════════════════════════════════
const MODES = [
  { value: 'distill',   emoji: '📋', labelKey: 'td_mode_distill',  descKey: 'td_mode_distill_desc' },
  { value: 'followup',  emoji: '📨', labelKey: 'td_mode_followup', descKey: 'td_mode_followup_desc' },
  { value: 'series',    emoji: '🔄', labelKey: 'td_mode_series',   descKey: 'td_mode_series_desc' },
];

const MEETING_TYPES = [
  { value: 'general',    labelKey: 'td_mt_general' },
  { value: 'standup',    labelKey: 'td_mt_standup' },
  { value: 'planning',   labelKey: 'td_mt_planning' },
  { value: 'retro',      labelKey: 'td_mt_retro' },
  { value: 'one_on_one', labelKey: 'td_mt_one_on_one' },
  { value: 'client',     labelKey: 'td_mt_client' },
  { value: 'brainstorm', labelKey: 'td_mt_brainstorm' },
];

const TONES = [
  { value: 'professional', labelKey: 'td_tone_professional' },
  { value: 'formal',       labelKey: 'td_tone_formal' },
  { value: 'casual',       labelKey: 'td_tone_casual' },
];

const PRI_BADGE = { high: '🔴', medium: '🟡', low: '🟢' };

// ════════════════════════════════════════════════════════════
// MAIN
// ════════════════════════════════════════════════════════════
const TheDebrief = ({ tool }) => {
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();

  const c = {
    card:         isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:      isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:        isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:         isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:    isDark ? 'text-zinc-400' : 'text-gray-500',
    required:      isDark ? 'text-amber-400' : 'text-amber-700',
    btnPrimary:   isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary: isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-100' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    btnDis:       isDark ? 'bg-zinc-700 text-zinc-500 cursor-not-allowed' : 'bg-gray-200 text-gray-400 cursor-not-allowed',
    border:       isDark ? 'border-zinc-700' : 'border-gray-200',
    success:      isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:      isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:       isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-200 text-red-800',
    pillActive:   isDark ? 'border-cyan-500 bg-cyan-900/30 text-cyan-200' : 'border-cyan-600 bg-cyan-100 text-cyan-900',
    pillInactive: isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500' : 'border-gray-300 text-gray-500 hover:border-gray-400',
    badge:        isDark ? 'bg-cyan-900/30 text-cyan-300' : 'bg-cyan-100 text-cyan-800',
    tipBg:        isDark ? 'bg-amber-900/20 border-amber-700' : 'bg-amber-50 border-amber-300',
    tipText:      isDark ? 'text-amber-300' : 'text-amber-800',
    successBox:   isDark ? 'bg-emerald-900/20 border-emerald-700' : 'bg-emerald-50 border-emerald-300',
    successTxt:   isDark ? 'text-emerald-300' : 'text-emerald-800',
    warningBox:   isDark ? 'bg-red-900/20 border-red-700' : 'bg-red-50 border-red-200',
    warningTxt:   isDark ? 'text-red-300' : 'text-red-700',
    infoBox:      isDark ? 'bg-sky-900/20 border-sky-700' : 'bg-sky-50 border-sky-200',
    infoTxt:      isDark ? 'text-sky-300' : 'text-sky-800',
    histBg:       isDark ? 'bg-sky-900/20 border-sky-700/30' : 'bg-sky-50 border-sky-200',
    highPri:      isDark ? 'bg-red-900/20 text-red-300' : 'bg-red-50 text-red-700',
    medPri:       isDark ? 'bg-amber-900/20 text-amber-300' : 'bg-amber-50 text-amber-700',
    lowPri:       isDark ? 'bg-emerald-900/20 text-emerald-300' : 'bg-emerald-50 text-emerald-700',
    labelText:    isDark ? 'text-zinc-200' : 'text-gray-700',
  };
  c.label = c.labelText;
  c.textMuteded = c.textMuted;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';

  const resultsRef = useRef(null);

  const meetingsInputRefs = useRef([]);
  const shouldFocusNewMeetingsRef = useRef(false);

  const [showHistory, setShowHistory] = useState(false);

  // Mode
  const [mode, setMode] = useState('distill');

  // Shared input
  const [transcript, setTranscript] = useState('');
  const [meetingType, setMeetingType] = useState('general');
  const [attendees, setAttendees] = useState('');
  const [context, setContext] = useState('');

  // Follow-up options
  const [tone, setTone] = useState('professional');

  // Series mode
  const [meetings, setMeetings] = useState([
    { title: '', date: '', transcript: '' },
    { title: '', date: '', transcript: '' },
  ]);
  const [sessionHistory, setSessionHistory] = usePersistentState('the-debrief-history', []);

  // Results
  const [results, setResults] = usePersistentState('the-debrief-results', null);
  const [error, setError] = useState('');
  const [expandedSections, setExpandedSections] = useState({});

  useEffect(() => {
    if (!results) return;
    const timer = setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 200);
    return () => clearTimeout(timer);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [results]);

  const charCount = useMemo(() => {
    if (mode === 'series') return meetings.reduce((sum, m) => sum + (m.transcript?.length || 0), 0);
    return transcript.length;
  }, [mode, transcript, meetings]);

  // Series helpers
  const addMeeting = useCallback(() => { if (meetings.length < 5) { shouldFocusNewMeetingsRef.current = true; setMeetings(p => [...p, { title: '', date: '', transcript: '' }]); }; }, [meetings.length]);
  const removeMeeting = useCallback((i) => { if (meetings.length > 2) setMeetings(p => p.filter((_, idx) => idx !== i)); }, [meetings.length]);
  const updateMeeting = useCallback((i, field, val) => setMeetings(p => p.map((m, idx) => idx === i ? { ...m, [field]: val } : m)), []);

  const toggleSection = useCallback((key) => setExpandedSections(prev => ({ ...prev, [key]: !prev[key] })), []);

  const canSubmit = mode === 'series'
    ? meetings.filter(m => m.transcript?.trim()).length >= 2
    : transcript.trim().length > 0;

  // ─── Keyboard shortcut ───
  useEffect(() => {
    const handler = (e) => {
      if (!(e.metaKey || e.ctrlKey) || e.key !== 'Enter') return;
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (!loading && canSubmit) submit();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading, canSubmit]);

  useEffect(() => {
    if (shouldFocusNewMeetingsRef.current) {
      const last = meetingsInputRefs.current[meetings.length - 1];
      if (last) last.focus();
      shouldFocusNewMeetingsRef.current = false;
    }
  }, [meetings.length]);

  // ── API ──
  const submit = useCallback(async () => {
    setError(''); setResults(null); setExpandedSections({});
    try {
      let data;
      if (mode === 'distill') {
        if (!transcript.trim()) { setError(t('td_err_paste')); return; }
        data = await callToolEndpoint('the-debrief', {
          transcript: transcript.trim(), meetingType, attendees: attendees.trim() || null,
          context: context.trim() || null,
          userLocale, userCurrency, userRegion,
        });
      } else if (mode === 'followup') {
        if (!transcript.trim()) { setError(t('td_err_paste')); return; }
        data = await callToolEndpoint('the-debrief/followup', {
          transcript: transcript.trim(), meetingType, attendees: attendees.trim() || null, tone,
          userLocale, userCurrency, userRegion,
        });
      } else if (mode === 'series') {
        const valid = meetings.filter(m => m.transcript?.trim());
        if (valid.length < 2) { setError(t('td_err_two_meetings')); return; }
        data = await callToolEndpoint('the-debrief/series', {
          meetings: valid.map(m => ({ title: m.title.trim() || null, date: m.date.trim() || null, transcript: m.transcript.trim() })),
          context: context.trim() || null,
          userLocale, userCurrency, userRegion,
        });
      }
      setResults(data);
      const entry = {
        id: 'db_' + Date.now(), date: new Date().toISOString(), mode,
        title: data?.meeting_summary?.substring(0, 50) || meetingType || mode,
        preview: (data?.meeting_summary || transcript || meetingType || mode).slice(0, 40),
        actions: data?.action_items?.length || 0,
      };
      setSessionHistory(prev => [entry, ...prev].slice(0, 6));
    } catch (err) { setError(err.message || t('td_err_failed')); }
  }, [mode, transcript, meetingType, attendees, context, tone, meetings, callToolEndpoint, setSessionHistory, setResults, userLocale, userCurrency, userRegion, t]);

  const loadExample = useCallback(() => {
    setMode('distill');
    setMeetingType('general');
    setAttendees(t('td_ex_attendees'));
    setContext(t('td_ex_context'));
    setTone('professional');
    setTranscript(t('td_ex_transcript'));
    setResults(null);
  }, [setMode, setMeetingType, setAttendees, setContext, setTone, setTranscript, setResults, t]);

  const handleReset = useCallback(() => {
    setTranscript(''); setAttendees(''); setContext('');
    setResults(null); setError(''); setExpandedSections({});
    setMeetings([{ title: '', date: '', transcript: '' }, { title: '', date: '', transcript: '' }]);
  }, []);

  const priBg = (p) => p === 'high' ? c.highPri : p === 'medium' ? c.medPri : c.lowPri;

  // ── Copy builders ──
  const buildDistillCopy = useCallback(() => {
    if (!results) return '';
    const lines = [t('td_copy_debrief'), '', results?.meeting_summary || '', ''];
    if (results?.decisions?.length) {
      lines.push(t('td_copy_decisions'));
      results?.decisions?.forEach((d, i) => lines.push(`${i + 1}. ${d.decision}`));
      lines.push('');
    }
    if (results?.action_items?.length) {
      lines.push(t('td_copy_actions'));
      results?.action_items?.forEach(a => lines.push(`• ${a.action} → ${a.owner} (${a.deadline})`));
      lines.push('');
    }
    if (results?.open_questions?.length) {
      lines.push(t('td_copy_questions'));
      results?.open_questions?.forEach(q => lines.push(`? ${q.question}`));
      lines.push('');
    }
    lines.push(BRAND);
    return lines.join('\n');
  }, [results, t]);

  const buildFollowupCopy = useCallback(() => {
    if (!results) return '';
    const lines = [t('td_copy_followups'), ''];
    if (results?.group_email) {
      lines.push(t('td_subject', { val: results?.group_email?.subject }), '', results?.group_email?.body, '');
    }
    lines.push(BRAND);
    return lines.join('\n');
  }, [results, t]);

  const buildSeriesCopy = useCallback(() => {
    if (!results) return '';
    const lines = [t('td_copy_debrief'), '', results?.series_summary || '', ''];
    if (results?.recurring_topics?.length) {
      lines.push('🔁');
      results.recurring_topics.forEach(r => lines.push(`• ${r.topic}${r.frequency ? ` (${r.frequency})` : ''}`));
      lines.push('');
    }
    if (results?.accountability_gaps?.length) {
      lines.push('⚠️');
      results.accountability_gaps.forEach(g => lines.push(`• ${g.action} — ${g.owner} [${g.status}]`));
      lines.push('');
    }
    if (results?.next_meeting_agenda?.length) {
      lines.push('📋');
      results.next_meeting_agenda.forEach(a => lines.push(`• ${a}`));
      lines.push('');
    }
    lines.push(BRAND);
    return lines.join('\n');
  }, [results, t]);

  const buildCopy = useCallback(() => {
    if (mode === 'distill') return buildDistillCopy();
    if (mode === 'followup') return buildFollowupCopy();
    if (mode === 'series') return buildSeriesCopy();
    return buildDistillCopy();
  }, [mode, buildDistillCopy, buildFollowupCopy, buildSeriesCopy]);

  // ─── Register export content ───
  useRegisterActions(results ? buildCopy() : '', tool?.title);

  // ── Shared ──
  const Pill = ({ active, onClick, children }) => (
    <button onClick={onClick} className={'px-3 py-1.5 rounded-lg border text-xs font-semibold transition-all ' + (active ? c.pillActive : c.pillInactive)}>
      {active && <span className="mr-1">✓</span>}{children}
    </button>
  );

  const Section = ({ title, emoji, sKey, badge, defaultOpen = false, children }) => {
    const open = expandedSections[sKey] ?? defaultOpen;
    return (
      <div className={c.card + ' border rounded-xl overflow-hidden'}>
        <button onClick={() => toggleSection(sKey)} className="w-full flex items-center justify-between p-4 text-left hover:opacity-80">
          <div className="flex items-center gap-2">
            <span className="text-base">{emoji}</span>
            <span className={'text-sm font-semibold ' + c.text}>{title}</span>
            {badge && <span className={'text-xs px-2 py-0.5 rounded-full ' + c.badge}>{badge}</span>}
          </div>
          <span className={'text-xs ' + c.textMuted}>{open ? '▲' : '▼'}</span>
        </button>
        {open && <div className={'px-4 pb-4 border-t ' + c.border}>{children}</div>}
      </div>
    );
  };

  // ════════════════════════════════════════════════════════════
  // INPUT
  // ════════════════════════════════════════════════════════════
  const renderInput = () => (
    <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5 space-y-4`}>
      <div className="pb-3 border-b border-zinc-500">
        <h2 className={'text-xl font-bold ' + c.text}>
          <span className="mr-2">{tool?.icon ?? '📋'}</span>{tool?.title ?? t('td_title')}
        </h2>
        <p className={'text-sm ' + c.textSecondary}>{tool?.tagline ?? t('td_tagline')}</p>
        <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className={`mt-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium border disabled:opacity-40 ${isDark ? 'text-white border-white/40' : 'text-gray-800 border-transparent'}`}>{t('try_example')}</button>
      </div>

      <div className="flex gap-1.5 overflow-x-auto pb-1">
        {MODES.map(m => (
          <button key={m.value} onClick={() => { setMode(m.value); setResults(null); setError(''); }}
            className={'flex items-center gap-2 px-4 py-3 rounded-xl border-2 transition-all flex-shrink-0 ' +
              (mode === m.value ? c.pillActive + ' border-2' : c.pillInactive)}>
            <span className="text-lg">{m.emoji}</span>
            <div className="text-left">
              <p className={'text-xs font-bold ' + (mode === m.value ? '' : c.textMuted)}>{t(m.labelKey)}</p>
              <p className={'text-[10px] ' + c.textMuted}>{t(m.descKey)}</p>
            </div>
          </button>
        ))}
      </div>

      {mode !== 'series' ? (
        <div>
          <p className={'text-xs ' + c.textMuted + ' mb-3'}>
            {t('td_xref_runthrough_q')} <a href="/TheRunthrough" className={linkStyle}>🎙️ {t('td_xref_runthrough')}</a> {t('td_xref_runthrough_tail')}
          </p>
          <label className={'text-base font-bold ' + c.text + ' mb-1 block'}>{t('td_paste_label')}</label>
          <p className={'text-xs ' + c.textMuted + ' mb-3'}>{t('td_paste_hint')}</p>
          <textarea value={transcript} onChange={e => setTranscript(e.target.value)}
            placeholder={t('td_paste_ph')}
            className={'w-full h-40 p-4 border-2 rounded-xl ' + c.input + ' outline-none focus:ring-2 resize-none text-sm font-mono'} />
          {charCount > 0 && (
            <p className={'text-xs ' + c.textMuted + ' mt-1'}>
              {t('td_charcount', { count: charCount.toLocaleString(), min: Math.round(charCount / 750) })}
            </p>
          )}
        </div>
      ) : (
        <div className="space-y-3">
          {meetings.map((mtg, idx) => (
            <div key={idx} className={c.card + ' border rounded-xl p-4'}>
              <div className="flex items-center gap-2 mb-2">
                <span className={'text-xs font-bold ' + c.badge + ' px-2 py-0.5 rounded-full'}>{t('td_meeting_n', { n: idx + 1 })}</span>
                <input ref={el => { meetingsInputRefs.current[idx] = el; }} type="text" value={mtg.title} onChange={e => updateMeeting(idx, 'title', e.target.value)}
                  placeholder={t('td_meeting_title_ph')}
                  className={'flex-1 px-3 py-1.5 rounded-lg border text-xs ' + c.input + ' outline-none'} />
                <input type="text" value={mtg.date} onChange={e => updateMeeting(idx, 'date', e.target.value)}
                  placeholder={t('td_meeting_date_ph')}
                  className={'w-28 px-3 py-1.5 rounded-lg border text-xs ' + c.input + ' outline-none'} />
                {meetings.length > 2 && (
                  <button onClick={() => removeMeeting(idx)} className={'text-xs px-2 py-1 rounded ' + c.warningTxt}>✕</button>
                )}
              </div>
              <textarea value={mtg.transcript} onChange={e => updateMeeting(idx, 'transcript', e.target.value)}
                placeholder={t('td_paste_transcript_ph')}
                className={'w-full h-24 p-3 border-2 rounded-xl ' + c.input + ' outline-none focus:ring-2 resize-none text-xs font-mono'} />
            </div>
          ))}
          {meetings.length < 5 && (
            <button onClick={addMeeting} className={'w-full py-3 rounded-xl border-2 border-dashed text-xs font-bold ' + c.pillInactive}>
              {t('td_add_meeting')}
            </button>
          )}
        </div>
      )}

      <div className={c.card + ' border rounded-xl p-5 space-y-3'}>
        <div>
          <label className={'text-xs font-bold ' + c.textSecondary + ' uppercase tracking-wide mb-2 block'}>{t('td_meeting_type')}</label>
          <div className="flex flex-wrap gap-1.5">
            {MEETING_TYPES.map(mt => <Pill key={mt.value} active={meetingType === mt.value} onClick={() => setMeetingType(mt.value)}>{t(mt.labelKey)}</Pill>)}
          </div>
        </div>
        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className={'text-xs font-bold ' + c.textSecondary + ' uppercase tracking-wide mb-1 block'}>{t('td_attendees_label')}</label>
            <input type="text" value={attendees} onChange={e => setAttendees(e.target.value)}
              placeholder={t('td_attendees_ph')}
              className={'w-full px-3 py-2 rounded-xl border text-sm ' + c.input + ' outline-none'} />
          </div>
          <div>
            <label className={'text-xs font-bold ' + c.textSecondary + ' uppercase tracking-wide mb-1 block'}>{t('td_context_label')}</label>
            <input type="text" value={context} onChange={e => setContext(e.target.value)}
              placeholder={t('td_context_ph')}
              className={'w-full px-3 py-2 rounded-xl border text-sm ' + c.input + ' outline-none'} />
          </div>
        </div>

        {mode === 'followup' && (
          <div>
            <label className={'text-xs font-bold ' + c.textSecondary + ' uppercase tracking-wide mb-2 block'}>{t('td_tone')}</label>
            <div className="flex flex-wrap gap-1.5">
              {TONES.map(tn => <Pill key={tn.value} active={tone === tn.value} onClick={() => setTone(tn.value)}>{t(tn.labelKey)}</Pill>)}
            </div>
          </div>
        )}
      </div>

        <button onClick={submit} disabled={loading || !canSubmit}
      className={'w-full py-4 rounded-2xl text-sm font-bold flex items-center justify-center gap-2 transition-all disabled:opacity-40 ' + (loading || !canSubmit ? c.btnDis : c.btnPrimary)}>
      {loading ? <><span className="inline-block animate-spin">{tool?.icon ?? '📋'}</span> {t('td_processing')}</>
        : mode === 'distill' ? <><span className="mr-1">{tool?.icon ?? '📋'}</span> {t('td_extract')}</>
        : mode === 'followup' ? <><span>📨</span> {t('td_draft_followups')}</>
        : <><span>🔄</span> {t('td_analyze_series')}</>}
      </button>
    </div>
  );

  // ════════════════════════════════════════════════════════════
  // RESULTS — DISTILL
  // ════════════════════════════════════════════════════════════
  const renderDistill = () => {
    if (!results) return null;
    return (
      <div className="space-y-4">
        {/* Summary */}
        <div className={'p-5 rounded-2xl border-2 ' + c.tipBg}>
          <div className="flex items-center gap-2 mb-1">
            <span className={'text-xs font-bold px-2 py-0.5 rounded-full ' + c.badge}>{results?.meeting_type_detected || meetingType}</span>
            {results?.duration_estimate && <span className={'text-xs ' + c.textMuted}>⏱️ {results?.duration_estimate}</span>}
          </div>
          <p className={'text-sm font-bold ' + c.text}>{results?.meeting_summary}</p>
        </div>

        {/* Decisions */}
        {results?.decisions?.length > 0 && (
          <Section title={t('td_decisions_made')} emoji="✅" sKey="decisions" badge={results?.decisions?.length + ''} defaultOpen>
            <div className="space-y-2 mt-3">
              {results?.decisions?.map((d, i) => (
                <div key={i} className={'p-3 rounded-lg border ' + c.successBox}>
                  <p className={'text-sm font-semibold ' + c.text}>{d.decision}</p>
                  {d.context && <p className={'text-xs ' + c.textSecondary + ' mt-1'}>{d.context}</p>}
                  <div className="flex gap-3 mt-1">
                    {d.who_decided && <span className={'text-[10px] ' + c.textMuted}>👤 {d.who_decided}</span>}
                    {d.reversibility && <span className={'text-[10px] ' + c.textMuted}>↩️ {d.reversibility}</span>}
                  </div>
                </div>
              ))}
            </div>
          </Section>
        )}

        {/* Action Items */}
        {results?.action_items?.length > 0 && (
          <Section title={t('td_action_items')} emoji="🎯" sKey="actions" badge={results?.action_items?.length + ''} defaultOpen>
            <div className="space-y-2 mt-3">
              {results?.action_items?.map((a, i) => (
                <div key={i} className={c.card + ' border rounded-lg p-3'}>
                  <div className="flex items-start gap-3">
                    <span className="text-base mt-0.5">{PRI_BADGE[a.priority] || '⚪'}</span>
                    <div className="flex-1 min-w-0">
                      <p className={'text-sm font-semibold ' + c.text}>{a.action}</p>
                      <div className="flex flex-wrap gap-2 mt-1.5">
                        <span className={'text-[10px] font-bold px-2 py-0.5 rounded-full ' +
                          (a.owner === 'UNASSIGNED' ? c.highPri : c.badge)}>
                          👤 {a.owner}
                        </span>
                        <span className={'text-[10px] font-bold px-2 py-0.5 rounded-full ' +
                          (a.deadline === 'No deadline set' ? c.medPri : c.badge)}>
                          📅 {a.deadline}
                        </span>
                        <span className={'text-[10px] px-2 py-0.5 rounded-full ' + priBg(a.priority)}>
                          {a.priority}
                        </span>
                      </div>
                      {a.depends_on && <p className={'text-[10px] ' + c.textMuted + ' mt-1'}>{t('td_depends_on', { val: a.depends_on })}</p>}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </Section>
        )}

        {/* Open Questions */}
        {results?.open_questions?.length > 0 && (
          <Section title={t('td_open_questions')} emoji="❓" sKey="questions" badge={results?.open_questions?.length + ''}>
            <div className="space-y-2 mt-3">
              {results?.open_questions?.map((q, i) => (
                <div key={i} className={'p-3 rounded-lg ' + c.cardAlt}>
                  <p className={'text-sm font-semibold ' + c.text}>{q.question}</p>
                  <p className={'text-xs ' + c.textSecondary + ' mt-1'}>{q.why_unresolved}</p>
                  {q.suggested_owner && <p className={'text-[10px] ' + c.tipText + ' mt-0.5'}>{t('td_suggested_owner', { who: q.suggested_owner })}</p>}
                </div>
              ))}
            </div>
          </Section>
        )}

        {/* Parking Lot */}
        {results?.parking_lot?.length > 0 && (
          <Section title={t('td_parking_lot')} emoji="🅿️" sKey="parking">
            <div className="space-y-1 mt-3">
              {results?.parking_lot?.map((p, i) => <p key={i} className={'text-xs ' + c.textSecondary}>• {p}</p>)}
            </div>
          </Section>
        )}

        {/* Tensions */}
        {results?.tensions?.length > 0 && (
          <Section title={t('td_tensions')} emoji="⚡" sKey="tensions">
            <div className="space-y-2 mt-3">
              {results?.tensions?.map((ten, i) => (
                <div key={i} className={'p-3 rounded-lg border ' + c.warningBox}>
                  <p className={'text-xs font-bold ' + c.warningTxt}>{ten.topic}</p>
                  <p className={'text-xs ' + c.textSecondary + ' mt-0.5'}>{ten.nature}</p>
                  <p className={'text-[10px] ' + c.textMuted + ' mt-0.5'}>{t('td_resolution', { val: ten.resolution })}</p>
                </div>
              ))}
            </div>
          </Section>
        )}

        {/* Meeting Health */}
        {results?.meeting_health && (
          <div className={'p-4 rounded-xl ' + c.cardAlt}>
            <p className={'text-xs font-bold ' + c.textMuted + ' uppercase mb-2'}>{t('td_meeting_health')}</p>
            <div className="space-y-1">
              {results?.meeting_health?.efficiency && <p className={'text-xs ' + c.text}>{t('td_efficiency', { val: results?.meeting_health?.efficiency })}</p>}
              {results?.meeting_health?.accountability && <p className={'text-xs ' + c.text}>{t('td_accountability', { val: results?.meeting_health?.accountability })}</p>}
              {results?.meeting_health?.pattern_warning && (
                <p className={'text-xs ' + c.warningTxt}>⚠️ {results?.meeting_health?.pattern_warning}</p>
              )}
            </div>
          </div>
        )}

        {/* Follow-up Email */}
        {results?.follow_up_email && (
          <Section title={t('td_ready_followup')} emoji="📨" sKey="email" defaultOpen>
            <div className={'mt-3 p-4 rounded-lg ' + c.cardAlt + ' whitespace-pre-wrap'}>
              <p className={'text-xs font-mono ' + c.text}>{results?.follow_up_email}</p>
            </div>
            <div className="mt-2">
            </div>
          </Section>
        )}


      </div>
    );
  };

  // ════════════════════════════════════════════════════════════
  // RESULTS — FOLLOW UP
  // ════════════════════════════════════════════════════════════
  const renderFollowup = () => {
    if (!results) return null;
    return (
      <div className="space-y-4">
        {/* Group Email */}
        {results?.group_email && (
          <div className={c.card + ' border rounded-xl p-5'}>
            <p className={'text-xs font-bold ' + c.textMuted + ' uppercase mb-1'}>{t('td_group_email_title')}</p>
            <p className={'text-sm font-bold ' + c.text + ' mb-3'}>{t('td_subject', { val: results?.group_email?.subject })}</p>
            <div className={'p-4 rounded-lg ' + c.cardAlt + ' whitespace-pre-wrap mb-3'}>
              <p className={'text-xs font-mono ' + c.text}>{results?.group_email?.body}</p>
            </div>
          </div>
        )}

        {/* Individual Nudges */}
        {results?.individual_nudges?.length > 0 && (
          <Section title={t('td_individual_followups')} emoji="💬" sKey="nudges" badge={results?.individual_nudges?.length + ''} defaultOpen>
            <div className="space-y-3 mt-3">
              {results?.individual_nudges?.map((n, i) => (
                <div key={i} className={c.cardAlt + ' border rounded-lg p-3'}>
                  <div className="flex items-center gap-2 mb-2">
                    <span className={'text-xs font-bold ' + c.text}>→ {n.to}</span>
                    <span className={'text-[9px] font-bold px-2 py-0.5 rounded-full ' + c.badge}>{n.channel}</span>
                    <span className={'text-[9px] px-2 py-0.5 rounded-full ' +
                      (n.urgency === 'send_now' ? c.highPri : n.urgency === 'within_24h' ? c.medPri : c.lowPri)}>
                      {n.urgency === 'send_now' ? t('td_send_now') : n.urgency === 'within_24h' ? t('td_within_24h') : t('td_can_wait')}
                    </span>
                  </div>
                  <p className={'text-xs ' + c.text + ' mb-2'}>{n.message}</p>
                </div>
              ))}
            </div>
          </Section>
        )}

        {/* Boss Update */}
        {results?.boss_update && (
          <div className={c.card + ' border rounded-xl p-5'}>
            <p className={'text-xs font-bold ' + c.textMuted + ' uppercase mb-1'}>{t('td_boss_update_title')}</p>
            <p className={'text-sm font-bold ' + c.text + ' mb-2'}>{t('td_subject', { val: results?.boss_update?.subject })}</p>
            <div className={'p-3 rounded-lg ' + c.cardAlt + ' mb-2'}>
              <p className={'text-xs ' + c.text + ' whitespace-pre-wrap'}>{results?.boss_update?.body}</p>
            </div>
          </div>
        )}

        {/* Calendar Invites */}
        {results?.calendar_invites?.length > 0 && (
          <Section title={t('td_meetings_to_schedule')} emoji="📅" sKey="calendar" badge={results?.calendar_invites?.length + ''}>
            <div className="space-y-2 mt-3">
              {results?.calendar_invites?.map((cal, i) => (
                <div key={i} className={'p-3 rounded-lg ' + c.cardAlt}>
                  <p className={'text-xs font-bold ' + c.text}>{cal.title}</p>
                  <p className={'text-[10px] ' + c.textSecondary}>👥 {cal.attendees} · 📅 {cal.when}</p>
                  <p className={'text-[10px] ' + c.textMuted + ' mt-0.5'}>{cal.purpose}</p>
                </div>
              ))}
            </div>
          </Section>
        )}


      </div>
    );
  };

  // ════════════════════════════════════════════════════════════
  // RESULTS — SERIES
  // ════════════════════════════════════════════════════════════
  const renderSeries = () => {
    if (!results) return null;
    return (
      <div className="space-y-4">
        {results?.series_summary && (
          <div className={'p-5 rounded-2xl border-2 ' + c.tipBg}>
            <p className={'text-xs font-bold ' + c.tipText + ' uppercase mb-1'}>{t('td_series_overview')}</p>
            <p className={'text-sm font-bold ' + c.text}>{results?.series_summary}</p>
          </div>
        )}

        {/* Productivity Trend */}
        {results?.productivity_trend && (
          <div className={'p-4 rounded-xl border ' + (results?.productivity_trend?.direction === 'improving' ? c.successBox : results?.productivity_trend?.direction === 'declining' ? c.warningBox : c.infoBox)}>
            <p className={'text-xs font-bold ' + (results?.productivity_trend?.direction === 'improving' ? c.successTxt : results?.productivity_trend?.direction === 'declining' ? c.warningTxt : c.infoTxt) + ' mb-1'}>
              {results?.productivity_trend?.direction === 'improving' ? '📈' : results?.productivity_trend?.direction === 'declining' ? '📉' : '➡️'} {t('td_trend', { val: results?.productivity_trend?.direction })}
            </p>
            <p className={'text-xs ' + c.text}>{results?.productivity_trend?.evidence}</p>
            {results?.productivity_trend?.recommendation && <p className={'text-xs ' + c.tipText + ' mt-1'}>💡 {results?.productivity_trend?.recommendation}</p>}
          </div>
        )}

        {/* Recurring Topics */}
        {results?.recurring_topics?.length > 0 && (
          <Section title={t('td_recurring_topics')} emoji="🔁" sKey="recurring" badge={results?.recurring_topics?.length + ''} defaultOpen>
            <div className="space-y-2 mt-3">
              {results?.recurring_topics?.map((rt, i) => (
                <div key={i} className={'p-3 rounded-lg border ' + (rt.resolved ? c.successBox : c.warningBox)}>
                  <div className="flex items-center gap-2 mb-1">
                    <span className={'text-xs font-bold ' + c.text}>{rt.topic}</span>
                    <span className={'text-[9px] font-bold px-2 py-0.5 rounded-full ' + (rt.resolved ? (isDark ? 'bg-emerald-900/20 text-emerald-400' : 'bg-emerald-100 text-emerald-700') : (isDark ? 'bg-red-900/20 text-red-400' : 'bg-red-100 text-red-700'))}>
                      {rt.resolved ? t('td_resolved') : t('td_unresolved')}
                    </span>
                    <span className={'text-[9px] ' + c.textMuted}>{rt.frequency}</span>
                  </div>
                  <p className={'text-xs ' + c.textSecondary}>{rt.why_recurring}</p>
                </div>
              ))}
            </div>
          </Section>
        )}

        {/* Accountability Gaps */}
        {results?.accountability_gaps?.length > 0 && (
          <Section title={t('td_accountability_gaps')} emoji="⚠️" sKey="gaps" badge={results?.accountability_gaps?.length + ''}>
            <div className="space-y-2 mt-3">
              {results?.accountability_gaps?.map((g, i) => (
                <div key={i} className={'p-3 rounded-lg border ' + c.warningBox}>
                  <p className={'text-xs font-bold ' + c.text}>{g.action}</p>
                  <p className={'text-[10px] ' + c.textSecondary}>{t('td_assigned_in', { who: g.owner, meeting: g.assigned_meeting })}</p>
                  <div className="flex items-center gap-2 mt-1">
                    <span className={'text-[9px] font-bold px-2 py-0.5 rounded-full ' +
                      (g.status === 'completed' ? (isDark ? 'bg-emerald-900/20 text-emerald-400' : 'bg-emerald-100 text-emerald-700') : g.status === 'disappeared' ? (isDark ? 'bg-red-900/20 text-red-400' : 'bg-red-100 text-red-700') : c.medPri)}>
                      {g.status}
                    </span>
                    {g.pattern && <span className={'text-[10px] ' + c.warningTxt}>🔁 {g.pattern}</span>}
                  </div>
                </div>
              ))}
            </div>
          </Section>
        )}

        {/* Decisions Revisited */}
        {results?.decisions_revisited?.length > 0 && (
          <Section title={t('td_decisions_revisited')} emoji="↩️" sKey="revisited">
            <div className="space-y-2 mt-3">
              {results?.decisions_revisited?.map((dr, i) => (
                <div key={i} className={'p-3 rounded-lg ' + c.cardAlt}>
                  <p className={'text-xs font-bold ' + c.text}>{dr.decision}</p>
                  <p className={'text-[10px] ' + c.textSecondary}>{t('td_decided_reopened', { orig: dr.original_meeting, revisited: dr.revisited_meeting })}</p>
                  <p className={'text-[10px] ' + c.tipText + ' mt-0.5'}>{t('td_why', { val: dr.why })}</p>
                </div>
              ))}
            </div>
          </Section>
        )}

        {/* Next Meeting Agenda */}
        {results?.next_meeting_agenda?.length > 0 && (
          <div className={'p-4 rounded-xl border ' + c.successBox}>
            <p className={'text-xs font-bold ' + c.successTxt + ' mb-2'}>{t('td_next_agenda')}</p>
            {results?.next_meeting_agenda?.map((a, i) => <p key={i} className={'text-xs ' + c.successTxt + ' mb-1'}>{i + 1}. {a}</p>)}
            <div className="mt-2">
            </div>
          </div>
        )}
      </div>
    );
  };

  // ════════════════════════════════════════════════════════════
  // HISTORY
  // ════════════════════════════════════════════════════════════
  const renderHistory = () => {
    if (sessionHistory.length === 0) return null;
    const modeEmoji = (m) => MODES.find(mo => mo.value === m)?.emoji || '📋';
    const formatDate = (iso) => { try { const d = new Date(iso); const diff = Math.floor((new Date() - d) / 86400000); return diff === 0 ? t('td_today') : diff === 1 ? t('td_yesterday') : diff < 7 ? t('td_days_ago', { n: diff }) : d.toLocaleDateString(userLocale || undefined, { month: 'short', day: 'numeric' }); } catch { return ''; } };
    return (
      <div className={'mt-6 p-4 rounded-2xl border ' + c.histBg}>
        <button onClick={() => setShowHistory(!showHistory)} className="w-full flex items-center gap-2 text-left">
          <span>📋</span>
          <span className={'text-sm font-bold ' + c.text + ' flex-1'}>{t('td_past_debriefs')}</span>
          <span className={'text-xs ' + c.textMuted}>{sessionHistory.length}</span>
          <span className={'text-xs ' + c.textMuted}>{showHistory ? '▲' : '▼'}</span>
        </button>
        {showHistory && (
          <div className="mt-3 space-y-2">
            {sessionHistory.map(entry => (
              <div key={entry.id} className={'rounded-xl border ' + c.card + ' p-3 flex items-center gap-3'}>
                <span className="text-lg">{modeEmoji(entry.mode)}</span>
                <div className="flex-1 min-w-0">
                  <div className={'text-sm font-semibold ' + c.text + ' truncate'}>{entry.title}</div>
                  <div className={'text-xs ' + c.textMuted + ' mt-0.5'}>
                    {formatDate(entry.date)}{entry.actions > 0 ? t('td_n_actions', { n: entry.actions }) : ''}
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    );
  };

  // ════════════════════════════════════════════════════════════
  // MAIN RENDER
  // ════════════════════════════════════════════════════════════
  return (
    <div className={`space-y-4 ${c.text}`}>
      {!results && renderInput()}

      {/* ── Results phase: persistent header card with reset (ternary, not && — see PF-3 replace-mode note) ── */}
      {results ? (
        <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5`}>
          <div className="pb-3 border-b border-zinc-500">
            <div className="flex items-start justify-between">
              <div>
                <h2 className={'text-xl font-bold ' + c.text}>
                  <span className="mr-2">{tool?.icon ?? '📋'}</span>{tool?.title ?? t('td_title')}
                </h2>
                <p className={'text-sm ' + c.textSecondary}>{tool?.tagline ?? t('td_tagline')}</p>
              </div>
              <button onClick={handleReset} className={`${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs font-bold flex-shrink-0`}>
                ↺ {t('start_over')}
              </button>
            </div>
          </div>
        </div>
      ) : null}

      {results && (
        <div ref={resultsRef} className="space-y-4">
          {mode === 'distill' && renderDistill()}
          {mode === 'followup' && renderFollowup()}
          {mode === 'series' && renderSeries()}

          {/* Edit Input — partial reset, returns to input form keeping content */}
          <button onClick={() => { setResults(null); setError(''); }}
            className={'w-full py-3 rounded-xl text-xs font-bold flex items-center justify-center gap-1.5 ' + c.btnSecondary}>
            {t('td_edit_input')}
          </button>

          <div className={'p-4 rounded-2xl border ' + c.card}>
            <p className={'text-xs font-bold ' + c.textMuted + ' uppercase tracking-wide mb-2'}>{t('td_related')}</p>
            <div className={'space-y-1.5 text-xs ' + c.textSecondary}>
              <p>{t('td_xref_velvet_q')} <a href="/VelvetHammer" className={linkStyle}>{t('td_xref_velvet')}</a> {t('td_xref_velvet_tail')}</p>
              <p>{t('td_xref_ghost_q')} <a href="/GhostWriter" className={linkStyle}>{t('td_xref_ghost')}</a> {t('td_xref_ghost_tail')}</p>
            </div>
          </div>
        </div>
      )}
      {error && (
        <div className={'p-4 ' + c.warningBox + ' border rounded-xl flex items-start gap-3'}>
          <span className={'text-base ' + c.warningTxt}>⚠️</span>
          <p className={'text-sm ' + c.warningTxt}>{error}</p>
        </div>
      )}
      {renderHistory()}
    </div>
  );
};

TheDebrief.displayName = 'TheDebrief';
export default TheDebrief;
