import React, { useState, useEffect, useRef, useCallback } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';
import { currencySymbol } from '../utils/formatLocale';
import { CopyBtn } from '../components/ActionButtons';
import { pickExample } from '../utils/exampleRotation';
import { revealSection } from '../utils/revealSection';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

const EXAMPLES = [
  {
  ticketType: 'parking',
  city: 'Seattle, WA',
  ticketText: 'CITY OF SEATTLE — PARKING INFRACTION NOTICE. Violation: SMC 11.23.180 — Parking in passenger load zone. Date: 07/22/2026 Time: 6:40 PM. Location: 1400 block, E Pine St. Penalty: $47. Respond within 15 days of issue date.',
  whatHappened: "The load-zone sign says the restriction runs 'Passenger Load Zone 7AM–6PM'. I parked at 6:40 PM, after the posted end time. The sign is also partially bent behind a tree branch — you can barely read it from the street side.",
  fineAmount: '47',
  deadline: '15 days from issue',
},
  {
  ticketType: 'camera',
  city: 'Chicago, IL',
  ticketText: 'CITY OF CHICAGO — AUTOMATED SPEED ENFORCEMENT VIOLATION. Recorded speed: 36 MPH in a posted 30 MPH safety zone. Date: 08/03/2026 Time: 07:12 AM. Location: 4400 S Western Ave. Fine: $35.00. Photographs and video of the violation are available online using the notice number above.',
  whatHappened: "The safety-zone limit only applies when the park is open or a school is in session, and 7:12am on a Sunday in August is neither. I have looked at the photos on the city site and they show the car and the plate clearly, but nothing in them establishes what time the zone became active.",
},
  {
  ticketType: 'parking',
  city: 'Austin, TX',
  ticketText: 'CITY OF AUSTIN — PARKING CITATION. Violation: Blocking fire hydrant, within 15 feet. Date: 09/02/2026 Time: 2:15 PM. Location: 600 Congress Ave. Fine: $150. Pay or contest within 21 days.',
  whatHappened: "I parked in front of a fire hydrant for about ten minutes to grab coffee. I know it's a fire hydrant — there's no ambiguity there. I just didn't think anyone would notice that fast.",
  fineAmount: '150',
  deadline: '21 days',
},
  {
  ticketType: 'camera',
  city: 'Los Angeles, CA',
  ticketText: 'CITY OF LOS ANGELES — RED LIGHT PHOTO ENFORCEMENT VIOLATION. Failure to stop at red signal. Date: 09/10/2026 Time: 5:48 PM. Location: Intersection of Sunset Blvd & Vine St. Fine: $490. Photographs and a short video clip are available online using the citation number above.',
  whatHappened: "The video shows I entered the intersection on a yellow light, but the car in front of me stopped short, so I was already committed and could not stop safely without risking a rear-end collision.",
  fineAmount: '490',
  deadline: '30 days',
},
  {
  ticketType: 'parking',
  city: 'Boston, MA',
  ticketText: 'CITY OF BOSTON — PARKING VIOLATION NOTICE. Violation: Expired meter. Date: 09/15/2026 Time: 11:20 AM. Location: 200 Newbury St. Fine: $40. Pay within 14 days or request a hearing.',
  whatHappened: "I paid through the ParkBoston app and have a screenshot of the payment confirmation timestamped before the ticket was issued, but the officer's handheld apparently had not yet synced with the system when they wrote it up.",
  fineAmount: '40',
  deadline: '14 days',
},
];

const TicketTackler = ({ tool }) => {
  const { callToolEndpoint, loading, error, userLocale, userCurrency } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();
  const sym = currencySymbol(userLocale, userCurrency);

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20'
                          : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-400' : 'text-gray-500',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white'
                          : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    // Waiting for input: an outline, not a smudge. Empty fill keeps "filled"
    // meaning "ready"; the border and label carry the visibility. Important
    // modifiers because tools carry their own border/text utilities on the
    // submit and Tailwind resolves conflicts by stylesheet order, not class
    // order. See the PF-13 exception in audit/audit_v2-3-2.py.
    btnIdle:       isDark ? '!bg-transparent !border-2 !border-cyan-500/85 !text-cyan-300 cursor-not-allowed'
                          : '!bg-transparent !border-2 !border-cyan-600/85 !text-cyan-800 cursor-not-allowed',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200'
                          : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200'
                          : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200'
                          : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200'
                          : 'bg-red-50 border-red-200 text-red-800',
    successTxt:    isDark ? 'text-emerald-300' : 'text-emerald-800',
    warningTxt:    isDark ? 'text-amber-300' : 'text-amber-800',
    pillActive:    isDark ? 'border-cyan-500 bg-cyan-900/30 text-cyan-200'
                          : 'border-cyan-600 bg-cyan-100 text-cyan-900',
    pillInactive:  isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500'
                          : 'border-gray-300 text-gray-500 hover:border-gray-400',
    required:      isDark ? 'text-amber-400' : 'text-amber-700',
  };
  c.label = c.labelText;

  // ── State ──
  const [ticketType, setTicketType] = useState('parking');
  const [city, setCity] = useState('');
  const [ticketText, setTicketText] = useState('');
  const [ticketImage, setTicketImage] = useState(null); // { dataUrl, mediaType }
  const [whatHappened, setWhatHappened] = useState('');
  const [fineAmount, setFineAmount] = useState('');
  const [deadline, setDeadline] = useState('');
  const [results, setResults] = usePersistentState('ticket-tackler-results', null);
  const [sessionHistory, setSessionHistory] = usePersistentState('ticket-tackler-history', []);
  const [showHistory, setShowHistory] = useState(false);
  const [phase, setPhase] = useState(null); // 'main' | 'followup'
  const [followupQ, setFollowupQ] = useState('');
  const [followup, setFollowup] = useState(null);
  const resultsRef = useRef(null);
  const fileInputRef = useRef(null);

  const hasAnyInput = !!(city || ticketText || ticketImage || whatHappened || fineAmount || deadline || results);

  const loadExample = () => {
    const ex = pickExample('TicketTackler', EXAMPLES);
    setTicketType(ex.ticketType);
    setCity(ex.city);
    setTicketText(ex.ticketText);
    setWhatHappened(ex.whatHappened);
    setFineAmount(ex.fineAmount);
    setDeadline(ex.deadline);
    setTicketImage(null);
  };

  const handleReset = () => {
    setTicketType('parking');
    setCity(''); setTicketText(''); setTicketImage(null);
    setWhatHappened(''); setFineAmount(''); setDeadline('');
    setResults(null); setFollowup(null); setFollowupQ('');
  };

  const handleFile = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => setTicketImage({ dataUrl: reader.result, mediaType: file.type || 'image/jpeg' });
    reader.readAsDataURL(file);
    e.target.value = '';
  };

  const handleSubmit = useCallback(async () => {
    if (loading || !city.trim() || (!ticketText.trim() && !ticketImage && !whatHappened.trim())) return;
    setPhase('main');
    setResults(null); setFollowup(null);
    try {
      const data = await callToolEndpoint('ticket-tackler', {
        ticketType,
        city,
        ticketText: ticketText || undefined,
        ticketImageBase64: ticketImage?.dataUrl || undefined,
        imageMediaType: ticketImage?.mediaType || undefined,
        whatHappened: whatHappened || undefined,
        fineAmount: fineAmount || undefined,
        deadline: deadline || undefined,
      });
      setResults(data);
      setSessionHistory(prev => [
        { id: Date.now(), preview: `${city.trim()} · ${(whatHappened || ticketText).trim().slice(0, 40)}`, verdict: data?.assessment?.verdict, city, ticketType },
        ...prev,
      ].slice(0, 6));
    } catch (_) { /* error state handled by hook */ }
    finally { setPhase(null); }
  }, [loading, city, ticketText, ticketImage, whatHappened, fineAmount, deadline, ticketType, callToolEndpoint, setResults, setSessionHistory]);

  const handleFollowup = useCallback(async () => {
    if (loading || !followupQ.trim() || !results) return;
    setPhase('followup');
    try {
      const data = await callToolEndpoint('ticket-tackler/followup', {
        question: followupQ,
        city,
        ticketType,
        analysisContext: `${results?.assessment?.verdict}: ${results?.assessment?.reason}`,
      });
      setFollowup(data);
    } catch (_) { /* error state handled by hook */ }
    finally { setPhase(null); }
  }, [loading, followupQ, results, city, ticketType, callToolEndpoint]);

  // ⌘/Ctrl+Enter submits
  const handleSubmitRef = useRef(null);
  handleSubmitRef.current = handleSubmit;
  useEffect(() => {
    const onKey = (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'Enter' && e.target.tagName !== 'SELECT') {
        handleSubmitRef.current?.();
      }
    };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, []);

  // Scroll to results
  useEffect(() => {
    if (results && resultsRef.current) {
      const id = setTimeout(() => revealSection(resultsRef.current), 100);
      return () => clearTimeout(id);
    }
  }, [results]);

  const verdictMeta = (v) => {
    switch (v) {
      case 'WORTH_CONTESTING': return { cls: c.success, label: t('tt_verdict_worth_contesting'), icon: '🥊' };
      case 'PROBABLY_PAY':     return { cls: c.danger, label: t('tt_verdict_probably_pay'), icon: '💸' };
      case 'VERIFY_FIRST':
      default:                 return { cls: c.warning, label: t('tt_verdict_verify_first'), icon: '⚖️' };
    }
  };

  const buildFullText = () => {
    if (!results) return '';
    const parts = [];
    const asmt = results?.assessment;
    if (asmt) parts.push(`${verdictMeta(asmt.verdict).label}\n${asmt.reason}`);
    if (results?.what_may_matter?.length) {
      parts.push(t('tt_matter_title') + ':\n' + results.what_may_matter.map(a => `• ${a?.issue} — ${a?.supports_it} (${t('tt_matter_verify')}: ${a?.needs_verification}; ${t('tt_matter_helps')}: ${a?.evidence_that_would_help})`).join('\n'));
    }
    if (results?.what_to_verify?.length) {
      parts.push(t('tt_verify_title') + ':\n' + results.what_to_verify.map(v => `• ${v}`).join('\n'));
    }
    if (results?.evidence_to_get?.length) {
      parts.push(t('tt_evidence_title') + ':\n' + results.evidence_to_get.map(ev => `• (${ev?.urgency}) ${ev?.item} — ${ev?.why}`).join('\n'));
    }
    if (results?.appeal_letter) parts.push(t('tt_letter_title') + ':\n' + results.appeal_letter);
    if (results?.how_to_file) {
      parts.push(`${t('tt_file_title')}:\n${t('tt_file_where')}: ${results.how_to_file?.where}\n${t('tt_file_tips')}: ${results.how_to_file?.method_tips}\n${t('tt_file_deadline')}: ${results.how_to_file?.deadline_note}`);
    }
    if (results?.pay_or_contest) {
      parts.push(`${t('tt_pay_or_contest_title')}:\n${verdictMeta(results.pay_or_contest?.recommendation).label} — ${results.pay_or_contest?.reasoning}`);
    }
    if (results?.dont_say?.length) parts.push(t('tt_dontsay_title') + ':\n' + results.dont_say.map(d => `• ${d}`).join('\n'));
    return parts.join('\n\n') + BRAND;
  };
  useRegisterActions(buildFullText(), tool?.title || 'Ticket Tackler');

  return (
    <div className="space-y-6">
      {/* Header + inputs card */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm px-5 pt-2.5 pb-5`}>
        <div className="pb-3 border-b border-zinc-500 flex items-center justify-between">
          <div>
            {/* PF-30 — the wrapper already prints the name as the page <h1>. */}
            <p className={`text-base ${c.textSecondary}`}>
              <span className="me-2 text-lg">{tool?.icon ?? '🎫'}</span>{t('tt_tagline')}
            </p>
            <button
              onClick={loadExample}
              disabled={loading}
              style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }}
              className="mt-2 px-4 py-2 rounded-full text-sm font-semibold border border-black/25 text-zinc-900 shadow-sm hover:brightness-105 hover:shadow transition disabled:opacity-40 whitespace-nowrap"
            >✨ {t('try_example')}
            </button>
          </div>
          <div className="flex items-center gap-2 flex-shrink-0">
            {sessionHistory.length > 0 && (
              <button onClick={() => setShowHistory(!showHistory)}
                className={`text-xs font-bold px-3 py-1.5 rounded-lg ${c.btnSecondary}`}>
                📋 {sessionHistory.length}
              </button>
            )}
            {hasAnyInput ? (
              <button onClick={handleReset} className={`${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs font-bold`}>
                ↺ {t('start_over')}
              </button>
            ) : null}
          </div>
        </div>

        <div className="pt-4 space-y-4">
          {/* History panel */}
          {showHistory && sessionHistory.length > 0 && (
            <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4 space-y-2`}>
              <p className={`text-xs font-bold ${c.textMuted} mb-1`}>{t('tt_recent')}</p>
              {sessionHistory.map(h => (
                <button key={h.id}
                  onClick={() => { setCity(h.city || ''); setTicketType(h.ticketType || 'parking'); setShowHistory(false); }}
                  className={`w-full text-start flex items-center justify-between px-3 py-2 rounded-lg ${c.card} border ${c.border} hover:opacity-80 transition-opacity`}>
                  <span className={`text-sm ${c.textSecondary} truncate`}>{h.preview}</span>
                  {h.verdict && <span className={`text-xs font-bold ms-2 shrink-0 ${h.verdict === 'WORTH_CONTESTING' ? c.successTxt : h.verdict === 'PROBABLY_PAY' ? c.textMuted : c.warningTxt}`}>{verdictMeta(h.verdict).label}</span>}
                </button>
              ))}
            </div>
          )}

          {/* Type toggle */}
          <div>
            <label className={`block text-sm font-medium mb-1.5 ${c.label}`}>{t('tt_type_label')}</label>
            <div className="flex flex-wrap gap-2">
              {[['parking', t('tt_type_parking')], ['camera', t('tt_type_camera')]].map(([val, label]) => (
                <button key={val} onClick={() => setTicketType(val)}
                  className={`px-3 py-1.5 rounded-full border text-sm font-medium ${ticketType === val ? c.pillActive : c.pillInactive}`}>
                  {label}
                </button>
              ))}
            </div>
          </div>

          <div>
            <label className={`block text-sm font-medium mb-1.5 ${c.label}`}>
              {t('tt_city_label')} <span className={c.required}>*</span>
            </label>
            <input type="text" value={city} onChange={(e) => setCity(e.target.value)}
              placeholder={t('tt_city_ph')}
              className={`w-full px-3 py-2 border rounded-lg text-sm outline-none focus:ring-2 ${c.input}`} />
          </div>

          <div>
            <label className={`block text-sm font-medium mb-1.5 ${c.label}`}>{t('tt_ticket_label')}</label>
            <textarea value={ticketText} onChange={(e) => setTicketText(e.target.value)}
              placeholder={t('tt_ticket_ph')} rows={4}
              className={`w-full px-3 py-2 border rounded-lg text-sm outline-none focus:ring-2 resize-y ${c.input}`} />
            <input ref={fileInputRef} type="file" accept="image/*" onChange={handleFile} className="hidden" />
            <button onClick={() => fileInputRef.current?.click()} disabled={loading}
              className={`mt-2 ${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs font-semibold disabled:opacity-40`}>
              {ticketImage ? t('tt_photo_replace') : t('tt_photo_btn')}
            </button>
            {ticketImage ? <span className={`ms-2 text-xs ${c.successTxt}`}>✓ {t('tt_photo_added')}</span> : null}
          </div>

          <div>
            <label className={`block text-sm font-medium mb-1.5 ${c.label}`}>{t('tt_happened_label')}</label>
            <textarea value={whatHappened} onChange={(e) => setWhatHappened(e.target.value)}
              placeholder={t('tt_happened_ph')} rows={3}
              className={`w-full px-3 py-2 border rounded-lg text-sm outline-none focus:ring-2 resize-y ${c.input}`} />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className={`block text-sm font-medium mb-1.5 ${c.label}`}>{t('tt_fine_label')}</label>
              <input type="text" value={fineAmount} onChange={(e) => setFineAmount(e.target.value)}
                placeholder={t('tt_fine_ph', { sym })}
                className={`w-full px-3 py-2 border rounded-lg text-sm outline-none focus:ring-2 ${c.input}`} />
            </div>
            <div>
              <label className={`block text-sm font-medium mb-1.5 ${c.label}`}>{t('tt_deadline_label')}</label>
              <input type="text" value={deadline} onChange={(e) => setDeadline(e.target.value)}
                placeholder={t('tt_deadline_ph')}
                className={`w-full px-3 py-2 border rounded-lg text-sm outline-none focus:ring-2 ${c.input}`} />
            </div>
          </div>

          <button title={t('cmd_enter')} onClick={handleSubmit}
            disabled={loading || !city.trim() || (!ticketText.trim() && !ticketImage && !whatHappened.trim())}
            className={`relative w-full py-3 ${(!city.trim() || (!ticketText.trim() && !ticketImage && !whatHappened.trim())) ? c.btnIdle : c.btnPrimary} rounded-xl font-semibold`}>
            {loading && phase === 'main'
              ? <span><span className="inline-block animate-spin me-2">{tool?.icon ?? '🎫'}</span>{t('tt_building')}</span>
              : t('tt_submit')}
          {!loading && (
            <kbd aria-hidden="true"
              className="hidden sm:flex items-center absolute end-3 top-1/2 -translate-y-1/2 px-1.5 py-0.5 rounded border border-white/30 bg-white/15 text-[10px] font-bold tracking-wide">
              ⌘↵
            </kbd>
          )}
          </button>

          {error ? <div className={`${c.danger} border rounded-lg px-3 py-2 text-sm`}>{t('tt_error')}</div> : null}
          <p className={`text-xs ${c.textMuted}`}>{t('tt_disclaimer')}</p>
        </div>
      </div>

      {/* Results */}
      {results && (
        <div data-copy-results ref={resultsRef} className="scroll-mt-24 space-y-4">
          {/* Verdict */}
          {results?.assessment ? (
            <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5`}>
              <div className={`border rounded-xl px-4 py-3 ${verdictMeta(results.assessment?.verdict).cls}`}>
                <div className="text-lg font-bold">
                  <span className="me-2">{verdictMeta(results.assessment?.verdict).icon}</span>
                  {verdictMeta(results.assessment?.verdict).label}
                </div>
                <p className="text-sm mt-1">{results.assessment?.reason}</p>
              </div>
            </div>
          ) : null}

          {/* What may matter */}
          {results?.what_may_matter?.length ? (
            <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5 space-y-3`}>
              <h3 className={`font-bold ${c.text}`}>🔍 {t('tt_matter_title')}</h3>
              {results.what_may_matter.map((a, i) => (
                <div key={i} className={`${c.cardAlt} rounded-lg p-3`}>
                  <span className={`font-semibold text-sm ${c.text}`}>{a?.issue}</span>
                  <p className={`text-sm mt-1 ${c.textSecondary}`}>{a?.supports_it}</p>
                  <p className={`text-xs mt-1 ${c.warningTxt}`}>❓ {t('tt_matter_verify')}: {a?.needs_verification}</p>
                  <p className={`text-xs mt-1 ${c.textMuted}`}>📎 {t('tt_matter_helps')}: {a?.evidence_that_would_help}</p>
                </div>
              ))}
            </div>
          ) : null}

          {/* What to verify */}
          {results?.what_to_verify?.length ? (
            <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5`}>
              <h3 className={`font-bold ${c.text}`}>❓ {t('tt_verify_title')}</h3>
              <ul className="mt-2 space-y-1.5 list-disc ps-5">
                {results.what_to_verify.map((v, i) => (
                  <li key={i} className={`text-sm ${c.textSecondary}`}>{v}</li>
                ))}
              </ul>
            </div>
          ) : null}

          {/* Evidence to get */}
          {results?.evidence_to_get?.length ? (
            <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5`}>
              <h3 className={`font-bold ${c.text}`}>📸 {t('tt_evidence_title')}</h3>
              <ul className="mt-2 space-y-2">
                {results.evidence_to_get.map((ev, i) => (
                  <li key={i} className={`text-sm ${c.textSecondary}`}>
                    <span className={`me-2 text-xs font-bold uppercase ${ev?.urgency === 'today' ? c.warningTxt : c.textMuted}`}>
                      {ev?.urgency === 'today' ? t('tt_urgency_today') : t('tt_urgency_before')}
                    </span>
                    <span className={`font-medium ${c.text}`}>{ev?.item}</span> — {ev?.why}
                  </li>
                ))}
              </ul>
            </div>
          ) : null}

          {/* Appeal letter — only rendered when the model concluded there's a basis for one */}
          {results?.appeal_letter ? (
            <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5`}>
              <div className="flex items-center justify-between gap-2">
                <h3 className={`font-bold ${c.text}`}>✉️ {t('tt_letter_title')}</h3>
                <CopyBtn content={results.appeal_letter + BRAND} label={t('tt_letter_copy')} />
              </div>
              <p className={`text-sm mt-2 whitespace-pre-wrap leading-relaxed ${c.textSecondary}`}>{results.appeal_letter}</p>
            </div>
          ) : null}

          {/* How to file + pay or contest */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {results?.how_to_file ? (
              <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5`}>
                <h3 className={`font-bold ${c.text}`}>📮 {t('tt_file_title')}</h3>
                <p className={`text-sm mt-2 ${c.textSecondary}`}><span className={`font-semibold ${c.text}`}>{t('tt_file_where')}:</span> {results.how_to_file?.where}</p>
                <p className={`text-sm mt-1 ${c.textSecondary}`}><span className={`font-semibold ${c.text}`}>{t('tt_file_tips')}:</span> {results.how_to_file?.method_tips}</p>
                <p className={`text-sm mt-1 ${c.warningTxt}`}><span className="font-semibold">⏰ {t('tt_file_deadline')}:</span> {results.how_to_file?.deadline_note}</p>
              </div>
            ) : null}
            {results?.pay_or_contest ? (
              <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5`}>
                <h3 className={`font-bold ${c.text}`}>{t('tt_pay_or_contest_title')}</h3>
                <div className={`inline-flex items-center gap-1.5 mt-2 px-2.5 py-1 rounded-lg text-xs font-bold ${verdictMeta(results.pay_or_contest?.recommendation).cls}`}>
                  <span>{verdictMeta(results.pay_or_contest?.recommendation).icon}</span>
                  {verdictMeta(results.pay_or_contest?.recommendation).label}
                </div>
                <p className={`text-sm mt-2 ${c.textSecondary}`}>{results.pay_or_contest?.reasoning}</p>
              </div>
            ) : null}
          </div>

          {/* Don't say */}
          {results?.dont_say?.length ? (
            <div className={`${c.danger} border rounded-xl p-4`}>
              <h3 className="font-bold text-sm">🤐 {t('tt_dontsay_title')}</h3>
              <ul className="mt-1 space-y-1 text-sm list-disc ps-5">
                {results.dont_say.map((d, i) => <li key={i}>{d}</li>)}
              </ul>
            </div>
          ) : null}

          {/* Follow-up */}
          <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5`}>
            <label className={`block text-sm font-medium mb-1.5 ${c.label}`}>{t('tt_followup_label')}</label>
            <div className="flex gap-2">
              <input type="text" value={followupQ} onChange={(e) => setFollowupQ(e.target.value)}
                onKeyDown={(e) => { if (e.key === 'Enter') handleFollowup(); }}
                placeholder={t('tt_followup_ph')}
                className={`flex-1 px-3 py-2 border rounded-lg text-sm outline-none focus:ring-2 ${c.input}`} />
              <button onClick={handleFollowup} disabled={loading || !followupQ.trim()}
                className={`${c.btnPrimary} px-4 py-2 rounded-lg text-sm font-semibold disabled:opacity-40`}>
                {loading && phase === 'followup'
                  ? <span className="inline-block animate-spin">{tool?.icon ?? '🎫'}</span>
                  : t('tt_followup_send')}
              </button>
            </div>
            {followup ? (
              <div className={`${c.cardAlt} rounded-lg p-3 mt-3 space-y-1`}>
                <p className={`text-sm ${c.textSecondary}`}>{followup?.answer}</p>
                {followup?.watch_out ? <p className={`text-xs ${c.warningTxt}`}>⚠️ {t('tt_followup_watch')}: {followup.watch_out}</p> : null}
                {followup?.next_step ? <p className={`text-xs ${c.accentTxt}`}>→ {t('tt_followup_next')}: {followup.next_step}</p> : null}
              </div>
            ) : null}
          </div>
        </div>
      )}
    </div>
  );
};

TicketTackler.displayName = 'TicketTackler';

export default TicketTackler;
