import React, { useState, useCallback, useEffect, useRef } from 'react';
import { useRegisterActions } from '../components/ActionBarContext';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { usePersistentState } from '../hooks/usePersistentState';
import { useTheme } from '../hooks/useTheme';
import { useTranslation } from '../i18n/useTranslation';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

// ════════════════════════════════════════════════════════════
// QUICK-PICK SCENARIOS
// ════════════════════════════════════════════════════════════
const QUICK_PICKS = [
  { labelKey: 'tf_qp_write', emoji: '✍️' },
  { labelKey: 'tf_qp_money', emoji: '💰' },
  { labelKey: 'tf_qp_decision', emoji: '🤔' },
  { labelKey: 'tf_qp_conversation', emoji: '🗣️' },
  { labelKey: 'tf_qp_broken', emoji: '🔧' },
  { labelKey: 'tf_qp_learn', emoji: '📚' },
  { labelKey: 'tf_qp_plan', emoji: '🗺️' },
  { labelKey: 'tf_qp_food', emoji: '🍳' },
];

// ════════════════════════════════════════════════════════════
// COMPONENT
// ════════════════════════════════════════════════════════════
const EXAMPLE_KEYS = ['tf_ex1', 'tf_ex2', 'tf_ex3'];
const ToolFinder = ({ tool }) => {
  const { callToolEndpoint, loading } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();

  // ─── Navy & Gold palette ───
  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-500' : 'text-gray-400',
    required:      isDark ? 'text-amber-400' : 'text-amber-500',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-200 text-red-800',
    pillInactive:  isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500' : 'border-gray-300 text-gray-500 hover:border-gray-400',
    badge:         isDark ? 'bg-cyan-900/30 text-cyan-300' : 'bg-cyan-100 text-cyan-800',
    cardHover:     isDark ? 'group-hover:border-cyan-600' : 'group-hover:border-cyan-400',
  };

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-600 hover:text-cyan-700 underline underline-offset-2';

  // ─── State ───
  const [error, setError] = useState('');
  const [problem, setProblem] = usePersistentState('toolfinder-problem', '');
  const [results, setResults] = usePersistentState('toolfinder-result', null);
  const [sessionHistory, setSessionHistory] = usePersistentState('toolfinder-history', []);
  const loadExample = () => {
    const key = EXAMPLE_KEYS[Math.floor(Math.random() * EXAMPLE_KEYS.length)];
    setProblem(t(key));
  };

  const resultsRef = useRef(null);

  // ─── Actions (declared before useEffect to avoid stale closures) ───
  const findTools = useCallback(async (text) => {
    const query = (text !== undefined ? text : problem);
    if (!query.trim()) return;
    setError('');
    setResults(null);
    try {
      const data = await callToolEndpoint('tool-finder', { problem: query.trim() });
      setResults(data);
      setSessionHistory(prev => [{
        id: Date.now(), date: new Date().toISOString(),
        preview: query.trim().substring(0, 40),
        result: data,
      }, ...prev].slice(0, 6));
    } catch (err) {
      setError(err.message || t('tf_err'));
    } }, [problem, callToolEndpoint, setError, setResults, setSessionHistory, t]);

  const handleQuickPick = useCallback((label) => {
    setProblem(label);
    findTools(label);
  }, [findTools, setProblem]);

  const handleReset = useCallback(() => {
    setProblem('');
    setResults(null);
    setError('');
  }, [setProblem, setResults, setError]);

  const buildFullText = useCallback(() => {
    if (!results) return '';
    let text = t('tf_copy_header') + '\n';
    if (results?.understanding) text += `\n${results?.understanding}\n`;
    if (results?.recommendations?.length) {
      text += `\n${t('tf_copy_recommended')}\n`;
      results?.recommendations?.forEach((rec, i) => {
        text += `\n${i + 1}. ${rec.icon || '🔧'} ${rec.title} — ${rec.why}`;
        if (rec.what_to_do) text += `\n   → ${rec.what_to_do}`;
      });
    } if (results?.workflow) text += `\n\n${t('tf_copy_workflow')} ${results?.workflow}`;
    return text + BRAND;
  }, [results, t]);

  // ─── Register export content ───
  useRegisterActions(results ? buildFullText() : '', tool?.title);

  // ─── Scroll to results ───
  useEffect(() => {
    if (!results) return;
    const t = setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 100);
    return () => clearTimeout(t);
  }, [results]);

  // Global Cmd/Ctrl+Enter listener — after all handlers to avoid TDZ
  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && !loading) findTools(problem);
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, [loading, findTools, problem]);

  const r = results;

  // ════════════════════════════════════════════════════════════
  // RENDER
  // ════════════════════════════════════════════════════════════
  return (<div className={`space-y-4 ${c.text}`}>

      {/* ── HEADER ── */} <div className={`${c.card} border ${c.border} rounded-xl p-6`}>
        <div className={`mb-5 pb-4 border-b ${c.border}`}>
          <div className="flex items-start justify-between gap-3">
            <div>
              <h2 className={`text-2xl font-bold ${c.text}`}>
                <span className="mr-2">{tool?.icon ?? '🧰'}</span>{tool?.title ?? 'Tool Finder'}
              </h2>
              <p className={`text-sm ${c.textSecondary} mt-1`}>{tool?.tagline ?? "Describe your problem — I'll find the right tools for you"}</p>
              <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className={`mt-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium border disabled:opacity-40 ${isDark ? 'text-white border-white/40' : 'text-gray-800 border-transparent'}`}>{t('try_example')}</button>
            </div>
            {(results || problem.trim()) && (
              <button onClick={handleReset} className={`${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs font-bold flex-shrink-0`}>
                ↺ {t('start_over')}
              </button>
            )}
          </div>
        </div>

        {/* ── PROBLEM INPUT ── */} <div className="mb-4">
          <label className={`text-sm font-bold ${c.text} block mb-1.5`}>
            {t('tf_input_label')} <span className={c.required}>*</span>
          </label>
          <textarea
            value={problem} onChange={e => setProblem(e.target.value)} placeholder={t('tf_input_ph')}
            rows={3} className={`w-full px-4 py-3 border rounded-xl text-sm ${c.input} ${c.border} ${c.text} outline-none focus:ring-2 resize-none placeholder:${c.textMuted}`} />
        </div>

        {/* ── QUICK PICKS ── */} {!results && (<div className="mb-5">
            <p className={`text-xs font-bold ${c.textMuted} mb-2`}>{t('tf_quick_label')}</p>
            <div className="flex flex-wrap gap-1.5">
              {QUICK_PICKS.map(qp => (<button
                  key={qp.labelKey} onClick={() => handleQuickPick(t(qp.labelKey))} disabled={loading} className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors min-h-[32px] ${c.pillInactive} disabled:opacity-40`} >
                  {qp.emoji} {t(qp.labelKey)} </button>
              ))} </div>
          </div>
        )} {/* ── SUBMIT ── */} <div className="flex gap-3">
          <button
            onClick={() => findTools()} disabled={loading || !problem.trim()} className={`flex-1 ${c.btnPrimary} disabled:opacity-40 disabled:cursor-not-allowed font-bold py-3 px-6 rounded-xl flex items-center justify-center gap-2 min-h-[48px] shadow-lg transition-all`} >
            {loading
              ? <><span className="inline-block animate-spin">{tool?.icon ?? '🧰'}</span> {t('tf_searching')}</>
              : <><span>{tool?.icon ?? '🧰'}</span> {t('tf_find_cta')}</>} </button>
        </div>
        <p className={`text-xs text-center ${c.textMuted} mt-2`}>
          {t('tf_xref_skillgap_pre')} <a href="/SkillGapMap" className={linkStyle}>{t('tf_skillgap_link')}</a> {t('tf_xref_skillgap_post')}
        </p>
      </div>

      {/* Error */} {error && (<div className={`${c.danger} border rounded-xl p-4 flex items-start gap-3`}>
          <span className="flex-shrink-0 mt-0.5">⚠️</span>
          <p className="text-sm">{error}</p>
        </div>
      )} {/* ══════════════════════════════════════════════════════════ */} {/* RESULTS                                                  */} {/* ══════════════════════════════════════════════════════════ */} {results && (<div className="space-y-4">
          <div ref={resultsRef} data-results-anchor />
          {/* ── UNDERSTANDING ── */} {r.understanding && (<div className={`${c.card} border ${c.border} rounded-xl p-5`}>
              <p className={`text-sm ${c.textSecondary} leading-relaxed`}>
                <span className={`font-bold ${c.text}`}>{t('tf_understanding_label')} </span>
                {r.understanding} </p>
            </div>
          )} {/* ── RECOMMENDATIONS ── */} {r.recommendations && r.recommendations.length > 0 && (<div className="space-y-3">
              <div className="flex items-center justify-between">
                <h3 className={`text-sm font-bold ${c.text}`}>
                  {r.recommendations.length === 1 ? t('tf_best_tool') : t('tf_top_tools', { count: r.recommendations.length })} </h3>

              </div>

              {r.recommendations.map((rec, idx) => (<a
                  key={rec.id} href={`/${rec.id}`} target="_blank"
                  rel="noopener noreferrer"
                  className="block no-underline group"
                >
                  <div className={`${c.card} border ${c.border} rounded-xl p-5 transition-all group-hover:shadow-md ${c.cardHover}`}>
                    {/* Tool header */} <div className="flex items-start gap-3 mb-3">
                      <span className="text-2xl flex-shrink-0">{rec.icon || '🔧'}</span>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 flex-wrap">
                          <h4 className={`text-base font-bold ${c.text} group-hover:underline`}>
                            {rec.title} </h4>
                          {idx === 0 && r.recommendations.length > 1 && (<span className={`text-[9px] font-bold px-2 py-0.5 rounded-full ${c.badge}`}>
                              {t('tf_best_match')}
                            </span>
                          )} <span className={`text-[9px] font-bold px-2 py-0.5 rounded-full ${c.badge}`}>
                            {rec.category} </span>
                        </div>
                      </div>
                      <span className={`text-sm ${c.textMuted} group-hover:translate-x-1 transition-transform flex-shrink-0`}>→</span>
                    </div>

                    {/* Why this tool */} <p className={`text-sm ${c.textSecondary} leading-relaxed mb-2`}>
                      {rec.why} </p>

                    {/* What to do */} {rec.what_to_do && (<div className={`${c.cardAlt} rounded-lg px-3 py-2 mt-2`}>
                        <p className={`text-xs ${c.textMuted}`}>
                          <span className="font-bold">{t('tf_quick_start')}</span> {rec.what_to_do} </p>
                      </div>
                    )} </div>
                </a>
              ))} </div>
          )} {/* ── WORKFLOW ── */} {r.workflow && (<div className={`${c.success} border rounded-xl p-4 flex items-start gap-3`}>
              <span className="flex-shrink-0 mt-0.5">🔗</span>
              <div>
                <p className={`text-xs font-bold mb-1`}>{t('tf_workflow_label')}</p>
                <p className={`text-sm leading-relaxed`}>{r.workflow}</p>
              </div>
            </div>
          )} {/* ── NO PERFECT FIT ── */} {r.no_perfect_fit && (<div className={`${c.card} border ${c.border} rounded-xl p-4`}>
              <p className={`text-xs font-bold ${c.textMuted} mb-1`}>{t('tf_closest_note')}</p>
              <p className={`text-sm ${c.textSecondary}`}>{r.no_perfect_fit}</p>
            </div>
          )} {/* ── CLARIFICATION ── */} {r.clarification && (<div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
              <p className={`text-xs font-bold ${c.textMuted} mb-1`}>{t('tf_clarification_label')}</p>
              <p className={`text-sm ${c.textSecondary}`}>{r.clarification}</p>
            </div>
          )} {/* ── BROWSE ALL ── */} <p className={`text-xs text-center ${c.textMuted}`}>{t('tf_ai_disclaimer')}</p>
          <div className={`text-center pt-2`}>
            <p className={`text-xs ${c.textMuted} mb-2`}>{t('tf_not_found')}</p>
            <a
              href="/"
              className={`text-sm font-bold underline ${linkStyle}`} >
              {t('tf_browse_all')}
            </a>
          </div>
        </div>
      )} {/* Conditional cross-ref — only after results */} {r?.workflow && (<div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
          <p className={`text-xs font-bold ${c.textMuted} mb-2`}>{t('tf_xref_workflow_label')}</p>
          <div className="flex flex-wrap gap-3">
            <a href="/TheRunthrough" className={`text-xs ${linkStyle}`}>{t('tf_xref_runthrough')}</a>
          </div>
        </div>
      )} {/* Always-on related tools */} <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
        <p className={`text-xs font-bold ${c.textMuted} mb-2`}>{t('tf_related')}</p>
        <div className="flex flex-wrap gap-3">
          <a href="/DecisionCoach" className={`text-xs ${linkStyle}`}>{t('tf_decision_coach')}</a>
          <a href="/OnePercenter" className={`text-xs ${linkStyle}`}>{t('tf_one_percenter')}</a>
        </div>
      </div>
      {/* Session sessionHistory */} {/* eslint-disable-next-line no-restricted-globals */} {sessionHistory.length > 0 && (<div className={`${c.cardAlt} border ${c.border} rounded-xl p-4 mt-4`}>
          <p className={`text-xs font-bold ${c.textMuted} mb-2`}>{t('tf_recent')}</p>
          <div className="space-y-1">
            {/* eslint-disable-next-line no-restricted-globals */} {sessionHistory.map(s => (<div key={s.id} className="flex items-center justify-between">
                <span className={`text-xs ${c.textSecondary} truncate`}>{s.preview || t('tf_session')}</span>
                <span className={`text-xs ${c.textMuted} ml-2 shrink-0`}>{new Date(s.date).toLocaleDateString()}</span>
              </div>
            ))} </div>
        </div>
      )} </div>
  );
};

ToolFinder.displayName = 'ToolFinder';
export default ToolFinder;
