import React, { useState, useEffect, useRef, useCallback } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';
import { pickExample } from '../utils/exampleRotation';
import { revealSection } from '../utils/revealSection';
import Caret from '../components/Caret';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

// Concern keys are stable across the V3 rewrite even though two labels
// changed ('visual_clutter' -> "Visual activity / clutter", 'parking' ->
// "Arrival / parking") — profiles saved under v2 keep working with no
// migration. personal_space, waiting, and other are new.
const CONCERNS = [
  { key: 'noise', labelKey: 'smm_con_noise', icon: '🔊' },
  { key: 'crowds', labelKey: 'smm_con_crowds', icon: '👥' },
  { key: 'lighting', labelKey: 'smm_con_lighting', icon: '💡' },
  { key: 'smells', labelKey: 'smm_con_smells', icon: '👃' },
  { key: 'temperature', labelKey: 'smm_con_temperature', icon: '🌡️' },
  { key: 'visual_clutter', labelKey: 'smm_con_visual_activity', icon: '🎯' },
  { key: 'personal_space', labelKey: 'smm_con_personal_space', icon: '🧍' },
  { key: 'waiting', labelKey: 'smm_con_waiting', icon: '🕓' },
  { key: 'parking', labelKey: 'smm_con_arrival_parking', icon: '🅿️' },
  { key: 'other', labelKey: 'smm_con_other', icon: '❓' },
];

// Required for Route mode — walking/driving/transit/cycling produce
// fundamentally different preparation advice, so this can't be left to a
// free-text field the visitor might skip. See ROUTE_SYSTEM's ROUTE MODE
// RULES for how the backend uses this.
const TRAVEL_MODES = [
  { value: 'walking', labelKey: 'smm_travel_walking', icon: '🚶' },
  { value: 'driving', labelKey: 'smm_travel_driving', icon: '🚗' },
  { value: 'public_transit', labelKey: 'smm_travel_transit', icon: '🚌' },
  { value: 'bicycle', labelKey: 'smm_travel_bicycle', icon: '🚲' },
  { value: 'other', labelKey: 'smm_travel_other', icon: '❓' },
];

const PLACE_TYPES = [
  { value: 'restaurant', labelKey: 'smm_pt_restaurant', icon: '🍽️' },
  { value: 'grocery', labelKey: 'smm_pt_grocery', icon: '🛒' },
  { value: 'store', labelKey: 'smm_pt_store', icon: '🏪' },
  { value: 'mall', labelKey: 'smm_pt_mall', icon: '🏬' },
  { value: 'cafe', labelKey: 'smm_pt_cafe', icon: '☕' },
  { value: 'airport', labelKey: 'smm_pt_airport', icon: '✈️' },
  { value: 'event', labelKey: 'smm_pt_event', icon: '🎤' },
  { value: 'movie_theater', labelKey: 'smm_pt_movie_theater', icon: '🎬' },
  { value: 'gym', labelKey: 'smm_pt_gym', icon: '🏋️' },
  { value: 'museum', labelKey: 'smm_pt_museum', icon: '🖼️' },
  { value: 'park', labelKey: 'smm_pt_park', icon: '🌳' },
  { value: 'hospital', labelKey: 'smm_pt_hospital', icon: '🏥' },
  { value: 'office', labelKey: 'smm_pt_office', icon: '🏢' },
  { value: 'library', labelKey: 'smm_pt_library', icon: '📚' },
  { value: 'other', labelKey: 'smm_pt_other', icon: '❓' },
];

// "What changed?" checkboxes for Conditions Changed — the visitor's own
// report, never a re-prediction. See backend RESCAN_SYSTEM.
const CHANGE_OPTIONS = [
  { key: 'louder', labelKey: 'smm_chg_louder' },
  { key: 'more_crowded', labelKey: 'smm_chg_crowded' },
  { key: 'brighter', labelKey: 'smm_chg_brighter' },
  { key: 'smell', labelKey: 'smm_chg_smell' },
  { key: 'temperature', labelKey: 'smm_chg_temperature' },
  { key: 'longer_wait', labelKey: 'smm_chg_wait' },
  { key: 'layout', labelKey: 'smm_chg_layout' },
  { key: 'other', labelKey: 'smm_chg_other' },
];

function TripRecon({ tool }) {
  const { isDark } = useTheme();
  const { callToolEndpoint, loading } = useClaudeAPI();
  const { t } = useTranslation();

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-400' : 'text-gray-500',
    required:      isDark ? 'text-amber-400' : 'text-amber-700',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    warningTxt:    isDark ? 'text-amber-300' : 'text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-200 text-red-800',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';

  // ── View ──
  const [view, setView] = useState('form'); // form | results | route (place-prep is the landing screen; route is a tab, not a separate page)
  const [error, setError] = useState('');

  // ── Place form ──
  const [location, setLocation] = useState('');
  const [placeType, setPlaceType] = useState('');
  const [visitDate, setVisitDate] = useState('');
  const [visitTime, setVisitTime] = useState('');
  const [concerns, setConcerns] = useState({});
  const [knownInfo, setKnownInfo] = useState('');
  const [specificNotes, setSpecificNotes] = useState('');
  const [results, setResults] = usePersistentState('sensoryminefieldmapper-result-v3', null);

  // ── Route form ──
  const [routeStart, setRouteStart] = useState('');
  const [routeDestination, setRouteDestination] = useState('');
  const [travelMode, setTravelMode] = useState('');
  const [routeWhen, setRouteWhen] = useState('');
  const [routeKnownInfo, setRouteKnownInfo] = useState('');
  const [routeResults, setRouteResults] = useState(null);
  const [routeLoading, setRouteLoading] = useState(false);

  // ── Panels ──
  const [showPanel, setShowPanel] = useState(null); // rescan | kit | ask | rate
  const [rescanChanged, setRescanChanged] = useState({});
  const [rescanOtherText, setRescanOtherText] = useState('');
  const [rescanResult, setRescanResult] = useState(null);
  const [rescanLoading, setRescanLoading] = useState(false);
  const [comfortKit, setComfortKit] = useState(null);
  const [kitLoading, setKitLoading] = useState(false);
  const [kitChecked, setKitChecked] = useState({});
  const [askNeed, setAskNeed] = useState('');
  const [askResult, setAskResult] = useState(null);
  const [askLoading, setAskLoading] = useState(false);

  // ── Rate this visit ("What was it actually like?") ──
  const [ratePerFactor, setRatePerFactor] = useState({});
  const [rateWhatHelped, setRateWhatHelped] = useState('');
  const [rateWhatDifferent, setRateWhatDifferent] = useState('');

  // ── Profiles ──
  const [showProfileForm, setShowProfileForm] = useState(false);
  const [profileName, setProfileName] = useState('');
  const [profileNotes, setProfileNotes] = useState('');
  const [profiles, setProfiles] = usePersistentState('smm-profiles', []);
  const [activeProfileNotes, setActiveProfileNotes] = useState('');

  // ── History ──
  const [sessionHistory, setSessionHistory] = usePersistentState('sensoryminefieldmapper-history', []);
  const [visitHistory, setVisitHistory] = usePersistentState('smm-history-v2', []);

  // ── Recent places ── continuity, not just history: unlike sessionHistory
  // (a plain query log) this is keyed one-per-place and carries forward what
  // the visitor actually reported about it — place type, concerns, and the
  // free-text fields — so a repeat visit doesn't start from zero. Never
  // auto-applied; picking one only offers a recap the visitor confirms or
  // discards (see selectedRecent below), because a wait time or a lighting
  // complaint was true of the last visit, not a fact about this one.
  const [recentPlaces, setRecentPlaces] = usePersistentState('smm-recent-places-v1', []);
  const [selectedRecent, setSelectedRecent] = useState(null);
  const [showAllRecent, setShowAllRecent] = useState(false);

  // Route mode's own Recent — same continuity idea, keyed on the
  // start→destination pair rather than a single place.
  const [recentRoutes, setRecentRoutes] = usePersistentState('smm-recent-routes-v1', []);
  const [selectedRecentRoute, setSelectedRecentRoute] = useState(null);
  const [showAllRecentRoutes, setShowAllRecentRoutes] = useState(false);

  const selectedConcerns = Object.entries(concerns).filter(([, v]) => v).map(([k]) => k);
  const concernLabel = (key) => { const con = CONCERNS.find(c2 => c2.key === key); return con ? t(con.labelKey) : key; };
  const placeTypeIcon = (val) => PLACE_TYPES.find(pt => pt.value === val)?.icon || '📍';
  const travelModeIcon = (val) => TRAVEL_MODES.find(tm => tm.value === val)?.icon || '🧭';
  const travelModeLabel = (val) => { const tm = TRAVEL_MODES.find(t2 => t2.value === val); return tm ? t(tm.labelKey) : val; };
  const today = new Date().toISOString().split('T')[0];

  const pastVisitsHere = visitHistory.filter(v => location.length > 3 && v.location?.toLowerCase().includes(location.toLowerCase().slice(0, 6)));

  // ════════════════════════════════════════
  // ACTIONS
  // ════════════════════════════════════════
  const loadProfile = (profile) => {
    const restored = {};
    (profile.concerns || []).forEach(k => { restored[k] = true; });
    setConcerns(restored);
    setActiveProfileNotes(profile.notes || '');
    setSelectedRecent(null);
  };

  const saveProfile = () => {
    if (!profileName.trim() || selectedConcerns.length === 0) return;
    setProfiles(prev => [...prev, { id: Date.now(), name: profileName.trim(), concerns: selectedConcerns, notes: profileNotes.trim() || '' }]);
    setProfileName(''); setProfileNotes(''); setShowProfileForm(false);
  };
  const deleteProfile = (id) => setProfiles(prev => prev.filter(p => p.id !== id));

  // One entry per place (matched on trimmed/lowercased name), most recent
  // first. Updates in place on a repeat search rather than growing forever.
  const rememberPlace = (loc, pType, cons, known, notes) => {
    const norm = loc.trim().toLowerCase();
    if (!norm) return;
    setRecentPlaces(prev => [
      { id: Date.now(), norm, location: loc.trim(), placeType: pType || '', concerns: cons, knownInfo: known || '', specificNotes: notes || '', lastVisit: new Date().toISOString() },
      ...prev.filter(p => p.norm !== norm),
    ].slice(0, 12));
  };

  // Picking a recent place restores the place itself AND which concerns
  // applied there — reselecting "noise" isn't claiming an observation, it's
  // just restating what the visitor cares about. Free-text notes are
  // different: a wait time or a lighting complaint was true of the LAST
  // visit, not a fact about this one, so those only surface as a recap the
  // visitor explicitly confirms (below) — never applied silently.
  const pickRecentPlace = (rec) => {
    setLocation(rec.location); setPlaceType(rec.placeType || '');
    const restored = {};
    (rec.concerns || []).forEach(k => { restored[k] = true; });
    setConcerns(restored);
    setSelectedRecent((rec.knownInfo || rec.specificNotes) ? rec : null);
  };
  const useRecentDetails = () => {
    if (!selectedRecent) return;
    setKnownInfo(selectedRecent.knownInfo || '');
    setSpecificNotes(selectedRecent.specificNotes || '');
    setSelectedRecent(null);
  };
  const startFreshFromRecent = () => setSelectedRecent(null);

  // Same split for routes: start/destination/travel-mode/concerns are
  // settled facts about the trip, restored immediately; the free-text note
  // is a past observation, gated the same way.
  const rememberRoute = (start, dest, mode, cons, known) => {
    const norm = `${start.trim().toLowerCase()}→${dest.trim().toLowerCase()}`;
    if (!start.trim() || !dest.trim()) return;
    setRecentRoutes(prev => [
      { id: Date.now(), norm, routeStart: start.trim(), routeDestination: dest.trim(), travelMode: mode || '', concerns: cons, knownInfo: known || '', lastVisit: new Date().toISOString() },
      ...prev.filter(r => r.norm !== norm),
    ].slice(0, 12));
  };
  const pickRecentRoute = (rec) => {
    setRouteStart(rec.routeStart); setRouteDestination(rec.routeDestination); setTravelMode(rec.travelMode || '');
    const restored = {};
    (rec.concerns || []).forEach(k => { restored[k] = true; });
    setConcerns(restored);
    setSelectedRecentRoute(rec.knownInfo ? rec : null);
  };
  const useRecentRouteDetails = () => {
    if (!selectedRecentRoute) return;
    setRouteKnownInfo(selectedRecentRoute.knownInfo || '');
    setSelectedRecentRoute(null);
  };
  const dismissRecentRoute = () => setSelectedRecentRoute(null);

  const resetAll = () => {
    setLocation(''); setPlaceType(''); setVisitDate(''); setVisitTime('');
    setConcerns({}); setKnownInfo(''); setSpecificNotes(''); setActiveProfileNotes('');
    setResults(null); setRouteResults(null); setError(''); setSelectedRecent(null); setShowAllRecent(false);
    setSelectedRecentRoute(null); setShowAllRecentRoutes(false);
    setShowPanel(null); setRescanResult(null); setRescanChanged({}); setRescanOtherText('');
    setComfortKit(null); setKitChecked({}); setAskResult(null); setAskNeed('');
    setRatePerFactor({}); setRateWhatHelped(''); setRateWhatDifferent('');
    setRouteStart(''); setRouteDestination(''); setTravelMode(''); setRouteWhen(''); setRouteKnownInfo('');
    setView('form');
  };

  const loadExample = () => {
    const ex = pickExample('SensoryScout', [
      { loc: 'smm_ex_location', type: 'grocery', concerns: { noise: true, crowds: true, lighting: true }, known: 'smm_ex_known', notes: '' },
      { loc: 'smm_ex2_location', type: 'hospital', concerns: { lighting: true, smells: true, temperature: true, waiting: true }, known: 'smm_ex2_known', notes: '' },
      { loc: 'smm_ex3_location', type: 'airport', concerns: { crowds: true, waiting: true, parking: true }, known: 'smm_ex3_known', notes: '' },
      { loc: 'smm_ex4_location', type: 'movie_theater', concerns: { noise: true, visual_clutter: true, personal_space: true }, known: 'smm_ex4_known', notes: '' },
      { loc: 'smm_ex5_location', type: 'event', concerns: { crowds: true, noise: true, other: true }, known: 'smm_ex5_known', notes: 'smm_ex5_notes' },
    ]);
    setLocation(t(ex.loc));
    setPlaceType(ex.type);
    setConcerns(ex.concerns);
    setKnownInfo(t(ex.known));
    setSpecificNotes(ex.notes ? t(ex.notes) : '');
    setSelectedRecent(null);
    setView('form');
    setError('');
  };

  const analyzeLocation = async () => {
    if (!location.trim()) { setError(t('smm_err_enter_location')); return; }
    if (selectedConcerns.length === 0) { setError(t('smm_err_select_concern')); return; }
    setError(''); setResults(null); setShowPanel(null);
    setRescanResult(null); setComfortKit(null); setKitChecked({}); setAskResult(null);
    try {
      const data = await callToolEndpoint('sensory-minefield-mapper', {
        location: location.trim(),
        placeType: placeType || undefined,
        visitDateTime: (visitDate || visitTime) ? `${visitDate || ''} ${visitTime || ''}`.trim() : undefined,
        concerns: selectedConcerns,
        knownInfo: knownInfo.trim() || undefined,
        specificNotes: specificNotes.trim() || undefined,
        profileNotes: activeProfileNotes || undefined,
        pastVisits: pastVisitsHere.slice(0, 3).map(v => ({ summary: v.whatHelped ? `Previous visit — what helped: ${v.whatHelped}` : '' })),
      });
      setResults({ ...data, location: location.trim(), placeType, concerns: selectedConcerns });
      // Exception: the 40 is a preview-string truncation length, not a history cap; history itself is capped at 6 below.
      setSessionHistory(prev => [{ id: Date.now(), date: new Date().toISOString(), preview: location.slice(0, 40) }, ...prev].slice(0, 6));
      rememberPlace(location, placeType, selectedConcerns, knownInfo.trim(), specificNotes.trim());
      setView('results');
    } catch (err) { setError(err.message || t('smm_err_analyze')); }
  };

  const planRoute = async () => {
    if (!routeStart.trim() || !routeDestination.trim()) { setError(t('smm_err_route_stops')); return; }
    if (!travelMode) { setError(t('smm_err_route_travel_mode')); return; }
    setRouteLoading(true); setRouteResults(null); setError('');
    try {
      const data = await callToolEndpoint('sensory-minefield-mapper/route', {
        stops: [{ location: routeStart.trim() }, { location: routeDestination.trim() }],
        travelMode,
        when: routeWhen || undefined,
        concerns: selectedConcerns,
        knownInfo: routeKnownInfo.trim() || undefined,
      });
      setRouteResults(data);
      rememberRoute(routeStart, routeDestination, travelMode, selectedConcerns, routeKnownInfo.trim());
    } catch (err) { setError(err.message || t('smm_err_route')); }
    finally { setRouteLoading(false); }
  };

  const fetchRescan = async () => {
    const changed = Object.entries(rescanChanged).filter(([, v]) => v).map(([k]) => k);
    if (!changed.length && !rescanOtherText.trim()) return;
    setRescanLoading(true); setRescanResult(null);
    try {
      const data = await callToolEndpoint('sensory-minefield-mapper/rescan', {
        location: results?.location || location,
        whatChanged: changed,
        otherText: rescanOtherText.trim() || undefined,
        originalPlanSummary: results?.summary?.one_liner,
        concerns: selectedConcerns,
      });
      setRescanResult(data);
    } catch (err) { setError(err.message || t('smm_err_rescan')); }
    finally { setRescanLoading(false); }
  };

  const fetchComfortKit = async () => {
    setKitLoading(true); setComfortKit(null); setKitChecked({});
    try {
      const data = await callToolEndpoint('sensory-minefield-mapper/comfort-kit', {
        concerns: selectedConcerns, placeType: results?.placeType || placeType,
        specificNotes: specificNotes.trim() || undefined,
      });
      setComfortKit(data); setShowPanel('kit');
    } catch (err) { setError(err.message || t('smm_err_kit')); }
    finally { setKitLoading(false); }
  };

  const fetchAskScript = async () => {
    if (!askNeed.trim()) return;
    setAskLoading(true); setAskResult(null);
    try {
      const data = await callToolEndpoint('sensory-minefield-mapper/ask-script', {
        need: askNeed.trim(), location: results?.location || location,
      });
      setAskResult(data);
    } catch (err) { setError(err.message || t('smm_err_ask')); }
    finally { setAskLoading(false); }
  };

  const saveVisitRating = () => {
    const entry = {
      id: Date.now(), date: new Date().toISOString(),
      location: results?.location || location, placeType: results?.placeType || placeType,
      perFactor: ratePerFactor, whatHelped: rateWhatHelped.trim(), whatDifferent: rateWhatDifferent.trim(),
    };
    setVisitHistory(prev => [entry, ...prev].slice(0, 6));
    setShowPanel(null); setRatePerFactor({}); setRateWhatHelped(''); setRateWhatDifferent('');
  };

  const buildFullText = useCallback(() => {
    if (!results) return '';
    const lines = [`🗺️ ${t('smm_title')} — ${results.summary?.heading || results.location}`, results.summary?.one_liner || '', ''];
    if (results.what_you_know?.length) { lines.push(t('smm_what_you_know') + ':'); results.what_you_know.forEach(k => lines.push(`• ${k}`)); lines.push(''); }
    if (results.worth_preparing_for?.length) {
      lines.push(t('smm_worth_preparing') + ':');
      results.worth_preparing_for.forEach(f => { lines.push(`${f.factor}: ${f.what_might_matter}`); f.prepare?.forEach(p => lines.push(`  - ${p}`)); });
      lines.push('');
    }
    if (results.before_you_go?.length) { lines.push(t('smm_before_you_go') + ':'); results.before_you_go.forEach(s => lines.push(`• ${s}`)); lines.push(''); }
    if (results.while_youre_there?.length) { lines.push(t('smm_while_there') + ':'); results.while_youre_there.forEach(s => lines.push(`• ${s}`)); lines.push(''); }
    if (results.things_you_could_ask?.length) { lines.push(t('smm_what_to_say') + ':'); results.things_you_could_ask.forEach(s => lines.push(`• ${s.situation} — "${s.script}"`)); lines.push(''); }
    if (results.backup_plan?.length) { lines.push(t('smm_plan_b') + ':'); results.backup_plan.forEach(s => lines.push(`• ${s}`)); lines.push(''); }
    if (results.unknowns_that_matter?.length) { lines.push(t('smm_unknowns') + ':'); results.unknowns_that_matter.forEach(s => lines.push(`• ${s}`)); }
    return lines.join('\n') + BRAND;
  }, [results, t]);

  const resultsRef = useRef(null);
  useRegisterActions(buildFullText(), tool?.title || 'Trip Recon');

  useEffect(() => {
    if (!results || !resultsRef.current) return;
    const timer = setTimeout(() => revealSection(resultsRef.current), 200);
    return () => clearTimeout(timer);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [results]);

  const analyzeLocationRef = useRef(null);
  const planRouteRef = useRef(null);
  const viewRef = useRef(null);
  const canSubmitRef = useRef(false);
  const canRouteRef = useRef(false);
  analyzeLocationRef.current = analyzeLocation;
  planRouteRef.current = planRoute;
  viewRef.current = view;
  canSubmitRef.current = !!(location.trim() && selectedConcerns.length > 0);
  canRouteRef.current = !!(routeStart.trim() && routeDestination.trim() && travelMode);

  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
        if (viewRef.current === 'route' && !routeLoading && canRouteRef.current) planRouteRef.current?.();
        else if (viewRef.current === 'form' && !loading && canSubmitRef.current) analyzeLocationRef.current?.();
      }
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading, routeLoading]);

  const toggleConcern = (key) => setConcerns(prev => ({ ...prev, [key]: !prev[key] }));

  // ═══════════════════════════════════════
  // RENDER
  // ═══════════════════════════════════════
  return (
    <div className={`space-y-4 ${c.text}`}>
      <div className={`${c.card} border ${c.border} rounded-xl p-5`}>
        <div className="pb-3 border-b border-zinc-500">
          <div className="flex items-center justify-between">
            <div>
              <h2 className={`text-xl font-bold ${c.text} flex items-center gap-2`}>
                <span className="me-2">{tool?.icon ?? '🗺️'}</span>{tool?.title ?? 'Trip Recon'}
              </h2>
              {/* i18n key, not tool?.tagline — the catalog tagline keeps its
                  leading emoji (toolTagline() convention), which would
                  double against the icon span just above it. */}
              <p className={`text-sm ${c.textSecondary}`}>{t('smm_tagline')}</p>
              {view === 'form' && (
                <button onClick={loadExample} className="mt-2 px-4 py-2 rounded-full text-sm font-semibold border border-black/25 text-zinc-900 shadow-sm hover:brightness-105 hover:shadow transition whitespace-nowrap" style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }}>✨ {t('try_example')}</button>
              )}
            </div>
            <button onClick={resetAll} className={`${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs font-bold flex-shrink-0`}>↺ {t('smm_start_over')}</button>
          </div>
        </div>
      </div>

      <div className="max-w-3xl mx-auto space-y-4">
        {error && <div className={`p-3 rounded-xl border ${c.danger}`}><span className="me-1">⚠️</span> {error}</div>}

        {/* ════════ MODE TABS + SHARED PANEL ════════ Place-prep is the
            landing screen; route is a real tab attached to the same panel,
            not a separate near-empty page. */}
        {(view === 'form' || view === 'route') && (
          <div className={`${c.card} border ${c.border} rounded-xl shadow-sm overflow-hidden`}>
            <div className={`flex border-b ${c.border}`}>
              <button onClick={() => setView('form')}
                className={`flex-1 py-3 text-sm font-bold text-center border-b-2 -mb-px transition-colors ${view === 'form' ? `${c.accentTxt} border-cyan-500 ${isDark ? 'bg-zinc-700/30' : 'bg-slate-50'}` : `${c.textMuted} border-transparent hover:${c.text}`}`}>
                🔍 {t('smm_scout_place')}
              </button>
              <button onClick={() => setView('route')}
                className={`flex-1 py-3 text-sm font-bold text-center border-b-2 -mb-px transition-colors ${view === 'route' ? `${c.accentTxt} border-cyan-500 ${isDark ? 'bg-zinc-700/30' : 'bg-slate-50'}` : `${c.textMuted} border-transparent hover:${c.text}`}`}>
                🧭 {t('smm_plan_route')}
              </button>
            </div>

            <div className="p-5 space-y-5">
              {/* ════════ PLACE FORM ════════ */}
              {view === 'form' && (
                <>
                  <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
                    <div className="flex items-center justify-between mb-2 gap-3">
                      <div>
                        <p className={`text-[10px] font-bold uppercase tracking-wider ${c.textMuteded}`}>👤 {t('smm_your_profiles')}</p>
                        <p className={`text-[10px] ${c.textMuteded} mt-0.5`}>{t('smm_profiles_hint')}</p>
                      </div>
                      <button onClick={() => setShowProfileForm(true)} className={`text-xs font-bold px-3 py-1.5 rounded-lg ${c.btnSecondary} whitespace-nowrap flex-shrink-0`}>{t('smm_new')}</button>
                    </div>
                    {profiles.length === 0 ? (
                      <p className={`text-xs ${c.textMuteded}`}>{t('smm_profiles_empty')}</p>
                    ) : (
                      <div className="flex flex-wrap gap-2">
                        {profiles.map(p => (
                          <div key={p.id} className="flex items-center gap-1">
                            <button onClick={() => loadProfile(p)} className={`px-3 py-1.5 rounded-full text-xs font-bold ${c.btnSecondary}`}>{p.name}</button>
                            <button onClick={() => deleteProfile(p.id)} className={`text-[9px] ${c.textMuteded} hover:text-zinc-400`}>✕</button>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>

                  {/* Recent — an input shortcut, so it comes before the
                      blank input it fills in, not after the submit button.
                      Hidden entirely with no history. */}
                  {recentPlaces.length > 0 && (
                    <div>
                      <p className={`text-[10px] font-bold uppercase tracking-wider mb-1.5 ${c.textMuteded}`}>{t('smm_recent')}</p>
                      <div className="space-y-2">
                        {(showAllRecent ? recentPlaces : recentPlaces.slice(0, 3)).map(rec => (
                          <button key={rec.id} onClick={() => pickRecentPlace(rec)}
                            className={`w-full text-start p-3 rounded-xl border transition-all ${selectedRecent?.id === rec.id ? (isDark ? 'border-cyan-500 bg-cyan-900/20' : 'border-cyan-500 bg-cyan-50') : (isDark ? 'border-zinc-600 hover:border-zinc-500' : 'border-zinc-200 hover:border-zinc-300')}`}>
                            <div className="flex items-center justify-between gap-2">
                              <div className="min-w-0">
                                <p className={`text-sm font-bold truncate ${c.text}`}>{placeTypeIcon(rec.placeType)} {rec.location}</p>
                                <p className={`text-[10px] ${c.textMuteded}`}>{t('smm_last_visit', { date: new Date(rec.lastVisit).toLocaleDateString() })}</p>
                                {rec.concerns?.length > 0 && <p className={`text-xs ${c.textSecondary} mt-0.5 truncate`}>{rec.concerns.map(k => concernLabel(k)).join(' · ')}</p>}
                              </div>
                              <span className={`text-xs font-bold ${c.accentTxt} flex-shrink-0`}>{t('smm_use_again')} →</span>
                            </div>
                          </button>
                        ))}
                      </div>
                      {!showAllRecent && recentPlaces.length > 3 && (
                        <button onClick={() => setShowAllRecent(true)} className={`text-xs font-bold mt-2 ${c.accentTxt}`}>{t('smm_see_all_recent')}</button>
                      )}
                    </div>
                  )}

                  {selectedRecent && (
                    <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4 space-y-2`}>
                      <p className={`text-[10px] font-bold uppercase tracking-wider ${c.accentTxt}`}>{t('smm_last_time_told_us')}</p>
                      {selectedRecent.knownInfo && <p className={`text-xs ${c.textSecondary}`}>“{selectedRecent.knownInfo}”</p>}
                      {selectedRecent.specificNotes && <p className={`text-xs ${c.textSecondary}`}>“{selectedRecent.specificNotes}”</p>}
                      <p className={`text-xs font-bold ${c.text}`}>{t('smm_still_relevant')}</p>
                      <div className="flex gap-2">
                        <button onClick={useRecentDetails} className={`flex-1 py-2 rounded-xl text-xs font-bold ${c.btnPrimary}`}>✓ {t('smm_use_these_again')}</button>
                        <button onClick={startFreshFromRecent} className={`flex-1 py-2 rounded-xl text-xs font-bold ${c.btnSecondary}`}>{t('smm_start_fresh')}</button>
                      </div>
                    </div>
                  )}

                  <div>
                    <label className={`block text-xs font-bold uppercase tracking-wider mb-1.5 ${c.textMuteded}`}>{t('smm_where_label')} <span className={c.required}>*</span></label>
                    <input type="text" value={location}
                      onChange={e => { setLocation(e.target.value); if (selectedRecent && e.target.value !== selectedRecent.location) setSelectedRecent(null); }}
                      placeholder={t('smm_where_ph')} className={`w-full p-3 border-2 rounded-xl focus:outline-none focus:ring-2 ${c.input}`} />
                    {pastVisitsHere.length > 0 && <p className={`text-xs mt-1.5 ${c.accentTxt}`}>📋 {t('smm_been_here_n', { count: pastVisitsHere.length })}</p>}
                  </div>

                  <div>
                    <label className={`block text-xs font-bold uppercase tracking-wider mb-1.5 ${c.textMuteded}`}>{t('smm_care_about')} <span className={c.required}>*</span></label>
                    <div className="grid grid-cols-3 sm:grid-cols-5 gap-2">
                      {CONCERNS.map(con => (
                        <button key={con.key} onClick={() => toggleConcern(con.key)}
                          className={`p-3 rounded-xl border text-center transition-all ${concerns[con.key] ? (isDark ? 'border-cyan-500 bg-cyan-900/20' : 'border-cyan-500 bg-cyan-50') : (isDark ? 'border-zinc-600 hover:border-zinc-500' : 'border-zinc-200 hover:border-zinc-300')}`}>
                          <span className="text-xl block">{con.icon}</span>
                          <span className={`text-xs font-bold ${c.text}`}>{t(con.labelKey)}</span>
                        </button>
                      ))}
                    </div>
                  </div>

                  <div>
                    <label className={`block text-xs font-bold uppercase tracking-wider mb-1.5 ${c.textMuteded}`}>{t('smm_known_label')} <span className={`text-xs font-normal normal-case ${c.textMuteded}`}>({t('smm_optional')})</span></label>
                    <textarea value={knownInfo} onChange={e => setKnownInfo(e.target.value)} placeholder={t('smm_known_ph')} rows={2} className={`w-full p-3 border-2 rounded-xl text-sm resize-y focus:outline-none focus:ring-2 ${c.input}`} />
                  </div>

                  <div>
                    <label className={`block text-xs font-bold uppercase tracking-wider mb-1.5 ${c.textMuteded}`}>{t('smm_anything_specific')} <span className={`text-xs font-normal normal-case ${c.textMuteded}`}>({t('smm_optional')})</span></label>
                    <textarea value={specificNotes} onChange={e => setSpecificNotes(e.target.value)} placeholder={t('smm_specific_ph')} rows={2} className={`w-full p-3 border-2 rounded-xl text-sm resize-y focus:outline-none focus:ring-2 ${c.input}`} />
                  </div>

                  {/* Place type + day/time — tucked away rather than removed.
                      Recent already carries placeType forward for a returning
                      visitor; a first-time visitor can still set either, but
                      neither blocks the one required question (concerns). */}
                  <details className={`group ${c.cardAlt} border ${c.border} rounded-xl p-4`}>
                    <summary className="cursor-pointer list-none [&::-webkit-details-marker]:hidden">
                      <div className={`flex items-center gap-2 text-xs font-bold uppercase tracking-wider ${c.textMuteded}`}>
                        + {t('smm_add_trip_details')}
                        <Caret groupOpen className="ms-auto" />
                      </div>
                    </summary>
                    <div className="space-y-4 mt-4">
                      <div>
                        <label className={`block text-xs font-bold uppercase tracking-wider mb-1.5 ${c.textMuteded}`}>{t('smm_type_of_place')} <span className={`text-xs font-normal normal-case ${c.textMuteded}`}>({t('smm_optional')})</span></label>
                        <div className="grid grid-cols-4 sm:grid-cols-5 gap-2">
                          {PLACE_TYPES.map(pt => (
                            <button key={pt.value} onClick={() => setPlaceType(placeType === pt.value ? '' : pt.value)}
                              className={`p-2 rounded-xl border text-center transition-all ${placeType === pt.value ? (isDark ? 'border-cyan-500 bg-cyan-900/20' : 'border-cyan-500 bg-cyan-50') : (isDark ? 'border-zinc-600 hover:border-zinc-500' : 'border-zinc-200 hover:border-zinc-300')}`}>
                              <span className="text-lg block">{pt.icon}</span>
                              <span className={`text-[10px] font-bold leading-tight block ${c.text}`}>{t(pt.labelKey)}</span>
                            </button>
                          ))}
                        </div>
                      </div>

                      <div className="grid grid-cols-2 gap-3">
                        <div>
                          <label className={`block text-xs font-bold uppercase tracking-wider mb-1.5 ${c.textMuteded}`}>{t('smm_what_day')} <span className={`text-xs font-normal normal-case ${c.textMuteded}`}>({t('smm_optional')})</span></label>
                          <input type="date" value={visitDate} onChange={e => setVisitDate(e.target.value)} min={today} className={`w-full p-3 border-2 rounded-xl focus:outline-none focus:ring-2 ${c.input}`} />
                        </div>
                        <div>
                          <label className={`block text-xs font-bold uppercase tracking-wider mb-1.5 ${c.textMuteded}`}>{t('smm_what_time')} <span className={`text-xs font-normal normal-case ${c.textMuteded}`}>({t('smm_optional')})</span></label>
                          <input type="time" value={visitTime} onChange={e => setVisitTime(e.target.value)} className={`w-full p-3 border-2 rounded-xl focus:outline-none focus:ring-2 ${c.input}`} />
                        </div>
                      </div>
                    </div>
                  </details>

                  <button title={t('cmd_enter')} onClick={analyzeLocation} disabled={loading} className={`relative w-full py-3.5 rounded-xl font-bold text-base ${c.btnPrimary} disabled:opacity-40`}>
                    {loading ? <span className="inline-block animate-spin">{tool?.icon ?? '🗺️'}</span> : <span className="me-2">🗺️</span>}
                    {loading ? t('smm_scouting') : t('smm_help_prepare')}
                    {!loading && (
                      <kbd aria-hidden="true"
                        className="hidden sm:flex items-center absolute end-3 top-1/2 -translate-y-1/2 px-1.5 py-0.5 rounded border border-white/30 bg-white/15 text-[10px] font-bold tracking-wide">
                        ⌘↵
                      </kbd>
                    )}
                  </button>

                  {selectedConcerns.length > 0 && (
                    <div>
                      {!showProfileForm ? (
                        <button onClick={() => setShowProfileForm(true)} className={`text-xs font-bold ${c.accentTxt}`}>💾 {t('smm_save_as_profile')}</button>
                      ) : (
                        <div className={`p-3 rounded-xl ${c.cardAlt} border space-y-2`}>
                          <label htmlFor="smm-profile-name" className="sr-only">{t('smm_profile_name_sr')}</label>
                          <input id="smm-profile-name" type="text" value={profileName} onChange={e => setProfileName(e.target.value)} placeholder={t('smm_profile_name_ph')} className={`w-full p-2.5 border-2 rounded-xl text-base ${c.input}`} />
                          <input type="text" value={profileNotes} onChange={e => setProfileNotes(e.target.value)} placeholder={t('smm_default_notes_ph')} className={`w-full p-2.5 border-2 rounded-xl text-base ${c.input}`} />
                          <div className="flex gap-2">
                            <button onClick={saveProfile} disabled={!profileName.trim()} className={`flex-1 py-2 rounded-xl text-xs font-bold ${c.btnPrimary} disabled:opacity-40`}>{t('smm_save_profile')}</button>
                            <button onClick={() => setShowProfileForm(false)} className={`py-2 px-4 rounded-xl text-xs font-bold ${c.btnSecondary}`}>{t('smm_cancel')}</button>
                          </div>
                        </div>
                      )}
                    </div>
                  )}
                </>
              )}

              {/* ════════ ROUTE FORM ════════ Mirrors the Place tab: no
                  repeated "Prepare for a Route" heading (the tab above
                  already says it), Recent before the blank inputs it fills
                  in, same settled-facts-vs-observations split. */}
              {view === 'route' && (
                <>
                  {recentRoutes.length > 0 && (
                    <div>
                      <p className={`text-[10px] font-bold uppercase tracking-wider mb-1.5 ${c.textMuteded}`}>{t('smm_recent')}</p>
                      <div className="space-y-2">
                        {(showAllRecentRoutes ? recentRoutes : recentRoutes.slice(0, 3)).map(rec => (
                          <button key={rec.id} onClick={() => pickRecentRoute(rec)}
                            className={`w-full text-start p-3 rounded-xl border transition-all ${selectedRecentRoute?.id === rec.id ? (isDark ? 'border-cyan-500 bg-cyan-900/20' : 'border-cyan-500 bg-cyan-50') : (isDark ? 'border-zinc-600 hover:border-zinc-500' : 'border-zinc-200 hover:border-zinc-300')}`}>
                            <div className="flex items-center justify-between gap-2">
                              <div className="min-w-0">
                                <p className={`text-sm font-bold truncate ${c.text}`}>{travelModeIcon(rec.travelMode)} {rec.routeStart} → {rec.routeDestination}</p>
                                <p className={`text-[10px] ${c.textMuteded}`}>{t('smm_last_used', { date: new Date(rec.lastVisit).toLocaleDateString() })} · {travelModeLabel(rec.travelMode)}</p>
                                {rec.concerns?.length > 0 && <p className={`text-xs ${c.textSecondary} mt-0.5 truncate`}>{rec.concerns.map(k => concernLabel(k)).join(' · ')}</p>}
                              </div>
                              <span className={`text-xs font-bold ${c.accentTxt} flex-shrink-0`}>{t('smm_use_again')} →</span>
                            </div>
                          </button>
                        ))}
                      </div>
                      {!showAllRecentRoutes && recentRoutes.length > 3 && (
                        <button onClick={() => setShowAllRecentRoutes(true)} className={`text-xs font-bold mt-2 ${c.accentTxt}`}>{t('smm_see_all_recent')}</button>
                      )}
                    </div>
                  )}

                  {selectedRecentRoute && (
                    <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4 space-y-2`}>
                      <p className={`text-[10px] font-bold uppercase tracking-wider ${c.accentTxt}`}>{t('smm_last_time_told_us')}</p>
                      {selectedRecentRoute.knownInfo && <p className={`text-xs ${c.textSecondary}`}>“{selectedRecentRoute.knownInfo}”</p>}
                      <p className={`text-xs font-bold ${c.text}`}>{t('smm_still_relevant')}</p>
                      <div className="flex gap-2">
                        <button onClick={useRecentRouteDetails} className={`flex-1 py-2 rounded-xl text-xs font-bold ${c.btnPrimary}`}>✓ {t('smm_use_these_again')}</button>
                        <button onClick={dismissRecentRoute} className={`flex-1 py-2 rounded-xl text-xs font-bold ${c.btnSecondary}`}>{t('smm_start_fresh')}</button>
                      </div>
                    </div>
                  )}

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    <div>
                      <label className={`block text-xs font-bold uppercase tracking-wider mb-1.5 ${c.textMuteded}`}>{t('smm_route_start')} <span className={c.required}>*</span></label>
                      <input type="text" value={routeStart}
                        onChange={e => { setRouteStart(e.target.value); if (selectedRecentRoute && e.target.value !== selectedRecentRoute.routeStart) setSelectedRecentRoute(null); }}
                        className={`w-full p-3 border-2 rounded-xl text-sm ${c.input}`} />
                    </div>
                    <div>
                      <label className={`block text-xs font-bold uppercase tracking-wider mb-1.5 ${c.textMuteded}`}>{t('smm_route_destination')} <span className={c.required}>*</span></label>
                      <input type="text" value={routeDestination}
                        onChange={e => { setRouteDestination(e.target.value); if (selectedRecentRoute && e.target.value !== selectedRecentRoute.routeDestination) setSelectedRecentRoute(null); }}
                        className={`w-full p-3 border-2 rounded-xl text-sm ${c.input}`} />
                    </div>
                  </div>
                  <div>
                    <label className={`block text-xs font-bold uppercase tracking-wider mb-1.5 ${c.textMuteded}`}>{t('smm_route_traveling')} <span className={c.required}>*</span></label>
                    <div className="grid grid-cols-3 sm:grid-cols-5 gap-2">
                      {TRAVEL_MODES.map(tm => (
                        <button key={tm.value} onClick={() => setTravelMode(tm.value)}
                          className={`p-2 rounded-xl border text-center transition-all ${travelMode === tm.value ? (isDark ? 'border-cyan-500 bg-cyan-900/20' : 'border-cyan-500 bg-cyan-50') : (isDark ? 'border-zinc-600 hover:border-zinc-500' : 'border-zinc-200 hover:border-zinc-300')}`}>
                          <div className="text-lg">{tm.icon}</div>
                          <div className={`text-[10px] font-semibold mt-0.5 ${c.textSecondary}`}>{t(tm.labelKey)}</div>
                        </button>
                      ))}
                    </div>
                  </div>
                  <div>
                    <label className={`block text-xs font-bold uppercase tracking-wider mb-1.5 ${c.textMuteded}`}>{t('smm_route_when')} <span className={`text-xs font-normal normal-case ${c.textMuteded}`}>({t('smm_optional')})</span></label>
                    <input type="text" value={routeWhen} onChange={e => setRouteWhen(e.target.value)} placeholder={t('smm_route_when_ph')} className={`w-full p-3 border-2 rounded-xl text-sm ${c.input}`} />
                  </div>
                  <div>
                    <label className={`block text-xs font-bold uppercase tracking-wider mb-1.5 ${c.textMuteded}`}>{t('smm_route_care_about')}</label>
                    <div className="flex flex-wrap gap-2">
                      {CONCERNS.map(con => (
                        <button key={con.key} onClick={() => toggleConcern(con.key)} className={`px-3 py-1.5 rounded-full text-xs font-bold ${concerns[con.key] ? c.btnPrimary : c.btnSecondary}`}>{con.icon} {t(con.labelKey)}</button>
                      ))}
                    </div>
                  </div>
                  <div>
                    {/* Own key, distinct from smm_known_label (used by the main
                        "Prepare for a Place" form) — reusing that key here said
                        "the place" on a screen asking about a route. */}
                    <label className={`block text-xs font-bold uppercase tracking-wider mb-1.5 ${c.textMuteded}`}>{t('smm_route_known_label')} <span className={`text-xs font-normal normal-case ${c.textMuteded}`}>({t('smm_optional')})</span></label>
                    <textarea value={routeKnownInfo} onChange={e => setRouteKnownInfo(e.target.value)} placeholder={t('smm_route_known_ph')} rows={2} className={`w-full p-3 border-2 rounded-xl text-sm resize-y ${c.input}`} />
                  </div>
                  <button title={t('cmd_enter')} onClick={planRoute} disabled={routeLoading} className={`relative w-full py-3.5 rounded-xl font-bold ${c.btnPrimary} disabled:opacity-40`}>
                    {routeLoading ? <span className="inline-block animate-spin">{tool?.icon ?? '🗺️'}</span> : <span className="me-2">🧭</span>}
                    {routeLoading ? t('smm_planning') : t('smm_plan_route_btn')}
                    {!routeLoading && (
                      <kbd aria-hidden="true"
                        className="hidden sm:flex items-center absolute end-3 top-1/2 -translate-y-1/2 px-1.5 py-0.5 rounded border border-white/30 bg-white/15 text-[10px] font-bold tracking-wide">
                        ⌘↵
                      </kbd>
                    )}
                  </button>
                </>
              )}
            </div>
          </div>
        )}

        {/* ════════ RESULTS ════════ */}
        {view === 'results' && results && (
          <div data-copy-results ref={resultsRef} className="scroll-mt-24 space-y-4">
            <div className={`${c.card} border-2 border-cyan-600/40 rounded-2xl p-5`}>
              <p className={`text-[10px] font-bold uppercase tracking-widest mb-1 ${c.accentTxt}`}>🗺️ {t('smm_your_plan')}</p>
              <h2 className={`text-xl font-black ${c.text}`}>{results.summary?.heading || results.location}</h2>
              <p className={`text-sm ${c.textSecondary} mt-1`}>{results.summary?.one_liner}</p>
            </div>

            {results.what_you_know?.length > 0 && (
              <div className={`${c.card} border ${c.border} rounded-2xl p-5`}>
                <p className={`text-xs font-bold uppercase tracking-wider mb-2 ${c.accentTxt}`}>📌 {t('smm_what_you_know')}</p>
                {results.what_you_know.map((k, i) => <p key={i} className={`text-sm ${c.textSecondary}`}>• {k}</p>)}
              </div>
            )}

            {results.worth_preparing_for?.length > 0 && (
              <div className={`${c.card} border ${c.border} rounded-2xl p-5 space-y-4`}>
                <p className={`text-xs font-bold uppercase tracking-wider ${c.accentTxt}`}>🧭 {t('smm_worth_preparing')}</p>
                {results.worth_preparing_for.map((f, i) => (
                  <div key={i} className={`${c.cardAlt} border rounded-xl p-4`}>
                    <p className={`text-sm font-black ${c.text} mb-1`}>{f.factor}</p>
                    <p className={`text-xs ${c.textSecondary} mb-2`}>{f.what_might_matter}</p>
                    {f.prepare?.map((p, pi) => <p key={pi} className={`text-xs ${c.textMuteded}`}>💡 {p}</p>)}
                  </div>
                ))}
              </div>
            )}

            {(results.before_you_go?.length > 0 || results.while_youre_there?.length > 0) && (
              <div className={`${c.card} border ${c.border} rounded-2xl p-5`}>
                {results.before_you_go?.length > 0 && (
                  <div className="mb-3">
                    <p className={`text-[10px] font-bold uppercase ${c.textMuteded} mb-1.5`}>🎒 {t('smm_before_you_go')}</p>
                    {results.before_you_go.map((s, i) => <p key={i} className={`text-xs ${c.textSecondary}`}>✓ {s}</p>)}
                  </div>
                )}
                {results.while_youre_there?.length > 0 && (
                  <div>
                    <p className={`text-[10px] font-bold uppercase ${c.textMuteded} mb-1.5`}>{t('smm_while_there')}</p>
                    {results.while_youre_there.map((s, i) => <p key={i} className={`text-xs ${c.textSecondary}`}>✓ {s}</p>)}
                  </div>
                )}
              </div>
            )}

            {results.things_you_could_ask?.length > 0 && (
              <div className={`${c.card} border ${c.border} rounded-2xl p-5`}>
                <p className={`text-xs font-bold uppercase tracking-wider mb-3 ${c.accentTxt}`}>💬 {t('smm_what_to_say')}</p>
                {results.things_you_could_ask.map((s, i) => (
                  <div key={i} className={`${c.cardAlt} border rounded-xl p-3 mb-2`}>
                    <p className={`text-xs ${c.textMuteded} mb-1`}>{s.situation}</p>
                    <p className={`text-sm italic ${c.text}`}>“{s.script}”</p>
                  </div>
                ))}
              </div>
            )}

            {results.backup_plan?.length > 0 && (
              <div className={`p-4 rounded-xl border-2 ${isDark ? 'border-amber-700/50 bg-amber-900/15' : 'border-amber-200 bg-amber-50'}`}>
                <p className={`text-xs font-bold uppercase mb-1.5 ${c.warningTxt}`}>🛡️ {t('smm_plan_b')}</p>
                {results.backup_plan.map((s, i) => <p key={i} className={`text-xs ${c.warningTxt}`}>{i + 1}. {s}</p>)}
              </div>
            )}

            {results.unknowns_that_matter?.length > 0 && (
              <div className={`${c.cardAlt} border ${c.border} rounded-2xl p-5`}>
                <p className={`text-xs font-bold uppercase tracking-wider mb-2 ${c.textMuteded}`}>❓ {t('smm_unknowns')}</p>
                {results.unknowns_that_matter.map((u, i) => <p key={i} className={`text-xs ${c.textMuteded}`}>• {u}</p>)}
              </div>
            )}

            {/* ── Action strip ── */}
            <div className="grid grid-cols-3 gap-2">
              <button onClick={() => setShowPanel(showPanel === 'rescan' ? null : 'rescan')} className={`py-2.5 rounded-xl text-xs font-bold ${c.btnSecondary}`}>🔄 {t('smm_conditions_changed')}</button>
              <button onClick={fetchComfortKit} disabled={kitLoading} className={`py-2.5 rounded-xl text-xs font-bold disabled:opacity-40 ${c.btnSecondary}`}>{kitLoading ? (tool?.icon ?? '🗺️') : '🎒'} {t('smm_comfort_kit')}</button>
              <button onClick={() => setShowPanel(showPanel === 'ask' ? null : 'ask')} className={`py-2.5 rounded-xl text-xs font-bold ${c.btnSecondary}`}>💬 {t('smm_help_me_ask')}</button>
            </div>
            <div className="flex justify-center">
              <button onClick={() => setShowPanel(showPanel === 'rate' ? null : 'rate')} className={`text-xs font-bold ${c.accentTxt}`}>⭐ {t('smm_rate_visit')}</button>
            </div>

            {/* ── Conditions Changed panel ── */}
            {showPanel === 'rescan' && (
              <div className={`${c.card} border-2 rounded-2xl p-5 ${isDark ? 'border-amber-700/50' : 'border-amber-300'}`}>
                <p className={`text-xs font-bold uppercase tracking-wider mb-3 ${c.accentTxt}`}>🔄 {t('smm_conditions_changed')}</p>
                <p className={`text-[10px] font-bold uppercase ${c.textMuteded} mb-2`}>{t('smm_what_changed')}</p>
                <div className="flex flex-wrap gap-2 mb-3">
                  {CHANGE_OPTIONS.map(opt => (
                    <button key={opt.key} onClick={() => setRescanChanged(prev => ({ ...prev, [opt.key]: !prev[opt.key] }))}
                      className={`px-3 py-1.5 rounded-full text-xs font-bold border ${rescanChanged[opt.key] ? (isDark ? 'border-amber-500 bg-amber-900/30 text-amber-200' : 'border-amber-500 bg-amber-100 text-amber-900') : (isDark ? 'border-zinc-600 text-zinc-300' : 'border-zinc-300 text-zinc-600')}`}>
                      {t(opt.labelKey)}
                    </button>
                  ))}
                </div>
                <textarea value={rescanOtherText} onChange={e => setRescanOtherText(e.target.value)} placeholder={t('smm_chg_other_ph')} rows={2} className={`w-full p-3 border-2 rounded-xl text-sm resize-y mb-3 ${c.input}`} />
                <button onClick={fetchRescan} disabled={rescanLoading} className={`w-full py-2.5 rounded-xl text-sm font-bold mb-3 ${c.btnPrimary} disabled:opacity-40`}>
                  {rescanLoading ? <span className="inline-block animate-spin">{tool?.icon ?? '🗺️'}</span> : t('smm_update_plan')}
                </button>
                {rescanResult && (
                  <div className="space-y-2">
                    <p className={`text-sm ${c.text}`}>{rescanResult.acknowledgment}</p>
                    {rescanResult.adjusted_plan?.map((a, i) => <p key={i} className={`text-xs font-bold ${c.text}`}>{i + 1}. {a}</p>)}
                    {rescanResult.still_applies_from_before?.length > 0 && (
                      <div className="mt-1">
                        <p className={`text-[10px] font-bold uppercase ${c.textMuteded}`}>{t('smm_still_applies')}</p>
                        {rescanResult.still_applies_from_before.map((a, i) => <p key={i} className={`text-xs ${c.textSecondary}`}>• {a}</p>)}
                      </div>
                    )}
                    {rescanResult.if_still_hard && <p className={`text-xs mt-1 ${c.warningTxt}`}>🛡️ {rescanResult.if_still_hard}</p>}
                    {/* Quick check — fixed, non-generated questions (not model output) */}
                    <div className={`mt-3 p-3 rounded-xl ${c.cardAlt} border`}>
                      <p className={`text-[10px] font-bold uppercase ${c.textMuteded} mb-1.5`}>{t('smm_quick_check')}</p>
                      <p className={`text-xs ${c.textSecondary}`}>• {t('smm_check_1')}</p>
                      <p className={`text-xs ${c.textSecondary}`}>• {t('smm_check_2')}</p>
                      <p className={`text-xs ${c.textSecondary}`}>• {t('smm_check_3')}</p>
                      <p className={`text-xs ${c.textSecondary}`}>• {t('smm_check_4')}</p>
                    </div>
                  </div>
                )}
              </div>
            )}

            {/* ── Comfort Kit panel ── */}
            {showPanel === 'kit' && comfortKit && (
              <div className={`${c.card} border-2 rounded-2xl p-5 ${isDark ? 'border-cyan-700/50' : 'border-cyan-300'}`}>
                <p className={`text-xs font-bold uppercase tracking-wider mb-3 ${c.accentTxt}`}>🎒 {t('smm_comfort_kit')}</p>
                {comfortKit.quick_note && <p className={`text-xs ${c.textSecondary} mb-3`}>💡 {comfortKit.quick_note}</p>}
                {[
                  { key: 'essentials', label: t('smm_kit_essentials'), items: comfortKit.essentials },
                  { key: 'comfort_items', label: t('smm_kit_comfort_items'), items: comfortKit.comfort_items },
                  { key: 'just_in_case', label: t('smm_kit_just_in_case'), items: comfortKit.just_in_case },
                ].filter(g => g.items?.length > 0).map(group => (
                  <div key={group.key} className="mb-3">
                    <p className={`text-[10px] font-bold ${c.textMuteded} mb-1.5`}>{group.label}</p>
                    {group.items.map((item, i) => {
                      const checkKey = `${group.key}-${i}`;
                      return (
                        <button key={i} onClick={() => setKitChecked(prev => ({ ...prev, [checkKey]: !prev[checkKey] }))}
                          className={`w-full text-start flex items-center gap-2.5 p-2 rounded-lg mb-1 ${kitChecked[checkKey] ? (isDark ? 'bg-emerald-900/20' : 'bg-emerald-50') : ''}`}>
                          <span className={`text-sm ${kitChecked[checkKey] ? '' : 'opacity-30'}`}>{kitChecked[checkKey] ? '✅' : '⬜'}</span>
                          <div className="flex-1 min-w-0">
                            <p className={`text-xs font-bold ${kitChecked[checkKey] ? (isDark ? 'text-emerald-400 line-through' : 'text-emerald-700 line-through') : c.text}`}>{item.item}</p>
                            <p className={`text-[10px] ${c.textMuteded}`}>{item.why}</p>
                          </div>
                          {item.priority === 'must_have' && <span className={`text-[8px] font-bold px-1.5 py-0.5 rounded-full ${isDark ? 'bg-red-900/30 text-red-300' : 'bg-red-100 text-red-700'}`}>{t('smm_kit_must')}</span>}
                        </button>
                      );
                    })}
                  </div>
                ))}
              </div>
            )}

            {/* ── Help Me Ask panel ── */}
            {showPanel === 'ask' && (
              <div className={`${c.card} border-2 rounded-2xl p-5 ${isDark ? 'border-cyan-700/50' : 'border-cyan-300'}`}>
                <p className={`text-xs font-bold uppercase tracking-wider mb-3 ${c.accentTxt}`}>💬 {t('smm_help_me_ask')}</p>
                <label htmlFor="smm-ask-need" className="sr-only">{t('smm_ask_need_sr')}</label>
                <textarea id="smm-ask-need" value={askNeed} onChange={e => setAskNeed(e.target.value)} placeholder={t('smm_ask_ph')} rows={2} className={`w-full p-3 border-2 rounded-xl text-sm resize-y mb-3 ${c.input}`} />
                <button onClick={fetchAskScript} disabled={askLoading || !askNeed.trim()} className={`w-full py-2.5 rounded-xl text-sm font-bold mb-3 ${c.btnPrimary} disabled:opacity-40`}>
                  {askLoading ? <span className="inline-block animate-spin">{tool?.icon ?? '🗺️'}</span> : t('smm_write_script')}
                </button>
                {askResult && (
                  <div className={`${c.cardAlt} border rounded-xl p-3`}>
                    <p className={`text-xs ${c.textMuteded} mb-1`}>{askResult.situation}</p>
                    <p className={`text-sm italic ${c.text}`}>“{askResult.script}”</p>
                  </div>
                )}
              </div>
            )}

            {/* ── Rate this visit panel ── */}
            {showPanel === 'rate' && (
              <div className={`${c.card} border-2 rounded-2xl p-5 ${isDark ? 'border-emerald-700/50' : 'border-emerald-300'}`}>
                <p className={`text-xs font-bold uppercase tracking-wider mb-3 ${c.accentTxt}`}>⭐ {t('smm_what_actually')}</p>
                {(results.concerns || selectedConcerns).map(key => (
                  <div key={key} className="mb-3">
                    <p className={`text-xs font-bold ${c.text} mb-1.5`}>{concernLabel(key)}</p>
                    <div className="flex gap-2">
                      {['lower', 'about', 'higher'].map(opt => (
                        <button key={opt} onClick={() => setRatePerFactor(prev => ({ ...prev, [key]: opt }))}
                          className={`flex-1 py-1.5 rounded-lg text-[10px] font-bold ${ratePerFactor[key] === opt ? c.btnPrimary : c.btnSecondary}`}>
                          {t(`smm_rate_${opt}`)}
                        </button>
                      ))}
                    </div>
                  </div>
                ))}
                <textarea value={rateWhatHelped} onChange={e => setRateWhatHelped(e.target.value)} placeholder={t('smm_what_helped_ph')} rows={2} className={`w-full p-3 border-2 rounded-xl text-sm resize-y mb-2 ${c.input}`} />
                <textarea value={rateWhatDifferent} onChange={e => setRateWhatDifferent(e.target.value)} placeholder={t('smm_what_different_ph')} rows={2} className={`w-full p-3 border-2 rounded-xl text-sm resize-y mb-3 ${c.input}`} />
                <button onClick={saveVisitRating} className={`w-full py-2.5 rounded-xl text-sm font-bold ${c.btnPrimary}`}>{t('smm_save_rating')}</button>
              </div>
            )}
          </div>
        )}

        {/* ════════ ROUTE RESULTS ════════ The route form itself now lives
            inside the shared tab panel above; this stays a separate
            sibling, same as Place mode's results view. */}
        {view === 'route' && routeResults && (
              <div className="space-y-4">
                <div className={`${c.card} border-2 border-cyan-600/40 rounded-2xl p-5`}>
                  <h2 className={`text-lg font-black ${c.text}`}>{routeResults.route_summary?.heading}</h2>
                  <p className={`text-sm ${c.textSecondary}`}>{routeResults.route_summary?.one_liner}</p>
                </div>
                {routeResults.stops?.map((stop, i) => (
                  <div key={i} className={`${c.card} border ${c.border} rounded-2xl p-4`}>
                    <p className={`text-sm font-black ${c.text} mb-2`}>{stop.stop}</p>
                    {stop.what_you_know?.map((k, ki) => <p key={ki} className={`text-xs ${c.textSecondary}`}>📌 {k}</p>)}
                    {stop.worth_preparing_for?.map((f, fi) => (
                      <div key={fi} className={`${c.cardAlt} border rounded-lg p-2.5 mt-2`}>
                        <p className={`text-xs font-bold ${c.text}`}>{f.factor}</p>
                        <p className={`text-xs ${c.textSecondary}`}>{f.what_might_matter}</p>
                        {f.prepare?.map((p, pi) => <p key={pi} className={`text-[10px] ${c.textMuteded}`}>💡 {p}</p>)}
                      </div>
                    ))}
                  </div>
                ))}
                {routeResults.before_you_leave?.length > 0 && (
                  <div className={`${c.card} border ${c.border} rounded-2xl p-4`}>
                    <p className={`text-[10px] font-bold uppercase ${c.textMuteded} mb-1.5`}>🎒 {t('smm_before_you_go')}</p>
                    {routeResults.before_you_leave.map((s, i) => <p key={i} className={`text-xs ${c.textSecondary}`}>✓ {s}</p>)}
                  </div>
                )}
                {routeResults.backup_plan?.length > 0 && (
                  <div className={`p-4 rounded-xl border-2 ${isDark ? 'border-amber-700/50 bg-amber-900/15' : 'border-amber-200 bg-amber-50'}`}>
                    <p className={`text-xs font-bold uppercase mb-1.5 ${c.warningTxt}`}>🛡️ {t('smm_plan_b')}</p>
                    {routeResults.backup_plan.map((s, i) => <p key={i} className={`text-xs ${c.warningTxt}`}>{i + 1}. {s}</p>)}
                  </div>
                )}
                {routeResults.unknowns_that_matter?.length > 0 && (
                  <div className={`${c.cardAlt} border ${c.border} rounded-2xl p-4`}>
                    <p className={`text-xs font-bold uppercase ${c.textMuteded} mb-1.5`}>❓ {t('smm_unknowns')}</p>
                    {routeResults.unknowns_that_matter.map((u, i) => <p key={i} className={`text-xs ${c.textMuteded}`}>• {u}</p>)}
                  </div>
                )}
              </div>
        )}

        {/* Fallback only: once Recent Places has anything, its cards
            supersede this plain log for the same information — this
            covers a returning visitor whose old sessionHistory predates
            that feature but who hasn't searched again yet. */}
        {sessionHistory.length > 0 && recentPlaces.length === 0 && view === 'form' && (
          <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
            <p className={`text-xs font-bold ${c.textMuted} mb-2`}>📋 {t('smm_recent')}</p>
            <div className="space-y-1">
              {sessionHistory.map(s => (
                <div key={s.id} className="flex items-center justify-between">
                  <span className={`text-xs ${c.textSecondary} truncate`}>{s.preview || t('smm_session')}</span>
                  <span className={`text-xs ${c.textMuted} ms-2`}>{new Date(s.date).toLocaleDateString()}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Pre-result cross-ref — at the foot, never above the form. */}
        {!results && (
          <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
            <p className={`text-[10px] font-bold ${c.textMuted} uppercase mb-2`}>🔗 {t('smm_related_tools')}</p>
            <div className="flex flex-wrap gap-3">
              <a href="/DecisionCoach" className={`text-xs ${linkStyle}`}>🎯 {t('smm_xref_decisioncoach')}</a>
            </div>
          </div>
        )}

        {/* Post-result cross-ref. */}
        {results && (
          <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
            <p className={`text-[10px] font-bold ${c.textMuted} uppercase mb-2`}>🔗 {t('smm_related_tools')}</p>
            <div className="flex flex-wrap gap-3">
              <a href="/DecisionCoach" className={`text-xs ${linkStyle}`}>🎯 {t('smm_xref_decisioncoach')}</a>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

TripRecon.displayName = 'TripRecon';
export default TripRecon;
