import React, { useState, useEffect, useCallback, useRef } from 'react';
import Caret from '../components/Caret';
import { useRegisterActions } from '../components/ActionBarContext';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { usePersistentState } from '../hooks/usePersistentState';
import { useTheme } from '../hooks/useTheme';
import { useTranslation } from '../i18n/useTranslation';
import { currencySymbol } from '../utils/formatLocale';
import { pickExample } from '../utils/exampleRotation';
import { revealSection } from '../utils/revealSection';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

const UpsellShield = ({ tool }) => {
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();
  const sym = currencySymbol(userLocale, userCurrency);

  const SITUATIONS = [
    { key: 'us_sit_car', emoji: '🚗' },
    { key: 'us_sit_phone', emoji: '📱' },
    { key: 'us_sit_furniture', emoji: '🛋️' },
    { key: 'us_sit_contractor', emoji: '🔨' },
    { key: 'us_sit_gym', emoji: '🏋️' },
    { key: 'us_sit_timeshare', emoji: '🏖️' },
    { key: 'us_sit_insurance', emoji: '📋' },
    { key: 'us_sit_realestate', emoji: '🏠' },
  ];

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-400' : 'text-gray-500',
    required:      isDark ? 'text-amber-400' : 'text-amber-700',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    // Waiting for input: an outline, not a smudge. Empty fill keeps "filled"
    // meaning "ready"; the border and label carry the visibility. Important
    // modifiers because tools carry their own border/text utilities on the
    // submit and Tailwind resolves conflicts by stylesheet order, not class
    // order. See the PF-13 exception in audit/audit_v2-3-2.py.
    btnIdle:       isDark ? '!bg-transparent !border-2 !border-cyan-500/85 !text-cyan-300 cursor-not-allowed'
                          : '!bg-transparent !border-2 !border-cyan-600/85 !text-cyan-800 cursor-not-allowed',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-200 text-red-800',
    pillInactive:  isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500' : 'border-gray-300 text-gray-500 hover:border-gray-400',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    // Tool-specific
    hookBg:        isDark ? 'bg-cyan-900/30 border-cyan-800' : 'bg-cyan-50 border-cyan-200',
    hookText:      isDark ? 'text-cyan-200' : 'text-cyan-800',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';

  // ─── State (useState before usePersistentState — PF-11/PF-14) ───
  const [whatYouWant, setWhatYouWant] = useState('');
  const [budget, setBudget] = useState('');
  const [concerns, setConcerns] = useState('');
  const [error, setError] = useState('');
  // Ground-up rewrite (2026-09-14): Watch For is prominent, not collapsible —
  // it's the tool's main content now. The three secondary sections start
  // collapsed so the page opens calm; Your Plan and Your Exit Line are
  // always visible and need no toggle at all.
  const [expandedSections, setExpandedSections] = useState({});

  // ─── Persistent state ───
  // -v2 keys: the old schema (their_playbook, the_real_deal, body_language,
  // the_nuclear_option) has nothing in common with this one — a restored v1
  // result would render mostly empty under the new UI.
  const [situation, setSituation] = usePersistentState('upsellshield-situation-v2', '');
  const [results, setResults] = usePersistentState('upsellshield-result-v2', null);
  const [sessionHistory, setSessionHistory] = usePersistentState('upsellshield-history-v2', []);

  const loadExample = () => {
    const ex = pickExample('UpsellShield', [
      { sit: 'us_ex_situation',  want: 'us_ex_want',  budget: 'us_ex_budget',  worry: 'us_ex_concerns' },
      { sit: 'us_ex2_situation', want: 'us_ex2_want', budget: 'us_ex2_budget', worry: 'us_ex2_concerns' },
      { sit: 'us_ex3_situation', want: 'us_ex3_want', budget: 'us_ex3_budget', worry: 'us_ex3_concerns' },
      { sit: 'us_ex4_situation', want: 'us_ex4_want', budget: 'us_ex4_budget', worry: 'us_ex4_concerns' },
      { sit: 'us_ex5_situation', want: 'us_ex5_want', budget: 'us_ex5_budget', worry: 'us_ex5_concerns' },
    ]);
    setSituation(t(ex.sit));
    setWhatYouWant(t(ex.want));
    setBudget(t(ex.budget, { sym }));
    setConcerns(t(ex.worry, { sym }));
  };

  const resultsRef = useRef(null);

  const toggleSection = useCallback((key) => {
    setExpandedSections(p => ({ ...p, [key]: !p[key] }));
  }, []);

  // Cmd/Ctrl+Enter submits — SELECT-only guard, ref pattern to avoid stale closures
  const generateRef = useRef(null);
  const canSubmitRef = useRef(false);
  canSubmitRef.current = !!situation.trim() && !loading;

  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && !loading && canSubmitRef.current) {
        e.preventDefault();
        generateRef.current?.();
      }
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, [loading]);

  const generate = useCallback(async (quickSit) => {
    const sit = quickSit || situation;
    if (!sit.trim()) return;
    setError(''); setResults(null);
    if (quickSit) { setSituation(quickSit); setWhatYouWant(''); setBudget(''); setConcerns(''); }
    try {
      const data = await callToolEndpoint('upsell-shield', {
        situation: sit.trim(),
        whatYouWant: whatYouWant.trim() || null,
        budget: budget.trim() || null,
        concerns: concerns.trim() || null,
        userLocale, userCurrency, userRegion,
      });
      setResults(data);
      // Full input + full result, not a truncated preview: this is what
      // lets a session card actually be reopened, and lets the Recent
      // Sessions preview show the real structure (want/budget) instead of
      // a raw text slice.
      setSessionHistory(prev => [{
        id: Date.now(), date: new Date().toISOString(),
        situation: sit.trim(),
        whatYouWant: whatYouWant.trim(),
        budget: budget.trim(),
        concerns: concerns.trim(),
        result: data,
      }, ...prev].slice(0, 6));
    } catch (err) { setError(err.message || t('us_error')); }
  }, [situation, whatYouWant, budget, concerns, callToolEndpoint, setError, setResults, setSituation, setWhatYouWant, setBudget, setConcerns, setSessionHistory, userLocale, userCurrency, userRegion, t]);

  // Keep generateRef fresh every render so the keyboard handler always invokes the latest closure
  generateRef.current = generate;

  const handleReset = useCallback(() => {
    setSituation(''); setWhatYouWant(''); setBudget('');
    setConcerns(''); setResults(null); setError('');
  }, [setSituation, setWhatYouWant, setBudget, setConcerns, setResults, setError]);

  const openSession = useCallback((s) => {
    setSituation(s.situation || '');
    setWhatYouWant(s.whatYouWant || '');
    setBudget(s.budget || '');
    setConcerns(s.concerns || '');
    setResults(s.result || null);
    setError('');
  }, [setSituation, setWhatYouWant, setBudget, setConcerns, setResults, setError]);

  const buildFullText = useCallback(() => {
    if (!results) return '';
    const r = results;
    let text = `🛡️ ${t('us_copy_header')}: ${situation}\n`;
    if (r.your_plan?.length) {
      text += `\n${t('us_copy_plan')}\n`;
      r.your_plan.forEach(item => { text += `\n• ${item}`; });
    }
    if (r.exit_line) text += `\n\n${t('us_copy_exitline')} ${r.exit_line}`;
    if (r.watch_for?.length) {
      text += `\n\n${t('us_copy_watchfor')}\n`;
      r.watch_for.forEach((w, i) => {
        text += `\n${i + 1}. ${w.moment}\n${t('us_copy_mighthappen')} ${w.what_might_happen}\n${t('us_copy_response')} ${w.your_response}\n`;
      });
    }
    if (r.questions_worth_asking?.length) {
      text += `\n${t('us_copy_questions')}\n`;
      r.questions_worth_asking.forEach(q => { text += `\n• ${q.question}`; });
    }
    if (r.before_you_commit?.length) {
      text += `\n\n${t('us_copy_commit')}\n`;
      r.before_you_commit.forEach(item => { text += `\n☐ ${item}`; });
    }
    if (r.if_pressure_continues) text += `\n\n${t('us_copy_ifpressure')} ${r.if_pressure_continues}`;
    return text + BRAND;
  }, [results, situation, t]);

  // ─── Register export content (component-level hook) ───
  useRegisterActions(results ? buildFullText() : '', tool?.title);

  // ─── Scroll to results ───
  useEffect(() => {
    if (!results) return;
    const timer = setTimeout(() => revealSection(resultsRef.current), 100);
    return () => clearTimeout(timer);
  }, [results]);

  const r = results;

  return (
    <div className={`space-y-4 ${c.text}`}>
      <div className={`${c.card} border ${c.border} rounded-xl p-6`}>
        <div className={`mb-5 pb-4 border-b ${c.border} flex items-start justify-between gap-3`}>
          <div>
            {/* PF-30 — the wrapper already prints the name as the page <h1>. */}
            <p className={`text-base ${c.textSecondary}`}>
              <span className="me-2 text-xl">{tool?.icon ?? '🛡️'}</span>{t('us_tagline')}
            </p>
            <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className="mt-2 px-4 py-2 rounded-full text-sm font-semibold border border-black/25 text-zinc-900 shadow-sm hover:brightness-105 hover:shadow transition disabled:opacity-40 whitespace-nowrap">✨ {t('try_example')}</button>
          </div>
          {(results || situation.trim()) && (
            <button onClick={handleReset} className={`flex-shrink-0 ${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs font-medium`}>
              ↺ {t('start_over')}
            </button>
          )}
        </div>

        {/* Opening hook */}
        <div className={`${c.hookBg} border rounded-xl p-4 mb-4`}>
          <p className={`text-sm font-medium ${c.hookText}`}>
            {t('us_hook')}
          </p>
        </div>

        <div className="mb-4">
          <label className={`text-sm font-bold ${c.text} block mb-1.5`}>{t('us_q_situation')} <span className={c.required}>*</span></label>
          <input type="text" value={situation} onChange={e => setSituation(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && situation.trim() && !loading && generate()}
            placeholder={t('us_ph_situation')}
            className={`w-full px-4 py-3 border rounded-xl text-sm ${c.input} ${c.border} ${c.text} outline-none focus:ring-2`} />
        </div>

        {!results && (
          <div className="mb-4">
            <p className={`text-xs font-bold ${c.textMuted} mb-2`}>{t('us_common')}</p>
            <div className="flex flex-wrap gap-1.5">
              {SITUATIONS.map(s => (
                <button key={s.key} onClick={() => generate(t(s.key))} disabled={loading}
                  className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors min-h-[32px] ${c.pillInactive} disabled:opacity-40`}>
                  {s.emoji} {t(s.key)}
                </button>
              ))}
            </div>
          </div>
        )}

        <div className="mb-4">
          <label className={`text-sm font-bold ${c.text} block mb-1.5`}>{t('us_q_want')} <span className={`font-normal ${c.textMuted}`}>({t('optional')})</span></label>
          <input type="text" value={whatYouWant} onChange={e => setWhatYouWant(e.target.value)}
            placeholder={t('us_ph_want', { sym })}
            className={`w-full px-4 py-3 border rounded-xl text-sm ${c.input} ${c.border} ${c.text} outline-none focus:ring-2`} />
        </div>

        <div className="mb-4">
          <label className={`text-sm font-bold ${c.text} block mb-1.5`}>{t('us_q_budget')} <span className={`font-normal ${c.textMuted}`}>({t('optional')})</span></label>
          <input type="text" value={budget} onChange={e => setBudget(e.target.value)}
            placeholder={t('us_ph_budget', { sym })}
            className={`w-full px-4 py-3 border rounded-xl text-sm ${c.input} ${c.border} ${c.text} outline-none focus:ring-2`} />
        </div>

        <div className="mb-5">
          <label className={`text-sm font-bold ${c.text} block mb-1.5`}>{t('us_q_concerns')} <span className={`font-normal ${c.textMuted}`}>({t('optional')})</span></label>
          <input type="text" value={concerns} onChange={e => setConcerns(e.target.value)}
            placeholder={t('us_ph_concerns')}
            className={`w-full px-4 py-3 border rounded-xl text-sm ${c.input} ${c.border} ${c.text} outline-none focus:ring-2`} />
        </div>

        <p className={`text-xs text-center ${c.textMuted} mb-2`}>
          {t('us_xref_pre')} <a href="/FakeReviewDetective" className={linkStyle}>🔍 {t('us_xref_fakereview')}</a> {t('us_xref_post')}
        </p>

        <div className="flex gap-3">
          <button title={t('cmd_enter')} onClick={() => generate()} disabled={loading || !situation.trim()}
            className={`relative flex-1 ${(!situation.trim()) ? c.btnIdle : c.btnPrimary} disabled:cursor-not-allowed font-bold py-3 px-6 rounded-xl flex items-center justify-center gap-2 min-h-[48px] shadow-lg`}>
            {loading ? <><span className="inline-block animate-spin text-xl">{tool?.icon ?? '🛡️'}</span> {t('us_arming')}</> : <><span className="text-xl">{tool?.icon ?? '🛡️'}</span> {t('us_prepare')}</>}
          {!loading && (
            <kbd aria-hidden="true"
              className="hidden sm:flex items-center absolute end-3 top-1/2 -translate-y-1/2 px-1.5 py-0.5 rounded border border-white/30 bg-white/15 text-[10px] font-bold tracking-wide">
              ⌘↵
            </kbd>
          )}
          </button>
        </div>

        {/* Try Example */}
        {!situation.trim() && !loading && (
          <div className="flex justify-center mt-3">
            <button
              onClick={loadExample}
              className={`text-xs font-medium ${c.textSecondary} underline underline-offset-2 min-h-[32px]`}
            >
              ✨ {t('try_example')}
            </button>
          </div>
        )}

        <p className={`text-xs text-center ${c.textMuted} mt-1`}>{t('us_disclaimer')}</p>
      </div>

      {error && (
        <div className={`${c.danger} border rounded-xl p-4 flex items-start gap-3`}>
          <span className="flex-shrink-0 mt-0.5">⚠️</span><p className="text-sm">{error}</p>
        </div>
      )}

      {results && (
        <div className="space-y-4">
          <div data-copy-results ref={resultsRef} data-results-anchor  className="scroll-mt-24"/>

          {/* Your Plan — first result, always visible. Begin with the
              user's own footing, not the seller's presumed intentions. */}
          {r.your_plan?.length > 0 && (
            <div className={`${c.card} border ${c.border} rounded-xl p-5`}>
              <h3 className={`text-sm font-bold ${c.text} mb-3 flex items-center gap-2`}><span>🧭</span> {t('us_plan_title')}</h3>
              <div className="space-y-1.5">
                {r.your_plan.map((item, i) => (
                  <p key={i} className={`text-sm ${c.textSecondary}`}>• {item}</p>
                ))}
              </div>
            </div>
          )}

          {/* Your exit line — prominent */}
          {r.exit_line && (
            <div className={`${c.warning} border rounded-xl p-4`}>
              <p className="text-[10px] font-bold mb-1">{t('us_exitline_label')}</p>
              <p className="text-sm font-bold leading-relaxed">{r.exit_line}</p>
            </div>
          )}

          {/* Watch For — prominent, not collapsible; this is the tool's main content now */}
          {r.watch_for?.length > 0 && (
            <div className={`${c.card} border ${c.border} rounded-xl p-4`}>
              <h3 className={`text-sm font-bold ${c.text} mb-3 flex items-center gap-2`}>
                <span>👀</span> {t('us_watchfor_title')}
              </h3>
              <div className="space-y-3">
                {r.watch_for.map((w, i) => (
                  <div key={i} className={`${c.cardAlt} rounded-xl p-4`}>
                    <h4 className={`text-xs font-bold ${c.text} mb-2`}>{i + 1}. {w.moment}</h4>
                    <p className={`text-xs ${c.textSecondary} mb-2`}><span className="font-bold">{t('us_mighthappen')}</span> {w.what_might_happen}</p>
                    <p className={`text-xs ${c.textMuted} mb-2 italic`}><span className="font-bold">{t('us_whydifficult')}</span> {w.why_it_can_be_difficult}</p>
                    <div className={`${c.success} border rounded-lg p-3`}>
                      <p className="text-[10px] font-bold mb-0.5">{t('us_your_response')}</p>
                      <p className="text-xs font-medium">{w.your_response}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Questions worth asking */}
          {r.questions_worth_asking?.length > 0 && (
            <div className={`${c.card} border ${c.border} rounded-xl overflow-hidden`}>
              <button onClick={() => toggleSection('questions')}
                className="w-full p-4 flex items-center justify-between text-start min-h-[44px]">
                <h3 className={`text-sm font-bold ${c.text} flex items-center gap-2`}><span>❓</span> {t('us_questions_title')}</h3>
                <Caret open={expandedSections.questions} />
              </button>
              {expandedSections.questions && (
                <div className={`px-4 pb-4 border-t ${c.border} pt-3 space-y-3`}>
                  {r.questions_worth_asking.map((q, i) => (
                    <div key={i} className={`${c.cardAlt} rounded-lg p-3`}>
                      <p className={`text-xs font-bold ${c.text} mb-1`}>{q.question}</p>
                      <p className={`text-xs ${c.textMuted} italic`}>{q.why_it_helps}</p>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* Before you commit */}
          {r.before_you_commit?.length > 0 && (
            <div className={`${c.card} border ${c.border} rounded-xl overflow-hidden`}>
              <button onClick={() => toggleSection('commit')}
                className="w-full p-4 flex items-center justify-between text-start min-h-[44px]">
                <h3 className={`text-sm font-bold ${c.text} flex items-center gap-2`}><span>📋</span> {t('us_commit_title')}</h3>
                <Caret open={expandedSections.commit} />
              </button>
              {expandedSections.commit && (
                <div className={`px-4 pb-4 border-t ${c.border} pt-3 space-y-1.5`}>
                  {r.before_you_commit.map((item, i) => (
                    <p key={i} className={`text-xs ${c.textSecondary}`}>☐ {item}</p>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* If pressure continues */}
          {r.if_pressure_continues && (
            <div className={`${c.card} border ${c.border} rounded-xl overflow-hidden`}>
              <button onClick={() => toggleSection('pressure')}
                className="w-full p-4 flex items-center justify-between text-start min-h-[44px]">
                <h3 className={`text-sm font-bold ${c.text} flex items-center gap-2`}><span>🚪</span> {t('us_pressure_title')}</h3>
                <Caret open={expandedSections.pressure} />
              </button>
              {expandedSections.pressure && (
                <div className={`px-4 pb-4 border-t ${c.border} pt-3`}>
                  <p className={`text-sm ${c.textSecondary} leading-relaxed`}>{r.if_pressure_continues}</p>
                </div>
              )}
            </div>
          )}

          <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
            <p className={`text-xs font-bold ${c.textMuted} mb-2`}>{t('us_also_useful')}</p>
            <div className="flex flex-wrap gap-3">
              <a href="/MarkupDetective" className={`text-xs ${linkStyle}`}>🔍 {t('us_xref_markup')}</a>
            </div>
          </div>
        </div>
      )}

      {/* Recent sessions — each card reopens the complete past result. */}
      {sessionHistory.length > 0 && (() => {
        const validSessions = sessionHistory.filter(s => s.result);
        if (!validSessions.length) return null;
        return (
          <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4 mt-4`}>
            <p className={`text-xs font-bold ${c.textMuted} mb-2`}>{t('us_recent')}</p>
            <div className="space-y-1.5">
              {validSessions.map(s => (
                <button
                  key={s.id}
                  onClick={() => openSession(s)}
                  className={`w-full text-start ${c.card} border ${c.border} rounded-lg px-3 py-2.5 hover:brightness-105 transition`}
                >
                  <p className={`text-xs font-semibold ${c.text} truncate`}>{s.situation}</p>
                  {(s.whatYouWant || s.budget) && (
                    <p className={`text-[10px] ${c.textMuted} mt-0.5 truncate`}>
                      {[s.whatYouWant, s.budget].filter(Boolean).join(' · ')}
                    </p>
                  )}
                  <div className="flex items-center justify-between mt-1">
                    {s.concerns ? (
                      <p className={`text-[10px] ${c.textMuted} truncate`}>{t('us_q_concerns')}: {s.concerns}</p>
                    ) : <span />}
                    <span className={`text-[10px] ${c.textMuted} ms-2 shrink-0`}>{new Date(s.date).toLocaleDateString()}</span>
                  </div>
                </button>
              ))}
            </div>
          </div>
        );
      })()}
    </div>
  );
};

UpsellShield.displayName = 'UpsellShield';
export default UpsellShield;
