import React, { useState, useEffect, useRef } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

const RELATIONSHIPS = [
  { value: 'boss', tKey: 'vh_rel_boss' },
  { value: 'colleague', tKey: 'vh_rel_colleague' },
  { value: 'direct_report', tKey: 'vh_rel_direct_report' },
  { value: 'client', tKey: 'vh_rel_client' },
  { value: 'vendor', tKey: 'vh_rel_vendor' },
  { value: 'landlord', tKey: 'vh_rel_landlord' },
  { value: 'neighbor', tKey: 'vh_rel_neighbor' },
  { value: 'family', tKey: 'vh_rel_family' },
  { value: 'friend', tKey: 'vh_rel_friend' },
  { value: 'other', tKey: 'vh_rel_other' },
];

const GOALS = [
  { value: 'behavior_change', tKey: 'vh_goal_behavior_change' },
  { value: 'apology', tKey: 'vh_goal_apology' },
  { value: 'compensation', tKey: 'vh_goal_compensation' },
  { value: 'set_boundary', tKey: 'vh_goal_set_boundary' },
  { value: 'clarify', tKey: 'vh_goal_clarify' },
  { value: 'escalate', tKey: 'vh_goal_escalate' },
];

const POWER = [
  { value: 'i_have_leverage', tKey: 'vh_power_leverage' },
  { value: 'neutral', tKey: 'vh_power_neutral' },
  { value: 'they_have_power', tKey: 'vh_power_they' },
];

const EXAMPLES = [
  {
    draft: "This is the THIRD time this month you've sent me a 'final' contract that you then change two days later. Do you have any idea how much time I'm wasting reviewing the same document over and over because YOU can't get your act together? Stop sending me half-baked drafts.",
    relationship: 'vendor',
    goal: 'behavior_change',
    power: 'i_have_leverage',
  },
  {
    draft: "I cannot believe you scheduled a 90-minute meeting for something that could have been a 3-line email. I have actual work to do and now my entire afternoon is destroyed. This is ridiculous.",
    relationship: 'colleague',
    goal: 'behavior_change',
    power: 'neutral',
  },
];
const VelvetHammer = ({ tool }) => {
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();

  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-400' : 'text-gray-500',
    required:      isDark ? 'text-amber-400' : 'text-amber-700',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-200 text-red-800',
    rageBg:        isDark ? 'bg-red-900/10 border-red-800/30' : 'bg-red-50 border-red-200',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';

  // ─── State (useState before usePersistentState — PF-11/PF-14) ───
  const [relationship, setRelationship] = useState('colleague');
  const [goal, setGoal] = useState('behavior_change');
  const [power, setPower] = useState('neutral');
  const [error, setError] = useState('');
  const [showHistory, setShowHistory] = useState(false);

  // ─── Persistent state ───
  const [draft, setDraft] = usePersistentState('velvethammer-draft', '');
  const [results, setResults] = usePersistentState('velvethammer-result', null);
  const [sessionHistory, setSessionHistory] = usePersistentState('velvethammer-history', []);

  const resultsRef = useRef(null);

  const loadExample = () => {
    const ex = EXAMPLES[Math.floor(Math.random() * EXAMPLES.length)];
    setDraft(ex.draft);
    setRelationship(ex.relationship);
    setGoal(ex.goal);
    setPower(ex.power);
  };

  const handleTransform = async () => {
    if (!draft.trim()) return;
    setError('');
    setResults(null);
    try {
      const data = await callToolEndpoint('velvet-hammer', {
        draft: draft.trim(), relationship, goal, power,
        userLocale, userCurrency, userRegion,
      });
      setResults(data);
      setSessionHistory(prev => [{
        id: Date.now(), date: new Date().toISOString(),
        // PF-25 exception: 40-char preview-text truncation; session history is capped at 6.
        preview: draft.trim().slice(0, 40),
        result: data,
      }, ...prev].slice(0, 6));
    } catch (err) {
      setError(err.message || t('vh_error'));
    } };

  // ─── Keyboard: SELECT-only guard with stale-closure-safe refs ───
  const handleTransformRef = useRef(null);
  const canSubmitRef = useRef(false);
  handleTransformRef.current = handleTransform;
  canSubmitRef.current = !!draft.trim() && !loading;

  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && !loading && canSubmitRef.current) {
        e.preventDefault();
        handleTransformRef.current?.();
      }
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, [loading]);

  const handleReset = () => { setResults(null); setError(''); setDraft(''); };

  const buildAllText = () => {
    if (!results?.variants) return '';
    return results.variants.map(v => `${v.label}:\n${v.message}`).join('\n\n---\n\n') + BRAND;
  };

  // ─── Register export content ───
  useRegisterActions(results ? buildAllText() : '', tool?.title);

  // ─── Scroll to results ───
  useEffect(() => {
    if (!results) return;
    const timer = setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 100);
    return () => clearTimeout(timer);
  }, [results]);

  const toneColor = (tone) => {
    if (tone === 'collaborative') return isDark ? 'text-emerald-400' : 'text-emerald-600';
    if (tone === 'balanced') return isDark ? 'text-amber-400' : 'text-amber-600';
    return isDark ? 'text-red-400' : 'text-red-600';
  };

  const toneBg = (tone) => {
    if (tone === 'collaborative') return isDark ? 'bg-emerald-900/20 border-emerald-700' : 'bg-emerald-50 border-emerald-300';
    if (tone === 'balanced') return isDark ? 'bg-amber-900/20 border-amber-700' : 'bg-amber-50 border-amber-300';
    return isDark ? 'bg-red-900/20 border-red-700' : 'bg-red-50 border-red-200';
  };

  return (<div className={`space-y-4 ${c.text}`}>

      {/* Header */} {/* Input card */} <div className={`${c.card} border ${c.border} rounded-xl shadow-sm p-5 space-y-4`}>

        {/* Header inside card */} <div className={`flex items-center justify-between pb-3 border-b ${c.border}`}>
          <div>
            <h2 className={`text-2xl font-bold ${c.text}`}>
              <span className="mr-2">{tool?.icon ?? '🔨'}</span>{tool?.title ?? t('vh_title')} </h2>
            <p className={`text-sm ${c.textSecondary} mt-0.5`}>{tool?.tagline ?? t('vh_tagline')}</p>
            <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className={`mt-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium border disabled:opacity-40 ${isDark ? 'text-white border-white/40' : 'text-gray-800 border-transparent'}`}>{t('try_example')}</button>
          </div>
          <div className="flex items-center gap-2 flex-shrink-0">
            {sessionHistory.length > 0 && (<button onClick={() => setShowHistory(!showHistory)} className={`text-xs font-bold px-3 py-1.5 rounded-lg ${c.btnSecondary}`}>
                📋 {sessionHistory.length} </button>
            )}
            {(results || draft.trim()) && (
              <button onClick={handleReset} className={`${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs font-bold`}>
                ↺ {t('start_over')}
              </button>
            )}
          </div> </div>

        {/* History panel */} {showHistory && sessionHistory.length > 0 && (<div className={`${c.cardAlt} border ${c.border} rounded-xl p-4 space-y-2`}>
            <p className={`text-xs font-bold ${c.textMuted} mb-1`}>{t('vh_recent')}</p>
            {sessionHistory.map(h => (<div key={h.id} className={`flex items-center justify-between text-xs ${c.textSecondary}`}>
                <span className="truncate">{h.preview}</span>
                <span className={`ml-2 shrink-0 ${c.textMuted}`}>{new Date(h.date).toLocaleDateString()}</span>
              </div>
            ))} </div>
        )} {/* Rage box */} <div>
          <label className={`text-sm font-semibold ${c.text} block mb-2`}>
            🤬 <em>{t('vh_rage_label')}</em> <span className={c.required}>*</span>
          </label>
          <p className={`text-xs ${c.textMuted} mb-2`}>{t('vh_rage_hint')}</p>
          <textarea
            value={draft} onChange={e => setDraft(e.target.value)} placeholder={t('vh_rage_ph')}
            rows={5} className={`w-full p-3 border rounded-lg text-sm resize-none outline-none focus:ring-2 transition-colors ${c.input} ${c.rageBg}`} />
        </div>

        {/* Context row */} <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          <div>
            <label className={`text-xs font-semibold ${c.labelText} block mb-1.5`}>{t('vh_recipient')}</label>
            <select value={relationship} onChange={e => setRelationship(e.target.value)} className={`w-full p-2.5 border rounded-lg text-sm outline-none ${c.input}`}>
              {RELATIONSHIPS.map(r => <option key={r.value} value={r.value}>{t(r.tKey)}</option>)} </select>
          </div>
          <div>
            <label className={`text-xs font-semibold ${c.labelText} block mb-1.5`}>{t('vh_goal')}</label>
            <select value={goal} onChange={e => setGoal(e.target.value)} className={`w-full p-2.5 border rounded-lg text-sm outline-none ${c.input}`}>
              {GOALS.map(g => <option key={g.value} value={g.value}>{t(g.tKey)}</option>)} </select>
          </div>
          <div>
            <label className={`text-xs font-semibold ${c.labelText} block mb-1.5`}>{t('vh_power')}</label>
            <select value={power} onChange={e => setPower(e.target.value)} className={`w-full p-2.5 border rounded-lg text-sm outline-none ${c.input}`}>
              {POWER.map(p => <option key={p.value} value={p.value}>{t(p.tKey)}</option>)} </select>
          </div>
        </div>

        <button
          onClick={handleTransform} disabled={loading || !draft.trim()} className={`w-full py-3 rounded-xl font-semibold text-sm flex items-center justify-center gap-2 transition-all disabled:opacity-40 ${c.btnPrimary}`}>
          {loading
            ? <><span className="inline-block animate-spin">{tool?.icon ?? '🔨'}</span> {t('vh_transforming')}</>
            : <><span>{tool?.icon ?? '🔨'}</span> {t('vh_transform')}</>} </button>



        <p className={`text-xs text-center ${c.textMuted}`}>{t('vh_disclaimer')}</p>
        <p className={`text-xs text-center ${c.textMuted} mt-1`}>
          {t('vh_in_person_pre')} <a href="/DifficultTalkCoach" className={linkStyle}>🗣️ {t('vh_difficult_talk')}</a> {t('vh_in_person_post')}
        </p>

        {error && <div className={`p-3 rounded-lg border text-sm ${c.danger}`}>⚠️ {error}</div>} </div>

      {/* Results */} {results && (<div className="space-y-4">
          <div ref={resultsRef} data-results-anchor />

          {/* Rage audit */} {results.rage_audit && (<div className={`${c.warning} border rounded-xl p-4`}>
              <p className={`text-xs font-bold mb-1`}>🔬 {t('vh_rage_audit')}</p>
              <p className={`text-sm`}>{results.rage_audit}</p>
            </div>
          )} {/* Variants */} {results.variants?.map((variant, i) => (<div key={i} className={`${c.card} border ${c.border} rounded-xl p-5 space-y-3`}>
              <div className="flex items-center justify-between">
                <div>
                  <span className={`text-sm font-bold ${toneColor(variant.tone)}`}>{variant.label}</span>
                  {variant.when_to_use && (<p className={`text-xs ${c.textMuted} mt-0.5`}>{variant.when_to_use}</p>
                  )} </div>
                <span className={`text-xs px-2 py-1 rounded-full border font-medium ${toneBg(variant.tone)}`}>
                  {variant.label} </span>
              </div>
              <div className={`${isDark ? 'bg-zinc-900/50' : 'bg-slate-100'} rounded-lg p-4`}>
                <p className={`text-sm ${c.text} whitespace-pre-wrap leading-relaxed`}>{variant.message}</p>
              </div>
            </div>
          ))} {/* Cross-tool links */} <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
            <p className={`text-xs font-bold ${c.textMuted} mb-2`}>🔗 {t('vh_related')}</p>
            <div className="flex flex-wrap gap-3">
              <a href="/ConflictCoach" className={`text-xs ${linkStyle}`}>⚔️ {t('vh_conflict_coach')}</a>
              <a href="/ComebackCooker" className={`text-xs ${linkStyle}`}>🗣️ {t('vh_comeback_cooker')}</a>
            </div>
          </div>
        </div>
      )} </div>
  );
};

VelvetHammer.displayName = 'VelvetHammer';
export default VelvetHammer;
