import React, { useState, useEffect, useRef, useCallback } from 'react';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';

// ─── Duration presets (labelKey resolved via t() at render time) ───
const DURATIONS = [
  { min: 15, labelKey: 'vbd_dur_15', icon: '⚡' },
  { min: 25, labelKey: 'vbd_dur_25', icon: '🍅' },
  { min: 45, labelKey: 'vbd_dur_45', icon: '☕' },
  { min: 60, labelKey: 'vbd_dur_60', icon: '📚' },
  { min: 90, labelKey: 'vbd_dur_90', icon: '🎯' },
];

const CHECK_IN_FREQS = [
  { min: 10, labelKey: 'vbd_freq_10' },
  { min: 15, labelKey: 'vbd_freq_15' },
  { min: 20, labelKey: 'vbd_freq_20' },
  { min: 30, labelKey: 'vbd_freq_30' },
];

const ENVIRONMENTS = [
  { id: 'home_desk', icon: '🏠', labelKey: 'vbd_env_home_desk' },
  { id: 'coffee_shop', icon: '☕', labelKey: 'vbd_env_coffee_shop' },
  { id: 'library', icon: '📚', labelKey: 'vbd_env_library' },
  { id: 'office', icon: '🏢', labelKey: 'vbd_env_office' },
  { id: 'couch', icon: '🛋️', labelKey: 'vbd_env_couch' },
  { id: 'bed', icon: '🛏️', labelKey: 'vbd_env_bed' },
];

const MOODS = [
  { id: 'focused', icon: '🎯', labelKey: 'vbd_mood_focused' },
  { id: 'scattered', icon: '🌀', labelKey: 'vbd_mood_scattered' },
  { id: 'tired', icon: '😴', labelKey: 'vbd_mood_tired' },
  { id: 'anxious', icon: '😰', labelKey: 'vbd_mood_anxious' },
  { id: 'motivated', icon: '🔥', labelKey: 'vbd_mood_motivated' },
  { id: 'neutral', icon: '😐', labelKey: 'vbd_mood_neutral' },
];

const STATUS_OPTIONS = [
  { id: 'on_track', icon: '✅', labelKey: 'vbd_status_on_track' },
  { id: 'drifting', icon: '🌊', labelKey: 'vbd_status_drifting' },
  { id: 'stuck', icon: '🧱', labelKey: 'vbd_status_stuck' },
  { id: 'ahead', icon: '🚀', labelKey: 'vbd_status_ahead' },
  { id: 'taking_break', icon: '☕', labelKey: 'vbd_status_taking_break' },
];

// ─── Session Modes (v4) — label/desc resolved via t() at render time ───
const SESSION_MODES = [
  { id: 'default',          icon: '👥', labelKey: 'vbd_mode_default',          descKey: 'vbd_mode_default_desc',          defaultFreq: 15 },
  { id: 'deep_work',        icon: '🧘', labelKey: 'vbd_mode_deep_work',        descKey: 'vbd_mode_deep_work_desc',        defaultFreq: 30 },
  { id: 'sprint',           icon: '⚡', labelKey: 'vbd_mode_sprint',           descKey: 'vbd_mode_sprint_desc',           defaultFreq: 10 },
  { id: 'grind',            icon: '⛏️', labelKey: 'vbd_mode_grind',            descKey: 'vbd_mode_grind_desc',            defaultFreq: 15 },
  { id: 'creative',         icon: '🎨', labelKey: 'vbd_mode_creative',         descKey: 'vbd_mode_creative_desc',         defaultFreq: 20 },
  { id: 'avoidance_buster', icon: '🌱', labelKey: 'vbd_mode_avoidance_buster', descKey: 'vbd_mode_avoidance_buster_desc', defaultFreq: 10 },
];

// Mode-specific color accents for active session
const MODE_COLORS = {
  default:          { bar: 'bg-cyan-500',    glow: 'shadow-cyan-500/20',    badge: 'bg-cyan-500' },
  deep_work:        { bar: 'bg-cyan-600',    glow: 'shadow-cyan-600/20',    badge: 'bg-cyan-600' },
  sprint:           { bar: 'bg-amber-500',   glow: 'shadow-amber-500/20',   badge: 'bg-amber-500' },
  grind:            { bar: 'bg-zinc-500',    glow: 'shadow-zinc-500/20',    badge: 'bg-zinc-600' },
  creative:         { bar: 'bg-cyan-500',  glow: 'shadow-cyan-500/20',  badge: 'bg-cyan-500' },
  avoidance_buster: { bar: 'bg-emerald-500', glow: 'shadow-emerald-500/20', badge: 'bg-emerald-500' },
};

// ─── Sound helper (Web Audio API — no external files) ───
const playChime = () => {
  try {
    const ctx = new (window.AudioContext || window.webkitAudioContext)();
    const osc = ctx.createOscillator();
    const gain = ctx.createGain();
    osc.connect(gain);
    gain.connect(ctx.destination);
    osc.type = 'sine';
    osc.frequency.setValueAtTime(587, ctx.currentTime);
    osc.frequency.setValueAtTime(784, ctx.currentTime + 0.12);
    gain.gain.setValueAtTime(0.15, ctx.currentTime);
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.5);
    osc.start(ctx.currentTime);
    osc.stop(ctx.currentTime + 0.5);
  } catch (e) { /* audio not available */ }
};

const sendNotification = (title, body) => {
  try {
    if (Notification.permission === 'granted') {
      new Notification(title, { body, icon: '👥' });
    } } catch (e) { /* notifications not available */ }
};

// Example seeds — text fields resolved via t() at load time (locale-aware).
const EXAMPLES = [
  {
    taskKey: 'vbd_ex1_task',
    duration: 25,
    checkInFreq: 15,
    environmentKey: 'vbd_ex1_environment',
    moodKey: 'vbd_ex1_mood',
    goalsKey: 'vbd_ex1_goals',
    sessionMode: 'default',
  },
  {
    taskKey: 'vbd_ex2_task',
    duration: 45,
    checkInFreq: 20,
    environmentKey: 'vbd_ex2_environment',
    moodKey: 'vbd_ex2_mood',
    goalsKey: 'vbd_ex2_goals',
    sessionMode: 'default',
  },
];
const VirtualBodyDouble = ({ tool }) => {
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();

  // ─── Color config ───
  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-400' : 'text-gray-500',
    required:      isDark ? 'text-amber-400' : 'text-amber-700',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white' : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200' : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200' : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200' : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200' : 'bg-red-50 border-red-200 text-red-800',
    // ── Bespoke keys ──
    tag:            isDark ? 'bg-zinc-700 text-zinc-300 hover:bg-zinc-600 border-zinc-600' : 'bg-gray-100 text-gray-600 hover:bg-gray-200 border-gray-200',
    tagActive:      isDark ? 'bg-cyan-900/40 text-cyan-200 border-cyan-600' : 'bg-cyan-100 text-cyan-800 border-cyan-400',
    cardHover:      isDark ? 'hover:bg-zinc-700' : 'hover:bg-gray-50',
    accentLight:    isDark ? 'bg-cyan-900/25 border-cyan-700' : 'bg-cyan-50 border-cyan-200',
    accentLightText: isDark ? 'text-cyan-300' : 'text-cyan-800',
    errorText:      isDark ? 'text-red-300' : 'text-red-700',
    bubbleBg:       isDark ? 'bg-zinc-700' : 'bg-gray-100',
    bubbleText:     isDark ? 'text-zinc-100' : 'text-gray-800',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;
  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';


  // ─── State: View ───
  const [view, setView] = useState('setup');
  const [error, setError] = useState('');

  // ─── State: Setup ───
  const [task, setTask] = useState('');
  const [duration, setDuration] = useState(25);
  const [customDuration, setCustomDuration] = useState('');
  const [checkInFreq, setCheckInFreq] = useState(15);
  const [environment, setEnvironment] = useState('');
  const [mood, setMood] = useState('');
  const [goals, setGoals] = useState('');
  const [sessionMode, setSessionMode] = useState('default');

  // ─── State: Task breakdown ───
  const [subTasks, setSubTasks] = useState([]);
  const [subTaskChecked, setSubTaskChecked] = useState({});
  const [showBreakdown, setShowBreakdown] = useState(false);
  const [breakdownData, setBreakdownData] = useState(null);

  // ─── State: Active session ───
  const [sessionPlan, setSessionPlan] = useState(null);
  const [secondsRemaining, setSecondsRemaining] = useState(0);
  const [secondsElapsed, setSecondsElapsed] = useState(0);
  const [isPaused, setIsPaused] = useState(false);
  const [checkInsDone, setCheckInsDone] = useState(0);
  const [showCheckIn, setShowCheckIn] = useState(false);
  const [, setCheckInResponse] = useState(null);
  const [checkInNote, setCheckInNote] = useState('');
  const [chatLog, setChatLog] = useState([]);
  const [isOnBreak, setIsOnBreak] = useState(false);
  const [breakSecondsRemaining, setBreakSecondsRemaining] = useState(0);
  const [moodAfter, setMoodAfter] = useState('');
  const [completionNote, setCompletionNote] = useState('');
  const [completionData, setCompletionData] = useState(null);
  const [stuckData, setStuckData] = useState(null);
  const [, setExtendData] = useState(null);
  const [inviteData, setInviteData] = useState(null);
  const [reviewData, setReviewData] = useState(null);

  // ─── State: Card (v4) ───
  const [cardData, setCardData] = useState(null);
  const [showCard, setShowCard] = useState(false);

  // ─── State: Sound & notifications ───
  const [soundEnabled, setSoundEnabled] = usePersistentState('vbd-sound', true);
  const [notificationsEnabled, setNotificationsEnabled] = useState(false);
  const [buddyTyping, setBuddyTyping] = useState(false);

  // ─── State: Persistent ───
  const [sessionLog, setSessionLog] = usePersistentState('vbd-session-log', []);

  // ─── Refs ───
  const loadExample = () => {
    const ex = EXAMPLES[Math.floor(Math.random() * EXAMPLES.length)];
    setTask(t(ex.taskKey));
    setDuration(ex.duration);
    setCheckInFreq(ex.checkInFreq);
    setEnvironment(t(ex.environmentKey));
    setMood(t(ex.moodKey));
    setGoals(t(ex.goalsKey));
    setSessionMode(ex.sessionMode);
  };

  const timerRef = useRef(null);
  const breakTimerRef = useRef(null);
  const resultsRef = useRef(null);
  const ambientTimerRef = useRef(null);
  const chatEndRef = useRef(null);
  const nextCheckInRef = useRef(0);
  const completeRef = useRef(null);
  const ambientMsgsRef = useRef([]);
  const ambientIndexRef = useRef(0);

  // ─── Computed ───
  const actualDuration = customDuration ? parseInt(customDuration) || 25 : duration;
  const totalCheckIns = Math.max(1, Math.floor(actualDuration / checkInFreq));
  const currentSubTask = subTasks.length > 0 ? subTasks.find((_, i) => !subTaskChecked[i]) : null;
  const subTasksCompleted = Object.values(subTaskChecked).filter(Boolean).length;
  const modeColors = MODE_COLORS[sessionMode] || MODE_COLORS.default;
  const modeLabel = t(SESSION_MODES.find(m => m.id === sessionMode)?.labelKey || 'vbd_mode_default');

  // Auto-scroll chat
  useEffect(() => { chatEndRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [chatLog, buddyTyping]);

  // Notification permission
  useEffect(() => {
    if (notificationsEnabled && typeof Notification !== 'undefined' && Notification.permission === 'default') {
      Notification.requestPermission();
    } }, [notificationsEnabled]);

  // ─── Helpers ───
  const formatTime = (secs) => {
    const m = Math.floor(secs / 60);
    const s = secs % 60;
    return `${m}:${s.toString().padStart(2, '0')}`;
  };

  const addChat = useCallback((from, message, emoji) => {
    setChatLog(prev => [...prev, { from, message, emoji, time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }]);
  }, []);

  const addBuddyMessage = useCallback((message, emoji, delay = 0) => {
    setTimeout(() => {
      setBuddyTyping(true);
      setTimeout(() => {
        setBuddyTyping(false);
        addChat('buddy', message, emoji);
      }, 600 + Math.random() * 800);
    }, delay);
  }, [addChat]);

  // ─── Timer logic ───
  useEffect(() => {
    if (view !== 'active' || isPaused || isOnBreak) return;
    timerRef.current = setInterval(() => {
      setSecondsRemaining(prev => {
        if (prev <= 1) { clearInterval(timerRef.current); completeRef.current?.(); return 0; } return prev - 1;
      });
      setSecondsElapsed(prev => {
        const next = prev + 1;
        const minutesElapsed = Math.floor(next / 60);
        if (minutesElapsed > 0 && minutesElapsed % checkInFreq === 0 && minutesElapsed / checkInFreq > nextCheckInRef.current) {
          nextCheckInRef.current = minutesElapsed / checkInFreq;
          setShowCheckIn(true);
          if (soundEnabled) playChime();
          if (notificationsEnabled) sendNotification(t('vbd_notif_checkin_title'), t('vbd_notif_checkin_body'));
        } return next;
      });
    }, 1000);
    return () => clearInterval(timerRef.current);
  }, [view, isPaused, isOnBreak, checkInFreq, soundEnabled, notificationsEnabled, t]);

  // ─── Ambient presence ───
  useEffect(() => {
    if (view !== 'active' || isPaused || isOnBreak) return;
    const msgs = ambientMsgsRef.current;
    if (!msgs?.length) return;
    // Deep work mode: longer gaps
    const isDeep = sessionMode === 'deep_work';
    const minDelay = isDeep ? 90000 : 45000;
    const maxDelay = isDeep ? 240000 : 120000;
    const scheduleNext = () => {
      const delay = minDelay + Math.random() * (maxDelay - minDelay);
      ambientTimerRef.current = setTimeout(() => {
        const msg = msgs[ambientIndexRef.current % msgs.length];
        ambientIndexRef.current++;
        setBuddyTyping(true);
        setTimeout(() => { setBuddyTyping(false); addChat('buddy', msg, null); }, 400);
        scheduleNext();
      }, delay);
    };
    const initDelay = setTimeout(scheduleNext, isDeep ? 40000 : 20000);
    return () => { clearTimeout(initDelay); clearTimeout(ambientTimerRef.current); };
  }, [view, isPaused, isOnBreak, addChat, sessionMode]);

  // ─── Break timer ───
  useEffect(() => {
    if (!isOnBreak) return;
    breakTimerRef.current = setInterval(() => {
      setBreakSecondsRemaining(prev => {
        if (prev <= 1) {
          clearInterval(breakTimerRef.current);
          setIsOnBreak(false);
          if (soundEnabled) playChime();
          addChat('buddy', sessionPlan?.break_suggestion?.return_message || t('vbd_chat_break_over'));
          return 0;
        } return prev - 1;
      });
    }, 1000);
    return () => clearInterval(breakTimerRef.current);
  }, [isOnBreak, soundEnabled, addChat, sessionPlan, t]);

  // ─── API: Task breakdown ───
  const handleBreakdown = async () => {
    if (!task.trim()) { setError(t('vbd_err_enter_task')); return; } setError('');
    try {
      const data = await callToolEndpoint('virtual-body-double', { action: 'breakdown', task: task.trim(), duration: actualDuration, mood, userLocale, userCurrency, userRegion });
      setBreakdownData(data);
      setSubTasks(data.sub_tasks?.map(s => s.label) || []);
      setSubTaskChecked({});
      setShowBreakdown(true);
    } catch (err) { setError(err.message || t('vbd_err_breakdown')); } };

  // ─── API: Start session ───
  const handleStart = async () => {
    if (!task.trim()) { setError(t('vbd_err_what_working')); return; } setError('');
    try {
      const data = await callToolEndpoint('virtual-body-double', {
        action: 'start', task: task.trim(), duration: actualDuration, checkInFrequency: checkInFreq,
        environment, mood, goals: goals.trim(), subTasks: subTasks.length > 0 ? subTasks : undefined, mode: sessionMode,
        userLocale, userCurrency, userRegion,
      });
      setSessionPlan(data);
      ambientMsgsRef.current = data.ambient_messages || [];
      ambientIndexRef.current = 0;
      setSecondsRemaining(actualDuration * 60); setSecondsElapsed(0); setCheckInsDone(0);
      nextCheckInRef.current = 0; setChatLog([]); setShowCheckIn(false); setCheckInResponse(null);
      setStuckData(null); setExtendData(null); setCompletionData(null); setCardData(null);
      setMoodAfter(''); setCompletionNote(''); setSubTaskChecked({}); setShowCard(false);
      setView('active');
      addBuddyMessage(data.kickoff?.greeting, '👋', 500);
      if (data.kickoff?.first_step) addBuddyMessage(t('vbd_first_step', { step: data.kickoff.first_step }), '🎯', 2500);
      if (data.kickoff?.environment_tip) addBuddyMessage(data.kickoff.environment_tip, '💡', 4500);
    } catch (err) { setError(err.message || t('vbd_err_start')); } };

  // ─── Quick-start from past session ───
  const handleRepeat = (session) => {
    setTask(session.task || ''); setDuration(session.duration || 25); setCustomDuration('');
    setCheckInFreq(session.checkInFreq || 15); setEnvironment(session.environment || '');
    setSessionMode(session.mode || 'default'); setMood(''); setGoals('');
    setSubTasks([]); setShowBreakdown(false); setBreakdownData(null); setError('');
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  // ─── API: Check-in ───
  const handleCheckIn = async (status) => {
    setShowCheckIn(false); setCheckInsDone(prev => prev + 1);
    const statusOpt = STATUS_OPTIONS.find(s => s.id === status);
    addChat('user', `${statusOpt?.icon || ''} ${statusOpt ? t(statusOpt.labelKey) : status}${checkInNote ? ` — ${checkInNote}` : ''}`);
    setCheckInNote('');
    try {
      const data = await callToolEndpoint('virtual-body-double', {
        action: 'check-in', task, status, minutesElapsed: Math.floor(secondsElapsed / 60),
        totalMinutes: actualDuration, currentCheckIn: checkInsDone + 1, totalCheckIns,
        sessionPersonality: sessionPlan?.session_personality, note: checkInNote,
        currentSubTask: currentSubTask || undefined, mode: sessionMode,
        userLocale, userCurrency, userRegion,
      });
      setCheckInResponse(data);
      addBuddyMessage(data.response, data.emoji);
      if (data.suggestion) addBuddyMessage(`💡 ${data.suggestion}`, null, 1500);
    } catch (err) { addChat('buddy', t('vbd_chat_still_here')); } };

  // ─── API: Stuck ───
  const handleStuck = async () => {
    addChat('user', t('vbd_chat_im_stuck'));
    try {
      const data = await callToolEndpoint('virtual-body-double', {
        action: 'stuck', task, minutesElapsed: Math.floor(secondsElapsed / 60),
        currentSubTask: currentSubTask || undefined, mode: sessionMode,
        userLocale, userCurrency, userRegion,
      });
      setStuckData(data);
      addBuddyMessage(data.diagnosis, '🔍');
      addBuddyMessage(`→ ${data.immediate_action}`, '🎯', 1200);
      if (data.permission) addBuddyMessage(data.permission, '💚', 2400);
    } catch (err) { addChat('buddy', t('vbd_chat_tiniest_piece')); } };

  // ─── API: Break ───
  const handleBreakAction = async () => {
    setIsOnBreak(true); setBreakSecondsRemaining(5 * 60);
    addChat('user', t('vbd_chat_taking_break'));
    try {
      const data = await callToolEndpoint('virtual-body-double', {
        action: 'break', task, minutesWorked: Math.floor(secondsElapsed / 60), breakDuration: 5, environment, mood,
        userLocale, userCurrency, userRegion,
      });
      addBuddyMessage(data.activity, '🌿');
      if (data.why) addBuddyMessage(data.why, '💚', 1000);
    } catch (err) { addChat('buddy', t('vbd_chat_step_away')); } };

  // ─── Session complete ───
  // eslint-disable-next-line react-hooks/exhaustive-deps
  const handleSessionComplete = useCallback(async () => {
    clearInterval(timerRef.current); clearTimeout(ambientTimerRef.current);
    if (soundEnabled) playChime();
    if (notificationsEnabled) sendNotification(t('vbd_notif_complete_title'), t('vbd_notif_complete_body', { task }));
    setView('complete');
    try {
      const data = await callToolEndpoint('virtual-body-double', {
        action: 'complete', task, totalMinutes: actualDuration, checkInsCompleted: checkInsDone,
        totalCheckIns, moodBefore: mood, moodAfter, sessionLog, mode: sessionMode,
        subTasksCompleted: subTasks.length > 0 ? subTasksCompleted : undefined,
        totalSubTasks: subTasks.length > 0 ? subTasks.length : undefined,
        userLocale, userCurrency, userRegion,
      });
      setCompletionData(data);
    } catch (err) {
      setCompletionData({ celebration: t('vbd_fallback_celebration'), accomplishment_reframe: t('vbd_fallback_reframe'), card_quote: t('vbd_fallback_quote') });
    } }, [task, actualDuration, checkInsDone, totalCheckIns, mood, moodAfter, sessionLog, subTasks, subTasksCompleted, soundEnabled, notificationsEnabled, sessionMode, callToolEndpoint, userLocale, userCurrency, userRegion, t]);

  // ─── Keep completeRef current (must be after handleSessionComplete) ───
  useEffect(() => { completeRef.current = handleSessionComplete; }, [handleSessionComplete]);

  // ─── Keyboard shortcut — SELECT-only guard, ref pattern ───
  const handleStartRef = useRef(null);
  const canSubmitRef = useRef(false);
  handleStartRef.current = handleStart;
  canSubmitRef.current = !!task.trim() && !loading && !sessionPlan;

  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && !loading && canSubmitRef.current) {
        e.preventDefault();
        handleStartRef.current?.();
      }
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, [loading]);

  // ─── Generate accountability card (v4) ───
  const handleGenerateCard = async () => {
    setShowCard(true);
    try {
      const data = await callToolEndpoint('virtual-body-double', {
        action: 'card', task, totalMinutes: actualDuration, mode: sessionMode,
        buddyName: sessionPlan?.session_personality?.name, cardQuote: completionData?.card_quote,
        moodBefore: mood, moodAfter,
        subTasksCompleted: subTasks.length > 0 ? subTasksCompleted : undefined,
        totalSubTasks: subTasks.length > 0 ? subTasks.length : undefined,
        streak: sessionLog.length + 1,
        userLocale, userCurrency, userRegion,
      });
      setCardData(data);
    } catch (err) {
      setCardData({ achievement_title: t('vbd_card_default_title'), share_line: t('vbd_card_default_share', { min: actualDuration, task }), badge_emoji: '🎉' });
    } };

  // ─── End early ───
  const handleEndEarly = () => {
    clearInterval(timerRef.current); clearInterval(breakTimerRef.current); clearTimeout(ambientTimerRef.current);
    handleSessionComplete();
  };

  // ─── Save session ───
  const saveSession = () => {
    const entry = {
      id: Date.now(), task, duration: actualDuration, checkInFreq, environment, mode: sessionMode, preview: task.slice(0, 40),
      minutesWorked: Math.floor(secondsElapsed / 60), checkIns: checkInsDone,
      moodBefore: mood, moodAfter, completionNote, date: new Date().toISOString(),
      completed: secondsRemaining <= 0,
      subTasksCompleted: subTasks.length > 0 ? subTasksCompleted : undefined,
      totalSubTasks: subTasks.length > 0 ? subTasks.length : undefined,
    };
    setSessionLog(prev => [entry, ...prev].slice(0, 6));
    setView('setup'); resetForm();
  };

  // ─── Extend ───
  const handleExtend = async (extraMin = 15) => {
    try {
      const data = await callToolEndpoint('virtual-body-double', { action: 'extend', task, minutesCompleted: actualDuration, additionalMinutes: extraMin, userLocale, userCurrency, userRegion });
      setExtendData(data); setSecondsRemaining(extraMin * 60); setSecondsElapsed(0);
      nextCheckInRef.current = 0; setCheckInsDone(0); setView('active');
      addBuddyMessage(data.extension_message, '🔄');
      if (data.mini_goal) addBuddyMessage(t('vbd_goal_prefix', { goal: data.mini_goal }), '🎯', 1200);
    } catch (err) { setSecondsRemaining(extraMin * 60); setView('active'); addChat('buddy', t('vbd_chat_round_2')); } };

  // ─── Invite ───
  const handleInvite = async () => {
    try {
      const data = await callToolEndpoint('virtual-body-double', { action: 'invite', task, duration: `${actualDuration} minutes`, platform: 'text', userLocale, userCurrency, userRegion });
      setInviteData(data);
    } catch (err) { setError(t('vbd_err_invite')); } };

  // ─── Review ───
  const handleReview = async () => {
    if (sessionLog.length < 3) { setError(t('vbd_err_need_3')); return; } try {
      const data = await callToolEndpoint('virtual-body-double', { action: 'review', sessionLog: sessionLog.slice(0, 20), userLocale, userCurrency, userRegion });
      setReviewData(data); setView('insights');
    } catch (err) { setError(t('vbd_err_analyze')); } };

  const resetForm = () => {
    setTask(''); setGoals(''); setMood(''); setEnvironment('');
    setError(''); setSessionPlan(null); setStuckData(null);
    setExtendData(null); setCompletionData(null); setInviteData(null);
    setChatLog([]); setSubTasks([]); setSubTaskChecked({});
    setShowBreakdown(false); setBreakdownData(null);
    setCardData(null); setShowCard(false);
  };

  const buildSessionText = () => {
    if (!completionData) return '';
    return `${t('vbd_copy_session_title')}\n${t('vbd_copy_task')} ${task}\n${t('vbd_copy_mode')} ${modeLabel}\n${t('vbd_copy_duration')} ${actualDuration} ${t('vbd_card_min')}\n${t('vbd_copy_mood')} ${mood} → ${moodAfter}${subTasks.length ? `\n${t('vbd_copy_subtasks')} ${subTasksCompleted}/${subTasks.length}` : ''}\n\n${completionData.celebration}\n${completionData.accomplishment_reframe}${BRAND}`;
  };

  const buildCardText = () => {
    const lines = [
      `${cardData?.badge_emoji || '🎉'} ${cardData?.achievement_title || t('vbd_card_session_complete')}`,
      '',
      `📋 ${task}`,
      `⏱️ ${Math.floor(secondsElapsed / 60)} ${t('vbd_card_min')} · ${modeLabel} ${t('vbd_mode_suffix')}`,
      subTasks.length > 0 ? `✅ ${subTasksCompleted}/${subTasks.length} ${t('vbd_stat_subtasks')}` : null,
      '',
      `"${completionData?.card_quote || cardData?.share_line || t('vbd_card_quote_fallback')}"`,
      '',
      `— ${sessionPlan?.session_personality?.name || t('vbd_card_your_buddy')} ${t('vbd_was_here_suffix')}`,
      BRAND,
    ].filter(Boolean);
    return lines.join('\n');
  };

  // ─── Register export content — view-aware ───
  useRegisterActions(
    view === 'complete' && completionData
      ? (showCard ? buildCardText() : buildSessionText())
      : '',
    tool?.title
  );

  // ══════════════════════════════════════════════════
  // RENDER: SETUP
  // ══════════════════════════════════════════════════
  if (view === 'setup') {
    return (<div className="px-4 py-2">
        <div className="max-w-xl mx-auto space-y-5">

          {/* Header */} <div className="mb-2">
            <h1 className={`text-2xl font-bold ${c.text}`}>
              <span className="me-2">{tool?.icon ?? '👥'}</span>{tool?.title} </h1>
            <p className={`${c.textSecondary} text-sm mt-1`}>{tool?.tagline}</p>
            <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className={`mt-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium border disabled:opacity-40 ${isDark ? 'text-white border-white/40' : 'text-gray-800 border-transparent'}`}>{t('try_example')}</button>
          </div>
          <div className={`px-4 py-3 rounded-xl ${c.accentLight} border text-sm ${c.accentLightText} leading-relaxed`}>
            <span className="font-bold">{t('vbd_intro_bold')}</span> {t('vbd_intro_rest')}
          </div>

          {/* Status bar — only when there is something to show */} {sessionLog.length > 0 && (<div className={`${c.card} border rounded-xl p-4`}>
            <div className="flex items-center justify-between flex-wrap gap-2">
              <div>
                {sessionLog.length > 0 && (<span className={`text-sm font-medium ${c.text}`}>
                    <span>📊</span> {t('vbd_sessions_count', { count: sessionLog.length, plural: sessionLog.length !== 1 ? 's' : '' })} ·{' '} <span className={`text-xs ${c.textMuted}`}>
                      {t('vbd_hours_total', { hours: Math.round(sessionLog.reduce((sum, s) => sum + (s.minutesWorked || 0), 0) / 60 * 10) / 10 })}
                    </span>
                  </span>
                )} </div>
              <div className="flex items-center gap-2">
                <button onClick={() => setSoundEnabled(!soundEnabled)} className={`text-xs px-2.5 py-1.5 rounded-lg ${soundEnabled ? c.tagActive : c.tag}`} title={soundEnabled ? t('vbd_sound_on') : t('vbd_sound_off')}>{soundEnabled ? '🔔' : '🔕'}</button>
                <button onClick={() => setNotificationsEnabled(!notificationsEnabled)} className={`text-xs px-2.5 py-1.5 rounded-lg ${notificationsEnabled ? c.tagActive : c.tag}`} title={notificationsEnabled ? t('vbd_notif_on') : t('vbd_notif_off')}>{notificationsEnabled ? '📳' : '📴'}</button>
                {sessionLog.length >= 3 && (<button onClick={handleReview} disabled={loading} className={`text-xs px-3 py-1.5 rounded-lg font-medium disabled:opacity-40 ${c.tagActive}`}>
                    <span>📈</span> {t('vbd_insights')}</button>
                )} {sessionLog.length > 0 && (<button onClick={() => setSessionLog([])} className={`text-xs px-2.5 py-1.5 rounded-lg ${c.tag}`}>🗑️</button>
                )} </div>
            </div>
          </div>
          )} {/* Session Mode selector (v4) */} <div className={`${c.card} border rounded-xl p-5 space-y-3`}>
            <label className={`block text-sm font-semibold ${c.text}`}>{t('vbd_session_mode_label')}</label>
            <div className="grid grid-cols-2 gap-2">
              {SESSION_MODES.map(m => (<button key={m.id} onClick={() => { setSessionMode(m.id); setCheckInFreq(m.defaultFreq); }} className={`flex items-start gap-2.5 p-3 rounded-xl text-start transition-all border ${
                    sessionMode === m.id
                      ? `${MODE_COLORS[m.id].badge} text-white border-transparent shadow-lg`
                      : `${c.tag} ${isDark ? 'border-zinc-600' : 'border-gray-200'} ${c.cardHover}`
                  }`}>
                  <span className="text-lg">{m.icon}</span>
                  <div>
                    <span className="text-sm font-medium block">{t(m.labelKey)}</span>
                    <span className={`text-xs ${sessionMode === m.id ? 'text-white/70' : c.textMuted}`}>{t(m.descKey)}</span>
                  </div>
                </button>
              ))} </div>
          </div>

          {/* Task input + breakdown */} <div className={`${c.card} border rounded-xl p-5 space-y-4`}>
            <div>
              <label className={`block text-sm font-semibold ${c.text} mb-2`}>{t('vbd_what_working_on')} <span className={c.required}>*</span></label>
              <div className="flex gap-2">
                <input type="text" value={task} onChange={e => { setTask(e.target.value); setShowBreakdown(false); setSubTasks([]); }} placeholder={t('vbd_task_placeholder')}
                  className={`flex-1 p-3 rounded-lg border ${c.input} outline-none`} onKeyDown={e => e.key === 'Enter' && handleStart()} />
                {task.trim().length > 3 && (<button onClick={handleBreakdown} disabled={loading} className={`px-3 py-2 rounded-lg text-sm font-medium whitespace-nowrap disabled:opacity-40 ${subTasks.length > 0 ? c.tagActive : c.tag} transition-all`} title={t('vbd_split_task_title')}>
                    {loading ? <span className="inline-block animate-spin">{tool?.icon ?? '👥'}</span> : '✂️'} {t('vbd_split')}
                  </button>
                )} </div>
            </div>

            {/* Sub-task breakdown */} {showBreakdown && breakdownData && (<div className={`${c.accentLight} border rounded-xl p-4 space-y-2`}>
                <div className="flex items-center justify-between">
                  <p className={`text-xs font-bold ${c.accentLightText} uppercase tracking-wider`}><span>✂️</span> {t('vbd_task_breakdown')}</p>
                  <button onClick={() => { setShowBreakdown(false); setSubTasks([]); setBreakdownData(null); }} className={`text-xs ${c.textMuted}`}>✕ {t('vbd_clear')}</button>
                </div>
                {breakdownData.strategy_note && <p className={`text-xs ${c.accentLightText} italic`}>{breakdownData.strategy_note}</p>} {breakdownData.sub_tasks?.map((st, i) => (<div key={i} className={`flex items-start gap-2 p-2 rounded-lg ${isDark ? 'bg-zinc-700/40' : 'bg-white/70'}`}>
                    <span className={`text-xs font-bold ${c.accentLightText} mt-0.5 w-4`}>{i + 1}</span>
                    <div className="flex-1">
                      <span className={`text-sm ${c.text}`}>{st.label}</span>
                      <span className={`text-xs ${c.textMuted} ms-2`}>~{st.estimated_minutes}m</span>
                      {st.bonus && <span className={`text-xs ms-1 px-1 rounded ${isDark ? 'bg-zinc-600 text-zinc-300' : 'bg-gray-200 text-gray-600'}`}>{t('vbd_bonus')}</span>}
                      {st.tip && <p className={`text-xs ${c.textMuted} mt-0.5`}>💡 {st.tip}</p>} </div>
                    <span className={`text-xs px-1.5 py-0.5 rounded ${
                      st.difficulty === 'easy' ? 'bg-emerald-100 text-emerald-700' :
                      st.difficulty === 'hard' ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-700'
                    }`}>{st.difficulty === 'easy' ? t('vbd_diff_easy') : st.difficulty === 'hard' ? t('vbd_diff_hard') : st.difficulty === 'medium' ? t('vbd_diff_medium') : st.difficulty}</span>
                  </div>
                ))} {breakdownData.momentum_starter && (<p className={`text-xs ${c.accentLightText} mt-1`}><span>🎯</span> {t('vbd_start_label')} {breakdownData.momentum_starter}</p>
                )} </div>
            )} {/* Duration */} <div>
              <label className={`block text-sm font-semibold ${c.text} mb-2`}>{t('vbd_how_long')}</label>
              <div className="flex flex-wrap gap-2">
                {DURATIONS.map(d => (<button key={d.min} onClick={() => { setDuration(d.min); setCustomDuration(''); }} className={`px-3 py-2 rounded-lg text-sm font-medium transition-all ${duration === d.min && !customDuration ? c.tagActive : c.tag}`}>
                    <span>{d.icon}</span> {t(d.labelKey)} </button>
                ))} <input type="number" value={customDuration} onChange={e => setCustomDuration(e.target.value)} placeholder={t('vbd_custom')} className={`w-20 px-3 py-2 rounded-lg border text-sm ${c.input}`} min="5" max="180" />
              </div>
            </div>

            {/* Check-in frequency */} <div>
              <label className={`block text-sm font-semibold ${c.text} mb-2`}>{t('vbd_checkin_freq')}</label>
              <div className="flex flex-wrap gap-2">
                {CHECK_IN_FREQS.map(f => (<button key={f.min} onClick={() => setCheckInFreq(f.min)} className={`px-3 py-2 rounded-lg text-sm font-medium transition-all ${checkInFreq === f.min ? c.tagActive : c.tag}`}>
                    {t(f.labelKey)} </button>
                ))} </div>
            </div>
          </div>

          {/* Optional context */} <div className={`${c.card} border rounded-xl p-5 space-y-4`}>
            <p className={`text-xs font-medium ${c.textMuted} uppercase tracking-wider`}>{t('vbd_optional_context')}</p>
            <div>
              <label className={`block text-sm font-medium ${c.textSecondary} mb-2`}>{t('vbd_where_are_you')}</label>
              <div className="flex flex-wrap gap-2">
                {ENVIRONMENTS.map(e => (<button key={e.id} onClick={() => setEnvironment(environment === e.id ? '' : e.id)} className={`px-3 py-2 rounded-lg text-sm font-medium transition-all ${environment === e.id ? c.tagActive : c.tag}`}>
                    <span>{e.icon}</span> {t(e.labelKey)} </button>
                ))} </div>
            </div>
            <div>
              <label className={`block text-sm font-medium ${c.textSecondary} mb-2`}>{t('vbd_current_mood')}</label>
              <div className="flex flex-wrap gap-2">
                {MOODS.map(m => (<button key={m.id} onClick={() => setMood(mood === m.id ? '' : m.id)} className={`px-3 py-2 rounded-lg text-sm font-medium transition-all ${mood === m.id ? c.tagActive : c.tag}`}>
                    <span>{m.icon}</span> {t(m.labelKey)} </button>
                ))} </div>
            </div>
            <div>
              <label className={`block text-sm font-medium ${c.textSecondary} mb-2`}>{t('vbd_session_goal')}</label>
              <input type="text" value={goals} onChange={e => setGoals(e.target.value)} placeholder={t('vbd_goal_placeholder')}
                className={`w-full p-3 rounded-lg border ${c.input} outline-none text-sm`} />
            </div>
          </div>

          {/* Start button */} <button onClick={handleStart} disabled={loading || !task.trim()} className={`w-full py-4 rounded-xl font-bold text-lg ${modeColors.badge} ${c.accentTxt} disabled:opacity-40 transition-all shadow-lg hover:opacity-90`}>
            {loading ? (<span><span className="inline-block animate-spin">{tool?.icon ?? '👥'}</span> {t('vbd_setting_up')}</span>
            ) : (<span><span>{SESSION_MODES.find(m => m.id === sessionMode)?.icon || '▶️'}</span> {t('vbd_start_session', { mode: modeLabel })}</span>
            )} </button>

          {error && (<div className={`${c.danger} border rounded-xl p-4`}>
              <p className={`text-sm ${c.errorText}`}><span>⚠️</span> {error}</p>
            </div>
          )} <p className={`text-center text-xs ${c.textMuted}`}>{t('vbd_disclaimer_setup')}</p>

          {/* Cross-references */} <div className={`${c.card} border rounded-xl p-4`}>
            <p className={`text-xs font-medium ${c.textMuted} mb-2`}>{t('vbd_related_tools')}</p>
            <div className="flex flex-wrap gap-2">
              {[
                { id: 'BatchFlow', icon: '🔀', labelKey: 'vbd_xref_batchflow' },
                { id: 'BrainStateDeejay', icon: '🎧', labelKey: 'vbd_xref_brainstatedeejay' },
                { id: 'PEP', icon: '✨', labelKey: 'vbd_xref_pep' },
              ].map(xref => (<a key={xref.id} href={`/${xref.id}`}
                  className={`text-xs px-3 py-1.5 rounded-lg ${c.tag} ${c.cardHover} transition-colors`}>
                  <span>{xref.icon}</span> {t(xref.labelKey)} </a>
              ))} </div>
          </div>

          {/* Recent sessions */} {sessionLog.length > 0 && (<div className={`${c.card} border rounded-xl p-5`}>
              <h3 className={`text-sm font-bold ${c.text} mb-3`}><span>🕐</span> {t('vbd_recent_sessions')}</h3>
              <div className="space-y-2">
                {sessionLog.slice(0, 5).map(s => (<div key={s.id} className={`flex items-center justify-between p-2.5 rounded-lg ${isDark ? 'bg-zinc-700/50' : 'bg-gray-50'}`}>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-1.5">
                        <span className="text-xs">{SESSION_MODES.find(m => m.id === s.mode)?.icon || '👥'}</span>
                        <span className={`text-sm font-medium ${c.text} truncate`}>{s.task}</span>
                      </div>
                      <span className={`text-xs ${c.textMuted}`}>
                        {s.minutesWorked}m · {new Date(s.date).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })} {s.subTasksCompleted !== undefined ? ` · ${s.subTasksCompleted}/${s.totalSubTasks} ${t('vbd_tasks_suffix')}` : ''} </span>
                    </div>
                    <div className="flex items-center gap-2 ms-2 flex-shrink-0">
                      {s.completed && <span className="text-xs">✅</span>} <button onClick={() => handleRepeat(s)} className={`text-xs px-2.5 py-1.5 rounded-lg ${c.tag} ${c.cardHover} transition-colors font-medium`} title={t('vbd_repeat_session')}>🔁</button>
                    </div>
                  </div>
                ))} </div>
            </div>
          )} </div>
      </div>
    );
  } // ══════════════════════════════════════════════════
  // RENDER: ACTIVE SESSION
  // ══════════════════════════════════════════════════
  if (view === 'active') {
    const progress = actualDuration > 0 ? ((actualDuration * 60 - secondsRemaining) / (actualDuration * 60)) * 100 : 0;

    return (<div className="px-4 py-2">
        <div className="max-w-xl mx-auto space-y-4">

          {/* Timer header with mode-colored bar */} <div className={`${c.card} border rounded-xl p-5 text-center ${modeColors.glow} shadow-sm`}>
            {/* Mode badge + presence */} <div className="flex items-center justify-center gap-2 mb-3">
              <span className="text-xs">{SESSION_MODES.find(m => m.id === sessionMode)?.icon}</span>
              <div className={`w-2 h-2 rounded-full ${modeColors.bar} animate-pulse`} />
              <span className={`text-xs font-medium ${c.textMuted}`}>
                {sessionPlan?.session_personality?.name || t('vbd_buddy')} {t('vbd_is_here')}
                {sessionPlan?.session_personality?.style ? ` · ${sessionPlan.session_personality.style}` : ''} </span>
            </div>

            <div className={`text-5xl font-mono font-bold ${c.text} mb-2`}>
              {isOnBreak ? formatTime(breakSecondsRemaining) : formatTime(secondsRemaining)} </div>
            <p className={`text-sm ${c.textMuted}`}>{isOnBreak ? t('vbd_break_time') : task}</p>

            {/* Mode-colored progress bar */} <div className={`mt-3 h-2 rounded-full ${isDark ? 'bg-zinc-700' : 'bg-gray-200'} overflow-hidden`}>
              <div className={`h-full rounded-full transition-all duration-1000 ${isOnBreak ? 'bg-emerald-500' : modeColors.bar}`} style={{ width: `${isOnBreak ? ((300 - breakSecondsRemaining) / 300 * 100) : progress}%` }} />
            </div>

            {/* Controls */} <div className="flex items-center justify-center gap-3 mt-4">
              {!isOnBreak ? (<>
                  <button onClick={() => setIsPaused(!isPaused)} className={`px-4 py-2 rounded-lg text-sm font-medium ${c.tag}`}>
                    {isPaused ? `▶️ ${t('vbd_resume')}` : `⏸️ ${t('vbd_pause')}`}</button>
                  <button onClick={handleBreakAction} disabled={loading} className={`px-4 py-2 rounded-lg text-sm font-medium disabled:opacity-40 ${c.tag}`}>
                    ☕ {t('vbd_break')}</button>
                  <button onClick={handleEndEarly} className={`px-4 py-2 rounded-lg text-sm font-medium ${isDark ? 'bg-zinc-700 text-red-400' : 'bg-red-50 text-red-600'}`}>
                    ⏹ {t('vbd_end')}</button>
                </>
              ) : (<button onClick={() => { setIsOnBreak(false); clearInterval(breakTimerRef.current); addChat('buddy', t('vbd_chat_back_at_it')); }} className={`px-4 py-2 rounded-lg text-sm font-medium ${c.tagActive}`}>▶️ {t('vbd_end_break_early')}</button>
              )} </div>
          </div>

          {/* Sub-task checklist */} {subTasks.length > 0 && (<div className={`${c.card} border rounded-xl p-4`}>
              <p className={`text-xs font-bold ${c.textMuted} uppercase tracking-wider mb-2`}>
                <span>✂️</span> {t('vbd_subtasks_label')} · {subTasksCompleted}/{subTasks.length} </p>
              <div className="space-y-1.5">
                {subTasks.map((st, i) => (<button key={i} onClick={() => setSubTaskChecked(prev => ({ ...prev, [i]: !prev[i] }))} className={`w-full flex items-center gap-2 p-2 rounded-lg text-start text-sm transition-all ${
                      subTaskChecked[i]
                        ? (isDark ? 'bg-emerald-900/30 text-emerald-300 line-through opacity-60' : 'bg-emerald-50 text-emerald-700 line-through opacity-60')
                        : (i === subTasks.findIndex((_, j) => !subTaskChecked[j])
                          ? `${c.accentLight} ${c.accentLightText}`
                          : `${isDark ? 'bg-zinc-700/40 text-zinc-300' : 'bg-gray-50 text-gray-600'}`)
                    }`}>
                    <span>{subTaskChecked[i] ? '✅' : (i === subTasks.findIndex((_, j) => !subTaskChecked[j]) ? '👉' : '⬜')}</span>
                    {st} </button>
                ))} </div>
            </div>
          )} {/* Chat log */} <div className={`${c.card} border rounded-xl p-4`} style={{ maxHeight: '360px', overflowY: 'auto' }}>
            <div className="space-y-3">
              {chatLog.map((msg, i) => (<div key={i} className={`flex ${msg.from === 'user' ? 'justify-end' : 'justify-start'}`}>
                  <div className={`max-w-[85%] rounded-2xl px-4 py-2.5 ${
                    msg.from === 'user'
                      ? (isDark ? 'bg-cyan-700 text-white' : 'bg-cyan-500 text-white')
                      : `${c.bubbleBg} ${c.bubbleText}`
                  }`}>
                    {msg.emoji && msg.from === 'buddy' && <span className="me-1">{msg.emoji}</span>} <span className="text-sm">{msg.message}</span>
                    <div className={`text-[10px] mt-1 ${msg.from === 'user' ? 'text-cyan-200' : c.textMuted}`}>{msg.time}</div>
                  </div>
                </div>
              ))} {buddyTyping && (<div className="flex justify-start">
                  <div className={`rounded-2xl px-4 py-3 ${c.bubbleBg}`}>
                    <div className="flex gap-1">
                      <span className={`w-2 h-2 rounded-full ${modeColors.bar} animate-bounce`} style={{ animationDelay: '0ms' }} />
                      <span className={`w-2 h-2 rounded-full ${modeColors.bar} animate-bounce`} style={{ animationDelay: '150ms' }} />
                      <span className={`w-2 h-2 rounded-full ${modeColors.bar} animate-bounce`} style={{ animationDelay: '300ms' }} />
                    </div>
                  </div>
                </div>
              )} <div ref={chatEndRef} />
            </div>
          </div>

          {/* Check-in prompt */} {showCheckIn && !isOnBreak && (<div className={`${c.accentLight} border rounded-xl p-5 space-y-3`}>
              <p className={`text-sm font-semibold ${c.accentLightText}`}>
                <span>👋</span> {t('vbd_checkin_num', { num: checkInsDone + 1 })} — {sessionMode === 'creative' ? t('vbd_whats_exploring') : t('vbd_hows_going')} </p>
              <div className="flex flex-wrap gap-2">
                {STATUS_OPTIONS.map(s => (<button key={s.id} onClick={() => handleCheckIn(s.id)} disabled={loading} className={`px-3 py-2 rounded-lg text-sm font-medium disabled:opacity-40 ${c.tag} ${c.cardHover} transition-all`}>
                    <span>{s.icon}</span> {t(s.labelKey)} </button>
                ))} </div>
              <input type="text" value={checkInNote} onChange={e => setCheckInNote(e.target.value)} placeholder={t('vbd_add_note')} className={`w-full p-2 rounded-lg border text-sm ${c.input}`} />
            </div>
          )} {/* Stuck + Invite buttons */} {!isOnBreak && !showCheckIn && (<div className="flex gap-3">
              <button onClick={handleStuck} disabled={loading} className={`flex-1 py-3 rounded-xl text-sm font-medium disabled:opacity-40 ${c.warning} border ${c.warning} transition-all`}>
                {loading ? <span className="inline-block animate-spin">{tool?.icon ?? '👥'}</span> : <span>🧱</span>} {t('vbd_im_stuck')}
              </button>
              <button onClick={handleInvite} disabled={loading} className={`flex-1 py-3 rounded-xl text-sm font-medium disabled:opacity-40 ${c.tag} transition-all`}>
                <span>👋</span> {t('vbd_invite_friend')}
              </button>
            </div>
          )} {/* Stuck data */} {stuckData && (<div className={`${c.card} border rounded-xl p-5 space-y-3`}>
              <h3 className={`text-sm font-bold ${c.text}`}><span>🔧</span> {t('vbd_unstick_plan')}</h3>
              {stuckData.micro_steps?.map((step, i) => (<div key={i} className={`flex items-start gap-2 p-2 rounded-lg ${isDark ? 'bg-zinc-700/50' : 'bg-gray-50'}`}>
                  <span className={`text-xs font-bold ${c.textMuted} mt-0.5`}>{i + 1}</span>
                  <span className={`text-sm ${c.text}`}>{step}</span>
                </div>
              ))} {stuckData.environment_shift && <p className={`text-sm ${c.textSecondary}`}><span>🔄</span> {t('vbd_try_prefix')} {stuckData.environment_shift}</p>} {stuckData.bailout_option && <p className={`text-xs ${c.textMuted} italic`}>{t('vbd_or_prefix')} {stuckData.bailout_option}</p>} </div>
          )} {/* Invite data */} {inviteData && (<div className={`${c.card} border rounded-xl p-5 space-y-3`}>
              <h3 className={`text-sm font-bold ${c.text}`}><span>👋</span> {t('vbd_invite_buddy')}</h3>
              {inviteData.messages?.map((msg, i) => (<div key={i} className="space-y-1">
                  <p className={`text-xs font-medium ${c.textMuted} capitalize`}>{msg.tone}</p>
                  <div className={`p-3 rounded-lg ${isDark ? 'bg-zinc-700' : 'bg-gray-50'}`}>
                    <p className={`text-sm ${c.text}`}>{msg.text}</p>
                  </div>
                </div>
              ))}
              {inviteData.platform_tip && <p className={`text-xs ${c.textMuted} italic`}>💡 {inviteData.platform_tip}</p>} </div>
          )} </div>
      </div>
    );
  } // ══════════════════════════════════════════════════
  // RENDER: COMPLETE
  // ══════════════════════════════════════════════════
  if (view === 'complete') {
    return (<div className="px-4 py-2">
        <div className="max-w-xl mx-auto space-y-5">

          <div ref={resultsRef} data-results-anchor />

          {/* Celebration */} <div className={`${c.success} border rounded-xl p-6 text-center`}>
            <span className="text-4xl block mb-3">🎉</span>
            <h2 className={`text-xl font-bold ${c.accentTxt}`}>{t('vbd_session_complete')}</h2>
            {completionData && (<div className="mt-3 space-y-2">
                <p className={`text-sm ${c.accentTxt}`}>{completionData.celebration}</p>
                <p className={`text-sm ${c.accentTxt} opacity-80`}>{completionData.accomplishment_reframe}</p>
              </div>
            )}
            <p className={`text-xs ${c.textMuted} mt-4`}>
              {t('vbd_next_session_q')} <a href="/BrainStateDeejay" className={linkStyle}>🎧 {t('vbd_xref_brainstatedeejay')}</a> {t('vbd_next_session_rest')}
            </p>
          </div>

          {/* Stats */} <div className={`${c.card} border rounded-xl p-5`}>
            <div className={`grid ${subTasks.length > 0 ? 'grid-cols-4' : 'grid-cols-3'} gap-3 text-center`}>
              <div>
                <p className={`text-2xl font-bold ${c.text}`}>{Math.floor(secondsElapsed / 60)}</p>
                <p className={`text-xs ${c.textMuted}`}>{t('vbd_stat_minutes')}</p>
              </div>
              <div>
                <p className={`text-2xl font-bold ${c.text}`}>{checkInsDone}</p>
                <p className={`text-xs ${c.textMuted}`}>{t('vbd_stat_checkins')}</p>
              </div>
              {subTasks.length > 0 && (<div>
                  <p className={`text-2xl font-bold ${c.text}`}>{subTasksCompleted}/{subTasks.length}</p>
                  <p className={`text-xs ${c.textMuted}`}>{t('vbd_stat_subtasks')}</p>
                </div>
              )} <div>
                <p className={`text-2xl font-bold ${c.text}`}>{sessionLog.length + 1}</p>
                <p className={`text-xs ${c.textMuted}`}>{t('vbd_stat_total')}</p>
              </div>
            </div>
          </div>

          {/* Pattern / streak */} {completionData?.pattern_note && (<div className={`${c.accentLight} border rounded-xl p-4`}>
              <p className={`text-sm ${c.accentLightText}`}><span>📊</span> {completionData.pattern_note}</p>
            </div>
          )} {completionData?.streak_message && (<div className={`${c.warning} border rounded-xl p-4`}>
              <p className={`text-sm ${c.warning}`}><span>🔥</span> {completionData.streak_message}</p>
            </div>
          )} {/* ═══ ACCOUNTABILITY CARD (v4) ═══ */} {!showCard && completionData && (<button onClick={handleGenerateCard} disabled={loading} className={`w-full py-3 rounded-xl text-sm font-bold disabled:opacity-40 ${modeColors.badge} text-white transition-all hover:opacity-90`}>
              {loading ? <span className="inline-block animate-spin">{tool?.icon ?? '👥'}</span> : <span>🏆</span>} {t('vbd_generate_card')}
            </button>
          )} {showCard && (<div className={`border rounded-2xl overflow-hidden ${isDark ? 'border-zinc-600' : 'border-gray-200'}`}>
              {/* Card visual — designed for screenshots */} <div className={`${modeColors.badge} p-6 text-center text-white`}>
                <span className="text-3xl block mb-2">{cardData?.badge_emoji || SESSION_MODES.find(m => m.id === sessionMode)?.icon || '🎉'}</span>
                <h3 className="text-lg font-bold">{cardData?.achievement_title || t('vbd_card_session_complete')}</h3>
                <p className="text-sm opacity-80 mt-1">{modeLabel} {t('vbd_mode_suffix')}</p>
              </div>
              <div className={`${isDark ? 'bg-zinc-800' : 'bg-white'} p-5 space-y-3`}>
                <p className={`text-center text-sm italic ${c.textSecondary}`}>
                  "{completionData?.card_quote || t('vbd_card_quote_fallback')}"
                </p>
                <div className="flex justify-center gap-6 text-center">
                  <div>
                    <p className={`text-lg font-bold ${c.text}`}>{Math.floor(secondsElapsed / 60)}</p>
                    <p className={`text-[10px] ${c.textMuted} uppercase`}>{t('vbd_card_min')}</p>
                  </div>
                  {subTasks.length > 0 && (<div>
                      <p className={`text-lg font-bold ${c.text}`}>{subTasksCompleted}/{subTasks.length}</p>
                      <p className={`text-[10px] ${c.textMuted} uppercase`}>{t('vbd_card_tasks')}</p>
                    </div>
                  )} <div>
                    <p className={`text-lg font-bold ${c.text}`}>
                      {MOODS.find(m => m.id === mood)?.icon || '😐'} → {MOODS.find(m => m.id === moodAfter)?.icon || '😐'} </p>
                    <p className={`text-[10px] ${c.textMuted} uppercase`}>{t('vbd_card_mood')}</p>
                  </div>
                </div>
                <div className={`text-center pt-2 border-t ${c.border}`}>
                  <p className={`text-[10px] ${c.textMuted}`}>
                    {t('vbd_card_was_here', { name: sessionPlan?.session_personality?.name || t('vbd_buddy') })}
                  </p>
                </div>
                <div className="flex gap-2 pt-1">
                </div>
              </div>
            </div>
          )} {/* Post-session mood */} <div className={`${c.card} border rounded-xl p-5 space-y-3`}>
            <p className={`text-sm font-medium ${c.text}`}>{t('vbd_how_feel_now')}</p>
            <div className="flex flex-wrap gap-2">
              {MOODS.map(m => (<button key={m.id} onClick={() => setMoodAfter(m.id)} className={`px-3 py-2 rounded-lg text-sm font-medium transition-all ${moodAfter === m.id ? c.tagActive : c.tag}`}>
                  <span>{m.icon}</span> {t(m.labelKey)} </button>
              ))} </div>
            <input type="text" value={completionNote} onChange={e => setCompletionNote(e.target.value)} placeholder={t('vbd_completion_note_ph')}
              className={`w-full p-3 rounded-lg border ${c.input} text-sm`} />
          </div>

          {/* Rest permission */} {completionData?.rest_permission && (<div className={`${c.accentLight} border rounded-xl p-4`}>
              <p className={`text-sm ${c.accentLightText}`}><span>💜</span> {completionData.rest_permission}</p>
            </div>
          )}
          {completionData?.next_suggestion && (<div className={`${c.cardAlt} border rounded-xl p-4`}><p className={`text-xs font-bold ${c.textMuted} mb-1`}>💡 {t('vbd_next_idea')}</p><p className={`text-sm ${c.textSecondary}`}>{completionData.next_suggestion}</p></div>)}
          {/* Actions */} <div className="flex gap-3">
            <button onClick={saveSession} className={`flex-1 py-3.5 rounded-xl font-bold ${c.btnPrimary}`}>
              <span>💾</span> {t('vbd_save_done')}
            </button>
            <button onClick={() => handleExtend(15)} disabled={loading} className={`flex-1 py-3.5 rounded-xl font-bold border disabled:opacity-40 ${c.tag}`}>
              <span>🔄</span> {t('vbd_plus_15')}
            </button>
          </div>
          <button onClick={() => { setView('setup'); resetForm(); }} className={`w-full py-2.5 rounded-xl text-sm font-medium ${c.btnSecondary}`}>
            ↩ {t('start_over')}
          </button>

        </div>
      </div>
    );
  } // ══════════════════════════════════════════════════
  // RENDER: INSIGHTS
  // ══════════════════════════════════════════════════
  if (view === 'insights') {
    // Audit S5.5 Pattern A: alias to `results` so the audit's regex detects the
    // post-result cross-ref below as inside a results-conditional block.
    const results = reviewData;
    return (<div className="px-4 py-2">
        <div className="max-w-xl mx-auto space-y-5">
          <div className="flex items-center justify-between">
            <h2 className={`text-xl font-bold ${c.text}`}><span>📈</span> {t('vbd_session_insights')}</h2>
            <button onClick={() => setView('setup')} className={`text-sm px-3 py-1.5 rounded-lg ${c.tag}`}>{t('vbd_back')}</button>
          </div>

          {results && (<>
              <div className={`${c.card} border rounded-xl p-5`}>
                <div className="grid grid-cols-3 gap-3 text-center">
                  <div>
                    <p className={`text-2xl font-bold ${c.text}`}>{results?.total_sessions}</p>
                    <p className={`text-xs ${c.textMuted}`}>{t('vbd_stat_sessions')}</p>
                  </div>
                  <div>
                    <p className={`text-2xl font-bold ${c.text}`}>{results?.total_minutes}</p>
                    <p className={`text-xs ${c.textMuted}`}>{t('vbd_stat_minutes')}</p>
                  </div>
                  <div>
                    <p className={`text-2xl font-bold ${c.text}`}>{results?.completion_rate}</p>
                    <p className={`text-xs ${c.textMuted}`}>{t('vbd_stat_completed')}</p>
                  </div>
                </div>
              </div>

              {results?.sweet_spot && (<div className={`${c.accentLight} border rounded-xl p-5`}>
                  <h3 className={`text-sm font-bold ${c.accentLightText} mb-2`}><span>🎯</span> {t('vbd_sweet_spot')}</h3>
                  {results?.sweet_spot?.best_duration && <p className={`text-sm ${c.accentLightText}`}>{t('vbd_best_duration')} {results?.sweet_spot?.best_duration}</p>} {results?.sweet_spot?.best_time && <p className={`text-sm ${c.accentLightText}`}>{t('vbd_best_time')} {results?.sweet_spot?.best_time}</p>} {results?.sweet_spot?.best_task_type && <p className={`text-sm ${c.accentLightText}`}>{t('vbd_strongest_with')} {results?.sweet_spot?.best_task_type}</p>} </div>
              )} {results?.patterns?.length > 0 && (<div className={`${c.card} border rounded-xl p-5`}>
                  <h3 className={`text-sm font-bold ${c.text} mb-3`}><span>🔍</span> {t('vbd_patterns')}</h3>
                  <div className="space-y-3">
                    {results?.patterns?.map((p, i) => (<div key={i} className={`p-3 rounded-lg ${isDark ? 'bg-zinc-700/50' : 'bg-gray-50'}`}>
                        <p className={`text-sm font-medium ${c.text}`}>{p.observation}</p>
                        <p className={`text-xs ${c.textSecondary} mt-1`}>→ {p.suggestion}</p>
                      </div>
                    ))} </div>
                </div>
              )} {results?.streak && (<div className={`${c.warning} border rounded-xl p-4`}>
                  <p className={`text-sm font-medium ${c.warning}`}>
                    <span>🔥</span> {t('vbd_streak')} {results?.streak?.current} {results?.streak?.current !== 1 ? t('vbd_days') : t('vbd_day')} {results?.streak?.longest > results?.streak?.current ? ` (${t('vbd_best')} ${results?.streak?.longest})` : ''} </p>
                  {results?.streak?.message && <p className={`text-xs ${c.warning} mt-1`}>{results?.streak?.message}</p>} </div>
              )} {results?.encouragement && (<div className={`${c.success} border rounded-xl p-4`}>
                  <p className={`text-sm ${c.accentTxt}`}><span>💚</span> {results?.encouragement}</p>
                </div>
              )}

              <p className={`text-xs text-center ${c.textMuted}`}>
                {t('vbd_insights_xref_q')} <a href="/BrainStateDeejay" className={linkStyle}>🎧 {t('vbd_xref_brainstatedeejay')}</a> {t('vbd_insights_xref_rest')}
              </p>
              </>
          )}
          {!results && (<div className={`${c.card} border rounded-xl p-8 text-center`}>
              <span className="inline-block animate-spin">{tool?.icon ?? '👥'}</span>
              <p className={`text-sm ${c.textMuted} mt-2`}>{t('vbd_analyzing_sessions')}</p>
            </div>
          )} </div>

      </div>
    );
  } return null;
};

VirtualBodyDouble.displayName = 'VirtualBodyDouble';
export default VirtualBodyDouble;
