import React, { useState, useRef, useEffect, useCallback } from 'react';
import Caret from '../components/Caret';
import { useClaudeAPI } from '../hooks/useClaudeAPI';
import { useTheme } from '../hooks/useTheme';
import { usePersistentState } from '../hooks/usePersistentState';
import { useRegisterActions } from '../components/ActionBarContext';
import { useTranslation } from '../i18n/useTranslation';
import { pickExample } from '../utils/exampleRotation';
import { revealSection } from '../utils/revealSection';

const BRAND = '\n\n— Generated by DeftBrain · deftbrain.com';



// Stable ids persisted/sent to the backend; labels are localized at render time.
const TIMEFRAME_OPTIONS = [
  { id: '1 year',   labelKey: 'cr_tf_1y' },
  { id: '2 years',  labelKey: 'cr_tf_2y' },
  { id: '5 years',  labelKey: 'cr_tf_5y' },
  { id: '10 years', labelKey: 'cr_tf_10y' },
];

const EXAMPLE_DECISIONS = [
  {
    a: 'Stay in my current city, keep my job, stay close to family. Buy a small place in 2-3 years.',
    b: 'Take the offer in Seattle. New role, 30% raise, but a cross-country move and starting over socially.',
    about: '34, partnered, no kids yet. Parents are ageing but healthy and twenty minutes away. Twelve years of friendships here.',
    hard: 'The money and the work are genuinely better there. But I would be choosing it over the people who show up when something goes wrong.',
    timeframe: '2 years',
  },
  {
    a: 'Stay at my stable job. Good manager, predictable hours, work I can do without thinking.',
    b: 'Quit and go out on my own. Two clients lined up, about eight months of savings.',
    about: '41, one kid starting school, mortgage. My partner works part-time.',
    hard: 'I am not unhappy, which is the problem — I cannot tell whether I want this or whether I am just bored.',
    timeframe: '2 years',
  },
  {
    a: 'Stay in this relationship and keep working on it.',
    b: 'Leave, and start over on my own.',
    about: '37, together nine years, no kids. We own the flat together.',
    hard: 'I still love him. I just cannot tell whether we are building the life I want or whether I have stopped asking.',
    timeframe: '5 years',
  },
  {
    a: 'Go back to school full-time. Two years, no income, the degree I have wanted since I was 22.',
    b: 'Keep working and study part-time. Four or five years, but nothing has to change.',
    about: '29, renting, no dependents, savings would cover about a year.',
    hard: 'The fast route costs everything I have saved. The slow route costs years I will not get back.',
    timeframe: '5 years',
  },
  {
    a: 'Keep renting in the city. Ten-minute walk to everything, nothing is mine.',
    b: 'Buy the house in the suburbs. Space, a garden, a fifty-minute commute each way.',
    about: '35, partnered, thinking about kids in the next couple of years.',
    hard: 'Everyone says the suburbs are the sensible choice. I do not know if sensible is the same as right.',
    timeframe: '5 years',
  },
  {
    a: 'Accept the promotion. More money, a team of nine, my evenings become negotiable.',
    b: 'Turn it down and stay where I am. Same pay, same hours, and probably no second offer.',
    about: '44, two kids at home, the only one in my family who has ever managed anyone.',
    hard: 'Saying no feels like admitting I do not want more. Saying yes feels like agreeing to a life I have watched other people regret.',
    timeframe: '2 years',
  },
];


// ════════════════════════════════════════════════════════════
// MAIN COMPONENT
// ════════════════════════════════════════════════════════════
const WhichLife = ({ tool }) => {
  const { callToolEndpoint, loading, userLocale, userCurrency, userRegion } = useClaudeAPI();
  const { isDark } = useTheme();
  const { t } = useTranslation();
  // Localized label for a stored timeframe id (falls back to the raw id).
  const tfLabel = (id) => {
    const opt = TIMEFRAME_OPTIONS.find(o => o.id === id);
    return opt ? t(opt.labelKey) : id;
  };

  // ─── Standard c object ───
  const c = {
    card:          isDark ? 'bg-zinc-800' : 'bg-white',
    cardAlt:       isDark ? 'bg-zinc-700/50' : 'bg-slate-50',
    input:         isDark ? 'bg-zinc-900 border-zinc-600 text-zinc-100 placeholder-zinc-400 focus:border-cyan-500 focus:ring-cyan-500/20'
                          : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-cyan-500 focus:ring-cyan-100',
    text:          isDark ? 'text-zinc-50' : 'text-gray-900',
    textSecondary: isDark ? 'text-zinc-300' : 'text-gray-600',
    textMuted:     isDark ? 'text-zinc-400' : 'text-gray-500',
    labelText:     isDark ? 'text-zinc-200' : 'text-gray-700',
    accentTxt:     isDark ? 'text-cyan-400' : 'text-cyan-600',
    btnPrimary:    isDark ? 'bg-cyan-600 hover:bg-cyan-500 text-white'
                          : 'bg-cyan-600 hover:bg-cyan-700 text-white',
    // Waiting for input: an outline, not a smudge. Empty fill keeps "filled"
    // meaning "ready"; the border and label carry the visibility. Important
    // modifiers because tools carry their own border/text utilities on the
    // submit and Tailwind resolves conflicts by stylesheet order, not class
    // order. See the PF-13 exception in audit/audit_v2-3-2.py.
    btnIdle:       isDark ? '!bg-transparent !border-2 !border-cyan-500/85 !text-cyan-300 cursor-not-allowed'
                          : '!bg-transparent !border-2 !border-cyan-600/85 !text-cyan-800 cursor-not-allowed',
    btnSecondary:  isDark ? 'bg-zinc-700 hover:bg-zinc-600 text-zinc-200'
                          : 'bg-gray-100 hover:bg-gray-200 text-gray-700',
    border:        isDark ? 'border-zinc-700' : 'border-gray-200',
    success:       isDark ? 'bg-emerald-900/20 border-emerald-700 text-emerald-200'
                          : 'bg-emerald-50 border-emerald-300 text-emerald-800',
    warning:       isDark ? 'bg-amber-900/20 border-amber-700 text-amber-200'
                          : 'bg-amber-50 border-amber-300 text-amber-800',
    danger:        isDark ? 'bg-red-900/20 border-red-700 text-red-200'
                          : 'bg-red-50 border-red-200 text-red-800',
    required:      isDark ? 'text-amber-400' : 'text-amber-700',
    // Tool-specific: Path A (sky family) — distinct semantic color for two-path comparison
    pathABg:        isDark ? 'bg-sky-900/10'      : 'bg-sky-50',
    pathABorder:    isDark ? 'border-sky-800/40'  : 'border-sky-200',
    pathAAccent:    isDark ? 'text-sky-400'        : 'text-sky-700',
    pathABar:       isDark ? 'bg-sky-500'          : 'bg-sky-600',
    pathATabBorder: isDark ? 'border-sky-400'      : 'border-sky-600',
    // Tool-specific: Path B (amber family) — distinct semantic color
    pathBBg:        isDark ? 'bg-amber-900/10'    : 'bg-amber-50',
    pathBBorder:    isDark ? 'border-amber-800/40': 'border-amber-200',
    pathBAccent:    isDark ? 'text-amber-400'      : 'text-amber-700',
    pathBBar:       isDark ? 'bg-amber-500'        : 'bg-amber-600',
    pathBTabBorder: isDark ? 'border-amber-400'    : 'border-amber-600',
    // Tool-specific: timeframe pill states
    chipActive:    isDark ? 'border-cyan-500 bg-cyan-900/30 text-cyan-300' : 'border-cyan-600 bg-cyan-50 text-cyan-800',
    chipInactive:  isDark ? 'border-zinc-600 text-zinc-400 hover:border-zinc-500' : 'border-gray-300 text-gray-500 hover:border-gray-400',
    deleteTxt:     isDark ? 'text-zinc-500 hover:text-red-400' : 'text-gray-400 hover:text-red-500',
  };
  c.textMuteded = c.textMuted;
  c.label = c.labelText;

  const linkStyle = isDark
    ? 'text-cyan-400 hover:text-cyan-300 underline underline-offset-2'
    : 'text-cyan-700 hover:text-cyan-800 underline underline-offset-2';

  // ─── Session state ───
  const [error,          setError]          = useState('');
  const [activeNarrative,setActiveNarrative] = useState('a');
  const [showHistory,    setShowHistory]    = useState(false);

  // ─── Refs ───
  const resultsRef     = useRef(null);
  const handleSubmitRef = useRef(null);
  const canSubmitRef    = useRef(false);

  // ─── Persisted state ───
  const [pathA,    setPathA]    = usePersistentState('cr-pathA', '');
  const [pathB,    setPathB]    = usePersistentState('cr-pathB', '');
  const [aboutYou, setAboutYou] = usePersistentState('cr-about', '');
  const [whatsHard, setWhatsHard] = usePersistentState('cr-hard', '');
  const [timeframe,setTimeframe]= usePersistentState('cr-timeframe', '2 years');
  const [results,  setResults]  = usePersistentState('cr-results', null);
  const [sessionHistory,  setSessionHistory]  = usePersistentState('cr-history', []);

  // ─── Handlers ───
  const handleSubmit = useCallback(async () => {
    if (!pathA.trim() || !pathB.trim()) return;
    setError('');
    setResults(null);
    setActiveNarrative('a');

    try {
      const parsed = await callToolEndpoint('contrast-report', {
        pathA: pathA.trim(),
        pathB: pathB.trim(),
        aboutYou: aboutYou.trim() || undefined,
        whatsHard: whatsHard.trim() || undefined,
        timeframe,
        userLocale,
        userCurrency,
        userRegion,
      });

      if (parsed) {
        setResults(parsed);
        const entry = {
          id: 'cr_' + Date.now(),
          date: new Date().toISOString(),
          pathA: pathA.trim().substring(0, 50),
          pathB: pathB.trim().substring(0, 50),
          framed: parsed?.decision_framed?.substring(0, 80) || '',
          preview: (pathA.trim() + ' vs ' + pathB.trim()).slice(0, 40),
          results: parsed,
        };
        setSessionHistory(prev => [entry, ...prev].slice(0, 6));
      } else {
        setError(t('cr_error'));
      }
    } catch (err) {
      // Without this, a backend error threw past the handler — spinner stopped
      // with no result and no message (the bug that hid the stale-model 500).
      setError(err?.message || t('cr_error'));
    }
  }, [pathA, pathB, aboutYou, whatsHard, timeframe, callToolEndpoint, setResults, setSessionHistory, userLocale, userCurrency, userRegion, t]);

  const loadExample = useCallback(() => {
    // Steps through the set rather than re-rolling, and never re-offers the
    // pair already on screen.
    const ex = pickExample('WhichLife', EXAMPLE_DECISIONS.filter(e => e.a !== pathA));
    setPathA(ex.a);
    setPathB(ex.b);
    setAboutYou(ex.about);
    setWhatsHard(ex.hard);
    setTimeframe(ex.timeframe);
    setResults(null);
  }, [pathA, setPathA, setPathB, setAboutYou, setWhatsHard, setTimeframe, setResults]);

  const handleReset = useCallback(() => {
    setPathA('');
    setPathB('');
    setAboutYou('');
    setWhatsHard('');
    setResults(null);
    setError('');
    setActiveNarrative('a');
  }, [setPathA, setPathB, setAboutYou, setWhatsHard, setResults]);

  // ─── Build copyable text ───
  const buildFullText = useCallback(() => {
    if (!results) return '';
    let out = `🔮 ${t('cr_copy_header')}\n`;
    out += `"${results?.decision_framed || `${pathA} vs. ${pathB}`}"\n`;
    out += `${t('cr_copy_timeframe')} ${tfLabel(timeframe)}\n\n`;
    if (results?.path_a) {
      out += `━━ ${t('cr_path_caps')} A: ${results?.path_a?.label} ━━\n\n`;
      out += `${results?.path_a?.narrative?.trimEnd()}…\n\n`;
    }
    if (results?.path_b) {
      out += `━━ ${t('cr_path_caps')} B: ${results?.path_b?.label} ━━\n\n`;
      out += `${results?.path_b?.narrative?.trimEnd()}…\n\n`;
    }
    if (results?.what_to_notice) {
      out += `━━ ${t('cr_copy_what_noticed')} ━━\n\n`;
      out += `${t('cr_copy_trading')} ${results?.what_to_notice?.the_tradeoff}\n\n`;
      out += `${t('cr_copy_reaction')} ${results?.what_to_notice?.watch_your_reaction}\n\n`;
      out += `${t('cr_copy_question')} ${results?.what_to_notice?.a_question_to_sit_with}\n\n`;
    }
    return out + BRAND;
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [results, pathA, pathB, timeframe, t]);

  // Assign refs every render so handlers are always fresh
  handleSubmitRef.current = handleSubmit;
  canSubmitRef.current = !!(pathA.trim() && pathB.trim());

  useRegisterActions(buildFullText(), tool?.title || t('cr_default_title'));

  // ─── Scroll to results ───
  useEffect(() => {
    if (!results || !resultsRef.current) return;
    const t = setTimeout(() => revealSection(resultsRef.current), 200);
    return () => clearTimeout(t);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [results]);

  // ─── Ctrl+Enter submit ───
  useEffect(() => {
    const handler = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'SELECT') return;
      if ((e.ctrlKey || e.metaKey) && e.key === 'Enter' && !loading && canSubmitRef.current) {
        e.preventDefault();
        handleSubmitRef.current?.();
      }
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading]);

  const canSubmit = !loading && pathA.trim() && pathB.trim();

  // ─── Loading state ───
  const LoadingCard = () => (
    <div className={`${c.card} border ${c.border} rounded-2xl p-8 text-center space-y-3`}>
      <span className="animate-spin inline-block text-3xl">{tool?.icon ?? '🔮'}</span>
      <p className={`text-sm font-semibold ${c.text}`}>{t('cr_loading_title')}</p>
      <p className={`text-xs ${c.textMuted}`}>{t('cr_loading_sub')}</p>
    </div>
  );

  // ─── Narrative Section ───
  const NarrativeSection = ({ path, side }) => {
    if (!path) return null;
    const isA = side === 'a';
    return (
      <div className="space-y-4">
        <div className="flex items-center gap-3">
          <div className={`w-1 h-8 rounded-full ${isA ? c.pathABar : c.pathBBar}`} />
          <div>
            <p className={`text-xs font-semibold uppercase tracking-wider ${c.textMuted}`}>
              {t('cr_path_caps')} {side.toUpperCase()}
            </p>
            <h3 className={`text-lg font-bold ${c.text}`}>{path.label}</h3>
          </div>
        </div>
        <div className={`${isA ? c.pathABg : c.pathBBg} ${isA ? c.pathABorder : c.pathBBorder} border rounded-2xl p-6 sm:p-8`}>
          <p
            className={`text-sm sm:text-base ${c.text} leading-[1.85] whitespace-pre-wrap`}
            style={{ fontFamily: 'Georgia, "Times New Roman", serif' }}>
            {path.narrative?.trimEnd()}…
          </p>
        </div>
      </div>
    );
  };

  // ════════════════════════════════════════════════════════════
  // RENDER
  // ════════════════════════════════════════════════════════════
  return (
    <div className={`space-y-4 ${c.text}`}>

      {/* ─── Standard header card ─── */}
      <div className={`${c.card} border ${c.border} rounded-xl shadow-sm px-5 pt-2.5 pb-5`}>
        <div className="pb-3 mb-4 border-b border-zinc-500">
          <div className="flex items-start justify-between gap-3">
            <div>
              {/* PF-30 — the wrapper already prints the name as the page <h1>. */}
              <p className={`text-base ${c.textSecondary}`}>
                <span className="me-2 text-lg">{tool?.icon ?? '🔮'}</span>{t('cr_tagline')}
              </p>
              <button onClick={loadExample} disabled={loading} style={{ backgroundColor: (tool?.headerColor ?? '#888888') + '80' }} className="mt-2 px-4 py-2 rounded-full text-sm font-semibold border border-black/25 text-zinc-900 shadow-sm hover:brightness-105 hover:shadow transition disabled:opacity-40 whitespace-nowrap">✨ {t('try_example')}</button>
            </div>
            {(results || pathA.trim() || pathB.trim()) && (
              <button onClick={handleReset} className={`${c.btnSecondary} px-3 py-1.5 rounded-lg text-xs font-bold flex-shrink-0`}>
                ↺ {t('start_over')}
              </button>
            )}
          </div>
        </div>

        {/* ─── Input form — always visible ─── */}
        <div className="space-y-5">

          {/* Path A */}
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <div className={`w-1 h-5 rounded-full ${c.pathABar}`} />
              <label className={`text-sm font-semibold ${c.text}`}>
                {t('cr_patha_label')} <span className={c.required}>*</span>
              </label>
            </div>
            <p className={`text-xs ${c.textMuted} -mt-1`}>{t('cr_path_help')}</p>
            <textarea
              value={pathA}
              onChange={e => setPathA(e.target.value)}
              placeholder={t('cr_patha_ph')}
              rows={2}
              maxLength={400}
              className={`w-full px-4 py-3 rounded-xl text-sm border ${c.input} resize-none outline-none`}
            />
          </div>

          {/* Path B */}
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <div className={`w-1 h-5 rounded-full ${c.pathBBar}`} />
              <label className={`text-sm font-semibold ${c.text}`}>
                {t('cr_pathb_label')} <span className={c.required}>*</span>
              </label>
            </div>
            <p className={`text-xs ${c.textMuted} -mt-1`}>{t('cr_path_help_b')}</p>
            <textarea
              value={pathB}
              onChange={e => setPathB(e.target.value)}
              placeholder={t('cr_pathb_ph')}
              rows={2}
              maxLength={400}
              className={`w-full px-4 py-3 rounded-xl text-sm border ${c.input} resize-none outline-none`}
            />
          </div>

          {/* About you */}
          <div className="space-y-2">
            <label className={`text-sm font-semibold ${c.text}`}>
              {t('cr_about_label')}{' '}
              <span className={`font-normal ${c.textMuted}`}>{t('optional')}</span>
            </label>
            <p className={`text-xs ${c.textMuted} -mt-1`}>{t('cr_about_help')}</p>
            <textarea
              value={aboutYou}
              onChange={e => setAboutYou(e.target.value)}
              placeholder={t('cr_about_ph')}
              rows={2}
              maxLength={400}
              className={`w-full px-4 py-3 rounded-xl text-sm border ${c.input} resize-none outline-none`}
            />
          </div>

          {/* What's hard */}
          <div className="space-y-2">
            <label className={`text-sm font-semibold ${c.text}`}>
              {t('cr_hard_label')}{' '}
              <span className={`font-normal ${c.textMuted}`}>{t('optional')}</span>
            </label>
            <p className={`text-xs ${c.textMuted} -mt-1`}>{t('cr_hard_help')}</p>
            <textarea
              value={whatsHard}
              onChange={e => setWhatsHard(e.target.value)}
              placeholder={t('cr_hard_ph')}
              rows={2}
              maxLength={400}
              className={`w-full px-4 py-3 rounded-xl text-sm border ${c.input} resize-none outline-none`}
            />
          </div>

          {/* Timeframe */}
          <div className="space-y-2">
            <label className={`text-sm font-semibold ${c.text}`}>
              <span className="me-1.5">{tool?.icon ?? '🔮'}</span> {t('cr_howfar')}
            </label>
            {/* The chips carried flex-1 with no flex parent, so they were plain
                inline-blocks: no gap between them, and butted up against the end
                of the label because space-y only spaces block siblings. */}
            <div className="flex gap-2">
              {TIMEFRAME_OPTIONS.map(opt => (
                <button
                  key={opt.id}
                  onClick={() => setTimeframe(opt.id)}
                  className={`flex-1 border rounded-xl py-2 text-sm font-medium text-center transition-all duration-150 ${timeframe === opt.id ? c.chipActive : c.chipInactive}`}>
                  {t(opt.labelKey)}
                </button>
              ))}
            </div>
          </div>

          <button title={t('cmd_enter')}
          onClick={handleSubmit} data-print-keep disabled={loading || !canSubmit}
          className={`relative w-full ${(!canSubmit) ? c.btnIdle : c.btnPrimary} py-3 rounded-xl font-semibold text-sm shadow-sm
            disabled:cursor-not-allowed transition-all duration-200 flex items-center justify-center gap-2 min-h-[48px]`}>
          {loading
            ? <><span className="animate-spin inline-block">{tool?.icon ?? '🔮'}</span> {t('cr_writing')}</>
            : <><span>{tool?.icon ?? '🔮'}</span> {t('cr_show_both')}</>}
          {!loading && (
            <kbd aria-hidden="true"
              className="hidden sm:flex items-center absolute end-3 top-1/2 -translate-y-1/2 px-1.5 py-0.5 rounded border border-white/30 bg-white/15 text-[10px] font-bold tracking-wide">
              ⌘↵
            </kbd>
          )}
          </button>

          {error && (
            <div className={`${c.danger} border rounded-xl p-4 text-sm flex items-center gap-2`}>
              <span>⚠️</span> {error}
            </div>
          )}

          {/* Routing, below the form rather than above it. Good routing put in
              front of an empty form is an exit ramp before the entrance; here it
              is found by somebody who has read the questions and recognised that
              theirs is the other problem. */}
          <p className={`text-xs text-center ${c.textMuted} pt-1`}>
            {t('cr_xref_pre')}{' '}
            <a href="/DecisionCoach" className={linkStyle}>🧠 {t('cr_xref_decisioncoach')}</a>{' '}
            {t('cr_xref_decisioncoach_after')}
          </p>
        </div>
      </div>

      {/* Streaming Progress */}
      {loading && <LoadingCard />}

      {/* ═══════════════════════════════════════════════════════
          RESULTS
          ═══════════════════════════════════════════════════════ */}
      {results && (
        <div data-copy-results ref={resultsRef} className="scroll-mt-24 space-y-6">

          {/* Decision framed */}
          {results?.decision_framed && (
            <div className="text-center py-2">
              <p className={`text-xs font-semibold uppercase tracking-wider ${c.textMuted} mb-2`}>{t('cr_the_decision')}</p>
              <p className={`text-base font-medium italic ${c.text} max-w-md mx-auto`}>
                "{results?.decision_framed}"
              </p>
              <p className={`text-xs ${c.textMuted} mt-1`}>{t('cr_from_now', { tf: tfLabel(timeframe) })}</p>
            </div>
          )}

          {/* How to read this. It goes before either narrative, because the
              mechanism of this tool is not "here is your future" — it is that
              reacting to a lived scene is easier than reasoning about an
              abstract choice, and the parts that feel WRONG are information
              too. Vividness without this line is just a confident guess. */}
          {results?.how_to_read && (
            <p className={`text-xs ${c.textMuted} text-center max-w-md mx-auto`}>{results.how_to_read}</p>
          )}

          {/* Narrative tabs */}
          <div className={`flex border-b ${c.border}`}>
            <button
              onClick={() => setActiveNarrative('a')}
              className={`flex-1 py-3 text-sm font-medium text-center transition-all duration-150 flex items-center justify-center gap-2
                ${activeNarrative === 'a'
                  ? `${c.pathAAccent} border-b-2 ${c.pathATabBorder}`
                  : c.textMuted}`}>
              <div className={`w-2 h-2 rounded-full ${c.pathABar}`} />
              {results?.path_a?.label || t('cr_patha_label')}
            </button>
            <button
              onClick={() => setActiveNarrative('b')}
              className={`flex-1 py-3 text-sm font-medium text-center transition-all duration-150 flex items-center justify-center gap-2
                ${activeNarrative === 'b'
                  ? `${c.pathBAccent} border-b-2 ${c.pathBTabBorder}`
                  : c.textMuted}`}>
              <div className={`w-2 h-2 rounded-full ${c.pathBBar}`} />
              {results?.path_b?.label || t('cr_pathb_label')}
            </button>
          </div>

          {/* Active narrative */}
          <div>
            {activeNarrative === 'a' && <NarrativeSection path={results?.path_a} side="a" />}
            {activeNarrative === 'b' && <NarrativeSection path={results?.path_b} side="b" />}
          </div>

          {/* What I noticed */}
          {results?.what_to_notice && (
            <div className="space-y-4">
              <div className={`flex items-center gap-4 py-2`}>
                <div className={`flex-1 border-t ${c.border}`} />
                <span className={`text-xs font-semibold uppercase tracking-wider ${c.textMuted}`}>{t('cr_what_notice')}</span>
                <div className={`flex-1 border-t ${c.border}`} />
              </div>

              {results?.what_to_notice?.the_tradeoff && (
                <div className={`${c.card} border ${c.border} rounded-2xl p-5`}>
                  <p className={`text-xs font-semibold uppercase tracking-wider ${c.textMuted} mb-2 flex items-center gap-1.5`}>
                    <span>⚖️</span> {t('cr_the_tradeoff')}
                  </p>
                  <p className={`text-sm ${c.text} leading-relaxed`}>{results?.what_to_notice?.the_tradeoff}</p>
                </div>
              )}

              {results?.what_to_notice?.watch_your_reaction && (
                <div className={`${c.cardAlt} rounded-2xl p-5`}>
                  <p className={`text-xs font-semibold uppercase tracking-wider ${c.textMuted} mb-2 flex items-center gap-1.5`}>
                    <span>👀</span> {t('cr_watch_reaction')}
                  </p>
                  <p className={`text-sm ${c.text} leading-relaxed`}>{results?.what_to_notice?.watch_your_reaction}</p>
                </div>
              )}

              {results?.what_to_notice?.a_question_to_sit_with && (
                <div className={`${c.cardAlt} border ${c.border} rounded-2xl p-6 text-center`}>
                  <p className={`text-xs font-semibold uppercase tracking-wider ${c.textMuted} mb-3`}>
                    {t('cr_question_sit_with')}
                  </p>
                  <p className={`text-base italic ${c.text} leading-relaxed max-w-md mx-auto`}>
                    "{results?.what_to_notice?.a_question_to_sit_with}"
                  </p>
                </div>
              )}
            </div>
          )}

          {/* Cross-references */}
          <div className={`${c.cardAlt} border ${c.border} rounded-xl p-4`}>
            <p className={`text-[10px] font-bold ${c.textMuted} uppercase mb-2`}>🔗 {t('cr_related')}</p>
            <div className="flex flex-wrap gap-3">
              <a href="/BeliefStressTest" className={`text-xs ${linkStyle}`}>🧪 {t('cr_xref_belief')}</a>
              <a href="/AlternatePath" className={`text-xs ${linkStyle}`}>🔀 {t('cr_xref_alternate')}</a>
            </div>
          </div>

          {/* AI disclaimer */}
          <div className={`p-4 rounded-xl text-center ${c.cardAlt}`}>
            <p className={`text-xs ${c.textMuted}`}>🔮 {t('cr_disclaimer')}</p>
          </div>
        </div>
      )}

      {/* ─── History ─── */}
      {sessionHistory.length > 0 && (
        <div className={`p-4 rounded-2xl border ${c.border} ${c.cardAlt}`}>
          <div className="flex items-center gap-2">
            <button onClick={() => setShowHistory(!showHistory)} className="flex items-center gap-2 text-start flex-1">
              <span>📋</span>
              <span className={`text-sm font-bold ${c.text} flex-1`}>{t('cr_past_decisions')}</span>
              <span className={`text-xs ${c.textMuted}`}>{sessionHistory.length}</span>
              <Caret open={showHistory} />
            </button>
            {showHistory && (
              <button
                onClick={() => { setSessionHistory([]); setShowHistory(false); }}
                className={`text-xs ${c.deleteTxt} transition-colors ms-2`}>
                {t('cr_clear_all')}
              </button>
            )}
          </div>
          {showHistory && (
            <div className="mt-3 space-y-2">
              {sessionHistory.map(entry => (
                <div key={entry.id} className={`rounded-xl border ${c.border} ${c.card} p-3 flex items-center gap-3`}>
                  <span className="text-lg">🔮</span>
                  <div className="flex-1 min-w-0">
                    <div className={`text-xs ${c.text} truncate`}>
                      <span className={c.pathAAccent}>A:</span> {entry.pathA}
                    </div>
                    <div className={`text-xs ${c.text} truncate`}>
                      <span className={c.pathBAccent}>B:</span> {entry.pathB}
                    </div>
                    <div className={`text-xs ${c.textMuted} mt-0.5`}>
                      {(() => {
                        try {
                          const d = new Date(entry.date);
                          const diff = Math.floor((new Date() - d) / 86400000);
                          return diff === 0 ? t('cr_today') : diff === 1 ? t('cr_yesterday') : diff < 7 ? t('cr_days_ago', { count: diff }) : d.toLocaleDateString(userLocale || 'en-US', { month: 'short', day: 'numeric' });
                        } catch { return ''; }
                      })()}
                    </div>
                  </div>
                  <button
                    onClick={() => {
                      setResults(entry.results);
                      setPathA(entry.pathA);
                      setPathB(entry.pathB);
                      setShowHistory(false);
                    }}
                    className={`px-3 py-1.5 rounded-lg text-xs font-bold ${c.btnSecondary}`}>
                    {t('cr_view')}
                  </button>
                  <button
                    onClick={() => setSessionHistory(prev => prev.filter(e => e.id !== entry.id))}
                    className={`text-xs ${c.deleteTxt} transition-colors px-1`}
                    aria-label={t('cr_delete_entry')}>
                    ✕
                  </button>
                </div>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
};

WhichLife.displayName = 'WhichLife';

export default WhichLife;
